### PR TITLE
viantOrtbBidAdapter': deals support

### PR DESCRIPTION
**Pull request by skapoorViant**
## Type of change
- [x] Feature

## Description of change
Added pmp deals json in final request created by viantOrtbBidAdapter.

### CODE REVIEW

**Comment by patmmccann** [comment]
This is very interesting, please also support the standard location on the imp object though

**Comment by skapoorViant** [comment]
> This is very interesting, please also support the standard location on the imp object though

@patmmccann I fixed the rest code changes from my side, but please let me know if there's something from my side I would need to do for duplicated code check?

**Comment by patmmccann** [comment]
Duplicated code very minor, safe to ignore or fix if you like and prefer to not have the warning, I marked draft because you didn't have any tests and you didn't support the standard location for the deals object on the ortb2Imp part of the request

**Comment by patmmccann** [comment]
Adding some detail here, a publisher should be able to define a pmp like this https://docs.prebid.org/dev-docs/adunit-reference.html#first-party-data

 ```pbjs.addAdUnits({
    code: "test-div",
    mediaTypes: {
        banner: {
            sizes: [[300,250]]
        }
    },
    ortb2Imp: {
             "pmp": {
                "private_auction": 0,
                "deals": [
                    {
                        "id": "5678",
                        "bidfloor": 1.75,
                        "bidfloorcur": "USD",
                        "wseat": [
                            "16"
                        ],
                        "at": 3
                    },
                    {
                        "id": "1234",
                        "bidfloor": 2,
                        "bidfloorcur": "USD",
                        "wseat": [
                            "3539"
                        ],
                        "at": 1
                    },
                .....
    // ...
});`````

**Comment by skapoorViant** [comment]
> Adding some detail here, a publisher should be able to define a pmp like this https://docs.prebid.org/dev-docs/adunit-reference.html#first-party-data ; not just via your adapter parameters. It is a requirement you support the standard openrtb way of forming a bid request when you provide a parameter. The most frequent publisher complaint about prebid is bidder parameters having redundant implementations of the same information
> 
> ```
>    code: "test-div",
>    mediaTypes: {
>        banner: {
>            sizes: [[300,250]]
>        }
>    },
>    ortb2Imp: {
>             "pmp": {
>                "private_auction": 0,
>                "deals": [
>                    {
>                        "id": "5678",
>                        "bidfloor": 1.75,
>                        "bidfloorcur": "USD",
>                        "wseat": [
>                            "16"
>                        ],
>                        "at": 3
>                    },
>                    {
>                        "id": "1234",
>                        "bidfloor": 2,
>                        "bidfloorcur": "USD",
>                        "wseat": [
>                            "3539"
>                        ],
>                        "at": 1
>                    },
>                .....
>    // ...
> });`````
> ```

@patmmccann I am doing the changes based on your comment, but I do see the same json used by pubmatic adapter. Please check the link: [pubmatic](https://github.com/prebid/Prebid.js/blob/ad2af8f06a144efc483300fb4a2b2e448357c586/modules/pubmaticBidAdapter.js#L598)
Is prebid enforcing this change for all the adapters to standardize the adUnits?

**Comment by skapoorViant** [comment]
@patmmccann I have made the changes and added test case for that. Please review it.

**Comment by skapoorViant** [comment]
@patmmccann Could you please review it again at your earliest convenience? It is currently a blocker for our team and needs to be merged as soon as possible.

**Comment by patmmccann** [comment]
@pm-harshad-mane @jlquaccia @pm-manasi-moghe please see discussion above

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
@skapoorviant looks great! Please document

**Pull request merged**
