### PR TITLE
PulsePoint Bid Adapter: Support for first party eid data

### PR DESCRIPTION
**Pull request by anand-venkatraman**
## Type of change
- [x] Feature in PulsePoint Adapter

### CODE REVIEW

**Comment by patmmccann** [comment]
This is not following a convention on how a publisher might specify an eid. They would specify it like this 

https://docs.prebid.org/dev-docs/modules/userId.html#pubprovided-configuration

**Review by patmmccann — CHANGES_REQUESTED** [review]
What's wrong with https://docs.prebid.org/dev-docs/modules/userId.html#pubprovided-configuration ? 

Is there any documentation or examples of publishers using this additionalEid you are reading from?

**Comment by anand-venkatraman** [comment]
@patmmccann - thanks for pointing that out, I have refactored our adapter to use the generic `userIdAsEids` to take all `eids`.

**Comment by patmmccann** [comment]
Thanks @anand-venkatraman ; please link a docs repo pull indicating your change in id support to 'all' but these changes LGTM

**Review by patmmccann — APPROVED** [review]

**Comment by anand-venkatraman** [comment]
Docs repo changes have been made - https://github.com/prebid/prebid.github.io/pull/3689

**Pull request merged**
