### PR TITLE
vdo.ai bidder adapter

### PR DESCRIPTION
**Pull request by cpuBird**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: 'vdo.ai',
  params: {
    placementId: 'newsdv77'
  }
}
```

### CODE REVIEW

**Comment by cpuBird** [comment]
Hey @GLStephen, Just wanted to hear your review on this pull request.

**Comment by GLStephen** [comment]
@cpuBird I believe the manner in which you are loading external scripts is in violation of the external script policy. Can you explain what you are trying to do with the loadExternalScript call?

The Policy:
https://github.com/prebid/prebid-js-external-js-template#policy

Also, your sample params are not returning bids with which to validate the adapter is working.

Correct the second and provide some info on the first and we'll reevaluate.

**Comment by cpuBird** [comment]
Hi @GLStephen , I can see that we haven't used loadExternalScript call anywhere in our code. Can you send me any screenshot of the code where you have seen it. And also I've fixed the sample params from our end.

**Comment by GLStephen** [comment]
@cpuBird I think I had a few modules crossed up, will verify today

**Comment by GLStephen** [comment]
@cpuBird I'm still getting a noBid from your end, given that it's a new adapter I'd like to verify that it works before approving it. I determined it was another adapter raising the external script warning.

**Comment by cpuBird** [comment]
Hi @GLStephen, 
Sorry for the late response. You can now test the adapter and it will give sample bids as expected.

**Comment by GLStephen** [comment]
@cpuBird I am still not seeing bids with your test params and we cannot accept the bidder without functional test params, this is for myself to ensure quality as well as future users to ensure they have params they can use to test their own installs.

**Comment by cpuBird** [comment]
@GLStephen Please test now as I've enabled mock bidder on that placement.

**Comment by GLStephen** [comment]
LGTM

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/1841

**Pull request merged**
