### PR TITLE
eplanning bid adapter - add video auction support

### PR DESCRIPTION
**Pull request by fndigrazia**
## Type of change
- [ x ] Feature

## Description of change
Adding support for video auction in E-Planning adapter

ndigrazia@e-planning.net
- [ x] official adapter submission

### CODE REVIEW

**Comment by sebaperez** [comment]
Hi @gwhigs, it looks like that CircleCI Pipeline suite haven't run due of a set up problem. Is it possible to force them to run manually?

**Comment by gwhigs** [comment]
I don't appear to have permission to rerun jobs in CircleCI. Perhaps @jsnellbaker?

Re: https://app.circleci.com/pipelines/github/prebid/Prebid.js/13216

**Comment by jsnellbaker** [comment]
I am unable to rerun the job either.  I've not seen this error here before.  @fndigrazia could you try to resync/rebase with master just to ensure you have all the project files?  That may hopefully reset things for the circleCI job.

**Comment by fndigrazia** [comment]
Hi @jsnellbaker
I ran a git rebase just now and it returned:
Current branch master is up to date.

**Comment by fndigrazia** [comment]
I can delete this PR and create a new one to test if it works

**Pull request closed without merging**
