### PR TITLE
Add Relaido Adapter

### PR DESCRIPTION
**Pull request by relaido**
## Type of change
- [x] New bidder adapter

## Description of change
New adapter

- test parameters for validating bids
```
{
  bidder: 'relaido',
  params: {
    placementId: '9900'
  }
}
```

- contact email of the adapter’s maintainer: video-dev@cg.relaido.co.jp
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/1917

### CODE REVIEW

**Comment by relaido** [comment]
Hi @Fawke , thanks for the review.
event listener removed.

**Comment by Fawke** [comment]
@relaido

Thanks for making the change. But, when I'm trying to load your banner ad and video ad following the example you shared in the md file, and plug those values in the [hello_world](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html) example, am getting this error. 

Screenshot 2020-04-09 at 5 40 24 PM

I think your `isBidRequestValid` function is returning false because it doesn't find the uuid in localStorage. Can you have a look please?

**Comment by relaido** [comment]
@Fawke

The first access results in an error because there is no uuid.
Since uuid is registered after `UserSync`, it succeeds from the second time on.

**Comment by Fawke** [comment]
@relaido 

I put your adapter js file through a debugger and made some observations:

1. In the function `setUuid(e)`, this `if condition` (`(e.data && e.data.relaido_uuid)`) is always returning a false. It maybe because the value of `e.data` is a `string`.

2. In your `getUserSyncs` function, you need to have a check in place like this: `syncOtions.iframeEnabled`. Please take a look at a similar implementation of the `appnexus` or the `rubicon` adapter.

3. Also, in the same function `getUserSyncs`, the parameter `serverResponses` is coming empty. So, you might better wanna put a check in place, something like: `severResponses.length > 0`

(serverResponses is empty because no auction is taking place because the function, `isBidRequestValid` is returning a false)

Also, are there any particular reasons for setting the localStorage value in getUserSyncs function? What if the publisher doesn't allow userSync? What if the pub only allows image sync and not iframe sync?



> Since uuid is registered after `UserSync`, it succeeds from the second time on.

What do you mean second time on? You mean if I refresh the page again? A bit confused, because your `isBidRequestValid` function is always returning a false, leading to no auction taking place for your bidder. So, how will it succeed the second time on?

**Comment by relaido** [comment]
@Fawke

1.
> this if condition ((e.data && e.data.relaido_uuid)) is always returning a false

Sometimes returns true. e.data can also send objects.

> It maybe because the value of e.data is a string.

You're right. Check with isPlainObject.

2.
> In your getUserSyncs function, you need to have a check in place like this: syncOtions.iframeEnabled.

Fixed. However, some people have said this.
https://github.com/prebid/Prebid.js/pull/5017#discussion_r399485438

3.
> So, you might better wanna put a check in place, something like: severResponses.length > 0

Fixed.

---

> Also, are there any particular reasons for setting the localStorage value in getUserSyncs function?

I want to save uuid in localStorage at the first access.
When the page is updated again, the auction is performed using the uuid stored in localStorage.

> What if the publisher doesn't allow userSync?

Unfortunately, no auction is possible.

> What if the pub only allows image sync and not iframe sync?

Auction cannot be done here as well.

---

> What do you mean second time on?

Is to visit the same page again.
It is the same as refreshing the page.

> You mean if I refresh the page again?

The auction will be held because uuid is stored in localStorage.

> A bit confused, because your isBidRequestValid function is always returning a false, leading to no auction taking place for your bidder.

Hmm. I can conduct an auction.

> So, how will it succeed the second time on?

Do you allow userSync and iframe sync?
Is relaido_uuid stored in localStorage?

**Comment by Fawke** [comment]
@relaido 
> Fixed. However, some people have said this.
> [#5017 (comment)](https://github.com/prebid/Prebid.js/pull/5017#discussion_r399485438)

Unfortunately, that's not right. We still need the check in place. The deprecation was for the publisher facing API, but internally, the adapter is still using `iframeEnabled.`

Also, I noticed one thing, when sending a banner response, you are returning a `vast` and overwriting `bidResponse.ad` with your renderer code.

Is this done to overcome some of prebid's limitations?

Rest of things look okay to me.

**Comment by relaido** [comment]
@Fawke

> The deprecation was for the publisher facing API, but internally, the adapter is still using iframeEnabled.

Thanks. understood.

> Is this done to overcome some of prebid's limitations?

Banner could be a safeframe. to overcome that, I pass VASTXML as a parameter.
I referenced this program.
https://github.com/prebid/Prebid.js/blob/master/modules/adgenerationBidAdapter.js#L112-L120

**Comment by relaido** [comment]
@Fawke

doc also please review.
https://github.com/prebid/prebid.github.io/pull/1917

**Pull request merged**
