### PR TITLE
Qwarry bid adapter

### PR DESCRIPTION
**Pull request by pro-nsk**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by smenzer** [comment]
@pro-nsk you should not be including the `yarn.lock` file in this PR. please remove the file before we can review.

**Comment by pro-nsk** [comment]
> @pro-nsk you should not be including the `yarn.lock` file in this PR. please remove the file before we can review.

Hello. Fixed

**Review by musikele — CHANGES_REQUESTED** [review]
Please add more tests to the MR - we require at least 80% of line coverage, and now it is at 77.7%.

**Review by musikele — COMMENTED** [review]
Next time please give more details in the PR description. This one is basically empty

**Comment by musikele** [comment]
@pro-nsk we also need the docs PR to add qwarry to prebid website: https://github.com/prebid/prebid.github.io/

**Comment by pro-nsk** [comment]
> 
> 
> Please add more tests to the MR - we require at least 80% of line coverage, and now it is at 77.7%.

Hello. Fixed

**Comment by pro-nsk** [comment]
> 
> 
> @pro-nsk we also need the docs PR to add qwarry to prebid website: https://github.com/prebid/prebid.github.io/

Thanks. I've created new PR in https://github.com/prebid/prebid.github.io/

**Review by musikele — APPROVED** [review]
LGTM

**Pull request merged**
