### PR TITLE
Feature/adapter

### PR DESCRIPTION
**Pull request by sourabhg**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by sourabhg** [comment]
@sumit116 : Thanks for the update. I have added few test cases to increase the coverage beyond 80%. I will notify once the issue with our endpoint gets resolved.

**Comment by sourabhg** [comment]
@sumit116 : All the changes have been made as suggested and endpoint issue is resolved now.

**Comment by sumit116** [comment]
@sourabhg, you circleci and LGTM builds have failed. Can you check them?

**Comment by sourabhg** [comment]
@sumit116: I am not able to see any specific reasons in circleCI, could you please help

**Comment by pm-harshad-mane** [comment]
Hello @sumit116 ,

Looks like the issue is not with the new code, can you please re-run the CI job?
I had this issue before, I just re-run the CI job and it worked.

**Comment by sumit116** [comment]
> Hello @sumit116 ,
> 
> Looks like the issue is not with the new code, can you please re-run the CI job?
> I had this issue before, I just re-run the CI job and it worked.

I re-ran it many times, but it still giving me timeout error. Will have to check this more if its an issue with the endpoint or may something else.

**Comment by bretg** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/1515

**Comment by pm-harshad-mane** [comment]
Hello @sourabhg ,

Can you pull the upstream/master and try again?

**Comment by sourabhg** [comment]
@sumit116 @pm-harshad-mane : I did merge upstream master, still Circle CI build is doing a timeout. Any particular solution here ?

**Comment by pm-harshad-mane** [comment]
Hello @sourabhg ,

Please follow https://github.com/prebid/Prebid.js/pull/4409 this one fixes the Adagio test cases,   once these changes are merged, you can pull the master and then you should be able to pass the CI.

**Comment by sourabhg** [comment]
@sumit116 : I see all checks have passed now after the fix on the upstream master. Could you merge ?

**Comment by sumit116** [comment]
@sourabhg, I am still getting the `CORS` while hitting your adapter's bid endpoint.

`Access to XMLHttpRequest at 'https://prebid.deepintent.com/prebid' from origin 'http://localhost:9999' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

You need to resolve it to merge this PR because only then I can test the request and response of the endpoint. To test, can you check what is `Access-Control-Allow_origin` set to in your server file?

**Comment by sourabhg** [comment]
@sumit116 : we have resolved the issue for CORS, you should see the ad returning on hello world page. 
Screenshot 2019-11-06 at 12 20 41 PM

**Pull request merged**
