### PR TITLE
Code improvement for trustx adapter

### PR DESCRIPTION
**Pull request by PWyrembak**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change

Changed default price type from gross to net

- paul@trustx.org
- [x] official adapter submission

### CODE REVIEW

**Comment by PWyrembak** [comment]
Hey team,
any chance to get this merged soon?

**Comment by PWyrembak** [comment]
Hi @matthewlane!
We found a bug in TrustX adapter code compatible with Prebid v0.31 and we need to fix it since we have a significant amount of publishers using prebid v0.31 (not 1.0). Could you please advise on how do we proceed? Should we make a new pull request?

**Comment by matthewlane** [comment]
@PWyrembak Yes, you can make a new pull request against the [legacy branch](https://github.com/prebid/Prebid.js/tree/legacy)

**Comment by PWyrembak** [comment]
Thanks for answering @matthewlane. We made a new pull request against both the legacy branch https://github.com/prebid/Prebid.js/pull/1981 
and the master 1.0 branch https://github.com/prebid/Prebid.js/pull/1979.

**Pull request merged**
