### PR TITLE
GumGum Bid Adapter: add support for video.plcmt

### PR DESCRIPTION
**Pull request by MartinGumGum**
- [ x] Feature

## Description of change
 Add vplcmt property to the result object if plcmt is available

### CODE REVIEW

**Comment by MartinGumGum** [comment]
Hi @ChrisHuie, a couple of the last PRs were failing on Circleci. Is it a known issue? I do not have big changes and when I run locally it passes all the unit tests(before opening PR). Do you have any information on this?

**Comment by ChrisHuie** [comment]
> Hi @ChrisHuie, a couple of the last PRs were failing on Circleci. Is it a known issue? I do not have big changes and when I run locally it passes all the unit tests(before opening PR). Do you have any information on this?

reran and should be good now. A flaky test has started popping up this week it seems.

**Review by patmmccann — DISMISSED** [review]
needs tests

**Comment by MartinGumGum** [comment]
@patmmccann Done

**Comment by MartinGumGum** [comment]
Can someone review this change again?

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
