### PR TITLE
 hadronId user id submodule: force localStorage

### PR DESCRIPTION
**Pull request by jlaso**
## Type of change

- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter   
- [X] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

In order to give visitors a better user experience we have decided to store hadronId in localStorage in order to improve the timing for next website visits. Using that occasion we refactored and cleaned the code a little bit.

### CODE REVIEW

**Comment by patmmccann** [comment]
you're just deleting publisher choice? This appears to be an antifeature?

**Comment by jlaso** [comment]
> you're just deleting publisher choice? This appears to be an antifeature?

I'm sorry, what do you mean by "publisher choice"?

**Comment by patmmccann** [comment]
Publishers currently choose cookie or local storage. You appear to be deleting the configuration opportunity, likely in a way that breaks people who have chosen the former.

**Comment by jlaso** [comment]
Yeah, you're absolutely right looking only at the changes I made, but if you look at the full code you will see that we haven't implemented the cookie system nor the possibility to change the name of the stored value in localStorage.
So, what I am doing in this PR is adapt the documentation to the actual status of the code.
In other words, no matter what the publisher selects in the config we are not using it for storing the hadronId. 
But, if you consider that's not a good practice I will be more than happy to change whatever is needed to follow the rules.

**Comment by patmmccann** [comment]
just to confirm: if someone has the cookie configured and they upgrade to whichever 7.x version this is merged to, they wouldnt need to fix anything for hadron to keep working?

**Comment by jlaso** [comment]
You are right, if someone has cookie configured gonna have exactly the same behaviour with this update, because we were always looking at the backend to get the ID and with cookie configured we will still looking at backend.

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
