### PR TITLE
FreePass Bid Adapter : initial release

### PR DESCRIPTION
**Pull request by czarpino**
## Type of change

- [x] New bidder adapter   

## Description of change

New Bid Adapter from FreePass.

Please the ff parameters to validate the adapter:
```
{
    bidder: 'freepass',
    test: 1
}
```

Contact maintainer at [fp-hbidding@freebit.net](mailto:fp-hbidding@freebit.net)

## Other information

Docs: https://github.com/prebid/prebid.github.io/pull/4495

## Testing with hello_world
Related discussion: https://github.com/prebid/Prebid.js/issues/9712

Due to IP restriction we have prepared a US-based mock server to respond to external requests at `172.104.192.122`. If this is not acceptable, please advice and we will try to prepare for external access to actual bidder service.

To test, please add the ff to your `/etc/hosts`

```
172.104.192.122 bidding-dsp.ad-m.asia
```

### CODE REVIEW

**Review by patmmccann — CHANGES_REQUESTED** [review]
make sure you're passing tests

**Comment by czarpino** [comment]
@patmmccann Thanks for checking. I will look into it!

**Comment by czarpino** [comment]
@patmmccann Thank you for the feedback. All tests should now be passing.

**Comment by czarpino** [comment]
@patmmccann Sorry, if you get a chance, a re-review would be very appreciated. The PR has been updated and tests are now passing 🙏

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
