### PR TITLE
No Bid Adapter: added bidResponse.meta and advertiserDomains

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change
- [x] Feature

## Description of change
Added bidResponse.meta attribute and specifically "advertiserDomains" which is planned to be required in Prebid.js version 5.

- reda.guermas@nobid.io

### CODE REVIEW

**Comment by smenzer** [comment]
can you please get rid of all the extra files in this PR? it should only contain your specific code

**Comment by redaguermas** [comment]
Hello,
This error does not seem to be coming from my code. Do you know what we need to do to pass it?

Thanks

**Comment by ChrisHuie** [comment]
@redaguermas I just reran the test. A recent pr fixes this flaky test so not you.

**Comment by redaguermas** [comment]
@ChrisHuie ,
I removed the IE files. Can you check the test please.

Thanks

**Review by ChrisHuie — APPROVED** [review]

**Comment by ChrisHuie** [comment]
@redaguermas looks good :)

**Pull request merged**
