### PR TITLE
remove superfluous parameter from openx adapter

### PR DESCRIPTION
**Pull request by kkharma**
## Type of change

- [X ] Bugfix

## Description of change
removed unused ee parameter from openx adapter

### CODE REVIEW

**Comment by dbemiller** [comment]
@prebid/openx Is this guy from your team? Do you trust these changes?

No offense meant, but... without a link to a public API doc, someone we know to be connected to OpenX vetting you, or bidder params which we can test with, I'm not super comfortable merging this.

The Prebid core team tries to leave adapter maintenance up to the adapter's owners... but if we blindly approve changes like these, I can imagine malicious contributors sabotaging their competitor's adapter without their knowledge.

Would like feedback on how active others think we should be in this process.

**Comment by kkharma** [comment]
no worries... i work for openx.  is there someone from openx you've worked with in the past on adapter changes?  i can reach out to them.  i'm not sure why this parameter was ever set in the adapter in the first place.

**Comment by dbemiller** [comment]
I'm new to prebid too... but it looks like the prebid/openx group includes @Heray, who I don't recognize... so he'd be my best guess.

**Comment by kkharma** [comment]
unfortunately, they are not an openx employee, and i can't see the prebid/openx group.  is there anyone else i could try?  otherwise, i'll have to ask around internally.

**Comment by dbemiller** [comment]
huh... the git logs show that this file was in the initial commit, so I'm lost here.

Are there OpenX API docs that this adapter is coding against? I googled and found [this page](https://docs.openx.com/Content/developers/ad_request_api/adtagguide_tagapi.html) mentioned the URL `http://delivery_server_domain/w/1.0/jstag`, which looks like it's what the adapter hits.

But if that's the one, then [the API params](https://docs.openx.com/Content/developers/ad_request_api/adtagguide_parameters.html) barely line up with the adapter at all. `ju`, `jr`, etc... many of them aren't listed there. So I get the feeling I'm missing something.

**Comment by dbemiller** [comment]
Actually, although he's not a part of that group, @lntho shows up in the commit logs for #896 , official OpenX support

**Comment by kkharma** [comment]
ah cool... that's someone i recognize.  will follow up...

**Comment by lntho** [comment]
Hello @dbemiller I can confirm this pull request is fine. Is there supposed to be a prebid/openx group? I was the original submitter for the OpenX adapter

**Comment by dbemiller** [comment]
Ok, thanks @lntho. I'll merge this then.

I do see a bunch of `prebid/Adapter` teams in this project... but only about 25 of them--so far fewer than the total number of adapters. A prebid/openx team does exist... but my guess is it's not really maintained. It only includes some original members of the Prebid project.

This is the first I've seen of these, and I don't have permissions to edit them... so I've no idea if they're maintained. I'll ping the people who do, though, and make sure you guys get added.

**Pull request merged**
