### PR TITLE
ParrableIdSystem: Store third-party cookie support status in first-party cookie

### PR DESCRIPTION
**Pull request by icflournoy**
## Type of change
- [x] Other

## Description of change

(First-attempt #6689)

The Parrable backend tests a browser's support of third-party cookies on each request. If the test cookie is stored successfully (third party cookies are supported in the browser) then the cookie may remain up to 24 hours in the browser and be sent along with subsequent requests to our backend. We will not attempt to re-test third-party cookie status if the third-party cookie is received.

This change introduces a small value, to be stored in our compound/composite first-party cookie that retains the state of the browser's third-party cookie support from the last time it was tested. This is beneficial in browsers that don't support third-party cookies where we would otherwise always re-test their third-party cookie support on each request made.

The solution is implemented by storing two additional values in the first-party cookie maintained under prebid. The first is the actual state of third-party cookie support in the browser. This value is returned from our backend systems after the third-party cookie test is complete. The second value is a future unix timestamp (in seconds) that determines when the stored third-party cookie state is no longer valid, and will not be supplied to our backend, thus causing a re-test of the browser's third-party cookie support.

This change is internally facing and only affects our cookie storage layout, and the request/response exchange with our backend systems.

## Other information

* Author @victorigualada

### CODE REVIEW

**Comment by icflournoy** [comment]
@ChrisHuie it looks like the CircleCI 'build' workflow didn't kick off for this new PR either. Same issue as #6689 

We recently setup our own BrowserStack and enabled CircleCI on our fork of Prebid so that we can do some testing before opening a PR here, upstream. This shouldn't have affected your build in any way.

I'll try pushing another commit to the branch in this PR and see what happens. Our CircleCI Prebid.js project won't trigger on a commit to a branch that doesn't have a corresponding PR in our repo.

**Comment by ChrisHuie** [comment]
@icflournoy Thanks for resubmitting! I think this sometimes happens if you are following your repo and not the main Prebid repo in CircleCi. I can kick off the tests manually from my end but looks like I don't have access to edit this commit.

**Comment by icflournoy** [comment]
@ChrisHuie I've added you with "Write" permissions to our Prebid.js fork https://github.com/Parrable/Prebid.js

Let me know if you're able to kick off the tests manually for the `Parrable:parrableIdSystem/PBID-91_thirdPartyCookieSupport` branch.

---

If you're not already aware - GitHub Status Checks (applied on a per-branch level) can be used to enforce certain named status checks to pass on a branch before a PR can be merged. Example from on of our internal repos:
Screen Shot 2021-05-13 at 9 40 42 AM

Something to consider, if this behavior is not easily fixable from CircleCI's side.

**Comment by ChrisHuie** [comment]
@icflournoy I will have to work on this for a vit. Looks like this is a unique situation since I couldn't even automatically kick off the circleci tests like I usually do :/

**Comment by ChrisHuie** [comment]
Reaching out to CircleCi to work with them on a solution for this pr and going forward how to make sure no pr has a way to slip through the tests.

**Comment by ChrisHuie** [comment]
Yay for circleCi tests working now :)

**Comment by msm0504** [comment]
@icflournoy @ChrisHuie Circle CI tests are failing again.

**Comment by victorigualada** [comment]
@ChrisHuie we fixed the problem with our tests, caused by an early expiring cookie. Fix is in the last commit. Can you please rebuild? Thanks!

**Comment by icflournoy** [comment]
It looks like the build is now failing due to some timing on BrowserStack:
> Too long with no output (exceeded 10m0s): context deadline exceeded

**Comment by ChrisHuie** [comment]
@icflournoy circle ci I think was experiencing outages when this was last ran. Just kicked off the tests again

**Comment by icflournoy** [comment]
Thanks @ChrisHuie I see the CircleCI build ran! Friday was not a good day for CircleCI.

I recently re-enabled our CircleCI build for our Prebid fork (around 9:30 this morning). Which, by past evidence, should have prevented your build from running.

**Review by msm0504 — APPROVED** [review]

**Comment by ChrisHuie** [comment]
@icflournoy it looks like the behavior isn't consistent on firefox 72.0 -> https://app.circleci.com/pipelines/github/prebid/Prebid.js/5921/workflows/33f4dd7d-1f09-4bfe-8a46-7abe45d9dddf/jobs/14605

Could you take a look when you get a chance 🙏

**Comment by ChrisHuie** [comment]
@icflournoy yeah there seems to be a decent amount of flakiness with this pr because now i have seen it fail on new chrome, edge, and old firefox. Can you please work on stabilizing this a bit so we don't have to revert it again.

https://app.circleci.com/pipelines/github/prebid/Prebid.js/5966/workflows/a1ddfc16-44b6-4fd6-8b97-1195ebcca7a4/jobs/14698

**Pull request merged**
