### PR TITLE
Prebid auctions

### PR DESCRIPTION
**Pull request by protonate**
@mkendall07 for initial review. Adapters and tests need to be updated still.

### CODE REVIEW

**Comment by nanek** [comment]
This looks like a fairly large change. Can you provide clarity on the goal of this effort? I have some more questions, but before diving too deep, I'd like to understand more. Thanks!

**Comment by mkendall07** [comment]
@nanek 
The ability to "prefetch" demand  with prebid.js has been an often requested feature. We've attempted various approaches to doing this, however, they have all been unsuccessful, largely do to the existing architecture never having a concept of an "auction", it had always used globals to contain all the data about any particular request/response. We have considered this at length and decided the best approach would be to encapsulate all the related data about an auction into an instance variable and conduct our requests/responses inside the instance. This PR is the culmination of finishing that work.

**Comment by nedstankus** [comment]
@mkendall07 This sounds like a great addition.  Do you expect the auction encapsulation to resolve issues with concurrent requests?  I believe the previous prebid-auctions branch was intended to.

**Comment by mkendall07** [comment]
Closing as this isn't ready yet

**Pull request closed without merging**
