### PR TITLE
Zemanta adapter: copy adapter as Outbrain

### PR DESCRIPTION
**Pull request by rokostik**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change

~Hey, this renames the Zemanta adapter to Outbrain.~
EDIT: as discussed bellow in the comments, this is just a copy of the zemanta adapter until v5.0 to preseve backwards compatibility. We will remove the zemanta adapter for v5.0.
When we first made the decision to expose the Zemanta adapter as Outbrain we only supported prebid.js that this with minimal effort with the alias function. But now we also have a server adapter and noticed that it could cause confusion since aliases work a bit differently there so we decided to fully rename both adapters to Outbrain.

- Link to the PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/2847

### CODE REVIEW

**Comment by patmmccann** [comment]
I think this would break existing integrations, do you agree?

If so, please make on the 5.0 branch, expected in May.

**Comment by patmmccann** [comment]
Or maybe you could add outbrain and delete the alias from zemanta on 4, delete zemanta on 5?

**Comment by rokostik** [comment]
Hey @patmmccann thanks for the comment. We currently have one integration still explicitly using zemanta in the configuration and we were planning to coordinate with them to change it until the next release. But I agree with you that it would be better to have both adapters until 5.0 and then have a clean cutoff.

I will prepare the changes as you proposed.

**Comment by rokostik** [comment]
@patmmccann I pushed the changes. Regarding the deletion: do I just prepare a PR with the delete targeting the 5.0 branch or is there anything else to do?

**Comment by patmmccann** [comment]
That's it ty

**Comment by patmmccann** [comment]
I think you may want to remove the alias from the zemanta adapter on this pr

**Comment by rokostik** [comment]
> I think you may want to remove the alias from the zemanta adapter on this pr

Yeah, of course, thanks!

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
