### PR TITLE
Pangle Bid Adapter : initial release

### PR DESCRIPTION
**Pull request by bytedancer-1**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/4823

**Comment by bytedancer-1** [comment]
Update the same parameters, please help to see, no problem to help merge into it

**Comment by Rothalack** [comment]
Here's the errors thrown in the circleci build, not sure if you'd be able to see them or not.

Chrome 116.0.0.0 (Windows 10): Executed 13349 of 13345 (4 FAILED) (45.976 secs / 21.265 secs)
TOTAL: 4 FAILED, 13345 SUCCESS


1) should accept request if placementid and appid is passed
     pangle bid adapter isBidRequestValid
     AssertionError: expected false to equal true
    at Context.<anonymous> (/tmp/_karma_webpack_346388/commons.js:347570:75)

2) should return correct device type: tablet
     pangle bid adapter parseUserAgent
     TypeError: _pangleBidAdapter.spec.getDeviceType is not a function
    at Context.<anonymous> (/tmp/_karma_webpack_346388/commons.js:347624:47)

3) should return correct device type: mobile
     pangle bid adapter parseUserAgent
     TypeError: _pangleBidAdapter.spec.getDeviceType is not a function
    at Context.<anonymous> (/tmp/_karma_webpack_346388/commons.js:347628:47)

4) should return correct device type: desktop
     pangle bid adapter parseUserAgent
     TypeError: _pangleBidAdapter.spec.getDeviceType is not a function
    at Context.<anonymous> (/tmp/_karma_webpack_346388/commons.js:347632:47)


[11:12:39] 'test-all-features-disabled' errored after 2.68 min
[11:12:39] Error: Karma tests failed with exit code 1
    at ChildProcess.<anonymous> (/home/circleci/Prebid.js/gulpfile.js:342:12)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:505:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[11:12:39] 'test' errored after 3.75 min

Exited with code exit status 1

**Comment by bretg** [comment]
@bytedancer-1 - thanks for making the parameter change. And Prebid publishers thank you as well. 

Please remove the ".history/modules" directory from this PR.

**Comment by bytedancer-1** [comment]
@bytedancer-1 Take out the history. Look again, please. Thank you

**Comment by bytedancer-1** [comment]
@Rothalack Repair completed, please help review again

**Review by Rothalack — APPROVED** [review]
Looks good, working in testing for me.

**Pull request merged**
