### PR TITLE
IAS RTD Module: custom adUnitPath mapping

### PR DESCRIPTION
**Pull request by rbarbini-ias**
## Type of change
- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- adds the possibility for the client to explicitly map ad unit paths to slot ids
- updates the maintainer email

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@rbarbini-ias is there by chance a more general ias email or email group we can update as maintainer. We are trying to move away from individual emails used for maintainers since there will always be turnover.

**Comment by rbarbini-ias** [comment]
@ChrisHuie I'm checking internally, I will either add a commit with the new address or answer here shortly.

**Comment by rbarbini-ias** [comment]
@ChrisHuie done.

**Comment by rbarbini-ias** [comment]
@Rothalack done with https://github.com/prebid/prebid.github.io/pull/4084

**Review by Rothalack — APPROVED** [review]
Looks good!

**Pull request merged**
