### PR TITLE
Fix import warning for webpack 5

### LINKED ISSUE #5909: JSON import warning in webpack 5
## Type of issue

bug

## Description

Webpack 5 emits a warning when importing named exports from json files:

```
"WARNING in ../../node_modules/prebid.js/src/secureCreatives.js 15:16-30
Should not import the named export 'EVENTS'.'BID_WON' (imported as 'EVENTS') from default-exporting module (only default export is available soon)"
```

### Expected results
No warnings
### Actual results
A warning coming from src/secureCreatives.js
## Platform details

Prebid 4.13.0, macOS, node 14, webpack 5
## Other information

This is the fix/PR: https://github.com/gpoitch/Prebid.js/pull/1/files
Having some odd trouble with trying to view/PR anything in this repository.

### PR DESCRIPTION
**Pull request by GLStephen**
This PR created on behalf of @gpoitch for https://github.com/prebid/Prebid.js/issues/5909

Fixes #5909

--------------------

Webpack 5 emits a warning when importing named exports from json files:

```
"WARNING in ../../node_modules/prebid.js/src/secureCreatives.js 15:16-30
Should not import the named export 'EVENTS'.'BID_WON' (imported as 'EVENTS') from default-exporting module (only default export is available soon)"
```

### CODE REVIEW

**Comment by GLStephen** [comment]
Fixes #5909

**Comment by GLStephen** [comment]
@gpoitch I can't get this to pass Circle CI, but the failure doesn't look exactly related to this change, can you take a look?

**Comment by gpoitch** [comment]
@GLStephen looks like a timeout.  Restart the build/merge master?

**Comment by GLStephen** [comment]
@gpoitch yes, please do a merge with master and let's try it again

**Comment by gpoitch** [comment]
No dice. Master itself is currently failing but the errors are different.  Seems like a testing issue.

Thanks for opening the PR for me. Just realized my ad blocker was preventing me from doing anything in this repo.

**Comment by DecayConstant** [comment]
Do we know if the the testing issues have been dealt with? I'd like to see this get approved 👍

**Comment by gpoitch** [comment]
passing now

**Pull request merged**
