### PR TITLE
Dianomi Bid adapter: add new bid adapter

### PR DESCRIPTION
**Pull request by DianomiJH**
## Type of change

- [x] New bidder adapter   

## Description of change

New bid adapter for Dianomi plc.

- test parameters for validating bids

#### Native example
```js
var adUnits = [
    code: 'your-native-container-id',
    mediaTypes: {
        native: {
            image: {
                required: false,
                sizes: [100, 50]
            },
            title: {
                required: false,
                len: 140
            },
            sponsoredBy: {
                required: false
            },
            clickUrl: {
                required: false
            },
            body: {
                required: false
            },
            icon: {
                required: false,
                sizes: [50, 50]
            }
        }
    },
    bids: [{
        bidder: 'dianomi',
        params: {
            smartadId: 9607
        }
    }]
];
```

#### Banner example
```js
var adUnits = [
    code: 'your-banner-container-id',
    mediaTypes: {
      banner: {
        sizes: [[300, 250]]
      } 
    },
    bids: [{
        bidder: 'dianomi',
        params: {
            smartadId: 9607
        }
    }]
];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
eng@dianomi.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/3825

### CODE REVIEW

**Review by Fawke — COMMENTED** [review]
Hi @DianomiJH,

While running the unit tests locally, I see quite a few tests are failing. Can you run this command, `gulp test` locally and check if all tests pass?

I see the following messages when I run the tests.

```(javascript)
LOG: '[Failure f2b4b2dac1-21] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids price floors should add correct floor values'): 0 requests'
LOG: '[Failure f2b4b2dac1-22] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids multiple media types should use all configured media types for bidding'): 0 requests'
LOG: '[Failure f2b4b2dac1-23] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids banner should convert sizes to openrtb format'): 0 requests'
LOG: '[Failure f2b4b2dac1-24] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids video should pass video mediatype config'): 0 requests'
LOG: '[Failure f2b4b2dac1-25] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids native assets should set correct asset id'): 0 requests'
LOG: '[Failure f2b4b2dac1-26] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids native assets should add required key if it is necessary'): 0 requests'
LOG: '[Failure f2b4b2dac1-27] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids native assets should map img and data assets'): 0 requests'
LOG: '[Failure f2b4b2dac1-28] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids native assets should utilise aspect_ratios'): 0 requests'
LOG: '[Failure f2b4b2dac1-29] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids native assets should not throw error if aspect_ratios config is not defined'): 0 requests'
LOG: '[Failure f2b4b2dac1-30] XHR mock state after failure (for test 'Dianomi adapter buildRequests bids native assets icon/image sizing should flatten sizes and utilise first pair'): 0 requests'
```

**Comment by DianomiJH** [comment]
Hi @Fawke , running the tests locally and they are all passing: 
image
i have made a _very_ small change to a couple of the tests, but nothing that should have changed the results here. Can you please advise?

**Comment by Fawke** [comment]
I think in Prebid v7, we can't get reference to the ortb2 object from `getConfig`. It's now part of the bidrequest object. Know more [here](https://github.com/prebid/prebid.github.io/pull/3779/files#diff-e1ef37cf74a266c9e6bc7a3a96b6ad183160d17b0a7b13cddc4cf9163e4d0e0fR65)

I think the test are passing for you locally because you haven't pulled in the latest changes from master after Prebid v7 release. Please pull in the master branch and then run the test, you'd see them fail. To fix them, pull the ortb2 info from bidrequest object.

**Comment by DianomiJH** [comment]
Hi @Fawke , Thanks for the info, i totally missed the v7 release :) i've updated the code and tests to work with the new version. Let me know if you need anything else

**Review by Fawke — APPROVED** [review]

**Pull request merged**
