### PR TITLE
Add the NginAdAdapter, and bidmanager hooks

### PR DESCRIPTION
**Pull request by nginadfoundation**
The adapter for NginAd OpenRTB Ad Server version 1.6.8

### CODE REVIEW

**Comment by mkendall07** [comment]
@nginadfoundation 

Thanks for PR. Can you please remove the `build/*` files? Thanks

**Comment by mkendall07** [comment]
@nginadfoundation 
Could you also provide parameters to receive a test bid to validate the response?

**Comment by nginadfoundation** [comment]
Hi, I will review the requests and get back in the next day.

**Comment by nginadfoundation** [comment]
I will create a new pull request now.

**Pull request closed without merging**
