### PR TITLE
Avocet bid adapter

### PR DESCRIPTION
**Pull request by scritchley**
## Type of change
- [x] New bidder adapter 

## Description of change

- test parameters for validating bids
```
{
  bidder: 'avct',
  params: {
    placement: '5ebd27607781b9af3ccc3332'
  }
}
```

Tested using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: developers@avocet.io
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo: https://github.com/prebid/prebid.github.io/pull/1990

### CODE REVIEW

**Comment by scritchley** [comment]
I've set up a video bid on our side for the same placement. You should be able to see a vast response by passing a video object e.g:
```
{
    code: 'div-gpt-ad-1460505748561-1',
    mediaTypes: {
        video: {
            playerSize: [1920,1080],
            mimes: ["video/mp4"]
        }
    },
    // Replace this object to test a new Adapter!
    bids: [{
        bidder: 'avct',
        params: {
            placement: '5ebd27607781b9af3ccc3332'
        }
    }]
}
```

**Comment by scritchley** [comment]
The 307 Temporary Redirect response should redirect to the endpoint that delivers the bid response. Hopefully you should see the subsequent request responding with a valid bid.

Here's an example of the response we are returning:
```
{
    "requestId": "3913ab47ee0fe4",
    "cpm": 1.25679999,
    "width": 1920,
    "height": 1080,
    "ttl": 60,
    "creativeId": "5ed0e62bce94eec67e4ad223",
    "netRevenue": true,
    "currency": "USD",
    "vastXml": "<VAST version=\"3.0\"><Ad id=\"5ed0e62bce94eec67e4ad223\"><Wrapper><AdSystem>Avocet</AdSystem><VASTAdTagURI><![CDATA[http://ads.avct.cloud/vast?x=1&uuid=9c2537e4-ff46-4847-8bae-d81d9ec7b96f&ty=h&crid=5ed0e62bce94eec67e4ad223&tacid=5ed0ea1dce94eec67e4ad235&aid=3913ab47ee0fe4&accid=5a71dabcc71a10a80c991c55&brid=5a71dbf7c71a10a80c991c5e&ioid=5ec295e8768ce2024f43f8e2&caid=5ec295fd22fd504b7cd08fc1&it=2&iobsid=496e95e8768ce2024f43f8e4&ext_aid=3913ab47ee0fe4&bp=1.25679999&bt=1591258613181393042&h=1080&w=1920&vpr=0&vdp=0&domain=file%3A%2F%2F&gco=54510b3c816269000061a1df&stid=542d2c1615e3c013de53a6e2&gpc=SE13&glat=51.4643&glong=-0.0119&bip4=1577850158&ext_siid=5ebd27567781b9af3ccc3331&ext_pid=5ebd274e7781b9af3ccc3330&ext_sid=5ebd249f42aee25b390bbd3b&ext_plid=5ebd27607781b9af3ccc3332&optv=latest:latest&invsrc=5ebd243f7781b9af3ccc3322&ca=0&biid=requestd-5f6cbb7f55-s9c57|eu-west-1-production&reg=eu-west-1a&pixel=1&ck=1_9be02deb]]></VASTAdTagURI><Impression><![CDATA[http://ads.avct.cloud/sv?pp=1.25679999&uuid=9c2537e4-ff46-4847-8bae-d81d9ec7b96f&ty=h&crid=5ed0e62bce94eec67e4ad223&tacid=5ed0ea1dce94eec67e4ad235&aid=3913ab47ee0fe4&accid=5a71dabcc71a10a80c991c55&brid=5a71dbf7c71a10a80c991c5e&ioid=5ec295e8768ce2024f43f8e2&caid=5ec295fd22fd504b7cd08fc1&it=2&iobsid=496e95e8768ce2024f43f8e4&ext_aid=3913ab47ee0fe4&bp=1.25679999&bt=1591258613181393042&h=1080&w=1920&vpr=0&vdp=0&domain=file%3A%2F%2F&gco=54510b3c816269000061a1df&stid=542d2c1615e3c013de53a6e2&gpc=SE13&glat=51.4643&glong=-0.0119&bip4=1577850158&ext_siid=5ebd27567781b9af3ccc3331&ext_pid=5ebd274e7781b9af3ccc3330&ext_sid=5ebd249f42aee25b390bbd3b&ext_plid=5ebd27607781b9af3ccc3332&optv=latest:latest&invsrc=5ebd243f7781b9af3ccc3322&ca=0&biid=requestd-5f6cbb7f55-s9c57|eu-west-1-production&reg=eu-west-1a&pixel=1&ck=1_9be02deb]]></Impression><Creatives><Creative AdId=\"5ed0e62bce94eec67e4ad223\"><Linear><TrackingEvents></TrackingEvents><VideoClicks></VideoClicks></Linear></Creative></Creatives></Wrapper></Ad></VAST>"
  }
```

**Comment by jsnellbaker** [comment]
@scritchley 
Can you clarify if it's meant to hop to another URL entirely?  

Below is a screenshot of the Request in question taken from the browser console.
Screen Shot 2020-06-04 at 10 25 06 AM

It still doesn't appear to work for me.  Do you have any suggestions?

**Comment by scritchley** [comment]
It's a different URL to another subdomain under `avct.cloud`. I can see the second request in your screenshot 4 steps down from the highlighted prebid call. That should be the request that includes the valld bid response.

**Pull request merged**
