### PR TITLE
ShowHeroes Bid Adapter: added a new endpoint

### PR DESCRIPTION
**Pull request by vadim-mazzherin**
## Type of change
- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter 
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added a new endpoint to a new our bidder server
P.S. Recreate PR #8635  (+ unit tests, eslint fixed, update .md)

- contact email of the adapter’s maintainer: vadim.mazzherin@showheroes.com
- [x] official adapter submission

### CODE REVIEW

**Comment by Rothalack** [comment]
Hey @vadim-mazzherin you'll need to get a docs PR up here https://github.com/prebid/prebid.github.io/pulls

**Comment by Rothalack** [comment]
Hey @vadim-mazzherin , we need to get this PR to fire off CircleCI tests. There's an issue where your github is following your fork in CircleCI instead of Prebid's. It looks like you have it set so that I/others cannot make a file edit to this which should kick off the tests. What you would need to do then is unfollow your fork and follow the main prebid master. Let me know if this makes sense to you, we can work through it.

**Comment by vadim-mazzherin** [comment]
Hey @Rothalack, where in the settings can I allow you to edit? I didn't find that.
But in previous PR reviewers could edit files

**Comment by vadim-mazzherin** [comment]
And about the fork, i.e. how one of the options should I recreate it (the fork) and create a new PR? To fix a issue with CircleCI tests.

**Comment by vadim-mazzherin** [comment]
@Rothalack @jsnellbaker I will be glad to advice on how to fix this without recreating the PR again

**Comment by Rothalack** [comment]
Hey @vadim-mazzherin 

This is a circleci support article talking about it, under the header "If you're following the fork instead of the upstream repo"
https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

I believe if you just unfollow your fork, then submit any small code change to this PR, it should then fire off a circleci test. You should be able to do that from here
https://app.circleci.com/projects

Click on your prebid fork project and unfollow it, then go into the main prebid fork from this projects list and follow that. That should do it.

**Comment by vadim-mazzherin** [comment]
@Rothalack Thanks a lot for the answer!
But. Neither I nor our organization use CircleCI. And I was forbidden to give such wide access to our private repositories that CircleCI requests.
In general, it is a very strange situation that running tests on your side depends on our settings.

**Comment by vadim-mazzherin** [comment]
Are there any other options?

**Comment by Rothalack** [comment]
I wish I had an immediate answer. I've reached out for help, hopefully I have an answer soon.

**Comment by ChrisHuie** [comment]
@vadim-mazzherin @Rothalack I will just resubmit this pr under my gihub account this morning to keep this pr moving. The integration testing is tied to the specific github user idea by CircleCI so that will circumvent the issue.

**Comment by vadim-mazzherin** [comment]
@ChrisHuie Thank you very much!  I will wait for news

**Comment by vadim-mazzherin** [comment]
@ChrisHuie @Rothalack is there any chance to move it forward?
And another question, do you have any questions or comments about the code? In order not to delay it even more with edits later

**Comment by Rothalack** [comment]
I don't have an code edits for you. Once we get CircleCI tests to run, we may find some things that need changes though.

**Pull request closed without merging**
