### PR TITLE
Reviving and moving to prebid 3.0 of smartyAds bi adapter

### PR DESCRIPTION
**Pull request by Aigolkin1991**
## Type of change
- [x] Other

## Description of change

Reviving and moving to prebid 3.0 of smartyAds bi adapter

- test parameters for validating bids
```
var adUnits = [
                // Will return static native ad. Assets are stored through user UI for each placement separetly
                {
                    code: 'placementId_0',
                    mediaTypes: {
                        native: {}
                    },
                    bids: [
                        {
                            bidder: 'smartyads',
                            params: {
                                placementId: 0,
                                traffic: 'native'
                            }
                        }
                    ]
                },
                // Will return static test banner
                {
                    code: 'placementId_0',
                    mediaTypes: {
                        video: {
                            sizes: [[300, 250]],
                        }
                    },
                    bids: [
                        {
                            bidder: 'smartyads',
                            params: {
                                placementId: 0,
                                traffic: 'video'
                            }
                        }
                    ]
                },
                // Will return test vast xml. All video params are stored under placement in publishers UI
                {
                    code: 'placementId_0',
                    mediaTypes: {
                        banner: {
                            sizes: [[300, 250]],
                        }
                    },
                    bids: [
                        {
                            bidder: 'smartyads',
                            params: {
                                placementId: 0,
                                traffic: 'banner'
                            }
                        }
                    ]
                }
            ];
```

### CODE REVIEW

**Comment by Aigolkin1991** [comment]
Can you, please, point me, where gulp test errors occurs - github ci/cd doesn't show any the same as local test . Here is terminl output:
` Compiled successfully.
07 01 2020 15:02:46.690:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
07 01 2020 15:02:46.692:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
07 01 2020 15:02:46.717:INFO [launcher]: Starting browser ChromeHeadless
07 01 2020 15:02:47.495:INFO [HeadlessChrome 79.0.3945 (Linux 0.0.0)]: Connected on socket 6BLgN6EHbB6xqKPXAAAA with id 16354162
07 01 2020 15:02:48.835:WARN [web-server]: 404: /vuble_renderer.js
07 01 2020 15:02:51.224:WARN [web-server]: 404: /nurl&s=0.66
07 01 2020 15:02:51.225:WARN [web-server]: 404: /burl&s=0.66
07 01 2020 15:02:52.046:WARN [web-server]: 404: /scriptUrl.com
LOG: 'entrance', '2:52'

Finished in 6.601 secs / 3.564 secs @ 15:02:55 GMT+0200 (Eastern European Standard Time)

SUMMARY:
✔ 4052 tests completed
ℹ 2 tests skipped
[15:02:55] Finished 'test' after 48 s
[15:02:55] Finished 'test' after 1.18 min`

**Comment by Fawke** [comment]
@Aigolkin1991,

To see the error, you should run this command `gulp test` locally on the repository. It's not showing up in circle-ci because it runs this command `gulp test --browserstack --nolintfix`, so, it essentially bypasses the link checks, and yours is a eslint error.

Here's the screenshot which will point you to the exact error.
Screenshot 2020-01-08 at 11 26 51 AM

**Comment by Aigolkin1991** [comment]
For some reason i'm not seeing error even running gulp test from local work space, but i fixed error using you output

**Comment by Fawke** [comment]
Hi @Aigolkin1991,

Thanks for fixing the test case. It's strange that you're not able to see the error. But anyways, it's gone now.

I was testing your Banner, Native and Video with the test parameters that you've provided in your **md** file. For Banner, I see any problem, but bid responses coming for the native and video didn't seem right.

First, let's talk about native.

- Your bid response for native request looks like this. 
Screenshot 2020-01-09 at 8 05 50 PM

It has the **mediaType** property set to **banner**, instead of **native**.
Also, all the native assets like, `title`, `body`, `image`, `ico` are not bundled under the **native** object.

For your reference, here's a response for native request from Appnexus adapter.
Screenshot 2020-01-09 at 8 07 32 PM

As you can see, all the native assets are bundled against the native object.

About, your bid Response, 

- the mediaTypes is again set to 'banner' instead of 'video'.

I think your adapter supports instream video but it would be better if, in the md file, you can mention the context field as well.

Thanks and let me know if there's any confusion in what I wrote.

**Comment by adfinity-prebid** [comment]
I've packed all assets into native object on back end side. About video media type - the problem was due to some defaults in prebid code and part of code in our adapter which were deleting media type property from bid. After i removed this line `delete resItem.mediaType;`

**Comment by Aigolkin1991** [comment]
Thanks for native example. I've packed assets into native object on backend side. As for video bids with media type banner - this was due to this line of code in our adapter `delete resItem.mediaType;`. After media type beeing deleted, bid gets banner media type, despite the fact that we respond with proper mediaType

**Comment by Fawke** [comment]
Hi @Aigolkin1991,

Thanks for making the changes. I see that your instream video response is well formed. Would be great if you can, 

- 
```
   // Will return test vast xml. All video params are stored under placement in publishers UI
                {
                    code: 'placementId_0',
                    mediaTypes: {
                        video: {
                            sizes: [[300, 250]],
                        }
                    },
                    bids: [
                        {
                            bidder: 'smartyads',
                            params: {
                                placementId: 0,
                                traffic: 'video'
                            }
                        }
                    ]
                }
```
Add a key **context** to indicate that you support instream videos. This way, it'll be easier for reviewers in future to understand you support instream video media type.

Your native mediaType is still not formatted properly.
Screenshot 2020-01-13 at 8 35 42 PM

- The property **clickUrl** should be contained inside the native object.

Also, don't you think, in this particular [line](https://github.com/prebid/Prebid.js/blob/b7a61a76282496d6fddc215817a60bb81265c6db/modules/smartyadsBidAdapter.js#L20), it should now be:

```
      return Boolean(bid.native.title && bid.native.image && bid.native.impressionTrackers);
```
instead of:

```
return Boolean(bid.title && bid.image && bid.impressionTrackers);
```

This holds true since you now have moved these properties inside the **native** object.

Let me know if you have any questions. Thanks.

**Comment by Aigolkin1991** [comment]
Thanks for review, i've made changes into adapter and backend side

**Comment by Fawke** [comment]
@Aigolkin1991,

I still see property **clickUrl** not inside the native object. Please make this change because validation fails, saying " **Prebid ERROR: Invalid bid from smartyads. Ignoring bid: Native bid missing some required properties."**

Screenshot 2020-01-16 at 12 53 09 PM

Also, I see 3 test cases failing. You can run the command `gulp test` locally to know more about it. But attacked a screenshot for your reference as well.

Screenshot 2020-01-16 at 12 35 25 PM

**Comment by Fawke** [comment]
Hi @Aigolkin1991,

Thanks for fixing the unit test cases and moving the property **clickUrl** inside the native object. I think there's still a small typo in the response object due to which I am getting this error.

Screenshot 2020-01-20 at 12 40 23 PM

I think it's because of this:
Screenshot 2020-01-16 at 12 53 09 PM

You've misspelled **icon** as **ico**.

**Comment by Aigolkin1991** [comment]
I've fixed that on our backendside

**Pull request merged**
