### PR TITLE
Digitrust Disable from ID System

### PR DESCRIPTION
**Pull request by goosemanjack**
We are evaluating some deep changes to the way DigiTrust ID operates given changes in the market and in browsers. While this work is underway we want to limit any additional integrations with DigiTrust that might break when new changes roll out.

## Type of change
- [ X ] Other - Disable digitrust ID adoption pending design changes

## Description of change
This PR removes all references to the DigiTrust ID system from the UserID system in Prebid. A separate PR will be submitted that touches individual bidder adapters that may have taken an integration dependency.

- contact email of the adapter’s maintainer
- [ X ] official adapter submission

### CODE REVIEW

**Comment by patmmccann** [comment]
Hi, 

What about removing digitrust from adapters and prebid docs? 

Is your plan that publishers upgrading prebid would de-integrate automatically?

Thanks!

**Comment by goosemanjack** [comment]
I have a separate and as-yet unsubmitted PR that covers those items. I wanted to keep mucking with everyone's adapters out of this to limit chance of issues.

**Comment by patmmccann** [comment]
Would you rather commit against the 4.0 branch? Publishers that upgrade minor versions might consider this a breaking change.

**Comment by goosemanjack** [comment]
I'm going to have to get back to you after consulting some internal people. Being that any of the user Ids are optional for any publisher, this should not be breaking. I do, however, see your point. 

If I were to commit against 4.0, which branch should I look at?

**Comment by jaiminpanchal27** [comment]
@goosemanjack Here is Prebid 4.0 branch https://github.com/prebid/Prebid.js/tree/prebid-4.0

**Comment by goosemanjack** [comment]
Touching. Will try to find time this week.

**Comment by patmmccann** [comment]
Hey Chris, your commit was already merged on the 4.0 branch, you can close this pr, and hopefully open the adapters pr. 

Thanks!

**Comment by goosemanjack** [comment]
Thanks.

**Pull request closed without merging**
