### PR TITLE
Cleanmedianet Bid Adapter : update Placement to plcmt

### PR DESCRIPTION
**Pull request by CleanMediaNet**
fixed reference from Placement to plcmt

## Type of change
- [X ] Build related changes

### CODE REVIEW

**Review by patmmccann — APPROVED** [review]

**Review by patmmccann — CHANGES_REQUESTED** [review]
doesnt pass your tests

**Comment by CleanMediaNet** [comment]
> doesnt pass your tests

I forgot to load the new spec file, it's updated now

**Comment by patmmccann** [comment]
you didnt change this actually, still the same

**Comment by CleanMediaNet** [comment]
> you didnt change this actually, still the same

I forgot to include it in the pull request, I've just resubmitted it.

**Pull request closed without merging**
