### PR TITLE
Small alteration to Rubicon Project adapter

### PR DESCRIPTION
**Pull request by ajsouza**
- Permit pre-loading
- Support DealId

### CODE REVIEW

**Comment by bretg** [comment]
@mkendall07 - Andre is an engineer on our team - these changes look good from my perspective.

The main feature is to pass dealId, but also a minor tweak to check for the existence of the Rubicon code before automatically loading it.

**Comment by mkendall07** [comment]
@ajsouza & @bretg  LGTM. 
@matthewlane  please do a quick sanity check with bids and merge. Thanks

**Comment by mkendall07** [comment]
@bretg 
FYI - we are asking for code coverage of adapters now. Please look to add unit tests for rubicon adapter in the future. Thanks for you help.

**Comment by matthewlane** [comment]
@ajsouza @bretg Thanks for the update. Merged

**Pull request merged**
