### PR TITLE
Merge pubcommon and sharedid #6640

### PR DESCRIPTION
**Pull request by NothingIsMatter**
## Type of change
- [x] Feature

## Other information
Issue link: https://github.com/prebid/Prebid.js/issues/6640

### CODE REVIEW

**Review by smenzer — APPROVED** [review]
This still seems incredibly confusing to me. The name of the ID module file is `sharedId` but all code references in prebid are now to `pubCommonId`. Pulling in the module is even more strange:

```
import {pubCommonIdSubmodule} from 'modules/sharedIdSystem.js';
```

I understand the desire to avoid publisher changes, but why not keep as much in the code under the sharedId name _except_ for the few external pieces, like the source domain in the eids array and the name of the module used for publisher configuration?

Also, in the Issue, it mentions as a requirement:
>We expect publishers who have deployed SharedId to not be impacted but encouraged to remove sharedid from their pb.js build & migrate to the newly renamed Pubcommon sub adapter.

I don't see how publishers who are using `sharedId` as an ID module wouldn't be impacted...it seems like it will just stop working. It's not clear to me from the discussion in the issue if this requirement was scrapped or not, so just calling out that in the code, it has been.

**Review by mmoschovas — CHANGES_REQUESTED** [review]
@NothingIsMatter 

I may be mistaken, but it does not seem to me that this is aligned with the issue definition. Both pubCommon and sharedId should be usable as config options with pubCommon as an alias name for backwards compatibility. If I am correct in that assessment, I would suggest updating the file so that the name is set to sharedId and a new alias field can exist similar to below. 

```
...
export const pubCommonIdSubmodule = {
  /**
   * used to link submodule with config
   * @type {string}
   */
  name: MODULE_NAME,
  aliasName: "pubCommonId",
...
```

This would also require an update to the userId index.js file to look for name then alias if it exists. Something like the following:

```
function updateSubmodules() {
  ...
  submodules = addedSubmodules.map(i => {
    const submoduleConfig = find(configs, j => j.name && (j.name.toLowerCase() === i.name.toLowerCase() || 
      (i.aliasName && j.name.toLowerCase() === i.aliasName.toLowerCase())));
    if (submoduleConfig && i.name !== submoduleConfig.name) submoduleConfig.name = i.name;
...
```

This will allow the config to be defined asa either sharedId or pubCommonId, and the userId module will overwrite the alias name with the submodule name.

**Comment by NothingIsMatter** [comment]
@mmoschovas thx for comment.  I updated the PR, can you take a look ?

**Comment by mmoschovas** [comment]
This looks to be functioning correctly. The only issue I have is that I believe we should perhaps limit the pubCommon references where applicable. It is confusing to have the file and module reference sharedId but internal module comments and such referencing pubCommonId. Some examples:

```
* This module adds PubCommonId to the User ID module 
* The {@link module:modules/userId} module is required 
* @module modules/pubCommonIdSystem 
* @requires module:modules/userId
```

```
const storage = getStorageManager(GVLID, 'pubCommonId');
```

```
utils.logInfo('PubCommonId: IDs not provided for coppa requests, exiting PubCommonId');
```

The only reference I believe that should stay is that of the window object and the new alias. I think this would make this a little less confusing when building using the sharedIdSystem, but would appreciate others opinions on this. @jdwieland8282 what are your thoughts?

**Comment by mmoschovas** [comment]
Also this merge conflict will need to be resolved

**Comment by patmmccann** [comment]
Is this supposed to be on the 5.0 branch?

**Comment by jdwieland8282** [comment]
yes

**Comment by patmmccann** [comment]
This is not on the 5.0 branch,  please resubmit

**Comment by NothingIsMatter** [comment]
@patmmccann I need to pull from prebid 5.0 branch ?

**Comment by jdwieland8282** [comment]
thats correct @NothingIsMatter , this PR should have been made against that branch.

**Pull request closed without merging**
