### PR TITLE
Create Mobsmart bidder adapter

### PR DESCRIPTION
**Pull request by kpis-msa**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Create Mobsmart bidder adapter

- test parameters for validating bids
```
{
  bidder: 'mobsmart',
  params: {
    floorPrice: 100,
    currency: 'JPY'
  }
}
```

### CODE REVIEW

**Comment by bretg** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/1558

**Comment by kpis-msa** [comment]
Hi @jsnellbaker @bretg @sumit116 
I don't know why CircleCI fails. Is there anything I need to change?

**Comment by jsnellbaker** [comment]
@kpis-msa The circleci tests have unfortunately been a bit inconsistent recently.  I have rerun the job and it passed successfully.  So you should likely be okay.

**Comment by kpis-msa** [comment]
@jsnellbaker 
OK, Thank you.
How long does it take to merge?

**Pull request merged**
