### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by sami-elasticad**
## Type of change

- [x ] Bugfix

## Description of change
fixed problem with banner size and tests

- [ x] official adapter submission

### CODE REVIEW

**Comment by sami-elasticad** [comment]
please review bug fix. thank you.

**Comment by jaiminpanchal27** [comment]
@sami-elasticad Please revert all changes to hello_world.html

**Comment by mike-chowla** [comment]
I'll review after hello_world changes are reverted

**Comment by sami-elasticad** [comment]
i'll reopen on another pull request

**Pull request closed without merging**
