### PR TITLE
upgrade to webpack 4

### PR DESCRIPTION
**Pull request by sumit116**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Upgrate to webpack 4

### CODE REVIEW

**Comment by mkendall07** [comment]
This pull request **introduces 1 alert** when merging 877c7634a305f707cd60bd5d322b498df672bdcd into bc3987d4adac1c45b27976f559457c590b15af76 - [view on LGTM.com](https://lgtm.com/projects/g/prebid/Prebid.js/rev/pr-a68022c6efab7a8ad823376403c1789ff0be6544)

**new alerts:**

* 1 for Unused variable, import, function or class

---

**Warning** - Automated code review for prebid/Prebid.js will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by sumit116** [comment]
> This pull request **introduces 1 alert** when merging [877c763](https://github.com/prebid/Prebid.js/commit/877c7634a305f707cd60bd5d322b498df672bdcd) into [bc3987d](https://github.com/prebid/Prebid.js/commit/bc3987d4adac1c45b27976f559457c590b15af76) - [view on LGTM.com](https://lgtm.com/projects/g/prebid/Prebid.js/rev/pr-a68022c6efab7a8ad823376403c1789ff0be6544)
> 
> **new alerts:**
> 
> * 1 for Unused variable, import, function or class
> 
> **Warning** - Automated code review for prebid/Prebid.js will be disabled on October 1, 2019. You can avoid this by [installing the LGTM.com GitHub App](https://github.com/apps/lgtm-com/installations/new). Read about the [benefits of migrating to GitHub Apps](https://lgtm.com/blog/announcing_github_apps_migration) in the blog.
> 
> _Comment posted by [LGTM.com](https://lgtm.com)_

Removed unused var.

**Comment by snapwich** [comment]
I've been able to reproduce the bug in isolation here: https://github.com/snapwich/webpack4-chunk-bug

I also found what I think is a duplicate of the same issue we're experiencing here: https://github.com/webpack/webpack/issues/7230

There doesn't appear to be a fix yet :(

**Comment by sumit116** [comment]
> I've been able to reproduce the bug in isolation here: https://github.com/snapwich/webpack4-chunk-bug
> 
> I also found what I think is a duplicate of the same issue we're experiencing here: [webpack/webpack#7230](https://github.com/webpack/webpack/issues/7230)
> 
> There doesn't appear to be a fix yet :(

@snapwich , I found that you are using `enforce: true` in splitchunks cacheGroups which is not allowing the  common chunk (`entry`) to execute. Removing it worked for me. I am not sure why this property is creating this issue, but I checked the docs and found its only needed when you want to enforce deviation from the default values of `minSize` or `minChunks`, etc. I don't think we require to do that and even if we want to we can alternatively pass their respective values in the `chunk` object under `cacheGroups` .

**Comment by sumit116** [comment]
> This branch still has not addressed the issue with the `prebid-core.js` chunk never executing. The test page will not work with this bundle.
> 
> I think it may be a bug in the webpack splitChunks feature. I'm trying to recreate in an isolated environment.

I have checked it again and its working. The `prebid-core` chunk is getting executed and I am able to run  the `hello_world` example successfully. Can you check if you have any local changes like `enfore: true` or can you reinstall your packages?

**Comment by mkendall07** [comment]
This pull request **introduces 1 alert** when merging 93e201f4e874a49c71b5ccd9d2909bd71942409e into 099a723aa38e4fe57095fbc27876cb12e2272af6 - [view on LGTM.com](https://lgtm.com/projects/g/prebid/Prebid.js/rev/pr-2067d3bb775ef5bba6efc541cf1ded5aeeca981b)

**new alerts:**

* 1 for Useless assignment to local variable

---

**Warning** - Automated code review for prebid/Prebid.js will be disabled on October 1, 2019. You can avoid this by <a href="https://github.com/apps/lgtm-com/installations/new">installing the LGTM.com GitHub App</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by snapwich** [comment]
So I'm not sure I'm a fan of the copy/paste of the `splitChunks` plugin. It cuts us off from the upstream and puts us in a worse spot for future upgrades, which is not a good place to be in with webpack 5 just around the corner.

I think the `DLLPlugin` does what we want, unfortunately after some experimentation yesterday it seems that it doesn't work with `webpack-stream`: https://github.com/shama/webpack-stream/issues/149

I'm seeing if there's a way around that issue and investigating other solutions at the moment.

**Comment by sumit116** [comment]
> So I'm not sure I'm a fan of the copy/paste of the `splitChunks` plugin. It cuts us off from the upstream and puts us in a worse spot for future upgrades, which is not a good place to be in with webpack 5 just around the corner.
> 
> I think the `DLLPlugin` does what we want, unfortunately after some experimentation yesterday it seems that it doesn't work with `webpack-stream`: [shama/webpack-stream#149](https://github.com/shama/webpack-stream/issues/149)
> 
> I'm seeing if there's a way around that issue and investigating other solutions at the moment.

The copy of SplitChunksPlugin was added as the hacky solution mentioned in #3 of https://github.com/prebid/Prebid.js/pull/4112#issuecomment-524952875. Also, as discussed, using `DLLPlugin` would result in making some changes in the build process, which we would need to take care of too.

**Comment by sumit116** [comment]
I tried with a few things to decrease the Prebid bundle size but apart from creating a vendors (node_modules) chunk, could not get any significant decrease in size. We did not create a vendors chunk in webpack 3 since there is no reason to have it, so we do not add it in webpack 4 too. I compared the difference in size of current bundle and bundle after webpack4 upgrade: 
```with webpack 3 - 1085 kb (after 7zip - 229kb).
with webpack 4 - 1200kb (after 7zip - 233kb).```

Ideally we should have the same size but it seems like webpack4 increased the size keeping same configurations. Also, as per discussion with @snapwich, we can ignore the size issue as it shouldn't be a big issue.

Besides this, I have tested the build and serve commands and the bundle with hello_world example and found things working fine. 

cc: @mkendall07

**Comment by mkendall07** [comment]
since there is substantial size increase here and no tangible benefits I think we should defer this can be fixed properly (or Webpack 5 is released). 

Feel free to reopen if there is a strong reason to proceed here.

**Pull request closed without merging**
