### PR TITLE
Kinesso ID System: add UserId Module

### PR DESCRIPTION
**Pull request by SKOCHERI**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by jlukas79 — APPROVED** [review]

**Review by jlukas79 — APPROVED** [review]

**Review by ChrisHuie — APPROVED** [review]

**Comment by ChrisHuie** [comment]
currently working to fix conflicts on this pr

**Comment by ChrisHuie** [comment]
@SKOCHERI I tried to fix the conflicts on this pr but seem to still be getting a couple errors. If you get a chance to pull in recent commits or look at this I would appreciate it 🙏

**Comment by ChrisHuie** [comment]
Actually think I figured it out :) Will get this merged asap

**Comment by ChrisHuie** [comment]
closing with merge of #7283

**Pull request closed without merging**
