### PR TITLE
onetagBidAdapter: outstream support

### PR DESCRIPTION
**Pull request by OneTagDevOps**
## Type of change
- [x] Feature
- [x] Refactoring (no functional changes, no api changes)

## Description of change
Introduces video outstream support

## Email of the adapter’s maintainer
devops@onetag.com

## Documentation's reference
https://github.com/prebid/prebid.github.io/pull/2101

### CODE REVIEW

**Comment by patmmccann** [comment]
can you set bid.meta.mediaType as per http://prebid.org/dev-docs/bidder-adaptor.html#interpreting-the-response ?

**Comment by OneTagDevOps** [comment]
Thanks @musikele , you should see the video player correctly called, can you please check it now? We've also updated the .md file

**Comment by musikele** [comment]
LGTM

**Comment by musikele** [comment]
Ah: un saluto dall'Italia :)

**Comment by OneTagDevOps** [comment]
Un saluto a te Michele :)

**Pull request merged**
