### PR TITLE
GumGum adapter - include new parameter on the request

### PR DESCRIPTION
**Pull request by davidmh**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other

## Description of change
Including a new parameter for subsequent requests on the same page.

- contact email of the adapter’s maintainer
- [x] official adapter submission
dmejorado@gumgum.com

## Other information
Changed case on a couple of variables.

### CODE REVIEW

**Comment by davidmh** [comment]
Hi @matthewlane, could you help us review this update?

**Comment by matthewlane** [comment]
@davidmh Gladly. I have these bidder params for testing GumGum
```
{
  bidder: 'gumgum',
  params: {
    inScreen: 'ggumtest'
  }
}
```
but currently getting back empty bids. Are there different params I should be using?

**Comment by davidmh** [comment]
Thank you @matthewlane, that's expected behavior. Everything is fine as long as you get a healthy response.

**Comment by mkendall07** [comment]
@davidmh We prefer having permanent test params that return a valid bid. Is that possible?

**Comment by davidmh** [comment]
@mkendall07 we have a filter for unprocessed pages, so the endpoint won't return a bid until we have processed the page contents.

So if you're testing with a local domain the filter won't go away because the processor won't be able to reach it. We can bypass the filter by marking the URL as processed manually, can you share the full local URL you are using to test?

**Comment by mkendall07** [comment]
we usually just test with localhost, but if that's not possible, prebid.org can be the host. If you need a full URL, (http://prebid.org/all_bidders_test.html).

**Comment by davidmh** [comment]
Localhost works, we just need the full URL e.g. `http://localhost:9999/integrationExamples/gumgum.html`

**Comment by davidmh** [comment]
Done, you should be able to test with `http://prebid.org/all_bidders_test.html`

**Comment by matthewlane** [comment]
Can the `localhost:9999` address be accepted as well? I'm struggling to configure my test page as `prebid.org` without a port number

**Comment by davidmh** [comment]
Of course, I can ask our team to add `http://localhost: 9999/all_bidders_test.html`

Would that work for you?

**Comment by matthewlane** [comment]
I think it will, thank you!

**Comment by davidmh** [comment]
Done, seems to be working on my test.

test

**Comment by matthewlane** [comment]
That did the trick, thanks a lot

**Pull request merged**
