### PR TITLE
Adding aliases for adsparc and safereach to aardvark adapter

### PR DESCRIPTION
**Pull request by naegelin**
Adding aliases for adsparc and safereach

## Type of change
- [x] Refactoring (no functional changes, no api changes)

## Description of change
Adding aliases for adsparc and safereach

- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

-  PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/1237

### CODE REVIEW

**Comment by mike-chowla** [comment]
adsparc is already an alias of serverbid:
https://github.com/prebid/Prebid.js/blob/96aae26eb2e31b65cd43e5533c15f00f4696220c/modules/serverbidBidAdapter.js#L19

So this alias either needs a different name or the alias needs to be removed from ServerBid.  To remove it from ServerBid, I'd need some confirmation from someone at adsparc that removing it from ServerBid and adding it Aardvark is what they want to do.

**Comment by naegelin** [comment]
hey @mike-chowla - @sanjayamolligoda from adsparc tried to comment on this thread but it says he cannot. Any ideas?

**Comment by mkendall07** [comment]
usually that means you have an adblocker installed.

**Comment by sanjayamolligoda** [comment]
Hi Mike, 

I'd like to confirm this request to move adsparc's alias from serverbid to aardvark.

Cheers
Sanjaya

> adsparc is already an alias of serverbid:
> https://github.com/prebid/Prebid.js/blob/96aae26eb2e31b65cd43e5533c15f00f4696220c/modules/serverbidBidAdapter.js#L19
> 
> So this alias either needs a different name or the alias needs to be removed from ServerBid. To remove it from ServerBid, I'd need some confirmation from someone at adsparc that removing it from ServerBid and adding it Aardvark is what they want to do.

**Comment by naegelin** [comment]
@mike-chowla @mkendall07  hey guys I think we're all set here. let me know what else would be needed.

**Pull request merged**
