### PR TITLE
Nativo Bid Adapter: support native and video

### PR DESCRIPTION
**Pull request by doctafaustus**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [x] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
This pull request adds support for video and native Prebid advertisements in the Nativo Bid Adapter.

### CODE REVIEW

**Comment by patmmccann** [comment]
please also see https://github.com/prebid/Prebid.js/issues/12135

**Comment by jsfledd** [comment]
HI @spotxslagle! Wondering if you had an ETA for this. We're trying to get our Native and Video support up and running so any help getting this reviewed ASAP would be greatly appreciated. Thank you!

**Comment by jsfledd** [comment]
Hi @ChrisHuie and @spotxslagle Just following up again. We're trying to get our Native and Video support up and running so any help getting this reviewed ASAP would be greatly appreciated. Thank you!

**Comment by jsfledd** [comment]
HI @ChrisHuie and @spotxslagle, just wanted to bump this thread again. Please let us know if you have an ETA. Thank you!

**Review by spotxslagle — APPROVED** [review]

**Comment by jsfledd** [comment]
@ChrisHuie @spotxslagle Do you have an ETA when this would be merged? Thank you!

**Comment by jsfledd** [comment]
@ChrisHuie @spotxslagle Do you have an ETA when this would be merged? Thank you!

**Comment by muuki88** [comment]
docs https://github.com/prebid/prebid.github.io/pull/5552

**Pull request merged**
