### PR TITLE
Add  native support to clickforce adapter

### PR DESCRIPTION
**Pull request by MIGOdanis**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
 New bidder adapter from clickforce
- test parameters for validating bids  (display ad)
```
{
  bidder: "clickforce",
  params: {
      zone: "6682",
  }
}
```
- test parameters for validating bids (native ad)
```
{
  bidder: "clickforce",
  params: {
      zone: "6878",
  }
}
```
Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
danis@clickforce.com.tw
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by MIGOdanis** [comment]
@mjacobsonny Hi can you let me know what doc we need?  thank you very much

**Comment by mjacobsonny** [comment]
@MIGOdanis -- Please add `media_types: native` to https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/clickforce.md.

**Comment by MIGOdanis** [comment]
@mjacobsonny  hi, Thanks for the help. we are add media_types now.

**Comment by AdminDoublemax** [comment]
hi @mjacobsonny 

if we do anything. please let me know. 

thanks!

**Comment by MIGOdanis** [comment]
hi @mjacobsonny

if we do anything. please let me know.

thanks!

**Pull request merged**
