### PR TITLE
Glimpse Bid Adapter: update testing, capture ad target, and GDPR consent choices

### PR DESCRIPTION
**Pull request by samueldobbie**
## Type of change

- [x] Feature
- [x] Refactoring (no functional changes, no api changes)

## Description of change

- Re-wrote most of the adapter as we're now handling format conversions and deal tagging server-side
- Started to capture ad targeting, demand network ids, and GDPR consent choices
- Introduced a local auth JWT that is retrieved / set for bid requests and responses
- Added lots of tests / increased the code coverage

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@samueldobbie can you please change the imports from utils to be specific to the functions you are using please? 🙏 We are trying to go through and get ride of all the import * from utils currently.

**Comment by samueldobbie** [comment]
@ChrisHuie good idea! I've pushed the change.

**Comment by musikele** [comment]
@samueldobbie I am trying to use the test parameters in glimpseBidAdapter.md but I always receive 400 from server. Can you provide me with valid test parameters?

**Comment by samueldobbie** [comment]
@musikele Apologies, I hadn't yet deployed the changes to `prd`, could you please try again. Requests using the given test parameters will currently return no bid as domain validation and deal retrieval is being performed server-side; I can introduce a `demo` flag on each bid request to get it returning dummy bids if that would help with validation on your end?

**Review by musikele — APPROVED** [review]
LGTM

**Pull request merged**
