### PR TITLE
Add Centro adapter

### PR DESCRIPTION
**Pull request by Niksok**
Hello Team,

We would like to add our CBX adapter for your solution. Please find our test example of integration here: http://iowcentro.azurewebsites.net/example.html

For any testing purpose you can use ad slot with id 28136
If you would like to notify us about something good or bad, contact us at: brandexchange@centro.net 

Our official website is https://www.centro.net/ 

Thank you,
CBX

### CODE REVIEW

**Comment by protonate** [comment]
Thanks for contributing, code looks good and test page is rendering ads. Please also provide unit tests for your adapter using these instructions: https://github.com/prebid/Prebid.js#unit-testing-with-karma.  We need test coverage at > 80% in order to merge adapters.

**Comment by Niksok** [comment]
Hello!
Unit tests for Centro adapter is ready. Please check it.

**Comment by protonate** [comment]
On Friday it was necessary to remove a commit from Prebid.js, and a force push of master branch has rewritten history. As a committer with an open PR this event impacts you, and we regret the inconvenience. We will need to close your PR and ask that you reapply your changes to a current fork of master, then open a new PR. This will align your history with the main project and your PR will show only your changes. 

Committers are referred to the Apache License (https://github.com/prebid/Prebid.js/blob/master/LICENSE) for details on submitting code to the Prebid.js project.

**Comment by Niksok** [comment]
Hello, we repeat our PR here, please review - https://github.com/prebid/Prebid.js/pull/556

**Pull request closed without merging**
