### PR TITLE
Memeglobal prebid

### PR DESCRIPTION
**Pull request by naamushka**
Prebid adapter for MemeGlobal. Use tagId 007 for testing.

### CODE REVIEW

**Comment by naamushka** [comment]
Hi,
Contact mail: naama@memeglobal.com

**Comment by AlexStanovsky** [comment]
@protonate , I resolved the conflicts with master and re-pushed.

**Comment by protonate** [comment]
Thanks, please also provide unit tests for your adapter using these instructions: https://github.com/prebid/Prebid.js#unit-testing-with-karma. We need test coverage at > 80% in order to merge adapters.

**Comment by naamushka** [comment]
hi @protonate, thanks for your time. we now have coverage > 80%

**Comment by protonate** [comment]
Thanks for the updates and tests. I'm getting 500 errors when requesting adds with this request:
```
http://stinger.memeglobal.com/api/v1/services/prebid?callback=window.pbjs.mgres&src=prebid_prebid_0.12.0-pre&br=%7B%22id%22%3A%22569357cfdbdc275%22%2C%22imp%22%3A%5B%7B%22id%22%3A%2255dd3859caad967%22%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A250%7D%2C%22tagid%22%3A%22007%22%2C%22bidfloor%22%3A%22%22%7D%5D%2C%22site%22%3A%7B%22domain%22%3A%22prebidapp.com%3A9999%22%2C%22page%22%3A%22%2Fgpt-each-bidder3.html%22%7D%7D
```

**Comment by naamushka** [comment]
Hi, I had a problem and it is fixed now. thanks!

**Comment by protonate** [comment]
Thanks for the update, confirmed ads are returned, tests are green, reviewed.

**Pull request merged**
