### PR TITLE
GumGum: uses encodeURIComponent inline

### PR DESCRIPTION
**Pull request by susyt**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [X] Other

## Description of change

Encodes a param object instead of relying on parseQueryStringParameters

### CODE REVIEW

**Comment by susyt** [comment]
Hi @jsnellbaker @harpere ,

Is it possible to get this reviewed and released quickly? the release today (3.16.0) causes curly braces to be left in our query string which we'd like to avoid

thanks!

**Comment by harpere** [comment]
Hi @susyt - sounds like a test may be needed around this parameter. 
Also, are you suggesting we try to release this prior to next week's 3.17.0 release?

**Comment by susyt** [comment]
Thank you for getting back to me so quickly! yes, I apologize for asking but my team/manager has asked if it were possible to get it released sooner

**Comment by harpere** [comment]
merged, but we rarely do early releases, and even then only to fix core problems, not adapters.

**Pull request merged**
