### PR TITLE
TheMediaGrid: RTD module support with mergeDeep of user.data

### PR DESCRIPTION
**Pull request by TheMediaGrid**
## Type of change

- [x] Feature

## Description of change

Added support for Ftrack RTD module

- grid-tech@themediagrid.com
- [x] official adapter submission

### CODE REVIEW

**Comment by patmmccann** [comment]
This appears to add support for the entire user data object. Should it be relabeled?

**Review by patmmccann — CHANGES_REQUESTED** [review]
this appears to just not work unless the only thing writing to this location for the pub is this; also ftrack probably cannot write here, we're going to move it to eids most likely

**Comment by TheMediaGrid** [comment]
@patmmccann please take a look, did I understand your proposal correctly?

**Comment by patmmccann** [comment]
@TheMediaGrid I thought this was waiting on the ftrack merge, my mistake, i see this is for all RTD modules support now.

**Review by patmmccann — APPROVED** [review]
thanks very much!

**Pull request merged**
