### PR TITLE
Ozone Bid Adapter: Various improvements

### PR DESCRIPTION
**Pull request by AskRupert-DM**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added Support for instream
Minor code clean ups

engineering@ozoneproject.com

### CODE REVIEW

**Comment by AskRupert-DM** [comment]
Not sure why Circle CI tests aren't running - spec file looks okay to me - are you able to advise @patmmccann ?

**Comment by patmmccann** [comment]
Typically if you're following your own fork it may not run

**Comment by patmmccann** [comment]
I added some line breaks to your md file, that seemed to do the trick (bc I don't follow your fork in circleci)

**Comment by AskRupert-DM** [comment]
Thanks @patmmccann - good to know !

@ncolletti - let me know if you need anything to help with your review / approving this

**Review by ncolletti — APPROVED** [review]
lgtm

**Comment by ncolletti** [comment]
Looks good @AskRupert-DM -- Before I merge, could you open a PR with the prebid site repo updating your dev-doc to include instream and relevant bid params: https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/ozone.md

**Comment by AskRupert-DM** [comment]
done - thank you!

**Comment by MartianTribe** [comment]
Docs PR: 
https://github.com/prebid/prebid.github.io/pull/3951

**Pull request merged**
