### PR TITLE
Add bid request info to Yieldmo bid adapter

### PR DESCRIPTION
**Pull request by cdoher01**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

### CODE REVIEW

**Comment by cdoher01** [comment]
Hey  @dbemiller & @matthewlane this is a PR related to our discussion here: https://github.com/prebid/Prebid.js/issues/1783

Appreciate your taking a look when you have a few minutes.

**Comment by mkendall07** [comment]
hey @cdoher01  looks like you have a linting error. See https://travis-ci.org/prebid/Prebid.js/builds/303235567#L967

Please fix so the travis build passes.

**Comment by cdoher01** [comment]
Thanks @mkendall07 I've updated to fix the linting

**Comment by matthewlane** [comment]
As of October 1st, we've stopped accepting PRs for adapters that are not compliant with Prebid 1.0 conventions. Please see this page for information on updating your adapter to work with Prebid 1.0: http://prebid.org/dev-docs/bidder-adapter-1.html

**Pull request closed without merging**
