### PR TITLE
Preciso Bid Adapter : Modified request validation in precisoBidAdapter.js

### PR DESCRIPTION
**Pull request by PrecisoSRL**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@PrecisoSRL it looks like you uploaded your ide files also into this pr. Can you please remove when you get a chance.

**Comment by PrecisoSRL** [comment]
> @PrecisoSRL it looks like you uploaded your ide files also into this pr. Can you please remove when you get a chance.

even though i have removed all the ide files, I am getting same error

**Comment by ChrisHuie** [comment]
@PrecisoSRL you might want to resubmit this because looks like there are a few additional changes now wrapped into this pr like updates to package-lock and other adapters.

**Comment by ChrisHuie** [comment]
@PrecisoSRL you might want to resubmit this because looks like there are a few additional changes now wrapped into this pr like updates to package-lock and other adapters.

**Comment by patmmccann** [comment]
Please do resubmit to confine your changes to your adapter

**Pull request closed without merging**
