### PR TITLE
Pubmatic Adapter dont modify shared bid data

### PR DESCRIPTION
**Pull request by ReinoutStevens**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Ensure pubmatic adapter does not modify a shared sizes variable

## Other information

https://github.com/prebid/Prebid.js/issues/3111

### CODE REVIEW

**Comment by ReinoutStevens** [comment]
Note that this still leaves a suspicious looking line https://github.com/prebid/Prebid.js/blob/master/modules/pubmaticBidAdapter.js#L120

**Comment by mkendall07** [comment]
@ReinoutStevens 
Is this causing an issue somewhere?

**Comment by ReinoutStevens** [comment]
@mkendall07 The reported issue associated with this PR has been causing some problems. Atm we have reverted our code and no longer make use of Pubmatic's multi-size support, and specify multiple bids per bids again (as it used to be the case).

**Comment by mkendall07** [comment]
@ReinoutStevens 
ah sorry I missed the linked issue. I think Prebid team should fix this at the core level. Will look into solution as well.

**Comment by ReinoutStevens** [comment]
@mkendall07 no worries, thanks for taking a look at this. 
I agree that an adapter modifying some passed objects should have no influence. I would expect a copy to be passed to each adapter, and not a shared object.
This PR is only a quick fix for a bigger problem, and I'm not sure of the impact of this change on pubmatic's adapter.

**Comment by jsnellbaker** [comment]
Closing this PR in favor of the fix put together by the Pubmatic team.  https://github.com/prebid/Prebid.js/pull/3122

**Pull request closed without merging**
