### PR TITLE
Admaru adapter : add new bid adapter

### PR DESCRIPTION
**Pull request by supadm**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Admaru Adapter added

- test parameters for validating bids
```
{
  bidder: 'admaru',
  params: {
       pub_id: '1234',
       adspace_id: '1234'
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

support@admaru.com

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by ChrisHuie** [comment]
> may I ask you when you would be able to review it? Thanks in advance!

I will work on it this week :)

**Review by ChrisHuie — APPROVED** [review]

**Comment by ChrisHuie** [comment]
@supadm can you please also submit docs to our docs repo with the addition of this adapter :) 
https://github.com/prebid/prebid.github.io

**Comment by supadm** [comment]
[Admaru Adapter: add dev docs for admaru adapter #3661](https://github.com/prebid/prebid.github.io/pull/3661)

**Comment by supadm** [comment]
> @supadm can you please also submit docs to our docs repo with the addition of this adapter :) https://github.com/prebid/prebid.github.io

@ChrisHuie  Thank you.
[Admaru Adapter: add dev docs for admaru adapter #3661](https://github.com/prebid/prebid.github.io/pull/3661)

**Pull request merged**
