### PR TITLE
calling setConfig multiple times on consentManagement causes requestBidsHook to be added each time

### PR DESCRIPTION
**Pull request by olafbuitelaar**
calling pbjs.setConfig with the consentManagement subscriber in the config struct;
invokes : $$PREBID_GLOBAL$$.requestBids.addHook(requestBidsHook, 50);
on each call, causing the consentManagement to be registered multiple times in the asyncSeries,
The causes strange sides effects while calling for bids, as the CMP reports to be timeouted.

For example;
pbjs.setConfig({consentManagement: {timeout:1}});
pbjs.setConfig({consentManagement: {timeout:2}});

I've added a simple boolean flag, to verify if the requestHook should be added or not.

### CODE REVIEW

**Comment by bretg** [comment]
@olafbuitelaar - please correct the merge conflicts.

**Comment by mkendall07** [comment]
This pull request **introduces 1 alert** when merging 0724dee3fc07d4764bd32be2aa75cf93efa7c479 into 32a611d6d88c9953246c7d420ecf9bcfb1aceaf0 - [view on LGTM.com](https://lgtm.com/projects/g/prebid/Prebid.js/rev/pr-92810403751f6c7f76fa6c8e5c19ac910154401e)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsnellbaker** [comment]
@olafbuitelaar Are you sure you put together the right changes to only handle the issue with the consentManagement setting multiple hooks due to multiple setConfigs?

There are a number of other changes in the module (such as analytics tracking and some logic to reattempt the CMP calls?), as well as various other changes to adapter files.

Can you please review and fix (or open a new PR)?

**Comment by olafbuitelaar** [comment]
@jsnellbaker, it looks like the PR picked up also other changes, it's only concerning commit 4f91ad7 and 5a0aad6 not sure i can take commits out of the PR

**Comment by jsnellbaker** [comment]
@olafbuitelaar In that case, can you open a new PR with the intended changes and we'll close this one out?

**Comment by jsnellbaker** [comment]
Closing this PR.  A new clean PR was created here: https://github.com/prebid/Prebid.js/pull/3399

**Pull request closed without merging**
