### PR TITLE
Openx Ortb2 Bid Adapter: initial release

### PR DESCRIPTION
**Pull request by bwschmidt**
## Type of change
- [x] New bidder adapter 

## Description of change
OpenX is working to replace its browser serving architecture and moving to an OpenRTB based protocol. We would like to offer a 2nd adapter which we will test with publishers. Once we have validated the new architecture the goal is to replace the current adapter with this one. The interface for publishers remains the same.

I am not sure if this has been done before and if there are comments or concerns. In my testing it seemed that overloading the bidder code did not result in any problems, the build will just use the one that is last alphabetically if both adapters are included in the build. Another approach would be to use a new code like `openx2` however for ease of testing we are hoping publishers would only have to change their build, not their webpages.

- test parameters for validating bids
```javascript
            bids: [{
                    bidder: 'openx',
                    params: {
                        delDomain: 'sademo-d.openx.net',
                        unit: '540096529',
                        test: true
                    }
               }]
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer prebid@openx.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by patmmccann** [comment]
Hey @bwschmidt 

I want to pitch an idea and see if you guys would be up for it. 

Right now if a publisher has, say 6 openrtb based adapters, they each have lots of redundant code. How about a generic openrtb bidder module that your new adapter would be a submodule of. The submodule would import the basic openrtb adapter and register certain things like your gvl id and any meta parameter return handling etc, but most of its code would just be imported. This way, if something gets added to the base adapter, your sub-adapter would automatically take advantage, eg regs.gpc or device.sua. This seems to go a long way towards achieving some of the goals of https://github.com/prebid/Prebid.js/issues/5001

**Comment by patmmccann** [comment]
One minor point, you might now want to call this openxnew, bc then we might end up with things like openx_new_new_final_final4real_v4

**Comment by bwschmidt** [comment]
Yeah that is a good idea, i'll take a stab at it and think of a better name

**Review by mmoschovas — APPROVED** [review]
lgtm but holding off on merging based on the conversation

**Comment by bwschmidt** [comment]
This PR has been updated with a name that makes more sense and also updated with prebid 7 FPD changes. Docs have been updated at https://github.com/prebid/prebid.github.io/pull/3836.

@patmmccann I am still interested in moving some of this code into a util. It wasnt as straightforward as I hoped as adapters split requests in different ways, as an example OpenX combines banner imps and splits video into different requests. I would like to get this released and come back to that work.

@mmoschovas please take a look at the small changes and see if it still looks good

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
