### PR TITLE
Added iQM Bid Adapter for Prebid.js 1.0

### PR DESCRIPTION
**Pull request by pkthakkar26**
## Type of change

- [x] New bidder adapter   

## Description of change

New bidder adapter added for iQM

- test parameters for validating bids
```
{
  bidder: 'iqm',
  params: {
    publisherId: 'df5fd732-c5f3-11e7-abc4-cec278b6b50a',
    tagId: '1c5c9ec2-c5f4-11e7-abc4-cec278b6b50a',
    placementId: '50cc36fe-c5f4-11e7-abc4-cec278b6b50a',
    bidfloor: 0.35
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

Maintainer Email: hbteam@iqm.com

### CODE REVIEW

**Comment by mike-chowla** [comment]
I'm not getting an bids back on the Hello World test:

Reuqest URL: http://pbd.bids.iqm.com/

Request Body:
`
{
  "id": "dfa20f06-cb81-411f-9191-9eba3df9a9df",
  "publisherId": "df5fd732-c5f3-11e7-abc4-cec278b6b50a",
  "tagId": "1c5c9ec2-c5f4-11e7-abc4-cec278b6b50a",
  "placementId": "50cc36fe-c5f4-11e7-abc4-cec278b6b50a",
  "device": {
    "h": 1080,
    "w": 1920,
    "dnt": 0,
    "language": "en",
    "make": "Google Inc.",
    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36",
    "devicetype": 2
  },
  "site": {
    "id": "1c5c9ec2-c5f4-11e7-abc4-cec278b6b50a",
    "page": "http://mike.pubmatic.com:9999/integrationExamples/gpt/hello_world.html",
    "domain": "mike.pubmatic.com:9999"
  },
  "imp": {
    "id": "21d54102bed454",
    "secure": 1,
    "bidfloor": 0.35,
    "displaymanager": "Prebid.js",
    "displaymanagerver": "v.1.0.0",
    "mediatype": "banner",
    "banner": {
      "w": 300,
      "h": 250
    }
  }
}
`

Response: HTTP 204

**Comment by mike-chowla** [comment]
I'm getting the following console warning in Chrome:

iqmBidAdapter.js:122 [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by pkthakkar26** [comment]
We have fixed the issue and modified endpoint url to https.

**Comment by mkendall07** [comment]
@mike-chowla 
can you re-check?

**Comment by mike-chowla** [comment]
Bids are coming in now.

I'm still seeing the deprecation warning on http pages (in Chrome) and https pages put up a dialog asking for to approve sharing location.   I'm unsure if bid adapters are permitted to make location requests.  @mkendall07 is this allowed ?   Seems like if the publisher wants a location request, they should make it and pass the location as a parameter into the bidder.  Requesting location may require changes to publisher privacy policies which is why I'm flagging it.

screen shot 2017-12-14 at 3 37 53 pm

screen shot 2017-12-14 at 3 53 20 pm

**Comment by mkendall07** [comment]
@mike-chowla 
Yeah thanks for flagging that. Those APIs should not be in the adapter. They need to be removed before merge. Thanks

**Comment by pkthakkar26** [comment]
@mkendall07, @mike-chowla  I have dropped geo functions. Please review.

**Comment by mike-chowla** [comment]
I've reviewed the updated code and don't see any major issues.  The adapter is sending the display manager field hardcoded to 1.0.0.  If the intent is to capture running prebid version, version should pulled from the prebid object

**Comment by mkendall07** [comment]
This is merged into master. Please submit a PR to the [docs repo](https://github.com/prebid/prebid.github.io) to add a file for your adapter to the [bidders directory](https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders) so your adapter's params will appear on the [bidders page](http://prebid.org/dev-docs/bidders.html). Thank you for contributing

**Comment by dtchanpura** [comment]
@mkendall07, The PR has already been submitted and have referenced this PR over there too.

https://github.com/prebid/prebid.github.io/pull/460

**Pull request merged**
