### PR TITLE
Add GDPR support to DAN Marketplace Bid Adapter

### PR DESCRIPTION
**Pull request by danmarketplace**
## Type of change

- [x] Feature

## Description of change

Added GDPR support to DAN Marketplace Bid Adapter

- niels@baarsma.net
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo https://github.com/prebid/prebid.github.io/pull/791

### CODE REVIEW

**Comment by snapwich** [comment]
There is a new third parameter to getUserSyncs that is the gdpr object. Does your pixel need to be updated to take into account gdpr compliance?

**Comment by danmarketplace** [comment]
Thank you, we add gdpr parameters in our sync pixel.

**Comment by danmarketplace** [comment]
Hey prebid team! @snapwich Any news on the review of this PR? BTW when are you going to release these changes?

**Comment by snapwich** [comment]
@danmarketplace it should be released early next week as part of 1.13

**Pull request merged**
