### PR TITLE
Prebid 9: extract DFP adpod logic into a separate dfpAdpod module

### PR DESCRIPTION
**Pull request by dgirardi**
## Type of change

- [x] Other

## Description of change

Closes https://github.com/prebid/Prebid.js/issues/10552

### CODE REVIEW

**Comment by dgirardi** [comment]
@jsnellbaker I was not able to test this (or adpod in general) end to end following the only guide that mentions it (https://docs.prebid.org/dev-docs/show-long-form-video-with-gam.html) as I can't get a bid from appnexus

there's a few examples for long form video that also seem to be associated with the appnexus adapter, but they don't appear to be using adpod.

**Comment by jsnellbaker** [comment]
@dgirardi  I restarted the test creatives for the longform tests that are in the integration tests folder.  I'll do some checking later on this PR.

**Review by jsnellbaker — APPROVED** [review]
Hi @dgirardi 

I ran a test using the test page under `http://test.localhost:9999/integrationExamples/gpt/googleads_ima_html5_samples/gam_pbjs/`; note - I swapped out the placementId for `15394006` which has some test adpod ads.

It seems that the output keys and DFP ad URL are getting generated correctly with these changes.  Took a screenshot for reference.

Screenshot 2024-05-31 at 11 54 41 AM

**Review by fowler446 — COMMENTED** [review]
LGTM

**Pull request merged**
