### PR TITLE
fix sizes for adblade so it works as "[[w, h]]" or "[w, h]"

### PR DESCRIPTION
**Pull request by frazjp65**
## Type of change

- [x ] Bugfix
- [x ] Code style update (formatting, local variables)
## Description of change

The adblade adapter was not working when sizes was called with "[300, 250]", but it did when called with "[[300, 250]]". This change should make it work both ways. 

I also fixed indentation in prebid.js that the "quality" check was complaining about. 
## Other information

fix indentation in prebid.js that the "quality" check complained about

### CODE REVIEW

**Comment by matthewlane** [comment]
@frazjp65 Thanks for the PR. On a testing page I'm getting back empty bids from Adblade, are these params still valid for testing?
```
{
    bidder: 'adblade',
    params: {
        partnerId: 39875,
        bidfloor: 0.01		// OPTIONAL float bid floor in $ CPM
    }
}
```

**Comment by frazjp65** [comment]
That was an old tag that I never changed. The publisher id should be 42980. I updated the tag on the test page.

**Comment by frazjp65** [comment]
Does the new tag work for you?

**Comment by jaiminpanchal27** [comment]
@frazjp65 Yes new tag worked fine. Thanks

**Comment by jaiminpanchal27** [comment]
Looks good. Merging. Thanks @frazjp65

**Pull request merged**
