### PR TITLE
Update adform adapter

### PR DESCRIPTION
**Pull request by Alexander-Kozlov**

### CODE REVIEW

**Comment by mkendall07** [comment]
@Alexander-Kozlov 
Is this just a refactor? Any functionality changes?

**Comment by Alexander-Kozlov** [comment]
We added I functionality for single parameter in bids.
When our clients needs to add reference url for adx.

**Comment by mkendall07** [comment]
@Alexander-Kozlov 
Thanks. Can you commit unit tests for the change?

**Comment by Alexander-Kozlov** [comment]
Yes i can. I am going to do it on Monday.

**Comment by mkendall07** [comment]
@Alexander-Kozlov 
Any update here?

**Comment by mkendall07** [comment]
@prebid/adform 
Going to close this out if there is no update here.

**Pull request closed without merging**
