### PR TITLE
rubicon: adding pubcid support

### PR DESCRIPTION
**Pull request by bretg**
## Type of change
- [ X ] Feature

## Description of change
Adding pubcid support to Rubicon client-side adapter

Docs PR https://github.com/prebid/prebid.github.io/pull/2397

### CODE REVIEW

**Review by harpere — CHANGES_REQUESTED** [review]
I think it needs to be added to line 240

**Review by idettman — APPROVED** [review]

**Comment by idettman** [comment]
@harpere I removed the filter entirely since we will be supporting all eids soon

**Review by idettman — APPROVED** [review]

**Comment by harpere** [comment]
> @harpere I removed the filter entirely since we will be supporting all eids soon

cool. LGTM

**Review by harpere — APPROVED** [review]

**Comment by bretg** [comment]
Thanks gents - there will be an internal ticket soon defined that will detail how to map the IDs to the GET params. We're good with passing all EIDs to PBS now. Merging.

**Pull request merged**
