### PR TITLE
New krushmedia Prebid.js adapter

### PR DESCRIPTION
**Pull request by Krushmedia**
## Type of change
- [x] New bidder adapter   

## Description of change

New bidder adapter

- test parameters for validating bids
```
{
  bidder: 'krushmedia',
  params: {
                                key: 783,
                                traffic: 'banner',
                                test: 1
  }
}
```

- contact email of the adapter’s maintainer
adapter@krushmedia.com
- [] official adapter submission

## Other information
https://github.com/prebid/prebid.github.io/pull/2403/

### CODE REVIEW

**Comment by Krushmedia** [comment]
@Fawke Good day to you, there is some failing job in circle  CI, but i can't get, looks like it comes from some internal errors
`Parrable ID System
    timezone filtering
      ✗ "before all" hook
	Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

**Comment by Fawke** [comment]
Hi @Krushmedia,

I've fixed the Circle CI test, sometimes you just have to run it again. I've gone through your submission and there are a few issues which you might wanna look at:

- Maintainer email id is missing from the markdown file.
- Getting a CORS error when trying to send banner/video request to your endpoint. Here's a screenshot 
for your reference.
Screenshot 2020-10-08 at 2 55 37 PM
- You have listed native mediatype as a supported mediatype, but I didn't find any corresponding example in the markdown file to test it.

**Review by Fawke — CHANGES_REQUESTED** [review]
Hi @Krushmedia,

I've fixed the Circle CI test, sometimes you just have to run it again. I've gone through your submission and there are a few issues which you might wanna look at:

Maintainer email id is missing from the markdown file.
You have listed native mediatype as a supported mediatype, but I didn't find any corresponding example in the markdown file to test it.
Getting a CORS error when trying to send banner/video request to your endpoint. Here's a screenshot
for your reference.
Screenshot 2020-10-08 at 2 55 37 PM

**Comment by Fawke** [comment]
@Krushmedia I see some changes since my last comment, are these final? Can I start my second review?

**Comment by Fawke** [comment]
@Krushmedia I still saw CORS errors when I last reviewed your changes. And I don't see a native example in your markdown file.

**Comment by Krushmedia** [comment]
We've added full support for native ads. The examples were also updated. Check, please.

**Review by Fawke — CHANGES_REQUESTED** [review]
@Krushmedia The change looks good, was able to get a bid back when I tested with banner. One last thing, can you add a response header `content-encoding: gzip`?

**Comment by Krushmedia** [comment]
@Fawke, we have added support for gzip in our responses. Could you check?

**Review by Fawke — APPROVED** [review]
LGTM

**Pull request merged**
