### PR TITLE
Rename pubProvidedSystem.js to pubProvidedIdSystem.js

### PR DESCRIPTION
**Pull request by GLStephen**
This filename didn't follow the convention of using "IdSystem.js" as the filename suffix.

### CODE REVIEW

**Review by jdwieland8282 — APPROVED** [review]

**Comment by smenzer** [comment]
@jdwieland8282 i assume this will require an update to the downloads page in the docs page, right?

**Comment by smenzer** [comment]
@GLStephen you need to modify the `userId_spec.js` to point to the right file name since it's changed now.

**Comment by GLStephen** [comment]
@smenzer will do

**Comment by smenzer** [comment]
LGTM, but before I merge I'm pretty sure this is going to require a change to the docs download page since the name of the file changed. @bretg can you confirm, please? 

currently, the `moduleCode` is listed as `pubProvidedSystem` (https://github.com/prebid/prebid.github.io/pull/2357/files#diff-c8eec1db450201507b0137188c7c58afd76e678c22c2de1e8b4a59e9a6a9bb41R548)

**Comment by bretg** [comment]
Updated pubprovided in download page -- docs PR https://github.com/prebid/prebid.github.io/pull/2426

**Comment by smenzer** [comment]
Great, thanks @bretg !

**Pull request merged**
