### PR TITLE
Aol adapter

### PR DESCRIPTION
**Pull request by ikhemissi**
Hi @nickjacob and Prebid team,

I have updated the aol-adapter branch with latest changes and fixed a minor bug with sizeId passing to DAC.js (I have also added the support for the pageid parameter).

Can you please check this out and eventually merge it in order to prepare for merging the aol-adapter branch in master ?

Thanks,
Iheb

### CODE REVIEW

**Comment by ikhemissi** [comment]
@nickjacob and @mkendall07 can you please check the pull-request and merge it or give some feedback ?
Thanks

**Comment by nickjacob** [comment]
the changes to AOL lgtm, just worried there's a git issue here because this PR has 48 commits?

**Comment by mkendall07** [comment]
Will work on reviewing this PR this week. Regarding the number of commits, I'm not sure but it looks like most are merge updates to keep in sync with master.

**Comment by nickjacob** [comment]
Oh I missed that it was against the other AOL branch

On Mon, Nov 2, 2015 at 10:42 AM, mkendall <notifications@github.com> wrote:

> Will work on reviewing this PR this week. Regarding the number of commits,
> I'm not sure but it looks like most are merge updates to keep in sync with
> master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prebid/Prebid.js/pull/85#issuecomment-153057221>.
>



-- 
 Lead Engineer, A Plus | nick@aplus.com | 617-680-0337

**Comment by ikhemissi** [comment]
Yes, it was just to have a more or less up-to-date branch (compared to master)

**Comment by mkendall07** [comment]
I'm going to merge this now and then do compare against master.

**Pull request merged**
