### PR TITLE
Rules enforcement: Video OpenRTB fields cannot only be read from bidder parameters

### PR DESCRIPTION
**Pull request by patmmccann**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [X] Other

## Description of change
Solution to #6512

### CODE REVIEW

**Comment by patmmccann** [comment]
Note fixed for gridnm in #6817 , will remove them from this shortly

thanks to @TheMediaGrid

**Comment by ym-dlabuzov** [comment]
We made #6873 to fix this for Yieldmo Bid Adapter

**Comment by patmmccann** [comment]
Thanks @ym-dlabuzov !! Happy holiday

**Comment by patmmccann** [comment]
closing and re-opening with the reduced list

**Pull request closed without merging**
