### PR TITLE
Anyclip Bid Adapter : initial release

### PR DESCRIPTION
**Pull request by basil79**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added new bid adapter AnyClip. It uses the external PubTag library for fast bids, first please add the following file to the `<HEAD>`

```html
<!-- AnyClip PubTag -->
<script src="https://anyclip-player.s3.amazonaws.com/anyclip-widget/pubtag/pubtag.js"></script>
```

- contact email of the adapter’s maintainer: basil.goldman@gmail.com or basil@anyclip.com
- test parameters for validating bids:
```js
var adUnits = [{
    code: 'adunit1',
    mediaTypes: {
        banner: { // support banner only
            sizes: [
                [300, 250]
            ]
        }
    },
    bids: [{
        bidder: 'anyclip',
        params: {
            publisherId: '12345', // required, string
            supplyTagId: '-mptNo0BycUG4oCDgGrU', // required, string
            floor: 0.1 // optional, floor
        }
    }]
}]
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page. -->

### CODE REVIEW

**Comment by Rothalack** [comment]
For your external PubTag code. I think the only other bidder doing something like this is Criteo and they seem to have gotten worked out where you do not need to ask the user to include an extra script in the head. I think you should attempt to do it that way, having the user have to add an extra script isn't an intended way of doing it. You should be able to see it here
https://github.com/criteo-forks/Prebid.js/blob/master/modules/criteoBidAdapter.js

Feel free to push back, I'm not absolutely certain about this.

**Comment by basil79** [comment]
> For your external PubTag code. I think the only other bidder doing something like this is Criteo and they seem to have gotten worked out where you do not need to ask the user to include an extra script in the head. I think you should attempt to do it that way, having the user have to add an extra script isn't an intended way of doing it. You should be able to see it here https://github.com/criteo-forks/Prebid.js/blob/master/modules/criteoBidAdapter.js
> 
> Feel free to push back, I'm not absolutely certain about this.

@Rothalack, yes, you right, it is similar to the Criteo adapter, but Criteo uses ```loadExternalScript``` from ```'../src/adloader.js'```, which requires a code review for the external file to allow our adapter to use this feature.

https://github.com/criteo-forks/Prebid.js/blob/master/modules/criteoBidAdapter.js#L186

This is normal for us: all of our publishers must include our PubTag library in order to use our prebid adapter.

**Comment by basil79** [comment]
> Hi @basil79 ; criteo is in process of removing this dependency in prebid 9

Hi @patmmccann , give me their pr I will check

**Comment by basil79** [comment]
@Rothalack, any updates?

**Comment by Rothalack** [comment]
There is a divide in opinion on whether or not the way you're doing this should be allowed. I've voiced my thoughts on this. I do not feel like I'm in the position to make this decision, it's a policy decision.

I'm unsure if @patmmccann s comment here was a request for you to make a change or just information for you.

**Comment by basil79** [comment]
> There is a divide in opinion on whether or not the way you're doing this should be allowed. I've voiced my thoughts on this. I do not feel like I'm in the position to make this decision, it's a policy decision.
> 
> I'm unsure if @patmmccann s comment here was a request for you to make a change or just information for you.

@Rothalack , criteo has been using this method for many years, we want to use it too. I haven't found any policies or restrictions to not do it this way.

**Comment by Rothalack** [comment]
They're doing it the intended way, which is to have the external JS in an open source github repo under Prebid. My understanding at least is that this is to keep the spirit of open source and have the code be publicly accountable.

**Comment by basil79** [comment]
> They're doing it the intended way, which is to have the external JS in an open source github repo under Prebid. My understanding at least is that this is to keep the spirit of open source and have the code be publicly accountable.

but we don't load external JS file using Prebid, our publishers do that

**Comment by Rothalack** [comment]
Right, which is where the divide in opinion occurs.

**Comment by basil79** [comment]
bottom line, any publisher wishing to use any prebid adapter must contact the company (ex SSP provider) that owns the adapter to obtain connection params etc.

**Review by Rothalack — APPROVED** [review]
I'm going to go ahead and approve and merge this. I don't see any more discussion on this topic and it seems like Pat was in approval.

**Pull request merged**
