### PR TITLE
New bidder adapter: pubgenius

### PR DESCRIPTION
**Pull request by edmonl**
## Type of change
- [x] New bidder adapter   

## Description of change
Add pubGENIUS bidder adapter

- test parameters for validating bids
```
{
  bidder: 'pubgenius',
  params: {
    adUnitId: '1000',
    test: true,
    bidFloor: 1.0 // Otherwise CPM for test bids is $0.01
  }
}
```

Tested using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- maintainer: meng@pubgenius.io
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/1963

## Other information
@kevinstubbs for peer awareness

### CODE REVIEW

**Comment by edmonl** [comment]
Hi @bmwcmw why do the checks fail? Anything I can do to solve it?

**Comment by bmwcmw** [comment]
Hi @edmonl, for a first look I don't think it's related to your code. [Here](https://github.com/prebid/Prebid.js/pull/5208) you may find some similar issues. 

Also, you could keep your branch rebased with master for any potential fix.

**Comment by edmonl** [comment]
Thanks @bmwcmw ! I merged the latest master and the checks have passed!

**Comment by bmwcmw** [comment]
LGTM

**Comment by edmonl** [comment]
Thank you! I find our adapter in the code of  3.20.0 release but it's not included in the release note https://github.com/prebid/Prebid.js/releases/tag/3.20.0. Can you edit the release note to include this? @bmwcmw @mike-chowla

**Comment by smenzer** [comment]
@edmonl sorry about that! I've updated the release note to include your adapter

**Comment by edmonl** [comment]
Thank you @smenzer ! Do you happen to know when the doc PR https://github.com/prebid/prebid.github.io/pull/1963 gets merged?

**Comment by smenzer** [comment]
> Thank you @smenzer ! Do you happen to know when the doc PR [prebid/prebid.github.io#1963](https://github.com/prebid/prebid.github.io/pull/1963) gets merged?

@bretg does the docs releases once the prebid.js code is released. I'm not sure when the next scheduled release is, but he may be able to tell you.

**Comment by edmonl** [comment]
> > Thank you @smenzer ! Do you happen to know when the doc PR [prebid/prebid.github.io#1963](https://github.com/prebid/prebid.github.io/pull/1963) gets merged?
> 
> @bretg does the docs releases once the prebid.js code is released. I'm not sure when the next scheduled release is, but he may be able to tell you.

Thanks again!

**Pull request merged**
