### PR TITLE
Updated adloader.js trackPixel

### PR DESCRIPTION
**Pull request by ericperez**
Simplified the 'trackPixel' function: exit early if pixelUrl was not passed in, fixed bug whereby pixelUrl will always evaluate to 'truthy' because when it's not passed in, it's undefined and is cast to a string 'undefined' and then the "'&rnd=' + Math.random()" piece is appended to it; multiplied random number by 100 to ensure only positive integer values.

### CODE REVIEW

**Comment by protonate** [comment]
Can you use `utils.logMessage()` and an empty return in place of throwing a TypeError? Following [this example](https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L89)

**Comment by ericperez** [comment]
Done. I also added a check to determine if the delimiter for the 'rnd' token needs to be '?' or '&' and added Chai tests around the new functionality.

**Comment by protonate** [comment]
Looks good, thanks for the test. Please squash commits and we'll get this merged.

**Comment by protonate** [comment]
Commits were flattened and merged manually with [this commit](https://github.com/prebid/Prebid.js/commit/db9f2ef4f57bb7d3bfdc565b996abdca183ba0ae). Thanks for the contribution. Closing PR.

**Comment by ericperez** [comment]
Thanks @protonate

**Pull request closed without merging**
