### PR TITLE
Cedato new bid adapter

### PR DESCRIPTION
**Pull request by alexkh13**
## Type of change
- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
- test parameters for validating bids
```
{
  bidder: 'cedato',
  params: {
    player_id: 1450133326
  }
}
```
- [x] official adapter submission

### CODE REVIEW

**Comment by robertrmartinez** [comment]
@alexkh13 This is marked as a draft, are you planning on adding some updates?

Or is it ready for a full review?

**Comment by alexkh13** [comment]
@robertrmartinez Yes, this pull request is ready for review.

Test parameters has been updated.

**Comment by alexkh13** [comment]
https://github.com/prebid/prebid.github.io/pull/1215

**Comment by robertrmartinez** [comment]
Starting the review now.

Should be done shortly and we can get this into Tomorrows release!

**Comment by robertrmartinez** [comment]
Sorry accidentally clicked close!

**Comment by robertrmartinez** [comment]
@alexkh13 Hey this looks good.

But I want to point out / inquire about potentially passing the GDPR parameters?

If a publisher wishes to use Cedato, is there a way this bid adapter plans on handling GDPR consent?

Prebid will send a gdprApplies flag as well as the actual consent string.

This is accessible by both the `bidderRequest` object sent in by prebid:

image


As well as an optional `gdprConsent` object which can be sent into the getUserSyncs function!

image

Please get back to me and let me know if you will be adding these!

**Comment by robertrmartinez** [comment]
Example adapter of passing it along in the bidderRequest:

https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L146

User Sync:

https://github.com/prebid/Prebid.js/blob/master/modules/rubiconBidAdapter.js#L556

Please note that if consentManagement is enabled in the setConfig,

And Prebid was not able to get consent, but the auction is still allowed to occur,

Then the `gdprConsent` object is still passed, BUT it contains undefined values for each of the keys passed.

**Comment by alexkh13** [comment]
@robertrmartinez 
Added support for GDPR in the adapter

**Pull request merged**
