### PR TITLE
Added protocol to url

### PR DESCRIPTION
**Pull request by skazedo**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x ] Other

## Description of change

Request to add protocol to url by @sumit116 

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

### CODE REVIEW

**Comment by skazedo** [comment]
@harpere modified to only call secure. Though the pull request build seems to be failing on some other tests. Can you please check. Thanks

**Comment by harpere** [comment]
looks good, but I reran and looks like it's failing on the same tests each time.  You may need to merge `master` into your branch to pick up some fixed tests.

**Comment by skazedo** [comment]
Thanks. Merged but failing on a different test now.

**Comment by skazedo** [comment]
@harpere . Merged again today. Ran fine this time.

**Pull request merged**
