### PR TITLE
SirData RTD Module: Change (add Seller Defined Audience (SDA) support)

### PR DESCRIPTION
**Pull request by nouchy**
Add support for Seller Defined Audience.  Various improvement and support for new bidders.

## Type of change

- [X] Code style update (formatting, local variables)
- [X ] Refactoring (no functional changes, no api changes)

## Description of change
Additional bidders support.
Seller Defined Audience Support (incuding segtax)

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@nouchy can you please add unit testing for this pr and looks like there are some linting issues.

**Comment by nouchy** [comment]
> 

Done. Sorry for that

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/4293

**Comment by Fawke** [comment]
Hey @nouchy,

This PR looks good to me at first glance. But you'd need to improve the test coverage of this module to at least 80%. To see the test coverage, run this command `gulp test-coverage` followed by `gulp view-coverage` and navigate to your module location.

**Comment by nouchy** [comment]
> Hey @nouchy,
> 
> This PR looks good to me at first glance. But you'd need to improve the test coverage of this module to at least 80%. To see the test coverage, run this command `gulp test-coverage` followed by `gulp view-coverage` and navigate to your module location.

Sure! Done :)

**Review by Fawke — APPROVED** [review]

**Pull request merged**
