### PR TITLE
Snigel Bid Adapter: initial adapter release

### PR DESCRIPTION
**Pull request by snigelweb**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Add snigel bidder adapter.

- test parameters for validating bids
```
{
  bidder: 'snigel',
  params: {
    placement: 'prebid_test_placement'
  }
}
```

- contact email of the adapter’s maintainer:  devops@snigel.com
- [x] official adapter submission

## Other information

PR on prebid.github.io docs repository: https://github.com/prebid/prebid.github.io/pull/3919

### CODE REVIEW

**Comment by snigelweb** [comment]
Sorry for updating the PR, but we discovered an issue with the user sync internally and fixed it. Should be fine now.

**Review by Fawke — COMMENTED** [review]
Hi @snigelweb,

This PR looks mostly good. I noticed that in some places, you are using `bidderSettings` to read some bidder specific values. I think it would be more ideal to use [setBidderConfig](https://docs.prebid.org/dev-docs/publisher-api-reference/setBidderConfig.html) instead.

I agree BidderSettings does work here, but I think it's more suitable in cases where we want to modify bidder's bids (targeting, cpm, etc,). And setBidderConfig is specially designed to pass bidder specific values.

**Comment by snigelweb** [comment]
Thanks for your review and the heads-up. We will implement your review feedback along with fixing some issues we came across soon.

**Comment by snigelweb** [comment]
Hello @Fawke, we implemented the changes you requested and added some additional features while we were at it. Thanks.

**Review by Fawke — APPROVED** [review]
LGTM

**Pull request merged**
