### PR TITLE
feat: add the elapsed time to events for debugging

### PR DESCRIPTION
**Pull request by gpolaert**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Add to the events a new field to track the elapsed time
It allows us to better understand the whole process of the auctions run on the page. 

The tracked value represents the time elapsed since the time origin. See here for more information https://developer.mozilla.org/en-US/docs/Web/API/Performance/now.
In case of the `performance.now()` is not supported, there is no fallback, the value 0 is simply logged instead.

### CODE REVIEW

**Review by osazos — COMMENTED** [review]
Hi, 

Just a consistency concern:

- could you please use `window.performance` instead?
- I'm not sure about the naming of the function. A better naming could be `getPerformanceNow`, `getElapsedTime` or something like this.

**Review by osazos — DISMISSED** [review]
LGTM

**Comment by osazos** [comment]
@gpolaert, my bad but it missing unit tests.

**Comment by gpolaert** [comment]
Hello @osazos 

I think there is no test useful for the `getPerformanceNow()`, it's just an alias of `performance.now()`.
I can add a unit test to see if the elapsedTime is present on the events but I can't find the spec file of the events.

What do you want me to test?

**Comment by osazos** [comment]
Yep you right, it sounds overkill. Sorry for that.

**Review by osazos — APPROVED** [review]
LGTM

**Review by bretg — APPROVED** [review]
This is the prebid.js getEvents() function. Would suggest a documentation update, but won't require it.

**Comment by gpolaert** [comment]
> This is the prebid.js getEvents() function. Would suggest a documentation update, but won't require it.

Can do it, I will submit a PR to document the getEvents method soon

**Comment by bretg** [comment]
getEvents is documented, but sparsely. It doesn't mention the schema of what's in the results.

**Pull request merged**
