### PR TITLE
Rename idWardRtdProvider to anonymisedRtdProvider

### PR DESCRIPTION
**Pull request by kyrylenko**
## Type of change

- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Code style update (formatting, local variables)
- [x] Other

## Description of change
Introduced the **anonymisedRtdProvider** module as a replacement for the **idWardRtdProvider** because the company https://id-ward.com/ has been rebranded to https://www.anonymised.io/.
**idWardRtdProvider** module is maintained for backward compatibility until the next major Prebid release (9.0)
Added `bidders` optional param.
Added “enable_download: false” flag to prevent installations of the old idWardRtdProvider module ([docs](https://github.com/prebid/prebid.github.io/pull/4702))

## Other information

A link to a PR on the docs repo: https://github.com/prebid/prebid.github.io/pull/4702

### CODE REVIEW

**Comment by jon-caines-idward** [comment]
Hi, @patmmccann we have further changes to make to the RTD module and wish to prioritise our work accordingly. Are we still expecting v9 in 2024 or could it come earlier? Also is there a better channel over which I can ask such questions? With thanks.

**Comment by bretg** [comment]
Renames are unfortunately pretty common, so RTD/ID modules need a way of supporting aliases. How can these guys move forward with allowing publishers to utilize the "anonymised" name for new integrations?

**Comment by kyrylenko** [comment]
Hi @bretg , In my latest commit after your review::
- Renamed all “ID Ward” mentions to “Anonymised” In the old module 
- Added “enable_download: false” flag to prevent installations of the old idWardRtdProvider module ([docs](https://github.com/prebid/prebid.github.io/pull/4702))

So now the changes comply with the [how do I change the name of my module](https://docs.prebid.org/dev-docs/faq.html#im-a-developer---how-do-i-change-the-name-of-my-module) guide, except the “change the old file so that it includes the new file” because there is a new parameter introduced in the new module, so re-exporting with the name alias is not an option
I believe now it’s ready to be merged

**Comment by bretg** [comment]
@patmmccann - looks like what's happened here is a copy of IDWard to

**Comment by patmmccann** [comment]
We plan to release prebid 9 in May or June

**Comment by patmmccann** [comment]
> So now the changes comply with the [how do I change the name of my module](https://docs.prebid.org/dev-docs/faq.html#im-a-developer---how-do-i-change-the-name-of-my-module) guide, except the “change the old file so that it includes the new file” because there is a new parameter introduced in the new module, so re-exporting with the name alias is not an option
I believe now it’s ready to be merged

We could potentially merge if you come up with a way to solve this problem

**Comment by jon-caines-idward** [comment]
> > So now the changes comply with the [how do I change the name of my module](https://docs.prebid.org/dev-docs/faq.html#im-a-developer---how-do-i-change-the-name-of-my-module) guide, except the “change the old file so that it includes the new file” because there is a new parameter introduced in the new module, so re-exporting with the name alias is not an option
> > I believe now it’s ready to be merged
> 
> We could potentially merge if you come up with a way to solve this problem

@patmmccann can you define the problem we are trying to solve? Are you saying that we cannot update the RTD module to the new version as it has an additional parameter to the last one? Surely, there must be a way to iterate its functionality. Please help me break this down for our engineers to understand. Thanks.

**Comment by bretg** [comment]
@jon-caines-idward - the problem is that you aren't allowed to make a breaking change until a major release.

But also it sounds like @patmmccann doesn't want you to completely duplicate the code because of maintenance drift. So perhaps you could come up with a way to "include" the new name as part of the old code base, or some kind of alias?

**Comment by patmmccann** [comment]
>> there is a new parameter introduced in the new module, so re-exporting with the name alias is not an option
>@patmmccann can you define the problem we are trying to solve? 

The problem is you aren't following the guidelines on how to rename an adapter, which requires you to import the old adapter. If you are trying to add a new required parameter, that is also a breaking change and not allowed to be done in a minor version. If it is an optional parameter, it seems you can add it to the old adapter as well and import the new adapter from it.

**Comment by kyrylenko** [comment]
Hi @patmmccann , I’ve introduced the correction.
The new parameter I made optional.
All the changes are implemented in the new anonymisedRtdProvider.js, while the old idWardRtdProvider.js module just re-exports the needed functionality.
The current implementation completely follows the [guidelines on how to rename an adapter](https://docs.prebid.org/dev-docs/faq.html#im-a-developer---how-do-i-change-the-name-of-my-module)

**Comment by kyrylenko** [comment]
Hi @bretg I wanted to follow up on the pull request I recently updated - I believe now the PR completely fulfills the requirements. Could you please review it at your earliest convenience? Thank you!

**Comment by bretg** [comment]
@ChrisHuie - this looks better to me. Over to you and the team for a proper review.

**Comment by jon-caines-idward** [comment]
Hello Team Prebid, is there any news on Prebid v9 and when we could expect our revised RTD module in the solution? WIth thanks c.c. @bretg @ChrisHuie @patmmccann

**Comment by patmmccann** [comment]
Actually this is ready to merge now, thanks for your changes!

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
