### PR TITLE
ttd Bid Adapter: add regression test topmost domain

### PR DESCRIPTION
**Pull request by gielow**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Comment by gielow** [comment]
Adding a regression test for tydBidAdapter to avoid regression.

**Comment by gielow** [comment]
@patmmccann

**Comment by patmmccann** [comment]
thanks for this commit! Can you describe briefly the goal here? It seems to be adding tests to confirm the logic in refererDetection works for you going forward? Is this because you are comfortable with what is being sent over the wire with the latest merge @jlquaccia did? #9241

**Comment by gielow** [comment]
> thanks for this commit! Can you describe briefly the goal here? It seems to be adding tests to confirm the logic in refererDetection works for you going forward? Is this because you are comfortable with what is being sent over the wire with the latest merge @jlquaccia did? #9241

We had an internal issue, so I created a test that replicated our client's scenario that failed with the previous code. Then I used the changes from #9241 to confirm it works as intended.
We also want to avoid that future changes to the common/core code causing regression to our clients.

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
