### PR TITLE
Vidoomy Bid Adapter: bugfix for cookie sync with pixel fires

### PR DESCRIPTION
**Pull request by SasanFarrokh**
## Type of change

- [x] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Review by vidoomy — APPROVED** [review]

**Comment by ChrisHuie** [comment]
@SasanFarrokh can you please remove your package-lock file from this pr please. Also, it looks like our tests didn't kick off for this pr. That usually happens when you are following your fork of Prebid in CircleCI instead of the main project.

**Comment by SasanFarrokh** [comment]
I've reverted the changes on package-lock.
I think there's an issue on CircleCI with my account, Could I propose to run the tests localy with this PR?

image

Thanks BTW

**Comment by ChrisHuie** [comment]
@SasanFarrokh our integration tests check ie11 and for some other things. I will run this through circleci today on my side and if it passes will merge this :)

**Comment by SasanFarrokh** [comment]
@ChrisHuie 
Hey, Please tell me if I could help with anything, Thanks :raised_hands:

**Comment by ChrisHuie** [comment]
@SasanFarrokh running these changes through circleci now

**Comment by ChrisHuie** [comment]
@SasanFarrokh so per the above pr I tested it looks like fetch isn't supported in ie11. We are supporting ie11 for a couple more months. Can you change please.

**Comment by SasanFarrokh** [comment]
@ChrisHuie Done, switched to xhr

**Comment by ChrisHuie** [comment]
> @ChrisHuie Done, switched to xhr

Awesome. Will try and get this merged today if it now passes. Thanks for your patience :)

**Comment by ChrisHuie** [comment]
@SasanFarrokh can you please remove the index.html file from this pr and then looks like it is good to go :)

**Comment by SasanFarrokh** [comment]
@ChrisHuie index.html file removed, Thanks for your effort :raised_hands:

**Pull request merged**
