### PR TITLE
User ID's (liveramp, britepool) and gdpr

### PR DESCRIPTION
**Pull request by HuddledMasses**
## Type of change
- [x] Feature

## Description of change
Added support of user identeties and gdpr

### CODE REVIEW

**Comment by harpere** [comment]
Also the tests failed, but for some reason are running under your organization so I can't rerun them

**Comment by HuddledMasses** [comment]
@harpere For some reason ci fails with error 
`10 03 2020 12:44:16.716:ERROR [launcher]: Cannot load browser "bs_edge_17_windows_10"!
  Error: Username is required.`
and similar for other browsers
But local gulp test finishes successfuly
`[10:53:39] Using gulpfile ~/Documents/work/nodejs/prebid/testing/Prebid.js/gulpfile.js
[10:53:39] Starting 'test'...
[10:53:39] Starting 'clean'...
[10:53:39] Finished 'clean' after 13 ms
[10:53:39] Starting 'lint'...
[10:53:57] Finished 'lint' after 18 s
[10:53:57] Starting 'test'...

START:
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
14 04 2020 10:54:29.135:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
14 04 2020 10:54:29.137:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
14 04 2020 10:54:29.175:INFO [launcher]: Starting browser ChromeHeadless
14 04 2020 10:54:29.624:INFO [HeadlessChrome 81.0.4044 (Linux 0.0.0)]: Connected on socket Quc2Ua8zOoNtF7wzAAAA with id 78421739
LOG: Object{pubcid: '203a0692-f728-4856-87f6-9a25a6b63715'}
ERROR: '{"bidderCode":"tribeos","width":300,"height":250,"statusMessage":"Bid available","adId":"2041cbb1911a0d8","requestId":"21f3e9c3ce92f2","mediaType":"banner","source":"client","creativeId":"5e0b71e6823bb66fcb6c9858","cpm":1.1,"ad":"<html></html>","currency":"USD","netRevenue":true,"ttl":180}'

Finished in 5.192 secs / 3.06 secs @ 10:54:36 GMT+0300 (Eastern European Summer Time)

SUMMARY:
✔ 4646 tests completed
ℹ 2 tests skipped
[10:54:36] Finished 'test' after 39 s
[10:54:36] Finished 'test' after 56 s`

**Comment by HuddledMasses** [comment]
Added docs https://github.com/prebid/prebid.github.io/pull/1920

**Comment by harpere** [comment]
ran tests locally and they pass.  thx for adding docs.

**Pull request merged**
