### PR TITLE
Weborama RTD submodule: specify list of bidders to share data

### PR DESCRIPTION
**Pull request by peczenyj**
## Type of change

- [X] Feature

## Description of change
Enhance the support of bidders to share data, add some internal refactors.

Changes:
1. add new data source: sfbx lite. It is a site-centric data stored on local storage.
2. hability to specify what bidders we want to share what data. By default we share with all bidders available. We can also specify the list of ad units per bidder.
3. hability to specify what ad units we want to set targeting. By default we set on all ad units
4. hability to customize, in real time, the data shared or targeting per ad unit / bidder.
5. more unit tests

You can check the documentation:

https://github.com/Weborama/Prebid.js/blob/specify-list-of-bidders-to-share-data/modules/weboramaRtdProvider.md

and compare with the current version

https://docs.prebid.org/dev-docs/modules/weboramaRtdProvider.html#weborama-rtd-segmentation-module

- contact email of the adapter’s maintainer: tpeczenyj@weborama.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/ is here: https://github.com/prebid/prebid.github.io/pull/3745

### CODE REVIEW

**Comment by peczenyj** [comment]
Sorry guys but I submit this PR 2 weeks ago, is there any prevision of when it can be merged?

Thanks

**Review by Fawke — COMMENTED** [review]
Hi @peczenyj,

Thanks for waiting, sorry for the delay. This mostly looks good, but since it's quite a big PR to go through, do you mind adding a bit more specifics of the change in the PR description?

It'll be easier for me to understand the change and provide feedback if needed. Thanks.

**Comment by peczenyj** [comment]
Sure @Fawke

**Review by Fawke — APPROVED** [review]
Thanks for adding description. This change looks good.

**Pull request merged**
