### PR TITLE
feat(sublimeBidAdapter): updating sublimeBidAdapter module

### PR DESCRIPTION
**Pull request by fgcloutier**
## Type of change

- [x] Feature

## Description of change

- handle new notifyId parameter;
- bumping version to **0.6.0**

## Test parameters for validating bids:

```
{
  bidder: 'sublime',
  params: {
    zoneId: 1,
    notifyId: 42
  }
}
```

### CODE REVIEW

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/2353

**Comment by bmwcmw** [comment]
Hi @fgcloutier it's not blocking, is it planned that some fields like notifyId and transactionId are not ensured by the test?

**Comment by fgcloutier** [comment]
> Hi @fgcloutier it's not blocking, is it planned that some fields like notifyId and transactionId are not ensured by the test?

Hi @bmwcmw !
Thanks for your careful attention on this. These fields are only processed on backend, so no, we do not plan to test them in our adapter - at least for now.

**Review by bmwcmw — APPROVED** [review]
LGTM

**Pull request merged**
