### PR TITLE
AcuityAds adapter: fix issue with download

### PR DESCRIPTION
**Pull request by AcuityAdsIntegrations**
issue - `{"error":"Prebid file not built properly","requestId":"f4d9462b-43d3-401e-8cf3-8881b89340a8"}`

### CODE REVIEW

**Comment by AcuityAdsIntegrations** [comment]
@ChrisHuie please react

**Comment by ChrisHuie** [comment]
@AcuityAdsIntegrations Are you getting this error from the download page? Name capitalization shouldn't make a difference since it is consistent.

**Comment by AcuityAdsIntegrations** [comment]
> @AcuityAdsIntegrations Are you getting this error from the download page? Name capitalization shouldn't make a difference since it is consistent. This would be a breaking change for anyone pointing to the current file namespace.

Yes, from [download page](https://docs.prebid.org/download.html). I followed the [following](https://github.com/prebid/Prebid.js/issues/9037) issue

**Review by patmmccann — APPROVED** [review]

**Comment by bretg** [comment]
Rather than create a breaking change for publishers, we added a new feature to the download page that allows the bidders filename to differ from the biddercode. https://github.com/prebid/prebid.github.io/pull/4186

**Pull request merged**
