### PR TITLE
Retailspot Bid Adapter : initial release

### PR DESCRIPTION
**Pull request by rs-guian**
## Type of change

New bidder adapter 

- contact email of the adapter’s maintainer
guillaume@retail-spot.io

- link to new documentation on prebid.github.io:
https://github.com/prebid/prebid.github.io/pull/4490

- test parameters for validating bids:
```
{
  bidder: 'retailspot',
  params: {
    placement: 'test-1234'
  }
}
```

## Other information
I'll add unit tests and documentation on prebid.github.io
have a look at the basic test page:

https://retailspot.github.io/RSPlayer-Demo/testPages/prebid/simple.html?pbjs_debug=true

### CODE REVIEW

**Comment by rs-guian** [comment]
I don't understand, event when professor prebid is showing retailspot bid, the ad won't show up...
Any idea why ? 

```
{
input:{
bidder:"retailspot"
params:{
placement:"test-1234"
env:"prod"
}
crumbs:{
pubcid:"a2ad6a32-c9b8-462d-8e9e-98792f7583cf"
}
}
bidResponse:{
eventType:"bidResponse"
args:{
bidderCode:"retailspot"
width:300
height:250
statusMessage:"Bid available"
adId:"34481953cb706d"
requestId:"2d521c9c1fe05d"
transactionId:"597c81e5-09b3-4271-b311-f7557fbd651a"
auctionId:"8ce454b6-7dbf-4e66-8ee0-47c1b86c9503"
mediaType:"banner"
source:"client"
ttl:3600
creativeId:"Test-1234"
cpm:10
netRevenue:true
currency:"USD"
...
```


I don't see any blocking issue on this  log output   do you ? 
I've included all module, building in dev mode and did not include any CMP config...
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
utils.js:273 Prebid INFO: Prebid.js v7.44.0-pre loaded
utils.js:273 Prebid INFO: *BidAdapter 1.0.1 was loaded
utils.js:273 Prebid INFO: *BidAdapter 2.8.0 was loaded
utils.js:266 Prebid MESSAGE: Initializing UDM Adapter. PBJS Version: 7.44.0-pre with adapter version: 7.30V  Updated 2023 01 26
utils.js:280 Prebid WARNING: Viewability module should not be used. See https://github.com/prebid/Prebid.js/issues/8928
logWarn @ utils.js:280
init @ viewability.js:6
./modules/viewability.js @ viewability.js:9
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ viewability.js:1
(anonyme) @ viewability.js:1
webpackJsonpCallback @ jsonp chunk loading:36
(anonyme) @ vidoomyBidAdapter.js:1
(anonyme) @ prebid-footer.js:1
utils.js:266 Prebid MESSAGE: Emitting event for: auctionDebug
utils.js:273 Prebid INFO: Invoking pbjs.addAdUnits Arguments [Array(1), callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:266 Prebid MESSAGE: Emitting event for: addAdUnits
utils.js:273 Prebid INFO: USPAPI consentManagement module has been activated using default values (api: 'iab', timeout: 50ms)
utils.js:280 Prebid WARNING: USP CMP not found. Resuming auction without consent data as per consentManagement config.
logWarn @ utils.js:280
(anonyme) @ consentManagementUsp.js:235
done @ consentManagementUsp.js:194
onError @ consentManagementUsp.js:206
lookupUspConsent @ consentManagementUsp.js:100
loadConsentData @ consentManagementUsp.js:210
requestBidsHook @ consentManagementUsp.js:233
(anonyme) @ perfMetrics.js:379
measureHookTime @ perfMetrics.js:153
(anonyme) @ perfMetrics.js:378
next @ index.js:328
trap @ index.js:347
requestBids @ prebid.js:667
(anonyme) @ simple.html?pbjs_debug=true:49
(anonyme) @ prebid.js:1082
processQueue @ prebid.js:1079
__webpack_modules__../src/prebid.js.pbjsInstance.processQueue @ prebid.js:1096
(anonyme) @ prebid-footer.js:3
utils.js:266 Prebid MESSAGE: Emitting event for: auctionDebug
2utils.js:273 Prebid INFO: bidderSettings denied access to device storage for bidder 'adagio'
utils.js:280 Prebid WARNING: Adagio: script not found.
logWarn @ utils.js:280
adagioScriptFromLocalStorageCb @ adagioBidAdapter.js:147
(anonyme) @ adagioBidAdapter.js:176
(anonyme) @ storageManager.js:54
runAll @ prebid.js:763
executeCallbacks @ prebid.js:756
next @ index.js:328
(anonyme) @ perfMetrics.js:288
(anonyme) @ consentManagementUsp.js:237
done @ consentManagementUsp.js:194
onError @ consentManagementUsp.js:206
lookupUspConsent @ consentManagementUsp.js:100
loadConsentData @ consentManagementUsp.js:210
requestBidsHook @ consentManagementUsp.js:233
(anonyme) @ perfMetrics.js:379
measureHookTime @ perfMetrics.js:153
(anonyme) @ perfMetrics.js:378
next @ index.js:328
trap @ index.js:347
requestBids @ prebid.js:667
(anonyme) @ simple.html?pbjs_debug=true:49
(anonyme) @ prebid.js:1082
processQueue @ prebid.js:1079
__webpack_modules__../src/prebid.js.pbjsInstance.processQueue @ prebid.js:1096
(anonyme) @ prebid-footer.js:3
utils.js:266 Prebid MESSAGE: Emitting event for: auctionDebug
utils.js:273 Prebid INFO: bidderSettings denied access to device storage for bidder 'adagio'
utils.js:266 Prebid MESSAGE: pbjs: pubcid = a3459348-0d65-4fd5-a647-c0de9495b77a
utils.js:266 Prebid MESSAGE: Emitting event for: requestBids
utils.js:273 Prebid INFO: Invoking pbjs.requestBids Arguments [{…}, callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:266 Prebid MESSAGE: Emitting event for: beforeRequestBids
utils.js:273 Prebid INFO: Bids Requested for Auction with id: 8c989f93-13fd-41e4-b617-c8992ad71490 [{…}]
utils.js:266 Prebid MESSAGE: Emitting event for: auctionInit
utils.js:266 Prebidretailspot MESSAGE: CALLING BIDDER
utils.js:266 Prebidretailspot MESSAGE: Emitting event for: bidRequested
utils.js:266 Prebidretailspot MESSAGE: Emitting event for: beforeBidderHttp
utils.js:266 Prebidretailspot MESSAGE: Emitting event for: bidAdjustment
utils.js:273 Prebidretailspot INFO: suppressing empty key 'hb_deal' from adserver targeting
utils.js:273 Prebidretailspot INFO: suppressing empty key 'hb_acat' from adserver targeting
utils.js:266 Prebidretailspot MESSAGE: Emitting event for: bidResponse
utils.js:273 Prebid INFO: Bids Received for Auction with id: 8c989f93-13fd-41e4-b617-c8992ad71490 [Bid]0: Bidad: "<script type='text/javascript'>window.RetailSpotConfig = {preloaded: '<VAST version=\"3.0\"><Ad id=\"123\" type=\"front\"><InLine><AdSystem>DSP</AdSystem><AdTitle>adTitle</AdTitle><Impression id=\"11111\"><![CDATA[http://impressionv1.track.com]]></Impression><Impression id=\"11112\"><![CDATA[http://impressionv2.track.com]]></Impression><Creatives><Creative id=\"987\"><Linear><Duration>00:00:30</Duration><TrackingEvents><Tracking event=\"start\"><![CDATA[http://track.xxx.com/q/start?xx]]></Tracking><Tracking event=\"firstQuartile\"><![CDATA[http://track.xxx.com/q/firstQuartile?xx]]></Tracking><Tracking event=\"midpoint\"><![CDATA[http://track.xxx.com/q/midpoint?xx]]></Tracking><Tracking event=\"thirdQuartile\"><![CDATA[http://track.xxx.com/q/thirdQuartile?xx]]></Tracking><Tracking event=\"complete\"><![CDATA[http://track.xxx.com/q/complete?xx]]></Tracking></TrackingEvents><MediaFiles><MediaFile delivery=\"progressive\" type=\"video/mp4\" width=\"1024\" height=\"576\"><![CDATA[https://cdn.stickyadstv.com/www/images/1923863841-tv-mp4-6006ab69204df_4.mp4]]></MediaFile></MediaFiles></Linear></Creative></Creatives></InLine></Ad></VAST>',width: 400,height: 225,format: '',target: document.currentScript.parentElement,}var s = document.createElement('script');s.src = 'https://static.retail-spot.io/rsplayer.js';s.setAttribute('async', '');document.body.appendChild(s);\t</script>"adId: "3ab1de111b7d2d"adUnitCode: "/19968336/header-bid-tag-0"adapterCode: "retailspot"adserverTargeting: {hb_bidder: 'retailspot', hb_adid: '3ab1de111b7d2d', hb_pb: '10.00', hb_size: '400x225', hb_source: 'client', …}auctionId: "8c989f93-13fd-41e4-b617-c8992ad71490"bidder: "retailspot"bidderCode: "retailspot"cpm: 10creativeId: "Test-1234"currency: "USD"getIdentifiers: ƒ ()getSize: ƒ ()getStatusCode: ƒ ()height: 225mediaType: "banner"meta: {advertiserDomains: Array(0), dchain: {…}}metrics: {startTiming: ƒ, measureTime: ƒ, measureHookTime: ƒ, checkpoint: ƒ, timeSince: ƒ, …}netRevenue: trueoriginalCpm: 10originalCurrency: "USD"pbAg: "10.00"pbCg: ""pbDg: "10.00"pbHg: "10.00"pbLg: "5.00"pbMg: "10.00"requestId: "2309d1c4ae5022"requestTimestamp: 1681889358827responseTimestamp: 1681889358902size: "400x225"source: "client"status: "targetingSet"statusMessage: "Bid available"timeToRespond: 75transactionId: "89638e00-7488-44a1-becd-fa07bfa7355c"ttl: 3600width: 400[[Prototype]]: Objectlength: 1[[Prototype]]: Array(0)
utils.js:266 Prebid MESSAGE: Emitting event for: auctionEnd
utils.js:266 Prebid MESSAGE: Emitting event for: tcf2Enforcement
utils.js:273 Prebid INFO: Invoking pbjs.setTargetingForGPTAsync Arguments [callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:273 Prebid INFO: allowTargetingKeys - allowed keys [ hb_bidder, hb_adid, hb_pb, hb_size, hb_deal, hb_format, hb_uuid, hb_cache_host, hb_native_title, hb_native_body, hb_native_body2, hb_native_privacy, hb_native_privicon, hb_native_brand, hb_native_image, hb_native_icon, hb_native_linkurl, hb_native_displayurl, hb_native_cta, hb_native_rating, hb_native_address, hb_native_downloads, hb_native_likes, hb_native_phone, hb_native_price, hb_native_saleprice, hb_renderer_url, hb_adTemplate ]
utils.js:273 Prebid INFO: allowTargetingKeys - removed keys [ hb_source, hb_adomain, hb_source_retailspot, hb_adomain_retailspo ]
utils.js:266 Prebid MESSAGE: Attempting to set targeting-map for slot: div-1 with targeting-map: {hb_format: 'banner', hb_size: '400x225', hb_pb: '10.00', hb_adid: '3ab1de111b7d2d', hb_bidder: 'retailspot', …}
utils.js:266 Prebid MESSAGE: Emitting event for: setTargeting
utils.js:266 Prebidretailspot MESSAGE: Emitting event for: bidderDone
utils.js:273 Prebid INFO: AdxPremium Analytics - Everything ready
topics_frame.html?bidder=pubmatic:29 document.browsingTopics() not supported
utils.js:273 Prebid INFO: Invoking pbjs.onEvent Arguments(2) ['auctionInit', ƒ, callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:273 Prebid INFO: Invoking pbjs.onEvent Arguments(2) ['auctionEnd', ƒ, callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:273 Prebid INFO: Invoking pbjs.onEvent Arguments(2) ['bidRequested', ƒ, callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:273 Prebid INFO: Invoking pbjs.onEvent Arguments(2) ['bidResponse', ƒ, callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:273 Prebid INFO: Invoking pbjs.onEvent Arguments(2) ['noBid', ƒ, callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:273 Prebid INFO: Invoking pbjs.onEvent Arguments(2) ['bidWon', ƒ, callee: (...), Symbol(Symbol.iterator): ƒ]
utils.js:273 Prebid INFO: Invoking pbjs.getEvents
utils.js:273 Prebid INFO: Invoking pbjs.getEvents
utils.js:273 Prebid INFO: Trustpid module: Unsupported message caught. Origin: https://www.google.com, data: _grecaptcha_ready.
utils.js:273 Prebid INFO: Invoking pbjs.getEvents
```

**Comment by rs-guian** [comment]
Here is a log from GPT on Slot renderered event.  
it says the slot is empty ... 

`
Slot has been rendered:
{serviceName: 'publisher_ads', slot: om, isEmpty: true, slotContentChanged: true, size: null, …}
`

**Comment by ChrisHuie** [comment]
@rs-guian can you remove the changes to the packag-lock file from this pr please 🙏

**Comment by rs-guian** [comment]
@ChrisHuie   Sure,  sry about that.

Do you have any clue on the reason why no ad can be seen at :
https://retailspot.github.io/RSPlayer-Demo/testPages/prebid/simple.html?pbjs_debug=true

 ?

**Comment by Rothalack** [comment]
Hey @rs-guian just quickly popping in, I see this error from your test page.

ERROR: Error trying to write ad Id : to the page. Missing adId

This is likely the best thing to track down to figure out why you aren't seeing an ad display. When I find more time I'll see what I can find, but thought I'd come drop this here quickly for you!

**Comment by rs-guian** [comment]
Thank you [Rothalack](https://github.com/Rothalack) for your feedback.
everything seems fine now.

**Pull request merged**
