### PR TITLE
dgkeyword RTD Provider: add new real time data module 

### PR DESCRIPTION
**Pull request by mediaconsortium-develop**
## Type of change

- [ X ] Feature
https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders --> 
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ X ] Other

## Description of change

We want to add Real Time Data Submodule

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.
https://www.suuiiisya.com/test/agytest/rt_module_test.html

- contact email of the adapter’s maintainer
mediaconsortium-develop@bi.garage.co.jp

- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/mediaconsortium-develop/Prebid.js/blob/feature/dgkeywordRtdProvider/modules/dgkeywordRtdProvider.md

## Other information

we want to set some keywords before requestBids() in our customer's site.
The keywords are real time data and can be got to access our partner's service site.
So we want to start requestBids() after getting keywords only when our keywords service use.

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@osazos I tested this a few times and looks stable to me

**Comment by mediaconsortium-develop** [comment]
Thank you for merging to muster.
Now I checked prebid.js download site, and I found that dgkeyword real time sub-module can not select.
I think dgkeyword real time sub-module can use only when using gult build.
https://docs.prebid.org/download.html

So I want to change, our dgkeyword real time sub-module can download from the prebid.js download site.

I edited the pull request($6912) first message "official adapter submission" check on .
Will you please update the prebid.js download site?

**Comment by mediaconsortium-develop** [comment]
Thank you for merging to muster.
Now I checked prebid.js download site, and I found that dgkeyword real time
sub-module can not select.
I think dgkeyword real time sub-module can use only when using gulp build.
https://docs.prebid.org/download.html

So I want to change, our dgkeyword real time sub-module can download from
the prebid.js download site.

I edited the pull request($6912) first message "official adapter
submission" check on .
Will you please update the prebid.js download site?

2021年6月3日(木) 0:33 'Olivier' via ***@***.*** <
***@***.***>:

**Comment by patmmccann** [comment]
Please file as a new issue

**Comment by patmmccann** [comment]
Or open a pr similar to

https://github.com/prebid/prebid.github.io/pull/3005/files

**Pull request merged**
