### PR TITLE
tappx Bid Adapter: update isBidRequestValid and fix request url

### PR DESCRIPTION
**Pull request by prebidtappx**
## Type of change

- [X] Bugfix

## Description of change

- We've updated the mandatory parameters in isBidRequestValid
- We've made a fix by defining the request url
- We have updated the sizes that we allow in the tappxBidAdapter.md

### CODE REVIEW

**Comment by prebidtappx** [comment]
Excuse me, but I just realized that a change of an adapter that doesn't correspond to me (outbrainBidAdapter.js) has been included in the pull request, would it be possible to discard it, please?
Thank you

**Comment by ChrisHuie** [comment]
@prebidtappx do any new tests need to be added to the classic or new endpoints regex?

**Comment by prebidtappx** [comment]
Hello @ChrisHuie ,

initially we would not need to test that part, unless you tell us otherwise.
We are developing the video outstream feature, and in any case, we will improve the tests at that time to extend the test-coverage.
It's possible?

Thanks

**Comment by ChrisHuie** [comment]
@prebidtappx is the video outstream pr on the near horizon? If it coming down the pipeline in the coming weeks I'm fine waiting for those tests as what sounds like a more holistic update. Otherwise, it's kind of on the fence for me in terms of maintaining test coverage versus not wanting to add tests just for the sake of adding more tests.

**Comment by prebidtappx** [comment]
Hello @ChrisHuie ,

Although the outstream video pr should be done in the short term, following your feedback, we have decided to updated the tests for isValidRequest. In this way we cover the main changes in this update.

Thank you

**Comment by ChrisHuie** [comment]
Thank you :)

**Comment by patmmccann** [comment]
@prebidtappx please note the regex errors this introduced flagged at https://lgtm.com/projects/g/prebid/Prebid.js/alerts/?mode=list

**Pull request merged**
