### PR TITLE
Rule enforcement: support for floors must include the floors module

### PR DESCRIPTION
**Pull request by patmmccann**
## Type of change
- [X] Other

## Description of change
Enforcement of https://github.com/prebid/Prebid.js/issues/6465 for https://github.com/prebid/Prebid.js/issues/5966 release

I have tried to remove floor support for recently maintained adapters when possible, otherwise adapters were removed.

### CODE REVIEW

**Comment by patmmccann** [comment]
Ozone and EMX not included because of in progress efforts noted at https://github.com/prebid/Prebid.js/issues/6754 by @askrupert-dm and https://github.com/prebid/Prebid.js/pull/6797 by @EMXDigital

**Comment by patmmccann** [comment]
anticipating conflicts on https://github.com/prebid/Prebid.js/pull/6820/files ; will remove from those changes from this pr

**Comment by patmmccann** [comment]
sspbc changes removed, ready for review

**Review by ChrisHuie — APPROVED** [review]

**Comment by robertrmartinez** [comment]
What happened to this file

`test/spec/modules/smilewantedBidAdapter_spec.js`


Looks like it was renamed to

`test/spec/smilewantedBidAdapter_spec.js`

Which is not correct I believe.

**Comment by patmmccann** [comment]
> What happened to this file
> 
> `test/spec/modules/smilewantedBidAdapter_spec.js`
> 
> Looks like it was renamed to
> 
> `test/spec/smilewantedBidAdapter_spec.js`
> 
> Which is not correct I believe.
> 
> Very last change of files when I look at it:
> 
> image

fixed ty

**Comment by robertrmartinez** [comment]
I counted
- 29 modules removed
- 26 Spec files removed

I may have missed something but should this be equal number?

**Comment by patmmccann** [comment]
Not every module had a spec file

**Comment by robertrmartinez** [comment]
Also I just realized I double counted some because the `.md` file!

**Comment by robertrmartinez** [comment]
Looks good.

The changes where we removed the ability to pass a floor, but just set it to default is what we want for sure right?

Seems like the right thing imo.

Thanks this was a lot of work I am sure!

**Comment by patmmccann** [comment]
We're hoping those adapters, eg spotx, add support shortly. The only other option I can think of is removing them, so I tried for any adapter that seemed recently maintained to set the default. The deletions are almost all not maintained.

**Pull request merged**
