### PR TITLE
Adding an adapter for Adequant

### PR DESCRIPTION
**Pull request by relegit**
Hope I'm using this right

### CODE REVIEW

**Comment by mkendall07** [comment]
Hi @relegit 

Can you please include an example file update along with test params that can be used to get bid responses? 
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html

**Comment by relegit** [comment]
Here you go
Also fixed up the indentation slightly, and changed the lone {id} to the actual expected tag name, consistent with the rest of the example

**Comment by headerbidding** [comment]
I can confirm that the Adequqnt adapter works.

**Comment by relegit** [comment]
@mkendall07 please merge if you have no more requirements

**Comment by protonate** [comment]
This looks good. Please provide working test params for end-to-end tests, apply code style fixes and flatten commits and we'll get this merged. Also add "adequant" to the "adapters" array in [package.json](https://github.com/prebid/Prebid.js/blob/master/package.json#L9) as described in step 3 of the [Configure](https://github.com/prebid/Prebid.js#configure) section of the README such that the build will include this adapter.

Thanks for contributing.

**Comment by protonate** [comment]
Hi @relegit any update on this?

**Comment by Fry-kun** [comment]
@protonate
* by "test params for end-to-end tests" do you mean you need a live account on our system?
* code style fixes: what's the required code style?
* I'm not familiary enough with git, how do you flatten commits?

**Comment by relegit** [comment]
@protonate
* by "test params for end-to-end tests" do you mean you need a live account on our system?
* code style fixes: what's the required code style?
* I'm not familiary enough with git, how do you flatten commits?

**Comment by protonate** [comment]
As more adapters are added it becomes increasingly important to be sure that code changes are working with each adapter, so we ask for a set of live account params. These can be sent to us via our github email address (ncozi at appnexus dot com) if you prefer.

Code style is defined in the .jscs and .jshint files found in project root. These can be incorporated into your IDE to assist with conforming to code style.

Flattening, or squashing, commits allows us to use a single commit for a given PR. This gives us a commit log that describes the functional changes to the project without all of the intermediate steps a developer took to get there. This comes in very handy when composing release notes, among other things. This git-ready [article](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) describes how to do this.

If you would prefer we can apply code style changes and flatten commits, just let us know.

Thanks.

**Comment by relegit** [comment]
Created #281 squashed, please merge it

**Comment by protonate** [comment]
Closing this in favor of #281

**Pull request closed without merging**
