### PR TITLE
Add GourmetAds AppNexus Alias

### PR DESCRIPTION
**Pull request by tmoerschbacher**
Adding Gourmet Ads as an alias of AppNexus adapter.

### CODE REVIEW

**Comment by mkendall07** [comment]
LGTM.

**Comment by chefbenjamin** [comment]
@matthewlane @mkendall07 @tmoerschbacher Given the addition, will this be added to the front page of prebid.org ? What else do we need to provide ?

**Comment by tmoerschbacher** [comment]
Hi @chefbenjamin, no other info is required.  Would you like to have Gourmet show as an option on the download page (http://prebid.org/download.html)?  It is not something included here, but we can make that happen if you'd like.

**Comment by chefbenjamin** [comment]
@tmoerschbacher I see you've done it already. thanks mate.

**Comment by viddyrizkiyansah** [comment]
Hi,

Sorry for jump in, please advice if we want to be a bidder on appnexus adapter like gourmet ads, what we have to do ?

so our publisher who already using appnexus can add us in their Header Bidding as aliases

Thank you

**Pull request merged**
