### PR TITLE
Qc/qc usersyncs

### PR DESCRIPTION
**Pull request by SleimanJneidi**
## Type of change

- [X] Feature

## Description of change

Adds support for userSyncs in QC adapter

- inventoryteam@quantcast.com

### CODE REVIEW

**Comment by SleimanJneidi** [comment]
@harpere how would I do that?

**Comment by harpere** [comment]
there are 2 more arguments passed to getUserSyncs().  for example:
https://github.com/prebid/Prebid.js/blob/master/modules/rubiconBidAdapter.js#L751

**Comment by SleimanJneidi** [comment]
@harpere this will be appended on the server side

**Comment by SleimanJneidi** [comment]
@hadarpeer do you mind having another look please?

**Pull request merged**
