### PR TITLE
new boldwin bid adapter

### PR DESCRIPTION
**Pull request by Wls-demo**
## Type of change

- [x] New bidder adapter   

- test parameters for validating bids
```
{
  bidder: 'trendqube',
                            params: {
                                placementId: 0,
                                traffic: 'video'
                            }
}
{
                            bidder: 'trendqube',
                            params: {
                                placementId: 0,
                                traffic: 'banner'
                            }
                        }
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
wls_demo_box@smartyads.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/2112

### CODE REVIEW

**Comment by patmmccann** [comment]
can you copy bid.clickurl domain to bid.meta.advertiserDomains?

**Comment by Wls-demo** [comment]
@patmmccann  I've added meta with advert domains

**Comment by Wls-demo** [comment]
@patmmccann Good day to you, is there any updates? If thecase in failing circle ci - the problem in another adapter

**Comment by patmmccann** [comment]
I'm not the assigned reviewer; we just have buyer transparency as an initiative that widespread support for meta.AD is the first step of.

**Comment by Wls-demo** [comment]
@mike-chowla Good day to you,

**Comment by Wls-demo** [comment]
@mike-chowla Good day to you, is everything fine? Can you, please, close review

**Comment by Adprime** [comment]
@jaiminpanchal27 Good day to you, can i please ask you to assignee another reviewer to close this PR, because current seems have no activity since 14 of july

**Comment by mike-chowla** [comment]
I'll look at it today

**Pull request merged**
