### PR TITLE
remove nyan cat reporter as it slows down tests considerably

### LINKED ISSUE #774: Remove Nyan Karma reporter as it slows down testing 4x
## Type of issue
Question, build process, performance

## Description
Running unit tests without Nyan Karma reporter takes 1/4 of the time then when the Nyan reporter is enabled. I would advise removing it. To me, it doesn't give much value either.

## Steps to reproduce
Run `$ gulp test`.
- With Nyan: ~ 2mins, 2.5 mins for my colleague
- Without Nyan: ~ 30s

## Platform details
OS X El Capitan, Node.js 5 and 6

### PR DESCRIPTION
**Pull request by protonate**
## Type of change
- [x] Build related changes

## Description of change
Removes test coverage Nyan Cat reporter due to performance issues.

## Other information
fixes #774

### CODE REVIEW

**Comment by marian-r** [comment]
@protonate looks fine, thanks :)

**Comment by yairraz** [comment]
You would probably want to remove the karma-nyan-reporter plugin from the karma.conf.js plugins section and from package.json dev dependencies

**Comment by protonate** [comment]
@mkendall07 @yairraz PR updated

**Comment by mkendall07** [comment]
This didn't actually speed up running `gulp test` or `gulp serve` for me on a mac but I don't see any need for it so I'm good.

**Comment by marian-r** [comment]
@mkendall07 I tried it now, and it wasn't that much slower with Nyan reporter, but still about 10 seconds slower than without it. I'm not sure how I measured it last time. Maybe the difference is related to Chrome update? I don't see anything else being changed on my machine. Anyway, I found Nyan reporter quite useless and 10s speed up (25%) is still good :)

**Comment by mkendall07** [comment]
adios kitty.

**Comment by protonate** [comment]
I believe that incremental rebuilds on watched files is faster as well, haven't measured it.

**Comment by Studnicky** [comment]
Github does not have sad enough emojis to express how I feel about this.

**Pull request merged**
