### PR TITLE
Send debug info from adapter to external debugger

### PR DESCRIPTION
**Pull request by bjorn-lw**
## Type of change
- [x ] Feature

## Description of change
Send extended debug data from adapter to external debugger (Livewrapped wrapper) to track server side connections.

### CODE REVIEW

**Comment by bjorn-lw** [comment]
Merge?

**Comment by bjorn-lw** [comment]
@mkendall07 Would be awesome if this could be merged before 3.18 is released!

**Comment by bjorn-lw** [comment]
Would be really great if this change could be merged. Thanks.

**Comment by mkendall07** [comment]
@bjorn-lw this didn't get merged because the CircleCI tests are failing. I've retriggered the build now.

**Comment by bjorn-lw** [comment]
> @bjorn-lw this didn't get merged because the CircleCI tests are failing. I've retriggered the build now.

Yes, this is an extremely frustrating problem as I can't really do anything about it and I can't trigger a new build myself.

**Comment by mkendall07** [comment]
feel free to contribute to a resolution on that issue :). It's a bit thorny.

**Comment by mkendall07** [comment]
If the build continues the fail, please rebase off master and update the PR.

**Comment by bjorn-lw** [comment]
> feel free to contribute to a resolution on that issue :). It's a bit thorny.

I was expecting that answer :) You are right, I could probably do that. But time is not on my side.

**Comment by bjorn-lw** [comment]
@mkendall07 Picking up the latest changes from master seemed to do the trick. Is it still possible to merge in time for 3.19.0?

Thanks!

**Pull request merged**
