### PR TITLE
Between Bid Adapter: add sharedid support

### PR DESCRIPTION
**Pull request by ignat-one**
## Type of change

- [x] Feature

## Description of change
I have added sharedid support.

- contact email of the adapter’s maintainer: khaylov@betweenx.com
- [x] official adapter submission

### CODE REVIEW

**Comment by patmmccann** [comment]
Please indicate support with a docs pr

**Comment by ignat-one** [comment]
Hi ✋  @ncolletti @patmmccann   I have [opened PR](https://github.com/prebid/prebid.github.io/pull/2840/commits/341ba749be16704373591a5025a843640c44d5fe) in prebid.github.io repo

**Comment by smenzer** [comment]
fyi that sharedid may be deprecated - https://github.com/prebid/Prebid.js/issues/6522

**Review by ncolletti — APPROVED** [review]
LGTM

**Comment by jeanstemp** [comment]
https://github.com/prebid/prebid.github.io/pull/2840

**Pull request merged**
