### PR TITLE
Add PubWise Bid Simulator

### PR DESCRIPTION
**Pull request by GLStephen**
## Type of change
- [X ] New bidder adapter   

## Description of change
Addition of PubWise Bid Simulator Adapter. The Bid Simulator is part of the testing package we use internally for PubWise.io. We are making it publicly available because we feel the Prebid community will get some value from it.

- test parameters for validating bids
```
{
        bidderCode: 'pubwiseSim',
        bids: [
          {
            bidId: 'testId1',
            bidder: 'pubwiseSim',
            params: {
              site_id: 'test-test-test-test',
              height: '728',
              width: '90',
              cpm: 20,
              delay: 0,
            },
            sizes: [[160, 600]],
            placementCode: 'div-gpt-test-1'
          }
        ]
      }
```
- stephenj@pubwise.io
- [ x ] official adapter submission

### CODE REVIEW

**Comment by GLStephen** [comment]
I have resolved the conflict related to the list of active adapters.

**Comment by mkendall07** [comment]
@GLStephen 
Could you explain the purpose of this? Just not sure is all.. thanks

**Comment by GLStephen** [comment]
@mkendall07 We use it, similar to an echo server, to perform automated testing in our test environment. It allows you to send "real" not code level mocked bid requests into your Prebid setup and test end-to-end configuration, analytics setup and DFP integration and timeout behavior.  I thought it would be useful to the Prebid community in general.

I really appreciate the value of unit testing at a code level in Prebid.js, but often it is insufficient for some types of testing. For instance, if you want to verify interaction of DFP and non-header bidding line items you can either use a test tag from a demand partner, wait for a bid of some value to happen by, or you can use PubWise Sim. 

In the end, PubWise Sim provides significantly more control over the response than a test tag does and lets you introduce latency, and other options such as mismatched sizes. In addition, you can set variable return pricing without having to twiddle an adunit ID (like a test tag likely would have you do) which lets you through code control testing with more ease.

**Comment by GLStephen** [comment]
Documentation is here: https://github.com/prebid/prebid.github.io/pull/241

**Comment by bretg** [comment]
@GLStephen - this is good background, and looks like a useful tool. I'd suggest adding some of the words from above into the prebid.github.io doc PR. Will make a specific suggestion over there.

**Comment by jaiminpanchal27** [comment]
@GLStephen I am getting 404 trying to hit your endpoint. Test page https://jsfiddle.net/61ak300m/

**Comment by GLStephen** [comment]
@jaiminpanchal27 endpoint is up now, sorry about that, it had not been made live on the production farm

**Comment by GLStephen** [comment]
@bretg updates have been made to the documentation piece

**Comment by jaiminpanchal27** [comment]
@GLStephen I checked this and it works fine. This is good testing utility but i don't think it should be developed as an adapter. Also no test related code should be inside `./src`

**Comment by GLStephen** [comment]
@jaiminpanchal27 I understand your concern. It's one of those "isn't exactly like, but must behave like to properly test" sorts of things. In some ways, it is accurate that this is a test, but the current testing in ./test is more like unit tests, not outside in testing. This is more of a black box outside in interaction with controls vs. a whitebox unit test. Is there an alternate place for this sort of thing that can provide the same level of testing interaction, particularly pre-prod style integration testing which is the focus here?

**Comment by jaiminpanchal27** [comment]
@GLStephen Yes our integration level test is not upto the mark yet. We have tried this using nightwatch and browserstack. You can check this PR https://github.com/prebid/Prebid.js/pull/982 for end to end testing.
Integration testing is also in discussion for Prebid 1.0. Add your thoughts here https://github.com/prebid/Prebid.js/issues/891

**Comment by mkendall07** [comment]
@GLStephen 
Appreciate the feedback on integration test with a focus on the publisher. I do believe we need this, but we don't want it as part of the codebase here. We are talking about building out a toolset to help with this but it's in the early stages.

**Pull request closed without merging**
