### PR TITLE
Adding a new Trion Interactive Adapter and associated tests to prebid.

### PR DESCRIPTION
**Pull request by grohm33**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change

Adding Trion adapter

- test parameters for validating bids
```
{
  bidder: 'trion',
  params: {
    pubId : 1,//required
    sectionId : 2,//required
    re : ''//third party redirect optional
  }
}
```
- contact email of the adapter’s maintainer
mgroh@trioninteractive.com
- [x] official adapter submission

### CODE REVIEW

**Comment by aneuway2** [comment]
Hey @grohm33 ,just a heads up that you may want to also submit a PR to have your adaptor documented on prebid.org :-)

https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders

**Comment by grohm33** [comment]
@aneuway2 I added the pull request for documentation.  Thanks for the heads up!

**Comment by grohm33** [comment]
@protonate We just set up a test ad to return from pubId : '30222' and sectionId : '5'.  In order for this to return a bid you also need to be mobile user agent.  Let me know if that works for you.  Thanks!

**Comment by protonate** [comment]
Thanks, getting bids back now with those test params, LGTM

**Pull request merged**
