### PR TITLE
Added US Privacy support in TrustX Bid Adapter

### PR DESCRIPTION
**Pull request by PWyrembak**
## Type of change

- [x] Feature

## Description of change
Added US Privacy support in TrustX Bid Adapter to send it in bid request as us_privacy parameter

- link to dev doc pull request - https://github.com/prebid/prebid.github.io/pull/1644

- paul@trustx.org
- [x] official adapter submission

### CODE REVIEW

**Comment by PWyrembak** [comment]
Hello we have added pull request in doc repository https://github.com/prebid/prebid.github.io/pull/1644

**Comment by PWyrembak** [comment]
Hi Prebid Team,

We noticed that despite the merge to master, TRUSTX’s update wasn’t included release notes: https://github.com/prebid/Prebid.js/releases/tag/2.43.0
Was this just an oversight? We see our code changes in v2.43, so we were wondering if the release notes can be updated to reflect TRUSTX support of CCPA.

Best,
Paul


PAUL WYREMBAK
TRUSTX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>

**Comment by jsnellbaker** [comment]
Hi @PWyrembak 

These changes were just merged to the master branch recently and will be part of the upcoming 2.44.0 release.  

I checked out the 2.43.0 version of Prebid.js and verified the USP changes for your adapter were not included in that version.  How were you checking it on your end?

Regards,
Jason

**Comment by PWyrembak** [comment]
Jason,

Sorry about that – we verified that the changes were in fact NOT present in 2.43 and I hit send too early.  We’ll wait for the changes to be released in 2.44.0.  Appreciate the quick response!


PAUL WYREMBAK
TRUSTX<http://www.trustx.org/> | Head of Technical Operations
530 Seventh Ave, New York, NY 10018
+1 631.428.9992<tel:+1%20631.428.9992>
[X Logo]<http://www.trustx.org/>

**Pull request merged**
