### PR TITLE
IX adapter: sending outstream error codes in request

### PR DESCRIPTION
**Pull request by lksharma**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Capturing configuration related errors to be passed into `cygnus` request

### CODE REVIEW

**Comment by Rothalack** [comment]
The error failing testing is
should clear errors with successful response
	DEFAULT_VIDEO_BIDDER_REQUEST_DATA is not defined
	@webpack:///test/spec/modules/ixBidAdapter_spec.js:1933:32 <- test/test_index.js:253600:9

It repeats this error every time DEFAULT_VIDEO_BIDDER_REQUEST_DATA is referenced.

**Comment by Rothalack** [comment]
Hey @lksharma, did you get a chance to look at the error?

**Comment by patmmccann** [comment]
can you add 'add gvlid' to ticket description so people see it in release notes and have more incentive to upgrade

**Comment by Rothalack** [comment]
Hey @lksharma , any update?

**Comment by lksharma** [comment]
Hi @Rothalack,

I will be closing this PR for now and resubmitting it at a later time.

**Comment by Rothalack** [comment]
Fair enough! Thanks.

**Pull request closed without merging**
