### PR TITLE
adpone: onBidWon implementation

### PR DESCRIPTION
**Pull request by seergiioo6**
## Type of change

- [ ] Bugfix
- [x ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Adpone bid adapter onBidWon implementation 

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by robertrmartinez** [comment]
@seergiioo6 Hello thanks,

I want to test this but the current test parameters given in the `adponeBidAdapter.md` file do not seem to work.

Actually I get a CORS issue when a request is made to the https://rtb.adpone.com/bid-request?pid=1234 endpoint.

Can you please help me configure my test parameters to return bids from the adpone endpoint and allow a full e2e test?

**Comment by seergiioo6** [comment]
Hi @robertrmartinez!

I've created a placementId for testing purposes: 11946231713535.

Are you sending requests from a browser? Our endpoint is only accessible from browsers. That could be the reason you are not getting a valid bid response...

TY!

**Comment by robertrmartinez** [comment]
@seergiioo6 

Thanks for providing the placementId `11946231713535`

However it returns a 0 price bid.

image

Technically every adapter is supposed to have constant valid params which always return valid test bids.

Can use `debug` module to alter CPMS as needed,

But your adapter filters out your `serverresponse` bids if the CPM is not > 0 if I am not mistaken.

**Comment by robertrmartinez** [comment]
@seergiioo6 As it is not part of this PR I will not reject it for not returning a valid bid.

But as for the bidWon event URL I got it to fire but it returns a 404 every time.

Is there certain things that need to happen?

image

**Comment by seergiioo6** [comment]
Hi @robertrmartinez! you're right! Our adapter filters out bids if the CPM is not > 0. Now 11946231713535 returns a valid CPM. 

On the other hand. We've already fixed the 404 error that you were getting.

Thank you very much.

**Comment by robertrmartinez** [comment]
Thank you @seergiioo6.

I do get a `CORB` Warning now from the URL fired. Not sure what is expected.

image

Otherwise LGTM will merge.

If it is possible, please update your adapter markdown to contain this placement ID into another PR as soon as possible so future users / reviewers can use it when testing your adapter.

**Pull request merged**
