### PR TITLE
mgidBidAdapter: Add gpid value to bid request's imp[].ext

### PR DESCRIPTION
**Pull request by Gaudeamus**
## Type of change

- [x] Updated bidder adapter 

## Description of change
Adding gpid value for each bid request impression. No api changes

### CODE REVIEW

**Comment by Gaudeamus** [comment]
Hello, as to deduplicating issue, I can't address it right now, and I will schedule time for this in the next sprints. 
For now can we proceed as is?

**Comment by Gaudeamus** [comment]
also, please explain how I should remedy the following, for both adapters are the same:

[modules/mgidBidAdapter.js](https://github.com/prebid/Prebid.js/blob/f5b1fc3003044f4fc65d22a336c2e634173e3d36/modules/mgidBidAdapter.js#L700-L705) has 7 duplicated lines with [modules/mgidBidAdapter.js](https://github.com/prebid/Prebid.js/blob/f5b1fc3003044f4fc65d22a336c2e634173e3d36/modules/mgidBidAdapter.js#L693-L698)

**Comment by patmmccann** [comment]
> also, please explain how I should remedy the following, for both adapters are the same:
> 
> [modules/mgidBidAdapter.js](https://github.com/prebid/Prebid.js/blob/f5b1fc3003044f4fc65d22a336c2e634173e3d36/modules/mgidBidAdapter.js#L700-L705) has 7 duplicated lines with [modules/mgidBidAdapter.js](https://github.com/prebid/Prebid.js/blob/f5b1fc3003044f4fc65d22a336c2e634173e3d36/modules/mgidBidAdapter.js#L693-L698)

You do the same thing in each of those two cases. Define the constant you want outside of the switch and use it twice, or use an or inside your switch

**Comment by patmmccann** [comment]
Thanks for your attention on this matter soon, merging

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
