### PR TITLE
ozone adapter  - minor fix to add w/h to video requests

### PR DESCRIPTION
**Pull request by afsheenb**
- [ X] Bugfix

Minor bugfix to include width and height attributes in bid requests for video inventory. 

engineering@ozoneproject.com

### CODE REVIEW

**Comment by AskRupert-DM** [comment]
Hi @sumit116 let us know if you need any info - hopefully this is a straight-forward change that can be merged into the next release of PBJS but let us know if there's any issues. Do you know when the next release is scheduled for and if we can get this update included ?

**Comment by AskRupert-DM** [comment]
hi @sumit116 - please try again - believe the test response was probably excluded from India so I've set another one up using those same credentials that should target India.

**Comment by AskRupert-DM** [comment]
hey @sumit116 just checking in if you were able to see the bid-response coming back okay now ?

**Comment by sumit116** [comment]
> hey @sumit116 just checking in if you were able to see the bid-response coming back okay now ?


Hi @AskRupert-DM, I am still unable to get the response.
 
image

image

**Comment by AskRupert-DM** [comment]
@sumit116 - am I correct in thinking you refreshed / tried a couple of times - you may not get the response back every single time on every request - although i've tried to make a change in the ad-server to force a response each time so hopefully you will see it returned more consistently.

I'm able to get the payload that you are using to serve back a response on my end and can confirm India is included in the geo-targeting for our test ad - please try again and let me know if you still are not seeing it:

image

image

**Comment by sumit116** [comment]
> @sumit116 - am I correct in thinking you refreshed / tried a couple of times - you may not get the response back every single time on every request - although i've tried to make a change in the ad-server to force a response each time so hopefully you will see it returned more consistently.
> 
> I'm able to get the payload that you are using to serve back a response on my end and can confirm India is included in the geo-targeting for our test ad - please try again and let me know if you still are not seeing it:
> 
> image

@AskRupert-DM , I refreshed the page multiple times, have rechecked it again now, still I am not getting the response.

**Comment by AskRupert-DM** [comment]
Thanks @sumit116 think the reason you aren't able to see them is because your making requests coming from a non-whitelisted domain so our endpoint will always return an empty object. Will provide testpage URLs for you to use in future submissions to work around this.

**Comment by sumit116** [comment]
> Thanks @sumit116 think the reason you aren't able to see them is because your making requests coming from a non-whitelisted domain so our endpoint will always return an empty object. Will provide testpage URLs for you to use in future submissions to work around this.

Thank u @AskRupert-DM

**Pull request merged**
