### PR TITLE
OpenX Analytics Adapter: adapter no longer offered, remove adapter

### PR DESCRIPTION
**Pull request by bwschmidt**
## Type of change

- [x] Other

## Description of change

OpenX no longer offers analytics, removing the adapter

### CODE REVIEW

**Comment by bwschmidt** [comment]
docs: https://github.com/prebid/prebid.github.io/pull/3947

**Comment by patmmccann** [comment]
@bwschmidt removing adapters is a breaking change, but feel free to make it not call your endpoint and document that it has no function

**Comment by bwschmidt** [comment]
@patmmccann makes sense, for https://github.com/prebid/prebid.github.io/pull/3947 is that okay as is or should I just change the docs to say something like "OpenX has deprecated analytics"

**Comment by MartianTribe** [comment]
Docs PR: 
https://github.com/prebid/prebid.github.io/pull/3947

**Comment by bwschmidt** [comment]
here is a new PR as requested https://github.com/prebid/Prebid.js/pull/8828. Should this PR remain open for Prebid 8?

**Comment by patmmccann** [comment]
Prebid 8 is a long time (at least a few months) away, let's close it for now, I've got it mentioned in the tracking issue

**Comment by patmmccann** [comment]
I think docs okay as is

**Pull request closed without merging**
