### PR TITLE
Districtm DMX adapter support for CCPA

### PR DESCRIPTION
**Pull request by stevealliance**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x ] Other

## Description of change

Adding support for new IAB CCPA 

this value is added in the same path as GDPR 
```
 "regs": {
    "ext": {
      "gdpr": 1,     
      "us_privacy": "1NYN"
    }
  },
```

### CODE REVIEW

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/1674

**Comment by stevealliance** [comment]
addded unit test for ccpa and gdpr

**Comment by stevealliance** [comment]
@idettman, just to let you know that I've added some unit testing, for CCPA like you ask.

**Comment by stevealliance** [comment]
@bretg and @idettman,  I would really like this update to be included in the next release!

Thanks

**Pull request merged**
