### PR TITLE
few changes

### PR DESCRIPTION
**Pull request by sekindo**
## Type of change

- [x] Bugfix
1. remove of setting the bid.adId  
2. using https only when needed

### CODE REVIEW

**Comment by mkendall07** [comment]
@sekindo 
Why are you removing `bid.adId` ? Please see https://github.com/prebid/Prebid.js/issues/509 - we want to match bid ids to bid requests. Thanks

**Comment by sekindo** [comment]
We removed the bid.adId since we see that no other adapter is setting this parameter.
as far as we understand, this parameter is being set by the prebid library and there is no need to set it in the adapter.

**Comment by protonate** [comment]
We are recommending that adapters use the same ID for the bid response as was generated in the bid request. You can achieve this by passing the `bidRequest` object as the second argument to `bidfactory.createBid` for both a valid bid response and no bid scenarios. See https://github.com/prebid/Prebid.js/blob/master/src/bidfactory.js#L18

**Comment by sekindo** [comment]
added bidRequest object as the second argument to bidfactory.createBid

**Pull request closed without merging**
