### PR TITLE
New LuponMedia Bid Adapter

### PR DESCRIPTION
**Pull request by adxpremium**
## Type of change
- [X] New bidder adapter

## Description of change
Added new LuponMedia bidAdapter

- test parameters for validating bids
```
{
 bidder: "luponmedia",
 params: {
  siteId: 12345,
  keyId: '4o2c4'
 }
}
```

- info@luponmedia.com
- [X] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by adxpremium** [comment]
Please find docs below: 
https://github.com/prebid/prebid.github.io/pull/1922

**Comment by sumit116** [comment]
Hi @adxpremium , you need to add unit test for your adapter in a <your_adapter_name>_spec.js file.
Also, by mistake I merged your PR and I have reverted it now, so can you please add a new PR with all the changes and docs link. Sorry for the trouble.

**Comment by sumit116** [comment]
This PR is reverted in https://github.com/prebid/Prebid.js/pull/5145

**Comment by adxpremium** [comment]
Hi @sumit116,  we just added unit testing file and created new PR #5146

**Pull request merged**
