### PR TITLE
nanointeractive bid adapter

### PR DESCRIPTION
**Pull request by nanointeractive**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x ] New bidder adapter 
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

https://github.com/nanointeractive/prebid.github.io/blob/2a57cea7d15b3e3a69b24db288d8e3364c3996b5/dev-docs/bidders/nanointeractive.md

## Description of change
New bid adapter

- test parameters for validating bids
{
  bidder: 'nanointeractive',
  params: {
    sec: '04a0cb7fb9ac02840f7f33d68a883780',
    dpid: '58bfec94eb0a1916fa380162',
    pid: '58bfec94eb0a1916fa380163'
  }
}

- contact email of the adapter’s maintainer
rade@nanointeractive.com

### CODE REVIEW

**Comment by mkendall07** [comment]
hi @nanointeractive 
We have recently updated the format for adapters. Please submit the adapter in the form specified here http://prebid.org/dev-docs/bidder-adapter-1.html

You can see an example of the new format implemented here: https://github.com/prebid/Prebid.js/blob/master/modules/appnexusAstBidAdapter.js

Thanks!

**Comment by nanointeractive** [comment]
Dear Matt, can you please give us an info when can we expect approval of the pull request. If there is anything from our side we can do to fasten the process please let us know.

**Comment by mkendall07** [comment]
@nanointeractive 
Thanks for the update. I didn't see the most recent commits. I'll review this week. Thanks!

**Comment by nanointeractive** [comment]
Great, thanks !

**Comment by nanointeractive** [comment]
@mkendall07 
Thanks for the overview and the help. 
We deployed the requested changes.

I've also changed params for the bid validation, please use this one:
{
  bidder: 'nanointeractive',
    params: {
      sec: '04a0cb7fb9ac02840f7f33d68a883780',
      dpid: '58bfec94eb0a1916fa380162',
      pid: '58bfec94eb0a1916fa380163'
  }
}

Cheers

**Comment by mkendall07** [comment]
@nanointeractive 
thanks. Can you add the markdown file as well? see here for example: https://github.com/prebid/Prebid.js/blob/master/modules/appnexusAstBidAdapter.md

**Comment by nanointeractive** [comment]
thanks, done: https://github.com/nanointeractive/Prebid.js/blob/master/modules/nanointeractiveBidAdapter.md

**Comment by mkendall07** [comment]
@nanointeractive 
getting a CORS error now on your endpoint: `Failed to load http://tmp.audiencemanager.de/hb: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:9999' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by nanointeractive** [comment]
strange, I know the issue but we solved it by changing dynamically 'Access-Control-Allow-Origin' for each bid request from location.origin value. Can you please send me the Response headers and Request Payload.

**Comment by mkendall07** [comment]
It's because of `Access-Control-Allow-Origin: *` instead of `Access-Control-Allow-Origin: <domain>`

```HTTP/1.1 200 OK
Date: Wed, 25 Oct 2017 16:50:10 GMT
Server: Apache/2.4.27 (Amazon) PHP/5.6.25
X-Powered-By: PHP/5.6.25
Status: 200 OK
RequestId: e082476220652d6695d50c78b790b634
Hostname: 10-75-1-58#slave3
P3P: CP="NID DSP ALL COR"
Access-Control-Allow-Origin: *
responseTime: 90
Content-Length: 835
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/x-javascript```

**Comment by nanointeractive** [comment]
mystery solved, we disabled localhost for bid requests. I have enabled localhost, now everything should be fine

**Pull request merged**
