### PR TITLE
Apacdex Bid Adapter: userId module support, show demo ads in debug mode & other maintenance

### PR DESCRIPTION
**Pull request by thuyhq**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change
- Support Prebid UserId Module.
- Show demo ads when debug mode is enabled.
- Handles bidderRequest.timeout on the endpoint side.
- Fix error getting wrong device size if prebid.js is loaded in iframe.
- Add function to get domain from prebid config publisherDomain, pageUrl

### CODE REVIEW

**Review by musikele — CHANGES_REQUESTED** [review]
Hi @thuyhq , 
Test coverage falled down to 77%, and we require the bidder to have coverage above 80%. To see the test coverage, run 
```
npx gulp test-coverage
```

And to see the results 
```
npx gulp view-coverage
```

**Review by musikele — COMMENTED** [review]
Don't forget to add documentation and examples on how to use those parameters, if the user has to do anything to enable them.

**Review by musikele — CHANGES_REQUESTED** [review]
I tried to test the bidder with pbjs_debug=true as query param, so I expected to get a demo ad. I verified that the `test` variable was set true. 
However, the endpoint returned `400` with the following body: `can't parse payload data with error: Cannot parse domain name from payload` 

My test hostname is `jita.local.net:9999` 

I usually run `npx gulp serve --notest` and then use `gpt/hello_world.html` page to do my tests.

**Comment by musikele** [comment]
Hi @thuyhq , I've just added a few comments. Please verify and eventually correct them.

**Comment by thuyhq** [comment]
Hi @musikele,

> Hi @thuyhq ,
> Test coverage falled down to 77%, and we require the bidder to have coverage above 80%. To see the test coverage, run
> 
> ```
> npx gulp test-coverage
> ```
> 
> And to see the results
> 
> ```
> npx gulp view-coverage
> ```
I added some test units and the coverage went up 89%.





> Don't forget to add documentation and examples on how to use those parameters, if the user has to do anything to enable them.

I don't want to make these changes publicly available to my users. Therefore no additional documents are available



> I tried to test the bidder with pbjs_debug=true as query param, so I expected to get a demo ad. I verified that the `test` variable was set true.
> However, the endpoint returned `400` with the following body: `can't parse payload data with error: Cannot parse domain name from payload`
> 
> My test hostname is `jita.local.net:9999` 
> 
> I usually run `npx gulp serve --notest` and then use `gpt/hello_world.html` page to do my tests.

Fixed

Thank you for your reviews.

**Comment by smenzer** [comment]
@thuyhq i would suggest that you rebase your changes on master so that your PR doesn't include all of the commits already in there

**Comment by musikele** [comment]
If you're not familiar with rebasing: 

```
git pull --rebase origin master
```
all your commits will be applied on origin/master now. Solve all conflicts and follow the instructions in the terminal. 

At the end, 

```
git push --force <your_branch>
```

**Comment by thuyhq** [comment]
Hello @musikele , @smenzer 
Sorry for my limited knowledge with git.
I think I made the corrections according to your intentions.
Please help me check again.
Thank you.

**Review by musikele — APPROVED** [review]
LGTM

**Pull request merged**
