### PR TITLE
Adjust the bid value considering the view ability

### PR DESCRIPTION
**Pull request by ColombiaOnline**
## Type of change

- [ x] Bugfix
## Description of change
Update adjust the bid value considering the view ability

- contact email of the adapter’s maintainer
- [ x] official adapter submission

### CODE REVIEW

**Comment by smenzer** [comment]
@ColombiaOnline like I mentioned in the other PR, please do not change the package files. Make sure in your fork of this repository that you are pulling in the fresh master from the Prebid.js repo, not just your own...you need to keep yours in sync with this one.

I assume that in your local copy of Prebid, you have a remote called `origin` that is pointing to your fork (git@github.com:ColombiaOnline/Prebid.js.git) (you can check by typing `git remote -v`

If so, I would recommend setting up a new remote for this repo:

```git
git remote add upstream git@github.com:prebid/Prebid.js.git
```

Now, to pull in the latest master branch from this repo (not your fork), you would simply checkout the master branch locally (`git checkout master`) then run `git pull upstream master`. Now your local master branch is in sync with Prebid.js's, and you can apply your changes, then `git push origin master`, then do your PR.

**Comment by ColombiaOnline** [comment]
Hi @smenzer ,
Thanks for your support, i have fellow your suggestion step by step but i am unable to fetch file from pribid. i am again commit (3dd5fa7). Please push.

**Comment by smenzer** [comment]
if you followed the instructions above to add the remote called `upstream`, then you should be able to do the following:

```
$ git pull upstream master

$ git rebase master --interactive
```

After the second command, it will open up an editor and you'll see a bunch of commits, like this:

```
pick 9b324751 Add colombia adapter
pick d4c49dde Add https in the url
pick 6da9cb54 update files
pick d8f3ff19 add test cases and update md file
pick 8071c036 remove native from package.json and update colombia test cases
pick 8642bf9b Use conditions for the size
pick 9466e8bd Use conditions for the size and remove test warnings
pick f87587a2 remove package.json
pick de95bc13 Resolved import related errors
pick 8c32ee6d update referrer method
pick b13d3444 remove package json and update referer path
pick 1beff3d6 revert package json
pick 29be11f7 Resolved all changes
pick 618318be update version package json
pick 5dae91de Resolved test cases issues
pick 98fcb56b update file for adjust bid value
pick 73021a98 update file
pick 647d7170 update file for adjust bid values
pick 01462e55 Delete package-lock.json
pick f2d66e14 Revert package-lock.json
pick 35fef52f Update final file
pick b1f563cd Update file for adjust bid value
pick c1532282 revert version of packages json
pick 172263d2 replace 1 to 0
pick 191ad544 Revert previous version
pick 3dd5fa76 Update changes
pick 52b89441 Identity link id system - handle empty response (#5279)
```

Delete every line except the one for your latest changes: `pick 3dd5fa76 Update changes`

Then save the file and close the editor. Now it's going to say you have a conflict, so open up your bid adapter code and resolve it by removing the old code, so this:

```
<<<<<<< HEAD
    if (cpm < 1) {
=======
    if (cpm <= 0) {
>>>>>>> 3dd5fa76... Update changes
```

turns into this:

```
if (cpm <= 0) {
```

Now, save the file and go back to the command line.

```
$ git add modules/colombiaBidAdapter.js

$ git rebase --continue

$ git push origin master
```

Now you should be all set...once that's done I can review your changes. 

From now on, before you start working on code and before you put in a PR, run `git pull upstream master` on your branch.

**Comment by ColombiaOnline** [comment]
Hi @smenzer ,
Please help me, after run git rebase master --interactive
Open up an editor but facing different message like 
 noop

# Rebase 00b7f5c7..00b7f5c7 onto 00b7f5c7 (1 command)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.

**Comment by smenzer** [comment]
@ColombiaOnline I can't tell from your comment what is output from the terminal, vs editor messages, vs you just writing to me. can you please try to format it more clearly?

alternatively, since the change you're trying to make is so small, you may be better off taking a brand new fork of Prebid.js and starting your PR from there.

**Comment by ColombiaOnline** [comment]
Hi @smenzer 
Thanks,
Create new PR

**Pull request closed without merging**
