### PR TITLE
Prebid core & PBS adapter: better support for server-side stored impressions

### PR DESCRIPTION
**Pull request by dgirardi**
## Type of change

- [x] Feature
- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change

This adds the option of declaring adUnits without any explicit bidders that will be interpreted as S2S-only stored impressions (or other similar constructs where the server decides who is bidding):

 - adUnits that declare `ortb2Imp` will be considered valid even if they declare no `bids`;
 - for those adUnits, core injects a placeholder "null" bidder that generates only S2S requests;
 - the PBS adapter will then accept returned bids as long as `s2sConfig.allowUnknownBidderCodes` is set.

## Other information

Resolves https://github.com/prebid/Prebid.js/issues/7027
Docs PR TBD

This is an example page / stored impression:

```
<html>
<head>
    <script>
        var PREBID_TIMEOUT = 2000;

        var adUnits = [
            {
                code: 'test-div',
                mediaTypes: {
                    banner: {
                        sizes: [[728,90]]
                    }
                },
                ortb2Imp: { ext: { prebid: { storedauctionresponse: { id: '1001-static-response-300x250' } } } },
            }
        ];

        var pbjs = pbjs || {};
        pbjs.que = pbjs.que || [];

    </script>
    <script type="text/javascript" src="../../../build/dev/prebid.js" async></script>

    <script>
        var googletag = googletag || {};
        googletag.cmd = googletag.cmd || [];
        googletag.cmd.push(function() {
            googletag.pubads().disableInitialLoad();
        });

        pbjs.que.push(function() {
            pbjs.addAdUnits(adUnits);
            pbjs.setConfig({
                debug: true,
                s2sConfig: {
                    accountId: '14062',
                    bidders: ['rubicon'],
                    timeout: 1000,
                    endpoint: 'https://pg-prebid-server-qa.rubiconproject.com/openrtb2/auction',
                    syncEndpoint: 'https://prebid-server.qa.rubiconproject.com/cookie_sync',
                    enabled: true,
                    adapter: 'prebidServer',
                    allowUnknownBidderCodes: true
                }
            });
            pbjs.requestBids({
                bidsBackHandler: sendAdserverRequest
            });
        });

        function sendAdserverRequest(bids, timedOut, auctionId) {
            if (pbjs.adserverRequestSent) return;
            pbjs.adserverRequestSent = true;
            googletag.cmd.push(function() {
                pbjs.que.push(function() {
                    pbjs.setTargetingForGPTAsync();
                    googletag.pubads().refresh();
                });
            });
        }

        setTimeout(function() {
            sendAdserverRequest();
        }, PREBID_TIMEOUT);
    </script>

    <script>
        (function () {
            var gads = document.createElement('script');
            gads.async = true;
            gads.type = 'text/javascript';
            var useSSL = 'https:' == document.location.protocol;
            gads.src = (useSSL ? 'https:' : 'http:') +
                '//www.googletagservices.com/tag/js/gpt.js';
            var node = document.getElementsByTagName('script')[0];
            node.parentNode.insertBefore(gads, node);
        })();
    </script>

    <script>
        googletag.cmd.push(function() {
            googletag.defineSlot('/112115922/FL_PB_MedRect', [[300, 250], [300,600], [728,90]], 'test-div').addService(googletag.pubads());
            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
        });
    </script>
</head>

<body>
<h2>Hosted Prebid - 14062</h2>

<div id='test-div'>
    <script>
        googletag.cmd.push(function() { googletag.display('test-div'); });
    </script>
</div>
</body>
</html>

```

### CODE REVIEW

**Comment by OllyTriple13** [comment]
Hi - @bretg pointed me in the direction of this PR and we have been testing this at Freestar. Firstly, thank you for implementing this - it will come in very handy!

We think there is a slight issue in the logic. When we remove the bids object it passes validation, but does not merge the ortb2Imp object into the openrtb request. Adding dummy data into the bids object results in a successful merge.
This works:
```
var adUnits = [
          {
            code: 'test',
            mediaTypes: {
                banner: {
                    sizes: [[728,90]]
                }
            },
            bids: [ 
               {
                 bidder: 'Bidder A'
               }
             ],
            ortb2Imp: {
              ext: {
                prebid: {
                  storedrequest: { 
                    id: 'test-imp'
                  } 
                } 
              }
            }
          }
        ];
```
This does not:
```
var adUnits = [
          {
            code: 'test',
            mediaTypes: {
                banner: {
                    sizes: [[728,90]]
                }
            },
            ortb2Imp: {
              ext: {
                prebid: {
                  storedrequest: { 
                    id: 'test-imp'
                  } 
                } 
              }
            }
          }
        ];
```
Also we noticed that the bidders array in s2sconfig needs to be present for it to work, which seems a bit counter intuitive.

Hope we've got this right and it helps - let us know if you need more detail.

Thanks,

Olly.

**Comment by dgirardi** [comment]
@OllyTriple13 you are correct - a late one-line change ended up breaking everything. Should be fixed now, thanks for catching it! Good suggestion also on making `s2sConfig.bidders` optional; I'll follow up on that as well.

**Comment by OllyTriple13** [comment]
We've pulled your two commits and tested - it all looks good from our end. Thank you. Is there anything I can do to help this get reviewed?

**Review by robertrmartinez — APPROVED** [review]
Nice looks good!

**Pull request merged**
