### PR TITLE
Fixing bigObj size issue so that renderAd will size the iframe approp…

### PR DESCRIPTION
**Pull request by pdramos1**
addingin the correct calculation on bidObj.size

### CODE REVIEW

**Comment by ehoch** [comment]
@mkendall07 Any chance we could get a new Prebid.js 0.4.2 release with these recent fixes? Sovrn adapter is pretty broken without this fix.

**Comment by pwfsd** [comment]
Eric, I'm not sure 'pretty broken' is the right characterization.   If you pass an array of sizes the adapter should be fine, just use this:

sizes: [[300,250]]

instead of:

sizes: [300,250]

**Comment by ehoch** [comment]
@pwfsd Fair enough. I'll use that as a pretty solid workaround for now. Thank you.

**Comment by pdramos1** [comment]
I think this is the right answer, barring pulling the updated code from the
pull request and using that while waiting for 0.4.2

-P

**Pull request merged**
