### PR TITLE
EMX revised issue with schain forwarding

### PR DESCRIPTION
**Pull request by EMXDigital**
## Type of change
- [x] Bugfix

## Description of change
Schain object and test was being set and checked for in the wrong location. Applied to our implementation

### CODE REVIEW

**Review by mkendall07 — APPROVED** [review]
lgtm

**Comment by mkendall07** [comment]
@EMXDigital to get the build to pass you need to "favorite" the prebid.js project inside circleCI. Otherwise it attempts to run in your circleci account.

**Comment by DBogdanEMX** [comment]
Thanks @mkendall07, that's been cause for some confusion on our side for a while. We'll update moving forward.

**Comment by EMXDigital** [comment]
Hey there @mkendall07, we saw the following error in our stack. Is this expected, EMX doesn't currently have any plans for paying for a CircleCI plan. Is this a blocker for pull requests and are there any other ways forward?

"This job has been blocked because resource-class:xlarge is not available on your plan. Please upgrade to continue building"

**Comment by EMXDigital** [comment]
@mkendall07 wanted to follow up here - don't want to miss this weeks release, if possible, as we're getting towards the end of the year

**Comment by EMXDigital** [comment]
We fixed the CircleCI integration problem that we were facing with our account but this PR still seems to fail on CircleCI with an error regarding `PrebidManagerAnalytics Adapter build utm tag data` timing out on InternetExplorer. The spec file for the change passes, but we are not able to figure out why circleCI fails because of the timeout. Can you review and let us know what the next steps for us should be? @mkendall07

**Comment by mkendall07** [comment]
Hey @EMXDigital I restarted the job to see if it passes. If it continues to fail you'll want to rebase off the latest master in case there was another issue that should resolve it.

**Comment by EMXDigital** [comment]
@mkendall07 looks like everything is passing, lgtm?

**Comment by mkendall07** [comment]
yep, merged. Sorry for the long delay.

**Pull request merged**
