### PR TITLE
SmartyTech Bid Adapter : initial adapter release

### PR DESCRIPTION
**Pull request by preved-medved**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Comment by musikele** [comment]
Hi @preved-medved , your bidder does not satisfy the requirement of having at least 80% test coverage. 

Please be sure to increase code coverage. To see the coverage run first 

    npx gulp test-coverage 

and then 

    npx gulp view-coverage

**Comment by preved-medved** [comment]
Hi @musikele. Fixed, sorry for that.

**Review by musikele — CHANGES_REQUESTED** [review]
Check comments please

**Review by musikele — APPROVED** [review]
LGTM

**Comment by musikele** [comment]
@preved-medved  You may open a PR in the [headerbid-expert repository](https://github.com/prebid/headerbid-expert) to have their adapter recognized by the [Headerbid Expert extension](https://chrome.google.com/webstore/detail/headerbid-expert/cgfkddgbnfplidghapbbnngaogeldmop). The PR should be to the [bidder patterns file](https://github.com/prebid/headerbid-expert/blob/master/bidderPatterns.js), adding an entry with their adapter's name and the url the adapter uses to send and receive bid responses.

**Comment by muuki88** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/4125

**Pull request merged**
