### PR TITLE
adapter loader refactor

### PR DESCRIPTION
**Pull request by mhipszki**
I've refactored `loader/getAdapter.js` which I added in #424 to be able to add test coverage for it

`proxyquire` and `mock-fs` npm packages were necessary to be added to mock out internal dependencies in the `getAdapter` module

`getAdapter` is now completely self-contained and just needs to be called from `loaders/adapterLoader.js` module without parameters, the default `adapters.json` file is referenced inside `getAdapter`

as `getAdapter` is a Node module, `mocha` has been used to run tests against it

I've used `chai/expect` but if required I'm happy to convert the assertions to `chai/assert` instead

there's a new npm script `test-loaders` added to `package.json` to run the tests against the loader modules

### CODE REVIEW

**Comment by mhipszki** [comment]
build failure due to Karma running all specs under `test/` folder, even those which are only supposed to run under Node

```
26 07 2016 14:46:47.504:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
26 07 2016 14:46:47.517:INFO [launcher]: Starting browser Chrome
26 07 2016 14:46:48.934:INFO [Chromium 37.0.2062 (Ubuntu 0.0.0)]: Connected on socket /#Mjfg-nXaRj47mu5cAAAA with id 27917622
Chromium 37.0.2062 (Ubuntu 0.0.0) ERROR
  Uncaught SyntaxError: Use of const in strict mode.
  at /home/travis/build/prebid/Prebid.js/test/spec/loaders/getAdapters_spec.js:23665
```

Seems like the tests running in browsers (Prebid source) and utility scripts e.g. webpack loaders running in Node should have separate tooling?

`karma.conf.js` needs to be changes omitting custom webpack loader modules:

```
    // list of files / patterns to load in the browser
    files: [
      'test/**/*_spec.js'
    ],

    // list of files to exclude
    exclude: [
      'test/spec/loaders/**/*'
    ],
```

Also, another gulp task needs to be wired up to run the webpack loader tests during the build.

@mkendall07  I'm happy to add these changes to this PR if you think they're appropriate

**Comment by mkendall07** [comment]
@mhipszki 
makes sense to me. Can you add to this PR? 
@protonate 
Please take a look at this one.

**Comment by mhipszki** [comment]
@mkendall07 sure, np

**Comment by mhipszki** [comment]
@mkendall07 @protonate I've updated the Karma config and added a `gulp mocha` task, it's all green now, could you please take a look?

**Comment by protonate** [comment]
I'm getting the following output when trying to run `gulp run-tests`:
```
$ gulp run-tests
[12:49:33] Using gulpfile ~/code/Prebid.js/gulpfile.js
[12:49:33] Starting 'clean'...
[12:49:33] Starting 'hint'...
[12:49:33] Starting 'jscs'...
[12:49:34] Starting 'webpack'...
[12:49:34] Starting 'test'...
[12:49:34] Starting 'mocha'...
[12:49:34] Starting Karma server...


  loaders/getAdapters
    when custom adapter list is defined
      and exists
        ✓ should return custom adapter list
      and does not exist
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use
  server = new Server(config, [done])
  server.start()
instead.

        ✓ should return default adapter list and show warning
    when custom adapter list is not defined
      ✓ should return default adapter list
    when default adapter list cannot be found
[12:49:38] Finished 'clean' after 4.78 s
{ [Error: ./src/utils.js
Module build failed: Error: ENOENT, no such file or directory '/Users/ncozi/code/Prebid.js/.babelrc'
  at Binding.<anonymous> (/Users/ncozi/code/Prebid.js/node_modules/mock-fs/lib/binding.js:353:15)
  at maybeCallback (/Users/ncozi/code/Prebid.js/node_modules/mock-fs/lib/binding.js:43:17)
  at Binding.open (/Users/ncozi/code/Prebid.js/node_modules/mock-fs/lib/binding.js:327:10)
  at Object.fs.openSync (/Users/ncozi/code/Prebid.js/node_modules/mock-fs/node/fs-5.0.0.js:584:18)
  at Object.fs.readFileSync (/Users/ncozi/code/Prebid.js/node_modules/mock-fs/node/fs-5.0.0.js:431:33)
  at Object.readFileSync (/Users/ncozi/code/Prebid.js/node_modules/mock-fs/lib/index.js:59:31)
  at OptionManager.addConfig (/Users/ncozi/code/Prebid.js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:223:35)
  at OptionManager.findConfigs (/Users/ncozi/code/Prebid.js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:434:16)
  at OptionManager.init (/Users/ncozi/code/Prebid.js/node_modules/babel-core/lib/transformation/file/options/option-manager.js:482:12)
  at File.initOptions (/Users/ncozi/code/Prebid.js/node_modules/babel-core/lib/transformation/file/index.js:211:75)
  at new File (/Users/ncozi/code/Prebid.js/node_modules/babel-core/lib/transformation/file/index.js:129:22)
  at Pipeline.transform (/Users/ncozi/code/Prebid.js/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
  at transpile (/Users/ncozi/code/Prebid.js/node_modules/babel-loader/index.js:14:22)
  at Object.module.exports (/Users/ncozi/code/Prebid.js/node_modules/babel-loader/index.js:88:12)
 @ ./src/prebid.js 7:13-31./src/bidmanager.js
Module build failed: Error: ENOENT, no such file or directory '/Users/ncozi/code/Prebid.js/.babelrc'
```

**Comment by mhipszki** [comment]
@protonate sorry for the delay, I'm off for a few weeks

about the error

```
Module build failed: Error: ENOENT, no such file or directory '/Users/ncozi/code/Prebid.js/.babelrc'
```

seems like `mock-fs` (which I added for testing purposes) is intercepting the babel transpilation, I'll need to look into that a bit more once I'll have some of time

**Comment by mkendall07** [comment]
Closing in favor of https://github.com/prebid/Prebid.js/pull/698

**Pull request closed without merging**
