### PR TITLE
Vidazoo Adapter: Feature/unique-deal-id

### PR DESCRIPTION
**Pull request by uditalias**
## Type of change
- [x] Feature
- [x] Refactoring (no functional changes, no api changes)

## Description of change

Sends unique deal id as a server param

### CODE REVIEW

**Comment by uditalias** [comment]
@GLStephen LMK if I can assist with the merge of this PR. Thanks.

**Comment by GLStephen** [comment]
@uditalias this looks good, but based on GDPR requirements you need to update your sessionStorage access to access through the utils storage class. Once that's updated I can review again. Thanks!

**Comment by GLStephen** [comment]
@uditalias Rule 2 here covers this in the proposed rules https://github.com/prebid/Prebid.js/issues/5239

**Comment by uditalias** [comment]
@GLStephen Thank you for you review.
Is there any way to use the sessionStorage instead of the localStorage? I found the storageManager but only the local storage is supported.
I think that the local storage is too aggressive for my feature because it will persist across site visits.

**Comment by GLStephen** [comment]
@uditalias The setCookie and getCookie functions should be capable of creating session cookies.

**Comment by uditalias** [comment]
@GLStephen I changed the code to use the `storageManager` from utils. Please note that I added another field param called `sessionId`, this field is extracted from the localStorage (using the storageManager) and passed as a param to the server. Thanks.

**Comment by GLStephen** [comment]
@uditalias merged

**Pull request merged**
