### PR TITLE
ZetaGlobal SSP Analytics Adapter: add new analytics adapter

### PR DESCRIPTION
**Pull request by abermanov-zeta**
Zeta Global SSP Analytics Adapter

### CODE REVIEW

**Review by Fawke — CHANGES_REQUESTED** [review]
Hi @abermanov-zeta,

Can you please provide a link to the docs PR? Rest looks good.

**Comment by abermanov-zeta** [comment]
Hi @Fawke,
Here is the link - [https://github.com/prebid/prebid.github.io/pull/3460](https://github.com/prebid/prebid.github.io/pull/3460)
Thank you!

**Review by Fawke — APPROVED** [review]
LGTM

**Comment by Fawke** [comment]
Hi @abermanov-zeta, can you please either resolve the Codacy Static Code Analysis step, or can you fix all the issues reported there?

I can't merge this PR until all the checks have passed.

**Comment by abermanov-zeta** [comment]
@Fawke Thank you!

**Pull request merged**
