### PR TITLE
Yahoo Ads Bid Adapter: Fix to only set bid response renderer for video.

### PR DESCRIPTION
**Pull request by zach-bowman**
## Type of change

- [x] Bugfix
- [ ] Updated bidder adapter   

## Description of change

This PR fixes undesired behavior within the `YahooAdsBidAdapter` (per Yahoo business/product) which incorrectly allows for a renderer value to be created and set to the `bidResponse.renderer` field. `YahooAdsBidAdapter` is updated to include an additional clause `bidResponse.mediaType === VIDEO` alongside the existing `... context === outstream && !bidderRequest.renderer` as well as adds associated tests. At present [with this change], the `YahooAdsBidAdapter` should only create and set a renderer for appropriate video responses.

## Other information
Contact Email: [prebid-tech-team@yahooinc.com](mailto:prebid-tech-team@yahooinc.com)

### CODE REVIEW

**Comment by zach-bowman** [comment]
Cc @slimkrazy @radubarbos

**Comment by radubarbos** [comment]
LGTM

**Comment by zach-bowman** [comment]
Hi all, I just wanted to ask about the failing "Check for Duplicated Code" item above -- since it appears that some of the logic we have is now used by another adapter -- should I still extract the duplicated code? I just wanted to make sure this is the appropriate path forward as we would then share our intended specific logic across adapters (which may change). Happy to do so if this is the case (new to contributing, so just wanted to make sure). Same with https://github.com/prebid/Prebid.js/pull/12128 . Thanks in advance for the input!

**Comment by zach-bowman** [comment]
Hi reviewers, I just wanted to followup on the above question. In short: as I attempted to address the failing check, it seemed incorrect to remove that logic from our adapter as well as touch another adapter -- as this should be specific and subject to change per company. Let me know your suggestion on how to best address this so we can get this change out. Thanks so much in advance!

**Review by aishwaryapatil — APPROVED** [review]

**Review by Rothalack — APPROVED** [review]
Apologies for the delay, I wanted to get to this at the beginning of the week but I got sick. I can finally think clearly again today. This looks good, working in testing.

**Comment by zach-bowman** [comment]
No worries! I appreciate the help and patience with this! Still working to understand the process. Thanks again!

**Pull request merged**
