### PR TITLE
Create rtbdemandAdkBidAdapter.js

### PR DESCRIPTION
**Pull request by rtbdemand**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by rtbdemand** [comment]
rtbdemandAdkBidAdapter

**Comment by jsnellbaker** [comment]
@rtbdemand I see you opened a separate PR to add the md file for this new adapter.  Can you please instead include that file into this PR and close the other?  

Additionally all new adapters require unit tests to be included and working.  Please see this page (http://prebid.org/dev-docs/bidder-adaptor.html#adding-unit-tests) if you need further information about how to set them up.  Please also include the unit test file as part of this PR.  Thanks!

I'll start to review the adapter code soon and let you know of any additional feedback.

**Comment by jsnellbaker** [comment]
Also we need a docs PR before we can merge. 

Please submit a PR to the [docs repo](https://github.com/prebid/prebid.github.io) to add a file for your adapter to the [bidders directory](https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders) so your adapter's params will appear on the [bidders page](http://prebid.org/dev-docs/bidders.html).  

Thanks!

**Comment by rtbdemand** [comment]
I have added the rtbdemandadk.md in PR .Also we are expecting the host to change basis locations etc .So I would keep that way.Also I dont have a test ad configure to give cpms above 0.10 .Can we release it way it is please..?

**Comment by jsnellbaker** [comment]
@rtbdemand Thanks for the clarification.  I believe it would be okay if the test ad with the CPM value as well as the params value for the host.  

I don't see the md file in this PR however.  Additionally can you supply the unit test file as well as a docs PR that I mentioned in the earlier comments?  Those items need to be included for us to merge in this adapter.  Thanks.

**Comment by rtbdemand** [comment]
Added rtbdemandadk.md in PR as well prebid/prebid.github.io#696 and included the unit test file

**Comment by jsnellbaker** [comment]
Just a note for any future reference:
- the .md file for this adapter can be found at #2324
- the _spec.js file for this adapter can be found at #2352

**Pull request merged**
