### PR TITLE
Revert addition of video support to IX adapter as it is still in testing

### PR DESCRIPTION
**Pull request by ix-certification**
## Type of change
- [X] Bugfix
- [X] Feature

## Description of change
Reverts the addition of Video support to the IX adapter from PR #3901 
This adapter change is still in testing and should not have been added to master yet.

- contact email of the adapter’s maintainer pdu-supply-prebid@indexexchange.com
- [X] official adapter submission

## Other information
See https://github.com/prebid/Prebid.js/pull/3901

### CODE REVIEW

**Comment by jas-singh** [comment]
@harpere 
@idettman 

Hey guys, 

Can have this merged asap. We are seeing an issue with this update to our adapter and would like to revert this change for now.

**Comment by ix-prebid-support** [comment]
Is there any chance to release tag this as 2.21.1 to avoid any issues with publishers that automatically update to the latest 2.21.0 release tag? @jaiminpanchal27

**Comment by jsnellbaker** [comment]
@ix-prebid-support We actually just released the 2.22.0 version of Prebid.js a few minutes ago.  So these changes should be included in that release.

**Comment by ix-prebid-support** [comment]
Seeing it now much appreciated @jsnellbaker We have also found a workaround for 2.21.0 and will resubmit our PR for a future release thank-you and enjoy the holiday!

**Pull request merged**
