### PR TITLE
Advangelists Bid Adapter: support adomain, video params, and the floors module

### PR DESCRIPTION
**Pull request by NeerajKrRai**
## Type of change

- [ ] Bugfix
- [ ] Feature

## Description of change

https://github.com/prebid/Prebid.js/issues/6650
supporting advertiserDomains

https://github.com/prebid/Prebid.js/issues/6512
Support video params at the adunit level

https://github.com/prebid/Prebid.js/issues/6465
support the floors module

- contact email of the adapter’s maintainer-neeraj.it3@gmail.com,l@advangelists.com
- [ ] official adapter submission

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@NeerajKrRai can you remove your backup (.bak) files from this pr please 🙏

**Comment by NeerajKrRai** [comment]
@ChrisHuie Apologies for that. Have removed them resolved the conflict as well.

**Comment by NeerajKrRai** [comment]
@osazos Any update on this one? do let me know if any other info is required from my side.

Cheers,
Neeraj

**Comment by ChrisHuie** [comment]
@NeerajKrRai not sure I understand why you are adding a url.js file to Prebid Core? Can you explain the purpose for that module? If it is needed we need it to be documented well since we are adding it to the src.

**Comment by NeerajKrRai** [comment]
@ChrisHuie Yes, you are right , i was referring to some old version. So, I have removed the url file and made changes to the code to refer to src/utils for the same which works fine. Do let me know if any other info required from my side.

Appreciate your prompt feedback.

Cheers,
Neeraj

**Comment by NeerajKrRai** [comment]
@ChrisHuie any update on the review?

Thanks,
Neeraj

**Review by osazos — APPROVED** [review]
LGTM

**Comment by NeerajKrRai** [comment]
@osazos thanks! are there any further actions from our side on this?

Thanks,
Neeraj

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
