### PR TITLE
Fix removeAdUnit

### PR DESCRIPTION
**Pull request by benjaminclot**
## Type of change

- [x] Bugfix

## Description of change
When there are multiple adUnits with the same code, only one of them gets removed. This fixes that.

### CODE REVIEW

**Comment by benjaminclot** [comment]
All tests pass but CircleCI keeps returning timeouts :-/

**Comment by benjaminclot** [comment]
@idettman The branch has been updated with master and there's still a timeout error.

**Comment by idettman** [comment]
Nice catch @snapwich, so would the fix be something like this:
```
  adUnitCodes.forEach((adUnitCode) => {
    for (let i = $$PREBID_GLOBAL$$.adUnits.length; i > 0; i--) {
      if ($$PREBID_GLOBAL$$.adUnits[i].code === adUnitCode) {
        $$PREBID_GLOBAL$$.adUnits.splice(i, 1);
      }
    }
  })
```

**Comment by snapwich** [comment]
@idettman should be `i >= 0`, but other than that I think it's good.

**Comment by benjaminclot** [comment]
@snapwich @idettman requested change has been committed

**Pull request merged**
