### PR TITLE
Rise adapter

### PR DESCRIPTION
**Pull request by noamtzuberi**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added IronSource header bidding adapter

test parameters for validating bids:
```
{ 
   bidder: 'rise',
   params: {
   org: "56f91cd4d3e3660002000033",
   floorPrice: 3.20,
   testMode: true
}
```

As part of our company rebranding, we are forking the 'ironSource' adapter under a new name - 'Rise' and starting to pass our clients to the new adapter.
In the end, we will remove the ironSource adapter from the adapters list.

cc: @gilcoh33

### CODE REVIEW

**Comment by noamtzuberi** [comment]
Hi,
I think Circle was failed due to a glitch, but I don't have the option to re-build it.
I try to bump a few times but without success.

**Comment by gilcoh33** [comment]
> Hi,
> I think Circle was failed due to a glitch, but I don't have the option to re-build it.
> I try to bump a few times but Circle didn't trigger.

It never worked on Circle. it's prebid's circle config file, on our circle the project is not set

**Comment by noamtzuberi** [comment]
We passed Circle (-;

**Comment by noamtzuberi** [comment]
> > Hi,
> > I think Circle was failed due to a glitch, but I don't have the option to re-build it.
> > I try to bump a few times but Circle didn't trigger.
> 
> It never worked on Circle. it's prebid's circle config file, on our circle the project is not set

The Circle it's PreBid Circle.

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/2605

**Comment by musikele** [comment]
Hello @noamtzuberi . I am reviewing this PR. 
I set up an instream test page with the following parameters: 

```
var videoAdUnit = {
        code: "video1",
        mediaTypes: {
          video: {
            playerSize: [640, 480],
            context: "instream",
          },
        },
        bids: [
          {
            bidder: "rise",
            params: {
              org: "56f91cd4d3e3660002000033",
              testMode: true,
            },
          },
        ],
      };
```

but I see no ad. In particular, the response from the endpoint is: 

```
{"requestId":"3599b2bdac4d288","currency":"USD","netRevenue":true,"sessionId":"2e54654e-c093-4f0c-b96e-b217fb29a283","publisherId":"56f91cd4d3e3660002000033"}
```

And I get the following error in browser's console: 

```
Prebid MESSAGE: CALLING BIDDER ======= rise prebid.js:488:17
Prebid ERROR: Invalid bid from rise. Ignoring bid: Bidder rise is missing required params. Check http://prebid.org/dev-docs/bidder-adapter-1.html for list of params.
```

What am I doing wrong?

**Comment by noamtzuberi** [comment]
Hi @musikele ,
Sorry for the inconvenience but there is some bug on my side and I was fixed it.
Now it works.

**Review by musikele — APPROVED** [review]
LGTM

**Pull request merged**
