### PR TITLE
sharedIdSystem: fix for opted out user

### PR DESCRIPTION
**Pull request by yava-ua**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Scenario: user is opted out and afterwards opted in
Related to issue reported in prebid-sharedid https://github.com/prebid/shared-id/issues/7

@jdwieland8282 @wqi1972

### CODE REVIEW

**Comment by yava-ua** [comment]
@wqi1972 well, upon checking further I see that this fix has no value. The problem reproduces for the periods between syncs. 
Scenario with comments
1. Visit publisher website    -- shared id set properly, cookie created for publisher domain. syncTime is set to 24 hours max (may be less, configurable by publisher)
2. User is opted out  
3. Visit publisher website. -- user is not synced and is seen by publisher as opted in. It'll remain in that state until next sync

And vica verso, if user is opted in after opt out and is not yet synced it be treated by publisher as opted out until text sync. When setting syncTime to few seconds, changes to opt in/out are picked straight away.

@jdwieland8282 I believe this is the intended behavior. Please confirm. 

Closing this pr, as either way this fix is irrelevant

**Comment by jdwieland8282** [comment]
Ok, so it sounds like the issue in [prebid/shared-id#7](https://github.com/prebid/shared-id/issues/7) was related to the time in between when a user opts out and when that user has their cookie/uid zeroed out? Effectively zeroing out their cookie is the act of signaling to other publishers that this user is opted out. 

@wqi1972 there is a gap between when the user opts out on sharedid.org/optout and when the user's cookie is zeroed out (0000-000-0000). The zeroing out of the users cookie is done on the next sync. Is your concern related to this gap?

**Comment by wqi1972** [comment]
@jdwieland8282 , @yava-ua , sorry about late response on this issue.
I agree with @yava-ua , if the user cookie will be set correctly on next sync, then it is not an issue. When I raised the issue inside prebid/shared-id#7, I didn't notice the cookie sync setting inside PBJS.

I just tested and confirmed on the next sync, a new shared id will be generated. I will close prebid/shared-id#7

**Comment by jdwieland8282** [comment]
perfect, no need to apologize we all getting used to this, we appreciate your comments and help.  yes lets close #7

**Pull request closed without merging**
