### PR TITLE
Update adjust the bid value considering the viewability

### PR DESCRIPTION
**Pull request by ColombiaOnline**
## Type of change

- [x ] Bugfix

## Description of change
Update adjust the bid value considering the view-ability
Updated commit-id: 80936fe

- contact email of the adapter’s maintainer
- anil.singh1@timesinternet.in

### CODE REVIEW

**Comment by smenzer** [comment]
@ColombiaOnline please do not include `package.json` or `package-lock.json` in your PR. you should revert the changes and rebase off of master before we can approve this

**Comment by ColombiaOnline** [comment]
Close Ticket

**Comment by ColombiaOnline** [comment]
Hi @smenzer 
 What is the command of rebase off and remove file from PR.

**Comment by smenzer** [comment]
@ColombiaOnline there are several ways to do this, but the goal is to make your changes on top of a clean master. Using a rebase is a bit advanced, but allows you to put your already committed code on top of master pretty easily, see here for some explanations - https://www.freecodecamp.org/news/an-introduction-to-git-merge-and-rebase-what-they-are-and-how-to-use-them-131b863785f/. Once you've done the rebase, you can push your changes to your existing branch and it'll update the PR automatically.

You could also just close the existing PR, pull down master, and re-apply your changes on top, then submit a new PR. This is simpler, but unnecessary if you can do the rebase.

**Pull request closed without merging**
