### PR TITLE
Adloox Video Adserver Module: add new adserver module

### PR DESCRIPTION
**Pull request by jimdigriz**
## Type of change

- [X] New [Ad Server for Video](https://github.com/corememltd/Prebid.js/blob/feature/adloox/modules/adlooxAdServerVideo.js) ([documentation](https://github.com/corememltd/Prebid.js/blob/feature/adloox/modules/adlooxAdServerVideo.md))

## Description of change

Introduction of Adloox's (video) Ad Server module.

* contact email of the adapter’s maintainer: contact@adloox.com and alex+adloox@coremem.com
* this is an official submission

Disclosures:

 * optionally (enabled by default) processes the VAST tag into a Adloox VPAID JS wrapper which uses the Adloox post-buy verification script (~25kB gzipped from `j.adlooxtracking.com`)

This module automates the complex tasks an AdOps teams must perform when integrating with Adloox.

## Other information

 * module is required to bring [MRC accredited](http://www.mediaratingcouncil.org/) viewability metrics to video inventory
   * converts the VAST URL into an Adloox wrapped VAST/VPAID tag (`j.adlooxtracking.com/ads/vast/tag.php`)
   * optionally (enabled by default) walks the VAST chain and rewrites the fetched VAST tags in the chain to use [Blob URLs](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to avoid duplicate requests; solves the no-fill [`correlator`](https://support.google.com/admanager/table/9749596) related problems you get with [GAM](https://admanager.google.com/home/) tags
 * requires and communicates with the Adloox analytics module over a command processing queue
   * this module will not function without it and must not be merged before https://github.com/prebid/Prebid.js/pull/6308 has been merged
 * 'KLUDGE' commit (4ddcffaaa528c6f9e65018e173b79f351c0085ee) will be removed once I figure out (advice welcomed!) a better integration example and for us internally to merge the changes in `tag-dev.php` into `tag.php` in on Adloox's production infrastructure

This PR was created on request in https://github.com/prebid/Prebid.js/pull/6174#issuecomment-763964406

Changes since that version:
 * word smithing
 * [change eslint "warn" to "off"](https://github.com/prebid/Prebid.js/pull/6174#issuecomment-758582001) to neuter 'prebid/validate-imports' grumblings over the analytics command queue

### CODE REVIEW

**Comment by smenzer** [comment]
@osazos have you had a chance to review this yet?

**Comment by jimdigriz** [comment]
Anything I need to do here to get this merged?

Slightly concerned as it has now been a month (in this PR along) and there have been no comments about the code its-self or what may need changing. If something is needed here it would be great to hear about it sooner rather than later.

Let me know if I can help at all. Thanks

**Comment by gglas** [comment]
waiting for 6308 to resolve, dependencies between modules

**Comment by patmmccann** [comment]
removed the do not merge flag, @jimdigriz I imagine you want to rebase with the merge of #6308

**Comment by jimdigriz** [comment]
Yes thanks for that. I will work on getting the 'kludge' component fixed then rebase and poke the PR when we are ready.

**Comment by jimdigriz** [comment]
Can someone review the commit https://github.com/prebid/Prebid.js/pull/6309/commits/0f439fe8a1b7d95835bcd524edf28c8641556a68 to see if it makes sense for inclusion?

**Comment by jimdigriz** [comment]
@patmmccann @osazos any chance of reviewing commit https://github.com/prebid/Prebid.js/pull/6309/commits/54d7eab4555d96456db80804bdb6d00700b7df22 for inclusion which then unlocks this PR for merging; from our perspective as the authors.

**Comment by osazos** [comment]
Hi @jimdigriz 
Sure! Basically this one was blocked and I missed the notifications. I'll try to review it in the next days.

**Comment by jimdigriz** [comment]
> Hi @jimdigriz
> Sure! Basically this one was blocked and I missed the notifications. I'll try to review it in the next days.

This is covered by https://github.com/prebid/Prebid.js/pull/7161

**Comment by jimdigriz** [comment]
@ChrisHuie Now that #7161 is merged this PR is unblocked. @osazos kindly provided the first review and flag this for a second at some point. Can our PR now be put into the pool for the reviewers to pick up when they are free. Thanks

**Comment by jimdigriz** [comment]
@ChrisHuie @aleksatr three PR's down, two to go. Can I help with anything to get some eyeballs on this?

**Review by aleksatr — APPROVED** [review]

**Comment by aleksatr** [comment]
@ChrisHuie Changes look good to me, shall I wait for your review? (I see you in the reviewers list)

**Comment by ChrisHuie** [comment]
LGTM thanks @aleksatr

**Pull request merged**
