### PR TITLE
Adnuntius Bid Adapter: update on no cookies parameter

### PR DESCRIPTION
**Pull request by mikael-lundin**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
This pull request contains both options to remove the use of cookies for adnuntius, as well ass submitting a new module for real time data. It will be used to fetch user segments stored in Adnuntius Data, and pass it to selected bidders using ORTB2,

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: prebid@adnuntius.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/3433

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@mikael-lundin can you please pull the new RTD module into a different pr from this one that is updating an adapter? 🙏

**Comment by mikael-lundin** [comment]
I've now removed the RTD-module from this PR

**Comment by ChrisHuie** [comment]
@mikael-lundin are you still working on this pr? Seems to be a few testing errors

**Comment by mikael-lundin** [comment]
oh, yes I am. sorry for that was on a businesstrip will have a look at it !

**Comment by mikael-lundin** [comment]
Seems to be related to gumgum adapter and not Adnuntius. Trying to merge with latest master. :D

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
