### PR TITLE
Update Sonobi Bidder Adapter For Prebid 1.x

### PR DESCRIPTION
**Pull request by bansawbanchee**
## Type of change
- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter 
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change
Update Sonobi Bid Adapter For Prebid 1.x

- test parameters for validating bids
```
{
  bidder: "sonobi",
  params: {
    ad_unit: "/7780971/sparks_prebid_MR",
    sizes: [[300, 250], [300, 600]],
  }
}
```

- contact email of the adapter’s maintainer apex.prebid@sonobi.com
- [x] official adapter submission

### CODE REVIEW

**Comment by bansawbanchee** [comment]
Seems to be an issue with Chrome Headless on the Travis build. Let me know if we need to do anything to get this test to pass.

**Comment by bansawbanchee** [comment]
@mike-chowla do we have a timeframe on when this adapter will get reviewed? Thanks!

**Comment by mike-chowla** [comment]
@bansawbanchee Apologies for being slow on this.  I'll look at it today

**Comment by mike-chowla** [comment]
I'm not getting a bid back with the test parameters:

Request URL:
https://apex.go.sonobi.com/trinity.json?key_maker=%7B%22%2F7780971%2Fsparks_prebid_MR%7C21dfb9d577a57f%22%3A%22300x250%2C300x600%22%7D&ref=mike.pubmatic.com%3A9999&s=c65ebb7a-dd4c-4cfb-a108-b60db9469b34&

Request Headers:
```
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Connection:keep-alive
Content-Type:text/plain
Cookie:__uin_ox=e1d0c80e-501b-4348-a4c4-29e92b2d1952; __uin_sv=c88cedb0cb1b18e599424da76d551245; _ga=GA1.2.1711484788.1512082199; __uin_mm=50b159ee-3f4e-4b00-aad9-44079453d8a0; __uin_an=2757055929694404700; __uin_gm=ChUIq4yl9rnm_vQ0ELK7yP3PvrGDmgESKAgNEiQyMmM4NDhlNy02MDdlLTQwNDMtYTY5ZC03MWM1ZGE1NTE4MmE=; __uin_tl=15964120476609789461; __uis=ebcb5bf7-b82d-11e7-99b6-000acd29f999; __uin_rx=RX-a64c4ee1-acf9-4fc5-9e91-b6229f7d7581; __uin_pp=LCt0jcoOpOgg; __uin_td=4d467a14-b169-42c7-bb32-5c991a43344e; __uig=["sonobi-semasio-21:1512172800:5184000","7c92015dab0f9576fe63::","sonobi-semasio-22:1512172800:5184000","sonobi-semasio-37:1512172800:5184000","sonobi-semasio-9:1515888000:5184000"]; __uin_bw=22c848e7-607e-4043-a69d-71c5da55182a; HAPLB3S=s3628|Wmdp8; HAPLB3A=s3624|Wmdqw
Host:apex.go.sonobi.com
Origin:http://mike.pubmatic.com:9999
Referer:http://mike.pubmatic.com:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
```

Response Body: ```
{  
   "slots":{  
      "/7780971/sparks_prebid_MR|21dfb9d577a57f":{  

      }
   },
   "sbi_dc":"lax-1-",
   "sbi_px":[  
      {  
         "code":"ad",
         "delay":0,
         "url":"https://dpm.demdex.net/ibs:dpid=87880&dpuuid=ebcb5bf7-b82d-11e7-99b6-000acd29f999",
         "type":"image"
      }
   ]
}
```

**Comment by bansawbanchee** [comment]
Apologies. We setup a test campaign for you. That ad unit should now work outside of our own testing environment.

**Comment by mike-chowla** [comment]
Test ad is displaying now

**Comment by mkendall07** [comment]
@bansawbanchee 
This PR is good to go but you need to submit an update to https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/sonobi.md before we can merge. Thanks

**Comment by bansawbanchee** [comment]
Docs have been updated. https://github.com/prebid/prebid.github.io/pull/589

**Pull request merged**
