### PR TITLE
Add fabrick to eids file

### PR DESCRIPTION
**Pull request by andersonbd1**
## Type of change

- [X ] Other - updating modules/userId/eids.js per #6021

### CODE REVIEW

**Comment by jdwieland8282** [comment]
could you do something simpler like "neustar.com"

**Comment by andersonbd1** [comment]
@jdwieland8282 - updated to "neustar.biz"

**Review by jdwieland8282 — APPROVED** [review]
LGTM

**Comment by smenzer** [comment]
I'd suggest you update the eids.md file as well

**Comment by pm-harshad-mane** [comment]
Hello @andersonbd1 , Could you please update eids.md as well?

**Comment by pm-harshad-mane** [comment]
Hello @andersonbd1 
Gentle reminder to update the eids.md file so that we can merge the PR.

**Comment by andersonbd1** [comment]
@smenzer , @pm-harshad-mane - update made to eids.md.

**Review by smenzer — APPROVED** [review]
LGTM

**Pull request merged**
