### PR TITLE
Update Sovrn to use height / width from the response

### PR DESCRIPTION
**Pull request by ehoch**
Turns out that was silly easy. No reason to wait until next sprint @pdramos1

### CODE REVIEW

**Comment by pdramos1** [comment]
Awesome, we'll put it in the review and approve queue . :)

**Comment by mkendall07** [comment]
@pdramos1 
Is this PR good to go?

**Comment by pdramos1** [comment]
Good to go.

**Comment by pdramos1** [comment]
merged.

**Pull request merged**
