### PR TITLE
Connatix Bid Adapter: Support Events

### PR DESCRIPTION
**Pull request by rares-mihai-preda**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

### CODE REVIEW

**Comment by patmmccann** [comment]
@dgirardi could you help me find out why https://github.com/prebid/Prebid.js/pull/11548/files didnt work

**Comment by patmmccann** [comment]
op, this willl not be merging

**Comment by patmmccann** [comment]
@rares-mihai-preda this is being declined, you must use the onXevent methods available to bidders

**Comment by rares-mihai-preda** [comment]
@patmmccann 

We would appreciate your guidance on how to achieve our goal. Specifically, we need to track when an auction ends to determine which bidder won or had the highest CPM when we're participating, so we can compare it with our bid price and understand our position in the auction.

Any insights or examples you can share would be greatly appreciated.

Thank you again for your support!

**Comment by patmmccann** [comment]
@rares-mihai-preda you could contribute an analytics module or you could join the discussion at #11086

**Pull request closed without merging**
