### PR TITLE
Adding Video Support to Conversant Adapter

### PR DESCRIPTION
**Pull request by trex-conversant**
* Added support for video
* Added tagid parameter
* Added pos parameter
* Changed API endpoint
* Added support for multiple sizes per ad unit
* Updated tests.

## Type of change

- [x ] Feature
- [x ] Code style update (formatting, local variables)

## Description of change

Added in support for video, the bulk of this PR. Added in additional parameters which required minor changes. Now supporting multiple sizes per ad unit via new API endpoint.

### CODE REVIEW

**Comment by dbemiller** [comment]
Hey. Since your params are changing, could you also open a PR to update [the docs](http://prebid.org/dev-docs/bidders.html#conversant)?

We'll also need some sample params we can use for testing (eg `site_id`).

**Comment by trex-conversant** [comment]
Hi @dbemiller you can use site ID 108060 to test with. And thank for the info on the doc PR, will do.

**Comment by dbemiller** [comment]
I'm not seeing any VAST content or URL coming from your adapter... using this cannibalized source code from [the example page](http://video-demo.appnexus.com/pbjs/mjacobson/video_testing/prebid_video_videojs_new.html):

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Prebid.js video adUnit example</title>

    <!-- videojs -->
    <link rel="stylesheet" href="http://vjs.zencdn.net/5.9.2/video-js.css">
    <script type="text/javascript" src="http://vjs.zencdn.net/5.9.2/video.js"></script>

    <!-- videojs-vast-vpaid -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/videojs-vast-vpaid/2.0.2/videojs.vast.vpaid.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-vast-vpaid/2.0.2/videojs_5.vast.vpaid.min.js"></script>

    <!-- prebid.js -->
    <script src="../../build/dev/prebid.js" async></script>


    <script>

      var pbjs = pbjs || {};
      pbjs.que = pbjs.que || [];

      /*
       Prebid Video adUnit
       */

      var videoAdUnit = {
        code: 'video1',
        sizes: [640,480],
        mediaType: 'video',
        bids: [
          {
            bidder: 'conversant',
            params: {
              site_id: '108060',
              video: {
                skipppable: true,
                playback_method: ['auto_play_sound_off']
              }
            }
          }
        ]
      };

      pbjs.que.push(function(){
        pbjs.addAdUnits(videoAdUnit);
        pbjs.requestBids({
          timeout : 700,
          bidsBackHandler : function(bids) {
            console.log("BIDS ARE:");
            console.log(bids);
          }
        });
      });

      pbjs.bidderSettings =
        {
          standard: {
            adserverTargeting: [
              {
                key: "hb_bidder",
                val: function (bidResponse) {
                  return bidResponse.bidderCode;
                }
              }, {
                key: "hb_adid",
                val: function (bidResponse) {
                  return bidResponse.adId;
                }
              }, {
                key: "hb_pb",
                val: function (bidResponse) {
                  return "10.00";
                }
              }, {
                key: "hb_size",
                val: function (bidResponse) {
                  return bidResponse.size;

                }
              }
            ]
          }
        };

    </script>
</head>
<body></body>
</html>
```

Am I missing something?

**Comment by trex-conversant** [comment]
PR for Docs: https://github.com/prebid/prebid.github.io/pull/240

**Comment by trex-conversant** [comment]
For testing video, please test with site_id 88563.

**Comment by mkendall07** [comment]
Please fix linting errors. You can use `eslint --fix`

**Comment by dbemiller** [comment]
@trex-conversant After that merge, the diff shows 211 files changed. Please rebase, or open a new PR, to get a clean diff.

**Comment by dbemiller** [comment]
Bids are coming back invalid with site_id 88563...



screen shot 2017-06-01 at 1 07 05 pm

**Comment by trex-conversant** [comment]
Unfortunate timing, the test campaign just happened to end today, but I've renewed it. It should be good now.

**Comment by dbemiller** [comment]
@trex-conversant Looks like another conflict popped up

**Pull request merged**
