### PR TITLE
adyoulike Bid Adapter: Add userIds to bidrequest

### PR DESCRIPTION
**Pull request by guiann**
## Type of change

- [*] Feature

## Description of change
Transmit userIds from bid request if given.

- contact email of the adapter’s maintainer
 guillaume.andouard@adyoulike.com
- [*] official adapter submission

I am wondering if there is a standard way to test userId modules on an actual test page ? I've been trying to setup some userId module but I never receive any user ids...
Can anyone guide me through this process ? 

Thank you.

### CODE REVIEW

**Comment by guiann** [comment]
HEre is the PR on  prebid.github.io for documentation:

https://github.com/prebid/prebid.github.io/pull/3388

**Comment by patmmccann** [comment]
@guiann can you remove your changes to package lock from your pr?

**Comment by guiann** [comment]
Sure!   Done.

**Comment by guiann** [comment]
Again, If anyone can guide me trough a test process for the userId feature ? Is there a way to force some userIds to be sent with one or more userId modules ?

**Comment by ChrisHuie** [comment]
@guiann looks like tests are failing but should be fixed if you pull in recent commits from master. There was a bugfix recently for a sizing issue.

**Comment by guiann** [comment]
Done. thank you  Chris.

I'm still looking for a way to test userIds transmission. Do you know how to force it for end to end test purpose ?

**Comment by patmmccann** [comment]
@guiann are https://github.com/prebid/Prebid.js/blob/24ac6e3603415f0f3039a0ac8c15cce3dd72ffa1/test/spec/modules/eids_spec.js#L102 and https://github.com/prebid/Prebid.js/blob/24ac6e3603415f0f3039a0ac8c15cce3dd72ffa1/test/spec/modules/userId_spec.js#L953 what you are looking for?

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
