### PR TITLE
AdPartner bidadapter init

### PR DESCRIPTION
**Pull request by preved-medved**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by GLStephen** [comment]
@preved-medved your test params are blank. Can you please provide valid params? they are required to approve.

**Comment by bretg** [comment]
docs pr https://github.com/prebid/prebid.github.io/pull/1961

**Comment by preved-medved** [comment]
Hello, @GLStephen 
If I right to understand you comment, you can't see any ads in banner. I change the ID of test banner, and now You can see ads in our block.

**Comment by GLStephen** [comment]
LGTM

**Comment by GLStephen** [comment]
You can add yourself to Header Bidder Expert if you want to be in there: https://github.com/prebid/headerbid-expert

**Pull request merged**
