### PR TITLE
CCX Bid Adapter: add support for mediatypes video parameters

### PR DESCRIPTION
**Pull request by mjaworskiccx**
## Type of change

- [ ] Bugfix
- [ x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@mjaworskiccx it looks like you pulled code from after pr #6689 was merged. We had to revert it out that pr this morning #6735 so pulling a recent version should fix these test errors.

**Review by ChrisHuie — APPROVED** [review]

**Comment by ChrisHuie** [comment]
@mjaworskiccx can you please pull from upstream master again. When you happened to pull recent commits there was one we had to revert

**Comment by patmmccann** [comment]
please also fix the examples at https://github.com/prebid/Prebid.js/blob/master/modules/ccxBidAdapter.md and your bidder doc. Thanks!

**Comment by mjaworskiccx** [comment]
docs update

**Pull request merged**
