### PR TITLE
check if bidder exists before making request object

### PR DESCRIPTION
**Pull request by jsnellbaker**
## Type of change

- [x] Bugfix

## Description of change
To fix the issue #2677

Currently when an invalid/unknown bidder is used in an auction, a request object is still made for that bidder.  When the auction is running, it will recognize the bidder wasn't real and would return an error.  But the `done` related code used latter in the auction would still try to wait for that bidder's request to respond causing the auction to wait for the timeout.  

This fix performs the check to validate the bidder earlier, and if the bidder is rejected then the request object doesn't get made.  This streamlines the latter logic to only wait for bidders that are real/registered.

### CODE REVIEW

**Comment by robertrmartinez** [comment]
@jsnellbaker Pulled this branch and confirmed it fixes #2677.

Thanks!

**Comment by jsnellbaker** [comment]
@mkendall07 I removed the redundant check in the `callBids` function.

**Comment by harpere** [comment]
@jsnellbaker  this has conflicts that need to be resolved.

**Comment by jsnellbaker** [comment]
@harpere the conflict should be resolved now.

**Pull request merged**
