### PR TITLE
add new version for DecenterAds

### PR DESCRIPTION
**Pull request by vlaktion**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by vlaktion** [comment]
Hello. How long waits to merge my commits into the Master branch?

**Comment by smenzer** [comment]
typically reviews are done within a week.

**Comment by vlaktion** [comment]
Thank you

**Comment by vlaktion** [comment]
Will this commit be included in version 4.0 and higher or only in the latest 4.6? And how to add adapters for versions 3.17 and higher?

**Comment by smenzer** [comment]
> Will this commit be included in version 4.0 and higher or only in the latest 4.6? And how to add adapters for versions 3.17 and higher?

We don't do merges to old branches except near the time of major version releases. 3.27.1 was the last 3.x release and there are no more planned.

There are not separate branches for each minor version change that you can commit against and that are maintained independently. If you make commits now, your existing adapter would be in 4.5 and your changes would likely be in 4.7 or 4.8. The version that is in 4.5 now will never change. Every week the number increments, with any change to 4.x

Please take a look at the conversation in this PR, it has more details: https://github.com/prebid/Prebid.js/pull/5680#issuecomment-686565338

**Review by FilipStamenkovic — APPROVED** [review]
LGTM

**Comment by FilipStamenkovic** [comment]
@vlaktion You bidder will be available from pbjs 4.8.0 (next release)

**Comment by vlaktion** [comment]
Hello. Can you add this commits to 4.5 or 4.6, please?

**Comment by smenzer** [comment]
@vlaktion please see my previous comments...we do not merge to old branches or versions. this will go out in the next prebid release, scheduled for next week.

**Pull request merged**
