### PR TITLE
Jwplayer doc changes for FPD update

### PR DESCRIPTION
**Pull request by karimMourra**
## Type of change

- [x] Documentation

## Description of change
Updates the documentation and demo for changes introduced in FPD update https://github.com/prebid/Prebid.js/pull/6293, and adds a contact info. 

- link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/2695

## Other information
Must be merged with https://github.com/prebid/Prebid.js/pull/6293

### CODE REVIEW

**Comment by patmmccann** [comment]
is this based on a branch other than master? can we wait till that is merged first?

**Review by patmmccann — APPROVED** [review]
@ChrisHuie can you add do not merge flag

**Comment by patmmccann** [comment]
@karimMourra i think you'll still have to rebase your branch when #6293 is done

**Comment by FilipStamenkovic** [comment]
@karimMourra Please remove all commits made by @mmoschovas from your PR, this PR should only contain commits that are changing your adapter/module (or example for your adapter).  
Then, after #6293 is merged then you should pull/rebase this PR (like suggested by @patmmccann).

**Review by FilipStamenkovic — CHANGES_REQUESTED** [review]
Please take a look at my previous comment.

**Comment by karimMourra** [comment]
@FilipStamenkovic addressed

**Review by FilipStamenkovic — APPROVED** [review]
LGTM.  

Waiting for #6293 to be merged before this one is merged.

**Comment by karimMourra** [comment]
@FilipStamenkovic #6293 has been merged; can we merge this PR ?

**Pull request merged**
