### PR TITLE
Update Adyoulike Adapter to prebid 1.0

### PR DESCRIPTION
**Pull request by jeremyAdyoulike**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Version 1.0 of the Adyoulike Adapter, every mandatory params are the same as previous version

- test parameters for validating bids
```
{
 bidder: 'adyoulike',
params: {
  placement: '194f787b85c829fb8822cdaf1ae64435'
  }
}
```
- jeremy.hernandez@adyoulike.com
- [x] official adapter submission

https://github.com/prebid/prebid.github.io/pull/633

### CODE REVIEW

**Comment by mike-chowla** [comment]
I'm not getting any bids back with the test parameters:
Request:

```
POST /hb-api/prebid/v1? HTTP/1.1
Host: hb-api.omnitagjs.com
Connection: keep-alive
Content-Length: 195
Pragma: no-cache
Cache-Control: no-cache
Origin: http://mike.pubmatic.com:9999
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Content-Type: text/plain
Accept: */*
Referer: http://mike.pubmatic.com:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: ayl_visitor=160181e842820164783b47b2e478da8a; __cfduid=d22ccaf4e1c3df8c26f7d1043c64de8771513983785
{  
   "Version":"1.0",
   "Bids":{  
      "25067855216796":{  
         "PlacementID":"194f787b85c829fb8822cdaf1ae64435",
         "TransactionID":"f9a1a143-df48-4571-9d81-58391bf60da4",
         "width":300,
         "height":250
      }
   },
   "PageRefreshed":true
}

```

Response Body:
```
[  
   {  
      "Price":0,
      "Attempt":"b1f53ae162abe30b194f787b85c829fb",
      "Placement":"194f787b85c829fb8822cdaf1ae64435",
      "Ad":"",
      "CreativeID":"b1f53ae162abe30b194f787b85c829fb",
      "BidID":"25067855216796"
   }
]
```

**Comment by jeremyAdyoulike** [comment]
@mike-chowla could you try again? 
normally now is OK

**Comment by mike-chowla** [comment]
Bid requests are failing due to a CORS issue:
screen shot 2018-02-12 at 4 16 50 pm

You can fix it by setting withCredentials to false
```
@@ -45,10 +45,16 @@ export const spec = {
       PageRefreshed: getPageRefreshed()
     };
     const payloadString = JSON.stringify(payload);
+
+    const options = {
+      withCredentials: false
+    };
+
     return {
       method: 'POST',
       url: createEndpoint(dcHostname),
       data: payloadString,
+      options: options
     };
   },
   /**

```

**Comment by jeremyAdyoulike** [comment]
@mike-chowla I'm sorry for the delay.
I set withCredentials to false.

Could you test anew?

**Comment by jeremyAdyoulike** [comment]
@mike-chowla 
docs here:
https://github.com/prebid/prebid.github.io/pull/633

thanks :smiley:

**Pull request merged**
