### PR TITLE
eTarget Bid Adapter: getMetaData feature moved into bidderRequest

### PR DESCRIPTION
**Pull request by etargetse**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by etargetse** [comment]
@ChrisHuie @patmmccann Hey guys, can you please review our changes, Thanks.

**Comment by etargetse** [comment]
@ChrisHuie can you request review from someone else? it looks like @patmmccann is on vacation or something.

**Comment by etargetse** [comment]
@ChrisHuie @patmmccann Hi, what is going on? You are probably too busy but can you please review our adapter? Thanks.

**Comment by ChrisHuie** [comment]
@etargetse sorry Pat is on vacation. I will review this pr today

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
