### PR TITLE
add stv adapter

### PR DESCRIPTION
**Pull request by onlsol**
## Type of change
- [ x] New bidder adapter  

## Description of change
New adapter

- test parameters for validating bids
```

mediaTypes: {
  video: {
   playerSize: [640, 480],
   context: 'instream'
   }
 },
bids: [{
--
   bidder: 'stv',
   params: {
      placement: 'prer%3D613'
    }
  }]


```

Be sure to test the integration with your adserver using the [Hello World](/ntegrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by onlsol** [comment]
@jsnellbaker Done. I pushed new commit with changes.

**Comment by jsnellbaker** [comment]
@onlsol Thanks for making the update.  I ran the circleCI tests locally and found everything was passing successfully.  It only failed here because it was trying to run them with a different account that didn't have access to browserstack.

**Comment by onlsol** [comment]
Thank You

**Comment by bretg** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/1255

**Pull request merged**
