### PR TITLE
Novatiq ID System: add snowflake userId submodule

### PR DESCRIPTION
**Pull request by novatiq**
Novatiq snowflake userId submodule initial release

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by jdwieland8282 — CHANGES_REQUESTED** [review]
can you copy the contents of novatiqidsystem.md to https://github.com/prebid/prebid.github.io/blob/master/dev-docs/modules/userId.md
We'd like to have a second PR against prebid.github.io

**Comment by jdwieland8282** [comment]
There are 6 files additional files that need to be modified in order to successfully merge a user id module. 

1. https://github.com/prebid/Prebid.js/blob/master/modules/userId/userId.md
2. https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.md
3. https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.js
4. https://github.com/prebid/Prebid.js/blob/master/modules/.submodules.json

Docs PR against prebid.github.io
5. https://github.com/prebid/prebid.github.io/blob/master/dev-docs/modules/userId.md
6. https://github.com/prebid/prebid.github.io/blob/master/download.md

**Review by jdwieland8282 — APPROVED** [review]

**Comment by smenzer** [comment]
can you please link to the related docs pr?

**Comment by jdwieland8282** [comment]
Docs PR: https://github.com/prebid/prebid.github.io/pull/2718

**Review by smenzer — APPROVED** [review]
LGTM

**Pull request merged**
