### PR TITLE
Prebid Core: Update `renderAd` to use hook

### PR DESCRIPTION
**Pull request by iamnewton**
## Type of change

- [x] Feature

## Description of change

Updating `renderAd` to use hook in preparation to use in a Fledge proposal test.

### CODE REVIEW

**Comment by jsut** [comment]
It seems like this could replace #7059. Hooks seem to be more flexible than the event system is, but perhaps there are trade offs I am not aware of?

**Comment by robertrmartinez** [comment]
@jsut 

I think both make sense.

Adding and using this hook delays the execution of the renderAd function until your piece of code finishes and calls it directly. This hook stuff is mainly used to alter and change things before the hooked function executes.

The Event Library is more for notifying, and is non blocking. So I think both have a place, and AD_RENDER_SUCCEEDED seems like a valid event (Since there are times when a BID_WON Does not equal a Ad Successfully rendering)

**Comment by robertrmartinez** [comment]
@iamnewton Will you pull latest master, there was a fix for a flaky test merged.

**Review by robertrmartinez — COMMENTED** [review]
Looks fine.

I would like @snapwich to give his input since the hook library is his baby.

Rich, what are the impacts of adding this hook in the scenario where 99.9% of prebid wrappers will not actually register a hook.

What kind of overhead is there?

**Comment by snapwich** [comment]
very little overhead. this should be fine.

as for the event, hooks don't replace events; if you need the event i'd add that as well.

**Review by snapwich — APPROVED** [review]

**Comment by jsut** [comment]
@snapwich @robertrmartinez thanks for the context.

**Review by robertrmartinez — APPROVED** [review]

**Pull request merged**
