### PR TITLE
schain complete 0 omitted from yield request

### PR DESCRIPTION
**Pull request by IDRATHERDANCE**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

if schain `complete` equals 0 it was omitted from yield request. That is a bug. According to the standards described here: https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/supplychainobject.md. Complete can be 0 or 1. This is a simple fix.

- test parameters for validating bids
```
{
  bidder: 'yieldlab',
  params: {
    schain
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by smenzer** [comment]
please remove `package-lock.json` from this PR before we can merge, thanks!

**Comment by smenzer** [comment]
you don't want to delete the package-lock.json file, we need that in the repository...you just need to remove it from the PR...if it's easier you can create a new PR that does not include the file in any commit.

**Comment by IDRATHERDANCE** [comment]
sure, thanks. i will create a new pr and close this one

**Comment by IDRATHERDANCE** [comment]
https://github.com/prebid/Prebid.js/pull/5902

**Pull request closed without merging**
