### PR TITLE
Vidazoo Bid Adapter: support for Video MediaTypes

### PR DESCRIPTION
**Pull request by uditalias**
## Type of change
- [X] Feature

## Description of change

Added support for video media types

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@uditalias can you update documentation for this change and looks like one of your unit tests is currently failing.

**Comment by uditalias** [comment]
@ChrisHuie 
Test fixed + added PR for prebid.github.io with updated media_types

https://github.com/prebid/prebid.github.io/pull/4180

**Comment by patmmccann** [comment]
can you cover your changes with a test video request

**Comment by uditalias** [comment]
> can you cover your changes with a test video request

Hey @patmmccann Added tests for video media type request

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
