### PR TITLE
Blue Billywig bid adapter update

### PR DESCRIPTION
**Pull request by K-JBoon**
## Type of change

- [x] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Bit of a messy one, as it includes the following changes:

- General code quality upgrade (Code style update)
- Correctly flag returned bids as a video mediatype (Bugfix)
- Always hit user syncs, also if we don't get bid responses (Feature)
- Validate video params, and allow submitting them additionally on the bidder params (Feature)
- Recognize VAST URL on bids in a few more situations (Feature)
- Remove DigiTrust (Maintenance)

If this needs to be split into multiple PRs please let me know.

- contact email of the adapter’s maintainer: dev+prebid@bluebillywig.com

Docs PR:
https://github.com/prebid/prebid.github.io/pull/2198

### CODE REVIEW

**Comment by K-JBoon** [comment]
Hey @ncolletti , just wondering if you needed any additional info for the review?

**Comment by K-JBoon** [comment]
Hi @ncolletti / @mkendall07 , would really like to get an update on the progress/any blockers here, or have it re-assigned for review.

**Comment by ncolletti** [comment]
Sorry for the delay. These changes look good to me.

**Review by ncolletti — APPROVED** [review]

**Comment by K-JBoon** [comment]
@ncolletti All good, thanks for the review!

**Pull request merged**
