### PR TITLE
Serverbid Legacy Adapter

### PR DESCRIPTION
**Pull request by jcswart**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Adds an alias to legacy adapter.

Doc PR: https://github.com/prebid/prebid.github.io/pull/568

### CODE REVIEW

**Comment by mkendall07** [comment]
just to be clear, we are only accepting bug fixes into legacy or 1.0 compliant adapters. We are not reviewing/testing anything that doesn't adhere to the 1.0 format. Thanks

**Comment by jcswart** [comment]
@mkendall07 @snapwich So if I revert this to the 1.0 adapter that was included in 0.34.X and simply add the alias that I need then anyone that downloads the legacy version of Prebid will have a properly working adapter? Do I understand you correctly?

**Comment by mkendall07** [comment]
@jcswart 
correct

**Comment by jcswart** [comment]
Thanks!

**Comment by jcswart** [comment]
@snapwich @mkendall07 I've simply added the alias and reverted the previous changes.

**Pull request merged**
