### PR TITLE
PulsePoint: Fixing endpoints for HTTPS compatibility

### PR DESCRIPTION
**Pull request by anand-venkatraman**

### CODE REVIEW

**Comment by ojotoxy** [comment]
This change seems to make the pulsepoint adapter not work very well, but still works a little. (I see about a 100x reduction in pulsepoint wins..) I had to stop using this code. I am not really sure what the problem is.

Why is the bidding URL for pulsepoint changing?

**Comment by anand-venkatraman** [comment]
@ojotoxy, the bidder url endpoint change doesnt change anything underlying. If you can provide me more context and a test page probably, I can help you with this. You can reach me at avenkatraman@pulsepoint.com

**Comment by mkendall07** [comment]
Is it possible the amount of demand is lower for secure pages (and the tags available to serve on them) is the cause?

**Comment by anand-venkatraman** [comment]
@mkendall07, we did identify the issue with the endpoint, the rollout should happen in an hour, and it should fix the issue. Thanks to @ojotoxy for letting us know.

**Comment by mkendall07** [comment]
@anand-venkatraman  thanks for the quick fix @ojotoxy  for reporting!

**Pull request merged**
