### PR TITLE
Update adkernelBidAdapter.js

### PR DESCRIPTION
**Pull request by Avimobi**
description: Prebid adbite Bidder Adaptor
Host: cpm.adbite.com

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by robertrmartinez — APPROVED** [review]

**Review by robertrmartinez — CHANGES_REQUESTED** [review]
Looks fine but add / update your tests for aliases.

They are failing

**Review by Avimobi — COMMENTED** [review]
We have change the array and count which you suggested. plz check and let us know if you need anything else.

**Comment by robertrmartinez** [comment]
@Avimobi 

Did you forget to check in and push to this branch?

Still to associated change to the _spec file.


I do not see a commit since my comment.

**Comment by robertrmartinez** [comment]
@Avimobi I see you added two new PR's

I have closed those and ask that you simply update this PR with the changes to the spec file please.

**Comment by Avimobi** [comment]
Hello robert
I am extremely sorry for delay. I have made changes to _spec file and committed to same branch. Plz check and let me know in case you need any thing else.

**Comment by robertrmartinez** [comment]
no worries. Thanks for making the update

**Review by robertrmartinez — APPROVED** [review]

**Pull request merged**
