### PR TITLE
Prebid Core: Added aliasRegistry to the Public API

### PR DESCRIPTION
**Pull request by jlquaccia**
## Type of change
- [x] new feature

## Description of change
- Added aliasRegistry from adapterManager to the Public API

## Other information
Github Issue: https://github.com/prebid/Prebid.js/issues/8568
PR for documentation updates: https://github.com/prebid/prebid.github.io/pull/4308

### CODE REVIEW

**Comment by patmmccann** [comment]
that was simpler than i expected it to be lol :) we want to add one feature here I think. In the committee I think we wanted to preserve the ability of publishers to keep this non-public if for some reason that was important to them, so can we add a config check, with pubs using the 'https://docs.prebid.org/dev-docs/publisher-api-reference/setConfig.html' call to do something maybe like pbjs.setConfig({ 'aliasRegistry': 'private'}) ?

**Review by patmmccann — CHANGES_REQUESTED** [review]
awesome, ty! let's add the ability to hide it in config in case anyone is relying on private aliases

**Comment by patmmccann** [comment]
i think what i am suggesting in js would look something like: `if not config.getConfig('aliasRegistry') === 'private' {$$PREBID_GLOBAL$$.aliasRegistry = adapterManager.aliasRegistry};`

**Comment by jlquaccia** [comment]
@patmmccann haha yea definitely turned out to be a quick one, easier than I had originally thought.  Cool sounds good!  Refactored things a bit so that now the default is for the aliasRegistry to be public but if it is set to private the registry will no longer be accessible on the public api.  Also just updated the PR for the doc changes related to this PR: https://github.com/prebid/prebid.github.io/pull/4308

**Review by patmmccann — APPROVED** [review]

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
