### PR TITLE
Optimon Analytics Adapter: add new analytics adapter

### PR DESCRIPTION
**Pull request by pixelgroup-israel**
## Type of change
- [x] Feature

## Description of change
Initial release of the Optimon Prebid Analytics Adapter.

### CODE REVIEW

**Comment by Rothalack** [comment]
Hey @pixelgroup-israel I think the two major things left to do are steps 3 and 5 here.
https://docs.prebid.org/dev-docs/integrate-with-the-prebid-analytics-api.html

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/2707

**Comment by Rothalack** [comment]
Thanks @bretg 

@pixelgroup-israel Now that I see you've got the docs there, that just leaves the test file step. It is Step 3 in the dev docs I linked above.

You would create the test here I believe test/spec/modules/optimonAnalyticsAdapter_spec.js
There's lots of examples in that folder as well.

**Comment by pixelgroup-israel** [comment]
Hi,
I have added the unit testing.
Can you please re-check?

Thanks,
Amit

**Review by Rothalack — APPROVED** [review]
This looks good!

**Pull request merged**
