### PR TITLE
IndexExchange Bid Adapter: Added support for netID, ID+ and FabrickId userId

### PR DESCRIPTION
**Pull request by li-ran**
## Type of change

- [X] Feature

## Description of change
Added support to netID, ID+ and FabrickId userId in IndexExchange Adapter

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @li-ran ,
Prebid UserId module provides available userIds in eids format as well, you may directly consume the UserIds in EIDs format or filter as needed, 
Example: https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L702
Refer: https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.md and https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.js

**Review by Fawke — CHANGES_REQUESTED** [review]
@li-ran 

Looks good overall, but I think you don't wanna update the `package-lock.json` file. Can you revert that change.

Also, as @pm-harshad-mane as pointed out, if you want, you can get rid of your custom function, `addUserEids` since the User Id module already does this conversion for you.

Furthermore, it'll be ideal if you update the docs on Prebid.org by adding `userIds:` key in the meta information for the doc. It'll help publisher quickly identify which userIds you support. You can refer to the [appnexus docs](https://raw.githubusercontent.com/prebid/prebid.github.io/master/dev-docs/bidders/appnexus.md) for more details.

**Comment by li-ran** [comment]
Hi @pm-harshad-mane, @Fawke,

I have updated the ixBidAdapter to use _userIdAsEids_ in Prebid userID module.
Here is the PR for the documentation updates: https://github.com/prebid/prebid.github.io/pull/2699

Please let me know if there is anything else that need to be updated.

**Review by Fawke — APPROVED** [review]
LGTM

**Pull request merged**
