### PR TITLE
C-Wire Bid Adapter: Code refactorings

### PR DESCRIPTION
**Pull request by espen-j**
## Type of change
Refactoring (no functional changes, no api changes)

## Description of change

A bigger refactoring of the code:
- Less Customizations and processing for the sent bids
  - While keeping backwards compatibility
- Remove unsupported types, namely VIDEO, and all related code.
- Add test cases
- Add debug flag and feature flags
- More clear documentation, hopefully.

Sorry, this is a bigger change. It should be well unit-tested and the integration test also works using the hello-world example.

### CODE REVIEW

**Comment by espen-j** [comment]
Looks like a flaky test? I can't re-trigger it.

```
[2-2] 2023-01-20T17:01:34.499Z INFO webdriver: DATA {
[2-2]   using: 'css selector',
[2-2]   value: 'body > div[class="GoogleActiveViewElement"] > a > img, body > div[class="GoogleActiveViewElement"] > div[class="card"]'
[2-2] }
[1-0] Error in "Prebid.js Banner Ad Unit Test "before all" hook for "should load the targeting keys with correct values""
Error: Timeout of 60000ms exceeded. The execution in the test "Prebid.js Banner Ad Unit Test "before all" hook for "should load the targeting keys with correct values"" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/circleci/Prebid.js/test/spec/e2e/banner/basic_banner_ad.spec.js)
    at createTimeoutError (/home/circleci/Prebid.js/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/errors.js:498:15)
    at Hook.Runnable._timeoutError (/home/circleci/Prebid.js/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:431:10)
    at Timeout.<anonymous> (/home/circleci/Prebid.js/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:246:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```

**Review by Fawke — COMMENTED** [review]
Hi @espen-j,

Your changes mostly look good. I also wanted to get a test bid back, but using your default params in the md file didn't give me any bids.

Just want to make sure that after the refactoring nothing broke and bids are coming back and ad is rendering. Is there any way to force a bid back?

**Comment by espen-j** [comment]
Hi @Fawke 

Thanks for the review! 
I added the prebid version to the request object and rebased the branch on top of latest master.

You can test the adapter here:
https://creatives-testing.cwi.re/prebid/?cwcreative=2930

In the payload you should see the current prebid version attached to the bid request. Hope this helps!

**Comment by espen-j** [comment]
Build failed, but looks like a [flaky, unrelated test](https://app.circleci.com/pipelines/github/prebid/Prebid.js/14524/workflows/225533ea-9143-4e92-884a-d050e458dbbd/jobs/26599?invite=true#step-106-3733)?
```
[firefox 109.0 windows #2-6] 1) Prebid.js Native Ad Unit Test should render GAM creative
[firefox 109.0 windows #2-6] expected false to be true      
      actual expected
      
      falsetrue
      
[firefox 109.0 windows #2-6] AssertionError: expected false to be true
[firefox 109.0 windows #2-6]     at Context.<anonymous> (/home/circleci/Prebid.js/test/helpers/testing-utils.js:45:11)
[firefox 109.0 windows #2-6]
[firefox 109.0 windows #2-6] 2) Prebid.js Native Ad Unit Test should render GAM creative
[firefox 109.0 windows #2-6] data did not match any variant of untagged enum FrameId at line 1 column 2893
[firefox 109.0 windows #2-6] invalid argument: data did not match any variant of untagged enum FrameId at line 1 column 2893
[firefox 109.0 windows #2-6]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[firefox 109.0 windows #2-6]     at Object.switchFrame (/home/circleci/Prebid.js/test/helpers/testing-utils.js:16:13)
[firefox 109.0 windows #2-6]     at Context.<anonymous> (/home/circleci/Prebid.js/test/helpers/testing-utils.js:39:17)

```

**Review by Fawke — APPROVED** [review]
Looks good. Some tests are flaky, I re-ran them, and all passed.

**Comment by espen-j** [comment]
Thanks @Fawke 🙇

**Pull request merged**
