### PR TITLE
Bidfluence Adapter update - Single call

### PR DESCRIPTION
**Pull request by francescocristallo**
## Type of change

- [x] Refactoring (no functional changes, no api changes)

## Description of change
Same code refactored for sending a single call to the server instead of multiple calls for each bid

- integrations@bidfluence.com
- [x] official adapter submission

### CODE REVIEW

**Comment by francescocristallo** [comment]
@jsnellbaker 
The params are the same for both endpoints, I created a test page and used the v1 one and it works. Could you please post the call payload? It could be a security restriction blocking the call our side.

Thanks

**Comment by jsnellbaker** [comment]
@francescocristallo Below is a copy of the request payload:
```
{"v":"2.0","azr":true,"ck":true,"re":"http://ap.localhost:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true","st":["http://ap.localhost:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true"],"tz":"300","sr":"1680x1050x24","tm":3000,"vp":"1682x348","sdt":"2018/12/05 20:01:47","top":true,"gdpr":false,"gdprc":"","bids":[{"bid":"2e8f27de25bc82","tid":"1000","pid":"1000","rp":0,"w":"300","h":"250"}]}
```

**Comment by francescocristallo** [comment]
@jsnellbaker Thanks, as I thought the new endpoint was blocking the localhost address. I fixed it, now it returns the test Ad correctly.

**Comment by jsnellbaker** [comment]
Thanks for the update; LGTM

**Pull request merged**
