### PR TITLE
Richaudience Bid Adapter : add compatibility to GPP

### PR DESCRIPTION
**Pull request by richaudience**
## Type of change

- [ ] Bugfix
- [ x ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@richaudience please see issue #11044

**Comment by ChrisHuie** [comment]
@richaudience Can you please fix how you are getting timeout to not use the config but what is passed? We fixed a bunch of adapters on this issue but seems like we missed yours. Thanks

**Comment by patmmccann** [comment]
@richaudience the config timeout may not be correct; see https://github.com/prebid/Prebid.js/issues/8973#issuecomment-1241393541

Only use the timeout from the request to set tmax

**Comment by richaudience** [comment]
Hi @patmmccann 
Sorry, I don't understand, you need that change the name of the key"timeout" for "tmax" ? 
In the adapter is not used the object "timeout" for nothing is only enriched the request.
You can clarify to me the change you have need?
Cheers

**Review by ChrisHuie — APPROVED** [review]

**Comment by ChrisHuie** [comment]
tmax

**Comment by ChrisHuie** [comment]
tmax

**Comment by richaudience** [comment]
Hi @ChrisHuie 
The changes have been approved, but when will be merged into master branch?
If you need anything, something more? If waiting, your response.
Cheers

**Comment by richaudience** [comment]
Hi! @ChrisHuie @patmmccann  
Is very important that we have this changes in the last version of Prebid, please you need anything more?
I am wanting your response.
Cheers

**Comment by patmmccann** [comment]
@richaudience what is your plan for #11044

**Pull request merged**
