### PR TITLE
SmileWanted Bid Adapter: support schain

### PR DESCRIPTION
**Pull request by QuentinGallard**
## Type of change

- [x] Updated bidder adapter   

## Description of change

Add schain support to the SmileWanted Bid Adapter

## 📋 Checklist

- [x]  https://github.com/prebid/prebid.github.io/pull/5109

### CODE REVIEW

**Review by patmmccann — CHANGES_REQUESTED** [review]
Please import this function from a library for both you and equativ

**Comment by QuentinGallard** [comment]
Sorry @patmmccann patmmccann, I can not see the failed tests on CircleCI.
All I see is:

> 404 ERROR
> 
> Page Not Found
> We can't find what you're looking for, but the links below may get you back on track

Is 8.52.0 the last tag in 8.x.x? I can't find a branch dedicated to 8.53.0 for sending the pull request.

Do we need to migrate to 9.x.x for this patch?

**Comment by patmmccann** [comment]
Yes,, next release is 9.1

It appears you're using the same function as equativ aka smartadsever. You need to modify both your adapter and theirs to import the function from a library.

**Comment by patmmccann** [comment]
Circleci generates a linting error on multiple blank lines

**Comment by QuentinGallard** [comment]
@patmmccann How can I access to the CircleCI tests to know exactly why it failed ?
I fixed the multiple blank lines, but it still failed. If I can't access to the CircleCi, can I have a copy of their report ?

Which function is the same as Equativ ? Is it `getUserSyncs` or `serializeSupplyChain` or something else ?

For serializeSupplyChain, I see it in:
- aja,
- adocean,
- gumgum,
- rubicon,
- equativ / smartadserver
- and vidoomy

And for getUserSyncs, I see it in:
- luponmedia
- adtrue
- setupad

I don't think I have the legitimacy to edit the code of other bidders, who are potentially our competitors.
And I don't know enough about the Prebid.js project to know where to put this kind of library.

**Comment by patmmccann** [comment]
> I don't think I have the legitimacy to edit the code of other bidders, who are potentially our competitors.

Sure you do, I will happily review to make sure you are not breaking them. If you do not edit their tests, all should be well. Anyone is welcome to improve the code quality of the project.

> And I don't know enough about the Prebid.js project to know where to put this kind of library.

Here is a handy example:

https://github.com/prebid/Prebid.js/pull/11824

**Comment by QuentinGallard** [comment]
Can you confirm it only concerns serializeSupplyChain ?
And can I add this function in [/home/quentin/PhpstormProjects/prebidjs/modules/schain.js](https://github.com/prebid/Prebid.js/blob/master/modules/schain.js) or do you suggest something else ?

**Comment by patmmccann** [comment]
Yes please solve that function but add it to /libraries/schains/index.js

**Comment by patmmccann** [comment]
https://github.com/prebid/Prebid.js/pull/11849 is a great example of a recent pr moving a duplicated function into a library

**Comment by patmmccann** [comment]
I fixed your linting error but not your test throws an assertion error

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
