### PR TITLE
Discovery Bid Adapter ：parameter change

### PR DESCRIPTION
**Pull request by cuihua111**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Comment by cuihua111** [comment]
I want to know why each commit doesn't automatically trigger circleCI to check? 
And if this pr can be dealt with in the current version, I would be very grateful.

**Comment by cuihua111** [comment]
Please deal with this PR as soon as possible, thank you @ChrisHuie

**Comment by SylviaF** [comment]
Hi @ChrisHuie ， I'm one of the dev of Discovery's Prebid Adapter. 

We commited a change last week, but it hasn't been merged or received any feedback until this week.
We would like to merge into master as soon as possible， because the publisher won't integrate our adapter before the new version were merged into master and be released.

So would you like to help us to give us some feedback, what do we need to do to make our new change be merge into master and be published in next version?

We need your help so much! Thank you very much for your time!

**Comment by ChrisHuie** [comment]
@SylviaF @cuihua111 I've tried a couple things but looks like I am not able to manually kick off the CircleCI tests and they aren't triggering. I will check this pr out and if I can't get it to trigger I can just test it under my github handle because that is where the CircleCI differs for people.

**Comment by cuihua111** [comment]
@ChrisHuie Thank you so much, but I want to know if there is a better way to solve the problem of circleCI, otherwise I will trouble you every time I commit

**Comment by SylviaF** [comment]
> @SylviaF @cuihua111 I've tried a couple things but looks like I am not able to manually kick off the CircleCI tests and they aren't triggering. I will check this pr out and if I can't get it to trigger I can just test it under my github handle because that is where the CircleCI differs for people.

Hi @ChrisHuie , thanks so much for your effort.

We have recommited a new change and seen that the CircleCI tests is triggerd.
You can jump to the following link to do the remaining work. Thank you!!!
https://github.com/prebid/Prebid.js/pull/9249

**Pull request closed without merging**
