### PR TITLE
Teqblaze Library: Add ORTB2 device data to request payload

### PR DESCRIPTION
**Pull request by jwrosewell**
## Type of change
- [x] Feature
- [x] Updated bidder adapter

## Description of change
This PR enhances bid requests formed within Teqblaze library by incorporating device data from the global ORTB2 object.

The device object has previously been populated by simplistic parsers, if at all, and was inaccurate as a result. Prebid now benefits from RTD modules such as 51Degrees that enrich all the device object fields including Apple iPhone model category and device ID. The PR enables users Teqblaze-dependent bid adapters to benefit from the device object.

Affected bid adapters:
1. [acuityadsBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/acuityadsBidAdapter.js)
2. [admanBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/admanBidAdapter.js)
3. [adprimeBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/adprimeBidAdapter.js)
4. [axisBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/axisBidAdapter.js)
5. [beyondmediaBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/beyondmediaBidAdapter.js)
6. [boldwinBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/boldwinBidAdapter.js)
7. [compassBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/compassBidAdapter.js)
8. [contentexchangeBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/contentexchangeBidAdapter.js)
9. [copper6sspBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/copper6sspBidAdapter.js)
10. [e_volutionBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/e_volutionBidAdapter.js)
11. [emtvBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/emtvBidAdapter.js)
12. [globalsunBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/globalsunBidAdapter.js)
13. [iqzoneBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/iqzoneBidAdapter.js)
14. [kiviadsBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/kiviadsBidAdapter.js)
15. [krushmediaBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/krushmediaBidAdapter.js)
16. [loyalBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/loyalBidAdapter.js)
17. [lunamediahbBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/lunamediahbBidAdapter.js)
18. [mathildeadsBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/mathildeadsBidAdapter.js)
19. [mgidXBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/mgidXBidAdapter.js)
20. [mobfoxpbBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/mobfoxpbBidAdapter.js)
21. [orakiBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/orakiBidAdapter.js)
22. [pgamsspBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/pgamsspBidAdapter.js)
23. [playdigoBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/playdigoBidAdapter.js)
24. [pubCircleBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/pubCircleBidAdapter.js)
25. [qtBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/qtBidAdapter.js)
26. [smarthubBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/smarthubBidAdapter.js)
27. [visiblemeasuresBidAdapter](https://github.com/prebid/Prebid.js/blob/master/modules/visiblemeasuresBidAdapter.js)

## Other information
cc: @MaksymTeqBlaze, @teqblaze, @qt-io

### CODE REVIEW

**Comment by MaksymTeqBlaze** [comment]
Fields such as `deviceWidth`, `deviceHeight`, and `language` are extracted from `bidderRequest.ortb2.device`. It might be better to include the full device object in the request within specific adapters rather than in the library, as doing so for most adapters could simply add extra body size.

**Comment by justadreamer** [comment]
Hi @MaksymTeqBlaze! Thanks for your comment.  

The oRTB `device` object enriched by the [51DegreesRtdProvider](https://docs.prebid.org/dev-docs/modules/51DegreesRtdProvider.html) and potentially other RTD providers would contain standard oRTB fields s.a.: `devicetype`, `make`, `model`, `os`, `osv`, `w`, `h`, `pxratio`, `ppi`, and more.  We think that passing this object in its entirety is beneficial for both the SSPs and publishers.  Given those are standard oRTB fields - they don't add much to the payload - the above listed fields with values would probably add not more than 250 bytes.
 
While it is definitely safer to assume that each adapter should decide for itself whether to pass this data - it is quite tedious to add the same code to each individual adapter, also would result in a lot of code duplication, thus it is much easier to add on the common library level and should benefit every adapter. The major bidder adapters s.a. `openx`, `magnite`, `xandr` and others support passing the device object as is. Thus we'd strongly advocate for passing the whole `device` oRTB object on the common level as is in this PR.  
 
If you still think this is harmful to individual adapters - perhaps we could consider adding a common function on the library level and some light-weight mechanism for the dependent adapters to opt-in this behavior of passing the full `device` object?

**Comment by justadreamer** [comment]
Hi @MaksymTeqBlaze!  What are you thoughts on the above? Thx

**Comment by patmmccann** [comment]
As fyi, both of you are in the prebid slack

**Comment by justadreamer** [comment]
Thanks Patrick, just contacted @MaksymTeqBlaze on Slack.  Maksym, please check my message, thanks.

**Comment by MaksymTeqBlaze** [comment]
Yeah, we can add device to request

**Comment by justadreamer** [comment]
@MaksymTeqBlaze thanks for confirming that this is ok with you guys.  

The test failing is unrelated to this PR.  We thus removed Draft status and set as Ready for review. 

@patmmccann thanks for stimulating the communication on this, what would be the best process to get this PR approved and merged?

**Comment by patmmccann** [comment]
@justadreamer pubrise test failure sure looks related to me

**Review by patmmccann — CHANGES_REQUESTED** [review]
Test failures do appear related to me

**Comment by BohdanVV** [comment]
> Test failures do appear related to me

Hi @patmmccann,

It turns out I missed some errors in the tests because new bidders were switched to Teqblaze, and I wasn't aware of them. Thanks for the heads up!

I've fixed the tests, and the CI/CD is passing. I think it can be merged now. Thanks!

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
