### PR TITLE
Fix bug with supporting non-cpm dealId bids.

### PR DESCRIPTION
**Pull request by mkendall07**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change
Support non-cpm dealId bids. Including support for Xaxis adapter. 

## Other information
@prebid/core for review

### CODE REVIEW

**Comment by daniel-hoffmann** [comment]
@mkendall07 Hey! Looks good to me in regards to the changes in the adapter.

**Comment by mkendall07** [comment]
@snapwich 
want to give this a quick look as I think you refactored some of this code before?

**Comment by snapwich** [comment]
LGTM.  :+1: 

With that change the deal should come through automatically as `hb_deal` if you want to use `alwaysUseBid` or `enableSendAllBids` rather than manually passing in adapter.

**Comment by mkendall07** [comment]
@snapwich thanks. Yeah actually I don't think `hb_deal` comes through because it's considered a default key now, which is omitted on non-winning bids because we don't want to collide with the winning bid.

**Pull request merged**
