### PR TITLE
Adding 152media as alias

### PR DESCRIPTION
**Pull request by ialex**
## Type of change
- [ ] Other

## Description of change
Adding 152media network as an alias to Apnnexus AST 

- contact email of the adapter’s maintainer alejo@152media.com
- [ ] official adapter submission

### CODE REVIEW

**Comment by mkendall07** [comment]
@mjacobsonny for approval

**Comment by ialex** [comment]
i was checking and oftmedia is the same as 152media so no need to merge this, only piece missing is to include oftmedia in the prebid.org/download.html page.

**Comment by mkendall07** [comment]
@ialex 
you can have it included in the download page if you submit a pull request that includes a file like this for oftmedia:
https://raw.githubusercontent.com/prebid/prebid.github.io/master/dev-docs/bidders/pagescience.md

**Comment by ialex** [comment]
Ok i will close this for now and send another PR

**Pull request closed without merging**
