### PR TITLE
Adding an adapter for TripleLift's exchange

### PR DESCRIPTION
**Pull request by mattjone**
@protonate 

Submitting a new PR with the bidder params for the test as well as our adapter.

Here is a live [example](http://matt.triplelift.net/prebid/?tl_tactic_id=328417) in case it is helpful.

### CODE REVIEW

**Comment by mkendall07** [comment]
@mattjone Thanks for contributing. We will review and let you know if we have any questions.

**Comment by mattjone** [comment]
@mkendall07 - have you an opportunity to review our adapter? The conflicts are in the pbjs_example file and I'm happy to resolve them. I just want to mitigate the chance that I resolve them and then the code changes again prior to merging and there are new conflicts. Thanks for reviewing!

**Comment by mkendall07** [comment]
@mattjone No haven't had a chance to review yet. Please go ahead and fix the conflict though that will help in merging it after review.

**Comment by mkendall07** [comment]
@mattjone  - can you please provide test params to validate the bid responses as well?

**Comment by mkendall07** [comment]
bid params
```
{
                    bidder: 'triplelift',
                    params: { 
                        inventoryCode: 'headerbidding_placement' }
                }
```

**Comment by mattjone** [comment]
@mkendall07 - since you have the bid params can I just remove the pbjs example file from the PR to fix the conflict?

**Comment by protonate** [comment]
@mattjone this looks good to merge, please provide a working inventoryCode via email to me and @mkendall07 (address in Github profile) so we can confirm end-to-end functionality for the TripleLift adapter. I've also applied code style updates and hardcoded https for the bid request url, and will append that commit to the PR on merge. 

Thank you for contributing.

**Comment by mattjone** [comment]
@protonate Thanks for reviewing our adapter. I sent you an email with a live inventoryCode for testing purposes. Can you confirm if you received it?

**Pull request merged**
