### PR TITLE
pubGENIUS bid adapter: support video

### PR DESCRIPTION
**Pull request by edmonl**
## Type of change
- [x] Feature

## Description of change
pubGENIUS bid adapter supports video mediaType with this PR.

- test parameters for validating bids
```
{
  bidder: 'pubgenius',
  params: {
    adUnitId: '1001',
    bidFloor: 1,
    test: true,

    // other video parameters as in OpenRTB v2.5 spec
    video: {
      placement: 1,
      w: 640,
      h: 360,
      mimes: ['video/mp4'],
      protocols: [3],
      skip: 1
    }
  }
}
```

- contact email of the adapter’s maintainer: meng@pubgenius.io
- [x] official adapter submission
- A link to a PR on the docs repo: https://github.com/prebid/prebid.github.io/pull/2539

## Other information
@kevinstubbs for team

### CODE REVIEW

**Comment by edmonl** [comment]
Just a note that all tests passed locally.

**Comment by osazos** [comment]
Hi,
Could you use the same `params` object you put in the PR description in your pubgeniusBidAdapter.md file, It matches the expected params regarding your `isValidVideo()` method.

All the rest of the code seems ok.

**Comment by edmonl** [comment]
> Hi,
> Could you use the same `params` object you put in the PR description in your pubgeniusBidAdapter.md file, It matches the expected params regarding your `isValidVideo()` method.
> 
> All the rest of the code seems ok.

Done @osazos

**Review by osazos — APPROVED** [review]
LGTM

**Comment by bretg** [comment]
@edmonl - are you sure you want to specify videoCacheKey? Please see https://github.com/prebid/Prebid.js/issues/6078 -- better to never start using it than try to get rid of it later.

**Comment by edmonl** [comment]
> @edmonl - are you sure you want to specify videoCacheKey? Please see #6078 -- better to never start using it than try to get rid of it later.

@bretg Good point, thank you! You're right. While this PR has merged, we'll keep this in mind and maybe remove videoCacheKey later.

**Comment by bretg** [comment]
Here's the problem -- if you leave videoCacheKey in, then publishers have to set up a separate creative in the ad server for you.

Once the first one does that, you're screwed -- you can't remove videoCacheKey until you check with every pub that they're ready for it.

I highly recommend you remove videoCacheKey right now before you're live. But if you insist, I'll add you to the list of bidders in #6078 .

**Comment by edmonl** [comment]
I'll remove it in another PR. Does that work?

**Comment by bretg** [comment]
Yup, that would be fine. This one's already been merged.

**Pull request merged**
