### PR TITLE
Update consentManagementUsp.js to not store and reuse null consent

### PR DESCRIPTION
**Pull request by patmmccann**
Fixes bug described at https://github.com/prebid/Prebid.js/issues/5440 to comply with intent of #4425
## Type of change

- [X] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
No longer checks to see if consentData are stored; should recheck _uspapi

### CODE REVIEW

**Comment by patmmccann** [comment]
of note, build failed because of bad merge https://github.com/prebid/Prebid.js/commit/d8e5796827a46455185292e4a498628ecdb09bc6

**Comment by jsnellbaker** [comment]
On an additional note - I retested the browserstack tests locally and they passed fine.  I'm not sure why circleci tests are failing.  It seems like it's trying to use a previous commit where a `flatMap` was added for the amxBidAdapter, but the config/stats for the job appear to be pointing to the most recent commit (where the `flatMap` was removed).  I think we can just ignore it unless someone has another idea.

**Comment by patmmccann** [comment]
Thanks so much for all the education on yesterday's call. You're right, the
circleci fail is from a reverted amx adapter commit.

**Comment by bretg** [comment]
@harpere is out right now -- assigning over to @mkendall07

**Comment by mkendall07** [comment]
This change looks good if it's the behavior we want. The only slight caveat here is this part
>the USP (CCPA) api function __uspapi() always responds synchronously, whether or not privacy data is available, while the GDPR CMP may respond asynchronously, especially if waiting for a user response. **Unfortunately this doesn't necessarily mean it's always a synchronous transaction because if there are nested cross-domain iframes we may need to do an async postMessage().**
Note the bolded part, it's possible this puts an async delay into every auction request. As long as we are ok living with that it's a LGTM.

**Comment by mkendall07** [comment]
@bretg @patmmccann for weigh in ^^

**Comment by patmmccann** [comment]
I don't think we have a choice, usp is opt out and if someone opts out at
any point, refreshes and subsequent auctions need to know. If I were a
regulator and wanted to test for compliance, I would go to a page, opt out,
and look at the subsequent calls.

**Comment by mkendall07** [comment]
makes sense. It looks like circleci is continuously failing. Is this branch up to date with master?

**Comment by patmmccann** [comment]
there was a bad merge to master of the amx adapter that was later fixed

**Comment by patmmccann** [comment]
@mkendall07 it is up to date with master now

**Comment by bretg** [comment]
Re-ran the build and it passed. Since this is a bug, I'll assume that we're not going to need documentation. Will merge and add it to the rel notes.

**Pull request merged**
