### PR TITLE
PBjs Core: added `maxNestedIframes` option

### PR DESCRIPTION
**Pull request by fasenderos**
## Type of change
- [X] Bugfix
- [X] Feature

## Description of change
Added `maxNestedIframes` option to avoid endless loop on referer detection #6483.

### CODE REVIEW

**Comment by fasenderos** [comment]
I'm not sure about the default value of `maxNestedIframes`. I initially set it at `2` because in my case fix the issue #6483 and let Prebid works under AMP without AMP RTC, but it breaks some tests of `refererDetection_spec.js`.

`3` was enough to not break tests, but since I don't want to introduce braking changes I have chosen, as @bretg [suggested here](https://github.com/prebid/Prebid.js/issues/6483#issuecomment-821992823), a larger number, `10`.

Now I'm thinking that it's better to choose as trade off a number that is large enough to not break client applications and also multiple of 3 less 1 (e.g. 5 - 8 - 11 - 14 etc.) to fix Prebid under AMP.

If you have any hints I can change the default value accordingly.
Thanks.

**Comment by patmmccann** [comment]
This pr is fascinating because we were unaware prebid js could work in amp with such a minor change. All doc points to implementing a call to prebid server in amp.

Can you point us to a page where you've gotten pbjs working on amp?

**Comment by fasenderos** [comment]
I'm always talking about _"my case"_ because we have a custom implementation of Prebid (see after), so I don't want to raising false expectations :). Maybe it's just a pure fix of my specific case.

I'm working for an Advertising Platform and all of our publisher install our `widget` on their page and we delivery ONLY `native` creatives. At first the widget call our server to check if programmatic is enabled. If so, the `prebid.js` is loaded on page and the `adUnits` object is appended to the `head` with our custom adapter (`nativeryBidAdapter.js`) and `appnexus`. We don't have an Ad Server, and for this reason I have created a Prebid module ( `nativeryWrapper.js` ) that has an event listner on `AUCTION_END`, and here I'm using `getHighestCpmBids` on each ad unit code and fire the impression tracker with `postMessage`. Since our widget support only native creatives, once I get the list of the winning ads, I have to format the template for the widget output.

[Here](https://www.salernonotizie.it/2021/04/19/imprese-balneari-campane-pronte-a-riaprire-lottimismo-della-fiba/amp/) is a live example.

**Review by Rothalack — APPROVED** [review]
This looks good

**Pull request merged**
