### PR TITLE
Bridgeupp Bidder Adapter : initial release

### PR DESCRIPTION
**Pull request by sharon-bridgeupp**
## Type of change
- [ ] Bugfix
- [ ] Feature
- [X] New bidder adapter
- [ ] Updated bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
- contact email of the adapter’s maintainer : support@bridgeupp.com
- test parameters for validating bids:

```
{
    bidder: 'sonarads',
    params: {
        siteId: 'site-id-test',
        bidfloor: 0.01
}
```

## Other information
Related prebid docs PR: https://github.com/prebid/prebid.github.io/pull/5755

### CODE REVIEW

**Comment by sharon-bridgeupp** [comment]
@ChrisHuie - Hello , not sure how to request for a reviewer, can you help with a review here?

**Comment by sharon-bridgeupp** [comment]
Thanks @ChrisHuie for your attention here

Can you also help us anticipate when the review will happen?
Its important for us as the approval of the adapter is the only thing that is missing at the moment for us to start a prebid integration with a few clients
If there is anything that is missing or needed from our side please let us know

Thanks again for your help with the review here

**Review by ChrisHuie — APPROVED** [review]

**Comment by sharon-bridgeupp** [comment]
HI @ChrisHuie 
Thanks for merging the PR 
one question though - we dont see our name on the main page :https://deploy-preview-5743--prebid-docs-preview.netlify.app/download

can you please assist with understanding why its not included there yet ?

**Comment by sharon-bridgeupp** [comment]
I see it now , thank you

**Pull request merged**
