### PR TITLE
added an optional auctionId parameter to requestBids

### PR DESCRIPTION
**Pull request by PascalSalesch**
## Type of change
- Feature

## Description of change

Added an optional parameter `auctionId` to the requestBids api.
This makes it easier for us to track cross prebid auctions (i.e.: auctions where prebid adapters compete with other header bidding partners).

## ToDo: Docu update

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide a link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by PascalSalesch** [comment]
ah shit I think I messed up the rebasing

**Comment by mkendall07** [comment]
@bretg changed me mind ;) well he just pointed out that it could be somewhat common to use another wrapper in tandem with Prebid.js (think if you are using Amazon for example or another one that isn't supported by prebid.js).

**Comment by bretg** [comment]
Minimal docs PR -- https://github.com/prebid/prebid.github.io/pull/1225

I don't think this use case is prevalent enough at this point to warrant a full example. But anyone who disagrees is free to submit a more substantial docs update.

**Comment by jsnellbaker** [comment]
@PascalSalesch Can you please resolve the conflicts?

**Pull request merged**
