### PR TITLE
Mediakeys bid adapter: native and video support

### PR DESCRIPTION
**Pull request by mediakeys-platform**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Add support for Native and Video mediatypes in mediakeys adapter

- contact email of the adapter’s maintainer: prebidjs@mediakeys.com

### CODE REVIEW

**Comment by mediakeys-platform** [comment]
Dear reviewers, we created a test campaigns which should bid with your test page configured with:
```
pbjs.que.push(function() {
    pbjs.setConfig({
        consentManagement: {
            gdpr: {
                cmpApi: 'static',
                consentData: {
                    getTCData: {
                        tcString: 'any_valid_tcfv2_consent_string',
                        gdprApplies: true
                    }
                }
            }
        },
        ortb2: {
            device: {geo: {country: "FRA", lat: 43.611, lon: 3.876}}
        }
    });
});
```
A valid TCFv2 consent string is needed in order to receive a bid, you can use this one that is accepting all vendors:

```
CPKre1EPKre1EAHABBENBmCsAP_AAH_AAAAAGstD_TrMYyNj-XZ9Nrs0aYxOxMSXo-wCjAaJAWgBAQKAIJQGwmAQpAHgBCACIAAEIiJBAQIlDCHACQAA4IABASAAIAiABBIIICIAgEAQAwAICBBCCcAAAQKYgAAEEAUAmwoAAAoiQAAAIAAABgayACYKkxAA2JYYEk0KRQogBhEABUAoAKIAIEAaAABAAAghAIQQAAAAIAAAAAAAAAiAgEAAgEAAEAAAAHggAABAAAAAAAAAAgAIgAAQAAAAAAAAAIBgAAAAIAAAAQABQCBAAAAAAJAAAAAAAAGAAAAA.f_gAD_gAAAAA
```
Please let us know if you need more information on setting up the adapter.

**Review by FilipStamenkovic — APPROVED** [review]
LGTM.  

I just couldn't find docs PR.

**Comment by mediakeys-platform** [comment]
@FilipStamenkovic ok we'll add the docs!

Before merging, we have something to discuss about `insteam` videos.
We found that the `onBidWon` event is emitted only with specific `prebid` setup:

1. Enable [instreamTracking](https://docs.prebid.org/dev-docs/modules/instreamTracking.html) module and set the configuration to:
```
pbjs.setConfig({
    instreamTracking: {
        enabled: true,
        urlPattern: /vasts\.bidder\.mediakeys\.io.*/
    }
}
```
2. Disable `vast` cache in our [bid adapter video properties](https://github.com/prebid/Prebid.js/pull/7452/commits/541349571a3f4e6768ae2d0a5e26c51a964bd1bd#diff-ae08818d5c1fba944285c7e804ad8be1506c2d93fa2974d3328e66ad751fb436R732) with any string which can be found on `vastUrl` :
```
if (mediaType === VIDEO) {
  // For videos, disable server cache as vast is generated per bid request with specific tracking events
  newBid.videoCacheKey = 'no_cache';

  // The vast URL is server independently and must be fetched before video rendering in the renderer
  newBid.vastUrl = bid.ext.vast_url + '&no_cache';
}
```
3. Avoid marking the bid as used in buildVideoUrl 
```
pbjs.requestBids({
    timeout: 1000,
    bidsBackHandler: function (bids) {
        var highestCpmBids = pbjs.getHighestCpmBids('video1');

        if (highestCpmBids.length > 0) {
            // !!!!!!!! AVOID THIS OR THE BID WON EVENT WON'T BE EMITTED SOMETIMES !!!!!!!!
            // Mark the bid, used in buildVideoUrl, as used
            // pbjs.markWinningBidAsUsed({
            //     adUnitCode: adUnits[0].code
            // });

            invokeVideoPlayer(highestCpmBids[0].vastUrl);
        }
    }
});
```
Related prebid code can be found here: https://github.com/prebid/Prebid.js/blob/804295aa2dae0484d67891b73fcfc401ef8244f1/modules/instreamTracking.js#L44

We carefully read the docs, but we're not sure that we use prebid features correctly for the use case.
Please could you take some time to review this and if this is ok for you, we'll add a commit to the PR to fix the `onBidWon` event.

**Comment by ChrisHuie** [comment]
There was a conflict here because we have been going through all adapters to import only the functions used from utils instead of in a lot of cases importing the full util file

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/3298

**Review by FilipStamenkovic — APPROVED** [review]

**Pull request merged**
