### PR TITLE
Fix clear targeting

### PR DESCRIPTION
**Pull request by mkendall07**
@matthewlane & @protonate to review

### CODE REVIEW

**Comment by protonate** [comment]
Looks good, thanks for the fix, reviewed.

**Comment by nanek** [comment]
`slot.clearTargeting();` is still being called, just at a different time. Due to the async nature of these calls how do you guarantee that targeting set by others is not lost? 

Can you clarify the reason clearTargeting is required? Any reason not to only clear prebid specific keys?

**Comment by mkendall07** [comment]
@nanek 
The current implementation reads the current keys, stores them, clears the slot, and reapply the keys. This works because JS is single threaded and we are guarantee atomicity within our function. 

The reason we don't clear a single key? [Google's API doesn't support it. ](https://developers.google.com/doubleclick-gpt/reference#googletag.Slot_clearTargeting)

**Comment by aurelienjoneau** [comment]
Hi @mkendall07  
This new feature seems to break the targeting setting we use on our websites : when reapplying the keys, each value is reapplied to each ad slot. With version 0.10, every ad slot now has the targetting values of the last ad slot declared, after a lot of overwrite. 
This will become a major problem for us with future versions of prebid, as we can't change our targetting implantation system.
- is it possible to have a config option to keep the previous clearing system? something like pbjs.useLegacyClearTargetting ? Or do you see a fix for that problem ? thanks in advance

**Comment by dahjah** [comment]
I'm experiencing the same issue as aurelienjoneau. The targeting specific to the last tag in the array is applied to every tag. Perhaps there's an array traversing issue somewhere?

**Comment by mkendall07** [comment]
@dahjah 
This is resolved in 0.11.0

**Pull request merged**
