### PR TITLE
Single Adform adapter

### PR DESCRIPTION
**Pull request by braizhas**
## Type of change
- [x] Other

## Description of change
Removed legacy Adform adapter, since prebid 5.0 only adf adapter should be used to fetch Adform demand.

- contact email of the adapter’s maintainer Scope.FL.Scripts@adform.com
- [x] official adapter submission

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
- https://github.com/prebid/prebid.github.io/pull/2991

## Other information
Fixes https://github.com/prebid/Prebid.js/issues/6650

### CODE REVIEW

**Review by FilipStamenkovic — COMMENTED** [review]
I think this PR should only remove adform bid adapter? You shouldn't be adding changes to the `adfBidAdapter` since those changes are already merged in #6726.

**Comment by braizhas** [comment]
Should I revert commit https://github.com/prebid/Prebid.js/pull/6840/commits/0ada455bc8432b1da3359d1b6a5c5f1190cae27e ? Changes would be applied by some later merge from master?

**Comment by FilipStamenkovic** [comment]
Yes, as I see you only need 1st commit, which removes `adform` bidder and adds alias in `adfBidAdapter`, all your other changes are already on `master` branch.

**Review by FilipStamenkovic — APPROVED** [review]
LGTM

**Comment by patmmccann** [comment]
did your fix for #6650 geet removed from this pr?

**Comment by braizhas** [comment]
as @FilipStamenkovic noticed - it's ok to have it only in master branch. Later changes will be merged.

**Comment by patmmccann** [comment]
confirming i see it on master, ty

**Pull request merged**
