### PR TITLE
AdUp Technology bid adapter: add support for floor prices

### PR DESCRIPTION
**Pull request by MichaelErmer**
## Type of change

- [x] Feature

## Description of change
* added support for prebid floor module

- test parameters for validating bids
```
var adUnits = [
   {
        code: "example1",
        mediaTypes: {
            banner: {
                sizes: [[300, 250], [300, 600]],
            }
        },
        bids: [{
            bidder: "aduptech",
            params: {
                publisher: "prebid",
                placement: "12345"
            }
        }]
   }
];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo: https://github.com/prebid/prebid.github.io/pull/3816

### CODE REVIEW

**Comment by MichaelErmer** [comment]
How can I rerun the tests which failed at some other adapter?

**Comment by muuki88** [comment]
Related PR: https://github.com/prebid/prebid.github.io/pull/3816

**Review by musikele — APPROVED** [review]
LGTM

**Comment by dgirardi** [comment]
https://github.com/prebid/Prebid.js/pull/8548 fixes a test failure brought about by merging this with prebid 7.

**Pull request merged**
