### PR TITLE
Pubgears Bid Adapter : initial release

### PR DESCRIPTION
**Pull request by pubgears-com**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Comment by muuki88** [comment]
Docs: https://github.com/prebid/prebid.github.io/pull/4639

**Review by Fawke — CHANGES_REQUESTED** [review]
Hi @pubgears-com,

Please improve your unit test coverage to make it at least 80%. Currently, it's around 57%. Also, when I tried getting a test bid back using the example params you shared in your md file, am getting this error:

Screenshot 2023-07-06 at 2 54 21 PM

**Comment by pubgears-com** [comment]
> Hi @pubgears-com,
> 
> Please improve your unit test coverage to make it at least 80%. Currently, it's around 57%. Also, when I tried getting a test bid back using the example params you shared in your md file, am getting this error:
> 
> Screenshot 2023-07-06 at 2 54 21 PM

server will be live next week

**Comment by Fawke** [comment]
@pubgears-com Is your server live? I still see the same error.

**Comment by pubgears-com** [comment]
@Fawke  It's not yet, Sorry for the late answer, we'll reach out to you when it is live.

**Comment by ChrisHuie** [comment]
Please feel free to reopen.

**Pull request closed without merging**
