### PR TITLE
DSPx Bid Adapter: add ortb2 content, topics support

### PR DESCRIPTION
**Pull request by onlsol**
DSPx Bid Adapter: add ortb2 content, topics support

## Type of change
- [x] Feature

## Description of change
Improved the adapters support for ortb content, userids, topics.

### CODE REVIEW

**Comment by patmmccann** [comment]
Hi! it appears DSPx and STV are very closely mirrored. Please see #11879 and #8527 and #11854 and #11877 for examples on fixing. Thanks!

**Comment by onlsol** [comment]
@patmmccann Hi, that's right, the `stvBidAdapter` has several similarities in requirements, code constructs, conditions and code comments as `dspxBidAdapter`. 
As far as I see, none of them is related to the current PR's changes or commits.
Would it be possible to proceed with this PR as it is (type of change "feature")? If you agree, subsequently, in a separate PR, we could work on the maintenance/refactoring and move re-usable parts to `bidderUtils`.

**Comment by patmmccann** [comment]
Yes but please make sure that is your next pr; we are in the midst of an initiative to identify and consolidate duplicated code :)

**Review by patmmccann — APPROVED** [review]

**Comment by onlsol** [comment]
Understood, thanks for clarification.

**Pull request merged**
