### PR TITLE
Pubmatic Bid Adapter: Removed logic to append JW player data to the "dctr" param

### PR DESCRIPTION
**Pull request by jlquaccia**
## Type of change
- [x] Bugfix

## Description of change
Removed functionality to copy the JW player data to the dctr param in the pubmaticBidAdapter when using PBS

## Other information

Related Issue: https://github.com/prebid/Prebid.js/issues/9142
@dgirardi @patmmccann could you review?

### CODE REVIEW

**Comment by jlquaccia** [comment]
@dgirardi @patmmccann also note that I am still waiting to here back from some of the PubMatic team who work on the server-side to confirm if there is any server-side impact on this change.  So for the time being until then, we can hold off on merging.

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
Cc @bretg

**Comment by patmmccann** [comment]
@jlquaccia any update?

**Comment by jlquaccia** [comment]
@patmmccann sounds like there is a server-side impact to this on our end, which I'm trying to follow up with with a few people over here.  I'll keep you in the loop once I've got another update.

**Pull request merged**
