### PR TITLE
Eplanning: new optional parameter is added

### PR DESCRIPTION
**Pull request by chino117**
## Type of change
- [X] Build related changes

## Description of change

New optional parameter is added

- contact email of the adapter’s maintainer
chino117@hotmail.com

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/eplanning.md

### CODE REVIEW

**Comment by chino117** [comment]
BrowserStack testing failure is not related to my changes, how do I run the tests again?

**Comment by Rothalack** [comment]
I've been unable to get the tests to pass today either. It looks like everyone is having this issue. After 8 attempts, it's been inconsistent timeouts at various points. Will let you know when I know more. I may just need to keep running it until it passes without timeout.

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/2573

**Comment by Rothalack** [comment]
Sorry for the delay, just got through a move.

I see there's the new pull request #6139 that looks to have these changes plus another set of new changes. Could we close this PR and just use that?

**Comment by chino117** [comment]
Ok

**Pull request closed without merging**
