### PR TITLE
Sharethrough Bid Adapter: Add First Party Data and Outstream Support

### PR DESCRIPTION
**Pull request by maphe**
## Type of change
- [x] Feature

## Description of change
- Pass First Party Data through the adapter to the ad server
- Stop ignoring `outstream` video requests

pubgrowth.engineering@sharethrough.com

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@maphe can you pull in recent commits into your branch for this pr. Seems to be a bit behind the current version of master

**Comment by maphe** [comment]
@ChrisHuie, absolutely. Just did.

**Comment by maphe** [comment]
Hi @ChrisHuie, any update on this PR? it's been hanging for a little bit now. Thanks

**Comment by ChrisHuie** [comment]
@maphe there still seem to be errors related to the Smaato adapter?

**Comment by maphe** [comment]
@ChrisHuie that's weird, there's nothing related to Smaato in my changes, I'm gonna look into it but if you have any idea on what could cause that please let me know...

**Comment by maphe** [comment]
Ok I think I found it, apparently the override for the `config.ortb2` was carrying over to other specs and conflicting with what Smaato is doing with it. I'm not sure if something could be done at the prebid core to reset the `ortb2` object between adapter specs. Regardless, let's see if my fix makes the CI pass 🤞

**Review by msm0504 — APPROVED** [review]

**Pull request merged**
