### PR TITLE
PulsePoint Adapter.

### PR DESCRIPTION
**Pull request by anand-venkatraman**
Added adapter for PulsePoint (http://www.pulsepoint.com/).

### CODE REVIEW

**Comment by anand-venkatraman** [comment]
Please review and let us know.

Thanks,
Anand

**Comment by mkendall07** [comment]
@anand-venkatraman 

Thank you very much for submitting an adapter for review. Would you mind including a usage example with your adapter included? You can add to this file: https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html#L102

Also please let us know if this is an official adapter from Pulsepoint? thanks!

**Comment by anand-venkatraman** [comment]
@mkendall07 
Thank you for your review. I have added the usage example, and verified.
And yes, this is the official adapter from Pulsepoint.

Thanks,
Anand

**Comment by mkendall07** [comment]
Thanks for the quick update. It looks like the callback is not invoked unless there is an eligible bid. Is it possible to also return a `no_bid` condition? This would indicate that we are not waiting any longer for bids.

**Comment by anand-venkatraman** [comment]
@mkendall07 , I have addressed your comment. 

Thanks,
Anand

**Comment by mkendall07** [comment]
Thank you for the update @anand-venkatraman . The last thing I need to certify is the see valid bid responses being added. Please let me know the setup required to get valid bids (test bids are fine too). You can email me directly emailmatthere+pbjs (@) gmail (dot) com if you wish

**Comment by anand-venkatraman** [comment]
Thank you @mkendall07. I have emailed you the link to our test page, and the configuration information.

**Comment by mkendall07** [comment]
Thanks for the contribution @anand-venkatraman  and PulsePoint team. I've pulled into master.

**Pull request merged**
