### PR TITLE
Adding back ZEDO adapter with changes to make it compatible to latest prebid

### PR DESCRIPTION
**Pull request by skazedo**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by skazedo** [comment]
Hi @bmwcmw, just checking if you found any issues with this commit. thanks.

**Comment by skazedo** [comment]
Hi @bmwcmw, Removed the lock file and also synced with master. Thanks

**Comment by bmwcmw** [comment]
Hi @skazedo few things:
- Thanks for the last sync, it was not clear but I meant to just rollback the modification on package-lock.js and keep the file untouched by this PR :) 
- When I test with the adUnit examples in your zedoBidAdapter.md, for banner I think it lacks mediaTypes field, but for both banner and video the interpretResponse function is always getting an empty response. Please check and update them to make tests pass, or tell me if I'm missing something.

**Comment by skazedo** [comment]
@bmwcmw . thanks for reviewing. Sorry about the sync, its just a habit of updating with remote :). I have updated the md file with a new setup so you should see a response now with new values. thanks

**Comment by bmwcmw** [comment]
Hi @skazedo,

The package-lock.json is still in the change list, and causing the conflicts now:
Capture
You should rollback it to make it disappear from this change list.

Btw when I run tests using the updated example adunits, I still get empty responses, not sure if I'm getting anything wrong. Otherwise, the changes in your adapter look good.

**Comment by skazedo** [comment]
hi @bmwcmw , i had to merge with upstream to fix the issue. also i modified hello_world.html to verify the response and i could see the returned response. let me know if you want me to share it here. thanks.

**Comment by bmwcmw** [comment]
@skazedo Great, thanks for the fix! Could you please share your test config here? I'm still getting the empty response body so directly an error in the first check of interpretResponse.

Capture

**Comment by skazedo** [comment]
i tried with this config
var adUnits = [{
             code: 'div-gpt-ad-1460505748561-0',
             mediaTypes: {
                 banner: {
                     sizes: [[300, 250], [300,600]],
                 }
             },
             // Replace this object to test a new Adapter!
             bids: [{
                 bidder: 'zedo',
                 params: {
                     channelCode: 2264004735,
                     dimId:9
                 }
             }]

         }];

**Comment by skazedo** [comment]
Here's the console logs i see.
image

**Comment by skazedo** [comment]
here's the console log i see 
image

**Comment by bmwcmw** [comment]
@skazedo Strange thing, I'm doing same from localhost but always get empty body. Maybe you're doing some filtering on your server side? But when I check with a mocked response it seems good, overall is also ok, so I'll approve here.
Perhaps you'd like to check why the response can be empty.

**Comment by skazedo** [comment]
hi @bmwcmw ,thanks for the merge. We do not do any filtering at the server. Could you let me know the response you see on the fmh.json. Also your console logs look different. is there a different query param besides pbjs_debug?

**Comment by bmwcmw** [comment]
@skazedo for example when I simply replace the adunit in gpt/hello_world.html by the banner adunit in zedoBidAdapter.md, the request sent to fmh.json:
Capture

> https://saxp.zedo.com/asw/fmh.json?g={%22placements%22:[{%22id%22:%2226f2058689e9d6%22,%22network%22:2264,%22channel%22:4735,%22publisher%22:0,%22width%22:300,%22height%22:250,%22dimension%22:9,%22version%22:%223.23.0-pre%22,%22keyword%22:%22%22,%22transactionId%22:%222ae72742-f8cb-40f5-ba8e-0d790e7b01a1%22,%22renderers%22:[{%22name%22:%22display%22}]}]}

in the console view with pbjs_debug, it shows `ERROR: in response for undefined adapter` just after `MESSAGE: Emitting event for: bidRequested`

**Comment by skazedo** [comment]
in the hello_world page, could you try removing all reference to googletag. I think that may cause some conflict since we do not have a setup there.

**Comment by bmwcmw** [comment]
Hey @skazedo, here my html page after removing all gpt references, it there anything wrong or missing? Thanks.

```
<html>
<head>
    <script async src="../../build/dist/prebid.js"></script>
    <script>
        var FAILSAFE_TIMEOUT = 3300;
        var PREBID_TIMEOUT = 1000;

        var adUnits = [{
          code: 'div-gpt-ad-1460505748561-0',
          mediaTypes: {
            banner: {
              sizes: [[300, 250], [300,600]],
            }
          },
          // Replace this object to test a new Adapter!
          bids: [{
            bidder: 'zedo',
            params: {
              channelCode: 2264004735, //REQUIRED
              dimId:9 //REQUIRED
            }
          }]

        }];

        var pbjs = pbjs || {};
        pbjs.que = pbjs.que || [];

    </script>

    <script>

        pbjs.que.push(function() {
            pbjs.addAdUnits(adUnits);
            pbjs.requestBids({
                bidsBackHandler: sendAdserverRequest,
                timeout: PREBID_TIMEOUT
            });
        });

        function sendAdserverRequest() {
            if (pbjs.adserverRequestSent) return;
            pbjs.adserverRequestSent = true;
        }

        setTimeout(function() {
            sendAdserverRequest();
        }, FAILSAFE_TIMEOUT);

    </script>
</head>

<body>
<h2>Prebid.js Test</h2>
<h5>Div-1</h5>
<div id='div-gpt-ad-1460505748561-0'>
</div>
</body>
</html>
```

**Comment by skazedo** [comment]
i tried the exact same test except changed the build path to ../../build/dev/prebid.js and i was able to see bid response. And i ran it against latest head version of the branch after merge from master.
image

**Pull request merged**
