### PR TITLE
Insticator Bid adapter: Add video placement param

### PR DESCRIPTION
**Pull request by StalmIlya**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added placement param to video objects

- contact email: ilya_stalmahov@lineate.com
- [x] official adapter submission

- A link to a PR on the docs repo: #https://github.com/prebid/prebid.github.io/pull/3864

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@StalmIlya can you give me edit access to this pr. Looks like our integration CircleCI tests didn't kick off but I can kick off on my end.

**Comment by ChrisHuie** [comment]
@StalmIlya can you give me edit access to this pr. Looks like our integration CircleCI tests didn't kick off but I can kick off on my end.

**Comment by StalmIlya** [comment]
@ChrisHuie unfortunately i can't see an "Allow edits from maintainers" checkbox. Is there another way to solve this issue?

**Comment by StalmIlya** [comment]
@ChrisHuie could you please check my PR? CircleCI ran with no issues :)

**Pull request merged**
