### PR TITLE
Revert "Add AMX RTB adapter"

### PR DESCRIPTION
**Pull request by patmmccann**
Reverts prebid/Prebid.js#5383

The PR uses flatmap and causes all circleci builds to fail on edge 17/edge18 and ie 11.

### CODE REVIEW

**Comment by GLStephen** [comment]
Circle CI runs on PRs, correct? CCI was all green on the PR. @patmmccann

**Comment by patmmccann** [comment]
Can you merge this @GLStephen or should someone else?

**Comment by GLStephen** [comment]
@patmmccann merged

**Comment by nickjacob** [comment]
Thanks—sorry about this! Tested with browserstack & fixed a few ie11 issues. New PR is here: https://github.com/prebid/Prebid.js/pull/5464

**Pull request merged**
