### PR TITLE
Core & multiple modules: introduce new `bidRejected` event, and refactor bid rejection logic

### PR DESCRIPTION
**Pull request by dgirardi**
## Type of change

- [x] Bugfix
- [x] Feature

## Description of change

This: 
 - introduces a new `bidRejected` event, emitted when an adapter returns a bid response that core decides should not be used
 - normalizes the "NO_BID" rejections done by priceFloors and currency. Unlike the proposal in https://github.com/prebid/Prebid.js/issues/8956, I decided to _not_ generate these bids outside of those cases, because they don't always work well through the usual bid response flow (for example, sometimes we do not know which bidder it came from, or which adUnit it refers to). 
 - the above means that apart from the new 'bidRejected' event, the current behavior is left unchanged, except that:
 - banner bid responses whose size does not match any of the sizes in the request are now rejected (see https://github.com/prebid/Prebid.js/issues/8887)
 - targeting logic now does not check for bid size, but does exclude NO_BID bids

## Other information

Closes https://github.com/prebid/Prebid.js/issues/8956
Closes https://github.com/prebid/Prebid.js/issues/8887

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@Fawke @ncolletti I know you guys have a few other pr reviews. Do either of you need me to reassign this one?

**Review by Fawke — APPROVED** [review]
Looks good at a first glance. I was able to simulate an invalid bid and could see the `bidRejected` event fire.

I agree with the removal of the banner size check from targeting, and moving it as a separate check in Bidder Factory.

Rest, all looks good. I think making a note of this new event in the somewhere in the docs will be helpful for the Analytics adapters and other third party listeners.

**Comment by lgadzhev-devrix** [comment]
I'm getting this error after this update

`Exception in queued GPT command TypeError: e.getStatusCode is not a function`

**Comment by dgirardi** [comment]
@lgadzhev-devrix is it similar to https://github.com/prebid/Prebid.js/issues/9245? the author there concluded that the culprit was a browser extension. If your case is different could you open an issue and provide steps to reproduce?

**Comment by lgadzhev-devrix** [comment]
Yep, it was caused by the AdWizzard on my end. Thank you! I'm not sure why
I couldn't find this issue while googling the error

*--*


*Lachezar Gadzhev*Backend Developer
*DevriX Ltd.*

**Pull request merged**
