### PR TITLE
integr8 Bid Adapter: add new bid adapter

### PR DESCRIPTION
**Pull request by ardit-baloku**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added new adapter for integr8 adplatform

- test parameters for validating bids
```
{
    bidder: 'integr8',
    params: {
        propertyId: '105109', //Required
        placementId: '846835', //Required
        data: { //Optional
            catalogs: [{
                catalogId: "699229",
                items: ["193", "4", "1"]
            }],
            inventory: {
                category: ["tech"],
                query: ["iphone 12"]
            }
        }
    }
}
```

- contact email of the adapter’s maintainer: arditb@gjirafa.com
- [x] official adapter submission
- docs PR:  https://github.com/prebid/prebid.github.io/pull/3000

### CODE REVIEW

**Review by osazos — COMMENTED** [review]
Hi @ardit-baloku,

You set once your adRequest params, so if there are several adUnits using your bidder with different params, only the first value found will be set. Could you confirm it is the expected behavior?

You need to support the FloorPrices module. It is required with Prebid.js 5.x.

Regarding the video: 

- you must read and pass to your server the optional video params defined by the publisher at the adUnit level (#6512)
- you must provide a renderer for outsream context.

See https://docs.prebid.org/dev-docs/bidder-adaptor.html#supporting-video for more information.

**Comment by osazos** [comment]
Hey there, any news @ardit-baloku ?

**Comment by ardit-baloku** [comment]
Hi @osazos, sorry for the late response, I was on vacation. I have resolved the comments you left on this PR.

Regarding your question if the expected behaviour was to use the first found value, the answer is yes we intended that.

I have also added support for the FloorPrices module as you requested.

Regarding video, we only used "skipTime" as a parameter for video ads and we are now fetching that from bidRequest.mediaTypes.video.skipafter, but I have left bidRequest.params.skipTime as a fallback to keep it backwards compatible. Do we need to provide a renderer outstream context? We do not plan on supporting this any time soon and would like to skip this part if possible

**Comment by osazos** [comment]
Hi, sorry the delay.
Add a test about Floor Price would be nice, after that, all seems ok

**Review by osazos — APPROVED** [review]
LGTM

@ChrisHuie, do you want to review it or you just self-added yourself by mistake?

**Comment by ChrisHuie** [comment]
@osazos Added myself just so it wasn't sitting assigned to you while it wasn't moving :) Looks good to me!

**Pull request merged**
