### PR TITLE
Playground XYZ adapter - iframe usersync bug fix

### PR DESCRIPTION
**Pull request by monofonik**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- Fixes a bug where "image" type user sync pixels are not being dropped when the publisher allows iframe usersync.
- Removes a redundant iframe sync pixel URL from the Playground XYZ adapter code.

### CODE REVIEW

**Comment by monofonik** [comment]
Thanks @bretg PR updated. Noticed the CircleCI build is failing - but doesn't appear to be an issue with my changes?

**Comment by bretg** [comment]
Thanks - looks good. CircleCI has been kinda flaky lately. Re-running.

**Comment by bretg** [comment]
@monofonik - please resync this PR with master. I'm told that may eliminate the circleci problem. I've re-run this several times to no avail.

**Comment by monofonik** [comment]
Thanks @bretg updated looks good now

**Comment by bretg** [comment]
Merged. While I have your attention here, would like to pick up or close out https://github.com/prebid/prebid.github.io/pull/1203

**Comment by monofonik** [comment]
Thanks @bretg I'll reply on the other PR

**Pull request merged**
