### PR TITLE
Code Quality and Style Standards

### PR DESCRIPTION
**Pull request by protonate**
Define jscs and jshint settings to report on code quality and style standards. Updates code files to standards.

In some cases adapters were also updated, while some jshint options are set to be ignored.
This is not set to enforce quality at commit or build time ... yet. We ~~will~~ _may_ want to set that in place soon.

Also, add support for babel and es6 syntax. See the file `test/helpers/pbjs-test-only.js` for an example of an ES6 module. This file is imported using ES6 syntax in the `test/spec/aliasBidder_spec.js` file and required the ES5 way in `test/spec/adUnits_spec.js`.

### CODE REVIEW

**Comment by mkendall07** [comment]
Thanks @protonate !
Do we have any benchmarks on compiled prebid.js before / after babel ?

**Comment by protonate** [comment]
Here's preliminary file sizes without much ES6 syntax in place.

| Branch | dev | dist |
| --- | --- | --- |
| current master | 136 kb | 48 kb |
| babel inline runtime  | 119 kb | 53 kb |
| babel require runtime  | 135 kb | 59 kb |

**Comment by ehoch** [comment]
@mkendall07 @protonate  I'm not a NPM / Node guy, so pardon if I'm an idiot here, but since this PR whenver I gulp build, I'm getting

```
/Prebid.js/node_modules/gulp-jscs/node_modules/jscs/node_modules/babel-jscs/acorn-to-esprima.js:2
var tt       = require("babel-core").acorn.tokTypes;
                                          ^
TypeError: Cannot read property 'tokTypes' of undefined
    at Object.<anonymous> (/Users/ehochber/ruby/Prebid.js/node_modules/gulp-jscs/node_modules/jscs/node_modules/babel-jscs/acorn-to-esprima.js:2:43)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ehochber/ruby/Prebid.js/node_modules/gulp-jscs/node_modules/jscs/node_modules/babel-jscs/index.js:1:84)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ehochber/ruby/Prebid.js/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:2:17)
    at Module._compile (module.js:460:26)
```

I'm on a OS X 10.11.3 running NPM 2.10.1. Any ideas? I wanted to submit a PR to fix that Sovrn adaptor using the responses..

**Comment by mkendall07** [comment]
@ehoch 
Make sure you do a `sudo npm install` in the root directory to download the latest NPM dev dependencies. If your still having issues after that, just do `rm -rf ./node_modules && npm cache clean && npm install` to clear out & reinstall.

**Comment by ehoch** [comment]
@mkendall07 And thank you for walking a NPM n00b through that. Working now.

**Pull request merged**
