### PR TITLE
Digitrust exit - 4.0 branch

### PR DESCRIPTION
**Pull request by patmmccann**
This simply opens #5334 on the 4.0 branch

### CODE REVIEW

**Comment by patmmccann** [comment]
I don't have write access to the IAB branch this PR is from; so i'll just  close this.

**Comment by pm-harshad-mane** [comment]
Hello @Fawke ,
I downloaded the code for the PR and ran `gulp test`, i do not see issues with it.

**Comment by pm-harshad-mane** [comment]
Can we update the PR branch code with `upstream/master`? i see old code of PubMatic adapter present in it.

**Comment by pm-harshad-mane** [comment]
I have raised a PR to remove the DigiTrust related test case from PubMatic bidder, https://github.com/prebid/Prebid.js/pull/5426

**Comment by Fawke** [comment]
@pm-harshad-mane Thanks for removing the test case. I've updated the prebid-4.0 branch with the changes on master. I've to close this PR in favor of https://github.com/prebid/Prebid.js/pull/5429, because I can't resolve the merge conflict in `modules/userId/eids.js`. 

5249 resolves this merge conflict.

**Pull request closed without merging**
