### PR TITLE
tappx Bid Adapter: fix wrong regex and gdpr bug

### PR DESCRIPTION
**Pull request by prebidtappx**
## Type of change
- [X] Bugfix

## Description of change

- We have fixed the wrong regex flagged at https://lgtm.com/projects/g/prebid/Prebid.js/alerts/?mode=list
- We have updated a wrong parameter related to our gdpr consent
- We have updated the adapter version

### CODE REVIEW

**Comment by patmmccann** [comment]
Thanks! Could you also add #6650 fix to this?

**Comment by prebidtappx** [comment]
Hello @patmmccann !
The adomain was added in this PR:  #6580 
Also, we don't see our adapter listed #6650 
Could you confirm that any changes are needed?

**Review by ChrisHuie — APPROVED** [review]

**Comment by ChrisHuie** [comment]
@prebidtappx you are good on adomain 👍

**Comment by prebidtappx** [comment]
Thank you @ChrisHuie and @patmmccann ! :grinning:

**Pull request merged**
