### PR TITLE
FTRACK UserId Submodule: adding more tests for the get ID methods in pbjs

### PR DESCRIPTION
**Pull request by ftxmoJason**
## Type of change
- [ ] Refactoring (no functional changes, no api changes)

## Description of change
- after making changes and adding tests for `pbjs.getUserIdsAsEids()`, we realized we also lacked tests for `pbjs.getUserIdsAsync()` and `pbjs.getUserIds()`

### CODE REVIEW

**Comment by patmmccann** [comment]
We love extra test PRs, ty!

**Comment by ftxmoJason** [comment]
@patmmccann I think this is ready to roll.

Do we think it would be helpful if there was a comment in the User Id submodule build directions asking folks to include tests for `pbjs.getUserIdsAsync()`, `pbjs.getUserIds()` and `pbjs.getUserIdsAsEids()`? Knowing what I know now, it feels pretty integral to have the responses from those methods dialed in.

**Comment by patmmccann** [comment]
It seems wise if the return structure is complicated, like yours or @Nick-Merkle

**Comment by ftxmoJason** [comment]
@patmmccann Added a PR to the documentation https://github.com/prebid/prebid.github.io/pull/3929

**Review by smenzer — APPROVED** [review]
LGTM

**Pull request merged**
