### PR TITLE
sspBC Bid Adapter: add bidfloor to imp and other updates to bid adapter

### PR DESCRIPTION
**Pull request by wojciech-bialy-wpm**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Update sspBCBidAdapter to a new version, with following changes:

- ad bidFloor data to imp (if provided in bidRequest)
- remove old params.bidFloor logic
- remove bidFloor check in interpretResponse (as it is handled by prebid.js bidFloors module)
- disable user sync on inventory that still uses TCF1
- code cleanup

### CODE REVIEW

**Comment by Rothalack** [comment]
This looks to be working for me. There's one documentation update I think you need, wouldn't you want to show Floors Module Support as yes on your dev-docs page? Any other edits you think you need?
https://docs.prebid.org/dev-docs/bidders/sspBC

**Comment by wojciech-bialy-wpm** [comment]
Hmm... No, I think support for getFloor is the only one.

Added in this pull request: https://github.com/prebid/prebid.github.io/pull/2992

**Comment by Rothalack** [comment]
Looks good!

**Comment by Rothalack** [comment]
@ChrisHuie Is there an issue with this?

**Pull request merged**
