### PR TITLE
EXADS Bid Adapter : update bidder code before adapter is published

### PR DESCRIPTION
**Pull request by giuseppe-exads**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Changed bidder code from exadsadserver to exads to comply with the filename convention: ${bidderCode}BidAdapter.js.
Fixed getEnvParams as specified in https://github.com/prebid/Prebid.js/pull/11456.

### CODE REVIEW

**Review by ChrisHuie — COMMENTED** [review]
This is all in first party data and doesn't need to be accessed this way

**Review by ChrisHuie — APPROVED** [review]

**Comment by ChrisHuie** [comment]
@giuseppe-exads can you please fix conflicts. Want to make sure and get this in before we release this afternoon or tomorrow's version of prebid so the adapter code is never changed for anyone.

**Comment by giuseppe-exads** [comment]
> Wouldn't let me select the block of code. Line 322 is where I am talking about -> This is all in first party data and doesn't need to be accessed this way

Hi @ChrisHuie, thanks for your consideration. I'll share it with my team and we'll plan the changes just possible.

**Comment by giuseppe-exads** [comment]
> @giuseppe-exads can you please fix conflicts. Want to make sure and get this in before we release this afternoon or tomorrow's version of prebid so the adapter code is never changed for anyone.

Conflict just fixed.

**Comment by giuseppe-exads** [comment]
Sorry @ChrisHuie, only one question. After your merging I've tried to download the prebidJS.
To do that I've navigated to https://docs.prebid.org/download.html and selected our EXADS adapter, but I get a short file of a few bytes containing:

{"error":"Prebid file not built properly","requestId":"ad6b1e82-7a59-4a0b-97ed-031c4bdb1d20"}

Do you have to do other actions?

**Comment by giuseppe-exads** [comment]
@tfoliveira

**Pull request merged**
