### PR TITLE
eTarget: adapter update

### PR DESCRIPTION
**Pull request by etargetse**
Send response reason

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by jsnellbaker — CHANGES_REQUESTED** [review]
Can you please update your unit tests to include checking for this new param?

**Review by jsnellbaker — CHANGES_REQUESTED** [review]
Hi @etargetse 
Did you get the chance to add/modify some unit tests that use this new field?

**Comment by etargetse** [comment]
We added this field just because we want to make some more detailed 
statistics it is not important parameter so why we need to make test for 
this parameter?

------ Original Message ------

**Comment by jsnellbaker** [comment]
It's general practice that new additions to your adapter have a corresponding test somewhere that validates the behavior and avoids gaps in logic.

**Comment by etargetse** [comment]
I did updated adapter specs and added unit test for new parameter

------ Original Message ------

**Review by smenzer — APPROVED** [review]
LGTM

**Comment by smenzer** [comment]
since @jsnellbaker is on vacation and his comments were addressed, I'm going to merge this.

**Pull request merged**
