### PR TITLE
LiveIntent UserId module: Add support for magnite id 

### PR DESCRIPTION
**Pull request by 3link**
## Type of change
- [x] Other

## Description of change
This pull request adds eid mapping for the magnite ids that now can be resolved via the LiveIntent UserId module.

## Other information

- repository of the backing live-connect module: https://github.com/LiveIntent/live-connect
- documentation PR: https://github.com/prebid/prebid.github.io/pull/4498

### CODE REVIEW

**Comment by 3link** [comment]
The test errors seem not to be related to changes in this PR.

**Comment by deepthivenkat** [comment]
Hello @patmmccann  Could you let me know for which of the following scenarios we are implementing the tie break for:
A) Magnite cookies are present from the magnite module and LiveIntent user id module also has a magnite cookie
B) Magnite cookies are not present in the magnite module but are present in both 33Across module and LiveIntent user id module

The reason i ask this is: 
For scenario A) if the path in which the magnite bidder adapter looks for magnite cookies populated from magnite module is different from the user->ext->eids array, then it is cleaner to implement the logic to read magnite cookies from LI only if magnite cookies are not populated by magnite module from magnite's bidder adapter. If the path is same, then i need to understand a little bit more about how to check if the magnite cookies are already present

For scenario B) Which approach do you like better? Relying on the load sequence(this provides equal opportunity for both 33Across and Liveintent) or allowing for Magnite to define the priority to pick up this cookie when its own module doesnt have it?

**Comment by jdwieland8282** [comment]
The id PMC recommends an optional `ext.provider` field to reference the "source of the source"
```
"user":{
   "ext":{
      "eids":[
         {
            "source":"magnite.com",
            "uids":[
               {
                  "id":"d88c96-5cb6-410d-827d-b019e476",
                  "atype":1,
                  "ext":{
                     "source":"magnite"
                  }
               }
            ]
         },
         {
            "source":"magnite.com",
            "uids":[
               {
                  "id":"d88c96-5cb6-410d-827d-b019e476",
                  "atype":1,
                  "ext":{
                     "source":"magnite"
                  }
               }
            ]
         }

**Comment by deepthivenkat** [comment]
Thank you!

**Comment by 3link** [comment]
@patmmccann @jdwieland8282 Can you please have a look at this proposal: https://github.com/prebid/Prebid.js/pull/9896?

**Review by SKOCHERI — DISMISSED** [review]

**Comment by SKOCHERI** [comment]
@3link Can you update https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.md with magnite eids

**Comment by 3link** [comment]
@SKOCHERI Done in https://github.com/prebid/Prebid.js/pull/9828/commits/68aae9531a44cb51224eaa8c82961c657fe00885. 

@SKOCHERI Please note, there is a [concern](https://github.com/prebid/Prebid.js/issues/9730) that is blocking this PR. There is a proposal that might unblock it and requires a review: https://github.com/prebid/Prebid.js/pull/9896.

**Review by skocheri1 — APPROVED** [review]

**Review by dgirardi — COMMENTED** [review]
this seems to go against https://github.com/prebid/Prebid.js/pull/9896, as in including the liveintent module can populate `magnite` at the top level instead of `libp.magnite`. is there some other integration pending?

**Comment by 3link** [comment]
> this seems to go against https://github.com/prebid/Prebid.js/pull/9896, as in including the liveintent module can populate magnite at the top level instead of inside libp. is there some other integration pending?

@dgirardi This is correct. This PR started the discussion about exposing the same type of identifiers via multiple user id modules. https://github.com/prebid/Prebid.js/pull/9896 is meant to be a place where possible solutions are discussed. Once a solution has been found, I will update this PR. 

It is possible to flag this PR as blocked? Alternatively, I can convert it to a draft so it does not confuse reviewers.

**Pull request closed without merging**
