### PR TITLE
Add host field into limelight bidder adapter

### PR DESCRIPTION
**Pull request by imedvedko**
## Type of change
Bidder adapter related changes

## Description of change
This PR adds `host` field into limelight bidder adapter

- test parameters for validating bids
```
var adUnits = [{
                code: 'placementCode',
                sizes: [[300, 250]],
                bids: [{
                        bidder: 'project-limelight',
                        params: {
                            host: 'ads.project-limelight.com',
                            adUnitId: 0,
                            adUnitType: 'banner'
                        }
                    }]
                }
            ];
```
```
var videoAdUnit = [{
                code: 'video1',
                sizes: [[300, 250]],
                bids: [{
                        bidder: 'project-limelight',
                        params: {
                            host: 'ads.project-limelight.com',
                            adUnitId: 0,
                            adUnitType: 'video'
                        }
                }]
            }];
```

- contact email of the adapter’s maintainer engineering@project-limelight.com
- [x] official adapter submission
- Bidder params documentation here https://github.com/prebid/prebid.github.io/pull/2048

### CODE REVIEW

**Comment by imedvedko** [comment]
@harpere @afewcc Can I help you with this pull-request merging? Can you disable stale bot for this pull request? It shouldn't be closed without merging :-)  .

**Comment by imedvedko** [comment]
@mike-chowla Can I help you with merging this pull-request?

**Comment by imedvedko** [comment]
@jaiminpanchal27 Can I help you with merging this pull-request?

**Comment by aleksatr** [comment]
hey @imedvedko , your test coverage is below 80%, can you bump it up? One of the requirements for merging PRs is to have at least 80% test coverage. 

To generate and view the code coverage reports:

```bash
gulp test-coverage
gulp view-coverage
```

**Comment by imedvedko** [comment]
@aleksatr Thanks for the detailed comment. I fixed it

**Comment by aleksatr** [comment]
> @aleksatr Thanks for the detailed comment. I fixed it

Np, I've checked the changes and they look good to me. You should consider providing some valid endpoint for testing, as the one you provided in examples does not seem to work `ads.project-limelight.com/hb` - host `ads.project-limelight.com` can't be resolved. This will make it easier to test future PRs.

So, feel free to open a new PR once you find a test endpoint, I'll be merging this one.

**Comment by aleksatr** [comment]
LGTM

**Comment by imedvedko** [comment]
Thanks

**Pull request merged**
