### PR TITLE
Create adapter for Brightcom

### PR DESCRIPTION
**Pull request by matan-ybrant**

### CODE REVIEW

**Comment by matan-ybrant** [comment]
Hi @protonate and @mkendall07 
This pull request continues pr #199 
Let me know if you need me to update anything else.
Thanks!

**Comment by protonate** [comment]
Thank you for the fresh PR @matan-ybrant, I'm doing final testing now prior to merge and the Brightcom ad server is refusing the connection when requesting bids. This is the request:
```
https://hb.iselephant.com/auc/ortb?callback=window.pbjs=window.pbjs||window.parent.pbjs||window.top.pbjs;window.pbjs.brightcomResponse&request=%7B%22id%22%3A%221094e6928c3e05f%22%2C%22imp%22%3A%5B%7B%22id%22%3A%229356ee2bb70309%22%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A250%7D%2C%22tagid%22%3A16577%7D%5D%2C%22site%22%3A%7B%22publisher%22%3A%7B%22id%22%3A%22%22%7D%2C%22domain%22%3A%22localhost%3A9999%22%2C%22page%22%3A%22%2Fgpt.html%22%7D%7D
```

Any ideas?

**Comment by matan-ybrant** [comment]
Hi @protonate 
Thanks for notifying me! It seems we have a small issue on our server.
We're working on it. I'll let you know once it's fixed.

**Comment by matan-ybrant** [comment]
Hi @protonate - we had some issues with the SSL certificate, but it's fixed now.
Please try again.
Thanks :)

**Comment by protonate** [comment]
Thanks @matan-ybrant I can confirm bids are now returned. Reviewed.

**Pull request merged**
