### PR TITLE
Zeus Prime RTD Provider: remove functionality 

### PR DESCRIPTION
**Pull request by mbcrute**
Removes zeusPrimeRtdProvider submodule along with associated docs and specs.

## Type of change

- [x] Feature

- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change
Removes the RTD module for Zeus Prime as we have deprecated the business.

## Other information

Documentation PR: Prebid/prebid.github.io#4226

### CODE REVIEW

**Comment by patmmccann** [comment]
Hi, you can't delete until a major version so you don't break a build prices, but you're welcome to remove all the functionality

**Comment by patmmccann** [comment]
Linking #8539

**Comment by mbcrute** [comment]
Hello @patmmccann 👋 Thanks for the feedback. I have updated this PR to remove the functionality associated with the module and added a deprecation warning message.

Further feedback is more than welcome.

**Comment by mbcrute** [comment]
Deleted 👍

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
