### PR TITLE
fix: retrieve unexpired bids only

### PR DESCRIPTION
**Pull request by johngeorgewright**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change

We're often receiving expired bids. I think there's some logic which is incorrect.

## Other information

https://github.com/prebid/Prebid.js/issues/2676

### CODE REVIEW

**Comment by johngeorgewright** [comment]
Sorry, I think I jumped the gun here. This isn't the cause of our issue.

**Comment by hgoebl** [comment]
I think your fix would be correct if `isBidExpired` were doing like the name suggests. Actually, a better name for `isBidExpired` would be `isBidNotExpired`, because the function returns `true` if the end-time of TTL is greater (=later) than current timestamp.

**Comment by johngeorgewright** [comment]
Hey @hgoebl, isn't that what an expired bid is?

If the current timestamp is less than the response time + TTL, then it's an unexpired bid, right?

**Comment by johngeorgewright** [comment]
This is what confused me for a bit.

**Comment by hgoebl** [comment]
Yes, you're right.
Either the name of the function is wrong, or the implementation. And as it's used like "not expired", my conclusion is that the name is wrong.

**Pull request closed without merging**
