### PR TITLE
Smart Ad Server: Fix bug when multi bids

### PR DESCRIPTION
**Pull request by Spacedragoon**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Support multi bids

## Other information

See issue #2166

### CODE REVIEW

**Comment by mike-chowla** [comment]
I tried testing this with the parameters from #1908 but I'm not getting any bids back

Here's the request body:
```
{  
   "siteid":32216,
   "pageid":881291,
   "formatid":13695,
   "bidfloor":0,
   "tagId":"div-gpt-ad-1460505748561-0",
   "sizes":[  
      {  
         "w":300,
         "h":250
      },
      {  
         "w":300,
         "h":600
      }
   ],
   "pageDomain":"http://mike.pubmatic.com:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true",
   "transactionId":"32b617ee-88eb-4c61-b6c1-4cc1b6c44a41",
   "timeout":3000,
   "bidId":"2f4f1ce0010ba3"
}
```

**Comment by Spacedragoon** [comment]
Hey @mike-chowla,

Indeed the parameters in this PR are out dated, and were actually changed in the md file. the right ones are 
```
{
  sizes: [[300, 250]],  // a display size
  bids: [{
    bidder: "smart",
    params: {
      domain: 'http://prg.smartadserver.com',
      siteId: 207435,
      pageId: 896536,
      formatId: 62913
    }
  }]
}
```

They just weren't updated in the PR message at the time. Sorry about that.

**Comment by mike-chowla** [comment]
I tried with the new params and am still not getting any bids back.  Response is 200 status code, content length 0

Request body:

```
{  
   "siteid":207435,
   "pageid":896536,
   "formatid":62913,
   "bidfloor":0,
   "tagId":"div-gpt-ad-1460505748561-0",
   "sizes":[  
      {  
         "w":300,
         "h":250
      },
      {  
         "w":300,
         "h":600
      }
   ],
   "pageDomain":"http://mike.pubmatic.com:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true",
   "transactionId":"3ed7eb77-4430-47f5-b85d-22e73db916b2",
   "timeout":3000,
   "bidId":"2bd748c0715116"
}

```

**Comment by Spacedragoon** [comment]
Hey @mike-chowla, I don't get it, I tried with your exact request body (copy/paste) with a rest client and i get the response. 

I also tried with the test page locally and it works just fine. 

http://imgland.net/file/DD9BP28unPz8GPz8unGD8unPw.png

http://imgland.net/file/AD9rP3ounPyxBekIunfT8unUg.png

**Comment by Spacedragoon** [comment]
Hello @mike-chowla, 

As I said it works when i try, could you try again ? Also, If it still doesn't work could you show the Url you are calling ?

**Comment by mike-chowla** [comment]
Sorry for the slow response.  I'd been in India and I thought that might have something to do with the issue.  I tried again and I'm still not getting any bids.

screen shot 2018-03-07 at 4 56 38 pm

screen shot 2018-03-07 at 4 56 27 pm

screen shot 2018-03-07 at 4 56 56 pm

**Comment by Spacedragoon** [comment]
Hello @mike-chowla 
Could you maybe try in a browser without your cookies, 
maybe you're opt out or blocked in some manner.

I know it's a bit annoying but i don't understand why you don't have any responses.

**Comment by ytyukhnin** [comment]
Hi @mike-chowla,
While my colleague @Spacedragoon is on vacation. Could you please test the PR once again with the following configuration to enforce the use of our French data-center as our test environment is installed there. The _prg.smartadserver.com_ endpoint while being geographically balanced could impact your test by adding additional latencies while contacting our test environment. 

```
        {
          sizes: [[300, 250]],  // a display size
          bids: [{
            bidder: "smart",
            params: {
              domain: 'http://ww251.smartadserver.com',
              siteId: 207435,
              pageId: 896536,
              formatId: 62913
            }
          }]
        }
```
Thank you.

**Comment by mike-chowla** [comment]
With those new parameters, I do get bids back but the ad is not rendering properly

screen shot 2018-03-13 at 1 29 42 pm

**Comment by ytyukhnin** [comment]
Could you please provide a HAR file so we could compare with our test? Do you have any errors in the console? Thank you.

**Comment by mike-chowla** [comment]
The test parameters need to return a valid ad.

HAR File:
[mike.pubmatic.com.har.zip](https://github.com/prebid/Prebid.js/files/1827484/mike.pubmatic.com.har.zip)

There's actually 2 issues.  The 0.05 cpm you are sending back is getting put in the zero price bucket which causes ads not to display with hello_world.html.  I can hack around that but you should really send a test ad back with a higher cpm to stay out of that bucket.

The adapter code returns ad field as the creative and as that field is coming back as JSON, it's not a valid creative
  
Here's what I'm getting back.

```
{  
   "cpm":0.05,
   "currency":"EUR",
   "width":300,
   "height":250,
   "ad":"{  \r\n   \"ad\":{  \r\n      \"insertionId\":\"7537582\",\r\n      \"pageId\":\"896536\",\r\n      \"formatId\":\"62913\",\r\n      \"impUrls\":\"http://ww251.smartadserver.com:80/h/aip?tmstp=2700661361&ckid=806240067568501518&pubid=14&systgt=%24qc%3d1314063287%3b%24ql%3dmedium%3b%24qpc%3d95122%3b%24qpp%3d408%3b%24qt%3d152_2199_15404t%3b%24dma%3d807%3b%24b%3d16640%3b%24o%3d12100&visit=S&statid=5&tgt=%24dt%3d1t%3b%24dma%3d807%3b%24hc&pgDomain=http%3a%2f%2fmike.pubmatic.com%3a9999%2fintegrationExamples%2fgpt%2fhello_world.html%3fpbjs_debug%3dtrue&capp=0&mcrdbt=0&insid=7537582&siteid=207435&imgid=0&pgid=896536&fmtid=62913&loguid=232879519236338477&logdate=1521507211229&sig=wdbtdgYygCsHswJj%2bk3xBIqHYmRnHroLtuiH4itTy3E%3d&rtb=1&rtbnid=475&rtbbid=232879519236338479&rtbh=b004f93b2729420cf0578aea9d33ef48f63ad664&rtblt=636571040112289147&rtbet=0&rtbnc=nc\",\r\n      \"userParams_domCode\":\"a\"\r\n   }\r\n}",
   "adUrl":null,
   "dealId":null,
   "ttl":300,
   "isNetCpm":false,
   "creativeId":2764915284948388740,
   "cSyncUrl":"//csync.smartadserver.com/rtb/csync/CookieSyncV.html?hasrtb=true&nwid=475&dcid=3&iscname=false&cname="
}
```

**Comment by ytyukhnin** [comment]
Hi @mike-chowla ,
We have changed the CPM to 5 EUR and added a real creative. You should get this as a response:

```
{
  "cpm": 5,
  "currency": "EUR",
  "width": 300,
  "height": 250,
  "ad": "<script>\r\nvar response = {  \r\n   \"ad\":{  \r\n      \"insertionId\":\"7537582\",\r\n      \"pageId\":\"896536\",\r\n      \"formatId\":\"62913\",\r\n      \"impUrls\":\"http://prg.smartadserver.com:80/h/aip?tmstp=4773323216&ckid=5319510449987626515&pubid=19&systgt=%24qc%3d1314859526%3b%24ql%3dmedium%3b%24qpc%3d75001%3b%24qpp%3d0%3b%24qt%3d184_1903_42652t%3b%24dma%3d0%3b%24b%3d16650%3b%24o%3d11100%3b%24sw%3d1920%3b%24sh%3d1200&visit=S&statid=5&tgt=%24dt%3d1t%3b%24hc&pgDomain=http%3a%2f%2flocalhost%3a9999%2fintegrationExamples%2fgpt%2fhello_world.html%3fpbjs_debug%3dtrue&capp=0&mcrdbt=0&insid=7537582&siteid=207435&imgid=0&pgid=896536&fmtid=62913&loguid=458903927762638288&logdate=1521541202956&sig=Mvru9IEXEWWxuI52agiBQAOdf1FXQAsrfRJkOWnq8j8%3d&rtb=1&rtbnid=475&rtbbid=458903927762638291&rtbh=70cfd168f08db5e685ab4c492b8b529df67db6d2&rtblt=636571380029556261&rtbet=0&rtbnc=nc\",\r\n      \"userParams_domCode\":\"a\"\r\n   }\r\n};\r\n</script>\r\n<img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAhIAAACFCAYAAAAOwRFtAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAEwtJREFUeNrsnUtWG0kWhkM+zEWvANWISZ+DatBj5BUgrwB5BcgrQKygxAoQK7BYgdMrsJg1I4txDwpOD3ugzpsRiRKQQEIZj4z4vnOCKqrszIzXjf/eeLUWi4UCAAAAR9y1svznca3PPFy0fGXnEzUKAAAACAkAAABASAAAAABCAgAAABASAAAAAAgJAAAAQEgAAAAAQgIAAAAQEgAAAICQAAAAAEBIAAAAAEICAAAAEBIAAACAkAAAAABASAAAAABCAgAAABASAAAAgJAAAAAAhAQAAAAAQgIAAAAQEgAAAICQAAAAAIQEAAAAAEICAAAAEBIAAACAkAAAAACEBAAAACAkAAAAALZkL5gvuWt18p8d81tvi785y9PD078fLh6o1trrZj//2TW/yT/3N6yTh7w+Zgnle26SyvOd0XCs2YdqvWzCsl6wEaHWb9Xmr+tr87zuJjW3qYGX/P5H/VP9r+6Htkaeai9rLRYLH42ma8RC1xiH45rfcGsGsswYkFmjBzS3xrpbSfL7UQ1Pvjf1kBmRIfUxD9CQdS20yZ9PeaYdbmIXqm2wFAxtC2+7fbINZbtEYLjoY6Ug7Jn6PdqqLx0uejV/zw8vZfHvPP235mf+y1vNXrgREtqz65vG07dkGDY16lmR8BjLjtSriDqX9XJv6mKa18XUk2gq2+SJwzc/PuVb5/0h0ba3/6LtHQfwVbcV+zBVEFr9IiSSFBK6ogZ5Og20ud8kZdC1x1cOnscBfdljpR6mFvO/b9rjQNUTaamvDdYZsg1buJbt7yjwry3b5ASnY2tx3rdkXxASSQmJu5YY6lGeDhrUDeITFUuvoOzc7QZ8tUQqxsaAP9RoMEIWtOXANS5STKL2rtVvWPtz0ybjijz0Tf+y7ZwgJJIQEs0UEOs8kVFw8/jbdWxJJw2vh90GVm0oRiqs6Ev8gmIp3JosHtIRex+PPgxNPbuqY4RE1EJCh8zHDTPYm0Ypxo0IbWrPb9Bw8bDOeIuoG29p5MYRCKnt8h1GO5w33JHYNEIxSmI6anXfEnHuI7qHkAhUSHyqoTKkUf2KUEQoMxD9yPOYvdieFEqn7uZpkifxjr5HKCKU8Xb+yvM4M4J1k/Y4i6Astst3OKSwK0WE0pWxC51EBMR+nkTU/lZhTxGCBz7t2LDEUz9PoJyOjaCYeDccutwHxQCjBdypiit8vI6jIr93a/ZKS73oMjmPrDwk35mZNmwCKe12OC6Ek44GxiwipO3N83TGkAn1CQntIc0ijUK8xakxHCMPnblTCBndoa9U+KvebXFuPMH9Stn0TXuMtUzaxgOeICSCrJvvxluPMQqRGXvTVgC1CQktIqRxHSRaZm0zmLkJOcuUiu7MvxOKPmziCWZmameo9LROCuVyatrdfrBfqBch3iTYJs8aIvQ2tTt947QcK4BahcRSRDCYvRdqr6czyyD5g878RvnLOoL08p0FLSbSi0pUhV7zxYS2aamIc3AqJPTaAETEa84tzl/vU7zQODGhdzM8IiYaJyD2zbef08WgfiGhDdYUEbGS2yS3gUEYYiJcUj5i+rRxaya0jc8UOzLAmpDQ+4aPKK5XiNfVpxjAm5gI1/tN/a6Ks8bstFmKCGw8WBIS+vwEtv2sZtjI0y8hNu83vAFL35nymHjdjIM/ZwIRAU6EhJwvD6u4YUoDGLDeJPWoRLsB9nOMiAC7QkKv3j2gmF4hntaAYgAGLITEOxyb3VfhoddxsCYCdmbvjUYmIS/XHeCn0gcLyV707J0/K1tR5Rs7JrncItnnFkAIcMDqW72GfVvkW+5aj4pF2qNiLUtINkOfE8GUNVgWEu5u7rtW+urubQ1gtqJziKDoGZEh328jmnLZiEu8IEXGAUYBpni9hR0dKr1oPQQRIXZyQncBF0LCdqO/VnVf1a2fVXaQoekw5a2YdcwDylbPYcLtRSJGc5OEMnqkjIATOkbIxTTv+mjyWgrIB7W8nKpjkjL57njM+0Gx8DKstTu7Colb095mL9qebn/i5et+3qn8d2mL+6Y+uiqMiMiwmEoIIyoxUUSJoEZWXyOuT7D8ZdEo95179drYDI2oaH/wu3v5d88cfrOIOV+Hw9ybgTMzBnu25bfvG4Peb6hHem88/OxDda53O/WVvcjY+u8+XHSCKsnNrxZ/fNHmspre3zVtsS6H4qNc5Hkaea4LsYEhnga7TjDOo9wZp689qHc6/nDRCk1IiAE9s9RYet5Vud4uN9rSwH/Lv3vs+DtdC4mfxoOc1tp5l+tthg3whH4qHSnLPLe3XfgS1FqJt+3JfaXNZQ6+pWMEhY+26Ffk6bzPAumDt6besySnihMREjZuUhRvoxuUutzcwMtWz76H73MhJKRDT4pkW+BpQyaDykmAXfvRCIixxfyX8+S2Dbmf9vp2RODXi7Iu29zM43e5qo8wRJ4+vMxndLCM8k2TP38neiGhvce/Lbzra7DnLrwtKMTodbxEUewJidKQj7106PDCq7eFl+piUNOD6kTZD7H/I7BdAnOlpyymgUVL9k3fd7WD4TrP/8BDPntKXwDog/qjfAiJoITEqnMkbFyNfR/04U362yTfFyv+b2xbPS+MMPJ3Kqf2+r8GJCLcrX3R7+mZ99qkH1gf6xQDaEgiQn/Xg1lA/UW5OYnTV72MPAmIz3n59hARcbNKSPQsvCf8g2m0QZHO9ofpAEKMWz2zIISRFm++xYSfNTv6fT3LA1dPwTZ1MnUk8NrmDAfX0QiX5+w8Kh2BRkAkLCRsXE3cnMYkXrp0AD3IjWgi1sXEpae3l7uHHjzl/cGyd4qQ2L5OXEWLXNeNyy3r4oR1uT4AIWFjaqN5UwPSETi90kU5Dx0Y7lUMvC/40t7ataWnHwR/YVSY7TGuaJFuA64WN1+bKMSchoSQAHA/qLvlZ0Bz9UOLg1aXprWTmLDFkeP25YJvXhaRQlJCAoMGbxnumUXP3Kdx3XTQmtLvgmyTFxYjBT1HOXExuH91fsYOICQAVjBy9J4br2cXrMaWEe7QrHaul/vG2kS9rd32GRmXrIcAV0KiT1HDOx7gXC13yzRx0N7V+7UxYCEkdquXB4sC10Xd2La7N4nfPQSOhUTbHK4E8Ba2PZv7gLejTan+IMXExJLIsxuR0AdtnVjtS+7XNkHiQkIYmlP9AHwNpiEP1jYEDv0t3Hazb/mbbUcjBuxqg7eEhC2PrV08GzEB670/MUw2pzdCFhIzS30Odmdi4Zm2d270LD77moOm4D0hMbf4PjFsv5jmAMeeeSlUwjV+7L0PWeCKyHts2FfbikhIObAuAp6x59SQLzl/uiiLFb/wuv3ZuKjsZwPyfqvcnjEQNjp6+f4UgBuBKGLiuOb8dawISF1utqJRY6Y04H0hIQ37riULaQ4sv1uef5W/S1bRT5TvK4UhFGy1gSZ4/OkaaH2ugqSuSQdb/N3qb/eVup6ZMp0/pY8P3Jmq/76KjqV22bMYjeC8CNgoIiHIXLKra3Xb5l1nRsBMlb5qOKN6EkS8nbvWowWPak7hBiceJPxeprrq+6AiQo7XiI5bIzCyisiYReRp21qHxrUBsJWQGDsUEi+NQCkqHk1H14loRWpRibq9P4RpGOJBpipkjn2g7Ec913G0UmhomzN7JjCWDk2T7I+tiATRCNhCSOjpjRvl7rKXdZGKk6dveN7Js8g8CIBUBMRQhbubpG3ExXHlu+XnbcPK2YZAu2VBMGwbkVCmw58E2snPTae5fSYuaOixkFmISNA2/A1ufePNHjQ0B01aAGtvWgNgayGhoxKXys8UxzYdXNKpMVj3ZhCaGmFBxAKW7Rl8eMeTwByS2LElJDh5Fdby3smWI9WksJ72eERUfM/T37khmxVnVnAIFoBrESF9boaIcE7HwjOZ1oAdhIT26AeqeYexlEi0QqZB5BCsebHVVIdZAcCeiBCbkanmTmU0GRtOU0axwseFhBYT4lXEMPiWO0K+V0QFkQqA+kXEleJ4bl90EBIQnpDQYkIa0teI8l2Kil9m+mNg5nMBYHcRAX5tG0ICAhQSWkxM8p9/quZOc6zjyBi/MkrRoVkAICIaWAc2nKF7Fq1DfUJCiwmZ5pDpgNsIy6I8YfN33iEnCAqAjQewLiIiCGxM1c4pVqhXSGgxIae9SYO9jLhcTo2gGDPlAfCuF5xRENFC3cK77H34bx4uhrkRkb3FctBMrDcWSoRC1k8MuaUUYCViA1hYGQYdiqAxRHXlw95Of1svwuwWA60+cyJGgyJ5ujJzwH3mCwEMut8fUxBRC4mMYrWAOOIR8ammQhmbRnyh4luMWSIGc26uOwZIXUTsG+cBABLnU21PEk/9cDEygkK2it5HWF4SnfhhohMAKTNSTGmkwJwiAHdC4rmgkHvrRVB8ydNNhOV2VezsAEgRvaPpjIJIAI7GBi9C4nkjnOZJTsX8R56+qbi2jZ4WuzoA0mNEEQCAGyGxFBQPxToKvW30j4hExRnTHJAUem2EjyPzH1W866/qokcRgA/2nL9Rh8rGRVoapb7pBE2cc70qjtnWh3UBxE7fQT+V9VXTIumdYZuIm/Iwpuq/dyu/s54DIBoh8VxUyFbKiUnK7IgoU5O2lU2L0/3YGgrxY3PbmgiIwUbi4bUdyZ71x9WCo1cRFpI6Kt4zcAASERKvDUL2ZBC0l1GKim7gwuLAGNgRTQqiRS+ytDXwXlrfW78UKNMX+epWxEXotgYAIbGllzF91um1R1FOg4TmSQyLxZdEJSBeepae+9XrybF6WnK2RlyUjgyRC4DGCYn1HkVmOnoZsSiFxYHnr2srohKAkNiW6yCPn1+Ki0nFiflBEwB4zafGfrneCSKLsQbmzAq54lwuEvN5ENaAJgUIiY15VHbXXAAAQmJLD0LmWJ+LCtfbxQ5yz6VPs4JIqTvqx1QgAEIieFEh0x9yXLfLMyt6NCuIDjt3zEwoWACERBNExcQchPVZuZn26NKsAN7lnuOXARASTRMUmZn2uLD8JraOQYzULZAREQAIicYKipHS0Ql76yf0jhKAmKBNAwBCoiImMmV3LQPTGwAAgJCIXEzIHvELmgCAFzoUAQBCIgYxMVLcKAjggwOmAAFSFRLS+e9aMR0iM6UZAHiBM1cAkhQSeu/3X8XV2fo8+qbD9d8A75NZeOaAYgVITUjIpVRKnZjfjgrj0vzohA0hMadpAbzLsaWDrgAgSCFx1xLv4ezFf5WLqpoenajfkHHQDsTG8gruupmwVgIgBSGhRcLVG39CohO/8j/XRKNQ9zwtizchVmycDCv3d4wpWoCYhcRdq6M2nx89VRLWv2uNGiEo9AVbRzU/lTUXECuZpeeeFk4IAEQoJLQYkF0N7S2eKX/2PHhBob/LhvHKaFaAkEBMACAkNJMdPPaqoBibyEZIIiLbUiBtChEJQEh8XEzEshsMACFhvIOTGt4hg7Us0vydP3NqFm36FBE9pXdVHFl6Q0azgijRi4hvLb+lut4KQQHQAPbWDLYDpdc71M1JkfQ20qlJcivngwMB0cl/jizlq+TGSV4A/CEOxl8O3nOqdITi/slOKOWzbyFqoPnoaHztN/nurfHYryxnp/1kKPQ7fxpDIWlW22CsxYPkR4SRi+u9OSUTUhASI2VnWnAVsqvjTL3eeg4AHxPEP2p+5sXei4G362kwPDbp3HyHeCFztZwmyCp/9rXQWB5qU6qtUkAcOMzDI0ICokf6nkxR2o3sAUCD2KsMxuUuhnYA33VgUhlFOH8hHEIsyynTGpAII4QEAJR8ejYQ2luAmIpxBYgfvejymoIAgKWQ0Ds0jimOD3PJsdiQGHLHDqe4AkAuJOzt0EgFMaYjigGSQk/j0e4BoIhIPOBZ7MSAtRGQqJiQbdw/KQiA1IXE4ULWRvSU/YNmYuTalB9AqvRxRABSFxLas5gZMXFJkWyMCK8hxQBJo6NxfQoCIHUhURqEw4UMjF/wMDYSET2mNAAK25HlP79SEACpC4mlUZBQfUcRnViHiCzWRQA8txsTxAQAQqJqFMroxGfF2okqt4XI0lNBAICYAEBIvGMY5EKtrjEO94mXlaxOZzoDADEBABsLiapxOFx0EhYUF3n+EREAm4uJPxVrrQAQEgiKYirjzzzPI5oKwFa2Qqb/xFbcUBgACIm3BMXnSA2FeFLfimkd1kMAfFRMyFor2RrKTjAAhMRaQ5EZQ/FHMfA2P0ohxu5C6QWVY5oHQC2CotwJdoGgAEBIrDMU82Lg1VEKmRuVraNN2u0h3/rVCIgRayEAahcTD2aKEEEBEBl7FgyGTAXoEx/vWmI0ekqffCf/bAeUd4meiKc0YfoCwKGg0Jd9jcyFgWIbTigYAITEOqMxLwZqnarComuSy6vLRThkT4lrvwF8i4qqbegZ21DahzYFBNAMWovFwu8XaHHRMcZjv/JPSUdbPk3CpWV0QQTDg/l91sjpimXZ1En4ZWEj3/oY59Dru2z7aeV7fXn0Ire/9fZF2g+830bKMbZO5v6FxC7GhUYOAADglf8LMACX9V5Sm56frgAAAABJRU5ErkJggg==\">",
  "adUrl": null,
  "dealId": null,
  "ttl": 300,
  "isNetCpm": false,
  "creativeId": -252826307751156000,
  "cSyncUrl": "//csync.smartadserver.com/rtb/csync/CookieSyncV.html?hasrtb=true&nwid=475&dcid=6&iscname=false&cname="
}
```

Could you please test again? Thank you.

**Pull request merged**
