### PR TITLE
Add viewability to e-planning bid adapter

### LINKED ISSUE #4132: Eplanning bid adapter will never return test bid.
### Type of issue
Bug

### Description
Eplanning adapter has  "t" bid param which should return test bid from cdn in any case. 

### Steps to reproduce
Add two eplanning bids with params:   
{t:1}
and
{ci:"123"} 

### Expected results
adapter should return static sample response from http://i.e-planning.net/layers/t_pbjs_2.json
## Other information
[Function that checks that request isTest](https://github.com/prebid/Prebid.js/blob/master/modules/eplanningBidAdapter.js#L139) can only return true if test request is the last in array, COZ  forEach is used instead of reduce

### PR DESCRIPTION
**Pull request by hdwmsconfig**
## Type of change
- [x] Feature

## Description of change
This PR adds viewability tracking to our e-planning bid adapter, and changes one of our request parameters. It also fixes #4132 

## Other information
We added an observer to be able to track adunits whose divs weren't yet rendered when buildRequests is first called. Unfortunately we ran into some problems while testing this feature, due to its asynchronous nature, the test code was finishing before the observer callback was called. Any ideas on how we can test this? Thanks.

### CODE REVIEW

**Comment by bretg** [comment]
Unit tests are broken with this change. I re-ran them many times. Failure is

```
IE 11.0.0 (Windows 10.0.0) ERROR
  {
    "message": "Object doesn't support property or method 'forEach'\nat webpack:///modules/eplanningBidAdapter.js:218:6 <- test/test_index.js:139444:7\n\nTypeError: Object doesn't support property or method 'forEach'\n   at Anonymous function (webpack:///modules/eplanningBidAdapter.js:218:6 <- test/test_index.js:139444:7)\n   at Anonymous function (webpack:///modules/eplanningBidAdapter.js:217:4 <- test/test_index.js:139443:5)",
    "str": "Object doesn't support property or method 'forEach'\nat webpack:///modules/eplanningBidAdapter.js:218:6 <- test/test_index.js:139444:7\n\nTypeError: Object doesn't support property or method 'forEach'\n   at Anonymous function (webpack:///modules/eplanningBidAdapter.js:218:6 <- test/test_index.js:139444:7)\n   at Anonymous function (webpack:///modules/eplanningBidAdapter.js:217:4 <- test/test_index.js:139443:5)"
  }
```

**Comment by hdwmsconfig** [comment]
Fixed the observed error but unrelated tests failed

**Comment by Nistenf** [comment]
Checks are now green

**Comment by sebaperez** [comment]
Hi @bretg @mike-chowla any update regarding this? Could it be merged? Thanks!

**Pull request merged**
