### PR TITLE
VIS.X Bid Adapter : add first-party id

### PR DESCRIPTION
**Pull request by vfedoseev**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
We have added the first-party user id for VIS.X bidder.

### CODE REVIEW

**Comment by vfedoseev** [comment]
Hi!

I've checked the test report and I see that the failed test is not related to the changes in this PR.

Thank you in advance for checking.

**Comment by patmmccann** [comment]
Why not just use the sharedid?

**Comment by vfedoseev** [comment]
Hi @patmmccann,

Thank you for your patience.

Actually we have some reasons to use our own first-party id. 
The main reason is that the publishers could integrate our inventory not only as HB, but also via the tags. And for the tag integrations we already use our own 'vads' cookie to save the first-party user ids. So, we'd like to use the same cookie in HB in order to match the users between the different type of integrations - HB and tags.

The other reasons that we can think of are the following:
- More control against the issues from our bidder side
- Avoiding mapping of multiple IDs (saves database space)
- Independence from the 3rd party ID format and logic changes
- Easier communication with publishers as they already possess the info on our ID solution and uses of the browser storage
- Full control over compliance with user privacy regulations (GDPR)

I hope that this information the suggested solution for VIS.X bidder in more details. However, if you have any further questions, we'l be happy to discuss it. 

Thank you in advance and have a nice day.

Best regards,
Vladimir

**Review by mmoschovas — APPROVED** [review]

**Comment by patmmccann** [comment]
@vfedoseev this is very interesting; I suggest you add similar discussion to your documentation when pubs inevitably ask the same

**Comment by vfedoseev** [comment]
Hi @patmmccann ,
Thank you a lot for the suggestions. We'll definitely consider the options of how to inform the publishers about the fact that our VIS.X bidder is using our own first-party id.

**Pull request merged**
