### PR TITLE
Relevate Health Bid Adapter: Use Storage Manager

### PR DESCRIPTION
**Pull request by hasanideepak**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Comment by hasanideepak** [comment]
@patmmccann As agreed, I have used the storage manager instead of directly using localStorage. Please review. Thanks

**Comment by patmmccann** [comment]
You must stop doing things like https://github.com/prebid/Prebid.js/pull/11931/commits/a34dd3ddf119338b322577338b6c68b205a36ebe. This is a conduct issue. Revert that commit.

**Comment by hasanideepak** [comment]
> You must stop doing things like [a34dd3d](https://github.com/prebid/Prebid.js/commit/a34dd3ddf119338b322577338b6c68b205a36ebe). This is a conduct issue. Revert that commit and any other changes that are designed to fool our checks and make our code worse.

I agree, but as you know these changes made to avoid duplicate code. How would I avoid it, if our adapter have some common lines with another adapter. We cant use the common library. Please guide.

**Comment by patmmccann** [comment]
What is your concern with importing functions? 

It is better to let the robot complain than to change the code to give from it

**Pull request closed without merging**
