### PR TITLE
New adapter - videofy

### PR DESCRIPTION
**Pull request by vladi-mmg**
## Type of change
- [X] New bidder adapter   

## Description of change
New adapter Videofy

- test parameters for validating bids
```
{
  code: 'video1',
  mediaTypes: {
    video: {
      playerSize: [[640, 480]],
      context: 'outstream'
    },
  },
  bids: [{
    bidder: 'videofy',
    params: {
      AV_PUBLISHERID: '55b78633181f4603178b4568',
      AV_CHANNELID: '5d19dfca4b6236688c0a2fc4'
    }
  }]
}
```

- contact email of the adapter’s maintainer
- [X] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/1987

### CODE REVIEW

**Comment by msm0504** [comment]
@vladi-mmg I happened to notice that this code is nearly identical to the existing `aniviewBidAdapter`. Does this need to be a separate adapter or can it be an alias of `aniview`?

http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.aliasBidder

**Comment by vladi-mmg** [comment]
@msm0504  We are using Aniview as an ad-server and player under our own domain (on a white label agreement). For building an outstream adapter for our own client we used their code as a reference but we need it to be under our name

**Comment by msm0504** [comment]
@vladi-mmg You can be under your own name. The `videofy` bidder code would be added as an alias in the `aniviewBidAdapter`. The adapter code could then be modified to set the domains based on the bidder code passed in on a given request. The existing adapter doesn't need to copied/pasted into a new adapter.

There are other adapters that have similar logic based on aliases. Here's a link to an example: https://github.com/prebid/Prebid.js/blob/master/modules/aolBidAdapter.js#L66

**Comment by vladi-mmg** [comment]
Thanks so much for the response, and accept my apologies in advance for trying to explain why alias's solution is a little less suited to our needs. 
 
We have a really big opportunity with a major publisher that agreed to start with our whiltelabel Aniview player but demands support in additional ad server and player. Using Aniview as an alias will limit us to their product. So we thought to use aniview code just to start our way with a basic working adapter and to upgrade it with additional capabilities on our next adapter version. In this way the adapter won't be similar at all in just a few weeks from now.

**Comment by vladi-mmg** [comment]
Sorry for the urgency but I wanted to ask if you got a chance to see my last reply? 
As I mentioned it's holding us back on an important business opportunity
so i would really appreciate your help here (:

**Comment by msm0504** [comment]
Approved and merged. This adapter will be in the next Prebid release - v3.21.0

**Pull request merged**
