### PR TITLE
Oxxion Analytics Adapter : initial adapter release

### PR DESCRIPTION
**Pull request by matthieularere-msq**
## Type of change
- [ ] New bidder adapter   
- [ ] Other

## Description of change
This PR is a follow up to #9101 : the goal is to rename the already existing bidwatch adapter. To avoid having to wait for a new major release, I duplicated the module and changed its name. I will deprecate the previous module later.

### CODE REVIEW

**Comment by bretg** [comment]
@dgirardi - would your advice in https://github.com/prebid/Prebid.js/pull/9433#pullrequestreview-1268108954 apply here as well to avoid code duplication?

**Comment by ChrisHuie** [comment]
@matthieularere-msq looks like there are a couple of linting errors popping up. If you could fix when you get a chance

**Comment by matthieularere-msq** [comment]
@ChrisHuie one of my colleagues is using my branch to make some modifications on his side, I need to rollback them

**Comment by matthieularere-msq** [comment]
@ChrisHuie for the circleci error, its says "AssertError: expected track to be called 4 times but was called 5 times" on my spec file. However I don't get it, how can it be called 4 times on my environnement and 5 when runned by circleci ?
When I run `gulp test-coverage --file=test/spec/modules/oxxionRtdProvider_spec.js` or `gulp test` commands I have no such issue. How can I find which adapter may be interfering ?

**Comment by ChrisHuie** [comment]
@matthieularere-msq will take a look at this today and try and see what is going on

**Comment by muuki88** [comment]
Docs: https://github.com/prebid/prebid.github.io/pull/4294

**Comment by muuki88** [comment]
Docs: https://github.com/prebid/prebid.github.io/pull/4294

**Review by ChrisHuie — APPROVED** [review]

**Comment by matthieularere-msq** [comment]
Hi,

I didn't understood what happened with the merge and revert, could you explain me this PR status ? 

Thanks

**Comment by matthieularere-msq** [comment]
Hi @ChrisHuie 
Could you please update me on what happening with this PR please ?
Thanks

**Comment by ChrisHuie** [comment]
Hey @matthieularere-msq can you please resubmit off the current master branch. When we originally merged it we had a persistent error in our testing and so we needed to revert to be able to release that week's version of Prebid.

**Comment by matthieularere-msq** [comment]
Hey @ChrisHuie , sure no problem, I just created a new PR. 
I wondered what happened with the merge, thanks for the explanation.

**Pull request merged**
