### PR TITLE
PBJS Core - Validate adunit page position / PBS and RP adapters updates to pass pos in banner and video requests

### PR DESCRIPTION
**Pull request by mmoschovas**
## Type of change

- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- PBJS Core update to include validation of pos value on adunit
- PBS adapter update to include pos value on banner requests (video already included)
- RP adapter update to use pos bidder params.pos or mediaType.banner.pos value in banner request (video already passed properly)

Issue: https://github.com/prebid/Prebid.js/issues/5578

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by ncolletti — APPROVED** [review]
LGTM, could use a docs PR to add a note about this in the Ad Unit Reference page. Also adding another reviewer since this contains core files.

**Review by Fawke — COMMENTED** [review]
Change looks good but we will need a Docs PR as well.

**Comment by bretg** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/2917

**Review by Fawke — APPROVED** [review]
LGTM

**Pull request merged**
