### PR TITLE
SupplyChainObject support and fires a pixel onTimeout

### PR DESCRIPTION
**Pull request by telariaEng**
## Type of change

- [x] Feature
- [x] Code style update (formatting, local variables)

## Description of change

- Enhanced our adapter to handle a SupplyChain Object. Please refer to [SupplyChain for Non-OpenRTB Requests](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/supplychainobject.md#supplychain-for-non-openrtb-requests) for more information
- Fires an event pixel onTimeout
- [Previous PR](https://github.com/prebid/prebid.github.io/pull/1458) Enhanced the adapter to prefer schain properties from validBidRequest

- contact email: github@telaria.com
- [x] official adapter submission

- [Docs PR](https://github.com/prebid/prebid.github.io/pull/1458)

### CODE REVIEW

**Comment by telariaEng** [comment]
@mike-chowla any updates on when this will be merged into master?

**Comment by bretg** [comment]
Please remind us how this one differs from #4137?

**Comment by telariaEng** [comment]
> Please remind us how this one differs from #4137?

According to the comment by @mike-chowla that PR was reverted. And he asked me to create a new PR based on the changes you requested.

**Comment by telariaEng** [comment]
@bretg any updates on when this will be merged with master?

**Comment by bretg** [comment]
I've reached out to @mike-chowla -- the schain changes here seem ok to me on a cursory glance.

**Comment by telariaEng** [comment]
@bretg thank you.

**Pull request merged**
