### PR TITLE
pubgenius: remove video cache key

### PR DESCRIPTION
**Pull request by edmonl**
## Type of change
- [x] Bugfix

## Description of change
Remove video cache key as per comments of #6040 

- contact email of the adapter’s maintainer: meng@pubgenius.io
- [x] official adapter submission

### CODE REVIEW

**Comment by osazos** [comment]
Hi @edmonl, @bretg 
I merged the first PR, sorry for that, I didn't know about the issue mentioned by @bretg.

**Comment by edmonl** [comment]
> Hi @edmonl, @bretg
> I merged the first PR, sorry for that, I didn't know about the issue mentioned by @bretg.

No worries. I just learned it too.

**Review by osazos — APPROVED** [review]

**Comment by jsnellbaker** [comment]
FYI - this change broke one of the pubgenius unit tests - which is now causing unit tests on master to fail.

I have put together another PR to correct the issue.  See #6090

**Comment by edmonl** [comment]
> FYI - this change broke one of the pubgenius unit tests - which is now causing unit tests on master to fail.
> 
> I have put together another PR to correct the issue. See #6090

Thank you very much for doing this for me ! @jsnellbaker

**Pull request merged**
