### PR TITLE
VisibleMeasures Bid Adapter : initial adapter release

### PR DESCRIPTION
**Pull request by VisibleMeasuresHB**
Doc: https://github.com/prebid/prebid.github.io/pull/4312

### CODE REVIEW

**Comment by Rothalack** [comment]
Hey @VisibleMeasuresHB , sorry for the delay.

When testing banner, it works perfect. When I test video or native, I get some errors that I'm not sure of.

When testing with video, I get these erros
Prebidvisiblemeasures ERROR: 
        This bid contains only vastXml and will not work when a prebid cache url is not specified.
        Try enabling prebid cache with pbjs.setConfig({ cache: {url: "..."} });
and
ERROR: Invalid bid from visiblemeasures. Ignoring bid: Video bid does not have required vastUrl or renderer property

With these params:

var adUnits = [{
    code: 'div-gpt-ad-1460505748561-0',
    mediaTypes: {
        video: {
            playerSize: [ [640, 480] ],
            context: 'instream',
            minduration: 5,
            maxduration: 60,
        }
    },
    // Replace this object to test a new Adapter!
    bids: [{
        bidder: 'visiblemeasures',
        params: {
            placementId: "testVideo"
        }
    }]
}];


When testing with Native, I get the error:
Prebid ERROR: Error trying to write ad. No ad for bid response id: 35c9af4b5e0a2f
Tested with these params:
var adUnits = [{
            code: 'div-gpt-ad-1460505748561-0',
            mediaTypes: {
                native: {
                    title: {
                        required: true
                    },
                    body: {
                        required: true
                    },
                    icon: {
                        required: true,
                        size: [64, 64]
                    }
                }
            },
            // Replace this object to test a new Adapter!
            bids: [{
                bidder: 'visiblemeasures',
                params: {
                    placementId: "testNative"
                }
            }]
}];


Let me know if you need any more info to reproduce these. I am just using the simple hello_world.html test page, nothing fancy.

**Comment by VisibleMeasuresHB** [comment]
Hey, @Rothalack, I tested it, and video and native works for me.
image
image
image
I also just used hello_world.html test page with adUnits from adapter, and everything seems to be working fine.
Can you please provide me more info about it, if it still doesn't work?

**Comment by Rothalack** [comment]
Hey @VisibleMeasuresHB , sorry I should have added that these errors are shown in the console when you add ?pbjs_debug=true to the URL of the page.

**Review by Rothalack — APPROVED** [review]
Looks good

**Pull request merged**
