### PR TITLE
Add user sync for brainyAdapter

### PR DESCRIPTION
**Pull request by brainymisio**
## Type of change

- [x] Feature

## Description of change
We add User-sync feature for braint Adapter and test cases.

### CODE REVIEW

**Comment by Shota-Moirya** [comment]
@idettman @jaiminpanchal27  could you please review the PR and let us know?

**Comment by brainymisio** [comment]
@idettman could you please review the PR and let us know?

**Comment by brainymisio** [comment]
@jaiminpanchal27 could you please review the PR and let us know?

**Comment by brainymisio** [comment]
@jsnellbaker could you please review the PR and let us know?

**Comment by jsnellbaker** [comment]
@brainymisio I'll take a look at this today and follow-up.

**Pull request merged**
