### PR TITLE
handle pubmatic targeting key value pairs if in DFP GPT format

### PR DESCRIPTION
**Pull request by tr-coull**

### CODE REVIEW

**Comment by mkendall07** [comment]
@tr-coull 
Thanks for the PR. Is there a way we can validate this?

**Comment by tr-coull** [comment]
Unfortunately I do not yet have a working test available externally I can send. The changes are:

1. Protocol-less url to pubmatic would not request when prebid.js run in an injected iframe in Chrome. Hardcode https does the request.
2. Prebid.js was expecting response from gads.pubmatic.com in "Legacy DART" format (see pages 10 & 11 of attached pubmatic doc). We are expecting the response in "DFP GPT" format, so the change detects this and handles both to set the targeting correctly.

Sorry but it may be a few weeks before I have a working test page I can demo on.
[Decision Manager Standard 2.4 Technical Integration Guide_1.pdf](https://github.com/prebid/Prebid.js/files/142577/Decision.Manager.Standard.2.4.Technical.Integration.Guide_1.pdf)

**Comment by protonate** [comment]
This looks ready to merge. I'll add a commit to this PR for code style and flatten the two commits from @tr-coull.

One minor note from applying code style is to prefer `decodeURI` or `decodeURIComponent` as `unescape` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape). See [line 109](https://github.com/tr-coull/Prebid.js/blob/master/src/adapters/pubmatic.js#L109) and [line 110](https://github.com/tr-coull/Prebid.js/blob/master/src/adapters/pubmatic.js#L110).

**Comment by protonate** [comment]
Merged with 56d5866664e84d873c6eee6e045d18b695a87e0e, closing.

A [prior change](https://github.com/prebid/Prebid.js/commit/69f5b7d1a782487e2f54451ecbfe078eab8dc4a0) was inadvertently included in the merge, but removed with f778cd5241a1401f70842b633dc6b96855df3361. However the attribution was switched to @mkendall07. We will correct this and change attribution to @tr-coull in the release notes.

**Comment by protonate** [comment]
@tr-coull please provide test params for end-to-end tests. As more adapters are added and the project grows having sufficient test coverage is a priority.

**Pull request closed without merging**
