### PR TITLE
windtalker adapter for prebid 2x

### PR DESCRIPTION
**Pull request by degroat**
## Type of change

- [ X] New bidder adapter

## Description of change
Prebid adapter for Windtalker.  NOTE -- Will update other pull request for master branch when our 3x adapter is ready.

- test parameters for validating bids
```
{
  bidder: 'windtalker',
  params: {
           "pubId":"187046"
           ,"siteId":"10"
           ,"size":"300x250"
           ,"placementId":"456"
  }
}
```

- contact email of the adapter’s maintainer: corbin@windtalker.io
- [X ] official adapter submission

### CODE REVIEW

**Comment by bretg** [comment]
Not pleased to be adding a new adapter to 2.x. @sumit116 - if you have cycles to look this over to help these guys, great. Otherwise, their publishers will need to upgrade to 3.x.

**Comment by bretg** [comment]
PR for 3.x adapter is https://github.com/prebid/Prebid.js/pull/4837

**Comment by sumit116** [comment]
> Not pleased to be adding a new adapter to 2.x. @sumit116 - if you have cycles to look this over to help these guys, great. Otherwise, their publishers will need to upgrade to 3.x.

Sure @bretg. I can help them with this, but I am not sure how would they handle their publishers who are still following 2.x if we don't keep the legacy branch any more?

@degroat, can you go through http://prebid.org/blog/pbjs-3 and let me know if you have any questions? Its a documentation for adapters to upgrade to Prebid 3.x.

**Comment by degroat** [comment]
@sumit116 We're clear on what needs to be done for 3.X upgrade and we'll be submitting an update for that.    We just have publishers who are asking for 2.x support and, yes, they should upgrade.  Unfortunately we can't force that.  Maybe I'm missing something, but haven't ten adapters have been updated on this branch in the last month?

**Comment by jaiminpanchal27** [comment]
@degroat We only maintain previous major versions for minimum 30 days. See details here https://github.com/prebid/Prebid.js/blob/master/PREBID_VERSIONING_DEPRECATION.md

We released 3.0 on Dec 11, 2019

**Pull request closed without merging**
