### PR TITLE
Platform.io video support

### PR DESCRIPTION
**Pull request by varashellov**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added support for video

- test parameters for validating bids
```
  {
    bidder: 'platformio',
    params: {
            pubId: '29521',
            siteId: '26049',
            size: '640X480',
            placementId: '123',
    }
  }
```

- contact email of the adapter’s maintainer
- [x] official adapter submission

### CODE REVIEW

**Comment by varashellov** [comment]
Docs https://github.com/prebid/prebid.github.io/pull/688

**Comment by varashellov** [comment]
Hello @jsnellbaker 
Thanks for the quick response.
Please check hello_world page https://github.com/varashellov/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html

**Comment by jsnellbaker** [comment]
Hi @varashellov, thanks for providing the sample page.  I found the issues I made during the banner and native testing.  The ads are delivering fine now.  

Can you back out the change to the `hello_world.html` page in this PR?  We should be good to merge once that's done.

**Comment by varashellov** [comment]
@jsnellbaker 
Uploaded the default file
Thanks

**Comment by jsnellbaker** [comment]
@varashellov Can you just remove the file from the PR entirely?  That would be better than uploading the same version of the file.  Thanks.

**Comment by jsnellbaker** [comment]
Hi @varashellov The last commit actually deletes the file instead of removing it from the PR.  I checked internally with some other folks, and they actually recommended to just re-add the file back into the PR at this point since it would be the easiest way to fix it.  

When you have the chance, can you please add the `master` version of this file to the PR?  

Thanks, and sorry for the back and forth.

**Pull request merged**
