### PR TITLE
Modify bid param checking of bridgewellBidAdapter

### PR DESCRIPTION
**Pull request by rigelbibi**
## Type of change

- [ x] Feature

## Description of change
Modify bid param checking of bridgewellBidAdapter

### CODE REVIEW

**Comment by smenzer** [comment]
can you please add test coverage for this? then it can be merged

**Comment by rigelbibi** [comment]
> can you please add test coverage for this? then it can be merged

I made some update and added test cases. please review again.
Thanks.

**Review by smenzer — APPROVED** [review]
Thanks for adding the tests. LGTM

**Comment by smenzer** [comment]
Sorry, I didn't realize this was against the 3.27.x legacy branch. you need to put in a PR against master (v4.x)

**Comment by rigelbibi** [comment]
> Sorry, I didn't realize this was against the 3.27.x legacy branch. you need to put in a PR against master (v4.x)

Sorry, I didn't explain clearly. 
Can we update our adapter for prebid.js 3.27.x ?
Or the 3.27.x is frozen and is not be modified anymore ?

**Comment by smenzer** [comment]
@rigelbibi no sorry, we don't plan to do any more releases to the 3.x branch.

**Comment by rigelbibi** [comment]
> @rigelbibi no sorry, we don't plan to do any more releases to the 3.x branch.

It's ok. Thanks for the information.

**Pull request merged**
