### PR TITLE
cpex Id System: Fixes and cleanup, adds eids, changes cookie name

### PR DESCRIPTION
**Pull request by EskelCz**
## Type of change
- [X] Bugfix
- [X] Code style update (formatting, local variables)

## Description of change
- `getId` has to return key `id` to trigger passing the id to bidders
- removed unused params
- added eids version
- renamed cookie to not be mistaken with some Chinese id
- not adding the id when cookie is not found
- updated tests to match the changes

### CODE REVIEW

**Comment by patmmccann** [comment]
Please note test failures

**Comment by EskelCz** [comment]
@jlukas79 Can we please get an estimate when this can be merged? It's a small change concerning just our code. Thanks

**Comment by EskelCz** [comment]
@patmmccann Please is there anyone else who can do the review? Should be no work at all I think.

**Comment by patmmccann** [comment]
Looks almost done, could you add tests to eids spec file?

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
