### PR TITLE
Kueez RTB Bid Adapter: added support for video media type

### PR DESCRIPTION
**Pull request by uditalias**
## Type of change

- [x] Feature

## Description of change

Added support for video media types

### CODE REVIEW

**Comment by uditalias** [comment]
@lksharma Let me know if you need anything from my end

**Comment by muuki88** [comment]
Docs PR: https://github.com/prebid/prebid.github.io/pull/4204

**Comment by uditalias** [comment]
@lksharma ? This PR is 21 days old, if something's not right please share, thanks.

**Comment by lksharma** [comment]
Thank you for your patience, @uditalias. The changes look good to me.

**Review by lksharma — APPROVED** [review]
LGTM

**Pull request merged**
