### PR TITLE
adding local node version >8.9 to <12.0.0 to avoid breaking build by fibers 3.1.1

### PR DESCRIPTION
**Pull request by renebaudisch**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
npm i fails with node >=12 because fibers 3.1.1 doesn't support it. This will install a local node version that fits fibers on npm i.

### CODE REVIEW

**Comment by renebaudisch** [comment]
@jaiminpanchal27 sorry, but then go on and do it!
A not known error like "fibers is not working" also is just confusing and doesn't help.

The problem is there since almost a year, regarding Issue https://github.com/prebid/Prebid.js/issues/3878

and over month no one was reacting!
It made me think you will never fix this at all and cannot update fibers/moha...

But maybe this will help finally
https://github.com/prebid/Prebid.js/pull/5128
But I'm familiar with your build, I do not know if you can update mocha without problems.

But every build process at the moment is a pain when Node 12 is installed!

**Comment by renebaudisch** [comment]
Here
https://github.com/prebid/Prebid.js/pull/4820
you told me you will not update to node 12 because it will break, now you will update after I found a soluztion that doesn't need an update.

However please finally fix this problem!

**Comment by jaiminpanchal27** [comment]
@renebaudisch My colleague is on to this one and will put up a PR in couple of days to fix this one with other webdriver changes.

**Comment by renebaudisch** [comment]
Using v3.20 I still get a n error on npm i from fibers 3.1.1.

Using
`gulp build --modules=prebidAdaptors.json `
afterwards succeeds, but is it operating fine this way?

Maybe you could have a look once more?

**Comment by maplefu0601** [comment]
I'm using node v12.16.1. There's no issue at all when running in local with meteor run --production, but when deploying to AWS using mup deploy with abernix/meteord:node-12.16.1-base, the deployment fails. It has the following errors:

 Prepare Bundle: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
	
	      ------------------------------------STDOUT------------------------------------
	      ot a member of 'uni'
	    target->Set(uni::NewLatin1Symbol(isolate, "Fiber"), fn);
	                ^~~
	../src/fibers.cc: At global scope:
	../src/fibers.cc:901:11: error: variable or field 'init' declared void
	 void init(Handle<Object> target) {
	           ^~~~~~
	../src/fibers.cc:901:11: error: 'Handle' was not declared in this scope
	../src/fibers.cc:901:24: error: expected primary-expression before '>' token
	 void init(Handle<Object> target) {
	                        ^
	../src/fibers.cc:901:26: error: 'target' was not declared in this scope
	 void init(Handle<Object> target) {
	                          ^~~~~~
	../src/fibers.cc: In instantiation of 'void uni::Return(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, uni::GetterCallbackInfo) [with T = v8::Object; uni::GetterCallbackInfo = v8::PropertyCallbackInfo<v8::Value>]':
	../src/fibers.cc:814:45:   required from here
	../src/fibers.cc:185:3: warning: 'void v8::ReturnValue<T>::Set(const v8::Persistent<S>&) [with S = v8::Object; T = v8::Value]' is deprecated: Use Global<> instead [-Wdeprecated-declarations]
	   info.GetReturnValue().Set(handle);
	   ^~~~
	In file included from /root/.cache/node-gyp/12.16.1/include/node/node.h:63:0,
	                 from ../src/coroutine.h:1,
	                 from ../src/fibers.cc:1:
	/root/.cache/node-gyp/12.16.1/include/node/v8.h:10424:6: note: declared here
	 void ReturnValue<T>::Set(const Persistent<S>& handle) {
	      ^~~~~~~~~~~~~~
	fibers.target.mk:120: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
	make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
	make: Leaving directory '/built_app/programs/server/node_modules/fibers/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
	gyp ERR! System Linux 5.4.0-1029-aws
	gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
	gyp ERR! cwd /built_app/programs/server/node_modules/fibers
	gyp ERR! node -v v12.16.1
	gyp ERR! node-gyp -v v5.0.7
	gyp ERR! not ok 
	node-gyp exited with code: 1
	Please make sure you are using a supported platform and node version. If you
	would like to compile fibers on this machine please make sure you have setup your
	build environment--
	Windows + OS X instructions here: https://github.com/nodejs/node-gyp
	Ubuntu users please run: `sudo apt-get install g++ build-essential`
	RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
	Alpine users please run: `sudo apk add python make g++`
	sh: 1: nodejs: not found
	npm ERR! code ELIFECYCLE
	npm ERR! syscall spawn
	npm ERR! file sh
	npm ERR! errno ENOENT
	npm ERR! fibers@3.1.1 install: `node build.js || nodejs build.js`
	npm ERR! spawn ENOENT
	npm ERR! 
	npm ERR! Failed at the fibers@3.1.1 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2021-02-13T00_06_48_966Z-debug.log

**Comment by renebaudisch** [comment]
That's why I favored >8.9 to <12.0.0 as fibers 3.1.1 isn't compatible with node >= 12.0.0 and so also fibers used in webdriver module has to be updated and using node < 12.0.0 haven't had that dependencies.
But this has been marked as fixed by upgrading prebid to be compatible to node >= 12, isn't it?

**Pull request closed without merging**
