### PR TITLE
NoBid Bid Adapter : add support for first party user id

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support for First Party User ID in NoBid Bid Adapter.

### CODE REVIEW

**Comment by redaguermas** [comment]
Hello team,
I am seeing an error unrelated to our Adapter. Can you help us with this error?

**Comment by redaguermas** [comment]
Hello @Rothalack,
Do you have an update for this PR?

**Review by Rothalack — APPROVED** [review]
Good to go

**Comment by patmmccann** [comment]
@redaguermas we had to revert this

**Pull request merged**
