### PR TITLE
RevContent adapter: Allow customization for bidfloor param

### PR DESCRIPTION
**Pull request by AzizSaleh**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
* Add bidfloor custom param
* Only return 1 ad when requested

- test parameters for validating bids
```
{
  bidder: 'revcontent',
  params: {
      apiKey: '8a33sdfsdfdsfsdfssss544f8sdfsdfsdfd3b1c',  // Required
      userId: 69565,                                      // Required
      widgetId: 599995,                                   // Optional
      domain: 'test.com',                                 // Optional - Default referral hostname
      bidfloor: 0.2                                            // Optional - Bid Floor - Default 0.1
  }
}
```

Test page: /integrationExamples/gpt/revcontent_example.html

contact email of the adapter’s maintainer: aziz@revcontent.com
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/: https://github.com/prebid/prebid.github.io/pull/1705

### CODE REVIEW

**Comment by AzizSaleh** [comment]
Test results: 

Screenshot_2020-01-10 Code coverage report for modules revcontentBidAdapter js

**Comment by bretg** [comment]
I see -- your module wasn't released yet, so the docs hadn't merged.

So please add the requested unit tests for the bidfloor param and we can get this one merged for next week's release.

**Comment by AzizSaleh** [comment]
Hi @bretg That was a good idea, I have added the test for both custom/default bidfloors.

Thanks!

**Comment by bretg** [comment]
I opened a CircleCI support ticket to get to the bottom of why some PRs (like this one) end up outside of Prebid's CircleCI account.

The response was:

```
It's likely that the users in questions are following their own project on our end, rather than the
open-source project - this will cause builds to trigger under their account rather than yours.
Asking the users to unfollow the project under their account in CircleCI and instead follow the
"real" project should resolve this issue.
```

On your CircleCI project's screen, click "unfollow" on the Prebid.js row:

Screen Shot 2020-01-21 at 9 25 12 AM

**Comment by AzizSaleh** [comment]
@bretg Not sure how that work. I was indeed following that forked Project:

Screen Shot 2020-01-21 at 7 14 10 PM (3)
Screen Shot 2020-01-21 at 7 12 53 PM (3)

I did unfollow, but not sure how that will help since circleci automatically picked up the forked branch on their own (when I enabled it it didn't give me an option to select which repo to run from).

**Comment by bretg** [comment]
Maybe you need to push another change to your fork to get the system to kick off another build and this time see that you're not following your own fork?

**Comment by bretg** [comment]
@AzizSaleh - good news is that the tests are running on Prebid's CircleCI now. The bad news is that it's failing on the linter -- please fix the indentation in your adapter.

**Comment by AzizSaleh** [comment]
@bretg What exactly are the indentation rules? I currently have set it to 4 spaces per tab. I ran `npx eslint modules/revcontentBidAdapter.js` which didn't show any errors (what would I run it locally so that I can see what you are seeing)? 

Thanks!

**Comment by bretg** [comment]
Note that it's the unit test file that has the issue. You can see the error by following the "details" link next to the ci/circleci row below.

The policy is 2-spaces per level.

```
#!/bin/bash -eo pipefail
gulp test --browserstack --nolintfix
[14:27:22] Using gulpfile ~/Prebid.js/gulpfile.js
[14:27:22] Starting 'test'...
[14:27:22] Starting 'clean'...
[14:27:22] Finished 'clean' after 46 ms
[14:27:22] Starting 'lint'...
[14:27:45] 
/home/circleci/Prebid.js/test/spec/modules/revcontentBidAdapter_spec.js
    9:1  error  Expected indentation of 2 spaces but found 4    indent
   10:1  error  Expected indentation of 2 spaces but found 4    indent
   12:1  error  Expected indentation of 2 spaces but found 4    indent
   13:1  error  Expected indentation of 4 spaces but found 8    indent
   14:1  error  Expected indentation of 6 spaces but found 12   indent
```

**Comment by AzizSaleh** [comment]
@bretg I was able to fix the indentation issue by running `gulp test --fix`. Committed the update. Now running your command does not show the indentation issue (before the fix it was). It is still showing browserstack errors for me (assuming because I don't have the credentials).

**Comment by bretg** [comment]
Ok - we build succeeded. I re-reviewed and the unit test changes were tiny this time, so we're good here. Merging.

**Pull request merged**
