### PR TITLE
2 sizes added to Rubicon adapter

### PR DESCRIPTION
**Pull request by aurelienjoneau**
Added 2 new sizes to Rubicon adapter : 1000x300 & 320x100

### CODE REVIEW

**Comment by bretg** [comment]
@mkendall07 - these are valid sizes. Thanks for checking.

**Comment by mkendall07** [comment]
@bretg 
Thanks. Any more sizes that should be in here?

**Comment by bretg** [comment]
There are over 100 sizes we _could_ add to the list, but would prefer not to enlarge the code unnecessarily. We added the top 20 (97th percentile) a while back. 320x100 has recently moved into that top 20, but 1000x300 is well down the long tail.

**Comment by aurelienjoneau** [comment]
Hey guys, that's because top sizes can change from countries to countries. How about asking prebid users to define their own size list in the bid configuration ? That would ensure no future website using specific sizes would get a problem with missing sizes.

**Comment by mkendall07** [comment]
Thanks @bretg for clarifying.

@aurelienjoneau that makes sense this is country specific. I'm not sure it's ideal to include duplicate size data with each placement, so I think we'll hold off on that for now.

**Pull request merged**
