### PR TITLE
Incrx Bid Adapter : add incrementX banner and vast 

### PR DESCRIPTION
**Pull request by Prebid-Vertoz**
Adding IncrementX Banner and VAST(Outstream) Adapter

### CODE REVIEW

**Comment by Prebid-Vertoz** [comment]
@patmmccann May I kindly ask if there are any updates on the PR or  anything is missing from our end,please let us know?

**Comment by Prebid-Vertoz** [comment]
Hello @ChrisHuie,
Hope you are doing well!

Could you please let us know when our adapter goes live or if there is anything pending on our side.

**Comment by Rothalack** [comment]
Apologies for the delay, I'm reviewing this now. I'm attempting to test and am confused by the error I'm getting. I'm trying to test with the required param you have listed, placementId, but I still get errors saying that I'm missing params for your bidder.

Prebidincrementx ERROR: Invalid bid from incrementx. Ignoring bid: Bidder incrementx is missing required params. Check http://prebid.org/dev-docs/bidder-adapter-1.html for list of params.

I've tried to verify reading your code and I don't see another required param other than placementId. I tried testing with size or sizes as well, but that's not working either. I thought maybe it's a misbehavior of only attempting Video ads, but it's happening for both banner and video. Somethings not right. Maybe there's something I'm missing.

**Comment by Rothalack** [comment]
Another note, you're missing your .md file along side your BidAdapter.js in /modules. You can look in /modules to see the .md everyone else has. Should be easy to get that up.

**Comment by Prebid-Vertoz** [comment]
> Apologies for the delay, I'm reviewing this now. I'm attempting to test and am confused by the error I'm getting. I'm trying to test with the required param you have listed, placementId, but I still get errors saying that I'm missing params for your bidder.
> 
> Prebidincrementx ERROR: Invalid bid from incrementx. Ignoring bid: Bidder incrementx is missing required params. Check http://prebid.org/dev-docs/bidder-adapter-1.html for list of params.
> 
> I've tried to verify reading your code and I don't see another required param other than placementId. I tried testing with size or sizes as well, but that's not working either. I thought maybe it's a misbehavior of only attempting Video ads, but it's happening for both banner and video. Somethings not right. Maybe there's something I'm missing.

Hello @Rothalack,

Thank you for response. The placementId is indeed the only required parameter for both banner and video ads. I have tested this with updated IncrementX Adapter on my end and did not encounter any errors with the given test pages. You can verify the implementation using the following links:

For video ads: [Video Test Page](https://textfeed.howgeneric.com/Test/pbjs_ix.html)
For banner ads: [Banner Test Page](https://textfeed.howgeneric.com/hb.html)
Please check these test pages and let me know if the issue persists or if there are any other parameters you believe might be missing.
Let me know, if anything missing from our end.

**Comment by Prebid-Vertoz** [comment]
> Another note, you're missing your .md file along side your BidAdapter.js in /modules. You can look in /modules to see the .md everyone else has. Should be easy to get that up.

I have added the incrxBidAdapter.md file

**Comment by Rothalack** [comment]
Thank you for the test pages. I can see video working now, I was able to verify this in a local test as well. However, for your test page for banner I am seeing the same issue as when I test locally. You can see it in the console if you add ?pbjs_debug=true

https://textfeed.howgeneric.com/hb.html?pbjs_debug=true

prebid.js:12  Prebidincrementx ERROR: Invalid bid from incrementx. Ignoring bid: Bidder incrementx is missing required params. Check http://prebid.org/dev-docs/bidder-adapter-1.html for list of params.

It's the same behavior I see when testing locally. I really don't understand how, because again looking at your code, you're only asking for placementId. Something else is going on here. Maybe it's unable to get placementId as intended, failing somewhere in the code we haven't noticed yet.

**Comment by Prebid-Vertoz** [comment]
> Thank you for the test pages. I can see video working now, I was able to verify this in a local test as well. However, for your test page for banner I am seeing the same issue as when I test locally. You can see it in the console if you add ?pbjs_debug=true
> 
> https://textfeed.howgeneric.com/hb.html?pbjs_debug=true
> 
> prebid.js:12 Prebidincrementx ERROR: Invalid bid from incrementx. Ignoring bid: Bidder incrementx is missing required params. Check http://prebid.org/dev-docs/bidder-adapter-1.html for list of params.
> 
> It's the same behavior I see when testing locally. I really don't understand how, because again looking at your code, you're only asking for placementId. Something else is going on here. Maybe it's unable to get placementId as intended, failing somewhere in the code we haven't noticed yet.

Hi @Rothalack 
I wanted to let you know that I have identified and resolved the issue we were facing. Could you please check the changes and let me know if everything is in order or if there are any additional requirements?

**Review by Rothalack — APPROVED** [review]
Looks good, working for me now!

**Pull request merged**
