### PR TITLE
NoBid Bid Adapter: support for Floors

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support for Floors for the NoBid Bid Adapter.

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@redaguermas looks like you included your code editor files. If you could please remove those 🙏

**Comment by redaguermas** [comment]
I only checked in 3 files: nobidBidAdapter.js, nobidBidAdapter.md and nobidBidAdapter_spec.js.
I am not seeing other files in "fe57afa"

**Comment by ChrisHuie** [comment]
> I only checked in 3 files: nobidBidAdapter.js, nobidBidAdapter.md and nobidBidAdapter_spec.js. I am not seeing other files in "fe57afa"

🤷‍♂️ Code editors sometimes do their own things so not sure the issue. This pr has 9 files changed though.

**Comment by redaguermas** [comment]
Sorry about that. I see now. It's strange how these files got in. I removed them. Thank you for bringing that to my attention.

**Comment by redaguermas** [comment]
Hello.
Any update on this?

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/4406

**Comment by redaguermas** [comment]
Hello,
My business team is asking about this update. Can you please let me know the status.
-Regards

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
