### PR TITLE
LunaMedia Adapter

### PR DESCRIPTION
**Pull request by trchandraprakash**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by trchandraprakash** [comment]
Hi Guys,

Can you please let me know if all good here and when adapter will get merged.

Thanks & Regards
Chandra Prakash

**Comment by trchandraprakash** [comment]
Hi Please find docs below
https://github.com/prebid/prebid.github.io/pull/1925

**Comment by trchandraprakash** [comment]
Hi Guys, Can you please let me know if all good here and when adapter will get available for client.

**Comment by trchandraprakash** [comment]
Hi Guys, Our clients eagerly waiting for adapter, can you please let me know if anything else pending from my side.

**Comment by trchandraprakash** [comment]
I tested those earlier, can you try test few times, you should see ads. 

While i am trying to setup prebid.js environment again to test, when i run "gulp serve" i get following error, and not sure why its not compiling like earlier.
i ran following earlier
$ git clone https://github.com/prebid/Prebid.js.git
$ cd Prebid.js
$ npm install

/Users/chandraprakash/Desktop/prebid/Prebid.js/modules/sublimeBidAdapter.js
  4:1  error  import "../src/url.js" cannot be resolved  prebid/validate-imports

✖ 1 problem (1 error, 0 warnings)

[15:05:02] 'lint' errored after 19 s
[15:05:02] ESLintError in plugin "gulp-eslint"
Message:
    Failed with 1 error
Details:
    domainEmitter: [object Object]
    domainThrown: false

[15:05:02] 'serve' errored after 19 s

Any help would be great.

**Comment by akovalnj** [comment]
Still getting 204s for both banner and video event though I tried 20 times.  

There were some fixes checked in recently that may solve your build issue.  Please do another checkout and try the build again.

**Comment by akovalnj** [comment]
The 204 issue was on my end.   I needed to use a different IP alias other than localhost.    Consistenly getting 200s now.   

But noticed one other thing.   There is a function to get the referrer when it seems that you could just get the value from bidderRequest.refererInfo.referer.   Do you need that extra layer?

**Comment by trchandraprakash** [comment]
Yes, lets keep that function for now.

**Pull request merged**
