### PR TITLE
Topics Fpd Module: Add vidazoo bidder iframe

### PR DESCRIPTION
**Pull request by saar120**
## Type of change

- [X] Feature
## Description of change

Added Vidazoo bidder to topicsFpdModule.

### CODE REVIEW

**Comment by saar120** [comment]
@patmmccann @ChrisHuie
Can we merge this please?

**Comment by patmmccann** [comment]
we're still thinking about if we want to allow nonmember companies in a vendorless module

**Comment by bgoldin-vidazoo** [comment]
> we're still thinking about if we want to allow nonmember companies in a vendorless module

Hi, nice to meet you! Hivestack are prebid members. Them and us are all part of the same company - Perion Network. Might this suffice to include us in the module as well?

**Comment by bgoldin-vidazoo** [comment]
@patmmccann Hi Patrick, sure you're busy but would be grateful for your help here. Can we merge this in light that we do have a membership through our sister business unit Hivestack?

**Comment by patmmccann** [comment]
We discussed in committee. We're going to remove everyone from the Topics module and require publishers configure each bidder in Prebid 9. Merging this for now but it will be removed shortly with everyone else

**Comment by patmmccann** [comment]
oh, needs conflicts resolved

**Review by patmmccann — APPROVED** [review]
Merging for now, will remove with everyone else for prebid 9

**Comment by saar120** [comment]
> oh, needs conflicts resolved

@patmmccann resolved

**Pull request merged**
