### PR TITLE
use bid request bidId for sovrn imp.id

### PR DESCRIPTION
**Pull request by protonate**

### CODE REVIEW

**Comment by protonate** [comment]
@mkendall07 please review & test

**Comment by mkendall07** [comment]
@cliffliang & @pdramos1 
It looks like our test placement is no longer receiving bids (tagid: "315045") - can you guys activate it again so we can validate the fix. Looks like the adapter is currently broken in master. Thanks!

**Comment by tcasson303** [comment]
We've updated 315045 so it pulls back a $0.01 CPM bid when called from any domain.

**Comment by mkendall07** [comment]
@tcasson303 

Thanks! Seeing bids back now. Small issue, not a blocker, the creative that comes back serves from this URL, which appears to be internal only http://www.lijit.com/res/images/houseart/2093_9-1394142045.gif.

**Comment by tcasson303** [comment]
Updated image to http://ap.lijit.com/www/images/sovrn-house-banner2-1.gif

**Pull request merged**
