### PR TITLE
PubMatic supporting updated Criteo User Id module

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [X] Feature

## Description of change
PubMatic supporting updated Criteo User Id module

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @bretg and @robertrmartinez ,
Could you please review this PR?

**Comment by pm-harshad-mane** [comment]
Hello @bretg and @robertrmartinez ,
Could you please review this PR?

**Comment by pm-harshad-mane** [comment]
Hello @robertrmartinez ,
Could you please review this?

**Comment by robertrmartinez** [comment]
Yeah was planning on getting to it this AM!

**Comment by pm-harshad-mane** [comment]
Thank you @robertrmartinez !!

**Pull request merged**
