### PR TITLE
Add new adapter - adWMGBidAdapter

### PR DESCRIPTION
**Pull request by nyakove**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Add new Bidder - adWMG Bid Adapter

- test parameters for validating bids
```
{
  bidder: 'adWMG',
  params: {
        publisherId: '5cebea3c9eea646c7b623d5e',
        IABCategories: ['IAB1', 'IAB5']
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by jsnellbaker — CHANGES_REQUESTED** [review]
Hi @nyakove 

Thank you for submitting this new adapter.

When I tried to load the test bid params on the `integrationExamples/gpt/hello_world.html` test page, I was seeing some strange errors which prevented the ad from properly rendering.

I attached a screenshot of the debug messages:
Screen Shot 2020-12-02 at 11 28 07 AM

While it looks like the `Invalid or unexpected token` error is coming from the `creative.js` file, I think it's just an exception that's being raised from a script inside the ad's creative code - specifically from `https://js.koneomobiledsp.com/v1.2.0-min.js`.

For the 404 error, the URL that was trying to load looked like:
```
http://test.localhost:9999/integrationExamples/gpt/undefined?undefined&ud=eyJlcnIiOnt9LCJzdyI6MTY4MCwic2giOjEwNTAsIm9ycyI6MCwibmFnIjoiTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTRfNikgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzg2LjAuNDI0MC4xOTggU2FmYXJpLzUzNy4zNiIsInZpYnIiOjEsImZmIjowLCJscyI6MSwidHMiOmZhbHNlLCJibCI6MTAwLCJyZWYiOiIiLCJjbGQiOjI0LCJweHIiOjIsIm5hdnBsYXQiOiJNYWNJbnRlbCIsImh3Y29uIjo4LCJ0em8iOjMwMCwic2VzcyI6dHJ1ZSwiaWR4ZGIiOnRydWUsIm9wZGIiOnRydWUsImhscmVzIjpmYWxzZSwiaGxicndzciI6ZmFsc2UsImhsb3MiOmZhbHNlLCJqc2ZvbnQiOlsiQW5kYWxlIE1vbm8iLCJBcmlhbCIsIkFyaWFsIEJsYWNrIiwiQXJpYWwgSGVicmV3IiwiQXJpYWwgTmFycm93IiwiQXJpYWwgUm91bmRlZCBNVCBCb2xkIiwiQXJpYWwgVW5pY29kZSBNUyIsIkJvb2sgQW50aXF1YSIsIkJvb2ttYW4gT2xkIFN0eWxlIiwiQ2FsaWJyaSIsIkNhbWJyaWEiLCJDYW1icmlhIE1hdGgiLCJDZW50dXJ5IiwiQ2VudHVyeSBHb3RoaWMiLCJDZW50dXJ5IFNjaG9vbGJvb2siLCJDb21pYyBTYW5zIE1TIiwiQ29uc29sYXMiLCJDb3VyaWVyIiwiQ291cmllciBOZXciLCJHZW5ldmEiLCJHZW9yZ2lhIiwiSGVsdmV0aWNhIiwiSGVsdmV0aWNhIE5ldWUiLCJJbXBhY3QiLCJMdWNpZGEgQnJpZ2h0IiwiTHVjaWRhIENhbGxpZ3JhcGh5IiwiTHVjaWRhIENvbnNvbGUiLCJMdWNpZGEgRmF4IiwiTFVDSURBIEdSQU5ERSIsIkx1Y2lkYSBIYW5kd3JpdGluZyIsIkx1Y2lkYSBTYW5zIiwiTHVjaWRhIFNhbnMgVHlwZXdyaXRlciIsIkx1Y2lkYSBTYW5zIFVuaWNvZGUiLCJNaWNyb3NvZnQgU2FucyBTZXJpZiIsIk1vbmFjbyIsIk1vbm90eXBlIENvcnNpdmEiLCJNUyBHb3RoaWMiLCJNUyBQR290aGljIiwiTVMgUmVmZXJlbmNlIFNhbnMgU2VyaWYiLCJQYWxhdGlubyIsIlBhbGF0aW5vIExpbm90eXBlIiwiVGFob21hIiwiVGltZXMiLCJUaW1lcyBOZXcgUm9tYW4iLCJUcmVidWNoZXQgTVMiLCJWZXJkYW5hIiwiV2luZ2RpbmdzIiwiV2luZ2RpbmdzIDIiLCJXaW5nZGluZ3MgMyJdLCJyZWdwbHVnIjpbIkNocm9tZSBQREYgUGx1Z2luOjpQb3J0YWJsZSBEb2N1bWVudCBGb3JtYXQ6OmFwcGxpY2F0aW9uL3gtZ29vZ2xlLWNocm9tZS1wZGZ+cGRmIiwiQ2hyb21lIFBERiBWaWV3ZXI6Ojo6YXBwbGljYXRpb24vcGRmfnBkZiIsIk5hdGl2ZSBDbGllbnQ6Ojo6YXBwbGljYXRpb24veC1uYWNsfixhcHBsaWNhdGlvbi94LXBuYWNsfiJdLCJ0cm1zIjpbMCwwLDAsMSwwLDEsMCwwXX0=
```
I think this is related to or a side-effect of the `invalid token` error, though I can't confirm for sure.  Can you please take a look to see why these errors may be happening?

Additionally, when I tried to run the unit tests locally, I saw a few consistent errors.  I copied them below, can you please take a look at these as well?
```
FAILED TESTS:
  adWMGBidAdapter
    parseUserAgent
      ✖ should return correct OS name
        HeadlessChrome 87.0.4280 (Mac OS X 10.14.6)
      AssertionError: expected 'iOS' to equal 'Windows'

      + expected - actual

      -iOS
      +Windows
      
    at Context.<anonymous> (webpack:///test/spec/modules/adWMGBidAdapter_spec.js:68:36 <- test/test_index.js:72057:82)


      ✖ should return correct OS version
        HeadlessChrome 87.0.4280 (Mac OS X 10.14.6)
      AssertionError: expected '7.12' to equal '10.0'

      + expected - actual

      -7.12
      +10.0
      
    at Context.<anonymous> (webpack:///test/spec/modules/adWMGBidAdapter_spec.js:73:37 <- test/test_index.js:72061:83)


    getUserSyncs
      ✖ should register iframe sync when only iframe is enabled
        HeadlessChrome 87.0.4280 (Mac OS X 10.14.6)
      AssertionError: expected 'https://rtb.adwmg.com/cphb.html?' to include 'http://rtb.adwmg.com/cphb.html?'

      + expected - actual

      
    at Context.<anonymous> (webpack:///test/spec/modules/adWMGBidAdapter_spec.js:259:28 <- test/test_index.js:72228:74)


      ✖ should register iframe sync when iframe and image are enabled
        HeadlessChrome 87.0.4280 (Mac OS X 10.14.6)
      AssertionError: expected 'https://rtb.adwmg.com/cphb.html?' to include 'http://rtb.adwmg.com/cphb.html?'

      + expected - actual

      
    at Context.<anonymous> (webpack:///test/spec/modules/adWMGBidAdapter_spec.js:269:28 <- test/test_index.js:72237:74)
```

**Comment by jeanstemp** [comment]
Docs PR: https://github.com/prebid/prebid.github.io/pull/2546

**Comment by nyakove** [comment]
Hi @jsnellbaker!

Thanks for review and apologize for the delayed answer. Unit tests already should be fixed. As for error during creative rendering, it was due broken creative coming from the backend in debug mode - and it should be fixed too. 

Please take a look

**Review by jsnellbaker — CHANGES_REQUESTED** [review]
Hi @nyakove 

Thank you for making the updates and clearing the issue with the creative.  I checked them again and they were working fine for me.

Overall the code looks fine, I wanted to check with you though about the commented CCPA (USP consent) code.  Is that something you want to activate?

Please confirm when you have the chance?

**Comment by nyakove** [comment]
@jsnellbaker thank you for the review. About CCPA/USP - for now this option disabled, because our customers mostly from EU, Eastern Europe and LATAM, and we no need to support USP consent. I made this part of code for the future, and when it will required, CCPA/USP will be enabled with adapter update

**Review by jsnellbaker — APPROVED** [review]
Thank you for the confirmation. LGTM

**Pull request merged**
