### PR TITLE
Conversant bid adapter to use userIdAsEids

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [ X ] Refactoring (no functional changes, no api changes)

## Note
-  We need confirmation from the Conversant team ( @sohlhausen @pycnvr  ) before merging this change. 

## Description of change
Making changes in Conversant bid adapter to use ```userIdAsEids```
Refer: https://github.com/prebid/Prebid.js/blob/master/modules/userId/eids.md
Please note that for TDID, I have added ext field as well, I referred prebidServerBidAdapter for that.
Old format was 
```
{
        source: 'adserver.org',
        uids: [{
            id: 'some-random-id-value',
            atype: 1
        }]
    }
```
New format is
```
{
        source: 'adserver.org',
        uids: [{
            id: 'some-random-id-value',
            atype: 1,
            ext: {
                rtiPartner: 'TDID'
            }
        }]
    }
```

### CODE REVIEW

**Comment by pycnvr** [comment]
LGTM.  Thanks for the update.

**Comment by pm-harshad-mane** [comment]
Thanks, @pycnvr for the swift response.

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker ,
Could you please review this PR?

**Comment by pm-harshad-mane** [comment]
Thank you @jsnellbaker and @idettman

**Pull request merged**
