### PR TITLE
Submit Onomagic Bidder Adapter

### PR DESCRIPTION
**Pull request by vyatsun**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: 'onomagic',
  params: {
    publisherId: 20167
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: vyatsun@gmail.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- [prebid/prebid.github.io#1940](https://github.com/prebid/prebid.github.io/pull/1940)

### CODE REVIEW

**Comment by vyatsun** [comment]
Still relevant

**Comment by GLStephen** [comment]
@vyatsun your bid params are returning no bid, can you verify they are working? Also, rebase against current master and it should clear up the Circle CI tests.

**Comment by vyatsun** [comment]
@GLStephen could you share the request payload and the country you're making the request from? as our server has domain/geo targeting enabled. I will check if the correct targeting is enabled. Thanks.

**Comment by GLStephen** [comment]
@vyatsun I'm in the US. Using this page with your test params in the PR: https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html

**Comment by vyatsun** [comment]
@GLStephen I just checked the test page with the params in the PR from the US and it worked for me. 

Here is the payload: 
`{"id":"3c1019dc5c9153","imp":[{"id":"284edb30e90198","banner":{"format":[{"w":300,"h":250},{"w":300,"h":600}],"ext":{"viewability":46}},"tagid":"div-gpt-ad-1460505748561-0"}],"site":{"domain":"localhost:9999","page":"http://localhost:9999/integrationExamples/gpt/hello_world.html","publisher":{"id":20167}},"device":{"devicetype":2,"w":1920,"h":1080},"tmax":3000}`

What's the domain it shows to you in the browser? E.g. localhost:9999 or something different?

**Comment by GLStephen** [comment]
@vyatsun this is the request payload, I'm seeing no bid:

```
{"id":"3d42115db2ebfe","imp":[{"id":"2126d027e8460d","banner":{"format":[{"w":300,"h":250},{"w":300,"h":600}],"ext":{"viewability":100}},"tagid":"div-gpt-ad-1460505748561-0"}],"site":{"domain":"172.19.155.226:9999","page":"http://172.19.155.226:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true","publisher":{"id":20167}},"device":{"devicetype":2,"w":2560,"h":1440},"tmax":3000}
```

**Comment by vyatsun** [comment]
@GLStephen I've created a targeting for 172.19.155.226:9999 on the server. Could you please try again?

**Comment by GLStephen** [comment]
LGTM

**Comment by GLStephen** [comment]
You can add yourself to Header Bidder Expert if you want to be in there: https://github.com/prebid/headerbid-expert

**Pull request merged**
