### PR TITLE
AOL Bid Adapter: Remove client side support for already deprecated endpoint floor support

### PR DESCRIPTION
**Pull request by patmmccann**
## Type of change

- [X] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Verizon / Yahoo reports they deprecated server side endpoint handling of floors some time ago, documentation states can be set as a parameterter
https://github.com/prebid/Prebid.js/pull/6657#issuecomment-838246391

### CODE REVIEW

**Comment by bretg** [comment]
Heads up @slimkrazy and @ETNOL - you've recently touched this adapter, giving you a chance to confirm this change.

**Comment by patmmccann** [comment]
Copying the vz comment from the other thread "Although onedisplay supported passing a the bidFloor parameter, it is just a server side pass back over to the onemobile platform.
Since onemobile does not support bidFloor via tag integrations, this delclaration is now redundant and will have no affect server side."

**Review by FilipStamenkovic — APPROVED** [review]
PR looks good.  
@patmmccann should I merge it, or are we waiting for someone from AOL team to confirm the changes?

**Comment by patmmccann** [comment]
@adam-browning @slimkrazy any concerns?

**Comment by patmmccann** [comment]
@FilipStamenkovic my understanding is they already confirmed in the linked thread, but let's give them until release day to respond

**Comment by adam-browning** [comment]
Hi @patmmccann,
We need some more time to consolidate and verify these changes.
I'd like to confirm this with our stakeholders and platform leads first.
What is the current due date that we need to align with?
Thanks in advance,
Adam

**Comment by patmmccann** [comment]
Friday May 21

**Comment by slimkrazy** [comment]
No issue with these changes. Please feel free to merge and release.

**Pull request merged**
