### PR TITLE
IndexExchange Secondary Request support (rotating ads, slideshows, etc)

### PR DESCRIPTION
**Pull request by amandelindex**
*UPDATE*
Pull request now also includes a fix to prevent IX from hitting the PBJS global timeout every time. See the comment below for details.

Updated the Index Exchange bidder adapter so that it supports multiple requests per page load (eg. slideshows, rotating ads, etc).

Previous functionality was to ignore request besides the initial one (on a single page load).
New functionality allows a new request to be sent to the Index Exchange ad server network without reloading the page.

### CODE REVIEW

**Comment by amandelindex** [comment]
This has been updated so that the adapter also no longer causes PBJS to hit the max timeout.

Previously the library expected 5 bids back if we asked IX's AS for 5 bids, but the AS might pass on some, so if it did it cause PBJS to wait for ever.

**Comment by mkendall07** [comment]
Thanks for the PR @amandelindex 

We will review for merge.

**Comment by mkendall07** [comment]
@amandelindex 

It looks like the test fore prebid.js isn't working any longer. Here are the params:
```
{
                        bidder: 'indexExchange',
                          params: {
                            id: '1',
                            siteID: 123456,
                            timeout: 1000
                        }
                    }
```
And using host override
```
107.22.171.78 as.casalemedia.com
107.22.171.78 js.indexww.com
```

**Comment by amandelindex** [comment]
I will check this out and see what went wrong.

**Comment by mkendall07** [comment]
Sorry for the confusion, my params are actually below - I've updated my comment above too. 
```
 params: {
                            id: '1',
                            siteID: 222222,
                            timeout: 2000
                        }

```

**Comment by mkendall07** [comment]
Hi @amandelindex 
Any luck on this?

**Comment by amandelindex** [comment]
This request is outdated, we have applied the fixes here: https://github.com/prebid/Prebid.js/pull/238
Please use the new pull request, I will close this one.

**Pull request closed without merging**
