### PR TITLE
Staq Adapter: update with meta envelope

### PR DESCRIPTION
**Pull request by mquirion**
## Type of change

- [x ] Other

## Description of change

This change wraps auction meta information around an array of event data rather than including all of that meta information within each event. 

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- matt@staq.com
- [ x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by mquirion** [comment]
CircleCI has failing tests, but on review, none of the tests involved have anything to do with my adapter.  I'm not clear on what's happening.  Running tests locally all succeed.

**Comment by jsnellbaker** [comment]
@mquirion There have some inconsistent tests that have been impacting the circleci tests.

When I reran the job though, I saw one set of tests that were due to a reverted adapter change.  If you resync with `master` it should clear at least that set of errors.

**Comment by mquirion** [comment]
@jsnellbaker Looks like that worked.  Thank you.

**Comment by mquirion** [comment]
@sumit116 Hi.  I know y'all are quite busy, but is there anything further I need to do to get this reviewed?

**Comment by sumit116** [comment]
> @sumit116 Hi. I know y'all are quite busy, but is there anything further I need to do to get this reviewed?

Hi @mquirion, I think we are good. 

> @sumit116 Hi. I know y'all are quite busy, but is there anything further I need to do to get this reviewed?

HI @mquirion, I think the PR is good to review. I will review it soon.

**Comment by sumit116** [comment]
Hi @mquirion, I had a look into you adapter and found the unit test coverage is way below the acceptance criteria of 80% which we follow. Can you add more tests as a part of this PR? Please let me know  your thoughts on this.

Info: To check unit test coverage you can do `gulp test-coverage` , and then `gulp view-coverage` and the coverage page will open port 1999 on your default browser.

Thanks!

**Comment by mquirion** [comment]
@sumit116 Hi, thanks for the feedback.

I've run the test coverage stats before this PR and now after this feedback.  I see the following for STAQ's adapter:

`
staqAnalyticsAdapter.js |   | 92.12% | 187/203 | 87.2% | 143/164 | 89.74% | 35/39 | 91.96% | 183/199
`

I'm unclear where you're getting the "below 80%" metric from.  Could you help me out?  I see the "Branches" metric at 77.79%, but that's for the entire project, and I see quite a number of other adapters well below 80%. 

Thanks.

**Comment by sumit116** [comment]
Tested on hello_world page, anaytics request goes to server with each event having its respective data.

**Pull request merged**
