### PR TITLE
PubMatic bid adapter to support CCPA/USP

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [X] Feature

## Description of change
PubMatic bid adapter to support CCPA/USP

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker , @harpere ,

Could you please review this PR?

**Comment by harpere** [comment]
@pm-harshad-mane  you should open a pull to add `usp_supported` to your adapter md file.  https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/pubmatic.md

**Comment by pm-harshad-mane** [comment]
Hello @harpere 
I have added documentation PR as well, could you please review the PRs?

**Comment by pm-harshad-mane** [comment]
Thank you @jsnellbaker !!

**Pull request merged**
