### PR TITLE
Fidelity: Add SCHAIN Support

### PR DESCRIPTION
**Pull request by onaydenov**
## Type of change

- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter  
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Add Schain support for Fidelity bid adapter

- contact email of the adapter’s maintainer onaydenov@fidelity-media.com
- [X] official adapter submission
- A link to a PR on the docs repo https://github.com/prebid/prebid.github.io/pull/1845

## Other information

Local test and build passed successfully

### CODE REVIEW

**Comment by onaydenov** [comment]
@baltiysk

**Comment by onaydenov** [comment]
> LGTM, just trying to get the tests to pass

@mkendall07  Can we do anything on our end? What's the reason for check failing?

**Comment by onaydenov** [comment]
> LGTM, just trying to get the tests to pass
@mkendall07 is the PR going to be merged into master soon? Please advise.

**Comment by bretg** [comment]
7 consecutive failures in browsertack, but `gulp test` succeeds locally. Going to merge this.

**Pull request merged**
