### PR TITLE
SOVRN Bid Adapter: refactor old test code

### PR DESCRIPTION
**Pull request by cpabst**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Modernizing some old test code

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

cpabst@sovrn.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@cpabst looks like the "get correct bid response" test is failing on safari. Can you take a look at that when you get a chance?

**Comment by cpabst** [comment]
@ChrisHuie Will do.

**Comment by maximpakhomov** [comment]
@ChrisHuie please review the PR

**Comment by cpabst** [comment]
@ChrisHuie The current test failure does not appear to be from our code. Am I missing something?
I fully rebased earlier before this test run.

**Comment by patmmccann** [comment]
If you repull master, that test issue should go away

**Comment by ChrisHuie** [comment]
> @ChrisHuie The current test failure does not appear to be from our code. Am I missing something? I fully rebased earlier before this test 

Rerunning testing and still going through the code but this should be merged today 👍

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
