### PR TITLE
adformBidAdapter: currency module support

### PR DESCRIPTION
**Pull request by braizhas**
## Type of change
- [x] Feature

## Description of change
Pass configured currency to adserver.

- contact email of the adapter’s maintainer
Scope.FL.Scripts@adform.com
- [x] official adapter submission

### CODE REVIEW

**Comment by bretg** [comment]
Does this obsolete https://github.com/prebid/Prebid.js/pull/4016 ?  Looks like the `rcur` param doesn't exist in your documentation -- please enter a separate PR against https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/adform.md

**Comment by bretg** [comment]
Never mind - that's the `adFormOpenRTB` adapter. Got it.

**Comment by braizhas** [comment]
I would prefer to have a single way for currency configuration. `rcur` parameter left to not break existing configurations only. I don't want to document it to avoid further usage.

**Comment by bretg** [comment]
sounds good

**Pull request merged**
