### PR TITLE
FeedAd Bid Adapter: add support for GDPR/TCF 2.0 & remove video support 

### PR DESCRIPTION
**Pull request by couchcrew-thomas**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added support for TCF 2.0 and GDPR to the FeedAd adapter.

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/ <br>https://github.com/prebid/prebid.github.io/pull/2831

### CODE REVIEW

**Comment by couchcrew-thomas** [comment]
The failed test does have nothing to do with my code.

**Comment by ChrisHuie** [comment]
@couchcrew-thomas could you also please update the .md file with the removing of video

**Comment by ChrisHuie** [comment]
@couchcrew-thomas I will help with the testing and see what is going on :)

**Review by FilipStamenkovic — APPROVED** [review]
LGTM.  
Just a little note, in the future please split PR like this into 2 separate PRs:
- add gdpr support
- remove video support.  

Before merging this PR, why didn't you add your `gvlid = 781` according to the: https://iabeurope.eu/vendor-list-tcf-v2-0/ ?

**Comment by couchcrew-thomas** [comment]
@FilipStamenkovic Thank you for the hint. I have added the `gvlid`. I could not find any mention of it inside the docs. Only within the aliases section.
As for the separate PRs, I will keep it in mind for the next update.
Thank you for your quick review.

**Comment by FilipStamenkovic** [comment]
@couchcrew-thomas Code looks good.  
Before merging, can you just update your docs [PR](https://github.com/prebid/prebid.github.io/pull/2831) with `gvl_id: 781`?

**Comment by couchcrew-thomas** [comment]
@FilipStamenkovic I've just added it to the docs PR.

**Pull request merged**
