### PR TITLE
e-Volution Bid Adapter : update bid request validation and added video placement keys

### PR DESCRIPTION
**Pull request by e-volution-tech**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [x] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## DOC
https://github.com/prebid/prebid.github.io/pull/5343

### CODE REVIEW

**Review by spotxslagle — APPROVED** [review]
I don't see any issues

**Review by spotxslagle — CHANGES_REQUESTED** [review]
Ack! I should have paid more attention. It needs to be passing the the ci check.

**Comment by ChrisHuie** [comment]
> Ack! I should have paid more attention. It needs to be passing the the ci check.

@spotxslagle I reran it and looks good :)

**Review by spotxslagle — APPROVED** [review]

**Comment by e-volution-tech** [comment]
@spotxslagle Is this adapter okay? Will it be merged, or do we need to fix something?

**Comment by spotxslagle** [comment]
@ChrisHuie Is this good to be merged?

**Pull request merged**
