### PR TITLE
GrowAdvertising Bid Adapter: add new adapter

### PR DESCRIPTION
**Pull request by lexerom**
## Type of change

- [x] New bidder adapter   

## Description of change
Add new 

- test parameters for validating bids
```
{
  bidder: 'growads',
  params: {
    zoneId: 'unique-zone-id'
  }
}
```

## Documentation
PR https://github.com/prebid/prebid.github.io/pull/3044

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo: https://github.com/prebid/prebid.github.io/pull/3044

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@lexerom can you please also include a markdown docs file in this pr please

**Comment by lexerom** [comment]
@ChrisHuie Added. But build has failed for some other tests, not related to my pr.

**Comment by ChrisHuie** [comment]
@lexerom yeah we have a flaky ie11 test that should get sorted out this week. Got the tests to pass when rerunning

**Review by musikele — COMMENTED** [review]
Please have a look at the file name for documentation file

**Pull request merged**
