### PR TITLE
NoBid Bid Adapter: add support for config.ortb2

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change
- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support for config.ortb2.

### CODE REVIEW

**Comment by redaguermas** [comment]
There seems to be an issue with the "fluctAdapter". That's not our Adapter.

**Comment by ChrisHuie** [comment]
@redaguermas can you please take out your code editor files from this pr?

**Comment by redaguermas** [comment]
@ChrisHuie 
Which files. The last commit "beda7fd" has only one file.

**Comment by ChrisHuie** [comment]
> @ChrisHuie Which files. The last commit "beda7fd" has only one file.

If you look at this pr your ide files are included. So there are 7 files being updated in this pr. 6 - don't exist technically (like .project)

**Comment by redaguermas** [comment]
@ChrisHuie ,
Ah, I see. Check it now, I deleted the extra files.
Thank you.

**Comment by ChrisHuie** [comment]
@redaguermas can you also add a test for this and it should be good to go!

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
