### PR TITLE
Fix for Issue 6117: Added Module Name in Build to Comments

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [ ] Feature

## Description of change
https://github.com/prebid/Prebid.js/issues/6117

So for `modules.json` file as following 
```
[
  "openxBidAdapter",
  "rubiconBidAdapter",
  "sovrnBidAdapter",
  "pubmaticBidAdapter",
  "pubmaticAnalyticsAdapter",
  "id5IdSystem",
  "dfpAdServerVideo",
  "browsiRtdProvider"
]
```

on using `gulp build --modules=modules.json`, the header in final build will be 
```
/* prebid.js v4.27.0-pre
Updated : 2021-02-10
Modules: rtdModule, adpod, userId, openxBidAdapter, rubiconBidAdapter, sovrnBidAdapter, pubmaticBidAdapter, pubmaticAnalyticsAdapter, id5IdSystem, dfpAdServerVideo, browsiRtdProvider */
```

Please note that if  `--modules` option is not used with `gulp build` then the header in final build will be 
```
/* prebid.js v4.27.0-pre
Updated : 2021-02-10
Modules: All available modules in current version. */
```

### CODE REVIEW

**Review by jsnellbaker — APPROVED** [review]
LGTM

Thanks for putting this together @pm-harshad-mane

**Comment by pm-harshad-mane** [comment]
Thank you @jsnellbaker for the review.
@ChrisHuie could you please review the change?

**Comment by pm-harshad-mane** [comment]
Hello @smenzer Could you please review the PR?

**Comment by smenzer** [comment]
@pm-harshad-mane this is great, thank you so much for putting this together!

@bretg since this is built into the `gulp build` process, will the [Prebid Downloads page](https://docs.prebid.org/download.html) also benefit from this feature or is there something else that would have to happen to make this work there?

**Review by smenzer — APPROVED** [review]
LGTM

**Review by ChrisHuie — APPROVED** [review]

**Comment by pm-harshad-mane** [comment]
Thank you @smenzer and @ChrisHuie !!

**Comment by bretg** [comment]
> since this is built into the gulp build process, will the Prebid Downloads page also benefit from this feature

Don't know. If it doesn't happen automatically, we can open an item to make it happen. I'd like to get a volunteer to learn this area... any takers? https://github.com/prebid/prebid-js-build-generator

**Comment by jsnellbaker** [comment]
I think it'll be fine.  From what I can gather, it looks like the download command uses the `--modules` flag - which works with this PR.  See here: https://github.com/prebid/prebid-js-build-generator/blob/master/routes/routes.js#L43

We'll see for sure with the next release where it can be tested directly.

**Comment by pm-harshad-mane** [comment]
@smenzer , @bretg Download Page scenario should be handled as changes in PR use `modules` parameter in gulp job.
We will make sure to test this with next release.

**Pull request merged**
