### PR TITLE
Add SARA-HB Bid Adapter

### PR DESCRIPTION
**Pull request by SARA-HB**
## Type of change
- [x] New bidder adapter   

## Description of change
New Bidder Adapter for SARA

- test parameters for validating bids
```
{
  bidder: 'sara',
  params: {
    uid: 5
  }
}
```

- github@sara.media
- [x] official adapter submission
- A link to a PR on the docs repo https://github.com/prebid/prebid.github.io/pull/628

### CODE REVIEW

**Comment by jaiminpanchal27** [comment]
To merge i will need Docs PR. Please submit a PR to the [docs repo](https://github.com/prebid/prebid.github.io) to add a file for your adapter to the [bidders directory](https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders) so your adapter's params will appear on the [bidders page](http://prebid.org/dev-docs/bidders.html). Thank you for contributing

**Comment by bretg** [comment]
@jaiminpanchal27 - docs PR is https://github.com/prebid/prebid.github.io/pull/628

**Comment by jaiminpanchal27** [comment]
@SARA-HB Any update ?

**Comment by SARA-HB** [comment]
@jaiminpanchal27 Please check the test ids again, we setup a campaign to return bids.
As for the docs, they were submitted in https://github.com/prebid/prebid.github.io/pull/628

**Comment by jaiminpanchal27** [comment]
@SARA-HB Not returning bids again. I tried testing using this page https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html

Tried both uid 5 and 6

**Comment by jaiminpanchal27** [comment]
@SARA-HB Any update ?

**Comment by SARA-HB** [comment]
Hey @jaiminpanchal27, it seems that in your example HTML you're calling only appnexus for bids. The bids section doesn't contain anything about 'sara'. Could you please check?

**Comment by jaiminpanchal27** [comment]
@SARA-HB hello_world is template we use to test all bidders. We update adUnits with the test params. It works now. Thanks

**Pull request merged**
