### PR TITLE
RTB House adapter update

### PR DESCRIPTION
**Pull request by piwanczak**
## Type of change
- [x] Bugfix

## Description of change
Add support for single bracket sizes array, ex: [300, 250]
next to canon one - [[300, 250]]

- contact email of the adapter’s maintainer
- [x] official adapter submission

### CODE REVIEW

**Comment by piwanczak** [comment]
@bretg the latter one. I'm assuming AdUnit.mediaTypes.banner.sizes should be either be single bracket, two elem array or array of two elem arrays. Fix is based on inconsistent publisher config - sizes could be either of the two.
Is there a trap I'm about to fall into that I'm not seeing? I'll be happy to fix if you think there is a better way to do this.

**Comment by bretg** [comment]
@mkendall07 - have we heard of other cases where AdUnit.mediaTypes.banner.sizes is [w,h] rather than [[w,h]]?

The underlying suggestion here is to have the platform convert to double array if only a single array is provided. If this is a common scenario, then having just one adapter cover it doesn't do as much good as the platform converting to the expected form.

**Comment by mkendall07** [comment]
>The underlying suggestion here is to have the platform convert to double array if only a single array is provided.
prebid core should do this but I don't think it does. 
I was going to open an issue for it but figured it take as much time to just fix it. https://github.com/prebid/Prebid.js/pull/2738

**Comment by harpere** [comment]
@piwanczak #2738, once merged, will fix the inconsistency and you'll be able to depend on a double array [[w,h]]

**Comment by bretg** [comment]
So... the implication is that this change shouldn't be needed after #2738 ... would you agree @piwanczak ?

**Comment by piwanczak** [comment]
@bretg Correct, once #2738 is merged my fix is unnecessary. 
Thank you as well as @mkendall07 !
I'll sub the other one and close my pull once #2738 is merged

**Comment by harpere** [comment]
@piwanczak #2738 has been merged

**Comment by bretg** [comment]
Good news. Closing.

**Comment by piwanczak** [comment]
Thank you!

**Pull request closed without merging**
