### PR TITLE
SharedIdSystem: return pubcid instead of sharedId

### PR DESCRIPTION
**Pull request by SKOCHERI**
- [x] Bugfix
This is for the issue reported in https://github.com/prebid/Prebid.js/pull/7099.
Apart from fixing the issue mentioned in https://github.com/prebid/Prebid.js/pull/7099. This PR has cleaned up the SharedIdSystem to removed calls to sharedId endpoint.

### CODE REVIEW

**Comment by philipwatson** [comment]
Cheers, looks good. 

I see another potential issue: it doesn't delete the stored id when `_pubcid_optout` cookie is detected.
So when the user opts-out _after_ the stored id is created, prebid will keep using this stored id until it expires.

**Comment by SKOCHERI** [comment]
> Cheers, looks good.
> 
> I see another potential issue: it doesn't delete the stored id when `_pubcid_optout` cookie is detected.
> So when the user opts-out _after_ the stored id is created, prebid will keep using this stored id until it expires.

@philipwatson In extendId() function, if optedout the id (cookie value) is set to undefined.

**Comment by philipwatson** [comment]
@SKOCHERI But the core user module won’t use it if undefined. Here: https://github.com/SKOCHERI/Prebid.js/blob/32837f4c5d2247fb67286b1a95b462d733004d60/modules/userId/index.js#L662

**Comment by SKOCHERI** [comment]
> @SKOCHERI But the core user module won’t use it if undefined. Here: https://github.com/SKOCHERI/Prebid.js/blob/32837f4c5d2247fb67286b1a95b462d733004d60/modules/userId/index.js#L662

@philipwatson The decode() is updated to handle output

**Comment by philipwatson** [comment]
Yep that works. Cheers!

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
