### PR TITLE
NEW adapter AdtelligentBidAdapter

### PR DESCRIPTION
**Pull request by Millerrok**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Add new adtelligentBidAdapter

- test parameters for validating bids
```
 var adUnits = [

      // Video instream adUnit
      {
        code: 'div-test-div',
        sizes: [[640, 480]],
        mediaTypes: {
          video: {
            context: 'instream'
          }
        },
        bids: [{
          bidder: 'adtelligent',
          params: {
            aid: 332842
          }
        }]
      },

      // Video outstream adUnit
      {
        code: 'outstream-test-div',
        sizes: [[640, 480]],
        mediaTypes: {
          video: {
            context: 'outstream'
          }
        },
        bids: [{
          bidder: 'adtelligent',
          params: {
            aid: 332842
          }
        }]
      },

      // Banner adUnit
      {
        code: 'div-test-div',
        sizes: [[300, 250]],
        bids: [{
          bidder: 'adtelligent',
          params: {
            aid: 324758
          }
        }]
      }
    ];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by mike-chowla** [comment]
If I configure 2 ad units on the page, I get an error.  The error is done to the response body coming back from the bid endpoint being malformed JSON.

Here's what I get back:

```
"{}[{"source":{"aid":324758,"pubId":18173},"bids": [{"type": "DISPLAY","adid":"3B12EDC12741DC4A","cmpId":73860,"requestId":"232242423b6cda","width":300,"height":600,"cpm":1.7,"ad":"\u003cscript id=\"P3B12EDC12741DC4A\" type=\"text/javascript\" >(function(d){var wrapper = d.createElement(\"script\"); wrapper.id = \"W3B12EDC12741DC4A\";wrapper.type = \"text/javascript\";wrapper.src = \"http://ads59.adtelligent.com/display/?adid=3B12EDC12741DC4A&cb=636653250\";var s = d.getElementById(\"P3B12EDC12741DC4A\");s.parentNode.insertBefore(wrapper, s);}(document));\u003c/script>\u003cnoscript>\u003cimg border=\"0\" alt=\"\" src=\"http://ads59.adtelligent.com/tracking/error/?adid=3B12EDC12741DC4A&code=2505\">\u003c/noscript>","cur": "USD"}
]},]" 
```

Console Error Message: in response for adtelligent adapter
The error message, in this case, is not very good because the error message is generated only using the error message in the server response.  If the server response is invalid, no useful error is given

**Comment by mike-chowla** [comment]
There are also should be a test case for the multiple ad-slot test case

**Comment by Millerrok** [comment]
@mike-chowla 
Hi! Thanks for review.
Test for multi-request is added.
The response for adtelligent adapter is correct.

Best regards

**Comment by mike-chowla** [comment]
I'm still getting an error with two ad slots on the page

screen shot 2018-02-22 at 4 40 21 pm

Here's my test page:
[hello_world_2_ad_slots.html.zip](https://github.com/prebid/Prebid.js/files/1747647/hello_world_2_ad_slots.html.zip)

**Comment by Millerrok** [comment]
@mike-chowla 
Hi Mike,  

Thanks for fully described flow of reproducing this issue.
The response for adtelligent adapter now is fixed.

Here is an example of response for adtelligent adapter:
http://hb.adtelligent.com/auction/?domain=localhost&callbackId=254afaa22cf733&aid=324758&ad_type=display&sizes=300x250%2C300x600&callbackId2=3aa1a0d1bbb9bd&aid2=324758&ad_type2=display&sizes2=300x250&

Best regards, 
Max

**Comment by mike-chowla** [comment]
@Millerrok I don't see a commit that fixes the issue

**Comment by Millerrok** [comment]
@mike-chowla
Hi Mike,

Thanks for review.
The test bid params for adtelligent adapter now is updated.

Best regards,
Max

**Comment by mike-chowla** [comment]
I tried requesting with the new test bid params and I am not getting a bid back

screen shot 2018-03-19 at 5 48 20 pm

screen shot 2018-03-19 at 5 48 32 pm

**Comment by Millerrok** [comment]
@mike-chowla
Hi Mike,

Thanks for review.
The test bid params for adtelligent adapter now is updated.

Here is an example of response for adtelligent adapter:
http://hb.adtelligent.com/auction/?domain=localhost&callbackId=28748347%D0%B0%D0%BF834%D0%B0%D0%BF&aid=350975&ad_type=display&sizes=300x250

Best regards,
Max

**Pull request merged**
