### PR TITLE
Apply matchMedia to the top frame

### PR DESCRIPTION
**Pull request by benjaminclot**
## Type of change
- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
In case Prebid.js is called from within an iFrame, matchMedia should be applied to window.top, not the containing iFrame.
This PR falls back to the legacy behavior in case of unfriendly iFrames.

### CODE REVIEW

**Comment by benjaminclot** [comment]
CI fails because of a Yieldbot adapter problem on Chrome 61.0.3163 (Windows 10.0.0)? 🤔

**Comment by benjaminclot** [comment]
It would be great if this PR could make it into the next release. This is quite an annoying bug, as it also impacts postbid.

**Comment by mike-chowla** [comment]
I'm doubtful it can get in the new next release because it needs to two reviews due to being a core change.

What scenarios do you expect this to fix?  I'm trying the think through all cases to understand why it makes sense that the media query is applied to top window rather than the iframe?

**Comment by benjaminclot** [comment]
> What scenarios do you expect this to fix? I'm trying the think through all cases to understand why it makes sense that the media query is applied to top window rather than the iframe?
Why would you apply it to an iframe? Isn't the goal to know the full width of a window?

**Pull request merged**
