### PR TITLE
BlueBillyWig Bid Adapter: add renderer customization options

### PR DESCRIPTION
**Pull request by K-JBoon**
## Type of change
- [x] Feature
- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change
We're adding the ability to customize the appearance/behaviour of our renderer at the code level instead of solely in our platform. This change adds the ability to use this in the Blue Billywig adapter.

- contact email of the adapter’s maintainer: dev+prebid@bluebillywig.com

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

https://github.com/prebid/prebid.github.io/pull/2832

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@K-JBoon this pr didn't kick off our CircleCi tests. This usually happens when you are following your fork of Prebid but not the source Prebid in CircleCi. If you give me edit access I can probably kick it of f manually too.

**Comment by K-JBoon** [comment]
Hey @ChrisHuie , I've just added you to the collaborators of the repo. Please let me know if you need anything else, cheers!

**Comment by ChrisHuie** [comment]
I'm still not able to edit this specific pr to kick off the tests for some reason. Even after I accepted your request. Trying to figure out whats going on

**Comment by K-JBoon** [comment]
@ChrisHuie If you want I can branch freshly off the current master and cherry-pick this update on it?

**Comment by ChrisHuie** [comment]
@K-JBoon you want to just recreate this pr and see if the tests happen to kick off then. Also, if you check the box at the bottom of the pr to let maintainers I will definitely be able to kick them off it doesn't work

**Comment by K-JBoon** [comment]
@ChrisHuie Oops yeah, you're right. Added to the right repo now!

**Comment by ChrisHuie** [comment]
Tests kicked off :)Thanks @K-JBoon

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
