### PR TITLE
IntentIq Analytics Adapter: add pcid value to the payload

### PR DESCRIPTION
**Pull request by DimaIntentIQ**
## Type of change

- [x] Updated Analytical Adapter

## Description of change
Added `pcid` value to the payload

### CODE REVIEW

**Comment by patmmccann** [comment]
please see #12171

**Comment by patmmccann** [comment]
Hi @DimaIntentIQ please always include your module name in your pr title

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
looks good, holding merge pending jsdoc update and title fix

**Comment by DimaIntentIQ** [comment]
> Hi @DimaIntentIQ please always include your module name in your pr title

Got it, thanks @patmmccann

**Comment by patmmccann** [comment]
can you do the jsdoc fix too?

**Comment by DimaIntentIQ** [comment]
> can you do the jsdoc fix too?

As I see there is our intentIqIdSystem.js in the list, but I don't really understand what should be fixed there

**Comment by patmmccann** [comment]
image

**Comment by patmmccann** [comment]
I fixed it, lmk if it looks fine to you

**Comment by DimaIntentIQ** [comment]
> I fixed it, lmk if it looks fine to you

Now I get it, @patmmccann thank you very very much!

**Pull request merged**
