### PR TITLE
[PT-32] Adding new functionality to reject subsequent requests to our…

### PR DESCRIPTION
**Pull request by shannonhochkins**
## Type of change

- [ ] Bugfix
- [x ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
After a PXYZ ad has won, we don't want another PXYZ ad on the page, we use an internal property on the spec object to save the last winning bid, if the new requesting bid has the same bidderCode we invalidate and return false.

- test parameters for validating bids
```
{
  bidder: 'pxyz',
  params: {
    placementId: '12341234'
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

If you have any advice on how to achieve this in a better more efficient way, currently with this implementation this allows us to only have ONE ad per page, we would eventually like this to allow up to one of each ad format per page. Is this possible?

### CODE REVIEW

**Comment by shannonhochkins** [comment]
Seems master is failing on "adagio analytics adapt" so we can't get this out!

**Comment by jsnellbaker** [comment]
Hi @shannonhochkins 

With the resync of master, the browserstack tests (which are ran by circleci) are passing locally, so we can ignore any other errors we might be seeing with the automated tests.

In regards to this PR itself, I have a few questions that I want to clarify.  

In terms of blocking subsequent requests and only showing 'once' on the page, what about the scenario if a publisher has you listed in multiple adUnits that are all part of the same auction?  Do you only fill one of those requests, or could your adapter fill all of those slots?  In the case of the latter and you won some of those ad slots on the page, would that being going against the 'shown once' you described here?  Or is that okay since it was the initial load, and you want to limit subsequent requests on the same page session (ie when a pub refreshes the ads).

Additionally, when you use the term `each ad format` are you referring to each adUnit/ad slot?  I see from your adapter code that you only support the `banner` ad format, so I wanted to confirm what you meant.

Thanks.

**Comment by shannonhochkins** [comment]
> Hi @shannonhochkins
> 
> With the resync of master, the browserstack tests (which are ran by circleci) are passing locally, so we can ignore any other errors we might be seeing with the automated tests.
> 
> In regards to this PR itself, I have a few questions that I want to clarify.
> 
> In terms of blocking subsequent requests and only showing 'once' on the page, what about the scenario if a publisher has you listed in multiple adUnits that are all part of the same auction? Do you only fill one of those requests, or could your adapter fill all of those slots? In the case of the latter and you won some of those ad slots on the page, would that being going against the 'shown once' you described here? Or is that okay since it was the initial load, and you want to limit subsequent requests on the same page session (ie when a pub refreshes the ads).
> 
> Additionally, when you use the term `each ad format` are you referring to each adUnit/ad slot? I see from your adapter code that you only support the `banner` ad format, so I wanted to confirm what you meant.
> 
> Thanks.

Hi jsnellbaker,

>  In terms of blocking subsequent requests and only showing 'once' on the page, what about the scenario if a publisher has you listed in multiple adUnits that are all part of the same auction? Do you only fill one of those requests, or could your adapter fill all of those slots?  In the case of the latter and you won some of those ad slots on the page, would that being going against the 'shown once' you described here?

When the publisher has us listed in multiple ad units, we take care of only bidding on one ad unit server side - this PR is to address the scenario when the publisher runs subsequent auctions, e.g. on pages with infinite scroll or lazy loading sections

> Additionally, when you use the term each ad format are you referring to each adUnit/ad slot? I see from your adapter code that you only support the banner ad format, so I wanted to confirm what you meant.

Yes technically we only support one format "banner", however we launch a number of different custom rich media "formats" from 320x50 and 300x250 banners.

Hope this clears things up for you!

Cheers,

**Comment by osazos** [comment]
> Seems master is failing on "adagio analytics adapt" so we can't get this out!

Hi @shannonhochkins, the issue you mention has been temporary fixed with #4409 
By the way the proper tests should be merged soon: #4417 

Sorry for the inconvenience.

**Comment by shannonhochkins** [comment]
> > Seems master is failing on "adagio analytics adapt" so we can't get this out!
> 
> Hi @shannonhochkins, the issue you mention has been temporary fixed with #4409
> By the way the proper tests should be merged soon: #4417
> 
> Sorry for the inconvenience.

Hi @osazos - Okay we'll keep checking for this PR to be merged, then we'll merge up stream and hopefully role this one through!

Cheers,

**Comment by shannonhochkins** [comment]
> > > Seems master is failing on "adagio analytics adapt" so we can't get this out!
> > 
> > 
> > Hi @shannonhochkins, the issue you mention has been temporary fixed with #4409
> > By the way the proper tests should be merged soon: #4417
> > Sorry for the inconvenience.
> 
> Hi @osazos - Okay we'll keep checking for this PR to be merged, then we'll merge up stream and hopefully role this one through!
> 
> Cheers,

Hi @osazos, 

Just wondering if there's any update on this?

I've merged upstream again.

Cheers,

**Comment by osazos** [comment]
Hi @shannonhochkins, I'm still waiting for #4417 to be merged. 
By the way, you merged upstream so our tests are fixed. The errors in CircleCi are not about adagioAnalyticsAdapter. 

The circleCi tests failed sometimes, you should ask an owner to rerun.

Best

**Comment by monofonik** [comment]
@jsnellbaker can you please let us know how we can progress this PR? Seems the CI tests are failing spuriously.

Thanks

**Pull request closed without merging**
