### PR TITLE
Native support for AdKernel adapter

### PR DESCRIPTION
**Pull request by ckbo3hrk**
## Type of change
- [x] Other

## Description of change

Added support for native media type

- prebid-dev@adkernel.com
- [x] official adapter submission

### CODE REVIEW

**Comment by ckbo3hrk** [comment]
Pull request for adapter doc update
https://github.com/prebid/prebid.github.io/pull/1893

**Comment by jsnellbaker** [comment]
@ckbo3hrk Do you have any test params for this new native support?

**Comment by ckbo3hrk** [comment]
> @ckbo3hrk Do you have any test params for this new native support?

@jsnellbaker Yes, I've updated adapter documentation. At the moment there is a server-side problem with HTTPS configuration so it's testable only via HTTP.

**Comment by ckbo3hrk** [comment]
> Could you take a look to see why the bid may not be returning?

Hi @jsnellbaker 
It looks like a test campaign targeting issue.  I've updated targeting. Hope this will help.

**Comment by ckbo3hrk** [comment]
> @ckbo3hrk I tried to use the test params again, but I'm still not seeing the bid return. Can you check again please? If there's any information you need, please let me know.
> 
> Thanks.

Hi @jsnellbaker
I guess it's an IP issue. Could you edit the adapter code and change `ip: 'caller'` to `ip: '8.11.10.11'`.
If no bid response - try 3-5 times as bidding is affected by a small probabilistic factor.
In case it won't help - I'll find these requests in raw request logs and figure out the exact reason.

**Pull request merged**
