### PR TITLE
Revert "don't allow null or undefined bid properties"

### PR DESCRIPTION
**Pull request by mkendall07**
Reverts prebid/Prebid.js#2865

### CODE REVIEW

**Comment by mkendall07** [comment]
@bwoolcott asked me to revert this commit.

**Comment by snapwich** [comment]
I'm fine with the revert.  Is the Zedo revert intentional as well?

**Comment by mkendall07** [comment]
I just used the github `revert`  button.

**Comment by snapwich** [comment]
@mkendall07 it lists the ZEDO commit in the revert commits, but I didn't see the files removed or deleted in the "Files changed" section, so I think it's okay.  Not sure why it has that commit though...

**Pull request merged**
