### PR TITLE
Prebid core: improve library support; make AnalyticsAdapter a library

### PR DESCRIPTION
**Pull request by dgirardi**
## Type of change

- [x] Feature

## Description of change

This:

 - improves library support to automatically generate libraries and track their dependencies, so that consumers of a library simply need to `import` symbols from it;
 - makes `AnalyticsAdapter.js` a library, so that it can be shared when multiple analytics adapters are included in the build.

## Other information

Closes https://github.com/prebid/Prebid.js/issues/7936
Original library PR: https://github.com/prebid/Prebid.js/pull/8527
Minor docs update: https://github.com/prebid/prebid.github.io/pull/3863

### CODE REVIEW

**Review by jsnellbaker — APPROVED** [review]
Checked the build file and saw the duplicate references for the analytics adapter code only appeared once, instead of dozens of time.  

So this appears to working from what I can tell.  Nice work :)

**Review by mmoschovas — APPROVED** [review]
lgtm

**Comment by robertrmartinez** [comment]
@dgirardi 

Analytics Adapters have stopped initializing since this PR for me.

I am trying to pinpoint why now.

Seems the modules `registerAnalyticsAdapter` code is never executing, like the module is not even loading itself. I put breakpoints at global level of module and they do not get hit.

Bid Adapters and other modules are loaded just fine.

I have only tested with rubicon analytics adapter so far.

Wondering if it is the changes to webpack build? Will keep looking.

**Comment by robertrmartinez** [comment]
Looks like `src/AnalyticsAdapter.js` is not being included in the build any longer.

Do we have to explicitly include it now?

**Comment by robertrmartinez** [comment]
Looks like the `libraries/analyticsAdapter/AnalyticsAdapter.js` formerly known as `src/analyticsAdapter.js` is no longer auto included in my prebid builds using same old command as before.

Our process uses Prebid Packager https://github.com/prebid/Prebid.js-packager which I am thinking is the problem.

Since src/analyticsAdapter.js is not inside the generated rubiconAnalyticsAdapter.js, prebid packager needs to include it in the build. Guessing it does not handle libraries or something.

I'll continue to look into it.

**Comment by robertrmartinez** [comment]
Yeah, so now looks like we need to update prebid packager to correctly include the necessary `library` files if modules from the build include it.

I see `analyticsAdapter.js` is output now after this PR when before it was not included in output files, it was just added into analyticsAdapter files themselves.

So this needs to be included in the build.

As I think we are the only ones working with prebid packager, I will try and fix this.

**Comment by dgirardi** [comment]
@robertrmartinez the build now [generates a `dependencies.json`](https://github.com/prebid/Prebid.js/blob/73c13cde704ef396a152ed9dcb8596779473107d/gulpfile.js#L245) that links output files to the output "library" files they need. I was unfortunately completely unaware of the packager

**Comment by robertrmartinez** [comment]
@dgirardi I whipped up something real quick which "solves" this. I know it could be written better / cleaner of course, but unfortunately I am slammed at the moment.

https://github.com/prebid/Prebid.js-packager/pull/4

I guess we should prob get off of this prebid packager sometime maybe, but it makes our system run quicker since we do not have to run gulp build every time we build a prebid wrapper.

**Pull request merged**
