### PR TITLE
Zeus Prime RTD Module: initial module release

### PR DESCRIPTION
**Pull request by PilotConway**
## Type of change

- [X] Feature

## Description of change

This adds an RTD module for Zeus Prime. Zeus Prime client side code requests contextual targeting information for the content on a page and sends the data as a page level key-value in Google AdManager. This is a vendor specific module, as an account and integration with Zeus Prime is required for the API to respond. 

Contact: support@zeustechnology.com

To validate, you can provide the following configuration to retrieve a 200 success response from our API: 

```js
{
  realTimeData: {
    dataProviders: [{
      name: 'zeusPrime',
      waitForIt: false,
      params: {
        gamId: "701", 
        hostname: "www.washingtonpost.com", 
        pathname: "/science/2022/09/26/nasa-dart-mission-asteroid-crash/"
      }
    }]
  },
}
```

_Note that users of this plugin will only provide gamId, so the hostname and pathname parameters are not documented in the markdown files_

## Other information

The documentation PR has been submitted as [https://github.com/prebid/prebid.github.io/pull/4117](https://github.com/prebid/prebid.github.io/pull/4117)

### CODE REVIEW

**Comment by patmmccann** [comment]
Reading through this, it appears this module sets gam targeting but doesn't make this information available to ssps other than adx?

**Comment by PilotConway** [comment]
@patmmccann That is correct. Prime is inventory that is sold and added to customers GAM account directly. So it's targeting lines in their account, more similar to sponsorship than programmatic.

**Comment by ChrisHuie** [comment]
Docs pr -> https://github.com/prebid/prebid.github.io/pull/4117

**Comment by patmmccann** [comment]
Appears to NOT be a rules violation; as it isn't sending key-values to adx or any exchange. Thanks for clarifying.

**Review by Fawke — COMMENTED** [review]
Hi @PilotConway,

All looks good, just add your module to the `modules/.submodules.json` list.

**Review by Fawke — APPROVED** [review]

**Pull request merged**
