### PR TITLE
Adding sharedid submodule as required to pubcommon submodule

### PR DESCRIPTION
**Pull request by YerkovichM**
## Type of change

- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Adding sharedid module as required to pubcommon module
Added initialization of required submodule
If not given configuration, required submodule will be given basic configuration from demanding module

### CODE REVIEW

**Comment by smenzer** [comment]
is this saying that any publisher who includes pubcommon will automatically be including sharedid as well?

**Comment by jdwieland8282** [comment]
> is this saying that any publisher who includes pubcommon will automatically be including sharedid as well?

yes

**Comment by smenzer** [comment]
feels like that needs to be well documented otherwise publishers are going to be including a module they aren't explicitly asking for. 

does this follow the the published Module Rules? specifically i'm looking at rule 1.5: "Modules must not import other Prebid modules at build time"  @bretg @patmmccann thoughts?

**Comment by jdwieland8282** [comment]
closing we will pursue a different approch

**Pull request closed without merging**
