### PR TITLE
PubMatic Bid Adapter: Added multibid support for GroupM

### PR DESCRIPTION
**Pull request by pm-azhar-mulla**
## Type of change

- [x] Feature

## Description of change

WRT https://github.com/prebid/Prebid.js/issues/8074
We have implemented a technique to reduce the network calls, we will not initiate network call for Alias but instead SSP will handles it using the publisherId it has and sends multiple bids in response. On receiving the response, depending upon the marketplace property we will set the bidderCode and bidder for particular bid.

### CODE REVIEW

**Review by pm-harshad-mane — COMMENTED** [review]
Looks good to me

**Comment by patmmccann** [comment]
@pm-harshad-mane have you looked at https://github.com/prebid/Prebid.js/issues/8129?

**Comment by pm-harshad-mane** [comment]
Thank you @patmmccann for pointing out issue #8129.

**Comment by pm-harshad-mane** [comment]
@pm-azhar-mulla , we will need to make changes to follow #8129

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
