### PR TITLE
Create andbeyondBidAdapter_spec.js

### PR DESCRIPTION
**Pull request by andbeyondmedia**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by andbeyondmedia** [comment]
Adding test

**Comment by bretg** [comment]
Goes with #2436

**Comment by bretg** [comment]
@andbeyondmedia - please take a look at the travis-ci failure. Kicked off a rebuild and it failed again...

```
"Uncaught Error: Cannot find module \"modules/andbeyondBidAdapter\"
```

**Comment by rtbdemand** [comment]
Test wont succeed I beleive unless the adapter is merged

**Comment by jsnellbaker** [comment]
Closing as partner PR #2436 was also closed.

**Pull request closed without merging**
