### PR TITLE
Allow Conversant sizes to be overridden per placement

### PR DESCRIPTION
**Pull request by combs**
follows pattern from sovrn.js

### CODE REVIEW

**Comment by matthewlane** [comment]
Thanks for the PR, looks good to me so far, just a conflict that needs to be resolved.

**cc**ing @msahagu2 for any feedback as well

**Comment by combs** [comment]
Fixed now, thank you @matthewlane !

**Comment by matthewlane** [comment]
Oops, looks like your build.sh and yarn.lock files were checked in on the most recent commit

**Comment by combs** [comment]
Oof, sorry, I think it's patched up now @matthewlane.

**Pull request merged**
