### PR TITLE
Eplanning Bid Adapter: viewability refactor and fix in search the divs

### PR DESCRIPTION
**Pull request by fndigrazia**
## Type of change
- [ x] Bugfix
- [ x] Refactoring (no functional changes, no api changes)

## Description of change
eplanning viewability refactor and fix in search the divs

ndigrazia@e-planning.net
- [ x] official adapter submission

### CODE REVIEW

**Comment by sebaperez** [comment]
Hi @Rothalack , do you have any ETA for reviewing this? Thanks!

**Comment by Rothalack** [comment]
I'm not seeing any other PR's that have done this. My best guess is maybe try to do a master merge and commit that? A commit may trigger the build.

**Comment by sebaperez** [comment]
Sure, thanks! We just did a new commit so it should trigger the build

**Comment by Rothalack** [comment]
I'm not sure why that's not triggering a build. I've reached out on slack to see if I can get it figured out.

**Comment by ChrisHuie** [comment]
@Rothalack 

> I'm not sure why that's not triggering a build. I've reached out on slack to see if I can get it figured out.

Kicked off tests 👍 (gave a bit more detail on this issue over slack)

**Review by Rothalack — APPROVED** [review]
Good to go!

**Pull request merged**
