### PR TITLE
LiveIntent Id Module: update dependency in Prebid

### PR DESCRIPTION
**Pull request by peixunzhang**
CM-1153 (https://liveintent.atlassian.net/browse/CM-1153)

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change
 Update LiveConnect dependency in Prebid

### CODE REVIEW

**Comment by patmmccann** [comment]
@peixunzhang please follow conventions on pr names

**Comment by peixunzhang** [comment]
> @peixunzhang please follow conventions on pr names

Will do. Thank you for checking.

**Review by patmmccann — CHANGES_REQUESTED** [review]
It seems you fail your own tests

**Comment by patmmccann** [comment]
conflicts with https://github.com/prebid/Prebid.js/pull/11118/files

**Pull request closed without merging**
