### PR TITLE
Vidazoo Adapter: save and send first request time

### PR DESCRIPTION
**Pull request by uditalias**
## Type of change

- [x] Feature

## Description of change
Adding first request time param to local storage

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203357576079959

### CODE REVIEW

**Comment by patmmccann** [comment]
Hi, we cannot accept further submissions on your adapter js without an attempt to solve code duplication.

**Comment by patmmccann** [comment]
@saar120 you are submitting multiple identical adapters; please adjust to prevent code duplication

image

**Comment by uditalias** [comment]
> Hi, we cannot accept further submissions on your adapter js without an attempt to solve code duplication.

Hi @patmmccann
Can you share an example where we can move duplicated code that relates to these specific adapters?

**Comment by patmmccann** [comment]
@uditalias please see the links in the github action comment above eg [modules/shinezRtbBidAdapter.js](https://github.com/prebid/Prebid.js/blob/bd910268940efdf1cdee634978f4088c53aaee00/modules/shinezRtbBidAdapter.js#L25-L151) has 128 duplicated lines with [modules/vidazooBidAdapter.js](https://github.com/prebid/Prebid.js/blob/bd910268940efdf1cdee634978f4088c53aaee00/modules/vidazooBidAdapter.js#L43-L151)

**Comment by uditalias** [comment]
> @uditalias please see the links in the github action comment above eg [modules/shinezRtbBidAdapter.js](https://github.com/prebid/Prebid.js/blob/bd910268940efdf1cdee634978f4088c53aaee00/modules/shinezRtbBidAdapter.js#L25-L151) has 128 duplicated lines with [modules/vidazooBidAdapter.js](https://github.com/prebid/Prebid.js/blob/bd910268940efdf1cdee634978f4088c53aaee00/modules/vidazooBidAdapter.js#L43-L151)

@patmmccann Yeah, I know, but where should we move the duplicated code? Is there a specific folder in the project for this purpose?

**Comment by patmmccann** [comment]
see #8527 
https://github.com/prebid/Prebid.js/tree/master/libraries

**Comment by uditalias** [comment]
> see #8527 https://github.com/prebid/Prebid.js/tree/master/libraries

Hey @patmmccann 
Your example (#8527) relates to the prebid core utils.
The duplicated code presented on this PR is related to specific adapters. Do you know if it is still relevant? Should we create a `vidazooUtils` folder with our specific functions used by some other adapters?

I just don't want to pollute the public environment of the Libraries folder with some specific adapters library code.

**Comment by patmmccann** [comment]
> Should we create a vidazooUtils folder with our specific functions used by some other adapters?

Prefect, yes do that

**Comment by patmmccann** [comment]
#11854 is a great example of a similar effort

**Review by patmmccann — APPROVED** [review]
Vidazoo adapter looks great! An additional pr fixing twist and these other heavily duplicated files is very welcome

**Comment by patmmccann** [comment]
Keep up the great work

**Pull request merged**
