### PR TITLE
Concert Bid Adapter: adding referrer

### PR DESCRIPTION
**Pull request by andrew-a-dev**
## Type of change
- [x] Other

Specifically: adding functionality to the existing Concert adapter

## Description of change

Adding a `ref` parameter to the bid calls, using the various "referrer" properties available in Prebid. 

(The PR also contains linting-related changes to the file as a whole, to do with `;` and whitespace.)

## Note

This PR was originally opened (and approved) here: https://github.com/prebid/Prebid.js/pull/8564 -- but I unintentionally closed the PR by messing around with `master` on our forked repo. 🤦 Sorry. (It also includes an adjustment to that version, as per a suggestion from @dgirardi 🙌 )

### CODE REVIEW

**Comment by patmmccann** [comment]
Circleci didn't run; typically it will if you unfollow your fork and make a tiny change

**Comment by andrew-a-dev** [comment]
> Circleci didn't run; typically it will if you unfollow your fork and make a tiny change

I'm sorry, I'm not sure what you mean by "unfollow your fork"? (I'm going to try pushing a tiny inconsequential change to our branch, regardless, just to see.)

**Comment by dgirardi** [comment]
I'm not sure how it works either, but you may have some levers to try in [circleci](https://app.circleci.com/)? (I know if set up my fork in it - "follow" in their parlance - it will try to use a different account for PRs that come from that fork).

**Comment by andrew-a-dev** [comment]
Thanks for that, @dgirardi . I assumed that the circleci tests were run by this repo, rather than the source repo. I've tried to add our fork to circleci, but apparently I don't have sufficient admin access to the repo to allow that. 🙄 😞 . I'll have to try again next week.

**Comment by ChrisHuie** [comment]
@andrew-a-dev CircleCi usually doesn't run because you are following your own fork in CircleCi instead of Prebid itself. If you go into CircleCI and unfollow your fork and rerun it will kick off the tests a lot of times. Also, if there is edit access on this pr I can kick off manually my making a commit.

**Comment by andrew-a-dev** [comment]
@ChrisHuie Thanks! I don't have access to _any_ CircleCI running; I checked all over, and CircleCI can only see my personal repositories, not any `voxmedia` organizational repos (let alone Prebid's one). So if you can tell me what to do to allow you access to edit this PR/branch, and kick off a CI run, I'd be very grateful! 🙌

**Comment by ChrisHuie** [comment]
@andrew-a-dev resubmitted this pr under #8676 :)

**Pull request closed without merging**
