### PR TITLE
Prebid Core: after auction is held, if more bids are matched by adUnitCode next apply filter for bidId

### LINKED ISSUE #7735: Twin ad units not working properly for native
## Type of issue

Bug
## Description

[Twin ad unit codes](https://docs.prebid.org/dev-docs/adunit-reference.html#twin-adunit-codes) are not working properly for native.  
I wanted to run 2 twin adunits, where each twin has different `adTemplate` for native.  
I've setup fake bidder to respond with 2 bids for both twins, but pbjs attaches `adTemplate` from '1st twin' on both bids.  
In that way both ads get rendered with same template, even though I configured different templates.

## Steps to reproduce

To reproduce it, load test page (described bellow) and you need to setup fake bidder that will provide two bids. My fake bidder responds with following adm (both bids have the same adm):

```
{
  "ver":"1.2",
  "assets":
  [
    {"id":5, "data":{"value":"Read More"}},
    {"id":4,"title":{"text":"This is a Prebid Native Creative2."}},
    {"id":0,"img":{"url":"https:\\/\\/vcdn.adnxs.com\\/p\\/creative-image\\/94\\/22\\/cd\\/0f\\/9422cd0f-f400-45d3-80f5-2b92629d9257.jpg","w":3000,"h":2250}},
    {"id":1,"img":{"url":"https:\\/\\/vcdn.adnxs.com\\/p\\/creative-image\\/bd\\/59\\/a6\\/c6\\/bd59a6c6-0851-411d-a16d-031475a51312.png","w":127,"h":83}},
    {"id":3,"title":{"text":"This is a Prebid Native Creative"}},
    {"id":2,"data":{"value":"Prebid.org"}}],"link":{"url":"https:\\/\\/lax1-ib.adnxs.com\\/click?AAAAAAAAJEAAAAAAAAAkQAAAAAAAACRAAAAAAAAAJEAAAAAAAAAkQMpy7K05m-sIdLZDYYFYVCE5JaVgAAAAAOLoyQBtJAAAbSQAAAIAAACDpc8FnPgWAAAAAABVU0QAVVNEAAEAAQBNXQAAAAABAgMCAAAAALsAtBX7hAAAAAA.\\/bcr=AAAAAAAA8D8=\\/pp=${AUCTION_PRICE}\\/cnd=%21Vg8IIQj8-LwKEIPLvi4YnPFbIAQoADEAAAAAAAAkQDoJTEFYMTo0Njc0QMArSQAAAAAAAPA_UQAAAAAAAAAAWQAAAAAAAAAAYQAAAAAAAAAAaQAAAAAAAAAAcQAAAAAAAAAAeAA.\\/cca=OTMyNSNMQVgxOjQ2NzQ=\\/bn=91951\\/test=1\\/clickenc=http%3A%2F%2Fprebid.org%2Fdev-docs%2Fshow-native-ads.html"},
    "eventtrackers":[{"event":1,"method":1,"url":"http://localhost:5500/event?type=impression&component=card"},
    {"event":2,"method":1,"url":"http://localhost:5500/event?type=v50&component=card"}
  ]}
```

In twin adunit configuration, for 1st adUnit twin `adTemplate` starts with: `<h1>1st template</h1>` and for 2nd twin adUnit, `adTemplate` starts with: `<h1>2nd template</h1>`.

Once the ad is loaded on the page, execute in dev console: `refreshSlots()`, you can notice that for both rendered ads, ad starts with `1st template`, which means that `adTemplate` was not properly loaded.

## Test page
Test html page can be found [here](https://github.com/FilipStamenkovic/Prebid.js/blob/twin_codes_native_bug/integrationExamples/gpt/prebidServer_native_example.html).

### PR DESCRIPTION
**Pull request by FilipStamenkovic**
## Type of change

- [x] Bugfix

## Description of change

During 'setupBidTargeting', if multiple bids requests are found, next apply filter by comparing bidId with requestId.
## Other information

This PR fixes #7735 issue

### CODE REVIEW

**Comment by FilipStamenkovic** [comment]
I decided to implement the fix only if multiple bids were matched.  
But, looking at this [line](https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L526), the fix could be written in a same way:

```
let bidReq = find(bidderRequest.bids, bid => bid.adUnitCode == adUnitCode && bid.bidId == bidObject.requestId);
```
?

**Comment by osazos** [comment]
> I decided to implement the fix only if multiple bids were matched. But, looking at this [line](https://github.com/prebid/Prebid.js/blob/master/src/auction.js#L526), the fix could be written in a same way:
> 
> ```
> let bidReq = find(bidderRequest.bids, bid => bid.adUnitCode == adUnitCode && bid.bidId == bidObject.requestId);
> ```
> 

IMO this is the right way.

**Comment by FilipStamenkovic** [comment]
@osazos I modified my fix according to your suggestion.

**Review by osazos — APPROVED** [review]
LGTM

**Pull request merged**
