### PR TITLE
Utiq user sub-module: Remove unused domain assingment

### PR DESCRIPTION
**Pull request by jkthomas**
## Type of change

- [x] Refactoring (no functional changes, no api changes)

## Description of change

Removal of domain checks which became irrelevant due to the data layer changes.

## Other information
This change is supposed to go together with the renaming changes introduced in https://github.com/prebid/Prebid.js/pull/9872, merged to Prebid 8 branch.

### CODE REVIEW

**Comment by jkthomas** [comment]
@ChrisHuie As all of the checks are now passing, can we move forward with this PR?

**Comment by Utiq-tech** [comment]
Please merge and publish ideally together with https://github.com/prebid/prebid.github.io/pull/4528. 
Thanks.

**Comment by ChrisHuie** [comment]
@Utiq-tech @jkthomas the module deletions need to go in a major version release pr. I saw the one on prebid 8 but doesn't look to include the removing of the old module. Since that is a breaking change for users can you put the deletions in a separate pr on the prebid 8 branch and take them out of this pr. Or just hold off a few weeks and Prebid 8 should be released and we can sync this with prebid 8 release and the previously merged pr.

**Comment by jkthomas** [comment]
@ChrisHuie So the https://github.com/prebid/Prebid.js/pull/9872 was the renaming PR, since we were migrating the solution to the new name and all parties that had been using our module were already notified.

This one is targeting the `master` branch since it was a default. We would like to put this PR's changes together with the renaming on the same day the Prebid 8 releases, so should I just change the target branch for this PR to `prebid8` one?

**Comment by patmmccann** [comment]
yes please, but perhaps create a new branch based on prebid 8 and then pr the prebid 8 branch with the changes, that should be cleaner

**Comment by jkthomas** [comment]
Did as suggested by both of you, I cleaned the commit history and moved it to https://github.com/prebid/Prebid.js/pull/10044, targeting `prebid-8`. Thank you.

**Pull request closed without merging**
