### PR TITLE
pbjs_testbids=true

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change

- [X] Feature

## Description of change
More details on https://github.com/prebid/Prebid.js/issues/4461 
Added support for PubMatic adapter

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @jaiminpanchal27 , @Fawke 
A gentle reminder to review the changes.

**Comment by jaiminpanchal27** [comment]
@pm-harshad-mane Code wise everything looks good but would need further approvals on your feature request https://github.com/prebid/Prebid.js/issues/4461 created here. I have tagged senior members for their input

**Comment by pm-harshad-mane** [comment]
Thank you @jaiminpanchal27 !

**Comment by bretg** [comment]
I'm not yet convinced this approach is the best way to handle the root issue here.

**Comment by pm-harshad-mane** [comment]
I have opened a separate PubMatic specific PR https://github.com/prebid/Prebid.js/pull/4553 
We can close this one.

**Pull request closed without merging**
