### PR TITLE
SeedingAlliance Bid Adapter: internal rework to send OpenRTB native compliant requests to backend

### PR DESCRIPTION
**Pull request by sag-henmus**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [x] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Due to work on the backend, we need clients to send properly formatted OpenRTB Native requests, as well as understand the response. This change assures that. Compability on the backend is ensured.

### CODE REVIEW

**Comment by patmmccann** [comment]
It seems you have several duplicated code blocks

[filtered-jscpd-report.json](https://github.com/user-attachments/files/15765023/filtered-jscpd-report.json)

**Comment by sag-henmus** [comment]
The change is only in two files, nowhere near where the report says. I'm unsure what the problem seems to be. Any advice on how to handle this?

**Comment by patmmccann** [comment]
If you pull in master it should make a pretty comment flagging the blocks now. 

The idea is to simply move the duplicated code to a common location and it import it in both places it is used

**Comment by patmmccann** [comment]
If your goal is to make ortb2 bid requests, why still use `convertOrtbRequestToProprietaryNative(validBidRequests)` ?

**Pull request closed without merging**
