### PR TITLE
Rubicon adapter parent window #254

### PR DESCRIPTION
**Pull request by bretg**
Patch for issue #254

### CODE REVIEW

**Comment by protonate** [comment]
Looks good to me, please flatten commits and we can merge this in.

**Comment by harpere** [comment]
@protonate - @bretg will be unavailable for the next week.  What's the easiest way to flatten his commits and get this merged?

**Comment by bretg** [comment]
Ok - worked through the 'git rebase -i' process -- believe the commits have been flattened. At least the commit as shown in my fork is now one instead of two. Please review.

**Comment by protonate** [comment]
@bretg thank you, though I'm not seeing that reflected in Github. Did you push your changes? 

In any event can go ahead and get this merged now.

**Comment by protonate** [comment]
I've flattened and merge this PR to master with [this commit](cb8c12b54d2eb348b62ba3efb35f6e57835e217d). Closing. Thanks for the contribution.

**Pull request closed without merging**
