### PR TITLE
PubMatic adapter to support PM Deals

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [X] Feature

## Description of change
PubMatic adapter to support PM Deals at the slot level

### CODE REVIEW

**Comment by robertrmartinez** [comment]
@pm-harshad-mane Can you please pull the latest from master to fix the linting errors.

**Comment by pm-harshad-mane** [comment]
Hello @robertrmartinez ,
I have pulled the code changes, but CI is failing for random cases.

**Comment by pm-harshad-mane** [comment]
@robertrmartinez All checks have passed now.

**Comment by pm-harshad-mane** [comment]
Thank you @robertrmartinez !

**Pull request merged**
