### PR TITLE
Libraries: New utility file to Remove code duplication in several adapters

### PR DESCRIPTION
**Pull request by MaksymTeqBlaze**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [x] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Created a library and utilized its functions in several adapters

### CODE REVIEW

**Comment by patmmccann** [comment]
You're my hero, thank you

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
@MaksymTeqBlaze why still in draft? I would love to merge the work you've accomplished so far

**Comment by MaksymTeqBlaze** [comment]
> @MaksymTeqBlaze why still in draft? I would love to merge the work you've accomplished so far

@patmmccann there are still some adapters that have same code and i need to add one small improvement for isBidRequestValid function

**Comment by MaksymTeqBlaze** [comment]
@patmmccann I have updated all adapters that I saw had this duplicated code and did not have much custom code. I also provided some functions that allow building requests with custom fields and logic.

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
