### PR TITLE
Adapt Adomik Analytics for Prebid.js legacy

### PR DESCRIPTION
**Pull request by Yann-Pravo**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Adapt Adomik Analytics for Prebid.js legacy

- contact email of the adapter’s maintainer yann.pravo@gmail.com
- [x] official adapter submission

### CODE REVIEW

**Comment by mkendall07** [comment]
hey @Yann-Pravo what's the purpose of this PR?

**Comment by mkendall07** [comment]
BTW, your test coverage is really low:
image

**Comment by Yann-Pravo** [comment]
Hi @mkendall07,
The purpose of the PR is to update the analytics adapter for adomik for the legacy version of Prebid.
Because not of all of our clients have moved to Prebid.js v1 but we want the same features for them.

I don't understand why my coverage is so slow, I was at 98% not so long ago. Could you give me an analytics adapter with good coverage to see what's the difference ?

Thank you,

Yann.

**Comment by mkendall07** [comment]
@Yann-Pravo 
You can see the coverage yourself if you run
`gulp test-coverage`
`gulp view-coverage`

**Comment by Yann-Pravo** [comment]
Hi @mkendall07 ,

I updated my test, everything looks good now.
image

**Comment by mkendall07** [comment]
thanks for updating tests. LGTM

**Pull request merged**
