### PR TITLE
Pubmatic Bid Adapter: add support for JW player

### PR DESCRIPTION
**Pull request by pm-manasi-moghe**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by pm-manasi-moghe** [comment]
Can this be taken up for review?

**Comment by Rothalack** [comment]
Apologies, I was on vacation. I am looking into this today.

**Review by Rothalack — APPROVED** [review]
This is working for me! You may want to update your docs on https://github.com/prebid/prebid.github.io but I will let you decide the need for that. 

In the future, you will want to consider a rebase of this branch, that would clean up the long list of merge commits, not a big deal.

**Comment by Rothalack** [comment]
After adding that approval, I noticed it's now saying there are merge conflicts in modules/pubmaticBidAdapter.js. I'm not sure why that is. Can you double check this on your end? @pm-manasi-moghe

**Comment by Rothalack** [comment]
Hey @pm-manasi-moghe I believe we're doing releases on Thursday. So if you can resolve this merge conflict before then, we should be able to get this out with that release.

**Review by Rothalack — CHANGES_REQUESTED** [review]
Resolve the merge conflict.

**Comment by pm-manasi-moghe** [comment]
Merge conflict has been resolved.

**Comment by Rothalack** [comment]
Here's the Circleci build error:

[13:24:33] Starting 'lint'...
[13:25:03] 
/home/circleci/Prebid.js/modules/pubmaticBidAdapter.js
     1:140  error  'convertTypes' is defined but never used  no-unused-vars
  1333:12   error  'utils' is not defined                    no-undef

✖ 2 problems (2 errors, 0 warnings)

[13:25:03] 'lint' errored after 29 s
[13:25:03] ESLintError in plugin "gulp-eslint"
Message:
    Failed with 2 errors
Details:
    domainEmitter: [object Object]
    domainThrown: false

[13:25:03] 'test' errored after 30 s

I'm not sure how it's coming to that conclusion. You're not defining convertTypes, you're using it from utils. It's defined in utils fine, you're importing and using it fine. I have a feeling this might be a misleading error. The change you made by adding _addJWPlayerSegmentData might be what to look into.

**Review by Rothalack — APPROVED** [review]

**Pull request merged**
