### PR TITLE
Fix typo in TheMediaGrid Bid Adapter

### PR DESCRIPTION
**Pull request by TheMediaGrid**
## Type of change

- [x] Bugfix

## Description of change

Fix typo in TheMediaGrid Bid Adapter

- grid-tech@themediagrid.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo to support TCF 2.0 https://github.com/prebid/prebid.github.io/pull/2201

### CODE REVIEW

**Comment by bretg** [comment]
@TheMediaGrid  - please add a unit test for this so we can get this merged in this week

**Comment by TheMediaGrid** [comment]
Hello, sorry for the delay, today or tomorrow morning we will add the necessary tests

**Comment by TheMediaGrid** [comment]
@bretg , test was added

**Review by bretg — APPROVED** [review]

**Comment by bretg** [comment]
Thanks!

**Pull request merged**
