### PR TITLE
Adtelligent new features

### PR DESCRIPTION
**Pull request by GeneGenie**
## Type of change
- [x] Feature
 
## Description of change
New features: 
AdPods support 
Changed TTL to be 5 min 
Fixed mediaType of bidResponse 
Fixed uspConsent getting correctly
UserId support
Schain Support 
POST endpoint
Chunk bid reqs
Multiple request hosts in rotation

- g.moroz@adtelligent.com
- [x] official adapter submission

[Docs pull request](https://github.com/prebid/prebid.github.io/pull/2010)

### CODE REVIEW

**Comment by GeneGenie** [comment]
Sorry to disturb you, @bretg but coverage test are not running :( 


`gulp test-coverage
[13:08:41] Using gulpfile ~/work/Prebid.js/gulpfile.js
[13:08:41] Starting 'test-coverage'...
[13:08:41] Starting 'clean'...
[13:08:41] Finished 'clean' after 15 ms
[13:08:41] Starting 'testCoverage'...
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.

START:
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
07 05 2020 13:09:39.223:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
07 05 2020 13:09:39.225:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 5
07 05 2020 13:09:39.243:INFO [launcher]: Starting browser ChromeHeadless
07 05 2020 13:09:39.698:INFO [HeadlessChrome 81.0.4044 (Mac OS X 10.14.6)]: Connected on socket oc_CTZAqOelx7kjFAAAA with id 77056038
07 05 2020 13:09:43.527:WARN [reporter]: SourceMap position not found for trace: Uncaught TypeError: Cannot read property 'f' of undefined
at http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:179:184990

TypeError: Cannot read property 'f' of undefined
    at Object.getParameterByName (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:179:184990)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:248:55123)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:166:69)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:670:68)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:5388:74)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:33903:1)
07 05 2020 13:09:43.527:WARN [reporter]: SourceMap position not found for trace: Uncaught TypeError: Cannot read property 'f' of undefined
at http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:179:184990

TypeError: Cannot read property 'f' of undefined
    at Object.getParameterByName (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:179:184990)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:248:55123)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:166:69)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:670:68)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:5388:74)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?46d877e7197d940e1e5415936ddda27eaef31d2e:33903:1)
HeadlessChrome 81.0.4044 (Mac OS X 10.14.6) ERROR
  Uncaught TypeError: Cannot read property 'f' of undefined
  at webpack:///src/utils.js:308:42 <- test/test_index.js:179:184990
  
  TypeError: Cannot read property 'f' of undefined
      at Object.getParameterByName (webpack:///src/utils.js:308:42 <- test/test_index.js:179:184990)
      at Object.<anonymous> (webpack:///src/config.js:30:27 <- test/test_index.js:248:55123)
      at __webpack_require__ (webpack:///webpack/bootstrap%206338f5ce9304eae1af67:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (test/test_index.js:166:69)
      at __webpack_require__ (webpack:///webpack/bootstrap%206338f5ce9304eae1af67:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (test/test_index.js:670:68)
      at __webpack_require__ (webpack:///webpack/bootstrap%206338f5ce9304eae1af67:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (webpack:///test/mocks/adloaderStub.js:2:1 <- test/test_index.js:5388:74)
      at __webpack_require__ (webpack:///webpack/bootstrap%206338f5ce9304eae1af67:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (webpack:///test/test_index.js:2:1 <- test/test_index.js:33903:1)

Finished in 3.832 secs / 0 secs @ 13:09:43 GMT+0300 (Eastern European Summer Time)

SUMMARY:
✔ 0 tests completed
[13:09:43] 'testCoverage' errored after 1.02 min
[13:09:43] Error: Karma tests failed with exit code 1
    at /Users/moroz/work/Prebid.js/gulpfile.js:278:12
    at removeAllListeners (/Users/moroz/work/Prebid.js/node_modules/karma/lib/server.js:370:9)
    at webServer.close (/Users/moroz/work/Prebid.js/node_modules/karma/lib/server.js:381:13)
    at Server.close (net.js:1565:9)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:203:15)
    at Server.EventEmitter.emit (domain.js:466:23)
    at emitCloseNT (net.js:1618:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[13:09:43] 'test-coverage' errored after 1.02 min`

**Comment by jsnellbaker** [comment]
@GeneGenie 

There is currently an issue we're in the middle of addressing with `test-coverage` command, but it will need some additional time.  

You can ignore the test-coverage for now if you want.  If you really need to see the coverage results, you can try out this workaround that we found:
https://github.com/prebid/Prebid.js/pull/5128/commits/5c5954e79433add9ddd06c5adc9cd24c0419edcd

We didn't want to implement this, so please ensure to not include it as part of your commits.  If you have any questions, please let me know.

**Comment by GeneGenie** [comment]
Thank you for assistance

**Comment by GeneGenie** [comment]
@sumit116  вщту

**Comment by GeneGenie** [comment]
Docs updated

**Comment by GeneGenie** [comment]
@bretg  currently it's very challenging to update/write unit tests. Since 
`gulp test --file "adapter_spec.js" ` 
is failing with error 
`Uncaught SyntaxError: Cannot use import statement outside a module`

**Comment by jsnellbaker** [comment]
If you want an alternative option to limit the number of unit tests that are run while you do the iteration, you can modify your primary `describe(` function in your test file to be `describe.only(`.  With this setting, the normal `gulp test` command will run that sub-section of tests.

If you do use this option, please remember to remove the param before you commit your changes.

**Comment by GeneGenie** [comment]
> If you want an alternative option to limit the number of unit tests that are run while you do the iteration, you can modify your primary `describe(` function in your test file to be `describe.only(`. With this setting, the normal `gulp test` command will run that sub-section of tests.
> 
> If you do use this option, please remember to remove the param before you commit your changes.
> 
> There is another PR in the works that should hopefully fix the `file` option soon. #5268

Yeah, I was using it, but it still compiles all adapters and all tests, which takes time.

**Pull request merged**
