### PR TITLE
Add refreshId method support to userId submodule interface

### PR DESCRIPTION
**Pull request by icflournoy**
## Type of change
- [x] Feature

## Description of change
This change supports the forthcoming Parrable userId system and allows us to maintain a previously persisted ID. Our use case is closely described by an older issue: https://github.com/prebid/Prebid.js/issues/3989

We extend the userId module interface to support a `refreshId` method, similar to the `getId` method.
`refreshId(configParams, consentData, storedId)` takes the ID retrieved from storage and allows the ID system to determine if the stored ID value should be updated with a new ID value.
The return from refreshId is set as the userId submodule's callback to be processed similar to the `getId` call that first stored the ID.

Recent work by ID5 introduced a `storage.refreshInSeconds` config item, which was supported by adding a `storedId` parameter to the `getId()` signature. https://github.com/prebid/Prebid.js/pull/4082.

While our intended behavior supported by this PR could be simulated by setting `storage.refreshInSeconds = 1` we believe that this refreshId method provides a cleaner way of signaling the intent to update an ID if the ID system deems an update is necessary. This feature also opens up the ability for any userId system to implement a refreshId function and handle ID maintenance each time the ID is accessed.

The ability to refresh our ID is inherent to our ID system and thus should not be a publisher configuration item like `storage.refreshInSeconds`.

We are open to ideas on how to integrate ID5's refreshInSeconds work with our refreshId work. Both features seem like two behaviors of the same "ID refresh" functionality.

### Proposal
1. `getId()` reverts to its former interface `getId(submodule.config.params, consentData)`
2. `refreshId(submodule.config.params, consentData, storedId)` is a supported method of a userId system submodule and, if it exists, is called each time `initSubmodules()` occurs.
3. **If** ID5's config item for `storage.refreshInSeconds` is specified then `refreshId()` is only called if the refreshInSeconds period has elapsed (otherwise refeshId is called every time).

We have built test in userId spec that runs two auctions and verifies that the ID has been updated by the second auction. This test is currently failing since we're not sure how to trigger the end of an auction event, thus having the userId module callbacks processed.

### Documentation
This is a change to the userId system supported interface - which we cannot find a documentation page for the supported methods when building a userId module. 

Points of contact for this PR are @eyas-ranjous and @icflournoy.

cc: @padurgeat and @smenzer from ID5, as this will be of interest to them and we are happy to have their input.

### CODE REVIEW

**Comment by padurgeat** [comment]
Hey Ian,
My understand from the past Criteo PR (`criteortusIdSubmodule`) is that if storage is not defined, (line 349), `getId()` will be called for every prebid call, which looks like the behaviour you're looking for. Cheers,

**Comment by icflournoy** [comment]
HI Pierre-Antoine - thanks for pointing that out. Criteo's PR did change the behavior such that if storage isn't defined then getId is called each time. It also looks like Criteo is fetching their cookie in getId their own way (using `utils.getCookie`), effectively circumventing the Prebid userId core module's storage mechanism.

We do want to store our ID using Prebid's storage mechanism, but we also want to refresh it, and would rather build onto the core userId API to benefit all modules than relying on custom logic within our own userId system.

**Comment by padurgeat** [comment]
Right! Let me know if I can help you. You can give me access to your fork if you need us to modify/review our implementation. Cheers,

**Comment by icflournoy** [comment]
Hey @padurgeat I've taken a first pass at updating your ID5IdSystem implementation with a refreshId() method that is invoked when `storage.refreshInSeconds` expires. I've invited you as a collaborator on our fork - you can take review the changes here https://github.com/Parrable/Prebid.js/pull/2

Thanks in advance for taking a look!

**Comment by jsnellbaker** [comment]
@icflournoy When you have the chance, can you please resolve the conflicts?

**Comment by icflournoy** [comment]
Hi @jsnellbaker we have some additional changes related to the refreshId and refreshInSeconds functionality that we're going to push soon to this branch. I will resolve conflicts at that time so I am working with the latest changes in your master branch.

**Comment by icflournoy** [comment]
Hi @jsnellbaker I'm closing this PR because it's superseded by changes from a recently-merged PR https://github.com/prebid/Prebid.js/pull/3869.  We will work on utilizing this change in the userId submodule interface in our own ID system.

@padurgeat thanks for your assistance on this, will let you know if we have any changes that overlap with your `config.refreshInSeconds` feature.

**Pull request closed without merging**
