### PR TITLE
Eids uid string only

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [X] Bugfix

## Description of change
In UserId module, while generating userIdAsEids, code will check if the provided id by a user-id-sub-module is string or not, an only string will be allowed.

Conversant adapter spec is updated to have uid value as string in test-cases.

### CODE REVIEW

**Comment by bretg** [comment]
Adding @pycnvr to confirm the Conversant change here.

**Comment by pycnvr** [comment]
Thanks.  Looks alright.

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker ,
Issac is not available I guess (from Slack), could you please review this small fix?

**Comment by pm-harshad-mane** [comment]
Thank you @jsnellbaker !!

**Pull request merged**
