### PR TITLE
added adaptor for sovrn

### PR DESCRIPTION
**Pull request by vikpj**
Hi all,

I've created an adaptor for Sovrn. Please review and let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by ialex** [comment]
Is it running on a live page i can check? i would love to see the adaptor working.

**Comment by vikpj** [comment]
I've been testing it here: http://exposuredynamics.com/test/prebid_test.html.

There are three caveats on the test page.

1. Instead of sending ```location.hostname``` it sends a static string ```"www.healthstatus.com"```. This is obviously not part of the commit.
2. I'm using prebid.js instead of prebid.min.js.
3. I'm testing postbid instead of the prebid.

**Comment by mkendall07** [comment]
Hi @vikpj ,

Thank you for you for contributing. We are currently working directly with Sovrn for an official adapter. I expect that will be pulled into prebid.js very soon. Thanks

**Comment by vikpj** [comment]
@mkendall07 I actually worked directly with Sovrn to build this.

**Pull request closed without merging**
