### PR TITLE
Improve Digital adapter: flag support for native 1.2 JS trackers in bid request

### PR DESCRIPTION
**Pull request by jbartek25**
## Type of change
- [X] Feature

## Description of change
Improve Digital adapter: Include explicit declaration of native 1.2 JS imp tracker support in bid request. JS trackers were supported already but some DSPs (like DV360) now expect to see explicit confirmation in bid request.

### CODE REVIEW

**Comment by patmmccann** [comment]
did you not want to allow PBS adapter to see this as well if a publisher configures it? Also it seems like we're diverging from PBS adapter here; it would seem a publisher would want to choose this in a consistent way.

**Comment by patmmccann** [comment]
@jbartek25 your review / feedback of #8665 is quite welcome

**Comment by patmmccann** [comment]
Any chance you could give feeedback directly on https://github.com/prebid/Prebid.js/pull/8086  ?

**Comment by jbartek25** [comment]
@patmmccann let me put this PR on hold until next week.

**Comment by patmmccann** [comment]
@jbartek25 8086 is now merged, I think it is fair default this config in your adapter as long as publishers have some way to specify they prefer no js trackers on native

**Comment by jbartek25** [comment]
I'll look into updating the adapter to adopt the ortb native allowing the overrides via the ad unit media type native.ortb object

**Comment by patmmccann** [comment]
After a bunch of discussion, i think we can merge this now, so up to you if you want to make edits or not

**Comment by jbartek25** [comment]
ok. please merge then. @dgirardi is converting the Improve Digital adapter to ortb as part of https://github.com/prebid/Prebid.js/pull/8738 so I'll make sure the default is overridable as part of that PR.

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
