### PR TITLE
add workaround to prevent IX adapter from ending auction early

### PR DESCRIPTION
**Pull request by protonate**
## Type of change

- [x] Bugfix

## Description of change
add workaround to prevent IX adapter from ending auction early

### CODE REVIEW

**Comment by protonate** [comment]
@mkendall07 @matthewlane for review

**Comment by mkendall07** [comment]
LGTM.

**Comment by dugwood** [comment]
@protonate why is it only for this bidder? I'm having the same issue with Rubicon: https://github.com/prebid/Prebid.js/issues/496#issuecomment-258149194

With the current code:
```
 1505 Request bid for rubicon
 1899 rubicon:    Time: 392
 1911 All bids are back (or timeout was hit): 406ms
 1912 bid #0: rubicon     CPM: 2.255  Time: 392
 1935 Winning bid: rubicon (price bucket: 2.20)
 2128 rubicon:    Time: 622
```
With a fix such as `bid.bidder === 'indexExchange' || bid.bidder === 'rubicon'`:
```
 1506 Request bid for rubicon
 1916 rubicon:    Time: 410
 1971 rubicon:    Time: 466
 1976 All bids are back (or timeout was hit): 471ms
 1977 bid #0: rubicon     CPM: 2.255  Time: 410
 1977 bid #1: rubicon     CPM: 4.679  Time: 466
 2001 Winning bid: rubicon (price bucket: 4.60)
```

I already hit this when I was struggling in my #700 pull request.

I'll send a PR for this, at least for Rubicon and RubiconLite (I'll test this one).

Okay, I know why you don't do it for all bidders: Criteo (that I'm testing in a beta preview) sends only one request for 3 zones with 2 sizes each, where Rubicon would launch 6 requests. So it depends on the bidder... And even more, it depends on the setup of Rubicon for each account.

This should be a parameter in the `adUnits` sent to `addAdUnits`, so that it doesn't break everything for currently valid setups.

**Comment by mkendall07** [comment]
I don't think it should be a parameter. We need standardized behavior across the bidders and in exception cases the bidder should tell us automatically how many bids they expect. Previously we had an `expectedBids` param that could be set. I think we can bring this back.

**Comment by dugwood** [comment]
Thanks @mkendall07, but as you can see in my latest comment (https://github.com/prebid/Prebid.js/issues/496#issuecomment-258163609, sorry for the cross posting...), there can't be a standard as it depends on the good will of bidders to setup correctly. And I must add that the Rubicon setup with fallback to another size is very bad, as you may have a better bid on the fallback than on the current bid, but you'll never know. And if you count the bids, you'll break current setups. So the end user must have a parameter for this (that could be set as default, for instance with `IX`.

As you said there was `expectedBids`, can you point me to this code?

**Comment by dugwood** [comment]
I can see it here: https://github.com/prebid/Prebid.js/blob/caa537077ff0319df91358fadb932ae741f3bccb/src/adapters/indexExchange.js#L415

But it's outside the user's scope. Meaning I can't set it for my Rubicon setup if I don't change the Rubicon adapter. So it must be set outside of the adapter.

Can I add a parameter for this? Would be set here:
```
{
    bidder: 'rubicon',
    params: { ... },
    oneRequestPerSize: true
}
```
And I'll remove all the expectedBids that are no longer used.

**Comment by protonate** [comment]
@dugwood have a look at this PR #773. Would this approach resolve your issues with Rubicon adapters?

**Comment by dugwood** [comment]
@protonate it's a great PR, but I don't think it will help, as Rubicon setup changes from one account to another. So for two different accounts, you can have one that uses the «fallback» and only returns one bid and one only, and the other without fallback that will fire multiple bids. Maybe we can find a solution within the Rubicon adapter, to detect the different setups. Maybe :-)

**Comment by dugwood** [comment]
I've narrowed it down to this piece of code, by comparing my setup and the one from another website with fallback (I've removed all useless variables):
```
window.rubicontag.loadConfiguration({
	"configuration": {"useMultiSize": true},
});
window.rubicontag.init();
```
So, the good news is that there's a variable in the `/header/accountID.js` with Rubicon.

I'm trying to create a patch for Rubicon adapter based on your PR (too bad it's not already merged!).

**Comment by dugwood** [comment]
The bad news: I just can't access the variable. It's hidden in the main object Rubicon create, and there's no public function `getConfigValue`. So there's no way to find out about this value, unless Rubicon returns it in the `setIntegration` function.

Anyway, the simple use of `useMultiSize` would be wrong, as Rubicon also tests for other cases using `useSingleRequest` (XHR and tests like that).

So, again, we're stuck with Rubicon bad implementation (the adapter can't do anything), same as in https://github.com/prebid/Prebid.js/issues/496#issuecomment-258149194

I'll ask my Rubicon contact to send this to their engineers to fix this, but I've no real hope here...

**Comment by dugwood** [comment]
@protonate I did some more tests today. It's even worse than before (the ad size is set by the first bid returned, so sometimes I have a 728x90 in a frame of 1000x300!).

Anyway, I've just read the following info:
#783
https://github.com/prebid/Prebid.js/issues/782#issuecomment-259163461

Hence I'm getting rid of `rubicon`, and restarted on `rubiconLite`. My main issue is that `rubiconLite` always answers only with one size, even if the url clearly states that there are multiple alt sizes.

So I guess that's another Rubicon bad setup on my account. I'm asking them right now to add the `useMultiSize` so that I can test it correctly.

That would remove the need for `expectedBids` if `rubicon` adapter is fully removed as it should.

I'll keep you posted. This is a big issue, that'll make anyone thinks it's a Prebid issue whereas it's a Rubicon issue in their account setup.

**Comment by mkendall07** [comment]
Hey @dugwood 
You said:
>My main issue is that rubiconLite always answers only with one size

I think this ideal isn't it? Rubicon is answer with the highest CPM ad that matches the given size(s). Seems correct to me unless I'm missing something?

**Comment by dugwood** [comment]
@mkendall07 yes, that would be great if it was working correctly, but, as I've just stated here: https://github.com/prebid/Prebid.js/issues/496#issuecomment-259441735, if you don't have the MAS enabled, you'll have only one size requested and not all the sizes.

But you're right, it only sends one request, so no need for `countBids()` here. As the `rubicon` old adapter is removed, that makes things easier, but there are a few bugs to address.

Anyway, for this very PR, we're good!

**Comment by mkendall07** [comment]
Right, I wrote that before I read your other comment. Makes sense now. I think Rubicon is on the right track.

**Pull request merged**
