### PR TITLE
Index exchange stop hitting prebid timeout on passes and support for multiple sizes per slot

### PR DESCRIPTION
**Pull request by indexexchange**
Refactor how expected bids is determined to more accurately represent the expected and to honour our timeout value

### CODE REVIEW

**Comment by mkendall07** [comment]
@indexexchange 
Thanks for the PR. Anything specific we should test for?

**Comment by indexexchange** [comment]
@mkendall07 Previously we were not creating bids for passing responses from our servers, this caused prebid to timeout while waiting for all our bids. This PR will have correct expected bids and create passing bids for them to stop prebid from hitting it's timeout.

You can use siteID 123456 on our test ad server to get a passing response.

**Comment by indexexchange** [comment]
@mkendall07 Updated this pull request as the original code for this was modified while adding in new feature. The case to test still exists, but there is a new case now, support for multiple sizes per slot has been added.

**Comment by mkendall07** [comment]
@indexexchange 
Can you please squash your commits into 1?

**Comment by indexexchange** [comment]
Closing this PR, found some issues that have to be sorted out. I will send new PR with fixes tomorrow morning.

**Pull request closed without merging**
