### PR TITLE
Prebid Core: Addition of Optional Category Targeting Key

### PR DESCRIPTION
**Pull request by jlquaccia**
## Type of change
- [x] Feature

## Description of change
Optional category targeting key can be sent to ad servers that stores the value of the Primary IAB category ID if present on the meta obj of a bid response.

## Other information
Hi @patmmccann, I was looking into this GitHub issue and had one question. I see in the table describing the meta obj [here](https://docs.prebid.org/dev-docs/bidder-adaptor.html#interpreting-the-response) that for category there are fields for primary and secondary cat id's.  For this new targeting key, should the value be set to the primary only? (what i did for this pr).  Or I can adjust the logic as needed.  I can also update things on the testing end after I find out.

### CODE REVIEW

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
This looks right to me! Might be useful to check prebid server adapter populating this correctly. 

Will need second review

**Comment by jlquaccia** [comment]
@patmmccann Ok awesome, sounds good!  Will look into PBS and then address the docs & unit tests next.

**Comment by patmmccann** [comment]
might be able to solve the prebid server check with a unit test

**Comment by robertrmartinez** [comment]
@jlquaccia @patmmccann So is this now expected to send by default always?

I thought this would be an opt-in thing?

**Comment by patmmccann** [comment]
Opt in, just like adomain

**Comment by jlquaccia** [comment]
hey @patmmccann @robertrmartinez, can you guys review when you get a chance?  Did the following:
- updated relative targeting related tests
- updated docs -> https://github.com/prebid/prebid.github.io/pull/4192
- confirmed that this new category targeting key also gets set with pbs (when the category targeting key is enabled)

**Review by robertrmartinez — APPROVED** [review]

**Comment by patmmccann** [comment]
thanks!

**Pull request merged**
