### PR TITLE
Various adapters: remove use of storageManager bypasses

### PR DESCRIPTION
**Pull request by patmmccann**
Fixes https://github.com/prebid/Prebid.js/issues/8689

### CODE REVIEW

**Comment by patmmccann** [comment]
@jsadwith looking for your feedback here; it isn't obvious why your tests are failing.

**Comment by kjavaherpour** [comment]
> @jsadwith looking for your feedback here; it isn't obvious to me why your tests are failing.

Testing locally to get this resolved

**Comment by kjavaherpour** [comment]
@patmmccann Hi Patrick, looks like the test is expecting url encoded strings, while the new function decodes them. We can update the tests to use the decoded strings, or you can (or we can encode them)? Not sure who should, since this is your PR.
```
    function getKrgCrbOldStyle() {
      return '%7B%22v%22%3A%22eyJzeW5jSWRzIjp7IjIiOiI4MmZhMjU1NS01OTY5LTQ2MTQtYjRjZS00ZGNmMTA4MGU5ZjkiLCIxNiI6IlZveElrOEFvSnowQUFFZENleUFBQUFDMiY1MDIiLCIyMyI6ImQyYTg1NWE1LTFiMWMtNDMwMC05NDBlLWE3MDhmYTFmMWJkZSIsIjI0IjoiVm94SWs4QW9KejBBQUVkQ2V5QUFBQUMyJjUwMiIsIjI1IjoiNWVlMjQxMzgtNWUwMy00YjlkLWE5NTMtMzhlODMzZjI4NDlmIiwiMl84MCI6ImQyYTg1NWE1LTFiMWMtNDMwMC05NDBlLWE3MDhmYTFmMWJkZSIsIjJfOTMiOiI1ZWUyNDEzOC01ZTAzLTRiOWQtYTk1My0zOGU4MzNmMjg0OWYifSwibGV4SWQiOiI1ZjEwODgzMS0zMDJkLTExZTctYmY2Yi00NTk1YWNkM2JmNmMiLCJjbGllbnRJZCI6IjI0MTBkOGYyLWMxMTEtNDgxMS04OGE1LTdiNWUxOTBlNDc1ZiIsIm9wdE91dCI6ZmFsc2UsImV4cGlyZVRpbWUiOjE0OTc0NDkzODI2NjgsImxhc3RTeW5jZWRBdCI6MTQ5NzM2Mjk3OTAxMn0=%22%7D';
    }
```

this could be decoded, for example. There are a few other functions that do the same thing (old style). Previously the field `rawCRB` was not decoding the cookies: `rawCRB: spec._readCookie('krg_crb'),` while the new function automatically decodes for us: https://github.com/prebid/Prebid.js/blob/59bc2eafda0c75a2c75a998ff87c801957bdde0c/src/storageManager.js#L104

**Comment by patmmccann** [comment]
@kjavaherpour @jsadwith thanks so much! Could you just pr to `nodoccookie` with your changes to this, or you could do your own pr and I'll remove changes to Kargo from this PR

**Comment by jsadwith** [comment]
@patmmccann here you go: https://github.com/prebid/Prebid.js/pull/8727

**Comment by patmmccann** [comment]
Thanks so much!

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
