### PR TITLE
Prebid 8: IMDS bid adapter - Rename synacormedia adapter

### PR DESCRIPTION
**Pull request by ecammit**
## Type of change
- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
This renames the `synacormedia` adapter to `imds` while allowing existing implementations to continue using `synacormedia`.

## Other information
https://github.com/prebid/prebid.github.io/pull/4237
https://github.com/prebid/prebid-server/pull/2508

### CODE REVIEW

**Comment by ecammit** [comment]
@ChrisHuie Would it be possible to get this reviewed and merged soon?

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
@ecammit please resolve conflicts

**Comment by ecammit** [comment]
> @ecammit please resolve conflicts

@patmmccann Hmm... I didn't see any conflicts. I just merged prebid-8 into it and pushed without issue. Let me know if you're seeing conflicts still because then it's likely I'm missing something.

**Comment by ecammit** [comment]
The **e2etest just needs to be re-run**. I don't have permissions to do that. If the moderators do not have permissions either, let me know and I'll push an empty commit to have the tests re-run. I just don't want to pollute the commit tree with empty commits if I don't have to.

The failure with the e2etest **was from a temporary issue** with browserstack. I ran it myself and it works fine:

```
[firefox 112.0 windows #2-7] Running: firefox (v112.0) on windows
[firefox 112.0 windows #2-7] Session ID: 1371319eed44800dd37b9446ee5c6736a415a729
[firefox 112.0 windows #2-7]
[firefox 112.0 windows #2-7] » /test/spec/e2e/outstream/basic_outstream_video_ad.spec.js
[firefox 112.0 windows #2-7] Prebid.js Outstream Video Ad Test
[firefox 112.0 windows #2-7]    ✓ should load the targeting keys with correct values
[firefox 112.0 windows #2-7]    ✓ should render the video ad on the page
[firefox 112.0 windows #2-7]
[firefox 112.0 windows #2-7] 2 passing (17.1s)


Spec Files:	 21 passed, 3 skipped, 24 total (100% completed) in 00:03:53 

2023-05-02T03:22:00.743Z INFO @wdio/local-runner: Shutting down spawned worker
2023-05-02T03:22:00.995Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-05-02T03:22:00.995Z INFO @wdio/local-runner: shutting down
[23:22:01] Finished 'test' after 3.92 min
[23:22:01] Finished 'e2e-test' after 4.63 min
```

as opposed to the automation's failure:

```
[firefox 112.0 windows #2-7] Running: firefox (v112.0) on windows
[firefox 112.0 windows #2-7] Session ID: 6f21bea227577303159b377737062cc85b6ed41c
[firefox 112.0 windows #2-7]
[firefox 112.0 windows #2-7] » /test/spec/e2e/outstream/basic_outstream_video_ad.spec.js
[firefox 112.0 windows #2-7] Prebid.js Outstream Video Ad Test
[firefox 112.0 windows #2-7]    ✖ "before all" hook for Prebid.js Outstream Video Ad Test
[firefox 112.0 windows #2-7]
[firefox 112.0 windows #2-7] 1 failing (1m 0.8s)
[firefox 112.0 windows #2-7]
[firefox 112.0 windows #2-7] 1) Prebid.js Outstream Video Ad Test "before all" hook for Prebid.js Outstream Video Ad Test
[firefox 112.0 windows #2-7] Timeout of 60000ms exceeded. The execution in the test "Prebid.js Outstream Video Ad Test "before all" hook for "should load the targeting keys with correct values"" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/circleci/Prebid.js/test/spec/e2e/outstream/basic_outstream_video_ad.spec.js)
[firefox 112.0 windows #2-7] Error: Timeout of 60000ms exceeded. The execution in the test "Prebid.js Outstream Video Ad Test "before all" hook for "should load the targeting keys with correct values"" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/circleci/Prebid.js/test/spec/e2e/outstream/basic_outstream_video_ad.spec.js)
[firefox 112.0 windows #2-7]     at createTimeoutError (/home/circleci/Prebid.js/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/errors.js:498:15)
[firefox 112.0 windows #2-7]     at Hook.Runnable._timeoutError (/home/circleci/Prebid.js/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:431:10)
[firefox 112.0 windows #2-7]     at Timeout.<anonymous> (/home/circleci/Prebid.js/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:246:24)
[firefox 112.0 windows #2-7]     at listOnTimeout (internal/timers.js:549:17)
[firefox 112.0 windows #2-7]     at processTimers (internal/timers.js:492:7)


Spec Files:	 20 passed, 1 failed, 3 skipped, 24 total (100% completed) in 00:04:36 

2023-05-01T23:16:25.683Z INFO @wdio/local-runner: Shutting down spawned worker
2023-05-01T23:16:25.934Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-05-01T23:16:25.934Z INFO @wdio/local-runner: shutting down
[23:16:25] 'test' errored after 4.62 min
[23:16:25] Error: Tests failed with error: Error: Command failed: /home/circleci/Prebid.js/node_modules/.bin/wdio /home/circleci/Prebid.js/wdio.conf.js
    at /home/circleci/Prebid.js/gulpfile.js:304:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[23:16:25] 'e2e-test' errored after 5.18 min
```

**Pull request merged**
