### PR TITLE
fix(usersync): corrected usersync url

### PR DESCRIPTION
**Pull request by sourabhg**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Corrected the user sync url

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by jsnellbaker** [comment]
@sourabhg Can you please review your unit tests and make the same change there as well?  There are a few failures in the circleci that have the details to which tests.

**Comment by sourabhg** [comment]
@jsnellbaker  resolved the issues.

**Comment by jsnellbaker** [comment]
@sourabhg Thanks for making the unit test update.  When I tried to test this new sync url just now, I was getting a 404 error from the new sync endpoint.

Can you check on your end?  If there's anything you want me to provide to help investigate, please let me know.

Thanks.

**Comment by sourabhg** [comment]
@jsnellbaker : updated to the correct url https://cdn.deepintent.com/syncpixel.html this is now the latest correct url and it works fine. Please merge.

**Pull request merged**
