### PR TITLE
Add back legacy DFP example and mitigate race condition in instant load

### PR DESCRIPTION
**Pull request by mkendall07**
@prebid/core please review.
CC:
@brondsem
@BartVB
@sonemic
@mercuryyy

### CODE REVIEW

**Comment by brondsem** [comment]
Thanks --- where do the new example pages get linked from?

**Comment by mercuryyy** [comment]
@mkendall07  i just went live with the load_pbjs_dfp_concurrently.html 
I cant spot anything wrong, i'll gather more performance data in the next 24-48 hours, really like this new method of loading prebid and dfp at the same time. 

Can you check my implantation? you should have live url from the email i'v sent you

**Comment by mercuryyy** [comment]
Update: Fill rate improved about 10-15%
bid win rate also 10-15%
adsense ad visibility improved from 44% to 46.5%  (very significant) 

Data from about 1,000,000 impressions after switching to load_pbjs_dfp_concurrently.html

**Comment by mkendall07** [comment]
@brondsem 
Not linked from anywhere yet. I'll make sure once it's merged we have appropriate links on teh prebid.org site and examples updated there. 

@mercuryyy 
Thanks for testing. Sounds like the results are promising. Have you experienced any overall impression loss? That was a concern with the instant load method and what we are trying to combat.

**Comment by mercuryyy** [comment]
@mkendall07 
Yes, Im seeing about 12-13% impression lost. compared to 10% when using with prebid.github.io/dev-docs/examples/simplified-price-bucket-setup.html 
Its high because Prebid timeout at 1999, site has high 59% bounce rate due to 80% is mobile traffic.
So users that change or leave a page within 3-7 seconds will most likely not get a paid impression.

In this specific case the increase in prebid filling more inventory actually increases the overall cpm to counter the impressions lost. But i'd still like to find an optimal way to lower impression lost.

**Comment by mercuryyy** [comment]
@mkendall07 

Also not all browsers support loadScript('//www.googletagservices.com/tag/js/gpt.js');

should add to loadScript function(
        var useSSL = 'https:' == document.location.protocol;
       script.src = (useSSL ? 'https:' : 'http:') +
                'scriptSrc';

or just comment to use full path in loadScript(' ');

**Comment by mkendall07** [comment]
@mercuryyy 
Which browsers don't support protocol-less URLs? According to [this](http://stackoverflow.com/questions/4831741/can-i-change-all-my-http-links-to-just) it's included in the spec and should be safe. 

The `appendChild` API specifies a referenceNode, so it is correct.

**Comment by mercuryyy** [comment]
@mkendall07 

"IE6 does not know how to handle this. If you care about supporting Internet Explorer 6 then you shouldn’t use these.
IE7-8 support protocol relative URLs but they’ll end up fetching the resource twice. Once from HTTP and once over HTTPS."

I Can't find a support chart specifics for all old browsers.

your correct about appendChild

**Comment by mkendall07** [comment]
cool, we don't support anything older than IE 9 with prebid.js.

**Comment by mercuryyy** [comment]
@mkendall07  can you see if prebid_timeout is not being honored in load_pbjs_dfp_concurrently.html

i emailed you an example debug where ads rendered 500ms after prebid timeout value

**Comment by mkendall07** [comment]
It still is being honored, however, the start time is now a bit later (since it's inside of prebid.js and not on the page directly). This means that the timeout will get registered after prebid.js loads and parsed. Seeing ads render 500ms later doesn't seem that out of line to me if you add in the latency required (~100ms load prebid.js, ~50-150ms processing time/lag on bid, ~200ms to call dfp, ~100ms to render ad)... make sense?

**Comment by mercuryyy** [comment]
@mkendall07 

screen shot 2016-08-26 at 9 23 23 am

**Comment by mercuryyy** [comment]
@mkendall07  on load_pbjs_before_dfp_example.html  on the first load it does not load ads and finish loading prebid, last debug msg "Attempting to set key value for slot" ...
action end never hits, then on the second pageload it works fine.

another note:

when using load_pbjs_dfp_concurrently.html avg pageload time in google analytics is 9.2-9.5
when using  load_pbjs_before_dfp_example.html avg page load time in google analytics is 7.59-8.00

i would think loading dfp and prebid at the same time will give a better overall pageload time or else whats the point of it?

**Comment by mercuryyy** [comment]
PREBID TIMEOUT is definitely ignored in the load_pbjs_dfp_concurrently.html  example

**Pull request merged**
