### PR TITLE
Trigger AUCTION_DEBUG from utils.logWarn with type set to WARNING

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [ X ] Feature

## Description of change
Trigger AUCTION_DEBUG from utils.logWarn with type set to WARNING, this will help publishers/analytics adapters collect the warnings together.

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
@jsnellbaker , I need some help here, https://github.com/prebid/Prebid.js/blob/master/test/spec/AnalyticsAdapter_spec.js#L45 this test case fails with the change made. Am not sure why it fails and how to fix it :(

**Comment by patmmccann** [comment]
Closely related to https://github.com/prebid/Prebid.js/pull/5563

FYI @ofirpaBrowsi @GLStephen @harpere

**Review by harpere — COMMENTED** [review]
LGTM other than the broken test.

**Comment by jsnellbaker** [comment]
> @jsnellbaker , I need some help here, https://github.com/prebid/Prebid.js/blob/master/test/spec/AnalyticsAdapter_spec.js#L45 this test case fails with the change made. Am not sure why it fails and how to fix it :(

Can you try to flip the order of the `args` and `eventType` params in the AnaltyicsAdapter_spec file's expect statements (in the `deep.equal` target value)?  I've seen the deep equal verification gets picky sometimes.

**Review by harpere — APPROVED** [review]

**Comment by pm-harshad-mane** [comment]
@jsnellbaker thank you for the feedback.
As we are triggering the AUCTION_DEBUG for warning calls, there were more event records in the array before the expected event in the test case, I have made the required change in the test case.

**Comment by pm-harshad-mane** [comment]
Thank you @harpere for merging the PR.

**Pull request merged**
