### PR TITLE
WINR Bid Adapter: add new bid adapter

### PR DESCRIPTION
**Pull request by winrdev**
## Type of change

- [x] New bidder adapter   

## Description of change

- test parameters for validating bids
```
var adUnits = [
  {
    code: "winr-demo",
    mediaTypes: {
      banner: {
        sizes: [[1, 1]],
      },
    },
    bids: [
      {
        bidder: "winr",
        params: {
          placementId: 21764100,
          domParent: ".blog-post",
          child: 4,
        },
      },
    ],
  },
];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: tech@winr.com.au
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/3042

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@winrdev I don't think I have come across a bid adapter that wraps a bid with custom scripts and html in this way before. Not sure how comfortable I am at returning a template string with executable code

**Comment by winrdev** [comment]
> @winrdev I don't think I have come across a bid adapter that wraps a bid with custom scripts and html in this way before. Not sure how comfortable I am at returning a template string with executable code. Will probably have to bring this pr up in the next prebid javascript meeting

@ChrisHuie We understand your concerns, however our ad units are unique in that they have a specific set of features outside of what traditional ads provide. These include features such as the ability to behave like a paywall in terms of temporarily redacting part of the article content. We have a one-to-one relationship with our publishers, given the unique nature of our content.

I hope this helps to resolve some of your concerns. We also noticed a few other adapters using a similar approach with bid wrapping i.e. Vox, AstraOne, TE Medya, FreeWheel and hybrid.ai

**Comment by ChrisHuie** [comment]
@winrdev confirmed this is ok. Merging this pr later today. Thanks for your patience on it :)

**Review by ChrisHuie — APPROVED** [review]

**Comment by winrdev** [comment]
Many thanks @ChrisHuie :)

**Pull request merged**
