### PR TITLE
topRTBBidAdapter: Can't automatically merge

### PR DESCRIPTION
**Pull request by Unnamalai57**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by Unnamalai57** [comment]
Can't automatically merge.

**Comment by bretg** [comment]
@Unnamalai57 - please help us understand what is this PR. topRTBBidAdapter.js and topRTBBidAdapter.md files already exist. What changes are you trying to make that "can't be merged"?

**Comment by Unnamalai57** [comment]
> @Unnamalai57 - please help us understand what is this PR. topRTBBidAdapter.js and topRTBBidAdapter.md files already exist. What changes are you trying to make that "can't be merged"?

Hi I have just changed adunitId in topRTBBidAdapter.md to produce valid bidResponse. Because the existing adunitId is not valid now.

**Comment by mike-chowla** [comment]
We need a mergeable pull request.  This one is re-adding all topRTBBidAdapter files and thus can not be merged.  I'm going to close this one.  Please open a new one with just the new changes.

**Pull request closed without merging**
