### PR TITLE
NoBid Analytics Adapter: initial release

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New Analytics adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

This is a new Analytics adapter.

### CODE REVIEW

**Comment by patmmccann** [comment]
we require 90% coverage or better; please leave this is draft until you add unit tests.

**Comment by redaguermas** [comment]
Hello @patmmccann ,
We added the unit tests. Can you please review?

**Comment by Rothalack** [comment]
Hey @redaguermas , you should get a PR up to update the docs for this as well.

https://docs.prebid.org/overview/analytics.html

**Comment by redaguermas** [comment]
Both files have been committed.
Website PR: https://github.com/prebid/prebid.github.io/pull/4821

**Review by Rothalack — APPROVED** [review]
Looks good, works in testing

**Pull request merged**
