### PR TITLE
Adnuntius Bid Adapter: Option to set TZO on a bidder and CPC price

### PR DESCRIPTION
**Pull request by mikael-lundin**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by mikael-lundin** [comment]
I see that test is failing, but not for my adaptor changes. :)

**Comment by mike-chowla** [comment]
Please remove the changes the package-lock.jso and resolve the merge conflicts

**Comment by mikael-lundin** [comment]
I think that I've managed to fix this. :)

**Comment by GLStephen** [comment]
@mikael-lundin there are till package-lock changes that need to be resolved, try checkout out the package-lock.json file from master and then doing "npm ci" then check back in.

**Comment by smenzer** [comment]
@mikael-lundin I would suggest that you rebase on current version of master to get rid of all the extra committed files in this PR

**Pull request closed without merging**
