### PR TITLE
Add user sync

### PR DESCRIPTION
**Pull request by Adprime**
## Type of change
- [x] Feature

## Description of change

Enable user syncing

### CODE REVIEW

**Comment by Adprime** [comment]
There is error inside prebidServerBidAdapter
`/home/circleci/Prebid.js/modules/prebidServerBidAdapter/index.js
  204:14  error  '_s2sConfig' is not defined  no-undef
  205:24  error  '_s2sConfig' is not defined  no-undef`
Does it appear in my PR due to some diverges in our repo, or it's currently exists in prebid.js master branch and will be fixed soon?

**Comment by harpere** [comment]
I don't see this error running tests locally on the master branch, and don't see it in other PRs.  So maybe something about your fork?

**Comment by Adprime** [comment]
@harpere I think those errors were fixed before your review, i've merged with upstream and now they are gone, but new one appeared

**Comment by harpere** [comment]
@Adprime this test error should have been fixed in master.  So please pull in the latest from master so the tests can rerun and hopefully succeed.

**Review by harpere — APPROVED** [review]

**Pull request merged**
