### PR TITLE
WIP: Fledge support

### PR DESCRIPTION
**Pull request by brodrigu**
## Type of change
- [x] Feature

## Description of change
Google is working with the W3C on a proposal to support advertising in a 3rd-party cookie-less world called [Turtledove/Fledge](https://github.com/WICG/turtledove/blob/main/FLEDGE.md). This feature adds support for running these new client side auctions before rendering a winning ad.

This PR is an iteration on top of #7189 by @iamnewton. The following changes have been made from his initial PR:
* module has been renamed to 'Private Client Auction'. There are multiple proposals in this space and we expect multiple iterations; a more generic name will make updates easier and keep renaming to a minimum.
* polyfill integration has been removed. This initial PR imagines what the prebid support would look like if Fledge was generally available today and based on the current proposal details. Polyfill support can be added outside of prebid, or included as an extension in a future PR.
* a configuration for `supportedAuctionTypes` has been added with current support only for fledge. In the future, parakeet or other client side auctions could be enabled here.

This is a working draft, so there are no tests currently available. If feedback on core implementation is positive, the PR will be updated with all requirements before merge.

## Other information
[Fledge proposal](https://github.com/WICG/turtledove/blob/main/FLEDGE.md)
[Fenced Frame Fledge Example](https://github.com/shivanigithub/fenced-frame/blob/master/OpaqueSrc.md)
[How Fledge could work with Prebid](https://github.com/JoelPM/prebid-td/blob/main/PrebidFledge.md)
#7189 
#7634

### CODE REVIEW

**Comment by vincent-grosbois** [comment]
hello !
are there any news on this PR ? it's something that we would interest us !

**Comment by dzhang-criteo** [comment]
Hello,

I would like to know if there are any plans of pursuing the idea of implementing a Fledge module into Prebid or has it been abandoned?

**Comment by brodrigu** [comment]
not abandoned, was awaiting feedback and holidays go in the way of making progress. Since there are no issues and some interest, I will schedule work to add necessary testing / documentation and attempt to get this merged.

**Comment by brodrigu** [comment]
The chrome team has taken feedback and [altered their proposal to support multiple SSPs](https://github.com/WICG/turtledove/pull/251) within the on-device auction and @JoelPM has [drafted a possible prebid.js module framework](https://github.com/JoelPM/prebid-td/blob/main/PrebidFledge.md) for participation in the auction.

These developments have rendered this PR obsolete and as a result I am closing it. Feel free to reuse any code written here if you find it useful.

**Pull request closed without merging**
