### PR TITLE
Yahoo Ads Bid Adapter: Fix to not set bidResponse vastUrl field with bid nurl value

### PR DESCRIPTION
**Pull request by zach-bowman**
## Type of change

- [x] Bugfix
- [ ] Updated bidder adapter   

## Description of change

This PR fixes undesired behavior within the `YahooAdsBidAdapter` (per Yahoo business/product) which incorrectly sets the `bidResponse.vastUrl` field with `bid.nurl` value. `YahooAdsBidAdapter` is updated to remove the setting of the  `bidResponse.vastUrl` field as well as removes the associated test. At present [with this change], the `YahooAdsBidAdapter` should _not consume the nurl in any case_ nor _provide creative responses in the nurl field_.

## Other information
Contact Email: [prebid-tech-team@yahooinc.com](mailto:prebid-tech-team@yahooinc.com)

### CODE REVIEW

**Comment by patmmccann** [comment]
Cc @slimkrazy @radubarbos

**Comment by radubarbos** [comment]
LGTM

**Comment by zach-bowman** [comment]
Hi all, I just wanted to ask about the failing "Check for Duplicated Code" item above -- since it appears that some of the logic we have is now used by another adapter -- should I still extract the duplicated code? I just wanted to make sure this is the appropriate path forward as we would then share our intended specific logic across adapters (which may change). Happy to do so if this is the case (new to contributing, so just wanted to make sure). Same with https://github.com/prebid/Prebid.js/pull/12139 . Thanks in advance for the input!

**Comment by zach-bowman** [comment]
Hi reviewers, I just wanted to followup on the above question. In short: as I attempted to address the failing check, it seemed incorrect to remove that logic from our adapter as well as touch another adapter -- as this should be specific and subject to change per company. Let me know your suggestion on how to best address this so we can get this change out. Thanks so much in advance!

**Review by aishwaryapatil — APPROVED** [review]

**Comment by zach-bowman** [comment]
> Hi reviewers, I just wanted to followup on the above question. In short: as I attempted to address the failing check, it seemed incorrect to remove that logic from our adapter as well as touch another adapter -- as this should be specific and subject to change per company. Let me know your suggestion on how to best address this so we can get this change out. Thanks so much in advance!

Hi -- just wanted to followup to see if there's any advice on the above to get this PR through -- thanks again!

**Comment by patmmccann** [comment]
> - since it appears that some of the logic we have is now used by another adapter -- should I still extract the duplicated code? I just wanted to make sure this is the appropriate path forward as we would then share our intended specific logic across adapters

This would be much appreciated, we're hoping to improve maintainability and bundle size!

**Review by patmmccann — APPROVED** [review]

**Comment by zach-bowman** [comment]
Thank you!

**Pull request merged**
