### PR TITLE
Colossus SSP Bidder Adapter: add onBidWon()

### PR DESCRIPTION
**Pull request by HuddledMasses**
- [x] Feature

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@HuddledMasses assuming huddled masses and Colussus SSP is the same? Just confirming.

**Comment by HuddledMasses** [comment]
@ChrisHuie huddled masses adapter (https://docs.prebid.org/dev-docs/bidders/huddledmasses) no longer valid

**Comment by ChrisHuie** [comment]
@HuddledMasses can you add a unit test for this and should be good?

**Comment by HuddledMasses** [comment]
@ChrisHuie we added unit tests

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
