### PR TITLE
Core & multiple modules: collect granular timing metrics for auctions, requests, responses

### PR DESCRIPTION
**Pull request by dgirardi**
## Type of change

- [x] Feature

## Description of change

This adds:
 -  a new `metrics` object to auctions, bid requests, and bid responses;
 -  new logic to measure the time spent in various parts of their lifecycles;
 - a new config option, `performanceMetrics`, that when set to false disables the above (measuring logic is skipped and each `metrics` object will be left empty).

Within a given auction, these metrics objects are related, with the intent of making most data available regardless of where you're getting them from. As an example, these are the `metrics` attached to an auction's winning bid (all numbers are milliseconds):

```json
{
  "userId.init.gdpr": [0],
  "userId.mod.init": [5, 1, 8, 9, 1],
  "userId.mods.connectId.init": [5],
  "userId.mods.criteo.init": [1],
  "userId.mods.id5Id.init": [8],
  "userId.mods.sharedId.init": [9],
  "userId.mods.unifiedId.init": [1],
  "userId.init.modules": [29],
  "userId.callbacks.pending": [3594],
  "userId.total": [3653],
  "requestBids.userId": 2,
  "requestBids.pubCommonId": 1,
  "requestBids.fpd": 2,
  "requestBids.validate": 1,
  "requestBids.makeRequests": 30,
  "requestBids.total": 580,
  "requestBids.callBids": 536,
  "adapter.s2s.buildRequests": 2,
  "adapters.s2s.appnexus.buildRequests": 2,
  "adapter.s2s.net": 410,
  "adapters.s2s.appnexus.net": 410,
  "adapter.s2s.interpretResponse": 1,
  "adapters.s2s.appnexus.interpretResponse": 1,
  "adapter.s2s.total": 428,
  "adapters.s2s.appnexus.total": 428,
  "addBidResponse.validate": 0,
  "addBidResponse.currency": 0,
  "addBidResponse.categoryTranslation": 0,
  "addBidResponse.dchain": 0,
  "addBidResponse.mass": 0,
  "addBidResponse.multibid": 0,
  "addBidResponse.total": 2,
  "render.pending": 2904,
  "render.e2e": 3484
}
```

And these are those attached to the auction, more or less a superset that also contain info about requests / responses that did not win:

```json
{
  "userId.init.gdpr": [0],
  "userId.mod.init": [5, 1, 8, 9, 1],
  "userId.mods.connectId.init": [5],
  "userId.mods.criteo.init": [1],
  "userId.mods.id5Id.init": [8],
  "userId.mods.sharedId.init": [9],
  "userId.mods.unifiedId.init": [1],
  "userId.init.modules": [29],
  "userId.callbacks.pending": [3594],
  "userId.total": [3653],
  "adapter.s2s.buildRequests": [2],
  "adapters.s2s.appnexus.buildRequests": [2],
  "adapter.client.validate": [0, 0],
  "adapters.client.grid.validate": [0],
  "adapter.client.buildRequests": [1, 1],
  "adapters.client.grid.buildRequests": [1],
  "adapters.client.adplus.validate": [0],
  "adapters.client.adplus.buildRequests": [1],
  "adapter.s2s.net": [410],
  "adapters.s2s.appnexus.net": [410],
  "adapter.s2s.interpretResponse": [1],
  "adapters.s2s.appnexus.interpretResponse": [1],
  "addBidResponse.validate": [0, 0, 0],
  "addBidResponse.currency": [0, 0, 0],
  "addBidResponse.categoryTranslation": [0, 0, 0],
  "addBidResponse.dchain": [0, 0, 0],
  "addBidResponse.mass": [0, 0, 0],
  "addBidResponse.multibid": [0, 0, 0],
  "addBidResponse.total": [2, 4, 2],
  "adapter.s2s.total": [428],
  "adapters.s2s.appnexus.total": [428],
  "adapter.client.net": [443, 492],
  "adapters.client.grid.net": [443],
  "adapter.client.interpretResponse": [0, 0],
  "adapters.client.grid.interpretResponse": [0],
  "adapter.client.total": [451, 498],
  "adapters.client.grid.total": [451],
  "adapters.client.adplus.net": [492],
  "adapters.client.adplus.interpretResponse": [0],
  "adapters.client.adplus.total": [498],
  "render.pending": [2904],
  "render.e2e": [3484],
  "requestBids.userId": 2,
  "requestBids.pubCommonId": 1,
  "requestBids.fpd": 2,
  "requestBids.validate": 1,
  "requestBids.makeRequests": 30,
  "requestBids.total": 580,
  "requestBids.callBids": 536
}
```

## Other information

Closes https://github.com/prebid/Prebid.js/issues/8776
Documentation https://github.com/prebid/prebid.github.io/pull/4015

### CODE REVIEW

**Comment by robertrmartinez** [comment]
I absolutely love this feature.

We did a similar test around a small subset of these metrics to do some analysis on how long things took.

Much smaller set of metrics, and since it was a fork we only ran it for a little bit.

This is such interesting data and can help us greatly optimize how we utilize prebid!

I will give this a good testing and review, but my only quick thing is should this be an optional module / feature?

It is quite a lot of data and some analytics adapters simply forward whatever prebid events emit to their endpoint, so this could possible add a decent amount of data to their storage.

**Comment by dgirardi** [comment]
I'll defer to your opinion on whether this should be optional - since this is the type of data you'd look at when you have a problem to solve, I thought it wouldn't work well as something you have to enable after the fact. But I am used to storage being basically free, so if  that's not the case then obviously can be a problem.

**Comment by robertrmartinez** [comment]
We only pick out specific things to send to our pipeline, so for me it is not a problem.

Maybe we can ask a couple adapters who would be affected.

Maybe just making an opt-out option or something?

The performance impact of just this measuring part should be pretty negligible right?

@patmmccann any input?

**Comment by dgirardi** [comment]
Just discussed this with @bretg and @patmmccann; we agreed that there should be a way to opt-out, but that the data should be available by default and analytics adapters have the responsibility of picking and choosing what they are interested in.

**Review by robertrmartinez — APPROVED** [review]
Awesome looks great.

To disable:
```js
pbjs.setConfig({
   performanceMetrics: false
});
```

Which makes `metrics` object still comes on events, just when using `getMetrics` or `toJSON` it returns empty object since no metrics were kept.

This will be in docs somewhere I guess?

Really cool though, can't wait to leverage these in our analytics system.

**Review by Rothalack — APPROVED** [review]
My only input was to ask if this should be off by default or not, but you guys already hashed that out. I trust your judgements on that.

Looks good to me!

**Pull request merged**
