### PR TITLE
NPM usage doc: Add resolve.extensions

### PR DESCRIPTION
**Pull request by ckybonist**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change

Add `resolve.extensions` to the [section](https://github.com/prebid/Prebid.js#usage-as-a-npm-dependency)

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

- https://github.com/prebid/Prebid.js/blob/master/src/utils.js#L6
- https://github.com/prebid/Prebid.js/blob/master/src/constants.json

### CODE REVIEW

**Comment by snapwich** [comment]
Does webpack not resolve `.js` and `.json` files by default? I'm pretty sure it does.

**Comment by ckybonist** [comment]
> Does webpack not resolve `.js` and `.json` files by default? I'm pretty sure it does.

Absolutely [it does](https://webpack.js.org/configuration/resolve/#resolveextensions).

However, IMHO, users who maintain typescript-based projects (like me) would definitely specify the `resolve.extensions` for `.ts`; Without the clear documentation, we have to dig into `node_modules/prebid.js` to find out which file causing the error, moreover, the webpack error logs 
 can't even tell us the actual reason why I get tripped...

```
Module not found: Error: Can't resolve '../src/constants' 
in '/Users/FatCat/my-project/node_modules/prebid.js/modules'

// Multiple errors...
```
NOTE: no extension at `../src/constants`

**Comment by snapwich** [comment]
So you're saying you changed `resolve.extensions` to `.ts` and it caused Prebid.js modules to not be found? Seems like expected behavior (hindsight is 20/20 I know).

I'd rather not specify default configuration, or configuration at all, in the webpack config that doesn't relate specifically to Prebid.js as that would include _A LOT_ of stuff besides just resolving extensions depending on what people are doing with webpack.

If being explicit in our code and manually specifying the `.js` extensions in all Prebid.js imports works around this gotcha, that seems like a better solution. Then we can add this [ESLint rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md) that ensures that all code going forward uses extensions.

**Comment by snapwich** [comment]
this issue should be resolved by #4876 being merged. let me know if this doesn't work for you.

**Comment by ckybonist** [comment]
Actually, I changed `resolve.extensions` to `['.js', '.ts']` at first and that's why I get the errors (missing `.json`).

Thanks for specifying all module extension explicitly! That's truly a BIG PR. 

Waiting for next stable release!

**Pull request closed without merging**
