### PR TITLE
add video auction support

### PR DESCRIPTION
**Pull request by fndigrazia**
## Type of change
- [ x ] Feature

## Description of change
Adding support for video auction in E-Planning adapter

ndigrazia@e-planning.net
- [ x] official adapter submission

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@fndigrazia I tried to kick off our integration testing with this pr but looks like you are currently following your fork in circleci instead of the main prebid project. If you unfollow your fork the circleci tests should automatically run the correct way :)

**Comment by ChrisHuie** [comment]
@fndigrazia let me try to kickoff the tests again and if I can't I will just resubmit under my account in a new pr

**Comment by sebaperez** [comment]
Hi @ChrisHuie, did you have a chance to look at this? It would be great if you can kickoff the test again or resubmit this under a new pr

**Comment by ChrisHuie** [comment]
> Hi @ChrisHuie, did you have a chance to look at this? It would be great if you can kickoff the test again or resubmit this in a new pr

I will resubmit today :)

**Pull request closed without merging**
