### PR TITLE
Dgkeyword Rtd Provider: add new real-time data submodule

### PR DESCRIPTION
**Pull request by mediaconsortium-develop**
## Type of change

- [ X ] Feature
https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders --> 
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ X ] Other

## Description of change

We want to add Real Time Data Submodule

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.
https://www.suuiiisya.com/test/agytest/rt_module_test.html

- contact email of the adapter’s maintainer
mediaconsortium-develop@bi.garage.co.jp

- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/mediaconsortium-develop/Prebid.js/blob/feature/dgkeywordRtdProvider/modules/dgkeywordRtdProvider.md

## Other information

we want to set some keywords before requestBids() in our customer's site.
The keywords are real time data and can be got to access our partner's service site.
So we want to start requestBids() after getting keywords only when our keywords service use.

### CODE REVIEW

**Comment by patmmccann** [comment]
This is really interesting. 

A few questions: 

https://mediaconsortium.profiles.tagger.opecloud.com/api/v1?url=https://cnn.com doesnt seem to return anything of note, is this by design? 

It appears your spec file requires the endpoint to actually be live and operational; is there anyway to remove this requirement?

Instead of just copying these keywords to the bidder params, can you copy data into the openrtb object, eg as per https://github.com/prebid/Prebid.js/issues/6057 and https://github.com/prebid/Prebid.js/issues/5795 ? Bidders should be reading from it instead of their params when available.

**Comment by mediaconsortium-develop** [comment]
Thank you very much for your quick response.

https://mediaconsortium.profiles.tagger.opecloud.com/api/v1?url=https://cnn.com
doesnt
seem to return anything of note, is this by design?
Yes.
to get keywords from our partners API service, we need to use cookie.
and if the client has no cookie, no keywords can get.

It appears your spec file requires the endpoint to actually be live and
operational; is there anyway to remove this requirement?
No, our service to get keywords requires realtime access to the API.
So, only when the publisher site wants to use our dgkeywords service,
requestBids() should delay until our dgkeywords service finish to send the
api responses.

Regards.

2021年3月16日(火) 1:30 'Patrick McCann' via
***@***.*** <
***@***.***>:

**Comment by patmmccann** [comment]
Sorry, by spec file i meant the test file

**Comment by patmmccann** [comment]
The third point I was making is that modules should do a getConfig on the ORTB object, then add their data to the global so that all adapters can grab your keywords, not just Xandr. Can you change to be compatible with #5795 ?

**Comment by mediaconsortium-develop** [comment]
>by spec file i meant the test file
I changed not to access actual endpoint.

> The third point I was making is that modules should do a getConfig on the ORTB object, then add their data to the global so that all adapters can grab your keywords, not just Xandr. Can you change to be compatible with #5795 ?
you mean the keywords which can get our keywords api service should
set grobal to be able to use some another bidders?
our keywords api service can only use xandr because xandr have
contract with the company of keywords api service.
So xandr can get the meaning of keywords from keywords api service,
and only xandr can treat the keywords.
If the keywords are set on the grobal, no other bidder can use the keywords.
For the reason, we set keywords on the adUnits params. Is it possible?


2021年3月17日(水) 2:13 'Patrick McCann' via
***@***.***
***@***.***>:

**Comment by patmmccann** [comment]
Are you saying publishers do not contract with Digital Garage, only Xandr? Publishers generally prefer all bidders can access information that would improve their ability to bid.

**Comment by mediaconsortium-develop** [comment]
Digital Garage has contact with Xandr and keywords service API.
and more, Xandr also have contact with keywords service API.
So, only Digital Garage can use keywords service API using Xandr bidder.

2021年3月19日(金) 4:23 'Patrick McCann' via
***@***.*** <
***@***.***>:

**Comment by mediaconsortium-develop** [comment]
Are there any other questions about our sub module?

We hope the sub module can select and use from prebid.js download site as
soon as possible.
Thank you very much for your cooperation of reviewing.

2021年3月19日(金) 11:41 山内健生 ***@***.***>:

**Review by osazos — CHANGES_REQUESTED** [review]
Hi @mediaconsortium-develop

If I understood correctly, the module works only with AppNexusBidAdapter. In this case you should explicitly explain it in your Readme and in the docs repo.

In addition to the use of the `ajax()` function as I wrote in the code comments, please improve your tests to have a coverage rate of at least 80%.

Your low score is mainly due to the fact you don't test a 200 response case from your endpoint. If needed, take example on the haloRtdProvider test cases.
By the way, I draw your attention to the fact that your tests "should get profiles …" have no assertions and test nothing for now.

**Comment by patmmccann** [comment]
Regarding your dependency on Xandr; we'll have to discuss in committee this particular case, as rtd submodules are expected to work with all bidders currently.

**Comment by mediaconsortium-develop** [comment]
Hi @osazos

Thank you for your review.

>If I understood correctly, the module works only with AppNexusBidAdapter.
In this case you should explicitly explain it in your Readme and in the
docs repo.
I write to dgkeywordRtdProvider.md like that.

>In addition to the use of the ajax() function as I wrote in the code
comments
I have changed to use ajax(), now we ask our patner to be able to access
the api using XMLHttpRequest.
Will you please wait for the response of our partner.

>please improve your tests to have a coverage rate of at least 80%.
We update test code, and we add 200 status code test with
'test/mock/xhr.js'.
「get profile test」 works well.
Thank you very much for telling sample.



2021年3月23日(火) 22:25 'Patrick McCann' via
***@***.*** <
***@***.***>:

**Comment by mediaconsortium-develop** [comment]
>Regarding your dependency on Xandr; we'll have to discuss in committee
this particular case, as rtd submodules are expected to work with all
bidders currently.
As you know, We feel haloRtdProvider is alike to our sub module.
* haloRtdProvider can work appnexus and adBuzz?.
we appreciate your discussion better for us.

2021年3月29日(月) 13:48 山内健生 ***@***.***>:

**Comment by patmmccann** [comment]
But the halo id also writes to the generic object, not just the appnexus adapter.

https://github.com/prebid/Prebid.js/blob/master/modules/haloRtdProvider.js#L60

**Comment by mediaconsortium-develop** [comment]
>But the halo id also writes to the generic object, not just the appnexus
adapter.
our sub module also writes keywords to the params object of all bidder
adUnits in which set  params: { dgkeyword: true }.
Just now only appnexus hava contact with keywords api service and can only
work well.

2021年3月30日(火) 5:18 'Patrick McCann' via
***@***.*** <
***@***.***>:

**Review by bretg — CHANGES_REQUESTED** [review]

**Comment by bretg** [comment]
This has been discussed in Prebid committee. We are not going to accept RTD modules that work only with specific bidders. Maybe you can work with others, but the documentation specifically mentions a bidder and is generally hard to read. It's really important that keywords should be written to the global location, not bidder-specific locations.

The workaround is easy, just merge your keywords into ortb2.site.keywords or ortb2.user.keywords:
- getConfig("ortb2")
- merge your keywords
- setConfig()

Or if your keywords are sensitive to specific bidders, an option to let the publishers define the bidders and then using setBidderConfig should work.

**Comment by mediaconsortium-develop** [comment]
As you requested, we tried.setConfig() ortb2.user or ortb2.siteFor example
setConfig({ ortb2: { user: { keywords: keywords } } });
The result: Keywords are not activated for AppNexus bidder from prebid
request.We think it does not work because it does not get keywords
from ortb2.user or ortb2.site in appnexusBidAdapter.js. At the same time,
we think appnexusBidAdapter.js is able to get keywords if we do
like gridBidAdapter.js.Is my understanding correct?In order to set keywords
by not editing appnexusBidAdapter.js, we think we need to
use adUnit.params.keywords.I sincerely thank you for your help.

2021年4月2日(金) 1:21 'bretg' via ***@***.*** <
***@***.***>:

**Comment by patmmccann** [comment]
You are correct in that appnexus adapter is not yet reading from ortb2 object. You are welcome to set both objects instead of just ortb2 object. See Sirdata for an example.

**Comment by mediaconsortium-develop** [comment]
Thank you for your response.
We will set the keywords both ortb2 (use setBidderConfig) and
adUnts.params.keywords(as we wrote in this pull request).
Is it OK?

>See Sirdata for an example.
I can not find "Sirdata" in Prebid.js github source code.




2021年4月17日(土) 1:02 'Patrick McCann' via
***@***.*** <
***@***.***>:

**Comment by patmmccann** [comment]
See #6515

**Comment by mediaconsortium-develop** [comment]
>See #6515
Thank you.

As Sirdata, we will set keywords both on ortb2 and adUnits.bidder.params.

2021年4月19日(月) 19:43 'Patrick McCann' via
***@***.***
***@***.***>:
>
> See #6515
>
> On Mon, Apr 19, 2021, 6:41 AM mediaconsortium-develop <

**Comment by mediaconsortium-develop** [comment]
I changed to set keywords using setBidderConfig() on ortb2.
Will you please check our pull request.

https://github.com/prebid/Prebid.js/pull/6410/commits

Regards.

2021年4月24日(土) 11:23 山内健生 ***@***.***>:
>
> >See #6515
> Thank you.
>
> As Sirdata, we will set keywords both on ortb2 and adUnits.bidder.params.
>
> 2021年4月19日(月) 19:43 'Patrick McCann' via
> ***@***.***
> ***@***.***>:
> >
> > See #6515
> >
> > On Mon, Apr 19, 2021, 6:41 AM mediaconsortium-develop <

**Comment by mediaconsortium-develop** [comment]
we finished to fix circle ci tests.
in our "dgkeyword" submodule, circle ci tests passed.
※ there are some errors in another module.

2021年5月11日(火) 21:17 'Patrick McCann' via
***@***.*** <
***@***.***>:

**Comment by patmmccann** [comment]
@osazos are you able to take another look?

**Comment by osazos** [comment]
Hi @mediaconsortium-develop,

Your PR has been merged but still got CircleCI issues and we had to revert it. Sorry for inconvenience.

Please try to fix it and reopen the PR.

Here the report from CI:

```
[17:49:54] Using gulpfile ~/Prebid.js/gulpfile.js
[17:49:54] Starting 'test'...
[17:49:54] Starting 'clean'...
[17:49:54] Finished 'clean' after 13 ms
[17:49:54] Starting 'lint'...
[17:50:23] Finished 'lint' after 29 s
[17:50:23] Starting 'test'...
⚠ ｢wdm｣: 
ℹ ｢wdm｣: Compiled with warnings.
ℹ ｢wdm｣: Compiling...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
⚠ ｢wdm｣: 
ℹ ｢wdm｣: Compiled with warnings.
26 05 2021 17:51:11.919:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
26 05 2021 17:51:11.920:INFO [launcher]: Launching browsers bs_edge_17_windows_10, bs_edge_18_windows_10, bs_ie_11_windows_10, bs_chrome_89_windows_10, bs_chrome_79_windows_10, bs_firefox_73_windows_10, bs_firefox_72_windows_10, bs_safari_11_mac_catalina, bs_safari_12_mac_mojave with concurrency 5
BrowserStackTunnel: binary not present
26 05 2021 17:51:11.939:INFO [launcher]: Starting browser edge 17.0 (Windows 10) on BrowserStack
26 05 2021 17:51:11.940:INFO [launcher]: Starting browser edge 18.0 (Windows 10) on BrowserStack
26 05 2021 17:51:11.940:INFO [launcher]: Starting browser ie 11.0 (Windows 10) on BrowserStack
26 05 2021 17:51:11.940:INFO [launcher]: Starting browser chrome 89.0 (Windows 10) on BrowserStack
26 05 2021 17:51:11.941:INFO [launcher]: Starting browser chrome 79.0 (Windows 10) on BrowserStack
BrowserStackTunnel: download binary for linux-x64 ...
BrowserStackTunnel: download complete
BrowserStackTunnel: chmod 0755 binary
26 05 2021 17:51:17.075:INFO [launcher.browserstack]: edge 18.0 (Windows 10) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/576bfc4d021e82806bf3b38d80adf25ad46de923
26 05 2021 17:51:17.075:INFO [launcher.browserstack]: chrome 79.0 (Windows 10) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/b38d5878b3a115c333787bce41da22aa43f094a1
26 05 2021 17:51:17.075:INFO [launcher.browserstack]: chrome 89.0 (Windows 10) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/f9fe510bb9cf0ae18a45191412e1e1557ac1de57
26 05 2021 17:51:17.075:INFO [launcher.browserstack]: ie 11.0 (Windows 10) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/268e1a3470b00adc111a94b1a084f91297bcb63f
26 05 2021 17:51:17.075:INFO [launcher.browserstack]: edge 17.0 (Windows 10) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/7a26cb3eab01f41687b9ba919164dedc03d11932
26 05 2021 17:51:28.939:INFO [Chrome 79.0.3945 (Windows 10.0.0)]: Connected on socket cPguwWTNFXpK00ucAAAA with id 48046166
26 05 2021 17:51:35.886:INFO [Edge 18.18363.0 (Windows 10.0.0)]: Connected on socket NOJZudytcAVI12QkAAAB with id 36708287
26 05 2021 17:51:38.518:INFO [Chrome 89.0.4389 (Windows 10.0.0)]: Connected on socket KpWBP4Kg9Z8oAqU7AAAC with id 19910188

  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses
  ✗ "before each" hook
	Error: Uncaught AssertionError: expected { Object (opeaud, opectx) } to be an undefined (node_modules/chai/chai.js:239)


  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`
26 05 2021 17:51:49.379:WARN [web-server]: 404: /someURL
26 05 2021 17:51:49.381:WARN [web-server]: 404: /someURL1

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses

  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses

  LoopMeAdapter
    interpretResponse
      - should return valid response when passed valid server response
26 05 2021 17:51:54.495:WARN [web-server]: 404: /undefined
  ✗ "before each" hook
	Error: Uncaught AssertionError: expected { Object (opeaud, opectx) } to be an undefined (node_modules/chai/chai.js:239)


  invibesBidAdapter:
    ✗ "before each" hook for "should send oi = 2 when gdpr doesn't apply or has global consent"
	TypeError: Cannot read property 'call' of undefined


  Invisibly Analytics Adapter test suite
    Invisibly Analytic tests specs
      ✗ "after each" hook for "auction init event"
	TypeError: events.getEvents.restore is not a function
	    at Context.<anonymous> (webpack:///test/spec/modules/invisiblyAnalyticsAdapter_spec.js:182:24 <- test/test_index.js:257452:24)


  Publisher Common ID
    Configuration
      - disable auto create

  PubMatic adapter
    implementation
      Request formation
        - test flag set to 1 when pubmaticTest=true is present in page url
26 05 2021 17:52:02.880:INFO [launcher]: Starting browser firefox 73.0 (Windows 10) on BrowserStack

  RealVu
    Analytics Adapter.
      - isInView returns "yes"
Chrome 79.0.3945 (Windows 10.0.0) LOG LOG: [Object{method: 'GET', url: 'https://api.relaido.jp/bid/v1/prebid/100000', data: Object{version: ..., timeout_ms: ..., ad_unit_code: ..., auction_id: ..., bidder: ..., bidder_request_id: ..., bid_requests_count: ..., bid_id: ..., transaction_id: ..., media_type: ..., uuid: ..., width: ..., height: ..., ref: ...}, options: Object{withCredentials: ...}, bidId: '2ed93003f7bb99', player: undefined, width: 1, height: 1, mediaType: 'banner'}]
26 05 2021 17:52:04.150:INFO [launcher.browserstack]: firefox 73.0 (Windows 10) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/5cc0cb81677b46757eda72ec2a50c6dfb80e1850
26 05 2021 17:52:07.717:INFO [IE 11.0.0 (Windows 10.0.0)]: Connected on socket Bxm-YjD2U90tD3tvAAAD with id 76588138
26 05 2021 17:52:17.001:INFO [launcher]: Starting browser firefox 72.0 (Windows 10) on BrowserStack
26 05 2021 17:52:18.179:INFO [launcher.browserstack]: firefox 72.0 (Windows 10) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/7f99c11e6a5f398d41cc242d3265e1c70695cdcb
26 05 2021 17:52:23.941:WARN [web-server]: 404: /someURL
26 05 2021 17:52:23.996:WARN [web-server]: 404: /someURL1

  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses
26 05 2021 17:52:29.010:WARN [web-server]: 404: /undefined
26 05 2021 17:52:32.194:INFO [Edge 17.17134.0 (Windows 10.0.0)]: Connected on socket yigmFiMZrdBayAwJAAAE with id 86441969
26 05 2021 17:52:32.225:INFO [launcher]: Starting browser safari 13.0 (OS X Catalina) on BrowserStack
26 05 2021 17:52:32.813:INFO [launcher.browserstack]: safari 13.0 (OS X Catalina) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/7fde615599c9e07257e90a4d9b56c80ce2754720
26 05 2021 17:52:32.896:INFO [launcher]: Starting browser safari 12.0 (OS X Mojave) on BrowserStack
26 05 2021 17:52:33.995:INFO [launcher.browserstack]: safari 12.0 (OS X Mojave) session at https://automate.browserstack.com/builds/fc7c4092be999c5584ff6d8134940cf6a2610909/sessions/afefdddb576a9474230427ce46c7807b59b9006a
26 05 2021 17:52:45.210:INFO [Firefox 73.0.0 (Windows 10.0.0)]: Connected on socket 5IZN3Lw1y8TTnscPAAAF with id 60373339
26 05 2021 17:52:45.797:WARN [web-server]: 404: /someURL
26 05 2021 17:52:45.915:WARN [web-server]: 404: /someURL1

  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses
26 05 2021 17:52:50.722:WARN [web-server]: 404: /undefined

  ID5 ID System
    Request Bids Hook
      ✗ "after each" hook
	Error: AssertionError: expected { Object (opeaud, opectx) } to be an undefined (node_modules/chai/chai.js:239)

      ✗ "before each" hook
	TypeError: Unable to get property 'call' of undefined or null reference


  currency
    setConfig
      ✗ "after each" hook for "results when no config available"
	TypeError: Unable to get property 'restore' of undefined or null reference
	   at Anonymous function (webpack:///test/spec/modules/idImportLibrary_spec.js:33:7 <- test/test_index.js:248946:7)


  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses
26 05 2021 17:53:10.502:INFO [Safari 13.1.2 (Mac OS X 10.15.6)]: Connected on socket O6W_P4KFvThEILipAAAG with id 79432356
  ✗ "before each" hook
	uncaught exception: AssertionError: expected { Object (opeaud, opectx) } to be an undefined (:0)


  currency
    ✗ "before each" hook for "results when no config available"
	Attempted to wrap logInfo which is already wrapped
	checkWrappedMethod@node_modules/sinon/pkg/sinon.js:3585:21
	wrapMethod@node_modules/sinon/pkg/sinon.js:3631:31
	stub@node_modules/sinon/pkg/sinon.js:2888:44
	@webpack:///test/spec/modules/idImportLibrary_spec.js:15:11 <- test/test_index.js:248931:11
	
	--------------
	wrapMethod@node_modules/sinon/pkg/sinon.js:3656:31
	spy@node_modules/sinon/pkg/sinon.js:2354:16
	@webpack:///test/spec/modules/id5IdSystem_spec.js:465:28 <- test/test_index.js:248740:28
	


  LoopMeAdapter
    interpretResponse
      - should return valid response when passed valid server response
26 05 2021 17:53:18.248:INFO [Firefox 72.0.0 (Windows 10.0.0)]: Connected on socket pP8EPF_hZR4l_GTSAAAH with id 36690589

  Publisher Common ID
    Configuration
      - disable auto create

  PubMatic adapter
    implementation
      Request formation
        - test flag set to 1 when pubmaticTest=true is present in page url

  RealVu
    Analytics Adapter.
      - isInView returns "yes"
Firefox 73.0.0 (Windows 10.0.0) LOG LOG: [Object{method: 'GET', url: 'https://api.relaido.jp/bid/v1/prebid/100000', data: Object{version: ..., timeout_ms: ..., ad_unit_code: ..., auction_id: ..., bidder: ..., bidder_request_id: ..., bid_requests_count: ..., bid_id: ..., transaction_id: ..., media_type: ..., uuid: ..., width: ..., height: ..., ref: ...}, options: Object{withCredentials: ...}, bidId: '2ed93003f7bb99', player: undefined, width: 1, height: 1, mediaType: 'banner'}]

  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses

  LoopMeAdapter
    interpretResponse
      - should return valid response when passed valid server response
26 05 2021 17:53:33.692:INFO [Safari 12.1.2 (Mac OS X 10.14.6)]: Connected on socket rvl-khpr7CZQfgxXAAAI with id 5191428

  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses

  Adagio bid adapter
    Adagio features
      getSlotPosition feature
        - should compute the slot position inside the parent window (window.top) when safeFrame is not available and postBid params is `true`

  AxonixBidAdapter
    buildRequests: can handle native ad requests
      - creates ServerRequests pointing to the correct region and endpoint if it changes
      - creates ServerRequests pointing to default endpoint if missing
      - creates ServerRequests pointing to default region if missing
    interpretResponse
      - parses 1 native responses

Chrome 79.0.3945 (Windows 10.0.0): Executed 8211 of 8228 (1 FAILED) (skipped 9) (39.66 secs / 17.035 secs)
Edge 18.18363.0 (Windows 10.0.0): Executed 3165 of 8228 (skipped 5) SUCCESS (8.637 secs / 4.828 secs)
Chrome 89.0.4389 (Windows 10.0.0): Executed 3373 of 8228 (3 FAILED) (skipped 5) (9.18 secs / 2.686 secs)
IE 11.0.0 (Windows 10.0.0): Executed 3194 of 8228 (skipped 5) SUCCESS (8.343 secs / 4.565 secs)
Edge 17.17134.0 (Windows 10.0.0): Executed 3157 of 8228 (3 FAILED) (skipped 5) (8.715 secs / 4.441 secs)
Firefox 73.0.0 (Windows 10.0.0): Executed 8184 of 8228 (2 FAILED) (skipped 9) (30.94 secs / 17.051 secs)
Safari 13.1.2 (Mac OS X 10.15.6): Executed 4628 of 8228 (skipped 6) SUCCESS (4.292 secs / 2.622 secs)
Firefox 72.0.0 (Windows 10.0.0): Executed 2922 of 8228 (skipped 5) SUCCESS (8.654 secs / 3.848 secs)
Safari 12.1.2 (Mac OS X 10.14.6): Executed 3520 of 8228 (skipped 5) SUCCESS (7.564 secs / 3.967 secs)
TOTAL: 9 FAILED, 40345 SUCCESS


1) "before each" hook
     
     Error: Uncaught AssertionError: expected { Object (opeaud, opectx) } to be an undefined (node_modules/chai/chai.js:239)

2) "before each" hook
     
     Error: Uncaught AssertionError: expected { Object (opeaud, opectx) } to be an undefined (node_modules/chai/chai.js:239)

3) "before each" hook for "should send oi = 2 when gdpr doesn't apply or has global consent"
     invibesBidAdapter:
     TypeError: Cannot read property 'call' of undefined

4) "after each" hook for "auction init event"
     Invisibly Analytics Adapter test suite Invisibly Analytic tests specs
     TypeError: events.getEvents.restore is not a function
    at Context.<anonymous> (webpack:///test/spec/modules/invisiblyAnalyticsAdapter_spec.js:182:24 <- test/test_index.js:257452:24)

5) "after each" hook
     ID5 ID System Request Bids Hook
     Error: AssertionError: expected { Object (opeaud, opectx) } to be an undefined (node_modules/chai/chai.js:239)

6) "before each" hook
     ID5 ID System Request Bids Hook
     TypeError: Unable to get property 'call' of undefined or null reference

7) "after each" hook for "results when no config available"
     currency setConfig
     TypeError: Unable to get property 'restore' of undefined or null reference
   at Anonymous function (webpack:///test/spec/modules/idImportLibrary_spec.js:33:7 <- test/test_index.js:248946:7)

8) "before each" hook
     
     uncaught exception: AssertionError: expected { Object (opeaud, opectx) } to be an undefined (:0)

9) "before each" hook for "results when no config available"
     currency
     Attempted to wrap logInfo which is already wrapped
checkWrappedMethod@node_modules/sinon/pkg/sinon.js:3585:21
wrapMethod@node_modules/sinon/pkg/sinon.js:3631:31
stub@node_modules/sinon/pkg/sinon.js:2888:44
@webpack:///test/spec/modules/idImportLibrary_spec.js:15:11 <- test/test_index.js:248931:11

--------------
wrapMethod@node_modules/sinon/pkg/sinon.js:3656:31
spy@node_modules/sinon/pkg/sinon.js:2354:16
@webpack:///test/spec/modules/id5IdSystem_spec.js:465:28 <- test/test_index.js:248740:28



[17:54:07] 'test' errored after 3.73 min
[17:54:07] Error: Karma tests failed with exit code 1
    at /home/circleci/Prebid.js/gulpfile.js:308:12
    at removeAllListeners (/home/circleci/Prebid.js/node_modules/karma/lib/server.js:370:9)
    at /home/circleci/Prebid.js/node_modules/karma/lib/server.js:381:13
    at Server.close (net.js:1600:9)
    at Object.onceWrapper (events.js:417:28)
    at Server.emit (events.js:323:22)
    at Server.EventEmitter.emit (domain.js:505:15)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
[17:54:07] 'test' errored after 4.22 min

Exited with code exit status 1
```

**Comment by mediaconsortium-develop** [comment]
I open new PR.
https://github.com/prebid/Prebid.js/pull/6847

I have got the latest master branch from your repository.
and I make new feature/dgkeywordRtdProvider_v2
<https://github.com/mediaconsortium-develop/Prebid.js/tree/feature/dgkeywordRtdProvider_v2>
branch
from the master.

But circle CI error can not disappear.
our test codes make no errors.  and probably our test code is ok.

2021年5月27日(木) 14:25 'Olivier' via ***@***.*** <
***@***.***>:

**Pull request merged**
