### PR TITLE
pubGENIUS bid adapter: support floor module

### PR DESCRIPTION
**Pull request by edmonl**
## Type of change
- [x] Feature

## Description of change
Make pubGENIUS bid adapter support getFloor.
Flagged by https://github.com/prebid/Prebid.js/issues/6465

- contact email of the adapter’s maintainer: meng@pubgenius.io
- [x] official adapter submission

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
  https://github.com/prebid/prebid.github.io/pull/2842

### CODE REVIEW

**Comment by patmmccann** [comment]
You're welcome to support both bidder parameters and the floors module.  Are you sure you wish to deprecate parameters support?

**Review by ncolletti — APPROVED** [review]
LGTM

**Comment by edmonl** [comment]
> You're welcome to support both bidder parameters and the floors module. Are you sure you wish to deprecate parameters support?

Sorry I missed this comment. Yes. We're pretty sure no one is currently using the bidder parameter.

**Comment by patmmccann** [comment]
Tag me in your PR to fix, I'll review it before the next release

**Pull request merged**
