### PR TITLE
Added '320x80': 59, '320x320': 72, '320x160': 73 to RUBICON_SIZE_MAP

### PR DESCRIPTION
**Pull request by tegner**
## Type of change
- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other

## Description of change
This commit adds the following sizes to rubicon size map

* '320x80': 59
* '320x320': 72
* '320x160': 73

### CODE REVIEW

**Comment by bretg** [comment]
Just need to resolve conflicts -- another size update was made the other day.

**Comment by bretg** [comment]
Please note that adding sizes in the adapter may not be enough to initiate auctions for those sizes. Please work with your Rubicon Project account rep to enable them on the backend.

**Comment by tegner** [comment]
@bretg Hi, I can't see the merge conflict, can you tell me where the problem lies? I have now moved the added lines to the bottom, although that isn't too pretty, I would want to keep the numeric order.

Regarding the backend, I have obtained the sizes from rubicon support, and the sizes is working for me.

**Comment by mkendall07** [comment]
@tegner 
Please pull in from upstream master into your fork. This will force resolution of the conflict. Then you can recommit your resolved file.

**Pull request merged**
