### PR TITLE
AOL bidder support

### PR DESCRIPTION
**Pull request by ikhemissi**
Hi guys,

I wanted to discuss the addition of support for AOL.

I think we can achieve that by either calling their REST API directly (more or less the way I did it here) or by using their Javascript library DAC.js (the way @nickjacob did it in this commit prebid/Prebid.js/commit/da753b8569696e2c0bff353b370be1753bde8883).

Each solution has its advantages and its drawbacks :  
- REST API call : the cost of performing the request bid is minimized but we have to understand how the API works (and we will perhaps lose some user data in the process).
- DAC.js : we have to load more resources (dependencies) in order to request the bid but less knowledge of the library/API is required in order to perform the bid request.

What do you think ?

### CODE REVIEW

**Comment by mkendall07** [comment]
Hi @ikhemissi ,
Thanks for the contribution. Can you explain more about possible loss of user data in process when using the REST API?

**Comment by ikhemissi** [comment]
Hi @mkendall07 ,
I was thinking about extra data that may (or not) be passed by DAC.js to the API like latitude and longitude.
With this implementation, we still can pass such data using the optional parameter "params.options" (a javascript object) but we have to do it ourselves. I mean searching for extra data and passing it to the bid configuration.
Whereas with DAC.js and its dependencies, this have been taken into account and it should be filled automatically.
This being said, I didn't confirm this myself so I can't be sure if this information is well handled or not by DAC.js.
On the other side, I think that not having all these extra dependencies may lead - depending on the type of site - to faster bids and faster page display.

**Comment by nickjacob** [comment]
I was thinking of going this route but got turned off by having to gather referrer (as AOL defines it) + other user data that they want (I think they do get a geo, I can get relevant code from DAC). DAC + the pubAPI script (loaded by DAC) will add user data by default if you don't specify any

I like this approach for speed/lightweight but I'm worried that it could hurt CPM by limiting AOL's access to impression context? my other concern would just be that aol would be turned off/have more friction if they don't see DAC.js (during integration)

**Comment by nickjacob** [comment]
ok actually just answered my own question + realized we might want to either enable all of this for the adapter or add to bid params:

you can enable/disable option to detect screen, flash version, timezone & geo (using html5 geo api if available) through DAC, right now it's all disabled in the other AOL adapter, going to check with our rep to see if it's something we should be doing -- here's screenshot of some of the DAC code --

screen shot 2015-10-14 at 3 45 34 pm

it might be there just for adtech server in which case I don't think DAC brings as much benefit

**Comment by mkendall07** [comment]
Thanks @ikhemissi  and @nickjacob for the info. As a publisher AOL advices to use DAC, then I think that would be the preferred way to go. It may not be a good idea to tightly couple to the API directly, in case changes are made. I'll wait for confirmation from @nickjacob on AOL's preference here.

**Comment by mkendall07** [comment]
Hey @nickjacob any more thoughts on this?

**Comment by nickjacob** [comment]
just talked to our rep; she doesn't have a preference as long as the cookies are sent correctly cross-domain, although she did mention that there might be value in the long-term to sending more user data through the data param (esp. on mobile), for that I think DAC has an advantage bc it includes a lot of cross-browser UA detection/scraping code

I'm leaning towards DAC just because it should (theoretically) make it less fragile/make it easier for an AOL rep to support, but I'm obviously biased here :), ^ this way is significantly lighter on the page/faster

**Comment by nickjacob** [comment]
Had a meeting w/ Wenda Zhou @aol yesterday; he's the product lead on marketplace client-side—hopefully he/his team will be contributing soon. They're recommending using DAC for now, since they'll be rolling out changes in the future to better support prebid.

**Comment by ikhemissi** [comment]
Hi guys,

I have ended up using the DAC.js solution too.
Can you please check the pull-request https://github.com/prebid/Prebid.js/pull/85 to prepare for a merge with the master branch ?

**Comment by mkendall07** [comment]
AOL already added with this PR: https://github.com/prebid/Prebid.js/pull/55

**Pull request closed without merging**
