### PR TITLE
Rubicon adapter: add a floor variable

### PR DESCRIPTION
**Pull request by benjaminclot**
## Type of change
- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change
Added a new "floor" variable to the Rubicon adapter, in order to be able to use rp_floor dynamically and not have a static 0.01 value.

- test parameters for validating bids
```
{
  bidder: 'rubicon',
  params: {
    // ...
    floor: 0.5,
    // ...
  }
}
```

### CODE REVIEW

**Comment by snapwich** [comment]
Needs to be updated in the unit test, but otherwise LGTM.  Verifying with @bretg about documentation and endpoint. 

Also this will need to be duplicated in #950 I imagine, so we might want to wait until that is merged.

**Comment by bretg** [comment]
This is fine. I'll update the Prebid.org docs in the coming weeks.

**Comment by benjaminclot** [comment]
Is this going to be merged soon? I kinda need it and I'd rather not use a "custom" adapter.
Also I can't make a unit test that responds differently based on the floor (and always the same for the tests), only the Rubicon guys can do that.

**Comment by mkendall07** [comment]
@benjaminclot 
Can you resolve conflicts? I think we can merge after that.

**Comment by snapwich** [comment]
@benjaminclot the unit test responses are mocked so anyone should be able to add the appropriate tests.  I'm willing to add those though, if you'd like.  I think that's possible if the "allow maintainers to edit" checkbox is clicked?

**Comment by benjaminclot** [comment]
@mkendall07 conflicts are resolved.
@snapwich the checkbox is checked.

**Comment by snapwich** [comment]
For whatever reason it won't let me push my change due to lack of permissions.  I thought being a Prebid.js member would be enough, or maybe i'm doing it wrong... But either way, here's the patch if you would like to apply it:

```diff
From ea495bb8f305269d7a3266adba81fb62c125bfc6 Mon Sep 17 00:00:00 2001
From: Rich Snapp <rsnapp@rubiconproject.com>
Date: Tue, 7 Feb 2017 10:46:00 -0700
Subject: [PATCH] added unit test to rubicon_spec for rp_floor override

---
 test/spec/adapters/rubicon_spec.js | 13 +++++++++++++
 1 file changed, 13 insertions(+)

diff --git a/test/spec/adapters/rubicon_spec.js b/test/spec/adapters/rubicon_spec.js
index a875def..853e99e 100644
--- a/test/spec/adapters/rubicon_spec.js
+++ b/test/spec/adapters/rubicon_spec.js
@@ -263,6 +263,19 @@ describe('the rubicon adapter', () => {

         });

+        it('should allow a floor override', () => {
+          bidderRequest.bids[0].params.floor = 2;
+
+          rubiconAdapter.callBids(bidderRequest);
+
+          let request = xhr.requests[0];
+
+          let [path, query] = request.url.split('?');
+          query = parseQuery(query);
+
+          expect(query['rp_floor']).to.equal('2');
+        });
+
         it('should not send a request and register an error bid if no valid sizes', () => {

           var sizesBidderRequest = clone(bidderRequest);
--
2.10.1 (Apple Git-78)
```

**Comment by benjaminclot** [comment]
@snapwich The test has been added (and lightly edited)

**Comment by mkendall07** [comment]
LGTM. Thanks!

**Pull request merged**
