### PR TITLE
Updating the audience network adapter to be 3.x compliant

### PR DESCRIPTION
**Pull request by robertrmartinez**
Adding back the audience network adapter and updating it to be compliant on 3.x.

You can see a diff from the 2.x and 3.x versions at the revision history of this GIST:

https://gist.github.com/robertrmartinez/cc4cc72fd1445f0096775aac36305583/revisions

### CODE REVIEW

**Comment by bretg** [comment]
@lovell - we'd like you to have a chance to review and approve this PR. Thanks.

**Comment by robertrmartinez** [comment]
I tested the `2.x` and `3.x` versions on an actual page and was able to see the request to Facebook go out and the same query params were passed (And the resolved `pageurl` sent is the same:

2.x Request:

https://an.facebook.com/v2/placementbid.json?placementids[]=1033648490040978_1709080755831078&adformats[]=300x250&testmode=false&pageurl=http%3A%2F%2Fwww.rubitest.com%3A8000%2Ftest_pages%2Fsanity%2FTEMP%prebid-test.html%3Fpbjs_debug%3Dtrue&sdk[]=6.0.web&adapterver=1.3.0&platform=241394079772386&platver=2.44.4-pre&cb=a4b4f9fe-adb6-45e5-96ae-cf24d3d597b2


3.x Request:

https://an.facebook.com/v2/placementbid.json?placementids[]=1033648490040978_1709080755831078&adformats[]=300x250&testmode=false&pageurl=http%3A%2F%2Fwww.rubitest.com%3A8000%2Ftest_pages%2Fsanity%2FTEMP%prebid-test.html%3Fpbjs_debug%3Dtrue&sdk[]=6.0.web&adapterver=1.3.0&platform=241394079772386&platver=3.4.0-pre&cb=03410156-2cb2-4598-a322-0c5c676c1a59

**Comment by bretg** [comment]
Going ahead to merge this as many are waiting on it. The testing done looks reasonable to me. @lovell , we'd still invite you to review the change.

**Comment by lovell** [comment]
Thanks for restoring this adapter. There's a new version coming along soon but this will provide a stopgap for those wanting to use it with Prebid.js v3.

**Pull request merged**
