### PR TITLE
Add support for Gamoshi's Gambid Bid Adapter

### PR DESCRIPTION
**Pull request by arikkfir**
## Type of change
- [x] New bidder adapter

## Description of change
Add support for Gamoshi's Gambid Platform to Prebid.js in the form of a new bidder adapter.
Here's how to simulate an example bid for testing:

```
{
  bidder: 'gambid',
  params: {
    supplyPartnerId: "1157"
  }
}
```

Contact email of the adapter’s maintainer: arik@gamoshi.com

### CODE REVIEW

**Comment by mkendall07** [comment]
This pull request **introduces 1 alert** when merging 9a71939430cc152a95338dfe4b5c46d3b5bfbe93 into f7cf6cb21c9558b042234755c44e1a9f6fe82f64 - [view on lgtm.com](https://lgtm.com/projects/g/prebid/Prebid.js/rev/pr-3665abf87127ff409dbd1712ac41eb6ff9243e24)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by mkendall07** [comment]
This pull request **introduces 1 alert** when merging f7bf27dd84b09b2c67fa3153001377517016c47a into f7cf6cb21c9558b042234755c44e1a9f6fe82f64 - [view on lgtm.com](https://lgtm.com/projects/g/prebid/Prebid.js/rev/pr-42b9f4a582ca5d119a2c87e0ec3edc77f30073e9)

**new alerts:**

* 1 for Useless conditional

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by arikkfir** [comment]
Thanks @snapwich - done.

**Comment by arikkfir** [comment]
@snapwich quick question - so on the next Prebid.js release users will be able to check the "Gamoshi Gambid" check-box?
Is there anything else we should do? do we need to create a PR for the docs repo as well?

**Pull request merged**
