### PR TITLE
Feature powerful adjust

### PR DESCRIPTION
**Pull request by CarsonBanov**
@mkendall07 

If we pass the whole bid object, Prebid publishers have some extremely cool new abilities.  Using the very same `bidCpmAdjustment` function (which btw will still be backwards compatible) users can do things like enhance their analytics with the additional data, track creatives across partners, decrease bids from slow bidders, etc.!  

.cc @nanek

### CODE REVIEW

**Comment by mkendall07** [comment]
@CarsonBanov 
Thanks. This makes the bid object mutable which is the reason I didn't implement this. I'm not sure this is a good idea, as it has potential for abuse.

**Comment by CarsonBanov** [comment]
That's definitely true.  Perhaps we could provide a copy of the bid object somehow?  We would really like to have access to the bid creatives.

**Comment by mkendall07** [comment]
@mjacobsonny & @Heray thoughts?

**Comment by mkendall07** [comment]
@CarsonBanov 
I'm thinking that a copy of the bid would be acceptable. If you want to implement that in this PR, I will review it. Thanks

**Comment by CarsonBanov** [comment]
@mkendall07 Updated.

**Comment by mkendall07** [comment]
@CarsonBanov 
Thanks, this LGTM. Can you please add a unit test to `bidmanager_spec.js` and I will merge.

**Pull request merged**
