### PR TITLE
Timmedia/timadapter 2.0

### PR DESCRIPTION
**Pull request by borisjaskerovich**
**Type of change**
  

- [ ] New bidder adapter

**Description of change**

- test parameters for validating bids

```
{
"bidder":"tim",
                "params":{
                "placementCode":"testPlacementCode",
                "publisherid":"testpublisherid"
                }
}
```
Be sure to test the integration with your adserver using the [Hello World](url) sample page.

- contact email of the adapter’s maintainer

   shlomi@thetimmedia.com

- [x]   official adapter submission

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/prebid/prebid.github.io#1117

### CODE REVIEW

**Comment by mike-chowla** [comment]
I'm getting the test response now.  I'm seeing a Cross-Origin error when rendering the ad because mime-type on the response to your pixel is application/json

screen shot 2019-01-30 at 2 31 13 pm

**Comment by borisjaskerovich** [comment]
Hi Mike,
We fixed the Cross-Origin error now.

**Comment by shlomisut** [comment]
hey @mike-chowla 

We changes the tracker to match the bidding domain, and missed the regional SSL config (`eu` worked fine ) 
now fixed and https://east.timmedia-hb.com/ works fine (as well as https://eu.timmedia-hb.com/ and https://sin.timmedia-hb.com/)

thanks

**Comment by borisjaskerovich** [comment]
Thanks @mike-chowla ,
We have two questions:
1. How do we get to be on this page: http://prebid.org/download.html ?
2. we want to be in version 1.4 also. do we need to open another pr from that branch?

**Pull request merged**
