### PR TITLE
Next Millennium Bid Adapter: update to comply with Prebid v5

### PR DESCRIPTION
**Pull request by mifanich**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
This adapter existed before.
We have made changes for approval to include it in v. 5.

- test parameters for validating bids
```
{
    bidder: 'nextMillennium',
    params: {
        placement_id: '528'
    }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

### CODE REVIEW

**Comment by patmmccann** [comment]
Please unfollow your own branch in circleci so that our tests run, also remove changes to hello world.

**Comment by mifanich** [comment]
I removed changes from hello_world.
Could you explain, how to unfollow my branch?

**Comment by ChrisHuie** [comment]
@mifanich inside circleci is should be in the drop-down panel to the left to unfollow your branch. Or if you give me edit access to this pr or the branch I can just kick off the test manually?

**Comment by mifanich** [comment]
> @mifanich inside circleci is should be in the drop-down panel to the left to unfollow your branch. Or if you give me edit access to this pr or the branch I can just kick off the test manually?
I gave you access to the repo

**Comment by ChrisHuie** [comment]
@mifanich looks like you still need to add documentation for this pr. Docs should be added to this repo -> https://github.com/prebid/prebid.github.io

..and then also a markdown file in this pr that helps explain using your adapter. All details should be here that you may need (https://docs.prebid.org/dev-docs/bidder-adaptor.html) 🤘

**Comment by mifanich** [comment]
@ChrisHuie Thank you, there is a PR doc
https://github.com/prebid/prebid.github.io/pull/3169/

**Comment by ChrisHuie** [comment]
@mifanich thanks.

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
