### PR TITLE
Rivr thin adapter

### PR DESCRIPTION
**Pull request by AlessandroDG**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Delegates the events handling to an external component that Rivr will provide to publishers.

- contact email of the adapter’s maintainer: alessandro@simplaex.com

### CODE REVIEW

**Comment by AlessandroDG** [comment]
@jsnellbaker thank you for your feedback. I will run it locally too and apply the needed changes.

circleci/Browserstack configuration never really worked properly. In the previous PR I had a different issue. Your colleague tried to understand the cause but he couldn't because of the free plan you have with circleci.

Here you can find the conversation: https://github.com/prebid/Prebid.js/pull/3202

**Comment by AlessandroDG** [comment]
@jsnellbaker browserstack tests ran now.

Anyway, I would really appreciate if you could help me figure out why the circleci build runs on our (Simplaex) instance rather then the Prebid one.

**Comment by jsnellbaker** [comment]
@AlessandroDG Thanks for making the updates.  

In regards to the CircleCI job, I'm not 100% sure what to do here.  From what we've seen, if the organization that houses the fork exists in CircleCI - it seems to default to run in that organization rather than in the target project.  If you have any ideas here, please let us know.

**Comment by AlessandroDG** [comment]
@jsnellbaker Thanks for merging the PR.
And also for the input on CircleCI, I will investigate on our side and get back to you when I will find out something.

**Pull request merged**
