### PR TITLE
CleanMediaNet Bid Adapter: endpoint update

### PR DESCRIPTION
**Pull request by CleanMediaNet**
Updated Endpoint

## Type of change
- [x ] Build related changes

## Description of change
Endpoint update

### CODE REVIEW

**Comment by blingster7** [comment]
@CleanMediaNet could you please address the failing CircleCI test?

**Review by blingster7 — CHANGES_REQUESTED** [review]
Please address failing CircleCI tests

**Comment by CleanMediaNet** [comment]
> Please address failing CircleCI tests

We have someone working on it and will hopefully have it fixed soon

**Comment by blingster7** [comment]
Hey just checking in here. Seems like the CircleCI tests still aren't passing

**Comment by CleanMediaNet** [comment]
Yeah we are having an issue figuring out what the issue is, it works building it locally and it worked before, but for some reason when we change the server credentials then it gives the error.
-------- Original message --------From: Brandon Ling <notifications@github.com> Date: 3/3/21  1:56 PM  (GMT-05:00) To: "prebid/Prebid.js" <Prebid.js@noreply.github.com> Cc: CleanMediaNet <github@cleanmedia.net>, Mention <mention@noreply.github.com> Subject: Re: [prebid/Prebid.js] CleanMediaNet Bid Adapter: endpoint update (#6353) 
Hey just checking in here. Seems like the CircleCI tests still aren't passing

**Comment by blingster7** [comment]
Any updates here @CleanMediaNet?

**Comment by ChrisHuie** [comment]
Following up on this pr @CleanMediaNet

**Comment by ChrisHuie** [comment]
closing. Feel free to update with changes to this pr

**Pull request closed without merging**
