### PR TITLE
33Across Analytics Adapter: initial release

### PR DESCRIPTION
**Pull request by macinjosh32**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New Analytics adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

The debut of a new Prebid Analytics Adapter from 33Across.

## Other information

Documentation PR: https://github.com/prebid/prebid.github.io/pull/4944

### CODE REVIEW

**Comment by macinjosh32** [comment]
I've sync'ed from the latest upstream main branch. Let me know if anything else is needed.

**Comment by macinjosh32** [comment]
@jlquaccia - Can you please review this pull request when you have a chance?

**Review by jlquaccia — APPROVED** [review]
overall lgtm

**Comment by macinjosh32** [comment]
Thanks, @jlquaccia! Feel free to merge at your earliest convenience.

**Comment by jlquaccia** [comment]
Hey @macinjosh32, apologies for overlooking this the other day, but looks like there are a few tests that are failing (flagged from the circleci build above).  Could you address these?  Then this PR should be good to go!

**Review by jlquaccia — CHANGES_REQUESTED** [review]
Need to address some tests that are failing.

**Comment by macinjosh32** [comment]
@jlquaccia - I found the issue and fixed it, and all tests are passing when I run "npm run test" locally.

However, when I push the fix and Prebid.js's CI runs, the BrowserStack testing fails on older Safari browsers due to a connection issue. I think the connection is unrelated to this pull request because CI is also failing on prebid:master with a similar error. I wanted to try re-running the CI, but it looks like write access is required for that. Can you please give it a try?

**Review by jlquaccia — APPROVED** [review]
LGTM

**Comment by jlquaccia** [comment]
@macinjosh32 @mscottnelson sorry for the delay, wanted to confirm with another Prebid member that the failed test was something unrelated as suspected above and turns out it is unrelated.  Re-ran the tests just now and everything passed.  All good to go, will merge!

**Comment by mscottnelson** [comment]
Not a problem, and thank you!

**Pull request merged**
