### PR TITLE
Cleanmedianet: New bidder adapter

### PR DESCRIPTION
**Pull request by sa1omon**
## Type of change

- [X] New bidder adapter

## Description of change

Added ```cleanmedianet``` as a new bidder adapter

## Test Parameters

```
var adUnits = [
    // Banner adUnit
   {
     code: 'banner-div',
     sizes: [[300, 250]],
     bids: [{
       bidder: 'cleanmedianet',
       params: {
          // ID of the supply partner you created in the Clean Media Net dashboard
         supplyPartnerId: '1253',
          // OPTIONAL: custom bid floor
         bidfloor: 0.01,
          // OPTIONAL: if you know the ad position on the page, specify it here
         //           (this corresponds to "Ad Position" in OpenRTB 2.3, section 5.4)
         //adpos: 1,
          // OPTIONAL: whether this is an interstitial placement (0 or 1)
         //           (see "instl" property in "Imp" object in the OpenRTB 2.3, section 3.2.2)
         //instl: 0
       }
     }]
   },
    // Video outstream adUnit
   {
     code: 'video-outstream',
     sizes: [[300, 250]],
     mediaTypes: {
       video: {
         context: 'outstream',
         playerSize: [300, 250]
       }
     },
     bids: [ {
       bidder: 'cleanmedianet',
       params: {
          // ID of the supply partner you created in the dashboard
         supplyPartnerId: '1254',
          // OPTIONAL: custom bid floor
         bidfloor: 0.01,
          // OPTIONAL: if you know the ad position on the page, specify it here
         //           (this corresponds to "Ad Position" in OpenRTB 2.3, section 5.4)
         //adpos: 1,
          // OPTIONAL: whether this is an interstitial placement (0 or 1)
         //           (see "instl" property in "Imp" object in the OpenRTB 2.3, section 3.2.2)
         //instl: 0
       }
     }]
   }
];
```

## Other information

Please refer also to [#1134](https://github.com/prebid/prebid.github.io/pull/1134) for bidder adapter's docs.

Thanks

### CODE REVIEW

**Comment by sa1omon** [comment]
Hi @bretg ,
Due to [#3537](https://github.com/prebid/Prebid.js/pull/3537) fix,
please revert the latest commit: 
[c74a4](https://github.com/prebid/Prebid.js/pull/3519/commits/c74a4845b523b86f8229dd824ffa235e44407f19)

Thanks

**Comment by jsnellbaker** [comment]
As per comments made on https://github.com/prebid/Prebid.js/pull/3548 and the above, I'm closing this PR.

**Comment by mmoses** [comment]
Hi Guys, any update on this ?

**Comment by sa1omon** [comment]
Hi @jsnellbaker @bretg @mike-chowla 
Do you know what is the ETA for approving this PR?

Thanks.

**Comment by mike-chowla** [comment]
Sorry for my slowness.  I've been out of the country.  I'm back now

**Comment by sa1omon** [comment]
> You should not be checking in package-lock.json. Please update your PR to remove the changes to package-lock.json

Hi @mike-chowla ,

I have reverted my changes for the package-lock.json. 
Please review and update me should other changes need to be done.

Thanks

**Comment by mike-chowla** [comment]
It looks to me like package-lock.json is still part of the PR.

screen shot 2019-02-22 at 4 58 05 pm

**Comment by sa1omon** [comment]
> It looks to me like package-lock.json is still part of the PR.
> 
> screen shot 2019-02-22 at 4 58 05 pm

Hi @mike-chowla ,

Please close this PR.
I have opened a new PR [#3582](https://github.com/prebid/Prebid.js/pull/3582)
without the package-lock.js file. 

Thanks

**Comment by mike-chowla** [comment]
Replaced by PR #3582

**Pull request closed without merging**
