### PR TITLE
Currency Module: always adding originalCpm and originalCurrency to bid object

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [X] Code style update (formatting, local variables)

## Description of change
#3855 
Always add originalCpm and originalCurrency to bid object when the currency module is enabled.

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker ,
Could you please review?

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker ,
A gentle reminder :)
Could you please review the change?

**Comment by jaiminpanchal27** [comment]
@pm-harshad-mane I am not 100% sure here but undefined shouldn't be problem here. If it is undefined it clearly means that bidder responded in same currency and there is no need to store same data in duplicate property. 

I guess analytics adapters or listeners can add a check for these properties and can easily figure this out.

**Comment by pm-harshad-mane** [comment]
@jaiminpanchal27 analytics adapters and listeners can add this un-documented check but I think it is better if currency module always sets these two fields so that the listeners and analytics adapters will not need this special handling and it will also make the bid-object have consistent fields.

@idettman has approved the change does that mean we can merge the change in master?

**Comment by pm-harshad-mane** [comment]
Thank you @idettman , @jaiminpanchal27 , @jsnellbaker :)

**Pull request merged**
