### PR TITLE
Criteo : Add support of PAF response model

### PR DESCRIPTION
**Pull request by leonardlabat**
## Type of change
- [X] Feature

## Description of change
This PR intent to make our adapter compatible with PAF by forwarding PAF response data to the publisher through the bid's meta property.

### CODE REVIEW

**Comment by patmmccann** [comment]
[bwschmidt](https://github.com/bwschmidt) your review would be appreciated

**Comment by patmmccann** [comment]
@leonardlabat could you link discussion of a paf response ?

**Comment by leonardlabat** [comment]
@patmmccann  it has been discussed here https://prebid.slack.com/archives/C032BTB7BHU/p1651163997883919

**Comment by patmmccann** [comment]
Is there somewhere in the mvp repo or addressability framework repo describing it?

**Comment by broggeri** [comment]
At the moment it's only described in the Prebid.js branch that Brian created in OpenX's fork: https://github.com/openx/Prebid.js/blob/paf/modules/pafRtdProvider.md

It references this section of the doc in the addressability framework repo : https://github.com/prebid/addressability-framework/blob/main/mvp-spec/ad-auction.md#step-4-send-transmission-responses. This doc will give you most of the information.

It lacks a little bit of explanation still, because the doc stops at the OpenRTB response.  To understand how we get from a transmission response in a OpenRTB response, to transmission response in a prebid bid object, a few more lines are necessary:

- The transmission response described in ad-auction.md above contains all the information for all the slots and all the bids in the OpenRTB bid response.
- the bid object in Prebid.js is just for a single slot though.
- we want to leave it to the paf client lib to figure out the audit log though, so the approach is to copy the full transmission response in each bid response object meta attribute, and add the content id for the winning bid in this ad slot
- that's how we get to
` bid.meta.paf = {
   content_id : "xxx"
   transmission: { ... }
   }`

**Comment by broggeri** [comment]
@leonardlabat could you also send this pull request to Brian's paf branch in the OpenX's fork ?

**Comment by bwschmidt** [comment]
lgtm

**Review by patmmccann — APPROVED** [review]
Thanks for the guest review Brian!

**Pull request merged**
