### PR TITLE
AOL Bid Adapter: add support for the floors module

### PR DESCRIPTION
**Pull request by patmmccann**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [X] Other

## Other information

Partial solution to #6465

### CODE REVIEW

**Comment by adam-browning** [comment]
Hey @patmmccann,
This adapter is maintained by the display part of our company
@slimkrazy should be the right person to assist.
I will also contact him internally.
Cheers!
Adam

**Comment by patmmccann** [comment]
if the floors don't work on this module, why not just delete on Line 274

    if (params.bidFloor) {
      queryParams.bidfloor = params.bidFloor;
    }


and you'll be fine for 5.0

@adam-browning @slimkrazy

**Comment by adam-browning** [comment]
Hi @patmmccann,
Sorry for the delayed response.

The aolBidAdapter has 2 bidders within it: onedisplay & onemobile.
Although onedisplay supported passing a the bidFloor parameter, it is just a server side pass back over to the onemobile platform.
Since onemobile does not support bidFloor via tag integrations, this delclaration is now redundant and will have no affect server side.

There is a new Adapter that was supposed to replace both aol & oneMobile adapters called the verizonMediaBidAdapter.js
But due to obvious reasons (Verizon Media rebranding to Yahoo under Apollo) there will be some delays.
bidfloor can be ignored at this point.
Thanks in advance!
Adam

**Comment by patmmccann** [comment]
thank you @adam-browning for noting the floors are no longer honored, I put in a pr to reflect

**Comment by slimkrazy** [comment]
@patmmccann - just to add the extra confirmation: This change is good.

**Pull request closed without merging**
