### PR TITLE
PR_REVIEW: added check for bidder name validity

### PR DESCRIPTION
**Pull request by bretg**
## Type of change
Documentation

## Description of change
Updating the reviewer reference to check the validity of the proposed bidder code:

- The bidder code must be lower case alphanumeric. The only special character allowed is underscore.
- The bidder code must be unique - make sure none of the other bid adapters is using the same code.
- The bidder code should be unique for the first 6 characters - this consideration helps with generating unique targeting keys for use by some ad exchanges, such as Google Ad Manager.
- There are several reserved words that cannot be used as bidder names: all, context, data, general, prebid, and skadn.

### CODE REVIEW

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
I think this should potentially extend to aliases. Of note, https://github.com/prebid/Prebid.js/pull/6253/files 'districtmdmx' added a shortcode alias so that keys wouldn't collide with their other adapter 'districtm'

**Review by patmmccann — CHANGES_REQUESTED** [review]
Should we change to "bidder code and all aliases" ?

**Comment by bretg** [comment]
> Should we change to "bidder code and all aliases" ?

changed

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
@gglas can we merge this before this week's release?

**Review by gglas — COMMENTED** [review]
LGTM

**Review by gglas — COMMENTED** [review]
approved

**Pull request merged**
