### PR TITLE
Consent module doublecall

### PR DESCRIPTION
**Pull request by olafbuitelaar**
new PR for; https://github.com/prebid/Prebid.js/pull/3371

### CODE REVIEW

**Comment by jsnellbaker** [comment]
@olafbuitelaar Can you fix the linting errors that were caught in the circleci check?

**Comment by olafbuitelaar** [comment]
@jsnellbaker  done..all green now..shouldn't these formattings not being dealt with automatically?

**Comment by jsnellbaker** [comment]
@olafbuitelaar Thanks for making the updates.  If your text editor has a plugin for eslint, it would be captured/handled while your writing the code the changes.  Depending on the setup of that plugin, when you save the file - it would automatically fix the linting errors during that save action.

Otherwise you'd need to run a `gulp` command to run the linting check.  You could use `gulp lint` directly, or you could run `gulp test` or `gulp serve` (if you were testing your changes locally) as both of those commands include the `gulp lint` as part of the sequence.

**Comment by olafbuitelaar** [comment]
@jsnellbaker i'm using VS Code with the eslint plugin..maybe something is broken, i'll check it out..maybe have a: gulp format command? just as the beauty of go?

**Comment by olafbuitelaar** [comment]
@idettman thanks. @jsnellbaker  just made a PR which appears to work for me.
As final note on this issue, i could imagine other modules might suffer from being double registered as listener, which probably isn't good in all cases.

**Pull request merged**
