### PR TITLE
6012: Fix for passing US Privacy string in buildVideoUrl and buildAdpodVideoUrl

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [ X ] Feature

## Description of change
Fix for https://github.com/prebid/Prebid.js/issues/6012
Fix for passing US Privacy string in buildVideoUrl and buildAdpodVideoUrl

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker ,
Can you please review the approach ? if it is fine then I will add the test cases too.

**Comment by jsnellbaker** [comment]
@pm-harshad-mane I think this looks good.

**Comment by pm-harshad-mane** [comment]
@jsnellbaker test case are added , can you please review? :-)

**Review by jsnellbaker — APPROVED** [review]
LGTM

**Comment by pm-harshad-mane** [comment]
Hello @msm0504 
Could you please review?

**Comment by pm-harshad-mane** [comment]
Hello @msm0504 ,
Gentle reminder to check review PR

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker ,
Looks like @msm0504 is busy, the changes are small, can we merge w/o second review?

**Review by msm0504 — APPROVED** [review]

**Review by Fawke — APPROVED** [review]

**Pull request merged**
