### PR TITLE
Pbjs Core: add new API to return the highest unused bid for a given adunit

### PR DESCRIPTION
**Pull request by woggle23**
## Type of change
- [ ] Feature

## Description of change
This introduces a new API to return the highest unused bid for a given adUnit code, regardless of whether an auction is still ongoing.

This is the approach I've taken in my fork of Prebid.js to address [this issue](https://github.com/prebid/Prebid.js/issues/3823). I appreciate this may not be an ideal approach, so any suggestions would be gratefully received.

### CODE REVIEW

**Review by blingster7 — APPROVED** [review]
LGTM, is there any way you can add a test somewhere?

**Comment by woggle23** [comment]
Sure, unit tests added.

**Review by ChrisHuie — APPROVED** [review]

**Comment by bretg** [comment]
I'm a little bummed this got merged without documentation.

I went to try to fix that gap myself and have a question and comment:

Q) I don't understand the difference between this function pbjs.getHighestCpmBids(adUnitCode)?
C) I don't particularly like the overly long name of this function. Bloat. It's too late now, but Chris, in the future, please help police shorter names.

**Comment by woggle23** [comment]
@bretg 
>Q1) I don't understand the difference between this function and pbjs.getHighestCpmBids(adUnitCode)?
`pbjs.getHighestCpmBids` only considers bids for auctions that have completed (and are also `unused`), the new API considers bids for ongoing auctions as well.

>Q2) What does "unused" mean? Does it mean that targeting was never set, it was never rendered, or something else?
see [here](https://github.com/prebid/Prebid.js/blob/e2062447abd900e1b7ad028eaa3bae6913c57ca9/src/prebid.js#L221).

>C) I don't particularly like the overly long name of this function. 40 characters. Wow. We're constantly under fire for code size and this won't minify. It's too late now, but Chris, in the future, please help police shorter names.
Noted.

**Comment by bretg** [comment]
Parsed the code myself to figure out what "unused" meant. If I got it wrong, please correct.

https://docs.prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.getHighestUnused

**Pull request merged**
