### PR TITLE
Utm feature for prebid analytics

### PR DESCRIPTION
**Pull request by sergey-roxot**
## Type of change

- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change
Added utm_tags reading and sending to prebid analytics in roxot analytics module.

### CODE REVIEW

**Comment by alex-khar** [comment]
Hey @ndhimehta! Do you have any estimates when you are able to review our pr? This will help us to plan our work. Thanks in advance.

**Comment by alex-khar** [comment]
@ndhimehta Could you please review this pr when you have a chance? Thanks!

**Comment by bretg** [comment]
Re-assigning to @snapwich

**Comment by alex-khar** [comment]
@bretg Thanks!

**Comment by alex-khar** [comment]
@snapwich Looking forward to your review. I'm concerned that the feature won't be in the next release.

**Pull request closed without merging**
