### PR TITLE
Alkimi Bid Adapter: add custom user object

### PR DESCRIPTION
**Pull request by kalidas-alkimi**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Review by spotxslagle — COMMENTED** [review]
Looks good to me, but it's not currently passing CI tests.

**Comment by spotxslagle** [comment]
My understanding is that a pr needs to pass automation to be approved, regardless of why it's failing. I tried rerunning the build and it failed again. I would suggest trying to merge master back into your branch, as other builds have been succeeding today.

**Comment by ChrisHuie** [comment]
I will also rerun in case its flaky. Might fix as well

**Comment by kalidas-alkimi** [comment]
@ChrisHuie @spotxslagle 

CI tests are passing now. Could you please check again? Thanks.

**Review by spotxslagle — APPROVED** [review]
LGTM

**Comment by kalidas-alkimi** [comment]
Hi  
Could you please merge this PR, if all is ok? Thanks.

**Pull request merged**
