### PR TITLE
Added support for NURL and ADM responses

### PR DESCRIPTION
**Pull request by optimatic58**
## Type of change
- [x] Feature

## Description of change

+ Added support for both NURL and ADM
+ Updated unit tests for changes
+ Added version number for internal records

- contact email of the adapter’s maintainer
prebid@optimatic.com

- [x] official adapter submission

### CODE REVIEW

**Comment by snapwich** [comment]
@optimatic58 this needs to be rebased off the latest master.  There were some changes that happened that would stop the tests from failing in travis.  Thanks!

**Comment by optimatic58** [comment]
We built this on the master and submitted this 21 days ago.  Do we need to rebase it to the latest master and resubmit it with a different ticket?

**Comment by snapwich** [comment]
@optimatic58 you need to rebase off master so that you have the latest, but you don't need to make a separate ticket.  If you rebase the source branch for this pull-request (`optimatic58:optimatic-adapter`) onto master and then push to your repo, the pull-request will automatically update.

**Comment by optimatic58** [comment]
@snapwich thanks, we have rebased on the latest master and pushed it.  let us know if there is anything else.

**Comment by snapwich** [comment]
Hmmm, I'm not quite sure how you rebased, but it rewrote the commits somehow and that is not good since now git thinks they're all new commits.  If it is easier, you may want to try making a new pull-request with just the commits you want.

**Comment by optimatic58** [comment]
that's weird... first, we rebased our source master (forked) off upstream master (prebid) to get them synced up and then rebased our optimatic-adapter branch off our master and pushed it.  not sure how this created an issue but now that this is done - how do we go about creating a new pull request?  We would have to create a new branch off the same master and wouldn't that still carry the same commit history?  may be we should have simply merged our master with the prebid upstream master rather than rebase it... regardless any ideas how to proceed?  thanks.

**Comment by optimatic58** [comment]
Submitted a new pull request - Support for NURL and ADM as backup #2112

**Pull request closed without merging**
