### PR TITLE
Somo prebid 3.0 updates

### PR DESCRIPTION
**Pull request by travisbeale**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [X] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Adding back Somo Audience Prebid adapter with 3.0 compliance.

- test parameters for validating bids
```
{
  bidder: 'somo',
          mediaTypes: {
            banner: {
              sizes: [[300, 250]]
            }
          },
          params: {
            placementId: 'test'
          }
  }
}
```

- prebid@somoaudience.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by travisbeale** [comment]
Failing test does not appear to be due to our code.

**Comment by jsnellbaker** [comment]
Hi @travisbeale 

It seems that some of the errors in the browserstack results look to be tied to the somoBidAdapter tests (specifically in IE11).  They appear to be failing when the tests are trying to validate the value in the `ortbRequest.site.domain` field.  

I think this potentially may be due to the slightly malformed mock URLs used in the `bidderRequest.refererInfo` objects used in the tests.  Below is a copy of one:
```
const bidderRequest = {
          refererInfo: {
            referer: 'https:/www.test.com/page?var=val',
            canonicalUrl: 'https:/www.test.com/page'
          }
        }
```
These URLs only have 1 `/` instead of 2.  I think IE11 may be handling this type of URL differently than the other modern browsers.  Can you try to set the extra `/` character to see if those IE11 tests pass?  If that's not the trick, can you dig a bit deeper to see what the issue may be?

**Comment by travisbeale** [comment]
@jsnellbaker Fixed the test, thanks catching that.

**Comment by jsnellbaker** [comment]
@travisbeale It seems that the error are still happening per the latest browserstack test ([here](https://circleci.com/gh/prebid/Prebid.js/5692?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).  Could you check around some more to see what may be the issue in IE11?

**Comment by travisbeale** [comment]
@jsnellbaker The CircleCI tests are now passing for our bid adapter in IE11.  The remaining CircleCI test failures do not appear to be in our code.

**Pull request merged**
