### PR TITLE
Prebid Server Bid Adapter : Support for custom headers for XHR call

### PR DESCRIPTION
**Pull request by sanved77**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

This PR introduces the capability to include custom headers in the XHR calls made to the Prebid Server bid adapter endpoint. By adding custom headers to the `s2sConfig` under the `customHeader` object, users can ensure that these headers are sent with the requests.

### Usage

```
// If only one server config is given

pbjs.setConfig({
  s2sConfig: {
    endpoint: 'https://prebid-server.example.com/bid',
    customHeader: {
      'Custom-Header': 'value'
    }
  }
});
```

```
// If multiple servers, then something like this

pbjs.setConfig({
    s2sConfig: [
        {
            name: "pbs-appnexus",
            customHeader: {
                'Authorization': 'Bearer token-appnexus',
                'Appnexus-Custom-Header': 'value-appnexus'
            }
        },
        {
            name: "pbs-rubicon",
            customHeader: {
                'Authorization': 'Bearer token-rubicon',
                'Rubicon-Custom-Header': 'value-rubicon'
            }
        },
    ],
});

```

### CODE REVIEW

**Comment by patmmccann** [comment]
Please make a docs pr. Thanks for the new feature!

**Comment by sanved77** [comment]
> Please make a docs pr. Thanks for the new feature!

You're welcome. Will add the docs PR

**Comment by sanved77** [comment]
@patmmccann 
Doc PR added as well - https://github.com/prebid/prebid.github.io/pull/5444

**Comment by patmmccann** [comment]
@bretg tagging you for input

**Review by dgirardi — APPROVED** [review]

**Review by PhreeMason — APPROVED** [review]

**Pull request merged**
