### PR TITLE
Changed invalid engine URL to a valid one, removed unnecessary params…

### PR DESCRIPTION
**Pull request by nanointeractive**
## Type of change

- [X] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- Changed invalid engine URL to a valid one for legacy adapter
- Fixed a bug (added 'body.forEach' in a serverResponse)
- Removed unnecessary parameters (doesn't change user-facing APIs)
- Updated documentation (md file)
- Updated test

### CODE REVIEW

**Comment by jsnellbaker** [comment]
Hi @nanointeractive I did try to test this again, but it seems like it's still the same.

Here's a copy of the response for reference:
```
[{"id":"2c59e8101923b4","bidderCode":"nanointeractive","cpm":0,"width":1,"height":1,"ad":"<div style=\"width:1px;height:1px;overflow: hidden;\"><div><\/div><\/div><img src=\"https:\/\/anz.audiencemanager.de\/log\/ad\/impression?id=57875debeb0a1926d103b941&adId=5635f685c0389ad458b7dbb63780a26d&alg=isrt-hsrt&rp=d&hb=1&dpid=58bfec94eb0a1916fa380162&pid=58bfec94eb0a1916fa380163&subId=&cb=1525882557\" style=\"display:none;\">","ttl":360,"creativeId":"5635f685c0389ad458b7dbb63780a26d","netRevenue":false,"currency":"EUR"}]
```

**Comment by jsnellbaker** [comment]
Hey @nanointeractive Did you have the chance to look into this again?

**Comment by nanointeractive** [comment]
Hey @jsnellbaker , I've changed the PID param value, now everything should be fine, sorry for the delay.

**Comment by jsnellbaker** [comment]
Hi @nanointeractive I did try the new param value but I'm still seeing the same no cpm response from the server.  Are you seeing this test criteria work when you use the `hello_world.html` page locally?

Given the server appears to be responding consistently with a formatted response and it's just the test placement that seems to be having issues, we could merge this in.  Or we could keep investigating.  Please let me know your thoughts.

```
[{"id":"2f10648e99a243","bidderCode":"nanointeractive","cpm":0,"width":1,"height":1,"ad":"<div style=\"width:1px;height:1px;overflow: hidden;\"><div><\/div><\/div><img src=\"https:\/\/anz.audiencemanager.de\/log\/ad\/impression?id=57875debeb0a1926d103b941&adId=0062ab9d66204c37cc74d766d14f8407&alg=isrt-hrt-mcam-ron&rp=d&hb=1&dpid=5afaa0280ae8996eb578de52&pid=5afaa0280ae8996eb578de53&subId=&cb=1526660310\" style=\"display:none;\">","ttl":360,"creativeId":"0062ab9d66204c37cc74d766d14f8407","netRevenue":false,"currency":"EUR"}]
```

**Comment by nanointeractive** [comment]
Hello @jsnellbaker , thanks for the input, I've enabled campaign for this test, now you should get a proper result. Please be free to merge it.

**Comment by jsnellbaker** [comment]
@nanointeractive Thanks for that change.  I can see the ad just fine now.

**Pull request merged**
