### PR TITLE
Adt new alias

### PR DESCRIPTION
**Pull request by GeneGenie**
## Type of change
- [x] Bugfix
- [x] Adding new alias + endpoint

## Description of change
Appaloosa service moved to unified prefix
Adding endpoint for onefiftytwo alias 
Adding new alias mediafuse
Added bidderCode splitter for those who may add custom alias to alias but keep remote url the same

- g.moroz@adtelligent.com
- [x] official adapter submission

### CODE REVIEW

**Comment by harpere** [comment]
@GeneGenie  your adapter tests are failing.

**Comment by harpere** [comment]
@GeneGenie - reminder that your adapter tests are failing.

**Comment by GeneGenie** [comment]
@harpere done

**Comment by GeneGenie** [comment]
Hey @harpere can you help me with this ?

**Review by harpere — APPROVED** [review]

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/2583

**Pull request merged**
