### PR TITLE
Prebid Core: Restore use of server-side adapter without client-side adapter

### PR DESCRIPTION
**Pull request by jorgeluisrocha**
## Type of change

- Bugfix

## Description of change
Fixes a bug that requires client-side adapter codes to be imported for server-side bidding. This obviates the need to import client-side adapter specifications. Additionally, this resolves the regression introduced by the original version of this PR found in #7662. 

## Other information
Issue: #6361 
Issue: #6388

### CODE REVIEW

**Review by FilipStamenkovic — CHANGES_REQUESTED** [review]
@jorgeluisrocha Looking at the test coverage, not a single test goes through your changes:

image


Can you add at least one test for the changes you did?

**Comment by ChrisHuie** [comment]
@jorgeluisrocha following up on this pr. Are you still working on this pr to add a little test coverage?

**Comment by patmmccann** [comment]
@karimMourra can you weigh in here? this seems stalled

**Comment by karimMourra** [comment]
Hi @patmmccann , Jorge will add unit tests to this PR when he has enough bandwidth

**Comment by ChrisHuie** [comment]
@karimMourra @jorgeluisrocha following up on this pr. Is it okay if I close this pr for now and it is just reopened when bandwidth provides

**Comment by bretg** [comment]
This PR is related to issue https://github.com/prebid/Prebid.js/issues/6361

For the record, client-side bid adapters defines 4 things that could be important to server behavior:

1. MediaTypes
2. Aliases
3. GVLID
4. transformBidParams

#1-3 are ok -- either they can be defined in s2sConfig as needed or they're also defined server-side.

A few bidAdapters do however, require transformBidParams() Those ones may not work well if the client-side adapter is not present.

**Comment by dgirardi** [comment]
This was incidentally fixed in #8357; just verified that no client side adapters are needed now for interfacing with Server.

**Pull request closed without merging**
