### PR TITLE
Update appnexusBidAdapter.js

### PR DESCRIPTION
**Pull request by matthieularere**
## Type of change
- [ ] Feature
- [ ] Other

## Description of change

Adding new aliases to appnexus adapter in order to use them in prebidserver (as the aliasBidder method has no equivalent in prebidserver)

### CODE REVIEW

**Comment by dbemiller** [comment]
@matthieularere is this what you're looking for in Prebid Server? https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md#bidder-aliases

If you're using the `/openrtb2/auction` endpoint, `Prebid.js` should take any `pbjs.aliasBidder` calls you make in JS and forward them in the request.

**Comment by matthieularere** [comment]
@dbemiller 
I did knew this was possible.

Is this openrtb2 response format compatible with all pbjs object functions ?

**Comment by dbemiller** [comment]
which function(s) do you need to work specifically?

I know that the Prebid.js design goal was to work with PBS's `/openrtb2` endpoint, and I know there's lots of code [inside the PBS Adapter](https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter.js#L451) trying to make it happen. If something doesn't work with openrtb2, you should be able to file an issue about it.

**Comment by jaiminpanchal27** [comment]
Closing this since it is not a valid change.

**Pull request closed without merging**
