### PR TITLE
AOL/VZM CCPA Compliance

### PR DESCRIPTION
**Pull request by slimkrazy**
## Type of change
- [ x] Feature

## Description of change
Pass CCPA consent to SSP endpoints.

- contact email of the adapter’s maintainer
aol.hb@teamaol.com

- [x] official adapter submission

## Other information
Changes based on the documentation in this issue and the implementation in the PR
https://github.com/prebid/Prebid.js/issues/4425
https://github.com/prebid/Prebid.js/pull/4502

### CODE REVIEW

**Comment by jsnellbaker** [comment]
Hi @slimkrazy 

If you haven't already, please ensure you submit a PR to the docs repo to update your bidder file ([here](https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders)) to support CCPA.  You just need to add the following variable to the top of your page:
`usp_supported: true`

Thanks.

**Comment by slimkrazy** [comment]
I'll update the docs repo later today - thanks @jsnellbaker

**Comment by Fawke** [comment]
@slimkrazy,

I was trying to get a response from your ad server using the **params** that you've shared in your md file, but, am not getting any response (**bid**) back.

Are there any extra params that I need to pass to get a response?

**Comment by slimkrazy** [comment]
Thanks @Fawke & @idettman 

Question: Will these CCPA changes be merged into the 3.0 branch as well?

**Pull request merged**
