### PR TITLE
LiveYield Analytics Adapter DfP Support

### PR DESCRIPTION
**Pull request by hamsterready**
## Type of change
- [x] Feature

## Description of change
Prebid.js quite often (:)) is being used with DfP and as such the final ad impression/revenue reporting shall take this under consideration. This PR allows one to pass DfP level details back to the LiveYield analytics server.

- [x] official adapter submission

### CODE REVIEW

**Comment by mike-chowla** [comment]
I tried testing this with the test params from #3443 but I'm getting the following error:
screen shot 2019-02-19 at 7 17 09 am

Could you add a comment with everything I need to get this to run?

**Comment by hamsterready** [comment]
Sure thing... you can find the code snippet that you are looking for in the correspnding [.md](https://github.com/prebid/Prebid.js/blob/master/modules/liveyieldAnalyticsAdapter.md) file. Here it is:

```html
<script>
(function(i,s,o,g,r,a,m,z){i['RTAAnalyticsObject']=r;i[r]=i[r]||function(){
z=Array.prototype.slice.call(arguments);z.unshift(+new Date());
(i[r].q=i[r].q||[]).push(z)},i[r].t=1,i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://tracker.liveyield.com/pubocean-tracker.min.js',
'rta');
</script>
```

after that enable analytics using:

```
{
  provider: 'liveyield',
  options: {
    customerId: 'b4c106a4-a8cb-4321-a9d2-aec3cde2e64e',
    customerName: 'Prebid Test',
    customerSite: 'prebid-test.com',
    sessionTimezoneOffset: '-300'
  }
}
```

Let me know if you need anything more.

**Comment by mike-chowla** [comment]
I'm getting a test failure:
screen shot 2019-02-22 at 5 23 51 pm

I test with your code on master sometimes these show up because a package was updated since you made the PR.

**Comment by hamsterready** [comment]
Thank you for this @mike-chowla - master merged to our branch, fix applied. Tests are passing. Please retest.

Cheers

**Pull request merged**
