### PR TITLE
Feature/refactoring adapter

### PR DESCRIPTION
**Pull request by kir-roxot**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter 
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change
We refactor our analytic adapter. PrebidAnalytics By Roxot.

### CODE REVIEW

**Comment by kir-roxot** [comment]
@matthewlane Thanks. Fixed. Can you take a look?

**Comment by mkendall07** [comment]
@kir-roxot Any update?

**Comment by mkendall07** [comment]
@kir-roxot 
please update or this will get closed out.

**Comment by bretg** [comment]
I've reached out to a contact at Roxot giving them a couple more days to respond before we close this PR.

**Comment by bretg** [comment]
My contact confirmed this PR can be closed.

**Pull request closed without merging**
