### PR TITLE
Issue 439 fix multi placement

### PR DESCRIPTION
**Pull request by CarsonBanov**
@mkendall07 

Fixes https://github.com/prebid/Prebid.js/issues/439.
We have tested this locally and it fixes our issue with the Sovrn adapter.

.cc @nanek @ehoch @sovrnoss

### CODE REVIEW

**Comment by mkendall07** [comment]
@CarsonBanov 
Can you explain the root cause of the issue here? The code removed from this PR is needed to match up data in the events sent out to analytics adapters. Ideally this should be fixed in the Sovrn adapter. Thanks

**Comment by nanek** [comment]
https://github.com/prebid/Prebid.js/issues/439#issuecomment-235440897 attempts to explain. In short, the code in reference sets the adId to the same value for all requests from a bidder for a adUnit. adId needs to be unique for everything to work.

Our prebid setup looks something like this for Sovrn, and other bidders where we want to request multiple bids from the same partner for the same adunit. One tagset supporting one ad size and another tagset supporting another ad size is one example.

```
      bids: [
        {bidder: 'sovrn',
        params: tagid: Sovrn.tagSet1[identifier]}
      ,
        {bidder: 'sovrn',
        params: tagid: Sovrn.tagSet2[identifier]}
      ]
```

This works great in v0.9.2. But once you add the code in this PR, the adId select is always the first bid response from the bidder for an adunit, instead of the winner, then it sets all bids to have the adId of that response. 

Perhaps there are alternate solutions, but we wanted to share what appears to work for us. This will impact any adapter that is configured more than once for an adUnit, so it is not really Sovrn adapter specific issue.

**Comment by mkendall07** [comment]
@nanek Thanks for explaining. Makes sense. Let me think about how to fix...

**Comment by mkendall07** [comment]
Closing this PR in favor of #498

**Comment by ehoch** [comment]
I've attempted to update to the latest Prebid after #498 and in an A/B test I can confirm 0.12-pre is still having performance issues compared to 0.10. 

We use the multiple requests for multi-size on more partners than just Sovrn. For us we're also using it on AOL and Pulsepoint.  Will this bug need to be fixed on every adaptor if we don't go with if we use 498 in lieu of reverting this?

**Comment by mkendall07** [comment]
@ehoch 
Good point. I'll check into that.

**Pull request closed without merging**
