### PR TITLE
Scaleable Analytics Adapter: Grouping Server Calls

### PR DESCRIPTION
**Pull request by cconnors1515**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Grouping all adunits together into a single call up to the server. This occurs once for auctions initiated and another time for bids/timeouts. Wins are still sent to server individually.
Also added a placeholder bidder for auction inits for each adunits to help differentiate requests for an adunit and requests for each bidder.

### CODE REVIEW

**Comment by cconnors1515** [comment]
Tests work fine on my local machine.

**Comment by cconnors1515** [comment]
@mkendall07 Just putting a message since it was marked as stale.

**Comment by cconnors1515** [comment]
@mkendall07 I merged in new master to bring in the XHR changes which allow for tests to work. The current failing test is a different adapter failing the linting.

**Comment by mkendall07** [comment]
@cconnors1515 
SOrry about that - can you rebase off master again to fix the linting errors?

**Comment by cconnors1515** [comment]
@mkendall07 Should be good to go now! I needed to add a local polyfill for Object.entries in order to pass tests on IE11. This probably should be added as an issue as local tests pass fine.

**Comment by cconnors1515** [comment]
@mkendall07 Can you add the need 2nd review label (if its needed) when you get a chance? Hoping to get this in for next release. Thanks!

**Comment by cconnors1515** [comment]
@mkendall07 @jsnellbaker Am I able to get this pushed to master? Thank You

**Comment by cconnors1515** [comment]
@jsnellbaker Thanks for the approval!

**Pull request merged**
