### PR TITLE
Fix for Issue 3130: passing new copy of adUnits object to every adapter

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
passing new copy of adUnits object to every adapter

## Type of change
- [x] Bugfix

## Description of change
https://github.com/prebid/Prebid.js/issues/3130

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @jsnellbaker,

Could you please review the change?
I have made a simple change, passing a new copy to every adapter(client and s2s) using utils.deepClone.
All unit test cases are passed without making a change in any unit test case.

**Comment by pm-harshad-mane** [comment]
Hello @snapwich ,

In version 1.25,
Before calling all client-side adapters we are creating a clone of AdUnits object, let's call it newAdUnitsObject and then we are passing this newAdUnitsObject to every adapter(same object to every adapter). If one of the adapters updates the newAdUnitsObject passed to it by mistake, then it affects newAdUnitsObject which is same for all adapters.

In the changes made, 
Before calling all client-side adapters we are creating a clone of AdUnits object, let's call it newAdUnitsObject and then we are passing a clone of newAdUnitsObject to every adapter(new object to every adapter). So if one of the adapters updates the clone of newAdUnitsObject by mistake, then it won't affect the clone of newAdUnitsObject shared with other adapters.

So with new changes, if there is an adapter making a mistake of affecting the common object won't need to fix the code as we will be passing a separate copy to every adapter.

**Comment by snapwich** [comment]
@pm-harshad-mane your fork was out-of-date with master so I've rebased off the latest.  I've also added a test that verifies your fix and protects against regressions.

LGTM

**Comment by pm-harshad-mane** [comment]
Thanks a lot, @snapwich and @jsnellbaker

**Pull request merged**
