### PR TITLE
Adding RevContent Bidder

### PR DESCRIPTION
**Pull request by AzizSaleh**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Adding RevContent Bidder

- test parameters for validating bids
```
{
  bidder: 'revcontent',
  params: {
      apiKey: '8a33sdfsdfdsfsdfssss544f8sdfsdfsdfd3b1c',  // Required
      userId: 69565,                                      // Required
      widgetId: 599995,                                // Optional
      domain: 'test.com',                                // Optional - Default referral hostname
  }
}
```

Test page: /integrationExamples/gpt/revcontent_example.html

- contact email of the adapter’s maintainer: aziz@revcontent.com
- [ x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/:
https://github.com/prebid/prebid.github.io/pull/1705

### CODE REVIEW

**Comment by robertrmartinez** [comment]
@AzizSaleh Hi, looks like there is some things checked in which should not be.

Can you please pull the latest from master.

As well as do not check in any changes to package.json or package-lock.json

And you have an added new line in modules/adformOpenRTBBidAdapter.js

So remove these and pull latest from master please.

**Comment by AzizSaleh** [comment]
Hey @robertrmartinez !

I tried pulling those files from prebid:master, however, the diff: https://github.com/prebid/Prebid.js/pull/4626/files is showing me changes that don't reflect prebid:master (where I pulled those files from).

**Comment by robertrmartinez** [comment]
@AzizSaleh Yeah, looks like your branch just diverged quite a bit from master, We merged the Prebid 3.0 changes into master since you originally pushed this branch over a month ago.

Honestly, if it is not too much of a hassle it could be better for you to clean your fork and rebase it with prebid master.

Then just create a new branch and include only your changes.

**Comment by AzizSaleh** [comment]
Makes sense. Will do that, thanks!

**Pull request closed without merging**
