### PR TITLE
zMaticoo Bid Adapter : Initial Release

### PR DESCRIPTION
**Pull request by lxj15398019970**
## Type of change

- [x] New bidder adapter   

## Description of change

zMaticoo Bid Adapter for Prebid.js

## Other information

the prebid docs PR is here : [https://github.com/prebid/prebid.github.io/pull/5056](https://github.com/prebid/Prebid.js/pull/url) https://github.com/prebid/prebid.github.io/pull/5056

### CODE REVIEW

**Comment by lxj15398019970** [comment]
please review

**Comment by lxj15398019970** [comment]
please review

**Comment by ChrisHuie** [comment]
@lxj15398019970 please update this pr to not remove the package-lock file from the project

**Comment by ChrisHuie** [comment]
> please review

This could take a couple of weeks to get reviewed since everyone is just getting back from the holidays and there are several new adapters to review.

**Comment by lxj15398019970** [comment]
please merge to the base master

**Comment by jlquaccia** [comment]
Hi @lxj15398019970, overall the code in the PR seems good to me.  Only a couple of asks..
- could you also create a docs PR for your bid adapter? (see https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
- looks there are some conflicts, could you resolve those too?

**Review by jlquaccia — CHANGES_REQUESTED** [review]
Hi @lxj15398019970, overall the code in the PR seems good to me. Only a couple of asks..

could you also create a docs PR for your bid adapter? (see https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
looks there are some conflicts, could you resolve those too?

**Comment by lxj15398019970** [comment]
> Hi @lxj15398019970, overall the code in the PR seems good to me. Only a couple of asks..
> 
> * could you also create a docs PR for your bid adapter? (see https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
> * looks there are some conflicts, could you resolve those too?

i have already create docs Pr about too week ago。[https://github.com/prebid/prebid.github.io/pull/5056](url)

**Comment by lxj15398019970** [comment]
@jlquaccia some unkonw reason .this pr is cloed，i create new pr .[https://github.com/prebid/Prebid.js/pull/10966](url)
please review

**Comment by lxj15398019970** [comment]
@jlquaccia @ChrisHuie  i have resolved code conflict and the prebid js docs PR is this:[https://github.com/prebid/prebid.github.io/pull/5056](url)。please help me review , The business is quite urgent, and many media want to cooperate with us through prebid js.

**Review by jlquaccia — APPROVED** [review]
LGTM

**Pull request merged**
