### PR TITLE
BeOp Bid Adapter: Fix tracker on BidWon and BidTimeout notice

### PR DESCRIPTION
**Pull request by sebrobert**
Don't know why params are in an array in that bid object. Make it work for both if it is fixed later

## Type of change
- [x] Bugfix
 
## Description of change
Our tracker was not working as the bid on bidWon and bidTimeout notice is having a "params" item as an array. Just get the first for that part of code

### CODE REVIEW

**Comment by sebrobert** [comment]
Hello @patmmccann ! Can you please give me some clues on how do I have to fix that branch to be released in a next coming version of Prebid please ? The failed tests do not seem to be BeOp related. Can I do something ?

**Comment by sebrobert** [comment]
The build is now **ok** ✅ , just need one approval to go in the next version of prebid. Until then our tracker is broken and we don't get any info from bidWon and bidTimeout notif. 🙏

**Comment by robertrmartinez** [comment]
@sebrobert Can you add an associated unit test?

Also, should we maybe update it to check the type of params first and then assign? Of course I leave that to you since you know your endpoint response format.

**Comment by sebrobert** [comment]
@robertrmartinez thanks for your followup ! 
I just made an update now. Seems to have an issue on another test from ours.

**Comment by robertrmartinez** [comment]
@sebrobert Can you please pull latest from prebid master branch?

Maybe that can resolve these failures. I have retried your circleCi test run many times and it keeps failing due to some randomness.

**Comment by robertrmartinez** [comment]
never mind it finally passed!

**Review by robertrmartinez — APPROVED** [review]

**Pull request merged**
