### PR TITLE
Utiq ID submodule: Update submodule name and parameters

### PR DESCRIPTION
**Pull request by jkthomas**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Other information

Documentation update PR -> https://github.com/prebid/prebid.github.io/pull/4920

### CODE REVIEW

**Comment by patmmccann** [comment]
all this is breaking; whats the goal

**Comment by jkthomas** [comment]
> all this is breaking; whats the goal

To follow prebid naming conventions based on Magnite feedback

**Review by smenzer — APPROVED** [review]
LGTM

**Comment by patmmccann** [comment]
@smenzer @jkthomas We're not able to merge this for a few months, as this is a breaking change

**Pull request merged**
