### PR TITLE
fluct Bid Adapter: updates for Prebid 5.0

### PR DESCRIPTION
**Pull request by toshi17**
## Type of change

- [x] Feature

## Description of change

- restore fluctBidAdapter.js compatible for Prebid 5.0
- add support for meta.advertiserDomains
    - related #6650

### CODE REVIEW

**Comment by toshi17** [comment]
ci fails with error...

```
24 08 2021 02:32:22.082:ERROR [launcher]: Cannot load browser "bs_edge_17_windows_10"!
  Error: Username is required.
```

I referred to this [comment](https://github.com/prebid/Prebid.js/pull/4740#issuecomment-576703428).
I was able to unfollow my forked version, but I'm not able to follow the main Prebid.js.
I've tried to get Prebid.js as my organization but had no success.
Is there a place where I can get more info about it? I've been searching online but no luck so far...

**Comment by ChrisHuie** [comment]
@toshi17 this is a weird CircleCI error because I don't appear to be able to rekick off the CircleCi test. Ususally I can rerun it. Is there any way to give me edit access to this pr to see if I can get it to work through my Circle credentials

**Comment by toshi17** [comment]
@ChrisHuie  I gave you access to the repo

スクリーンショット 2021-08-25 10 56 34

**Comment by ChrisHuie** [comment]
@toshi17 I thought my credentials might be able to override the local browserstack access key but doesn't seem to be working. I'm just going to resubmit this pr under my account and tag this pr to make sure this gets added back sooner rather than later. This is actually the first time i have come across this specific situation in CircleCI so going to have to research or talk to them so you don't have this problem with prs in the future

**Comment by toshi17** [comment]
@ChrisHuie Is there something I need to do or am I waiting on your review?

**Comment by ChrisHuie** [comment]
@toshi17 nothing. I will assign this pr out today to someone to get reviewed and I made the docs pr. So should be good

**Pull request closed without merging**
