### PR TITLE
Added VOX Bidder Adapter

### PR DESCRIPTION
**Pull request by hybrid-ai**
Added voxBidAdapter.js to get a bid from partners.hybrid.ai
PR Docs https://github.com/prebid/prebid.github.io/pull/2534

### CODE REVIEW

**Comment by GLStephen** [comment]
@hybrid-ai Things in general look good, but you are not sending any test bids, your images in the test page are coming up 404. We need valid 100% test bids to verify functionality.

**Comment by hybrid-ai** [comment]
> @hybrid-ai Things in general look good, but you are not sending any test bids, your images in the test page are coming up 404. We need valid 100% test bids to verify functionality.

Thank you for your comment. We added placements ids for testing.

**Comment by GLStephen** [comment]
@hybrid-ai I apologize for missing it before, but your code coverage is under our 80% requirement, you need to add more thorough testing to get to the 80% coverage.

**Comment by hybrid-ai** [comment]
> @hybrid-ai I apologize for missing it before, but your code coverage is under our 80% requirement, you need to add more thorough testing to get to the 80% coverage.

I checked it and I have these results for voxBidAdapter.js:

Statements - 82.26%
Branches - 92.11%
Functions - 80%
Lines - 81.97%

Do you have a different result?

**Pull request merged**
