### PR TITLE
Add user sync pixel logic in Adtelligent adapter

### PR DESCRIPTION
**Pull request by GeneGenie**
- [x] Feature

## Description of change
Adding cookie sync pixel support for Adtelligent adapter
Adding gdpr data support 

## Related PRs:
- docs https://github.com/prebid/prebid.github.io/pull/1053

## Misc
- g.moroz@adtelligent.com
- [x] official adapter submission

### CODE REVIEW

**Comment by GeneGenie** [comment]
@jsnellbaker I would be glad to do this, but 
`gulp test`
and 
`gulp serve`

are failing with  this trail :( 
```
[20:38:20] Working directory changed to ~/work/Prebid.js
[20:38:21] Using gulpfile ~/work/Prebid.js/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```


BUT! `npm test`  runs good =\ but takes too much time

**Comment by jsnellbaker** [comment]
@GeneGenie Did you install/setup `gulp-cli`?  There's a note about it on the install part of the README, [here](https://github.com/prebid/Prebid.js#Install).

**Comment by jsnellbaker** [comment]
Just saw your updates; can you copy the full `import` error so I can see?

**Comment by GeneGenie** [comment]
@jsnellbaker 
```
 gulp test --file ./test/spec/modules/adtelligentBidAdapter_spec.js 
[21:03:55] Using gulpfile ~/work/Prebid.js/gulpfile.js
[21:03:55] Starting 'test'...
[21:03:55] Starting 'clean'...
[21:03:55] Finished 'clean' after 57 ms
[21:03:55] Starting 'lint'...
[21:04:13] Finished 'lint' after 17 s
[21:04:13] Starting 'test'...

START:
07 12 2018 21:04:13.444:INFO [karma]: Karma v2.0.5 server started at http://0.0.0.0:9876/
07 12 2018 21:04:13.446:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
07 12 2018 21:04:13.452:INFO [launcher]: Starting browser ChromeHeadless
07 12 2018 21:04:13.814:INFO [HeadlessChrome 0.0.0 (Mac OS X 10.11.6)]: Connected on socket E9biGb-51DzvPabVAAAA with id 62387498
HeadlessChrome 0.0.0 (Mac OS X 10.11.6) ERROR
  {
    "message": "Uncaught SyntaxError: Unexpected token {\nat test/spec/modules/adtelligentBidAdapter_spec.js:1:8\n\nSyntaxError: Unexpected token {",
    "str": "Uncaught SyntaxError: Unexpected token {\nat test/spec/modules/adtelligentBidAdapter_spec.js:1:8\n\nSyntaxError: Unexpected token {"
  }

Finished in 0.144 secs / 0 secs @ 21:04:13 GMT+0200 (EET)

SUMMARY:
✔ 0 tests completed
[21:04:13] 'test' errored after 977 ms
[21:04:13] Error: Karma tests failed with exit code 1
    at /Users/moroz/work/Prebid.js/gulpfile.js:229:12
    at removeAllListeners (/Users/moroz/work/Prebid.js/node_modules/karma/lib/server.js:334:9)
    at webServer.close (/Users/moroz/work/Prebid.js/node_modules/karma/lib/server.js:344:11)
    at Server.close (net.js:1625:9)
    at Object.onceWrapper (events.js:255:19)
    at Server.emit (events.js:165:20)
    at emitCloseNT (net.js:1676:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
[21:04:13] 'test' errored after 18 s
```

Where adtelligentBidAdapter_spec.js:1  is:
`import {expect} from 'chai';`

**Comment by jsnellbaker** [comment]
@GeneGenie Thanks for providing the output; this type command isn't possible anymore due to the `karma-webpack` plugin not supporting the testing of individual files.

You'll either have to run the full `gulp test` command or carefully use the `.only` property in your unit test file.  If you insert the reference like the following `describe.only('adtelligentBidAdapter', function () {`, when you run `gulp test` - it will only run the tests for your adapter.

You'll have to remove this reference when you want to commit the changes, but it can be used while you're putting the tests together.

**Comment by GeneGenie** [comment]
Thank you for help!

**Comment by GeneGenie** [comment]
@jsnellbaker  Tests were added to get through min required lvl =) 
Thanks for help again

**Pull request merged**
