### PR TITLE
ZetaGlobalSsp AnalyticsAdapter: provide zeta params through cache

### PR DESCRIPTION
**Pull request by asurovenko-zeta**
## Type of change
- [x] Feature

### CODE REVIEW

**Comment by robertrmartinez** [comment]
@asurovenko-zeta 

Please add a unit test or two covering the change

**Review by osazos — COMMENTED** [review]
@asurovenko-zeta Please don't modify directly the `args` param you pass to your handlers. Instead use a copy, this way it can be safely modified before to be sent.

ex: 
```js
function adRenderSucceededHandler(orginalArgs) {
  const args = deepClone(originalArgs);
  // ...

  if (args.bid) {
    // cleanup object
    delete args.bid.metrics;
    delete args.bid.ad;
    // ...
  }
  // ...
   sendEvent(eventType, args);
}
  ```

**Comment by asurovenko-zeta** [comment]
@osazos sorry for the delay in fix. Now fix has been pushed.

**Review by osazos — APPROVED** [review]
LGTM

**Pull request merged**
