### PR TITLE
Weborama RTD submodule: add support to more bid adapters

### PR DESCRIPTION
**Pull request by peczenyj**
## Type of change

- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
add support for several bid adapter and set data on ortb2 global conf

- email: tpeczenyj@weborama.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

https://github.com/prebid/prebid.github.io/pull/3485

### CODE REVIEW

**Comment by peczenyj** [comment]
hey guys, if you had some doubt about this Pull Request please let me known

**Comment by peczenyj** [comment]
The error in ci seems a spurious error but I can’t rerun it

**Comment by peczenyj** [comment]
hey @umakajan are you available for this review? @jsnellbaker perhaps he is on vacation?

**Comment by peczenyj** [comment]
😢

**Review by jsnellbaker — COMMENTED** [review]
Hi @peczenyj 

I took a look through the changes here and I think they look fine (from what I can tell from the code alone).

I tried to load the updated test page as well though, and while the ad rendered fine - I noticed the endpoint URL for the RTD module (below) returned a 403 Forbidden error.
```
https://ctx.weborama.com/api/profile?token=to-be-defined&url=https%3A%2F%2Fprebid.org&
```

I realize the token wasn't really changed for this example, but I wanted to confirm that this would be the expected result here (or if something may be wrong).  Can you please confirm when you have the chance?

Thanks.

**Comment by peczenyj** [comment]
Hello @jsnellbaker 

To use a real token is really difficult, since there is an domain allow list per domain, I already ask for one just for this kind of demo and I am waiting. Anyway since this requests fails we use the default profile as fallback.

Regards

**Comment by jsnellbaker** [comment]
Thanks for providing the additional page.  I took a look at the information there and it still seems fine from what I can tell.  On the off-chance I did try to use the config settings outlined on the demo page in the test page here, but as I think you implied (via the domain list), it didn't help the endpoint URL from completing successfully.

If you're sure that the URL would be fine in a proper live environment, I can approve this PR; I haven't seen anything else really amiss.  If there's something else or some other way you'd want me to test - I'm willing to try.

Please let me know either way when you have the chance.  Thanks.

**Comment by peczenyj** [comment]
@jsnellbaker yes I am sure, in fact if you try you will see few examples did not work from other modules too.
once I have a better set of credentials I will update the example and documentation

**Review by jsnellbaker — APPROVED** [review]

**Comment by peczenyj** [comment]
great. Thanks a lot @jsnellbaker !

**Pull request merged**
