### PR TITLE
VidoomyAdapter: add schain and bidfloor to vidoomy adapter

### PR DESCRIPTION
**Pull request by sasanfarokh**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Adds support for `schain` in Vidoomy adapter.
Adds bidfloor parameter to params.

### CODE REVIEW

**Comment by sasanfarokh** [comment]
@ChrisHuie
Any updates on this PR?

**Comment by sasanfarokh** [comment]
Hey @ncolletti  ,
It's been a while since we added the support of `schain` and `bidfloor`, So this PR is a simple one just to pass these parameters along.
I would be happy to help if needed, Thanks a lot.

**Comment by ncolletti** [comment]
this looks fine, however could you add validation for the value type in `isBidRequestValid` and tests for both bidfloor and schain in your spec file? some guidance in your markdown as to what param properties are required vs optional would also be helpful.

**Comment by sasanfarokh** [comment]
> this looks fine, however could you add validation for the value type in `isBidRequestValid` and tests for both bidfloor and schain in your spec file? some guidance in your markdown as to what param properties are required vs optional would also be helpful.

Docs and tests are updated. :+1:

**Review by ncolletti — APPROVED** [review]
lgtm

**Pull request merged**
