### PR TITLE
PubMaticBidAdapter: Support for InBannerVideo (IBV) Field in Bid Response

### PR DESCRIPTION
**Pull request by pm-nitin-shirsat**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change

- Implementing functionality to consume and propagate the 'ibv' field from bid.ext to the bid response
- Adding the 'ibv' field in bid response enables publishers to Identify and track InBannerVideo traffic effectively

### CODE REVIEW

**Review by pm-harshad-mane — APPROVED** [review]
Looks good to me.

**Review by jlquaccia — COMMENTED** [review]
LGTM

**Comment by patmmccann** [comment]
This isn't the right place for this

**Comment by pm-harshad-mane** [comment]
@patmmccann can you please mention what is the recommended place for this?
We have intentionally added ext field as updating bid.mediaType creates rendering issues.

**Comment by pm-harshad-mane** [comment]
Hi @patmmccann 
We are waiting for your feedback.

**Comment by patmmccann** [comment]
yes

> Hi @patmmccann , is this a recommended approach? [7214c8e#diff-e4dbb62654fc2d8a7b5e6c2c66e0bae395cd945c1985f1509fd4484ecc79fa83R721](https://github.com/prebid/Prebid.js/commit/7214c8e742eda284e9c772b5c190ea7759b584ca#diff-e4dbb62654fc2d8a7b5e6c2c66e0bae395cd945c1985f1509fd4484ecc79fa83R721)

yes exactly, bid.meta.mediaType following many others https://github.com/search?q=repo%3Aprebid%2FPrebid.js+meta.mediatype&type=code

**Comment by patmmccann** [comment]
also i think you're setting bid.attr correctly in your prebid server openrtb responses; that's where i would expect it on the payload, and yes, ending up in bid.meta.mediaType

**Comment by pm-harshad-mane** [comment]
thanks @patmmccann ! we will update the PR.

**Pull request merged**
