### PR TITLE
Making originalCpm and originalCurrency fields in bid object always available

### PR DESCRIPTION
**Pull request by pm-harshad-mane**
## Type of change
- [X] Refactoring (no functional changes, no api changes)

## Description of change
Making originalCpm and originalCurrency fields in bid object always available
These attributes were available only when you include the currency module.
With these fields now we can also track the original cpm value even after cpm is modified by bidAdjustment flow.

Related issue: https://github.com/prebid/Prebid.js/issues/4393

### CODE REVIEW

**Comment by pm-harshad-mane** [comment]
Hello @bretg , 
Could you please review this small change?

**Comment by pm-harshad-mane** [comment]
Thank you @harpere 

Hello @jaiminpanchal27 
Could you please review as well?

**Comment by pm-harshad-mane** [comment]
Hello @jaiminpanchal27 ,

Could you please review the PR?

**Comment by jaiminpanchal27** [comment]
@pm-harshad-mane I have added this on my todo list to review before next release. Will take this soon. Thanks

**Comment by pm-harshad-mane** [comment]
Thank you for the update @jaiminpanchal27

**Comment by pm-harshad-mane** [comment]
Thank you @jaiminpanchal27 👍

**Pull request merged**
