### PR TITLE
fluct Bid Adapter: accept all eid sources

### PR DESCRIPTION
**Pull request by yowcow**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Accept all user EIDs by removing a filter limiting accepting sources.

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@yowcow I beleive you are following your own fork in CircleCI instead of the main Prebid project. You should be able to unfollow your fork on the left-hand side of CircleCI. That should fix the failing test issues.

**Comment by yowcow** [comment]
@ChrisHuie Thanks for pointing out!  I have disabled the CircleCI project on a fork in our organization, and now the build is running.  (Failed for a different reason, though)

**Comment by ChrisHuie** [comment]
@yowcow if you just pull in recent commits from master and fix conflict this should be good to go

**Comment by yowcow** [comment]
@ChrisHuie Thanks, merged the updated master and conflicts are now resolved :pray:

**Comment by yowcow** [comment]
Recently merged #10318 contained commits in this branch.
There's no more changes to apply, so I'm just closing this PR.

**Pull request closed without merging**
