### PR TITLE
Tappx Bid Adapter: getting correct site page

### PR DESCRIPTION
**Pull request by prebidtappx**
We are modifying the adapter to get better results obtaining the site page (current URL).

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@prebidtappx can you pull in recent commits and add unit testing for this pr please 🙏

**Comment by prebidtappx** [comment]
Hello,
All the changes are to increase the information in the request. None of these parameters are mandatory and for this reason we think that it is not required any unit test.
Please, can you approve the merge request?
Thanks

**Comment by ChrisHuie** [comment]
@prebidtappx This pr is 250+ commits behind master still. Can you please update

**Comment by prebidtappx** [comment]
Hello @ChrisHuie 
We made the sync force and now we have an error to pass the e2etest. Can you help us with this:
image
Thanks

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
