### PR TITLE
Prebid adapter for windtalker

### PR DESCRIPTION
**Pull request by degroat**
## Type of change

- [ X] New bidder adapter

## Description of change
Prebid adapter for Windtalker.

- test parameters for validating bids
```
{
  bidder: 'windtalker',
  params: {
           "pubId":"187046"
           ,"siteId":"10"
           ,"size":"300x250"
           ,"placementId":"456"
  }
}
```

- contact email of the adapter’s maintainer: corbin@windtalker.io
- [X ] official adapter submission

PR Docs: prebid/prebid.github.io#1788

### CODE REVIEW

**Comment by degroat** [comment]
@Fawke Please try again.  We had some geo restrictions in place that were likely causing the issue.

**Comment by Fawke** [comment]
@degroat,

I was still unable to get bid responses from India, so I told my colleague in US to test it. He got `banner` and `video` responses, but `native` still returned a `204`. 

Can you check?

**Comment by degroat** [comment]
@Fawke Native should be good now too.

**Comment by jsnellbaker** [comment]
Hi @degroat 

I was helping @Fawke earlier this morning with testing the adapter.  I tried the native params again, but I'm still not seeing a bid response.  I have copied the reqeust payload for reference:
```
{"id":"1edbd0adef7518","at":2,"imp":[{"id":"2dbf47e4c6a34f","secure":0,"banner":null,"native":{"request":"{\"assets\":[{\"id\":1,\"required\":1,\"title\":{\"len\":75}},{\"id\":2,\"required\":0,\"data\":{\"type\":2,\"len\":200}},{\"id\":4,\"required\":0,\"img\":{\"type\":1,\"wmin\":50,\"hmin\":50}},{\"id\":5,\"required\":1,\"img\":{\"type\":3,\"wmin\":150,\"hmin\":150}}]}","ver":"1.1"},"video":null,"bidfloor":"0.001","tagid":"123"}],"site":{"publisher":{"id":"584971","domain":"test.localhost"},"id":"584971","ref":"http://test.localhost:9999/integrationExamples/gpt/demo_native.html?pbjs_debug=true","page":"http://test.localhost:9999/integrationExamples/gpt/demo_native.html?pbjs_debug=true"},"app":null,"device":{"dnt":0,"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","language":"en-US","w":1680,"h":1050,"geo":{"lat":"40.712775","lon":"-74.005973"},"ifa":"XXX-XXX"}}
```

Can you take a look?

**Comment by degroat** [comment]
@jsnellbaker I'm getting a bid back now.  Here is my payload.

`{"id":"18b51e44536611","at":2,"imp":[{"id":"2fe652226cbdd3","secure":0,"banner":null,"native":{"request":"{\"assets\":[{\"id\":1,\"required\":1,\"title\":{\"len\":100}},{\"id\":2,\"required\":0,\"data\":{\"type\":2,\"len\":200}},{\"id\":4,\"required\":0,\"img\":{\"type\":1,\"wmin\":50,\"hmin\":50}},{\"id\":5,\"required\":1,\"img\":{\"type\":3,\"wmin\":150,\"hmin\":150}}]}","ver":"1.1"},"video":null,"bidfloor":"0.000001","tagid":"456"}],"site":{"publisher":{"id":"584971","domain":"localhost"},"id":"584971","ref":"","page":"http://localhost:9999/integrationExamples/gpt/native.html?pbjs_debug=true"},"app":null,"device":{"dnt":0,"ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36","language":"en-US","w":1920,"h":1080,"geo":{}}}`

**Pull request merged**
