### PR TITLE
Outbrain bid adapter: added floor module and privacy link support

### PR DESCRIPTION
**Pull request by markkuhar**
## Type of change

- [x] Feature

## Description of change

- added support for Prebid floor module
- added privacy link support
- added more validation of bid request format

contact email of the adapter’s maintainer
  - mkuhar@outbrain.com

### CODE REVIEW

**Comment by Rothalack** [comment]
This looks good on the code side. I think you need to get your docs updated to say your bid adapter accepts bidfloor and privacy link. You'll want to get a PR of that change here! https://github.com/prebid/prebid.github.io/pulls

**Comment by markkuhar** [comment]
Thanks for review @Rothalack! Can you please suggest how should I add to docs that we support passing privacyLink? I couldn't find any example.

**Comment by markkuhar** [comment]
Cool. I just opened PR with updated docs. https://github.com/prebid/prebid.github.io/pull/3670

**Review by Rothalack — APPROVED** [review]

**Comment by Rothalack** [comment]
Looks good, merging now.

**Pull request merged**
