### PR TITLE
OneVideo: CCPA and GDPR support for version 3.0

### PR DESCRIPTION
**Pull request by DeepthiNeeladri**
## Type of change

- [ x] Bugfix

## Description of change
onevideo adapter is supporting both CCPA and GDPR for 2.24.x  and 3.1.0 missed one use case in 3.0.0 so adding it

the 3.1.0 code is https://github.com/prebid/Prebid.js/pull/4571/files which is merged

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by jsnellbaker** [comment]
@DeepthiNeeladri the `prebid-3.0` is no longer in use.  Can you please re-pivot the PR to target `master` instead?

**Comment by msm0504** [comment]
@DeepthiNeeladri Your code changes are fine, but could you also merge the latest from `Prebid:master` into your fork? I think doing that will fix these failing circleci tests

**Comment by bretg** [comment]
@DeepthiNeeladri - to get this one across the finish line, need you to change the PR to merge into master, not the prebid:prebid-3.0 branch. 

Also, as msm0504 notes, we can't get unit tests to pass but if you rebased your fork from master it would probably work better.

And finally, we recommend making CCPA changes also in the 2.44.x-legacy branch as well since some key adapters haven't been upgraded to 3.x yet, many pubs are still on 2.44.x.

**Comment by DeepthiNeeladri** [comment]
@bretg I already merged the legacy 2.44.x https://github.com/prebid/Prebid.js/pull/4648
and for 3.1 https://github.com/prebid/Prebid.js/pull/4571 I thought i can add for 3.0 also. it hink i don't need this PR now

**Pull request closed without merging**
