### PR TITLE
cee Id System : initial ID module release

### PR DESCRIPTION
**Pull request by decemberWP**
## Type of change

- [x] Other

## Description of change

Name change from pirIdSystem to ceeIdSystem

### CODE REVIEW

**Comment by decemberWP** [comment]
Github shows these changes a bit weird, because on branch grupawp:ceeidsystem I've deleted pirIdSystem.js, pirIdSystem.md and pirIdSystem_spec.js however it doesn't show it's deleted. Should I create another PR to just delete these files?

**Comment by ChrisHuie** [comment]
> Github shows these changes a bit weird, because on branch grupawp:ceeidsystem I've deleted pirIdSystem.js, pirIdSystem.md and pirIdSystem_spec.js however it doesn't show it's deleted. Should I create another PR to just delete these files?

Yes. However, the delete will need to happen in a major release. Right now we have a prebid.js 9.0 branch for our upcoming major release with breaking changes. If you can submit your delete pr to that branch it would be appreciated.

**Comment by decemberWP** [comment]
@ChrisHuie Thanks for info. PirIdSystem delete PR here: https://github.com/prebid/Prebid.js/pull/11518

**Review by smenzer — APPROVED** [review]
LGTM

**Pull request merged**
