### PR TITLE
PulsePoint Adapter: Fixing issues related to Prebid 5.0

### PR DESCRIPTION
**Pull request by anand-venkatraman**
## Type of change
- [x] Refactoring (no functional changes, no api changes)

## Description of change
This PR addresses the issues that were marked for Prebid 5.0 release, listed below.
https://github.com/prebid/Prebid.js/issues/6650
https://github.com/prebid/Prebid.js/issues/6512
https://github.com/prebid/Prebid.js/issues/6465

### CODE REVIEW

**Comment by patmmccann** [comment]
Excellent thank you! Can you also change pulsepointBidAdapter.md and any other doc to move the openrtb parameters to the ad unit in your video examples?

**Comment by anand-venkatraman** [comment]
Docs updated in `prebidBidAdapter.md` and prebid.org docs https://github.com/prebid/prebid.github.io/pull/2993

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
It is unclear to me what is happening with circleci tests, but we'll get this merged before the next release. Thanks!

**Comment by ChrisHuie** [comment]
@anand-venkatraman @patmmccann I believe a pr that we reverted on Tuesday is in this pr. Fetch and merging upstream should fix the tests.

**Comment by anand-venkatraman** [comment]
I pulled latest upstream changes and tests are passing.

**Pull request merged**
