### PR TITLE
PubMatic adapter updated

### PR DESCRIPTION
**Pull request by PubMatic-OpenWrap**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x ] Build related changes
- [ x] CI related changes
- [ x] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: UOEDev@pubmatic.com
- [ ] official adapter submission

### CODE REVIEW

**Comment by mkendall07** [comment]
@PubMatic-OpenWrap 
it seems like you changed file permissions on all the files. Please revert those changes so we can review. Thanks.

**Comment by PubMatic-OpenWrap** [comment]
Hi @mkendall07 ,
I am not sure what exact steps I need to take to revert file permissions. 
Can you help me ?
Thanks.

**Comment by dbemiller** [comment]
On linux/mac, `chmod`: https://linux.die.net/man/1/chmod

**Comment by PubMatic-OpenWrap** [comment]
Thanks @dbemiller for your quick response.
But I am using Windows 7 Pro, and not sure what permissions should be for all files.

**Comment by dbemiller** [comment]
Honestly... if it were me, I'd start fresh from `master`, copy/paste all the changes I intended to make, and be careful not to change the file permissions this time. If I didn't do it intentionally, I'd avoid using whatever IDE I used the first time, because it might have set them automatically.

Otherwise, you can view the correct file permissions by checking out `master`, viewing them, and then checking out your current branch and changing them again. It looks like you changed ~100 files, though... so this might take a while.

Googling for "windows 7 pro file permissions" sent me here: https://technet.microsoft.com/en-us/library/cc754344(v=ws.11).aspx

Maybe that will help?

**Comment by mkendall07** [comment]
@PubMatic-OpenWrap 
I agree with Dave suggestion, starting from scratch and committing *just* your file is the best option here.

**Comment by dbemiller** [comment]
Closing this, in light of #1707

**Pull request closed without merging**
