### PR TITLE
Add flash detection to TripleLift adapter

### PR DESCRIPTION
**Pull request by tiffwu**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change

Adding a check for Flash support.

### CODE REVIEW

**Comment by protonate** [comment]
@tiffwu please resolve conflicts and we'll assign for review.

**Comment by tiffwu** [comment]
Hi @protonate -- by conflicts do you mean the test that failed? The error logged was:
> line 79  col 20  'ActiveXObject' is not defined.

^ this object exists in IE, and the line is wrapped in a try/catch block which then proceeds to check for Flash support in non-IE browsers.

**Comment by mkendall07** [comment]
@tiffwu 
No, conflict in git for the source. Please resolve the conflict so it can be merged. 

To fix the build error you need to preface `ActiveXObject` with `window` so jshint doesn't think it's undefined (it's a linting failure). IE `new window.ActiveXObject`

**Comment by tiffwu** [comment]
@mkendall07 Thank you. Fixed!

**Comment by mkendall07** [comment]
LGTM.

**Pull request merged**
