### PR TITLE
AdKernel Bid/Analytics Adapters: user privacy related changes

### PR DESCRIPTION
**Pull request by ckbo3hrk**
## Type of change
- [x] Other

## Description of change
User privacy - related changes for adkernel /adkernelAdn and adkernel analytics adaptors

- prebid-dev@adkernel.com
- [x] official adapter submission

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@ckbo3hrk going forward can you please split these types of prs into at least the adapter type. So one pr for changes to the bid adapters and 1 pr for changes to the analytics adapter.  That way it's just a bit easier to manage on the review side and scope of prs. Thanks

**Comment by ckbo3hrk** [comment]
@ChrisHuie My bad. I'll stick with this approach in the future.

**Review by ncolletti — APPROVED** [review]
LGTM. Will wait on merge till a docs pr is created mentioning new updates mainly for the analytics adapter, for reference: https://docs.prebid.org/dev-docs/integrate-with-the-prebid-analytics-api.html#step-5-website-pull-request

**Comment by ckbo3hrk** [comment]
@ncolletti https://github.com/prebid/prebid.github.io/pull/2823

**Pull request merged**
