### PR TITLE
YIELDONE adapter - add viewable rendering format

### PR DESCRIPTION
**Pull request by koji-eguchi**
## Type of change
- [x] Feature

## Description of change
- add viewable rendering format
  - render banner ad in viewable format if renderid in response is "ViewableRendering"

- contact email of the adapter’s maintainer y1dev@platform-one.co.jp
- [x] official adapter submission

### CODE REVIEW

**Comment by koji-eguchi** [comment]
@GLStephen 
Please confirm this.

**Comment by koji-eguchi** [comment]
@GLStephen @harpere 

Please confirm this.

**Comment by koji-eguchi** [comment]
Please confirm this.
why this request labeled both "needs review" and "stale" ?

**Comment by GLStephen** [comment]
@koji-eguchi I will review as soon as able, the review request was misplaced in a flurry of Git notifications

**Comment by koji-eguchi** [comment]
@GLStephen 
OK, Thanks.

**Pull request merged**
