### PR TITLE
GoldfishAds Rtd Provider : Initial Module Release

### PR DESCRIPTION
**Pull request by keithdoggett**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

New RTD module made by Goldfish Ads.

Email: keith@goldfishads.com

## Other information

Prebid github.io PR: https://github.com/prebid/prebid.github.io/pull/4935

### CODE REVIEW

**Comment by Rothalack** [comment]
This looks good in testing.

I'm not sure what should be done about the e2etest failure. I see this same error is happening in many builds. It looks unrelated to your code. My best guess is to try pulling master to see if there's a fix for it?

Do you have any information on this error @ChrisHuie ?
WARNING in ./modules/genericAnalyticsAdapter.js 59:13-44
export 'EVENTS'.'hasOwnProperty' (imported as 'CONSTANTS') was not found in '../src/constants.json'

**Comment by Rothalack** [comment]
It just occurred to me, it might be because you need to be added to adloader.js. Not certain.

**Comment by keithdoggett** [comment]
@Rothalack thanks for the review! I synced the fork and that seems to have fixed the tests. Let me know if you need any other changes.

**Review by Rothalack — APPROVED** [review]
Looks good

**Pull request merged**
