### PR TITLE
Sonobi Adapter - Added referrer param. Fixed timeout error in userSync

### PR DESCRIPTION
**Pull request by JonGoSonobi**
## Type of change
- [x] Bugfix
- [x] Feature

## Description of change
Added a referrer param to override the default window.location.host.
Fix for issue https://github.com/prebid/Prebid.js/issues/2489

- apex.prebid@sonobi.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

https://github.com/prebid/prebid.github.io/pull/744

## Other information
Fixes Issue https://github.com/prebid/Prebid.js/issues/2489

### CODE REVIEW

**Comment by JonGoSonobi** [comment]
@ndhimehta any movement on this?

**Comment by dmitriyshashkin** [comment]
@JonGoSonobi  tbh, not the best way to fix the problem. Instead of checking if the array is empty you wrap it in a try/catch. Not the most appropriate way to check the length of the array. And then you log the error. The situation that is causing the error is not uncommon or unexpected, requests to server timeout all the time. And now I get an ugly error message each time sonobi times out.

**Comment by JonGoSonobi** [comment]
@dmitriyshashkin The error should only be logged in debug mode. In which case it would let you know that the timeout for the Sonobi adapter is too low and that you should consider increasing it.

**Comment by dmitriyshashkin** [comment]
@JonGoSonobi `TypeError: Cannot read property 'body' of undefined` - it's rather difficult to understand that I should consider raising the timeout from this message. Besides prebid already fires the following error `Server call for sonobi failed: . Continuing without bids.` I'd say it's much more informative

**Comment by JonGoSonobi** [comment]
@dmitriyshashkin PR opened to remove the debug logging. https://github.com/prebid/Prebid.js/pull/2686
We left the try catch, otherwise we would have to check for not only the serverResponses Array being not empty, but also that the first index of it has a body and sbi_px is an array. We feel that just surrounding the parsing of server responses in a try catch is a much neater approach.

**Pull request merged**
