### PR TITLE
Adnuntius Bid Adapter: read sizes from request

### PR DESCRIPTION
**Pull request by mikael-lundin**
## Type of change

- [x] Feature

## Description of change

Just us reading the sizes from the request and passes them onto the ad server. No changes to the documentation needed, since this should be the default behavior of prebid.

- contact email of the adapter’s maintainer: prebid@adnuntius.com
- [x] official adapter submission

### CODE REVIEW

**Review by Fawke — COMMENTED** [review]
Hi @mikael-lundin,

I see that you're adding support for Video mediatype. Are you sure it won't require a change to the docs?

And I think you have mistakenly include the package-lock.json file in your commit. Can you please remove that?

**Comment by mikael-lundin** [comment]
Ah, my bad. The video I thought was already released, it should be in this documentation change:
https://github.com/prebid/prebid.github.io/pull/3905

**Comment by ChrisHuie** [comment]
@mikael-lundin this pr seems to remove the package.json file. Can you double check please 🙏

**Comment by mikael-lundin** [comment]
haha, for the love of god, I suck. hold on.

**Pull request closed without merging**
