### PR TITLE
IronSourceBidAdapter: Change logic of detect pageURL

### PR DESCRIPTION
**Pull request by liranbaruch**
## Type of change

- [ x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

We want to detect the page_url in different method than used before

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by osazos — APPROVED** [review]
LGTM

**Comment by noamtzuberi** [comment]
Hi @osazos @gglas ,

Any news? Thanks.

**Comment by gglas** [comment]
Hey Liran!  Releases were delayed over the holidays, we expect this week to resume normal schedule.

**Comment by liranbaruch** [comment]
Thank you for the update !
Happy new year :)

**Pull request merged**
