### PR TITLE
sharedIdSystem: return pubcid instead of sharedId

### PR DESCRIPTION
**Pull request by philipwatson**
## Type of change

- [x] Bugfix

## Description of change
I had a look at `sharedIdSystem.js` after the changes made in https://github.com/prebid/Prebid.js/pull/6808 for issue https://github.com/prebid/Prebid.js/issues/6640

I'm confused.

It doesn't make sense to me that the `sharedId` is passed into the callback. Should it be `pubcid` instead?

It could do with more tests. I didn't invest much time there because my understanding could be wrong.

From unit testing, I noticed `storage.expires` in the storeData function does not exist (or does it?). So I changed to `config.storage.expires`. Not sure if this is correct.

### CODE REVIEW

**Comment by jdwieland8282** [comment]
@NothingIsMatter Mind taking a look here?

**Comment by jdwieland8282** [comment]
@ChrisHuie re:  "return pubcid instead of sharedId 4 days ago"  can you ad more here?  The user id generated by the module formally known as pubcommon and the module formally known as sharedid, were just random string generators. The user id output of either shouldn't matter.  

The intention was to have a guid set in a 1pc, then added to the eids array using pubcid.org as the source.

**Comment by philipwatson** [comment]
Let me give a scenario to help raise the alarm a little ;-)

Given default `auctionDelay` of 0. A new user. On page load:

Bidders receive `bid.userId` as: 
```
{
   pubcid: "0ea08523-0ceb-4ae6-bde3-84b34c2eb893"
}
```
The value is a UUID created on the page (by sharedIdSystem's `getId`). All good here.

Then I look at the cookies in developer tools. I see the cookies created via sharedIdSystem:
_pubcid = 01EWC4FHX0QQEV1HGR16HAQGPM
_pubcid_sharedid = 01EWC4FHX0QQEV1HGR16HAQGPM

They are set to the same ULID value from sharedid server. The callback, which is run after the auction, replaces the established UUID with the ULID. Note: this will also happen to existing users (not just new users) when `getId` is called for a refresh.

So on the next page load, bidders receive `bid.userId` as:

```
{
   sharedid: {id: "01EWC4FHX0QQEV1HGR16HAQGPM"},
   pubcid: "01EWC4FHX0QQEV1HGR16HAQGPM"
}
```

For completeness, `bid.userIdAsEids` has:

```
[{
  source: "pubcid.org",
  uids: [{
    id: "01EWC4FHX0QQEV1HGR16HAQGPM",
    atype: 1
  }]
}]
```
Only pubcid.org here which is expected after reading the code - sharedId is filtered out (or do we want to see two items in the `uids` array here?)

sharedIdSystem manages the storage of `_pubcid_sharedid`.. but also gets the user id module to manage the storage of `_pubcid` with the same value. Obviously there is a problem here right?

**Comment by jdwieland8282** [comment]
Hey @philipwatson thanks for the example, we are taking a look, it does indeed look like a problem.  What we want in the eids array according to you example is indeed. 

```[{
  source: "pubcid.org",
  uids: [{
    id: "0ea08523-0ceb-4ae6-bde3-84b34c2eb893",
    atype: 1
  }]
}]

**Comment by ChrisHuie** [comment]
@philipwatson do you mind pulling in the latest commits from master to make sure the circleci tests are passing for this pr 🙏

**Comment by philipwatson** [comment]
No more changes coming in this PR. 
I've merged master. Can anyone rerun the build? An unrelated test is suspiciously timing out even though there is not much in it. Same test is failing on another PR.

**Comment by SKOCHERI** [comment]
@philipwatson The SharedIdSystem need not call the Sharedid endpoint. The same has been updated in https://github.com/prebid/Prebid.js/pull/7149 and the SharedIdSystem module is cleaned up to removed read/write cookie. Please take a look at this PR.

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
