### PR TITLE
Openx - creative rendering

### PR DESCRIPTION
**Pull request by nickjacob**
We got feedback during implementation that the rendered creative through `get('html')` wasn't including the necessary tracking pixels on all creatives; this PR is to replace using the html property with openx's API's rendering logic, which requires a bridge back into the parent window (`window.pbjs.ox_renderAd`)

### CODE REVIEW

**Comment by mkendall07** [comment]
Hey @nickjacob ,

I'm getting a `adUnit.get is not a function` error when running this code. Is this working for you?

**Comment by mkendall07** [comment]
I found the issue, you need a 2nd argument in `_createBidResponse()`

**Comment by premesh** [comment]
Hi, looking to test this out but assuming OpenX isnt working because of this issue? That correct?

**Comment by mkendall07** [comment]
HI @premesh,

I believe the impact is not all the pixels where firing, but the creative was still rendering. This fix will be merged shortly

**Comment by nickjacob** [comment]
yeah sorry; going to fix via CR & push changes in a second

**Comment by prebid** [comment]
@nickjacob, @bwschmidt is the engineering lead from OpenX and is also an admin of Prebid.js. Do you think he can help out here?

**Comment by nickjacob** [comment]
@prebid @bwschmidt  yeah that'd be great. Just pushed fix so the branch should work

**Comment by premesh** [comment]
Great thanks @nickjacob ! Looking forward to get this integration going on our site (ranker.com) :)  

@bwschmidt  FYI our Openx Rep just told me you guys dont support Prebid 

"In regards to the prebid, we currently do not support integrations with the product.  Our engineering team is looking into the product but currently we do not recommend implementing"

**Comment by prebid** [comment]
@ialex is working with @bwschmidt on another thread for their OpenX implementation. Any updates that can help the folks in this thread out?

**Comment by bwschmidt** [comment]
@premesh Correct, we are currently not recommending implementation with the current adapter. We are working on a new adapter but have been stalled on a release dependency. I anticipate being done early next week.

**Comment by premesh** [comment]
@bwschmidt  thanks for the heads up. We are currently using openx with a direct install so my plan was to switch to prebid with OpenX first before moving on to others. Assuming the how I set this up with prebid wont change and that i just need to wait for your changes before we go to prod ?  Or should will testing not work now anyways locally with the current release?

**Comment by premesh** [comment]
hey @bwschmidt  any update?

**Comment by prebid** [comment]
@bwschmidt could you let us know if you're still planning on releasing your version of the OpenX adaptor?

**Comment by mkendall07** [comment]
Hey @nickjacob  can you re-submit PR so it can be automatically pulled into  master if it's not too much trouble?

**Comment by nickjacob** [comment]
yeah no problem I'll rebase

On Wed, Nov 11, 2015 at 3:01 PM, mkendall <notifications@github.com> wrote:

> Hey @nickjacob <https://github.com/nickjacob> can you re-submit PR so it
> can be automatically pulled into master if it's not too much trouble?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prebid/Prebid.js/pull/60#issuecomment-155894899>.
>



-- 
 Lead Engineer, A Plus | nick@aplus.com | 617-680-0337

**Comment by mkendall07** [comment]
Thanks!

**Comment by nickjacob** [comment]
making a couple fixes this isn't good to go yet sry

**Comment by nickjacob** [comment]
actually I need to link up with our technical AM; concerned that this might not be the best integration.

**Comment by bwschmidt** [comment]
@prebid Apologies, I have been informed by my product manager to hold off on releasing the adapter at this time.

**Pull request closed without merging**
