### PR TITLE
RichAudience: Files name updated

### PR DESCRIPTION
**Pull request by richaudience**
## Type of change
- [X] Bugfix

## Description of change
Updating files name and bidder code for avoiding future errors

### CODE REVIEW

**Comment by bretg** [comment]
@richaudience - are you ready for this rename to take effect in PBJS 2.13? Any publisher's your working with would need to change their pages before upgrading

**Comment by richaudience** [comment]
Hi @bretg,

Yes, we are ready for this changes. We noticed that to the publisher we are working with.

Thanks for the comment!

**Comment by richaudience** [comment]
Hi,

We've seen that you have done two new releases, but our changes are not uploaded yet. There is something wrong?

Thanks

**Comment by bretg** [comment]
sorry - fell off my radar. Merging.

**Pull request merged**
