### PR TITLE
APS TAM Adapter deployment

### PR DESCRIPTION
**Pull request by balajimediafuse**
## Type of change
- [ ] Other
Prebid team, we have TAM adapter created for Amazon Publisher Services (APS) and we wanted this to be hosted privately. Please let us know whether the Prebid environment facilitates deploying TAM adapter privately

### CODE REVIEW

**Comment by patmmccann** [comment]
which part of your code interacts with the aps library?

**Comment by ChrisHuie** [comment]
@balajimediafuse it looks like this pr is separate from master. Can you please pull in commits on master to eliminate the conflicts?

**Comment by patmmccann** [comment]
Here are a couple historical references to calling https://gist.github.com/Heray/277d421bda2b827f43da and https://github.com/prebid/Prebid.js/issues/393

**Comment by patmmccann** [comment]
Closing due to non-responsive OP

**Pull request closed without merging**
