### PR TITLE
Timmedia/timadapter

### PR DESCRIPTION
**Pull request by shlomisut**
## Type of change

- [x] New bidder adapter   

## Description of change

- test parameters for validating bids
```
{
"bidder":"tim",
                "params":{
                "placementCode":"testPlacementCode",
                "publisherid":"testpublisherid"
                }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
shlomi@thetimmedia.com
- [x] official adapter submission

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/1117

### CODE REVIEW

**Comment by shlomisut** [comment]
retest this please

**Comment by shlomisut** [comment]
retest this please

**Comment by shlomisut** [comment]
Hello @mike-chowla , @jaiminpanchal27 
from what I see the build breaks on other adapter tests. this happened before, and re-testing the build made it green 

aside from the fact this indicates an unstable test/build - is there a way to retest the PR without dummy-pushing a commit? 

`retest this please` works for the jenkins build we use, but I couldn't find a way to do so for circleci. 
for now I'll push another dummy commit for it to retry, would be great to have a better way for it

thanks!
Shlomi

**Comment by mike-chowla** [comment]
I'm not getting any bids back.

here's the request url:
http://hb.stinger-bidder.tech/api/v2/services/prebid/testpublisherid/testPlacementCode?br=%7B%22id%22%3A%223313db1607fade%22%2C%22imp%22%3A%5B%7B%22id%22%3A%22264052c6259d9f%22%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A250%7D%2C%22tagid%22%3A%22testPlacementCode%22%7D%5D%2C%22site%22%3A%7B%22domain%22%3A%22mike.pubmatic.com%3A9999%22%2C%22page%22%3A%22http%3A%2F%2Fmike.pubmatic.com%3A9999%2FintegrationExamples%2Fgpt%2Fhello_world.html%3Fpbjs_debug%3Dtrue%22%2C%22publisher%22%3A%7B%22id%22%3A%22testpublisherid%22%7D%7D%2C%22device%22%3A%7B%22language%22%3A%22en%22%2C%22w%22%3A300%2C%22h%22%3A250%2C%22js%22%3A1%2C%22ua%22%3A%22Mozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010_13_6)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F71.0.3578.98%20Safari%2F537.36%22%7D%2C%22bidId%22%3A%22264052c6259d9f%22%7D

Here's the response:
`{"id": "3cc4012be43462", "seatbid": []}`

**Comment by mike-chowla** [comment]
When I went to check test coverage, I'm also seeing test failures.  This is somewhat curious because everything passed on CircleCI.  I test with your changes merged to a new branch off of the current master so perhaps something changed on master between now and when you submitted your PR.

SUMMARY:
✔ 3117 tests completed
ℹ 1 test skipped
✖ 3 tests failed

FAILED TESTS:
  timAdapterTests
    buildRequests
      ✖ bidRequest url
        HeadlessChrome 71.0.3578 (Mac OS X 10.13.6)
      Error: Invalid Chai property: exists. Did you mean "exist"?
          at Object.proxyGetter [as get] (webpack:///node_modules/chai/lib/chai/utils/proxify.js:75 <- test/test_index.js:3449:17)
          at Context.<anonymous> (webpack:///test/spec/modules/timBidAdapter_spec.js:63:33 <- test/test_index.js:119314:79)

      ✖ bidRequest data
        HeadlessChrome 71.0.3578 (Mac OS X 10.13.6)
      Error: Invalid Chai property: exists. Did you mean "exist"?
          at Object.proxyGetter [as get] (webpack:///node_modules/chai/lib/chai/utils/proxify.js:75 <- test/test_index.js:3449:17)
          at Context.<anonymous> (webpack:///test/spec/modules/timBidAdapter_spec.js:68:34 <- test/test_index.js:119318:80)

      ✖ bidRequest options
        HeadlessChrome 71.0.3578 (Mac OS X 10.13.6)
      Error: Invalid Chai property: exists. Did you mean "exist"?
          at Object.proxyGetter [as get] (webpack:///node_modules/chai/lib/chai/utils/proxify.js:75 <- test/test_index.js:3449:17)
          at Context.<anonymous> (webpack:///test/spec/modules/timBidAdapter_spec.js:73:37 <- test/test_index.js:119322:83)

TOTAL: 3 FAILED, 3117 SUCCESS

**Comment by borisjaskerovich** [comment]
Hi Mike,

the bidder does not  always return a bid. it is ok. we handle it in the interpret response function and return no bids from the adapter. there is also a test that checks this situation.
I ran the tests today and everything is working as expected.

**Comment by shlomisut** [comment]
Hey @mike-chowla 

the reason for the failed tests is that chai was updated to `4.2.0` on master branch (with a breaking API change of `exists` to `exist`). apparently as a preparation for prebid 2.0 release. 

The Q is - should we adapt our changes to that code or is there some 1.x maintenance branch ?  
for now we'll create _another_ PR with the updated code ontop of updated master 

As for the test bids. we'll fix that and notify you shortly.

Thanks
Shlomi

**Comment by shlomisut** [comment]
prebid 2.0 PR:  https://github.com/prebid/Prebid.js/pull/3497

**Comment by borisjaskerovich** [comment]
closing pr . moving to this:  prebid 2.0 PR: #3497

**Pull request closed without merging**
