### PR TITLE
AdHash Bid Adaptor : update to comply with Prebid 5.0

### PR DESCRIPTION
**Pull request by wyand-sp**
## Type of change
- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change
Adding the AdHash bidder adaptor for version 5.0.

- [x] official adapter submission

https://github.com/prebid/prebid.github.io/pull/3264

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@wyand-sp I don't see support for adomain here. Can you please add. That is now a requirement https://github.com/prebid/Prebid.js/issues/6650

**Comment by wyand-sp** [comment]
@ChrisHuie I did not see our bidder listed in #6650 so I thought it does not concern us. I will take a look.

**Comment by wyand-sp** [comment]
@ChrisHuie I have addressed the issue you pointed out. Please take a look. Thanks.

**Comment by ChrisHuie** [comment]
@wyand-sp looks like there are a few errors

**Comment by wyand-sp** [comment]
@ChrisHuie apologies about that. The error was from Chai - it said:
```
expected [ 'adhash.org' ] to equal [ 'adhash.org' ]
```
I was supposed to use .to.eql instead of .to.equal which does deep equal check for arrays.
Should be fine now.

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
