### PR TITLE
Quantum Advertising Adapter

### PR DESCRIPTION
**Pull request by sami-elasticad**
## Type of change
- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Initial push for Quantum Advertising Bid Adapter.

- test parameters for validating bids
# Sample Ad Unit: For Publishers
```
var adUnits = [{
          code: 'quantum-adUnit-id-1',
          sizes: [[300, 250]],
          bids: [{
              bidder: 'quantum',
              params: {
                placementId: 21546, //quantum adUnit id
                bannerFormat:'true' 
              }      
            }]
        }];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
sami@elasticad.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by mike-chowla** [comment]
There's some commented out code (lines 68 and 74 for example) that should be removed

**Comment by mike-chowla** [comment]
Code coverage is well below 80%:
screen shot 2018-01-30 at 6 00 15 pm

**Comment by mike-chowla** [comment]
There's a lot of code in the adapter for native but it the adapter doesn't declare native is a supported media type.  If native support is not ready in the adapter, the native code should not be included in the pull request.

**Comment by bretg** [comment]
@sami-elasticad - please note the review comments

**Comment by mike-chowla** [comment]
@sami-elasticad  It's good that you've added tests for native and test coverage is now > 80%.   But I'm still perplexed as to why there's code to render native but supportedMediaTypes doesn't declare native so the adapter can't actually be used with native.

**Comment by sami-elasticad** [comment]
Hi. I added supportedMediaTypes, it was something i missed. Please review changes. Thank you.

**Comment by sami-elasticad** [comment]
Yet I haven't been able to make a functional test for rendering the native bid. I tried every step from http://prebid.org/dev-docs/show-native-ads.html#how-native-ads-work but i didn't managed to make it working. Can you provide a functional example where a native ad is rendered with prebid.js 1.3+. Thank you.

**Comment by mike-chowla** [comment]
Here's the test page I use.  It's the example from Prebid.org with minor updates for 1.x
[pbjs_native.html.zip](https://github.com/prebid/Prebid.js/files/1740833/pbjs_native.html.zip)

**Comment by sami-elasticad** [comment]
Thank you for the test page. I tested and fixed some problems with assets. It worked on my side. Waiting for your reviews.

**Comment by mike-chowla** [comment]
You should update your docs to include the  bannerFormat parameter but otherwise looks good

**Comment by sami-elasticad** [comment]
We renounced to bannerFormat param. It works without it, we use mediaTypes only. Thank you.

**Pull request merged**
