### PR TITLE
Brightcom Bid adapter: add support for uspConsent, coppa, schain, userIdAsEids, userId

### PR DESCRIPTION
**Pull request by prBigBrother**
## Type of change

- [x] Feature

## Description of change
Add support for uspConsent, coppa, schain, userIdAsEids, userId

## Contact
[alexandruc@brightcom.com](mailto:alexandruc@brightcom.com)

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@prBigBrother can you please add unit test coverage for this pr?

**Comment by prBigBrother** [comment]
@ChrisHuie thanks for noticing about tests! 

tests are added

**Comment by prBigBrother** [comment]
Hi @ChrisHuie! sorry to bother you, would it be possible to receive an update on the pul request's current status?

**Comment by alexs-bc** [comment]
@ChrisHuie can you please advice on this pipeline error (Could not find a usable config.yml, you may have revoked the CircleCI OAuth app)?

**Comment by ChrisHuie** [comment]
@alexs-bc @prBigBrother haven't been able to fix the circleci issue. I will run this through our integration tests today to verify. Can you guys document these updates to your adapter in our docs repo please, then this should be good to go -> https://github.com/prebid/prebid.github.io

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
