### PR TITLE
Smaato bid adapter: adpod support added 

### PR DESCRIPTION
**Pull request by Enigo**
## Type of change

- [x] Feature

## Description of change
Adding OTT aka adpodding support for Smaato adapter.
Similar change will be done on prebid server side as well.

- contact email of the adapter’s maintainer: prebid@smaato.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:
- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
--> https://github.com/prebid/prebid.github.io/pull/3062

### CODE REVIEW

**Review by Fawke — APPROVED** [review]
LGTM

**Comment by Fawke** [comment]
Hi @Enigo, Can you please sync with master, we merged https://github.com/prebid/Prebid.js/pull/7104 to fix some failing circle-ci tests. Thank you.

**Comment by Enigo** [comment]
hey @Fawke, yep, sure, just rebased from the latest master

**Comment by Enigo** [comment]
and it is failing still :(

**Pull request merged**
