### PR TITLE
mgid adapter: native support, minor changes

### PR DESCRIPTION
**Pull request by Gaudeamus**
## Type of change

- [x] Feature
- [x] Refactoring (no functional changes, no api changes)

## Description of change

native support added, added currency and bidfloor optional parameters

- test parameters for validating bids
```
var adUnits = [{
  code: 'div-prebid',
  mediaTypes: {
    native: {
        image: {
            sendId: true,
            required: true,
            sizes: [80, 80]
        },
        clickUrl: {
            sendId: true,
            required: false
        },
        title: {
            required: true,
            len: 80
        },
        sponsored: {
            required: false
        }
    }
  },
  // Replace this object to test a new Adapter!
  bids: [{
    bidder: 'mgid',
    params : {
        accountId : "233", //test accountId, please replace after test
        placementId : "350971" // 300x250 test placementId, please replace after test
    }
  }]
}];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
prebid@mgid.com

- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/1283

### CODE REVIEW

**Comment by mkendall07** [comment]
This pull request **introduces 1 alert** when merging a24a528b5365bdb684332a1692cf97de7e1ccc57 into 253cbf4de5d575a70a288b3249d7bf4f1f7ddfc6 - [view on LGTM.com](https://lgtm.com/projects/g/prebid/Prebid.js/rev/pr-fc54013eb12347382025e734d05f7016d0776b2a)

**new alerts:**

* 1 for Unneeded defensive code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Gaudeamus** [comment]
Hello, @mkendall07, please revise

**Comment by Gaudeamus** [comment]
Hi @sumit116, please review the last commit

**Comment by Gaudeamus** [comment]
Thanx @sumit116, could you please remove "needs unit tests" label

**Pull request merged**
