### PR TITLE
Smartadserver Bid Adapter: add support for multiple media types

### PR DESCRIPTION
**Pull request by lowendavid**
## Type of change
- [x] Feature
- [x] Other

## Description of change

Two main changes are implemented:

1 - Feature : Handling of multiple media types in adUnit configuration, specifically banner & video.
2 - Other : Completely prevent csync when no csync url instead of trying to sync with null or undefined. This is cleaner.

### CODE REVIEW

**Comment by mkendall07** [comment]
@lowendavid looks like you have a conflict to resolve.

**Comment by lowendavid** [comment]
@mkendall07 thanks for the heads up, i had forgotten to commit the conflict resolution. I will make sure its all green today

**Comment by lowendavid** [comment]
@ChrisHuie It's all green now 😁

**Comment by ChrisHuie** [comment]
@lowendavid do you want to add an example or document the multiple media support in the .md file?

**Comment by lowendavid** [comment]
@ChrisHuie I need to check, I'll get back to you as soon as i have the answer (hopefully tomorrow)

**Comment by ChrisHuie** [comment]
@lowendavid following up on this pr with regards to updating the markdown file?

**Comment by lowendavid** [comment]
@ChrisHuie The .md has been updated, sorry for the slight delay it took me longer than expected to get the necessary setup on my side.

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
