### PR TITLE
Add CLICKFORCE Bid Adapter (updated to new spec)

### PR DESCRIPTION
**Pull request by MIGOdanis**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
 New bidder adapter from clickforce
- test parameters for validating bids
```
{
  bidder: "clickforce",
  params: {
      zone: "6682",
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
danis@clickforce.com.tw
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by harpere** [comment]
@MIGOdanis - this adapter does not follow the Prebid 1.0 spec.  Please see http://prebid.org/dev-docs/bidder-adaptor.html "How to Add a New Bidder Adapter"

**Comment by MIGOdanis** [comment]
@harpere  we already change the adapter to new version. please check the changes request. thank you

**Comment by MIGOdanis** [comment]
@mkendall07   HI , We have submitted doc at https://github.com/prebid/prebid.github.io/pull/557 , Please tell me what documents need to be submitted?  thank you

**Comment by MIGOdanis** [comment]
@mkendall07  Thank you for the help!

**Pull request merged**
