### PR TITLE
Prebid Server Bid Adapter: Openx parameters added to the host company configuration file

### PR DESCRIPTION
**Pull request by deivydas**
## Type of change

- [x] Feature

## Description of change

OpenX is added to the default PBS vendors list

## Other information

@kenan-gillet could you please review this PR ?

### CODE REVIEW

**Comment by patmmccann** [comment]
Is this Java or go?
 Is this a free service? 

Perhaps all these can be answered with a docs pr to https://prebid.org/product-suite/managed-services/ ?

**Comment by patmmccann** [comment]
Just awaiting clarification on these two questions,  perhaps it makes sense to add a comment to each one saying if they are Java or go.

**Comment by deivydas** [comment]
Hey @patmmccann,
sorry for such a late response.
Our prebid server is using the open source prebid server written in Go.
Also regarding pricing I would recommend contacting our Business Development team by filling this form:
https://www.openx.com/prebid/#form

Please let me know if there are more questions.
Thanks in advance,
Deivydas

**Comment by patmmccann** [comment]
@bretg what is the best place to document the map of host company to pbs platform language?

**Review by patmmccann — APPROVED** [review]

**Review by bretg — APPROVED** [review]
FWIW, 1000 seems awfully long for a server-side timeout, but pubs can override this.

**Review by kenan-gillet — APPROVED** [review]

**Comment by ChrisHuie** [comment]
Yeah. Rubicon went with 500ms but appnexus also went with 1000ms in this file

**Pull request merged**
