### PR TITLE
Rvr 2369 add trackable add ad units event

### PR DESCRIPTION
**Pull request by AlessandroDG**
## Type of change
- [x] Feature

## Description of change

Add ADD_AD_UNITS to trackable events.

## Other information
Requested by @jsnellbaker in #3683

### CODE REVIEW

**Comment by jsnellbaker** [comment]
Hi @AlessandroDG 

Thanks for splitting out this change from the other PR.  While I was looking over the overall logic, I noticed that there is another event that's not handled by the `AnalyticsAdapter`; the `REQUEST_BIDS` event.  

Since we're fixing one, can you update the PR to also fix the other?

**Comment by AlessandroDG** [comment]
@jsnellbaker I can do that. I will push the changes soon.

**Comment by AlessandroDG** [comment]
@jsnellbaker I added `REQUEST_BIDS` to the trackable events.
There is the usual issue with circleci running on my company's instance, tests should pass if executed locally or on your circleci instance.

**Comment by AlessandroDG** [comment]
@jsnellbaker you're welcome!

**Pull request merged**
