### PR TITLE
ViewdeosDX outstream support

### PR DESCRIPTION
**Pull request by GeneGenie**
## Type of change
- [x] Feature

## Description of change
Add uspConsent support
Allow configuring outstream player from params of bidder

```
{
...
  params: {
    aid:331133,
    outstream: {
      show_controls: 'show'
    }
  }
}
```

# Docs 
https://github.com/prebid/prebid.github.io/pull/1732

### CODE REVIEW

**Comment by mike-chowla** [comment]
I'm not receiving a bid back with the outstream test parameters.

Here's the request that's going out:
`https://hb.sync.viewdeos.com/auction/?domain=http%3A%2F%2Ftest.chowla.com%3A9999%2FintegrationExamples%2Fgpt%2Fhello_world_outstream.html%3Fpbjs_debug%3Dtrue&callbackId=21b53e3e98543c&aid=331133&ad_type=video&sizes=640x480&`

**Comment by GeneGenie** [comment]
@mike-chowla  what is your geo ?

**Comment by GeneGenie** [comment]
@mike-chowla I need some help here: don't know how to fix LGTM analysis problem

**Comment by GeneGenie** [comment]
@bretg  Good evening, the need in this functionality escalates quickly. Can you recheck it since LGTM passed. 
@mike-chowla I've also changed endpoint to geobalancer to exclude timeout issue on test bids.

**Comment by mike-chowla** [comment]
@GeneGenie I tried it again this morning I'm still not able to get an outstream bid back

**Comment by GeneGenie** [comment]
> @GeneGenie I tried it again this morning I'm still not able to get an outstream bid back

i've changed endpoint to support geo balancing: so the test link should be 
https://ghb.sync.viewdeos.com/auction/?domain=http%3A%2F%2Ftest.chowla.com%3A9999%2FintegrationExamples%2Fgpt%2Fhello_world_outstream.html%3Fpbjs_debug%3Dtrue&callbackId=21b53e3e98543c&aid=331133&ad_type=video&sizes=640x480

**Comment by mike-chowla** [comment]
Your outstream URL is failing to load due to an expired certificate:
https://player.sync.viewdeos.com/outstream-unit/2.01/outstream.min.js

Screen Shot 2020-01-31 at 4 21 59 PM

Screen Shot 2020-01-31 at 4 22 42 PM

**Comment by GeneGenie** [comment]
@mike-chowla fixed

**Pull request merged**
