### PR TITLE
LuponMedia Bid Adapter: user sync endpoint updated

### PR DESCRIPTION
**Pull request by adxpremium**
## Type of change
- [ x] Code style update (formatting, local variables)

### CODE REVIEW

**Comment by musikele** [comment]
Hi @adxpremium , code coverage is under 80%, that is the required minimum to accept the MR. 
In order to see code coverage, you can run: 

```
npx gulp test-coverage
```

followed by 

    npx gulp view-coverage

**Comment by adxpremium** [comment]
> Hi @adxpremium , code coverage is at 57.22%, that is below 80%, the required minimum to accept this PR. In order to see code coverage, you can run:
> 
> ```
> npx gulp test-coverage
> ```
> 
> followed by
> 
> ```
> npx gulp view-coverage
> ```

Hi, we are not sure what code coverage is in this case and what needs to be done on our side to make PR pass the minimum requirements? Could you please explain?

**Comment by musikele** [comment]
@adxpremium 

> Hi, we are not sure what code coverage is in this case and what needs to be done on our side to make PR pass the minimum requirements? Could you please explain? 

A Prebid rule is that everything that gets merged must have at least 80% code coverage + at least one review.

When we execute unit tests with `npx gulp test-coverage`, we check that tests are covering at least 80% of total lines of code. If you launch the two commands I wrote above, in your branch, you will be presented with a page with all the code coverage of all modules. 

image

**Comment by adxpremium** [comment]
@patmmccann digitrust is now removed

**Comment by patmmccann** [comment]
Tyvm

**Comment by musikele** [comment]
hi there. I still see tests missing for the following functions: 

- masSizeOrdering 
- setGdprAndPrivacy
- setUserId
- setSiteAndUserData
- setAdserverOrg
- setLiveIntent
- setIdentityLink
- setPubcommon
- mapSizes
- parseSizes

Coverage is still stuck at 56.75% , cannot merge.

**Comment by patmmccann** [comment]
@adxpremium please see https://github.com/prebid/Prebid.js/pull/8372 . Is your use of getLegacyFPD working? It appears not

**Comment by patmmccann** [comment]
@adxpremium review of your adapter cannot proceed until you improve test coverage.

**Pull request closed without merging**
