### PR TITLE
Criteo bid adapter: Bump fastbid version

### PR DESCRIPTION
**Pull request by leonardlabat**
## Type of change
- [X] Bugfix

## Description of change
Bump fast bid version to ensure the latest fix is available

### CODE REVIEW

**Comment by DemekaParis** [comment]
https://github.com/prebid/Prebid.js/pull/10456#pullrequestreview-1622531367

**Comment by allanjun** [comment]
hi @DemekaParis 

Thanks for raising this, you will want to follow progress on https://github.com/prebid/Prebid.js/issues/10653 that will address your very concern around loading external files. This feature is legacy design and allowed Criteo to run some features not available in Prebid.js by the time (Criteo ID Module, timeout stats and other minor things).

Criteo team is confident and committed to address this with Prebid 9.0 or even before. Please also notice that today it is already possible to optout from this feature.

Allan

**Comment by patmmccann** [comment]
We're not bumping fastbid any longer

**Comment by patmmccann** [comment]
@DemekaParis see also https://github.com/prebid/Prebid.js/issues/4031#issuecomment-516015357 and https://github.com/prebid/Prebid.js/issues/5804 as useful background.

**Comment by patmmccann** [comment]
Reopened as the Fastbid changes are minor bug fixes that I reviewed, awaiting board approval before this merge.

**Comment by DemekaParis** [comment]
I believe making the repository at https://github.com/Prebid-org/prebid-js-external-js-criteo/tree/master/dist public would be mutually beneficial at this time, especially until the anticipated PR for prebid 9 is implemented. If there are no proprietary elements involved, I see no issue with this approach. Alternatively, consider presenting it as an opt-in feature for publishers, as I am confident you can effectively communicate the advantages directly to them.

I would like to express my concern about the current opt-out mechanism, as it seems impractical. Referring to https://github.com/prebid/Prebid.js/blob/61d299e6d4c28c5096967d05f2140d70db7a3e54/modules/criteoBidAdapter.js#L27, it appears that opting out is not straightforward when downloading from the prebid.org website. Users have to modify the source code to "opt-out," as indicated below:
```
  If you don't want to use the FastBid adapter feature, you can lighten criteoBidAdapter size by :
  1. commenting the tryGetCriteoFastBid function inner content (see ref#1)
  2. removing the line 'verify' function import line (see ref#2)`
```

Also this opt-out/opt-in should be written in https://docs.prebid.org/dev-docs/bidders/criteo.html  where there is no mention of opt-out.


I appreciate your consideration of these points and believe addressing them would contribute to a smoother user experience.

**Comment by allanjun** [comment]
hi @DemekaParis these instructions are build-time instructions. A runtime optout is also possible, it is explained on our integration guides but we will also document on https://docs.prebid.org/dev-docs/bidders/criteo.html 👍 

```
pbjs.que.push(function () {
  pbjs.setConfig({
    'criteo': {
      fastBidVersion: 'none',
    }
  });
});
```

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
Ad discussed with the criteo team, this bug fix is the final bump

**Pull request merged**
