### PR TITLE
Add Support to Manually pass PageUrl

### PR DESCRIPTION
**Pull request by PubMatic-OpenWrap**
Adding Support for Manually passing Page Url. This would be helpful in postbid setup inside safeframes.

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: 'pubmatic',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: UOEDev@pubmatic.com
- [ ] official adapter submission

### CODE REVIEW

**Comment by mkendall07** [comment]
@PubMatic-OpenWrap 
Is this just page URL (location.href?) Would you be able to use something like this? https://github.com/prebid/Prebid.js/issues/1882

**Comment by mike-chowla** [comment]
#1882 would work. for this

**Comment by jsnellbaker** [comment]
@PubMatic-OpenWrap would you be able to update this PR to use the config.getConfig call structure that was suggested in the above referenced issue?  We believe this would be a better implementation for this type of request.  Thanks.

**Comment by mkendall07** [comment]
closing this in favor of https://github.com/prebid/Prebid.js/pull/2011

**Pull request closed without merging**
