### PR TITLE
Windtalker

### PR DESCRIPTION
**Pull request by degroat**
## Type of change
- [ X] New bidder adapter  

## Description of change
Prebid adapter for Windtalker.

- test parameters for validating bids
```
{
  bidder: 'windtalker',
  params: {
           "pubId":"187046"
           ,"siteId":"10"
           ,"size":"300x250"
           ,"placementId":"456"
  }
}
```

- contact email of the adapter’s maintainer: corbin@windtalker.io
- [X ] official adapter submission

### CODE REVIEW

**Comment by Fawke** [comment]
hi @degroat,

I see 45 files changed which is making it harder for me to review your submission. Can sync your code once with the master branch and also resolve the merge conflicts?

**Comment by degroat** [comment]
Things got ugly when I re-merged with the upstream master.   No idea how there were merge conflicts when all I did was add three new files.    So I just created a new branch named 'windtalker2' that is based on the current master w/ the new files.  Is there an easy way to update the pull request to use that?

**Comment by bretg** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/1788

**Comment by Fawke** [comment]
> Things got ugly when I re-merged with the upstream master. No idea how there were merge conflicts when all I did was add three new files. So I just created a new branch named 'windtalker2' that is based on the current master w/ the new files. Is there an easy way to update the pull request to use that?

I suggest you close this PR and create a new one, that'll be way easier. You can directly request my review on that new PR you open and I'll check it out. Make sure you include your Docs PR link as well in the new PR.

**Pull request closed without merging**
