### PR TITLE
Conversant Bid Adapter: add getUserSync

### PR DESCRIPTION
**Pull request by johnwier**
## Type of change
- [X ] Feature

## Description of change

Update the Conversant adapter to to use getUserSyncs to send sync pixels

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@johnwier it looks like our circle-ci tests didn't kick of on this pr. Is it possible to give me access to edit this pr to kick off our testing?

**Comment by johnwier** [comment]
How would I do that?

**Comment by ChrisHuie** [comment]
@johnwier there should be a checkbox on the side of the screen you can select that says something to the effect of "let maintainers edit" pull request. However, I can't seem to find it at the moment. So inviting me to the branch is probably the easiest. It is just under settings and then manage access.

**Comment by patmmccann** [comment]
unfollowing your own fork in circleci and submitting any commit tends to work as well

**Comment by johnwier** [comment]
Ok.  Sorry I dont have access rights on our fork to do that

**Comment by ChrisHuie** [comment]
@johnwier I will just submit a new pr for this from my account to get this through tests and moving

**Review by ChrisHuie — APPROVED** [review]

**Pull request merged**
