### PR TITLE
sspBC adapter: update to v4.6 (notifications, user sync)

### PR DESCRIPTION
**Pull request by wojciech-bialy-wpm**
## Type of change

- [x] Feature

## Description of change

Update sspBC adapter to v4.6:
- add notification endpoint
- send bidWon and onTimeout notifications
- send CMP version to user sync endpoint

### CODE REVIEW

**Comment by robertrmartinez** [comment]
please add unit tests @wojciech-bialy-wpm

**Comment by osazos** [comment]
Hi  @wojciech-bialy-wpm,

In order to approve your PR, could you please 
- add tests to cover onBidWon and onTimeout events, without these tests, your test-coverage is under 80%.
- fix your CI errors (Lint)
- fix your failing test : ✖ should provide correct url, if frame sync is allowed

In your `onTimeout`, `onBidWon` functions, you expect `bid.params` is an array, but in `isBidRequestValid` it is an object. shouldn't be both the same? 
If it is what you expect, you should add in your condition: `bid.params && bid.params.length ? …  : ''` to avoid error if a params array is empty.

**Comment by wojciech-bialy-wpm** [comment]
Sorry for the delay.

Tests updated:
- getUserSyncs test fixed (failed when adapter started appending tcf version to the url)
- onBidWon test added
- onTimeout test added

In the last two cases, while I can't get sinon to work with Prebid.js ajax module (similar case as in https://github.com/prebid/Prebid.js/issues/3842) methods now check whether notification payload is correctly constructed.

**Comment by osazos** [comment]
@wojciech-bialy-wpm, where is your updated test file please? I can't see it in your the files changed of this PR.

**Comment by wojciech-bialy-wpm** [comment]
@osazos Oh, I see the last commit (with changes to test/spec/modules/sspBCAdapter_spec.js) did not go through. Updating now.

**Review by osazos — APPROVED** [review]
LGTM

**Pull request merged**
