### PR TITLE
PremiumAds Bid Adapter: initial release

### PR DESCRIPTION
**Pull request by alexgmax**
## Type of change
- [x ] New bidder adapter  
- contact email of the adapter’s maintainer: adops@premiumads.net
- test parameters for validating bids:
```
   {
                        bidder: 'premiumads',
                        params: {
                            adUnitId: 1123568438,
                            floor: 0.3
                        }
   }
```

## Other information
Dev docs pull request: https://github.com/prebid/prebid.github.io/pull/4389

### CODE REVIEW

**Comment by alexgmax** [comment]
Hi @ChrisHuie, 
Thank you for your review, please let me know what else I need to update.

Regards,
Alex.

**Comment by ChrisHuie** [comment]
> Hi @ChrisHuie, Thank you for your review, please let me know what else I need to update.
> 
> Regards, Alex.

Can you pull in recent commits on master. There seem to be failing tests from other adapters in this pr.

**Comment by alexgmax** [comment]
> > Hi @ChrisHuie, Thank you for your review, please let me know what else I need to update.
> > Regards, Alex.
> 
> Can you pull in recent commits on master. There seem to be failing tests from other adapters in this pr.

I updated, but it still seems to have an error with SmartyadsAdapter, how should I resolve it?

**Review by Fawke — CHANGES_REQUESTED** [review]
Hi @alexgmax,

Can you please fix unit tests? I see about 122 unit tests failing on your branch. Some of the failures are from your changes, some are from other adapters. 

I tried pulling in master, but it didn't help. Can you please have a look and fix them? Try running `gulp test` to see the tests run.

**Comment by alexgmax** [comment]
Hi @Fawke 
I have committed the latest code and passed all unit tests.

**Comment by Fawke** [comment]
@alexgmax Yes, I see all the tests pass now, thanks for fixing them. You'll need to improve your test coverage though. After you fixed your tests, I was able to run `gulp test-coverage` followed by `gulp view-coverage`. The current coverage is 56%, please try to make it at least 80%.

**Comment by patmmccann** [comment]
Closing as stale

**Pull request closed without merging**
