### PR TITLE
remove duplicate line in AppNexus adapter

### PR DESCRIPTION
**Pull request by benjaminclot**
+ added reserve price parameter
- removed duplicate `jptCall = utils.tryAppendQueryString(jptCall, 'code', inventoryCode);`

### CODE REVIEW

**Comment by mkendall07** [comment]
@benjaminclot 
You actually don't need this code to be added. You can already add `reserve` into the AppNexus bidder params and it is automatically added to the query. Any key/value will work: https://github.com/benjaminclot/Prebid.js/blob/4e0e46c9cfc035e46e7d10a66b48ca8b212b7f37/src/adapters/appnexus.js#L117

**Comment by benjaminclot** [comment]
My bad, I didn't see this part.
But the duplicate line is still valid I guess :)

**Comment by mkendall07** [comment]
Yep. If you remove the other code I'll merge.

**Comment by benjaminclot** [comment]
Done.

**Pull request merged**
