### PR TITLE
Yieldmo Bid Adapter Update

### PR DESCRIPTION
**Pull request by merrdy**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Updating Yieldmo Prebid Adapter to meet Prebid 1.0 specs

- test parameters for validating bids
```
{
       code: 'div-gpt-ad-1460505748561-0', 
       sizes: [[300, 250], [300,600]],
       bids: [{
         bidder: 'yieldmo',
         params: {
           placementId: '1779781193098233305' // string with at most 19 characters (may include numbers only) 
         }
       }]
   }
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email: melody@yieldmo.com
- [x] official adapter submission

### CODE REVIEW

**Comment by merrdy** [comment]
Hey @jsnellbaker,

The issue was that the id in the placementId field is currently not in production, so you were probably getting a 204 when pinging our server. If you comment out that id, you should be able to get an ad. Is that alright? Otherwise I can ask our ad servers to send a response for that placementId. Thanks!

**Comment by jsnellbaker** [comment]
Hey @merrdy,

I did try to comment out the `placementId` (and the params object afterwards), but neither of these seemed to help.  I was still receiving the 204 response from the server.  Can you try to open up/publish the placement?  Thanks!

**Comment by merrdy** [comment]
@jsnellbaker 

Okay, I'll talk to ad serving. The other issue might be that you have to be emulating mobile in order to get an ad. So you might have to refresh after switching to mobile view in order to get an ad.

**Comment by merrdy** [comment]
@jsnellbaker 

Okay, I've updated the docs and the description above such that the placementId given should result in an ad. Don't forget to emulate mobile mode when you're trying to get the ad. We only serve on mobile, so an ad request from desktop will get a 204. Thanks for being patient with me about this!

**Comment by jsnellbaker** [comment]
@merrdy 

Thanks for submitting the changes and helping to enable the ad unit for testing.  I verified the delivery is working when I'm emulating and not when I'm using my desktop (as you noted).

LGTM

**Comment by merrdy** [comment]
@jsnellbaker 

Okay, thanks!

**Comment by jaiminpanchal27** [comment]
Need docs PR to merge. Please submit a PR to the [docs repo](https://github.com/prebid/prebid.github.io) to add a file for your adapter to the [bidders directory](https://github.com/prebid/prebid.github.io/tree/master/dev-docs/bidders) so your adapter's params will appear on the [bidders page](http://prebid.org/dev-docs/bidders.html). Thank you for contributing

**Comment by merrdy** [comment]
@jaiminpanchal27 

We've reopened our pr to update the docs here: https://github.com/prebid/prebid.github.io/pull/469#issuecomment-348238019.

Thanks!

**Pull request merged**
