### PR TITLE
fledgeForGpt: provide `bidfloor` in auction signals

### PR DESCRIPTION
**Pull request by dgirardi**
## Type of change

- [x] Feature

## Description of change

This adds two auction signals to fledge: `prebid.bidfloor` and `prebid.bidfloorcur`.

The `bidfloor` value is either the highest CPM that Prebid got for the slot, or (if there were no bids) the minimum required floor across all requests for the slot.

## Other information

Closes https://github.com/prebid/Prebid.js/issues/10139

### CODE REVIEW

**Comment by laurb9** [comment]
I did a small "live" test -  made a bundle with fledgeForGpt and openxBidAdapter, faked an openx server response to inject some auctionSignals and intercepted `runAdAuction` in the page to print out the arguments. I can see the expected merged `auctionSignals` in the prebid debug log as well as in the `runAdAuction` configuration passed by GPT:

Screenshot 2023-09-05 at 6 23 24 PM

**Review by Fawke — APPROVED** [review]
LGTM

**Review by patmmccann — APPROVED** [review]

**Review by patmmccann — APPROVED** [review]
Taking @laurb9 's review as second, thanks!

**Comment by pm-nitin-nimbalkar** [comment]
@patmmccann @Fawke @laurb9 

Hi Guys, Am just confused with the sentence written in description section "or (if there were no bids) the minimum required floor across all requests for the slot."

If there is no contextual bids for particular fledge slot, my assumption is that bid floor value should be 0. So what is "the minimum required floor across all requests for the slot." How this is calculated. Bit confused on this.

Can you elaborate it more on this with examples ?

TIA,
Nitin

**Comment by pm-harshad-mane** [comment]
@pm-nitin-nimbalkar , the publisher sets a floor value that is passed to all bidders in the contextual-request and bidders are required to bid higher than the floor value. if partners do not return contextual bids then in this case the floor value set by the publisher will be passed in PA.

**Pull request merged**
