### PR TITLE
Sovrn adapter - Allow using the same tagId for multiple slots

### PR DESCRIPTION
**Pull request by dbabaioff**

### CODE REVIEW

**Comment by pdramos1** [comment]
Hey I'm having a look at this. We think there is some merit to this but need to dot some i's and cross some t's.

**Comment by pdramos1** [comment]
Can you update from master and re submit the pull request.

**Comment by mkendall07** [comment]
@dbabaioff 
Can you rebase this PR so we can merge it? Thanks

**Comment by mkendall07** [comment]
Duplicate of https://github.com/prebid/Prebid.js/pull/244

**Pull request closed without merging**
