### PR TITLE
ID Library feat: turn off fullscan by default

### PR DESCRIPTION
**Pull request by iamnewton**
## Type of change

- [x] Feature
- [x] Code style update (formatting, local variables)

## Description of change

Turning off the ID library modules `fullscan` feature by default.

### CODE REVIEW

**Comment by jdwieland8282** [comment]
We have decided to disable full body scans by default, we will compile some documentation about the risks of enabling this feature in coming weeks. Thanks @iamnewton

**Comment by smenzer** [comment]
please make sure to remove the `package-lock.json` file from the PR before you mark it ready for review

**Comment by iamnewton** [comment]
@smenzer done.  Anything else on there to be aware of?  The PR is only in draft as I'm waiting to add some more documentation.

**Review by SKOCHERI — APPROVED** [review]

**Review by smenzer — APPROVED** [review]
LGTM

**Pull request merged**
