### PR TITLE
Ats analytics additional analytics data

### PR DESCRIPTION
**Pull request by mamatic**
## Type of change

- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)

## Description of change
- Added two additional properties(data) in analytics request, adapter_version, envelope_source
- Change the way of detecting user browser in atsAnalyticsAdapter
- Added preflight request with sampling rate, that we can handle who and with what sampling rate can fire actual request on analytics
- Remove host (analytics url) from configuration

### CODE REVIEW

**Comment by mamatic** [comment]
Hi @Fawke,
can you do the review or assign someone to review pull request? Tnx

**Comment by GLStephen** [comment]
@mamatic take a look at the LGTM bot and fix that issue, I'm also getting errors when testing directly. Can you take a look and ping me when fixed?

```
SUMMARY:                                                                                                                                                                                                                   ✔ 4 tests completed                                                                                                                                                                                                        ✖ 1 test failed                                                                                                                                                                                                                                                                                                                                                                                                                                       FAILED TESTS:                                                                                                                                                                                                                ats analytics adapter                                                                                                                                                                                                        track                                                                                                                                                                                                                        ✖ builds and sends request and response data                                                                                                                                                                                 HeadlessChrome 86.0.4240 (Linux 0.0.0)                                                                                                                                                                                   AssertionError: expected 0 to equal 1                                                                                                                                                                                                                                                                                                                                                                                                                 + expected - actual                                                                                                                                                                                                                                                                                                                                                                                                                                   -0                                                                                                                                                                                                                         +1                                                                                                                                                                                                                                                                                                                                                                                                                                                  at Context.<anonymous> (webpack:///test/spec/modules/atsAnalyticsAdapter_spec.js:151:34 <- test/spec/modules/atsAnalyticsAdapter_spec.js:7273:80)

**Comment by NemanjaRajkovic9** [comment]
@GLStephen Hello there.
Can you please point me to the LGTM issue?
Also, the tests are not failing when we start them.
Can you please tell me what do you mean by testing directly? Do you use "gulp test" or something else?

**Comment by GLStephen** [comment]
> This pull request **introduces 1 alert** when merging [44341df](https://github.com/prebid/Prebid.js/commit/44341df25bf5ffea110483b137c5d45655d7c94c) into [2f05506](https://github.com/prebid/Prebid.js/commit/2f055063ccca4d08c2cb5e8fe13abadd8346ba4c) - [view on LGTM.com](https://lgtm.com/projects/g/prebid/Prebid.js/rev/pr-4216ea5549245be79d26c60f3a9e748f77ee63a6)
> 
> **new alerts:**
> 
> * 1 for Useless conditional

**Comment by NemanjaRajkovic9** [comment]
I saw that but when i checked it out, i saw a message "This use of variable 'samplingRateCookie' always evaluates to true." on line 325, which is no longer there. 

And i see that LGTM analysis is successful, all checks are passed. 
Am I maybe looking at the wrong place? 
Can you take a look at the bottom of the PR?

**Comment by mamatic** [comment]
Hi @GLStephen ,
can you please review this pull request?

Regarding alert it was fixed in this commit:
- ATS-analytics - fix LGTM and add console log to atsAnalyticsAdapter test     ccaba77
https://github.com/prebid/Prebid.js/pull/6145/commits/ccaba77b89bab41c647123c680b9304565dc1045

Regarding test, all tests are passing, is there some other issues that needs to be fixed?

**Comment by ian-lr** [comment]
@GLStephen HNY! Could you take a pass at this when you have a moment? Thank you!

**Comment by smenzer** [comment]
@GLStephen can you please review this when you get a chance? if you won't have time, ping me in slack and i'll reassign. thanks!

**Comment by ian-lr** [comment]
Hi @Fawke! Could you take a look when you have a moment? Thanks

**Review by Fawke — APPROVED** [review]
LGTM

**Pull request merged**
