### PR TITLE
Submit NAF Digital Bidder Adapter

### PR DESCRIPTION
**Pull request by vyatsun**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: 'nafdigital',
  params: {
    publisherId: 2141020
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: vyatsun@gmail.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- [prebid/prebid.github.io#1262](https://github.com/prebid/prebid.github.io/pull/1262)

### CODE REVIEW

**Comment by vyatsun** [comment]
Hi @sumit116 
Thanks for your response. Can you please provide the request payload as well as the country you're sending the request from, so that I can create a targeting for you on the server?

**Comment by sumit116** [comment]
> Hi @sumit116
> Thanks for your response. Can you please provide the request payload as well as the country you're sending the request from, so that I can create a targeting for you on the server?

**Comment by sumit116** [comment]
HI @vyatsun ,

Request Payload: `{"id":"3f1fdfb0737e75","imp":[{"id":"2ce3666274b969","banner":{"format":[{"w":300,"h":250},{"w":300,"h":600}],"ext":{"viewability":100}},"tagid":"div-gpt-ad-1460505748561-0","bidfloor":0.01}],"site":{"domain":"test.localhost:9999","page":"http://test.localhost:9999/integrationExamples/gpt/hello_world.html?pbjs_debug=true","publisher":{"id":2141020}},"device":{"devicetype":2,"w":1366,"h":768},"tmax":3000}`

Country: `India`

**Comment by vyatsun** [comment]
Thanks @sumit116
I've created a new targeting on the server. Could you try again? Hopefully it will work this time.

**Comment by sumit116** [comment]
Thanks @vyatsun, Yes its working now.

Tested the adaptor on hello_world page and all unit tests have passed. Test coverage of the adaptor is above 80%. The changes are working well against all parameters listed in https://github.com/prebid/Prebid.js/blob/master/PR_REVIEW.md, hence approving the PR.

**Pull request merged**
