### PR TITLE
Rise bid adapter - support multi seller end points

### PR DESCRIPTION
**Pull request by innay**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [X] Other

## Description of change
Support multi seller end points - new bidder param rtbDomain which controls the seller end point

### CODE REVIEW

**Review by Fawke — COMMENTED** [review]
Hi @innay,

Your change looks good. I think since you're adding a new bid param, `rtbDomain`, its better to update the docs.

**Comment by innay** [comment]
Hi @Fawke , Thanks for your review. Added the 'rtbDomain' to the docs

**Comment by Fawke** [comment]
Thanks @innay. Can you also create a PR for the public docs? Specifically this file - https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/rise.md.

**Comment by innay** [comment]
@Fawke https://github.com/prebid/prebid.github.io/pull/3949

**Review by Fawke — APPROVED** [review]

**Pull request merged**
