### PR TITLE
Update test unit to match new alias bidder count (Adkernel)

### PR DESCRIPTION
**Pull request by iskmerof**
## Type of change

- [X] Other

## Description of change
Update test unit for alias count

### CODE REVIEW

**Comment by aleksatr** [comment]
Hi @iskmerof , the test in question is failing, check circleci output, the number of aliases in spec.aliases seems to be 8, so I'm not sure where does this `9` come from?

**Comment by aleksatr** [comment]
@iskmerof , ok I see, it's coming from this PR `https://github.com/prebid/Prebid.js/pull/6055`, can you just merge these two into one PR? or just push this commit (`git cherry-pick e6fec67eadcc0c73394cf86dd8520ff5f60ed729`) to `iskmerof:patch-1` ?

**Comment by iskmerof** [comment]
@aleksatr Thank you. No problem, will either close or merge them. There's some difficulties with GH UI in doing multiple commits in one PR.

**Comment by aleksatr** [comment]
@iskmerof , I pushed this commit to https://github.com/prebid/Prebid.js/pull/6055 for you, I'll close this one now.

**Comment by iskmerof** [comment]
@aleksatr Thank you very much!

**Pull request closed without merging**
