### PR TITLE
Module - Size Mapping V2

### PR DESCRIPTION
**Pull request by Fawke**
## Type of change
- [X] Feature

## Description of change

Implementation of the new size mapping spec. Find details of the spec here.
https://github.com/prebid/Prebid.js/issues/4129#issuecomment-545003349

- In short, this spec introduces ad unit and bidder level `sizeConfig` for displaying responsive ads.
- Behaviour of Labels stays unchanged. You can declare them in `pbjs.requestBids`.

Please read the docs PR to understand how to setup Ad Units using the new sizeConfig.

To load and test the module in isolation, you can run this command.

`gulp serve --modules=sizeMappingV2,<insert bidder adapters you want to test>`

There is an example to test the module located at `integrationExamples/gpt/responsiveAds_sizeMappingV2.html`. You can modify the parameters and verify.

Link to docs PR: https://github.com/prebid/prebid.github.io/pull/1729

### CODE REVIEW

**Comment by Fawke** [comment]
@idettman LGTM error should be gone now, and reverted back changes to `pbjs_api_spec.js`.

**Comment by benjaminclot** [comment]
I tested this module locally (with a production setup) and the results are very good. Is there an intent to merge this with Prebid 2.x too?

**Comment by Fawke** [comment]
> I tested this module locally (with a production setup) and the results are very good. Is there an intent to merge this with Prebid 2.x too?

Thanks for checking it out @benjaminclot. AFIK, we will merge this with 2.0 as well.

**Comment by benjaminclot** [comment]
Is this still planned for merging? (I sure do hope so)

**Pull request merged**
