### PR TITLE
Nobid adapter: Added support for CCPA

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change

- [X] Bugfix
- [X] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
- Added support for CCPA to the Nobid Adapter
- Fixed issue when Ad unit code are integer
- Changed URL for user sync

- test parameters for validating bids
```
{
  bidder: 'nobid',
  params: {
    siteId:2
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by redaguermas** [comment]
I am unable to see the CI error. I am getting a message like this:
image
Note that I ran "gulp test" locally and it works without any errors.

**Comment by bretg** [comment]
docs PR https://github.com/prebid/prebid.github.io/pull/1725

**Comment by redaguermas** [comment]
I was able to get to the CI today. It looks like the problem is in the RealVu Analytics Adapter. Can you please help?
image

**Comment by redaguermas** [comment]
Hello,
Is there someone to look into this issue please. We are blocked because of this and we need to be compliant with CCPA. This is urgent.

**Comment by GLStephen** [comment]
LGTM

**Comment by redaguermas** [comment]
@GLStephen ,
Thank you. Do you know how do I passed the test? 
image

**Comment by GLStephen** [comment]
@redaguermas I'm getting a second look at the CircleCI issue and we'll merge if it's just a transient thing or work on getting it resolved

**Comment by redaguermas** [comment]
Great thank you

**Pull request merged**
