### PR TITLE
Add Arteebee bidder adapter

### PR DESCRIPTION
**Pull request by jeffyecn**
## Type of change

- [x] New bidder adapter  

## Description of change

Add a new bidder adapter to connect to arteebee.com

- test parameters for validating bids
```
{
  bidder: 'arteebee',
  params: {
    ssp:'mock',
    pub:'prebidtest',
    source:'prebidtest',
    test: true
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

Contact email: jeffyecn@gmail.com

## Other information

The document pull request will be submit soon.

### CODE REVIEW

**Comment by jeffyecn** [comment]
Document PR has been submitted:

https://github.com/prebid/prebid.github.io/pull/452

**Comment by mike-chowla** [comment]
Bid request using the test parameters is getting a 204 back so I cannot verify ads load correctly.

Here's the request that's going out:

http://bidder.mamrtb.com/rtb/bid/mock?type=json&register=0
```javascript
{  
   "id":"fa0ddb81-cf63-4de3-b08c-496c01a5dfa6",
   "imp":[  
      {  
         "id":"2af390820b9459",
         "tagid":"div-gpt-ad-1460505748561-0",
         "banner":{  
            "format":[  
               {  
                  "w":300,
                  "h":250
               },
               {  
                  "w":300,
                  "h":600
               }
            ]
         }
      }
   ],
   "site":{  
      "id":"prebidtest",
      "page":"http://localhost:9999/integrationExamples/gpt/hello_world.html",
      "ref":"",
      "publisher":{  
         "id":"prebidtest",
         "domain":"localhost:9999"
      }
   },
   "device":{  
      "ua":"caller",
      "ip":"caller",
      "js":1
   },
   "at":1,
   "tmax":3000,
   "test":1
}
'''

**Comment by mike-chowla** [comment]
Lint has a lot of complaints about indentation and spacing:

[lint.out.txt](https://github.com/prebid/Prebid.js/files/1489323/lint.out.txt)

**Comment by jeffyecn** [comment]
Hi, Mike,  The 204 is because our system do not allow with host name localhost, is that possible you can map any valid domain to 127.0.0.1. It should be fine after that.

I will look at the lint complains, thanks for pointing it out.

Jeff Ye

**Comment by jeffyecn** [comment]
Hi, Mike,

I have fixed the lint complaint as well. Let me know if any thing need me to do. 

Thank you very much.

Jeff Ye

**Comment by mike-chowla** [comment]
I aliased my hostname and the ad loads fine now.  Lint issues are also resolved.

**Comment by jeffyecn** [comment]
Hi, Mike,

I have updated our bidder to accept localhost for test request. So, it should work without mapping to a fake host now.

BTW, I didn't see the travis ci build result for this PR, is there any thing I have missed?

Thanks.

Jeff Ye

**Comment by mkendall07** [comment]
@jeffyecn 
Try logging into travis-ci website with a user from our fork/organization. That sometimes is an issue. 

Then open/close the PR.

**Comment by jeffyecn** [comment]
try close / re-open to trigger travis-ci build

**Comment by jeffyecn** [comment]
Hi, Matt,

The travis-ci build is okay now. Thanks,

Jeff Ye

**Comment by jeffyecn** [comment]
@mike-chowla 

Hi, Mike, not sure if still anything need me to do? Have not seen the LGTM label on this PR yet. :-)

Thanks,

Jeff Ye

**Pull request merged**
