### PR TITLE
No bid version 1.2.8

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change
- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter 
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support for GDPR/TCF 2.0

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:
- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/2253

### CODE REVIEW

**Comment by redaguermas** [comment]
This error is unrelated to our code. Can you double-check please?

**Comment by robertrmartinez** [comment]
@redaguermas Please add unit tests

**Review by musikele — CHANGES_REQUESTED** [review]
as said in another comment, please add unit tests to keep the code coverage greater than 80%, but I encourage to test as much as you can. Thank you

**Comment by redaguermas** [comment]
The test-coverage does not work. Is it working for you?
> gulp test-coverage
[16:58:25] Using gulpfile ~/Documents/work/nobid/Prebid.js/gulpfile.js
[16:58:25] Starting 'test-coverage'...
[16:58:25] Starting 'clean'...
[16:58:25] Finished 'clean' after 10 ms
[16:58:25] Starting 'testCoverage'...

START:
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: Failed to compile.
26 08 2020 16:58:47.749:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
26 08 2020 16:58:47.750:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 5
26 08 2020 16:58:47.755:INFO [launcher]: Starting browser ChromeHeadless
26 08 2020 16:58:48.077:INFO [HeadlessChrome 84.0.4147 (Mac OS X 10.15.4)]: Connected on socket P5D7-7TxrFvaFTdvAAAA with id 42175759
26 08 2020 16:58:50.097:WARN [reporter]: SourceMap position not found for trace: Uncaught Error: Cannot find module "src/adloader.js"
at http://localhost:9876/base/test/test_index.js?dc5396d26193ca2528d42dc43b9d6782966d7e60:11837:1

Error: Cannot find module "src/adloader.js"
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?dc5396d26193ca2528d42dc43b9d6782966d7e60:11837:7)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?dc5396d26193ca2528d42dc43b9d6782966d7e60:20:30)
    at Object.<anonymous> (http://localhost:9876/base/test/test_index.js?dc5396d26193ca2528d42dc43b9d6782966d7e60:31966:1)
    at __webpack_require__ (http://localhost:9876/base/test/test_index.js?dc5396d26193ca2528d42dc43b9d6782966d7e60:20:30)
    at http://localhost:9876/base/test/test_index.js?dc5396d26193ca2528d42dc43b9d6782966d7e60:63:18
    at http://localhost:9876/base/test/test_index.js?dc5396d26193ca2528d42dc43b9d6782966d7e60:66:10
HeadlessChrome 84.0.4147 (Mac OS X 10.15.4) ERROR
  Uncaught Error: Cannot find module "src/adloader.js"
  at webpack:///test/mocks/adloaderStub.js:2:1 <- test/test_index.js:11837:1
  
  Error: Cannot find module "src/adloader.js"
      at Object.<anonymous> (webpack:///test/mocks/adloaderStub.js:2:1 <- test/test_index.js:11837:7)
      at __webpack_require__ (webpack:///webpack/bootstrap%20a27aaf5067d3fb4ce44d:19:1 <- test/test_index.js:20:30)
      at Object.<anonymous> (webpack:///test/test_index.js:2:1 <- test/test_index.js:31966:1)
      at __webpack_require__ (webpack:///webpack/bootstrap%20a27aaf5067d3fb4ce44d:19:1 <- test/test_index.js:20:30)
      at webpack:///webpack/bootstrap%20a27aaf5067d3fb4ce44d:62:1 <- test/test_index.js:63:18
      at test/test_index.js:66:10

Finished in 2.032 secs / 0 secs @ 16:58:50 GMT-0700 (Pacific Daylight Time)

SUMMARY:
✔ 0 tests completed

**Comment by redaguermas** [comment]
@musikele ,
Can you please review my last comment?

-Thanks

**Comment by musikele** [comment]
Hi @redaguermas , I can run tests just fine. You may need to delete node_modules folder and do npm install again. Also, currently there is anoter module that has failing tests. To get around this issue, you can comment out or skip the offending tests. 
Another thing that could help, instead of using `gulp test-coverage` directly, use `npx gulp test-coverage`. The difference is that `gulp test-coverage` will try to use globally-installed gulp, that may be of a different version respect to the one of prebidjs. By using `npx`, you are explicitly using the version used by prebid. 
Hope that helps. Let me know if you succeed.

**Comment by redaguermas** [comment]
@musikele 
The error seems unrelated to our Adapter changes.

**Comment by redaguermas** [comment]
@robertrmartinez , I added unit tests and the coverage is >80%.
The CI error is not related to our Adapter changes.

**Review by musikele — APPROVED** [review]
LGTM

**Pull request merged**
