### PR TITLE
new bidder adapter: mediasquareBidAdapter

### PR DESCRIPTION
**Pull request by matthieularere-msq**
## Type of change

- [ x] New bidder adapter   

## Description of change

Add necessary files for new bidder mediasquare

- test parameters for validating bids
```
{
    bidder: 'mediasquare',
    params: {
        owner: "test",
        code: "publishername_atf_desktop_rg_pave"
    }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer admin@mediasquare.fr
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by jeanstemp** [comment]
prebid/prebid.github.io#2017

**Comment by aleksatr** [comment]
hey @matthieularere-msq , check out the circleci output, you have some lint errors that you need to fix.  
Also, every new adapter submission must include unit tests: http://prebid.org/dev-docs/bidder-adaptor.html#adding-unit-tests

After you add unit tests, make sure that you have at least 80% unit test coverage:
To generate and view the code coverage reports:

```bash
gulp test-coverage
gulp view-coverage
```

If you have trouble running test-coverage & view-coverage, take a look at the temporary workaround here: #5128 (but please don't commit that change into this PR).

**Comment by matthieularere-msq** [comment]
Hey @aleksatr ,
Thanks, I think it should be good now.

**Comment by aleksatr** [comment]
hey @matthieularere-msq , yes, tests are passing and test coverage is good. 
I tried testing your adapter with the parameters you provided (owner: "test" and code: "publishername_atf_desktop_rg_pave", I also added `msq_test=true` to the URL, to hit the test endpoint), but I was unable to get a positive bid response:

image

Also, I noticed that in [documentation PR](https://github.com/prebid/prebid.github.io/pull/2017/files) you stated that this adapter supports schain and usp, while in adapter source I see that schain part is commented out:

```
// schain: validBidRequests.schain,
```

and there are no mentions of US privacy at all.

**Comment by matthieularere-msq** [comment]
Hey @aleksatr ,
I see your call coming from http://jita.local.net/pages/clamps.html?__JITA__&msq_test=true
This domain is likely to be blocked as suspicious as it's for sale.
I made tests from publishers hosted pages and from https://js.do/ (see https://js.do/mediasquare-ml/test_adapter), maybe you could try from this one?

You are right about schain and usp, we initialy planned to support it but it will be for a later version, I'll update the documentation PR

**Comment by aleksatr** [comment]
LGTM

**Pull request merged**
