### PR TITLE
MediaFuse bid adapter: initial release

### PR DESCRIPTION
**Pull request by balajimediafuse**
I have created alias from appnexus Prebid.js adapter and created one for Mediafuse

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Created MediaFuse Prebid.js bidder adapter alias from appnexus Prebid.js adapter

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by jsnellbaker** [comment]
@balajimediafuse This doesn't appear to be an alias update.  It looks like a copy of the raw appnexus bid adapter code, with the name replaced.

If you wanted to add an alias to the appnexus bid adapter, you can add it to this array variable here:
https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L69

Similarly, I noticed there was an alias for `mediafuse` under the bid adapter `adtelligent` (https://github.com/prebid/Prebid.js/blob/master/modules/adtelligentBidAdapter.js#L42).  That would likely need to be removed as well, so prevent any conflicts/collision within prebid's logic.

**Review by jsnellbaker — CHANGES_REQUESTED** [review]
Hi @balajimediafuse 

Thanks for making the separately requested updates.  There are a few additional changes that need to be made however.  Below are some in-line comments based on my initial testing.

In addition, in the `test/spec/modules/adtelligentBidAdapter_spec.js` file, there is a reference to the mediafuse alias which is causing one of adtelligent's unit tests to fail.  Below is a direct link to the remaining reference:
https://github.com/prebid/Prebid.js/blob/master/test/spec/modules/adtelligentBidAdapter_spec.js#L17

I believe if you remove the entry from their list, it should allow the unit test to pass.

Please let me know if you have any questions about the requested changes.  Thanks.

**Comment by balajimediafuse** [comment]
Dear @jsnellbaker,

 

I have updated the code as per your suggestions, and committed the code to same PR.

 

From one of your comments to update the code as ../src/polyfill.js. I cannot locate this file. Is this file part of the repo?

 

You can do your due diligence and let me know if any further code change is required from me.

 

Thanks & regards,

Balaji K

**Review by jsnellbaker — COMMENTED** [review]
@balajimediafuse Would you be able to try to rebase against `master`?  

There are some errors in the circleci browserstack tests complaining about the import of the polyfill file.  I think it may be tied to the rest of the forked code is out of sync with master, and that circleci's running with a version of the code that's in a old/new state.  If things were re-synced it may help address those errors and let the tests run against browserstack (which would let us know that things should be fine with these code changes in diferent browsers).

Thanks.

**Comment by balajimediafuse** [comment]
Dear @jsnellbaker,

 

I tried to sync my forked repo from Prebid.js/master repo and below are the results. I think it is update to date even I tried fetch from upstream. Even after that I cannot find ../src/polyfill.js in my local folder.

 

Am I missing something here? Please suggest

 



 

Thanks & regards,

Balaji K

**Comment by jsnellbaker** [comment]
Hi @balajimediafuse 

I didn't see anything attached or updated in the PR (or pushed to the fork). Could you try to send again?

**Comment by balajimediafuse** [comment]
Dear @jsnellbaker,

 

I tried all possible ways to rebase the remote master branch to my forked repo. But still I can’t able to see theile ‘../src/polyfill.js’

 

Can you please let me know how to I rebase my forked repo with Prebid.js <https://github.com/prebid/Prebid.js>  repo.

 

Thanks & regards,

Balaji K

**Comment by jsnellbaker** [comment]
I've found like this link with some steps that could use to git fetch/pull the changes from the master to a fork.  This could a different way to re-sync instead of a rebase.

https://gist.github.com/CristinaSolana/1885435

This stackoverflow also provides some commands you run to see how you have certain branches linked to upstream sources (so that you can potentially re-point them like what the above link provides as an example).
https://stackoverflow.com/questions/4950725/how-can-i-see-which-git-branches-are-tracking-which-remote-upstream-branch

**Comment by balajimediafuse** [comment]
Dear @jsnellbaker,

 

Thanks for the information. Now I have updated my forked repo from the original repo.

 

You will see the changes in the same PR. Now I can see ‘../src/polyfill.js’ on my local repo. Hope this resolved the rebase issue with master.

 

Please let me know if any change is required in the code.

 

Thanks & regards,

Balaji K

**Review by jsnellbaker — APPROVED** [review]
Glad to hear it worked out.  I think this looks good now.  I saw had a docs PR opened already, so please double-check it's in the right state given the changes we did here.

**Comment by balajimediafuse** [comment]
Dear @jsnellbaker,

 

Yes, I crossed check the PR and all the changes that suggested by you so far is in same PR <https://github.com/prebid/Prebid.js/pull/8113> 

 

Is the adapter approved now and our clients can start using the same?

 

Thanks & regards,

Balaji K

**Comment by jsnellbaker** [comment]
It should be available for general use when the next Prebid.js release goes out later this week; version 6.16.0.

Once it's available, your clients would need to update to that version and then they should be able to call your new bid adapter.

**Comment by balajimediafuse** [comment]
Dear @jsnellbaker,

 

Is our adapter moved to Production? I’m not seeing it in this link <https://docs.prebid.org/download.html> .

 

Please let me know the status so that I can update my team on the same.

 

Thanks & regards,

Balaji K

**Comment by jsnellbaker** [comment]
@balajimediafuse 

I'm sorry for the delay, I was out of office this past week.  I checked the download page today and saw MediaFuse was available for use.  Are you able to see it on your end?  There may have been a minor delay in the page re-syncing its options.

-Jason

**Comment by balajimediafuse** [comment]
Dear @jsnellbaker,

 

I checked the download page on Friday, and I could identify the MediaFuse name available, and I have passed the same information to internal team here.

 

Thanks for your efforts, much appreciated.

 

Thanks & regards,

Balaji K

**Pull request merged**
