### PR TITLE
Nativo Bid Adapter: add new bid adapter

### PR DESCRIPTION
**Pull request by jsfledd**
## Type of change

- [x ] New bidder adapter

## Description of change
Adding Nativo Bidder Adapter

- test parameters for validating bids
```
{
  bidder: 'nativo',
  params: {
      placementId: 1125609,
      url: 'https://test-sites.internal.nativo.net/testing/prebid_adpater.html'
  }
}
```

- contact email of the adapter’s maintainer: **prebiddev@nativo.com**
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/: **https://github.com/prebid/prebid.github.io/pull/2834**

## Other information
n/a

### CODE REVIEW

**Comment by patmmccann** [comment]
Welcome to the party Nativo

**Comment by ChrisHuie** [comment]
@jsfledd I don't think you intended to add your package.json file to this pr, Can you please take it out of this pr?

**Comment by jsfledd** [comment]
@ChrisHuie Thank you for the heads-up. I removed the file from the PR.

**Comment by Rothalack** [comment]
Hey @jsfledd  Do you have a placementId that would work for testing?

I'm getting a server call error, I'm not sure if that's configuration on my end or not. Is your bidder endpoint active?

**Comment by jsfledd** [comment]
Hey @Rothalack, thank you for the feedback. Wanted to give you a quick update. I am working on getting the endpoint to consistently return a bid. It's currently working on a qa version of the endpoint but not the prod version. I will let you know when it's ready.

**Comment by jsfledd** [comment]
Hi @Rothalack. Sorry for the delay in getting you the working endpoint. I believe we're all good to go for testing. I have made a small addition and updated the documentation with an additional adUnit bidder parameter.

**Review by Rothalack — APPROVED** [review]
Thanks for the updates, this looks good to go!

**Pull request merged**
