### PR TITLE
add advertiserDomains meta field to ix adapter

### PR DESCRIPTION
**Pull request by patmmccann**
## Type of change

- [ ] Bugfix
- [x ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

This adds meta field advertiserDomains partially solving #3115

### CODE REVIEW

**Comment by patmmccann** [comment]
Please check @ix-prebid-development @ix-prebid-support ; Thanks!!

**Comment by musikele** [comment]
@patmmccann , why this PR was open on the prebid-4.0 branch ?

**Comment by patmmccann** [comment]
because adding meta is in scope for https://github.com/prebid/Prebid.js/issues/4824

**Comment by ix-prebid-support** [comment]
@patmmccann can we add a test case to cover the case where this field is not present in the bid response?

**Comment by patmmccann** [comment]
@ix-prebid-support see https://github.com/prebid/Prebid.js/pull/5422

**Pull request merged**
