### PR TITLE
OpenX Adapter update to Prebid v1.0

### PR DESCRIPTION
**Pull request by lntho**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other

## Description of change
Update OpenX adapter to Prebid v1.0 specs

### CODE REVIEW

**Comment by rjvelicaria** [comment]
@matthewlane Added the markdown.  Is there anything else that we forgot to put in?

**Comment by matthewlane** [comment]
#1724 looks like an updated version of this PR, should this PR be closed in favor of that one?

**Comment by lntho** [comment]
@matthewlane We have decided to submit this PR first and submit the PR for video as another PR to our adapter later. I will update this PR to fix any comments the other PR had shortly.

**Comment by matthewlane** [comment]
@lntho Ok, looks like this was updated to fix comments from the other PR, we'll work on getting this merged first. Only holdup is that I'm getting empty bid responses with the test parameters from `openxBidAdapter.md`, please advise. Once bid response are validated we should be good to go

**Comment by lntho** [comment]
@matthewlane Thanks for the review. I have updated the ad unit as well as the size it can receive, this one should work now. Please let me know if it doesn't. Thanks again!

**Comment by matthewlane** [comment]
Hmm, still no luck with the updated parameters. What I'm doing is taking those and putting them on the [hello_world test page](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/hello_world.html#L23), updating the sizes to `[[728, 90]]`, running `gulp serve`, and opening the page in a browser. Checking `pbjs.getBidResponses()` in the console, OpenX has a statusMessage of "Bid returned empty or error response". Are you getting different results in this setup?

**Comment by lntho** [comment]
@matthewlane Apologies for the late response, I was out yesterday. I have updated to a new ad unit that I have tested with the hello_world test page and it should work. Please let me know if it doesn't.

**Pull request merged**
