### PR TITLE
Trion gdpr and usp consent

### PR DESCRIPTION
**Pull request by grohm33**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Updating Trion to comply with gdpr and usp consent

### CODE REVIEW

**Comment by grohm33** [comment]
also submitted documentation pull request at https://github.com/prebid/prebid.github.io/pull/1752

**Comment by bretg** [comment]
LGTM, but please try re-running the CircleCI unit tests to get them to pass.

**Comment by grohm33** [comment]
> LGTM, but please try re-running the CircleCI unit tests to get them to pass.

@bretg we had this issue with circleci build checks not passing on here in the past with our pull requests.  We do not have a browser stack account to run this against so the error I'm getting in the build is 'Username is required'.

**Comment by bretg** [comment]
I've opened a CircleCI support ticket to get to the bottom of why some PRs (like this one) end up outside of Prebid's CircleCI account.

**Comment by grohm33** [comment]
@bretg Thanks for the info!  I didn't realize it was associating our fork to the circleCi project.  The tests all pass now.

**Comment by ericrenebrown** [comment]
This is happening to me. Stopped following but I can't see an option to follow the "real" project.

**Pull request merged**
