### PR TITLE
CleanIO RTD Module: support billable event

### PR DESCRIPTION
**Pull request by alexeyst**
Add billable events to [clean.io Real-time Anti-Malvertising Module](https://docs.prebid.org/dev-docs/modules/cleanioRtdProvider.html)

## Type of change

- [x] Other

## Description of change
As described in [Vendor Billing](https://docs.prebid.org/dev-docs/vendor-billing.html), clean.io will now submit a billable event for each protected impression.

- contact email of the adapter’s maintainer

Module Name: clean.io Rtd provider
Module Type: Rtd Provider
Maintainer: [nick@clean.io](mailto:nick@clean.io)

- [x] official adapter submission

## Other information
Solution was previously merged as part of [pull request #7449](https://github.com/prebid/Prebid.js/pull/7449)

### CODE REVIEW

**Comment by nick-clean** [comment]
@ChrisHuie 
As we expected, the CircleCI tests failed. Our update includes utilizing a billable events; however, the tests seem to be hardcoded for a specific number of billable events so they fail when we send an unexpected event.
Screen Shot 2022-07-28 at 9 15 57 AM

Can you advise?  We believe this is an issue with the tests.

**Comment by nick-clean** [comment]
@mmoschovas 
We're not surprised that the CircleCI tests failed. Our update includes utilizing a billable events; however, the tests seem to be hardcoded for a specific number of billable events so they fail when we send an unexpected event.

With a previous submission, we were told to pull in recent PRs to resolve the issue, but that doesn't look to resolve the problem, as the tests seem to be hardcoded for specific values.  Can you let us know how to proceed?

**Comment by nick-clean** [comment]
> In the past, for things like
> 
> `should catch all events if affiliate id present Sovrn Analytics Adapter enableAnalytics AssertError: expected track to be called 5 times but was called 6 times`
> 
> we just increase the count in the expect

@patmmccann Thanks for jumping in. Are you stating that the tests need to be updated by manually adjusting the Expected count? Is that something @mmoschovas would do?  I unclear if this is something that you are requesting of us. Could you help clarify?

**Comment by mmoschovas** [comment]
@nick-clean sorry for the delay. You would need to go through the tests that fail with the introduction of your billable event and increase their expected values

**Review by mmoschovas — APPROVED** [review]
lgtm

**Pull request merged**
