### PR TITLE
RichAudience Adapter: Keywords + Screen resolution + CPU Core

### PR DESCRIPTION
**Pull request by richaudience**
## Type of change

- [ ] Bugfix
- [ x ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Add new parameters to the request

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by bretg — CHANGES_REQUESTED** [review]
Needs unit tests for the new params please.

**Comment by ChrisHuie** [comment]
It looks like there is also a reports JSON file getting committed in this request. Can you please take a look at that before I merge?

**Comment by ChrisHuie** [comment]
@richaudience could you please remove the package-lock.json from this pr since there appears to be no change to that file.  Right now it looks like all the lines in that file are being modified unless I am looking at it wrong.

**Comment by richaudience** [comment]
Close the pull and open other with only the necessary changes: 
[https://github.com/prebid/Prebid.js/pull/6259](new pull)

**Pull request closed without merging**
