### PR TITLE
Adot Bid Adapter: add advertiser domains support; add support for openrtb video parameters on the ad unit

### PR DESCRIPTION
**Pull request by Giudici-a**
- [X ] Feature

## Description of change
Change the adapter to fit with the new release by adding the support of the advertising domains.

Link to [#6650](https://github.com/prebid/Prebid.js/issues/6650?utm_medium=email&_hsmi=129770716&_hsenc=p2ANqtz-9W5qiCP-q5r0yn7UPZOFDisX3TghHKLu9VTHkq_XU9BsI1heFZQK5Qfg9g_-QeriJ0HXBBtRiiNta0brer9iGdYPJSmw&utm_content=129770716&utm_source=hs_email)

### CODE REVIEW

**Comment by patmmccann** [comment]
Hi,  can you also take a look at #6512

**Comment by ChrisHuie** [comment]
@Giudici-a can you please add a unit test to this pr please 🙏

**Comment by patmmccann** [comment]
appears to fix #6512 for adot, thanks!

**Comment by Giudici-a** [comment]
@ChrisHuie , i just added a test for the adomains, we are at 93.17% of coverage for our adapter !

Is it good enough for you ?

**Comment by ChrisHuie** [comment]
@Giudici-a the test coverage is fine. Looks like there are still some errors. I think pulling upstream commits should fix that. Could you change undefined to null also because looks like lgtm is complaining about setting delay time to undefined instead of null or 0 🙏

**Comment by Giudici-a** [comment]
Hi @ChrisHuie,  i modify the delay to avoid the lgtm complaining. 

But i don't understand why the tests of the ci are not working, i did the rebase on my branch with master, and the ci is still failing on test that are not on our adapter. 
Do you have any idea of how could i fix that ? Sorry for the disturbance.

**Comment by Giudici-a** [comment]
Hi @ChrisHuie,  i modify the delay to avoid the lgtm complaining. 

But i don't understand why the tests of the ci are not working, i did the rebase on my branch with master, and the ci is still failing on test that are not on our adapter. 
Do you have any idea of how could i fix that ? Sorry for the disturbance.

**Comment by Giudici-a** [comment]
Hi @ChrisHuie,  i modify the delay to avoid the lgtm complaining. 

But i don't understand why the tests of the ci are not working, i did the rebase on my branch with master, and the ci is still failing on test that are not on our adapter. 
Do you have any idea of how could i fix that ? Sorry for the disturbance.

**Comment by Giudici-a** [comment]
Hi @ChrisHuie,  i modify the delay to avoid the lgtm complaining. 

But i don't understand why the tests of the ci are not working, i did the rebase on my branch with master, and the ci is still failing on test that are not on our adapter. 
Do you have any idea of how could i fix that ? Sorry for the disturbance.

**Comment by ChrisHuie** [comment]
@Giudici-a  this looks fine. We have a few flaky tests that can occur from certain browsers and interacting with storage.

**Review by ChrisHuie — APPROVED** [review]

**Comment by Giudici-a** [comment]
@ChrisHuie  ok, Thanks for the review !

**Pull request merged**
