### PR TITLE
Kargo adapter

### PR DESCRIPTION
**Pull request by samuelhorwitz**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change
Adding an adapter for Kargo Global, Inc..

- test parameters for validating bids
```
{
  bidder: 'kargo',
  params: {
    placementId: '_lak5xuxuRo'
  }
},
{
  bidder: 'kargo',
  params: {
    placementId: '_m1Xt2E5dez'
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: sam@kargo.com
- [x] official adapter submission

### CODE REVIEW

**Comment by samuelhorwitz** [comment]
@protonate sorry if you are not the right person to ask here, but the Travis build is failing due to a Criteo test that fails (I haven't touched any of that code) and it also looks like the test suite bails before even finishing all the tests. I'm not sure how to resolve this but I don't believe it's our code that is triggering the Travis failure.

**Comment by dbemiller** [comment]
@samuelhorwitz No worries, you're absolutely right :).

Criteo fixed the issue in #1308. If you pull in the most recent changes those failures should go away.

**Comment by samuelhorwitz** [comment]
Cool thanks! Rebased everything, it's still bailing out at test 443 which might be our end, I will re-test locally again.

**Comment by samuelhorwitz** [comment]
Fixed up my tests and it appears that everything runs all the way through now.

**Comment by samuelhorwitz** [comment]
@dbemiller I have updated this PR to reflect all the re-organization of code on master and all the tests are passing with good (above 80%) coverage results. Is there anything else I need to do for this PR?

**Comment by dbemiller** [comment]
@samuelhorwitz No promises either way yet :).

Time to review this isn't scheduled in our current sprint... so I wouldn't expect anyone to look at it until at least next week.

**Comment by samuelhorwitz** [comment]
Cool, sounds good!

**Comment by samuelhorwitz** [comment]
Hey guys does this week seem likely for a review?

**Comment by dbemiller** [comment]
Looks great to me. Very nice code... you should be proud :).

FYI: You might want to [update the docs](https://github.com/prebid/prebid.github.io) explaining your bidder params too.

**Comment by samuelhorwitz** [comment]
Thanks! I have a documentation update here

https://github.com/prebid/prebid.github.io/pull/274

**Pull request merged**
