### PR TITLE
New mobfox prebid adapter

### PR DESCRIPTION
**Pull request by mobfxoHB**
## Type of change

- [x] New bidder adapter   

## Description of change

New mobfox adapter

- test parameters for validating bids
```var adUnits = [
                {
                    code:'1',
                    mediaTypes:{
                        banner: {
                            sizes: [[300, 250]],
                        }
                    },
                    bids:[
                        {
                            bidder: 'mobfoxpb',
                            params: {
                                placementId: 0
                            }
                        }
                    ]
                },
                {
                    code:'1',
                    mediaTypes:{
                        video: {
                            playerSize: [640, 480],
                            context: 'instream'
                        }
                    },
                    bids:[
                        {
                            bidder: 'mobfoxpb',
                            params: {
                                placementId: 0
                            }
                        }
                    ]
                },
                {
                    code:'1',
                    mediaTypes:{
                        native: {
                            title: {
                                required: true
                            },
                            icon: {
                                required: true,
                                size: [64, 64]
                            }
                        }
                    },
                    bids:[
                        {
                            bidder: 'mobfoxpb',
                            params: {
                                placementId: 0
                            }
                        }
                    ]
                }
            ];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
platform@mobfox.com
- [ ] official adapter submission

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/2501

### CODE REVIEW

**Review by Rothalack — COMMENTED** [review]
I was able to confirm your Banner set up was working. I was unable to confirm for Native and Video. This may just be a result of my set up. This is my first review and I'm not fully set up yet.

I saw that this may need a merge from master, seeing 22 commits behind.

I've been told that circleci often just needs to be reran, I do not have proper access yet to see the logs from circleci.

@harpere I would like to request a second review to ensure as I have not been fully trained on the system yet.

**Comment by mobfxoHB** [comment]
@Rothalack Good day to you, my congratulations on your first review. Here is basic HTML page to test setup - it will result output to console containig responses for every  mediatype.
`<html>
    <meta charset="utf-8">
    <head>
        <script src="Prebid.js/build/dist/prebid.js"></script>
    </head>
    <body>
        <script>
            var PREBID_TIMEOUT = 2000;
            var FAILSAFE_TIMEOUT = 3000;

            var adUnits = [
                {
                    code:'1',
                    mediaTypes:{
                        banner: {
                            sizes: [[300, 250]],
                        }
                    },
                    bids:[
                        {
                            bidder: 'mobfoxpb',
                            params: {
                                placementId: 0
                            }
                        }
                    ]
                },
                {
                    code:'1',
                    mediaTypes:{
                        video: {
                            playerSize: [640, 480],
                            context: 'instream'
                        }
                    },
                    bids:[
                        {
                            bidder: 'mobfoxpb',
                            params: {
                                placementId: 0
                            }
                        }
                    ]
                },
                {
                    code:'1',
                    mediaTypes:{
                        native: {
                            title: {
                                required: true
                            },
                            icon: {
                                required: true,
                                size: [64, 64]
                            }
                        }
                    },
                    bids:[
                        {
                            bidder: 'mobfoxpb',
                            params: {
                                placementId: 0
                            }
                        }
                    ]
                }
            ];

            var pbjs = pbjs || {};
            pbjs.que = pbjs.que || [];

            const cb = (a,b) => {
                console.log(a,b)
            }

            
            pbjs.que.push(function() {
                pbjs.addAdUnits(adUnits);
                pbjs.requestBids({
                    bidsBackHandler: cb,
                    timeout: PREBID_TIMEOUT
                });
            });
        </script>
    </body>
</html>
`
To make it work - create index.html, put this code in file and clone Prebid.js repo in the same folder, then as usual - npm install , gulp build and open newly created page
Hope it will help you a little

**Comment by Rothalack** [comment]
I've gotten access to Circleci and I see it is a failure to test IE 11.  It seems like every PR is failing on IE 11 and/or Safari, so I don't know if that has been addressed yet.

I've now confirmed your banner, video and native bids are working in the regular test and gdpr test.

This should still need a merge with master, showing 22 commits behind.

**Comment by mobfxoHB** [comment]
@Rothalack  I've merged masters with upstream, but really it is not necessary for PR to be on the same commit as main repository. Commits would not be reverted. Simple example - while you reviewing this PR - new commits are arriving to main repository , making current PR always stay behind

**Comment by Rothalack** [comment]
On line 37 in the main adapter, the URL function you are using isn't supported by IE, which is what is not passing in CircleCI
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

In the same block of code, you're accessing window and window.top which can be accessed rather by utils.getWindowTop and utils.getWindowLocation, etc. If you need host/pathname, it's probably best to just use utils.getWindowTop and use the result window object to get location, etc. You can code defensively for if these return empty.

Credit of this feedback to Robert

**Comment by Rothalack** [comment]
This looks good to go!

**Comment by Rothalack** [comment]
LGTM

**Pull request merged**
