### PR TITLE
Pair Id System: less noisy errors

### PR DESCRIPTION
**Pull request by patmmccann**
Not finding the id is not cause for an error

### CODE REVIEW

**Comment by robertrmartinez** [comment]
@patmmccann I fixed the tests and also updated the adapter to actually execute the `localStorageIsEnabled` and `cookiesAreEnabled` functions.

Added a test to cover it.

**Comment by patmmccann** [comment]
nice! now we need a new reviewer

**Comment by robertrmartinez** [comment]
@congdu-kun Please give this a review

**Review by congdu-kun — APPROVED** [review]
LGTM. Thanks for fixing this @patmmccann!

**Review by smenzer — APPROVED** [review]
LGTM

**Pull request merged**
