### PR TITLE
Districtm dmx passing dealid to prebid

### PR DESCRIPTION
**Pull request by stevealliance**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ x] Other

## Description of change
Deal id key was not map to prebid (dealid vs dealId)

### CODE REVIEW

**Comment by stevealliance** [comment]
> also - you should add USP/CCPA to your user sync requests `getUserSyncs()`



> looks good but needs docs for USP/CCPA support: https://github.com/prebid/prebid.github.io/pulls


This was update already here's the link http://prebid.org/dev-docs/modules/consentManagementUsp.html

**Comment by stevealliance** [comment]
> also - you should add USP/CCPA to your user sync requests `getUserSyncs()`

I would love this PR to be pushed, I will make another one for the user sync. Will make sure to have that ready both server and client side at the earliest

**Comment by stevealliance** [comment]
@harpere  updated requested are all done can you please review

**Comment by stevealliance** [comment]
@bretg, could you let my PR pass or have a look so we can move forward with this.
Thanks for your help I know you are not assign to my PR but didn't get any answer back.

**Comment by bretg** [comment]
Will let the docs go -- it's your call if you want to get credit for your adapter supporting CCPA. But for harpere's comment about the sync requests... when's that going to happen?

**Comment by stevealliance** [comment]
Hi @bretg I've already commit an update for that request [f31582b](https://github.com/prebid/Prebid.js/pull/4772/commits/f31582bd5a33dbd59ca3a24881af916c0d722e51).

Thanks

**Pull request merged**
