### PR TITLE
Currency support for SmartAdServer adapter

### PR DESCRIPTION
**Pull request by Mordhak**
## Type of change
- [x] Feature

## Description of change
Add currency support for SmartAdServer adapter (default to USD)

- contact : prebid@smartadserver.com
- [x] official adapter submission

### CODE REVIEW

**Comment by Mordhak** [comment]
Hi,

Could it be possible to have inputs about PR treatment delays to synchronise it with our own roadmap ?

Regards,

**Comment by jaiminpanchal27** [comment]
Looks good

**Comment by jaiminpanchal27** [comment]
@Mordhak Merged. Thanks

**Comment by Mordhak** [comment]
Hi @aneuway2,

A new parameter has been added to our adapter setup, but it is not mandatory. We added the currency which is set to "USD" by default, but can be overriden if needed.

I will create a new PR in the documentation project to update it accordingly.

Regards,

**Pull request merged**
