### PR TITLE
Submitting Clicktripz bid adapter

### PR DESCRIPTION
**Pull request by apmitchell**
## Type of change

- [x] New bidder adapter   

## Description of change

Submitting Clicktripz bidder adapter for acceptance into the prebid.js repo.
Includes:

1. adapter
2. description
3. test

- test parameters for validating bids
```
{
    bidder: "clicktripz",
    params: {
        placementId: '4312c63f',
        siteId: 'prebid',
    }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- integrations-support@clicktripz.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- https://github.com/prebid/prebid.github.io/pull/1836

### CODE REVIEW

**Comment by apmitchell** [comment]
Hi @bx2, I see this PR has a `needs docs` label.  Is there something I need to do or am I waiting on your review?

**Comment by bx2** [comment]
@apmitchell 

I will try to finish the review today.

In the meantime, the "needs-docs" label means that you are still to submit a MR with your bidder documentation. Take a look at https://prebid.org/dev-docs/bidder-adaptor.html at the very bottom:

```
1. Fork the repo prebid.github.io
2. Copy a file in dev-docs/bidders and modify
```

**Comment by apmitchell** [comment]
> @apmitchell
> 
> I will try to finish the review today.
> 
> In the meantime, the "needs-docs" label means that you are still to submit a MR with your bidder documentation. Take a look at https://prebid.org/dev-docs/bidder-adaptor.html at the very bottom:
> 
> ```
> 1. Fork the repo prebid.github.io
> 2. Copy a file in dev-docs/bidders and modify
> ```

Hi @bx2, I have that MR here prebid/prebid.github.io#1836

**Comment by bx2** [comment]
@apmitchell thanks for you patience. I reviewed and accepted the changes you submitted. They will be available in the next release of Prebid.

You may open a PR in the [headerbid-expert repository](https://github.com/prebid/headerbid-expert) to have your adapter recognized by the [Headerbid Expert extension](https://chrome.google.com/webstore/detail/headerbid-expert/cgfkddgbnfplidghapbbnngaogeldmop). The PR should be to the [bidder patterns file](https://github.com/prebid/headerbid-expert/blob/master/bidderPatterns.js), adding an entry with your adapter's name and the url the adapter uses to send and receive bid responses.

**Pull request merged**
