### PR TITLE
docereeAdManager Bid Adapter : Updated bid adapter

### PR DESCRIPTION
**Pull request by Doceree-techStack**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter  
- [ ] Updated bidder adapter   
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Updated field for user inputs

### CODE REVIEW

**Comment by Doceree-techStack** [comment]
please check

**Comment by patmmccann** [comment]
@Doceree-techStack we have no unit tests in this pr

**Comment by Doceree-techStack** [comment]
We have added only one parameter for our adrequest. Do we need to write unit tests for this?

**Comment by patmmccann** [comment]
Yes, a unit test isn't just an annoying chore, it protects your code from breaking in a very active project. Chatgpt is very skilled at writing them.

**Comment by Doceree-techStack** [comment]
We have added the required unit test please check.

**Pull request closed without merging**
