### PR TITLE
Rise Bid Adapter : set flexible terms for sync 

### PR DESCRIPTION
**Pull request by noamtzu**
## Type of change

- [ X] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Set flexible terms for sync

- test parameters for validating bids
```
{
            bidder: 'rise',
            params: {
                org: '56f91cd4d3e3660002000033', // Required
                floorPrice: 5.00, // Optional
                placementId: '12345678', // Optional
                testMode: true // Optional
            }
        }
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ X] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by noamtzu** [comment]
Hi @musikele, how are you? have a great week!

**Comment by musikele** [comment]
Hi @noamtzu , why you're not honoring the `syncOptions` parameter? I see that you always pass iframe and image...

**Comment by noamtzu** [comment]
Hi @musikele , we are respecting the params in `getAllowedSyncMethod` function and sending that to the server and he response with the exact sync method

**Comment by musikele** [comment]
After some discussion with the Prebid board, we'd prefer to have an `if iframeEnabled` and `if pixelEnabled`. Hope you understand the point of view of publishers. Can you add that to the code?

**Comment by noamtzu** [comment]
Hi @musikele , I'll close the PR. Thanks 🙏🏻

**Pull request closed without merging**
