### PR TITLE
Reforge Bid Adapter: add new bid adapter

### PR DESCRIPTION
**Pull request by reforge-prebid**
## Type of change

- [x] Bugfix
- [ ] Feature
- [x ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: 'reforge',
  params: {
   
           "id":"c33d3e84b93d4e2a44b4f22434ef99441678",
           "at":2,
           "tmax":410,
           "cur":[
              "USD"
           ],
           "bcat":[
              "IAB26",
              "IAB25",
              "IAB24"
           ],
           "imp":[
              {
                 "id":"1",
                 "instl":0,
                 "bidfloor":0,
                 "bidfloorcur":"USD",
                 "banner":{
                    "w":300,
                    "h":50,
                    "id":"1",
                    "btype":[
                       4
                    ],
                    "battr":[
                       8,
                       10
                    ],
                    "topframe":0,
                    "api":[
                       3,
                       5
                    ],
                    "pos":0
                 },
                 "banner1":{
                    "w":300,
                    "h":480,
                    "id":"1",
                    "btype":[
                       4
                    ],
                    "battr":[
                       8,
                       10
                    ],
                    "topframe":0,
                    "api":[
                       3,
                       5
                    ],
                    "pos":0
                 },
                 "secure":1
              }
           ],
           "site":{
              "id":"80862",
              "cat":[
                 "IAB15",
                 "IAB15-10"
              ],
              "publisher":{
                 "id":"80862"
              },
              "storeurl":"https://itunes.apple.com/app/id295646461"
           },
           "user":{
              "id":"3c098d88-3b09-42c2-86c2-954236d26a87"
           },
           "ext":{
              "udi":{
                 "idfa":"3c098d88-3b09-42c2-86c2-954236d26a86"
              },
              "fd":0,
              "utctimestamp":"1561101479962",
              "utcdatetime":"2019-06-21 07:17:59"
           }
        
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ amit.kumar@svgmedia.in] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by smenzer** [comment]
is this a new bidder adapter submission? why is the .js code minified?

**Comment by robertrmartinez** [comment]
Assigned to @Fawke 

But he cannot review until you submit the unminified code.

Prebid.js minifies code once wrappers are built.

@reforge-prebid

**Review by Fawke — CHANGES_REQUESTED** [review]
>Assigned to @Fawke
But he cannot review until you submit the unminified code.
Prebid.js minifies code once wrappers are built.
@reforge-prebid

Please provide unminified js code.

**Comment by ChrisHuie** [comment]
@reforge-prebid can you please also submit a docs pr to go along with this? The bottom of this page has instructions to help if you need it (https://docs.prebid.org/dev-docs/bidder-adaptor.html#required-files)

**Comment by ChrisHuie** [comment]
@reforge-prebid following up on this pr to see if there is anything I can help you with

**Comment by ChrisHuie** [comment]
closing. Please feel free to reopen with changes

**Pull request closed without merging**
