### PR TITLE
Userid module: change support for multiple sources in a single eid

### PR DESCRIPTION
**Pull request by Nick-Merkle**
## Type of change
- [x] Feature

## Description of change

* Added support for USER_IDS_CONFIG to use an optional function to obtain a value
* Merkle, or any other sub-module can support multiple ids per SSP

- example USER_IDS_CONFIG
```
'merkleId': {
    getSource: function(data) {
      if (data?.ext?.ssp) {
        return `${data.ext.ssp}.merkleinc.com`
      }
      return 'merkleinc.com'
    }
}
```

### CODE REVIEW

**Comment by patmmccann** [comment]
@Nick-Merkle please feel free to reword the title if necessary, we typically title 'module: change' as the titles go in release notes

**Comment by patmmccann** [comment]
Also, could you repull master, the script error you got from circleci should be resolved

**Review by smenzer — CHANGES_REQUESTED** [review]
overall looks good. can you please make sure you add documentation for the new config parameters your module supports now? there should be a prebid.org PR for those doc updates, too.

**Comment by Nick-Merkle** [comment]
> overall looks good. can you please make sure you add documentation for the new config parameters your module supports now? there should be a prebid.org PR for those doc updates, too.

That PR has been submitted too: https://github.com/prebid/prebid.github.io/pull/3809

**Comment by smenzer** [comment]
> That PR has been submitted too: [prebid/prebid.github.io#3809](https://github.com/prebid/prebid.github.io/pull/3809)

Great thanks. Just need a 2nd review since this touches core.

**Review by smenzer — APPROVED** [review]

**Review by Fawke — APPROVED** [review]

**Pull request merged**
