### PR TITLE
Invibes Bid Adapter - support for adUnitCode differentiation in multiposition

### PR DESCRIPTION
**Pull request by rcheptanariu**
## Type of change
- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Adapter will send adUnitCode to the ad server in order to distinguish between multiple requests that use the same placement id

- contact email of the adapter’s maintainer
system_operations@invibes.com

- [x] official adapter submission

### CODE REVIEW

**Comment by rcheptanariu** [comment]
Some tests appear to be failing, but they have no connection with my changes and, locally, the tests run OK for me.

**Review by Fawke — CHANGES_REQUESTED** [review]
Can you please write some unit test(s) for this change? Rest looks good.

**Comment by rcheptanariu** [comment]
> Can you please write some unit test(s) for this change? Rest looks good.

Thanks for the review!
Added unit tests for the feature,

**Comment by Fawke** [comment]
@rcheptanariu Can you please pull in the latest changes, someone fixed the failing circle ci tests. Thanks.

**Comment by rcheptanariu** [comment]
> @rcheptanariu Can you please pull in the latest changes, someone fixed the failing circle ci tests. Thanks.

Latest changes have been pulled

Thank you!

**Review by Fawke — APPROVED** [review]

**Pull request merged**
