### PR TITLE
Improvements for browsi RTD provider

### PR DESCRIPTION
**Pull request by omerBrowsi**
## Type of change

- [ ] Bugfix
- [ ] Other

## Description of change

1. Improvements for browsi RTD provider (support for placement id macros, timeout for ajax request)
2. Change bidsBackCallback hook data (adUnits instead of adUnits codes)
3. Add timeout param (used when we don't need auction dealy)

### CODE REVIEW

**Comment by jsnellbaker** [comment]
@omerBrowsi Can you please resync with the latest version of `master` (which was updated to 3.0 yesterday) and resolve the conflicts?  Thanks.

**Comment by omerBrowsi** [comment]
@jsnellbaker Just did but it seems like it cause some mess on this pull request.
Will it be easier if we close this one and I'll make another pull request?
Thanks

**Comment by jsnellbaker** [comment]
@omerBrowsi Eww - that may be the best here.

**Comment by omerBrowsi** [comment]
I opened a new pull request - 
https://github.com/prebid/Prebid.js/pull/4598

**Pull request closed without merging**
