### PR TITLE
Smoot Bid Adapter: initial release

### PR DESCRIPTION
**Pull request by leamarty**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [X] New bidder adapter  
- [ ] Updated bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Other information

Docs: https://github.com/prebid/prebid.github.io/pull/5619

### CODE REVIEW

**Comment by leamarty** [comment]
Eager for a review over here @Fawke 🙏  Thank you!

**Comment by leamarty** [comment]
@ChrisHuie hi there 👋  Any news on this end? Is there anything we need to change?

Thank you in advance!

**Comment by leamarty** [comment]
Hello @ChrisHuie @Fawke !

I'd appreciate a review&merge here. It's been ~2 weeks since the creation of this PR already 🙏

**Review by Fawke — APPROVED** [review]
LGTM

**Pull request merged**
