### PR TITLE
fix prebid server playerwidth and height

### PR DESCRIPTION
**Pull request by ReinoutStevens**
## Type of change

- [x ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Fixes https://github.com/prebid/Prebid.js/issues/6018

### CODE REVIEW

**Comment by ReinoutStevens** [comment]
Unit tests work locally, and I cant see the details of circleci.
If anyone could post the errors so I can investigate the error

**Comment by bretg** [comment]
Certainly appreciate the update @ReinoutStevens , but we need a unit test. Generally when something like this slides for so long, it means we're missing a test. :-)

**Comment by bretg** [comment]
Gotta love those flaky unit tests. 5 runs later it finally succeeded.

**Comment by ReinoutStevens** [comment]
@bretg A bit out of my league

Things that I see that are potentially wrong:

* The code should probably access playerSize, and not sizes, which afaik is the deprecated way to specify width and height. Given that there is a `isValidBid` check that checks for playerSize this should be fine
* I've been trying to get a working unit test: from what I see the unit tests have a `BID_REQUESTS = [...]`, but this only contains a banner ad, and so the code cant access `playerSize` in the unit tests ( as it doesn't exist in the mocked data ), but I am not confident enough to write a video mock. The unit tests would probably pass, but the code would just be dependent on what mock I wrote, and chances are pretty high that it will be wrong.

**Review by msm0504 — APPROVED** [review]

**Pull request merged**
