### PR TITLE
feat(unrulyBidAdapter): add userSync functionality

### PR DESCRIPTION
**Pull request by onome09**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

We are adding the user-sync function to our adapter. We'e also added the publisher configuration for user-syncing on our test page.

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

### CODE REVIEW

**Comment by onome09** [comment]
Hi Robert, 

Thanks for taking a look. Noted, we need to add the gdprConsent in. We will do the work to add this, and update the PR asap.

We should be able to get this pushed tomorrow morning. 

Thanks,

**Comment by robertrmartinez** [comment]
@onome09 

Awesome! Glad to have helped.

Be sure to add a unit test or two around the GDPR data being sent via your user sync as well!

Will watch for the update :)

**Comment by onome09** [comment]
@robertrmartinez 

We've added the GDPR consent changes, ready for your review!

**Comment by robertrmartinez** [comment]
@onome09 Nice, thanks for adding tests for it as well!

LGTM!

**Pull request merged**
