### PR TITLE
Lemma:set mediaType key value

### PR DESCRIPTION
**Pull request by lemmadev**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by harpere — COMMENTED** [review]
LGTM, but needs docs.

**Comment by lemmadev** [comment]
Hello Team, 
Above changes, We have just assigned the correct value to the mediaType key into the bid response object. Just change the logic to assign value to that key. Previously we have a check form request object if the user set that type then the media type value set otherwise it set undefined now we have changed logic on basis of response we discover media type and assigned it to the mediaType key inside the bid object. there are not any core changes done to the code.

**Comment by harpere** [comment]
I was thinking about documenting that you have gdpr support (and any other support that's not documented) here:  https://docs.prebid.org/dev-docs/bidders.html

**Comment by lemmadev** [comment]
No sir, We do not have any changes in the document such as.

**Comment by harpere** [comment]
I see that you support gdpr in both [buildRequests()](https://github.com/prebid/Prebid.js/blob/2074a6ff6fe88b2316bfd4c88aeb7c7e85b946bc/modules/lemmaBidAdapter.js#L280) and [getUserSyncs()](https://github.com/prebid/Prebid.js/blob/2074a6ff6fe88b2316bfd4c88aeb7c7e85b946bc/modules/lemmaBidAdapter.js#L67).  So why not document that?

**Comment by lemmadev** [comment]
I have to remove the non-supported code. Please review the changes.

**Comment by lemmadev** [comment]
Please review the changes.

**Comment by harpere** [comment]
You're removing support for GDPR?   Does your bid endpoint not support it?  in any case, your tests are now failing.

**Comment by lemmadev** [comment]
Yes, right now we have not supported this feature. I have fixed test cases. Please review it.

**Comment by lemmadev** [comment]
Kindly Please review the above changes.

**Comment by lemmadev** [comment]
Hello Team, 
Please review the above changes. We have pending integration of a couple of clients since last week.

**Comment by lemmadev** [comment]
> You're removing support for GDPR? Does your bid endpoint not support it? in any case, your tests are now failing.

Please review the above changes.

**Comment by lemmadev** [comment]
@harpere can we have the changes reviewed on priority please, this has been pending for a couple of weeks now?
We need to close this ASAP, as we have multiple integrations in the queue.
Let us know if there are any further changes required apart from the suggested one to take this to closure.

**Comment by lemmadev** [comment]
Please kindly review the above changes.

**Comment by lemmadev** [comment]
Hello Team, 
Please review the above changes.

**Comment by lemmadev** [comment]
@harpere can we have the changes reviewed on priority please, this has been pending for a couple of weeks now?
We need to close this ASAP, as we have multiple integrations in the queue.
Let us know if there are any further changes required apart from the suggested one to take this to closure.

**Comment by harpere** [comment]
apologize for the delay - lost track of this ticket, and our slack reminders have gone away.

**Pull request merged**
