### PR TITLE
ServerBid Server BidAdapter

### PR DESCRIPTION
**Pull request by jcswart**
Allow S2S configuration with ServerBid.

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change

Add S2S adapter: ServerBidServerBidAdapter.

- contact email of the adapter’s maintainer
    - jcswart@serverbid.com
- [x] official adapter submission

### CODE REVIEW

**Comment by dbemiller** [comment]
hey @jcswart ... thanks for the PR, but we're getting ready to release Prebid 1.0, and stopped accepting PRs for "old style" adapters quite a while ago.

Please update your adapter so that it conforms to the 1.0 standards. http://prebid.org/dev-docs/bidder-adapter-1.html

**Comment by jcswart** [comment]
@dbemiller this is for a new *server to server* adapter. Not a regular bid adapter.

How does it not conform to the new standards? As far as I can tell there is only one other server to server adapter, and that is for prebid. This adapter is compatible with the same style of input.

**Comment by jcswart** [comment]
I've opened https://github.com/prebid/Prebid.js/pull/1819 as it fixes an issue with linting. Otherwise the above comment is in effect.

**Comment by dbemiller** [comment]
@jcswart yes... the prebid-server one is out of compliance too. @snapwich is working on updating it right now.

I definitely didn't realize that this was an s2s adapter. I'm not sure whether that changes anything, with regards to the standards... but will run it by the team/leadership.

**Pull request closed without merging**
