### PR TITLE
Remove do callbacks if needed

### PR DESCRIPTION
**Pull request by kitwestneat**
## Type of change

- [x] Bugfix

## Description of change
A couple bug fixes that were easier to combine into one PR. The first removes the bid parameter to calls to addBidToAuction, since that function doesn't actually accept any parameters. 

The second removes doCallbacksIfNeeded since the calling order with addBidToAuction wasn't standardized, and it seems like it should be. Specifically it seems like the callbacks should always be done after the bid is added to the auction.

### CODE REVIEW

**Comment by protonate** [comment]
@kitwestneat any update here?

**Comment by kitwestneat** [comment]
I reuploaded a fix the same day...do you all need something else from me? I
guess it's no longer able to merge cleanly...

**Comment by mkendall07** [comment]
@kitwestneat 
Can you break out the changes into smaller PR's are try and rebase this? Thanks.

**Comment by kitwestneat** [comment]
ok I'll break them up

**Pull request closed without merging**
