### PR TITLE
ADXCG Bid Adapter: add video & parameter validation & other updates

### PR DESCRIPTION
**Pull request by adxcgcom**
## Type of change
- [x] Bugfix
- [x] Feature
- [x] Code style update (formatting, local variables)

## Description of change
Changed line ending to ";"
Added bidResponse meta tags
Added additional video and banner parameters validation
Moved video parameters from bidder custom to video official properties
Refactoring to prepare for future changes

- contact email of the adapter’s maintainer
- [x] official adapter submission
- info@adxcg.com

### CODE REVIEW

**Review by mmoschovas — CHANGES_REQUESTED** [review]
I am going to test these changes out but just a few notes after a first pass here.

**Comment by mmoschovas** [comment]
@adxcgcom I am trying to test this end to end, but I am receiving a 500 error specifically for video when a banner ad unit is not the first ad unit in the request. I have tried this with just video, native + video, banner + video, and all three mediatypes. I am using the test data in the md, so perhaps it is due to that. I would also suggest possibly updating the md since you require certain video data at the parent level in the ad unit i.e. mimes & protocols

**Comment by adxcgcom** [comment]
@mmoschovas
fixed

**Review by mmoschovas — APPROVED** [review]
Thanks for making these changes. This looks good

**Pull request merged**
