### PR TITLE
Impactify Bid Adapter : add different mediatypes and manage local storage

### PR DESCRIPTION
**Pull request by thomasdseao**
## Type of change

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Handling the parsing of a local storage value denoted by the key "_im_str" and managing more mediatypes.

### CODE REVIEW

**Comment by thomasdseao** [comment]
Linked doc PR : https://github.com/prebid/prebid.github.io/pull/4926

**Review by Fawke — CHANGES_REQUESTED** [review]
Hi @thomasdseao,

`gulp test` command fails. Can you please fix this?
A potential reason for this failure, I don't think you can import function `createEidsArray`.

If you wanna read eids, you can read it off of bidRequest object.

```(javascript)
function getEids(bidRequest) {
  if (deepAccess(bidRequest, 'userIdAsEids')) {
    return bidRequest.userIdAsEids || [];
  }
};
```

**Comment by thomasdseao** [comment]
> Hi @thomasdseao,
> 
> `gulp test` command fails. Can you please fix this? A potential reason for this failure, I don't think you can import function `createEidsArray`.
> 
> If you wanna read eids, you can read it off of bidRequest object.
> 
> ```
> function getEids(bidRequest) {
>   if (deepAccess(bidRequest, 'userIdAsEids')) {
>     return bidRequest.userIdAsEids || [];
>   }
> };
> ```

Hi @Fawke ,
Fixed.

**Comment by Fawke** [comment]
@thomasdseao I still see unit tests are failing. Can you please run `gulp test` and fix the test case? I see one error originating from your test case.

**Comment by thomasdseao** [comment]
@Fawke Is should be fixed now. Thank you.

**Review by Fawke — APPROVED** [review]
LGTM

**Pull request merged**
