### PR TITLE
Add support for deals in Index Exchange adaptor

### PR DESCRIPTION
**Pull request by indexexchange**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change

* Adding support for IX deal bids
* Adding support for sizes in IX configuration
* Adding IX sandbox mode
* Relaxing configuration check
* Using up-to-date IX demand parameters
- [x] official adapter submission

## Other information

This PR depends on the fix for issue #618.
This should be merged in after PR #619

### CODE REVIEW

**Comment by mkendall07** [comment]
Hi @indexexchange 
This is a lot of code change in the PR. I see a debug mode has been added (nice!), any instructions on how to use/test this feature? Any additional things in this PR? How about unit tests?

**Comment by indexexchange** [comment]
@mkendall07 -- we're hoping to get deal support for the IX adapter merged into the upcoming v0.13 release; we can make a separate PR for that feature.  Would that be preferable?

**Comment by protonate** [comment]
@indexexchange I've merged the prerequisite #619 so if you are able to make a separate PR specific to IX adapter deal support, with focused changes and test coverage, or can provide test coverage for all changes here, we should be able to include it in 0.13.0 release.

**Comment by indexexchange** [comment]
> so if you are able to make a separate PR specific to IX adapter deal support

We'll close this PR in favour of a more focused change solely for deal support.

**Pull request closed without merging**
