### PR TITLE
Ras Bid Adapter: support for SlotSequence parameter

### PR DESCRIPTION
**Pull request by wsusrasp**
## Type of change

- [ ] Bugfix
- [X] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

I have added new parameter to the adapter.

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Review by patmmccann — CHANGES_REQUESTED** [review]
Read this off the ad unit please

**Comment by patmmccann** [comment]
Here's an example

https://github.com/prebid/Prebid.js/blob/6f4fb5b78a4bc31a1f84b59ec5b98d4e3bcf0179/modules/ttdBidAdapter.js#L198

**Comment by wsusrasp** [comment]
Hello, I have updated the code to read the data off the adunit. However I seem to have an issue with one of the tests unrelated to the change, updating the branch with the current master did not seem to help. Do you have an idea what is the problem maybe? Thank you

**Comment by ChrisHuie** [comment]
> Hello, I have updated the code to read the data off the adunit. However I seem to have an issue with one of the tests unrelated to the change, updating the branch with the current master did not seem to help. Do you have an idea what is the problem maybe? Thank you

Rerunning CircleCI. There is currently a flaky test that is popping up more often the last several days

**Comment by patmmccann** [comment]
Appears to still not be read off mediatypes.banner.pos

**Comment by wsusrasp** [comment]
@patmmccann It seems I have misunderstood due to naming collision - the pos that I am reading off the bid params is not the same as udnit's pos. The one here is our custom param for determining the position of adunit with the same name if they are embedded multiple times. It is impossible for me to set that parameter elsewhere and mixing it with mediaTypes pos would later yield incorrect results when generating reports, since it takes different values than we expect. How should I proceed in this case?

**Comment by patmmccann** [comment]
interesting; the 'pos' is an extremely well understood field by most rtb participants; perhaps you'll want to reconsider the name to avoid the collision and the resulting confusion?

**Comment by wsusrasp** [comment]
Sadly we are already using this value in multiple applications on our side and refactoring it will not be easy

**Comment by patmmccann** [comment]
How about you copy it to pos on the endpoint but your publisher facing configuration has a better choice of name?

**Comment by patmmccann** [comment]
Sequence seems like a candidate parameter name

**Comment by wsusrasp** [comment]
That sounds reasonable, I'll update the PR shortly. Thanks

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
please also copy your .md changes over to the docs repo

**Pull request merged**
