### PR TITLE
NoBid Bid Adapter: Support for GPP 1.1

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support for GPP string and GPP applicable sections for Bid and user sync.

## Other information
https://github.com/prebid/prebid.github.io/pull/4771

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@redaguermas can you please remove the changes to the package-lock file from this pr

**Comment by redaguermas** [comment]
@ChrisHuie,
The build failed because it's missing the package-lock file

**Comment by ChrisHuie** [comment]
@redaguermas yes. Looks like you removed the file. I meant to undo the changes. Sorry.  I probably should have said untrack the changes to the package-lock instead. Just add back in the current one on master and should we should be good.

**Comment by redaguermas** [comment]
@ChrisHuie , do you know what the issue is?

**Comment by redaguermas** [comment]
@ChrisHuie 
Even when I run the tests from my local it fails with an error "Username is required". This is the command I am running:
gulp test --browserstack --nolintfix

Please advise. Thank you

**Comment by redaguermas** [comment]
Hello @ChrisHuie ,
The error cleared after we merged the master branch. Please review.
Thank you

**Comment by redaguermas** [comment]
Hello @ChrisHuie 
Any update on this PR?

**Comment by redaguermas** [comment]
@ChrisHuie @dangoldin @naffis @bborn ,
Any update on this PR? I am not seeing any comments. We want to be able to unblock this PR to work on the next feature. Please look into it.

THanks

**Review by ChrisHuie — APPROVED** [review]

**Comment by redaguermas** [comment]
Thank you @ChrisHuie

**Pull request merged**
