### PR TITLE
Add GVLID RichaudienceAdapter

### PR DESCRIPTION
**Pull request by richaudience**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ x ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Add GVLID in RichaudienceAdapter

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by bretg** [comment]
@richaudience - need to remove package-lock.json from this PR. Thanks.

**Comment by richaudience** [comment]
Hey @bretg 
I have already applied the change-
Cheers

**Review by Fawke — COMMENTED** [review]
@richaudience,

This looks good. I saw the docs for your adapter on Prebid.org, you can make it more descriptive by adding a few more things. For example,
```
gdpr_supported: true
gvl_id: 100
``` 

You can refer to the docs of some other adapters like appnexus or rubicon and see other meta data that you can add. (There are a lot of options, the more you add to the docs, easier for your users to see what features you provide)

**Comment by bretg** [comment]
Specifically this file -- https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/richaudience.md

**Comment by richaudience** [comment]
Hey guys
I have already uploaded the modification in prebid.io.
https://github.com/prebid/prebid.github.io/pull/2550
Cheers

**Review by Fawke — APPROVED** [review]
LGTM

**Pull request merged**
