### PR TITLE
Add .circleci/config.yml

### PR DESCRIPTION
**Pull request by ericrenebrown**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by ericrenebrown** [comment]
params: {
    accountId: '123',
    partnerId: '123',
    storage: true
  }

**Comment by jsnellbaker** [comment]
@ericrenebrown Is this PR accurate (ie do you have the right set of changes in)?  If so, explain the reason for the changes to our circleci setup?

**Comment by ericrenebrown** [comment]
> @ericrenebrown Is this PR accurate (ie do you have the right set of changes in)? If so, can you please explain the reason for the changes to our circleci setup?

Weird. I simply signed up to Circle CI. I must have clicked the wrong thing when verifying my other UserID changes. This can be ignored/rejected

**Comment by jsnellbaker** [comment]
Hi @ericrenebrown Thanks for confirming.  I'll close this PR then.

**Pull request closed without merging**
