### PR TITLE
Sharethrough Adapter - set bidderCode on invalid bid

### PR DESCRIPTION
**Pull request by jchau87**
## Type of change

- [x] Bugfix
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)

## Description of change
- Set bidderCode on bid object for invalid bids
- Don't use exception handling for control flow when there are no creatives

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
jchau@sharethrough.com
- [x] official adapter submission

### CODE REVIEW

**Comment by snapwich** [comment]
LGTM 👍

**Comment by dbemiller** [comment]
@jchau87 Please fix the merge conflicts, and update for compatibility with #1177

**Comment by mkendall07** [comment]
@jchau87 still waiting to resolve conflicts to merge this

**Comment by jchau87** [comment]
Sharethrough adapter moved into `/modules` directory

**Pull request merged**
