### PR TITLE
Windtalker adapter on a clean branch

### PR DESCRIPTION
**Pull request by degroat**
## Type of change

- [ X] New bidder adapter

## Description of change
Prebid adapter for Windtalker.

- test parameters for validating bids
```
{
  bidder: 'windtalker',
  params: {
           "pubId":"187046"
           ,"siteId":"10"
           ,"size":"300x250"
           ,"placementId":"456"
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: corbin@windtalker.io
- [X ] official adapter submission

### CODE REVIEW

**Comment by degroat** [comment]
Is it possible that this error is caused because this adapter doesn't support 3.0?  Should I resubmit the pull request and compare it to the 2.X branch?

**Comment by jsnellbaker** [comment]
@degroat The error reported in the circleci build is due to your use of the `logError` method with how you imported the util.js file.  If you change it to `utils.logError()` - it should work.

In regards to 3.x support, you mainly need to ensure your endpoint is hardcoded to `https` (which it doesn't appear to be currently) and ensure you aren't using deprecated functions from the utils file.  I see a few references that need to be updated; you can try to use the values herehttp://prebid.org/dev-docs/bidder-adaptor.html#referrers or create your own functions if you need something else.

Can you try to make these updates?  You'll eventually need to get your adapter 3.x compliant to stay in the repo, so it's best to work this out now.

**Comment by degroat** [comment]
I

> @degroat The error reported in the circleci build is due to your use of the `logError` method with how you imported the util.js file. If you change it to `utils.logError()` - it should work.
> 
> In regards to 3.x support, you mainly need to ensure your endpoint is hardcoded to `https` (which it doesn't appear to be currently) and ensure you aren't using deprecated functions from the utils file. I see a few references that need to be updated; you can try to use the values herehttp://prebid.org/dev-docs/bidder-adaptor.html#referrers or create your own functions if you need something else.
> 
> Can you try to make these updates? You'll eventually need to get your adapter 3.x compliant to stay in the repo, so it's best to work this out now.

The reason we aren't going for 3.x support right now is because we are using Platform.io as our technology partner and recommended that we simply copy their adapter, make the minor modifications and then submit.  When they add 3.x support to heir adapter, we're going to upgrade ours.

That said, I made the change to the logError method and now it appears to be blowing up the deprecated methods.   If my goal right now is to get in the 2.X branch, do I just submit a pull request vs. that legacy branch?

**Comment by sumit116** [comment]
> I
> 
> > @degroat The error reported in the circleci build is due to your use of the `logError` method with how you imported the util.js file. If you change it to `utils.logError()` - it should work.
> > In regards to 3.x support, you mainly need to ensure your endpoint is hardcoded to `https` (which it doesn't appear to be currently) and ensure you aren't using deprecated functions from the utils file. I see a few references that need to be updated; you can try to use the values herehttp://prebid.org/dev-docs/bidder-adaptor.html#referrers or create your own functions if you need something else.
> > Can you try to make these updates? You'll eventually need to get your adapter 3.x compliant to stay in the repo, so it's best to work this out now.
> 
> The reason we aren't going for 3.x support right now is because we are using Platform.io as our technology partner and recommended that we simply copy their adapter, make the minor modifications and then submit. When they add 3.x support to heir adapter, we're going to upgrade ours.
> 
> That said, I made the change to the logError method and now it appears to be blowing up the deprecated methods. If my goal right now is to get in the 2.X branch, do I just submit a pull request vs. that legacy branch?

Hi @degroat ,

I would suggest you to wait for your technology partner adapter to change to 3.0 and then update your PR instead of raising it against the legacy branch. The reason being that we are coming close to our threshold of keeping the legacy branch and may not support it for much longer.

**Comment by degroat** [comment]
@sumit116 If we have publishers that are using 2.X... and I need it to be available to download with 2.X... don't I need to submit it to both 2.x and 3.x?

**Pull request closed without merging**
