### PR TITLE
No bid version 1.2.9

### PR DESCRIPTION
**Pull request by redaguermas**
## Type of change
- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support for Extended User IDs.

### CODE REVIEW

**Review by harpere — APPROVED** [review]

**Comment by harpere** [comment]
@redaguermas do you want to open a docs PR?  https://github.com/prebid/prebid.github.io/pulls

**Comment by redaguermas** [comment]
Can you please see the docs PR here: https://github.com/prebid/prebid.github.io/pull/2452/

**Comment by redaguermas** [comment]
@harpere , Can you please merge these changes?

**Comment by redaguermas** [comment]
Hello @harpere can you please take a look at this PR. It was never merged.

**Comment by redaguermas** [comment]
Hello @robertrmartinez ,
Can you please take a look at this PR. It was never merged.

**Pull request merged**
