### PR TITLE
IX Bid Adapter: add detected page url to ixdiag

### PR DESCRIPTION
**Pull request by shahinrahbariasl**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [x] Other

## Description of change

- Adding internal logging for detected page URL
- No functional change for users

### CODE REVIEW

**Comment by patmmccann** [comment]
This is a rules violation, you have to use our methods

**Comment by patmmccann** [comment]
see https://github.com/prebid/Prebid.js/issues/5637#issuecomment-1116554262

**Comment by patmmccann** [comment]
actually we are still allowing changes on this until prebid 7, eg https://github.com/prebid/Prebid.js/pull/8391

**Review by patmmccann — APPROVED** [review]

**Comment by shahinrahbariasl** [comment]
@patmmccann thank you! Will make a note of that.

**Pull request merged**
