### PR TITLE
added adapters for gjirafa and malltv

### PR DESCRIPTION
**Pull request by codewiz14**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
- gjirafaBidAdapter
```
{
  bidder: 'gjirafa',
  params: {
    propertyId: '105227',
    placementId: '846841'
  }
}
```
- malltvBidAdapter
```
{
  bidder: 'malltv',
  params: {
    propertyId: '105135',
    placementId: '846835'
  }
}
```

- contact: drilon@gjirafa.com
- [x] official adapter submission

### CODE REVIEW

**Comment by bretg** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/2200

**Comment by GLStephen** [comment]
@codewiz14 I'm looking at this and things generally look good, but your endpoint is refusing test connections. We need 100% fill sample bid params so we can see bids to verify adapters and so that publishers can use it to verify their own builds and integrations work.

This is what I'm seeing:

```
Access to XMLHttpRequest at 'https://central.mall.tv/bid' from origin 'http://127.0.0.1:9999' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
VM378:1 POST https://central.mall.tv/bid net::ERR_FAILED
````

I've tried both the params here and in your doc PR and neither is returning bids.

**Comment by codewiz14** [comment]
Hi @GLStephen, it was configured to work only for `localhost:9999`, we just updated the CORS policy to allow on `127.0.01:9999` as well.
Everything should work with params in our docs for both adapters.

**Comment by GLStephen** [comment]
@codewiz14 the gjirafa bidder looks good, but the malltv bidder is receiving an error here:

```
  if (!hasValidKeys()) {
    logError(errorMessage(`Bidder ${bid.bidderCode} is missing required params. Check http://prebid.org/dev-docs/bidder-adapter-1.html for list of params.`));
    return false;
  }
```

The error is:

```
ERROR: Invalid bid from malltv. Ignoring bid: Bidder malltv is missing required params. Check http://prebid.org/dev-docs/bidder-adapter-1.html for list of params.
```

I suspect a required parameter may have changed in V4.

**Comment by codewiz14** [comment]
@GLStephen the issue was on interpret response when there is no bid, so we just updated `interpretResponse` to return an empty array when there is no bid.

**Comment by GLStephen** [comment]
@codewiz14 I missed the window for the release today, but this will be in the next release

**Pull request merged**
