### PR TITLE
ANTS Programmatic adapter

### PR DESCRIPTION
**Pull request by ANTSProgrammatic**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: 'ants',
  params: {
      zoneId: String, // id provided by ANTS
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer: support@antsprogrammatic.com
- [x] official adapter submission

### CODE REVIEW

**Comment by mkendall07** [comment]
@ANTSProgrammatic please add unit tests.

**Comment by ANTSProgrammatic** [comment]
@mkendall07 I'm done, can you check it

**Comment by protonate** [comment]
@ANTSProgrammatic any update on this?

**Comment by ANTSProgrammatic** [comment]
@protonate we are processing for fix "Adapters require at least 80% coverage", any suggest for fix kindly let me know

**Comment by ANTSProgrammatic** [comment]
Updated for adapters require at least 80% coverage: https://github.com/prebid/Prebid.js/blob/master/CONTRIBUTING.md

**Comment by ANTSProgrammatic** [comment]
@snapwich we have change this with "Adapters require at least 80% coverage: " https://github.com/prebid/Prebid.js/blob/master/CONTRIBUTING.md and looking forward to hearing from you soon

**Comment by mkendall07** [comment]
@snapwich 
this needs re-review.

**Comment by mkendall07** [comment]
@ANTSProgrammatic 
We have a new bidder adapter interface now. Please follow instructions here http://prebid.org/dev-docs/prebid-1.0-API.html to update the adapter to meet our 1.0 requirements. Thanks

**Comment by jaiminpanchal27** [comment]
@ANTSProgrammatic Prebid 1.0 is released and it does not support old pattern now.
We have a new bidder adapter interface now. Please follow instructions here http://prebid.org/dev-docs/prebid-1.0-API.html to update the adapter to meet our 1.0 requirements.

**Pull request closed without merging**
