### PR TITLE
TTD Bid Adapter : use topmost location when available

### PR DESCRIPTION
**Pull request by gielow**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

### CODE REVIEW

**Comment by gielow** [comment]
Use `topmostlocation` when available, or else use `page`.
Similar change: https://github.com/prebid/Prebid.js/pull/9152

**Comment by patmmccann** [comment]
Did #9241 solve for you

**Comment by gielow** [comment]
> 

I will add a different test to `ttdBidAdapter_spec.js` to confirm and update this PR.

**Comment by gielow** [comment]
> Did #9241 solve for you

@patmmccann add a regression test that passes with the latest changes.
Created a new PR and will close this one. Thank you.

https://github.com/prebid/Prebid.js/pull/9300

**Pull request closed without merging**
