### PR TITLE
Criteo Bid Adapter: add comment to explain how to remove dependency on RSA validation lib

### PR DESCRIPTION
**Pull request by leonardlabat**
- [X] Code style update (formatting, local variables)

## Description of change
This was asked by @patmmccann.
The goal is to explain for a publisher which won't use our fastbid feature, how to remove the dependency on the RSA validation lib (and thus reduce the generated bundle file).

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@leonardlabat it looks like this pr may have been pulled last week when we had a rogue IE character and some a few other tests we had to clean up. Pulling recent commits should fix errors on CircleCI

**Comment by leonardlabat** [comment]
Hello @ChrisHuie 

I've created my commit based on prebid-5.0 branch (as my change targets PB5 version). And it seems that prebid-5.0 has not been updated since 8 days. So I guess, it may have not the changes you mentionned here.
So, I'm not sure what I should do 🤔

**Comment by ChrisHuie** [comment]
@leonardlabat Sorry. I missed this was on the 5.0 branch! Ignore what I just said. lol. 
Yeah. I haven't done anything on the 5.0 branch this week or last week so not too sure on these test failures. I can dig into recent 5.0 commits to see if there are any flaky tests I run into.

**Comment by patmmccann** [comment]
@leonardlabat this is extremely helpful, thank you! Would it be possible to make it a build time flag, similar to https://github.com/prebid/Prebid.js/pull/6016 ?

**Comment by allanjun** [comment]
hi @patmmccann we are actually struggling to make it work on webpack. We have also seen related discussions on  https://github.com/prebid/Prebid.js/pull/6079 and https://github.com/prebid/Prebid.js/issues/6361 which cover similar needs, we can certainly revisit this once these two discussions are solved, would that work ?

**Comment by patmmccann** [comment]
yes, good to know, ty

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
