### PR TITLE
Emit event when setTargetingForGPTAsync is called

### PR DESCRIPTION
**Pull request by itayo155**
## Type of change
- [x] Feature

## Description of change
Emit a new event ('setTargeting') when setTargetingForGPTAsync is called. This indicates that all bids have been collected and actually sent away. 
For reference regarding why this is needed and intended use, please see issue #858. 

## Other information
Original issue: https://github.com/prebid/Prebid.js/issues/858

### CODE REVIEW

**Comment by itayo155** [comment]
Following up - any comments, or thoughts when it could be merged?

**Comment by mkendall07** [comment]
@itayo155 
can you rebase off master to resolve conflicts?

**Comment by itayo155** [comment]
Sure, done. Please let me know if there are any other comments.

**Comment by jaiminpanchal27** [comment]
@itayo155 
I don't think we should add this "SET_TARGETING" event for 2 reasons
1) We will be adding another targeting function for Appnexus adserver and maybe in future some more. So we should not be emitting this event from all the other public functions.
2) It is very similar to AUCTION_END event. Hence if its unreliable, we should fix that instead of adding new similar event.

**Comment by itayo155** [comment]
@jaiminpanchal27 
OK. If it is agreed that the AUCTION_END event should be emitted when bidding ends (i.e. when additional bids will not participate in current auction anymore), I suggest to close this PR and open a new one, for "making the AUCTION_END more accurate" or something like that.

However, given the way things are usually set-up by publishers, I see only two ways of implementing this change:
1. Hook the individual setTargeting functions (e.g. for DFP, AN, etc.), similarly to the way its done in the current PR. If there are multiple functions expected, this can be done by calling a single function which would emit the event.
2. Force a change in the way publishers interact with Prebid, e.g. by changing the API.

The reason is that setTargetging is usually being called directly from publisher's code, and more specifically - this happens when the auction times out at a time arbitrarily selected by publisher.
E.g. (adapted from a live implementation, comments are mine):
```
//start the auction
  pbjs.que.push(function() {
      pbjs.addAdUnits(adUnits);
      //...
      pbjs.requestBids({
          bidsBackHandler: sendAdserverRequest
      });

//set a timeout - arbitrarily selected by publisher
 setTimeout(function() {
      sendAdserverRequest();
  }, some_publisher_set_timeout);

//end the auction - note the setTargetingForGPTAsync is being called directly; and only at this point the auction actually ends
  function sendAdserverRequest() {
    //...      
        googletag.cmd.push(function() {
          pbjs.que.push(function() {
              //auction ends now, and we'd like the AUCTION_END event to somehow be emitted
              pbjs.setTargetingForGPTAsync();
              //...
          });
      });
  }
```

Would be happy for additional ideas for how to implement this.
Out of the two options above, I personally find (1) preferable.

Would be happy to hear your thoughts.

**Comment by mkendall07** [comment]
@itayo155 
Thanks for the PR. We'll review internally and get back to you.
Could you also send me an email directly? My email is in my profile. Thanks

**Comment by jaiminpanchal27** [comment]
@itayo155 
Looks good. Merging the PR.

**Pull request merged**
