### PR TITLE
Interactive Offers Bid Adapter: added data to the final response object

### PR DESCRIPTION
**Pull request by IOTiagoFaria**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@IOTiagoFaria it appears you are overwriting your entire current bid adapter file? I haven't compared the two files but is this intentional?

**Comment by IOTiagoFaria** [comment]
@ChrisHuie The only changes where made to the "parseResponseOpenRTBToPrebidjs" function.
Not sure why it shows as a new  file

**Comment by patmmccann** [comment]
Includes change for #6466 thank you

**Comment by IOTiagoFaria** [comment]
@patmmccann are these the changes ou requested? https://github.com/prebid/Prebid.js/pull/6648/commits/e1d7aa976ed1ae0ed2427f789be99f3ac61eed6a

**Comment by ChrisHuie** [comment]
@IOTiagoFaria can you please pull in recent merges so this pr doesn't view all these changes as new added files 🙏 Not sure what happened but hoping that fixes the git additions to sync

**Comment by patmmccann** [comment]
> @patmmccann are these the changes you requested? [e1d7aa9](https://github.com/prebid/Prebid.js/commit/e1d7aa976ed1ae0ed2427f789be99f3ac61eed6a)

Thanks for adding advertiserDomains, you have been removed from the list of bidders who do not support adomain.

**Comment by IOTiagoFaria** [comment]
@ChrisHuie what is the status of this review?

**Comment by patmmccann** [comment]
> @ChrisHuie what is the status of this review?

You have 37 files changed in this PR.

It's important to only submit your changes.

**Comment by IOTiagoFaria** [comment]
My mistake, do you think it will be easier/faster if this PR got cancelled and I create a new one with the fork fully updated?

**Comment by patmmccann** [comment]
That's up to you; it's no trouble if you want to close and resubmit or prefer to fix this one

**Comment by IOTiagoFaria** [comment]
I think its better for a new PR to be created, I don't want to mess this one even more...

**Comment by IOTiagoFaria** [comment]
new PR created https://github.com/prebid/Prebid.js/pull/6680

**Pull request closed without merging**
