### PR TITLE
Yandex Bid Adapter: add adServerCurrency support

### PR DESCRIPTION
**Pull request by Saveliev**
## Type of change

- [x] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
* added adServerCurrency support
* fixed auction price values for nurl

### CODE REVIEW

**Review by lksharma — CHANGES_REQUESTED** [review]
@Saveliev, overall the changes look good. Could you also update the unit tests to reflect these changes?

**Comment by Saveliev** [comment]
/fixed
@lksharma added unit tests for these changes. Please take a look

**Review by lksharma — APPROVED** [review]
LGTM

**Pull request merged**
