### PR TITLE
Vdoai adapter update - Added video mediaType support

### PR DESCRIPTION
**Pull request by cpuBird**
## Type of change

- [ ] Bugfix
- [x ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Added support for video mediatype in vdo.ai bidder adapter

### CODE REVIEW

**Comment by bretg** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/2496

**Comment by cpuBird** [comment]
Hi, is there any update on this?

**Review by bretg — CHANGES_REQUESTED** [review]
Looks fine except needs a unit test to make sure that when the response is video, that bidResponse.vastXml is set.

**Comment by GLStephen** [comment]
@cpuBird sorry for the delay - please make the change that @bretg requested and I'll review ASAP

**Comment by cpuBird** [comment]
Hi, I have added the unit test. Please review and suggest.

**Review by bretg — APPROVED** [review]
I see the unit test. Will let @GLStephen judge it's completeness.

**Pull request merged**
