### PR TITLE
[ParrableIdSystem] Accept list of partners as an array or string

### PR DESCRIPTION
**Pull request by icflournoy**
## Type of change

- [x] Feature

## Description of change

This changes introduces a new parameter (`partners`) to our module that supersedes the old `partner` string-list while still preserving the old behavior. While the old list accepted a comma-separated string of partner IDs we wanted to clean up the parameter name (make it plural) and have it accept a proper array for simplicity. Both `partner` and `partners` now operate the same way and can accept an array, or a comma-separated string.

Docs: https://github.com/prebid/prebid.github.io/pull/2688

### CODE REVIEW

**Comment by icflournoy** [comment]
@victorigualada can you take a look at why the timezone filter tests are failing on this unrelated PR? I incorporated the base64 fix from https://github.com/prebid/Prebid.js/pull/6268 in our other test that decodes the data parameter, which solved the first set of failing tests.

**Review by harpere — CHANGES_REQUESTED** [review]
tests are failing.

**Comment by icflournoy** [comment]
@harpere we've fixed the tests relevant to our module, but it appears that some unrelated tests are now causing the build to fail:

```
  pubmatic analytics adapter
    when handling events
      ✗ Logger: best case + win tracker
	Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

      ✗ bidCpmAdjustment: USD: Logger: best case + win tracker
	Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Review by harpere — APPROVED** [review]
reran tests and they're passing now.

**Pull request merged**
