### PR TITLE
Iqm Bid Adapter: add new bid adapter

### PR DESCRIPTION
**Pull request by Params10**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added new IQM bid adapter

- test parameters for validating bids
```
{
  bidder: 'iqm',
  params: {
             publisherId: 'df5fd732-c5f3-11e7-abc4-cec278b6b50a',
            placementId: 23451,
            bidfloor: 0.50,
            geo:{
                      country:'USA'
           },
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer :hbteam@iqm.com
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/3069/

### CODE REVIEW

**Comment by Params10** [comment]
Hello @ChrisHuie can you help us out with why this adapter tests are failing at browser stack testing as it works fine on local setup.

**Comment by ChrisHuie** [comment]
@Params10 we have a flaky ie test that was bad for a few days. If you pull in recent merges there is a fix in there that helps with it.

**Comment by Rothalack** [comment]
I've noticed a few things from trying to test.

There appears to be a change to package-lock.json, that may be my fault from testing, but please double check that you did not change the package settings on your end.

In testing, I'm getting a 400 Bad Request response from POST https://pdb.bids.iqm.com. I think I have the bidder set up properly so I would not expect that response. Let me know if you have any testing placement/publisher id to test with.

I see in your documentation PR https://github.com/prebid/prebid.github.io/pull/3069 you have the geo/country setting in your example, but it's not listed in your params documentation. I would either update your documentation to show that geo/country is a param, or remove it from the example bidder to avoid any confusion.

**Comment by Rothalack** [comment]
And merging in master should help with the Circleci test.

**Comment by Params10** [comment]
Hello, any updates for the pull request ?

**Comment by Rothalack** [comment]
Hey @Params10 . The merge with master fixed the package json issue and testing issues, so that's good to go.

That just leaves my question about your documentation regarding geo. I see in your test params here, geo is included, in your testing examples in your documentation it shows geo, then in your list of params in documentation, geo is not listed. I think you should either update your list of available params in documentation to include geo, or remove geo from your test examples. Without clearing that up, it will likely confuse users.

**Comment by Rothalack** [comment]
I see your update to your docs, this is good to go!

**Pull request merged**
