### PR TITLE
Reinstate Playground XYZ adapter with v3 support

### PR DESCRIPTION
**Pull request by monofonik**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other 

## Description of change

This pull request reinstates the Playground XYZ bid adapter with minor changes to make it compliant with Prebid v3.

I haven't submitted this as a "New bidder adapter" as our test parameters / dev docs remain unchanged.

### CODE REVIEW

**Comment by monofonik** [comment]
Note that the failing CircleCI tests appear to be unrelated to this PR

**Comment by monofonik** [comment]
Thanks @Fawke I've addressed the erroneous change to `appnexusBidAdapter_spec.js` and also corrected our test params with the correct ad unit code.

Can you try the hello world test again? Couple of notes:

- depending on your geo you may have to increase `PREBID_TIMEOUT`
- our bidder wont respond with demand unless it detects a valid hostname, so you may need to e.g. update your hosts file with a dummy domain name pointing to your local machine (see screeny below)

image

**Comment by Fawke** [comment]
Hi @monofonik,

Thanks for updating the test parameters, now, am able to get a bid back. While checking the response headers, I noticed that the **content-encoding** is not set to **gzip**. We require all our bid adapters to compress the their response before sending it to the client for a better performanceI

Is it possible to make this change and send the response gzipped?

**Comment by monofonik** [comment]
Hi @Fawke no problem - confirming our bid responses are now gzipped.

**Comment by Fawke** [comment]
@monofonik Thanks for making the change.

**Pull request merged**
