### PR TITLE
Added US Privacy support for TheMediaGrid Bid Adapter

### PR DESCRIPTION
**Pull request by TheMediaGrid**
## Type of change

- [x] Feature

## Description of change

Added US Privacy support in TheMediaGrid Bid Adapter to send it in bid request and in sync pixel as us_privacy parameter

- grid-tech@themediagrid.com
- [x] official adapter submission

- A link to a PR on the docs repo https://github.com/prebid/prebid.github.io/pull/1693

### CODE REVIEW

**Comment by bretg** [comment]
@TheMediaGrid - please consider applying these same changes against the 2.44.x-legacy branch

**Comment by bretg** [comment]
@TheMediaGrid - sorry, but your fork is out of date and we cannot get the unit tests to pass. Please rebase your fork from a more modern version of PBJS.

I attempted to do this for you, but found that your master branch is from a **long** time back. Apparently other reviewers ran into this, as your unit tests haven't succeeded the last several PRs. Since the tests work locally and we understand that CCPA support is important, I'll make that exception too, but not until extracting your promise to rebase first thing in the new year.

**Comment by bretg** [comment]
Ok - I'm going to merge this, but **please** re-base your fork for future PRs.

**Comment by TheMediaGrid** [comment]
Thank you, our forked repository is already all right

**Pull request merged**
