### PR TITLE
ShowHeroes Bid Adapter: add new endpoint

### PR DESCRIPTION
**Pull request by ChrisHuie**
Resubmit of #8758 to kick off CircleCi @Rothalack @vadim-mazzherin

### CODE REVIEW

**Comment by Rothalack** [comment]
Hey @vadim-mazzherin sorry, I should have noticed this earlier. Does this include new params that are not documented on your bidder reference page?

unitId, stage, contentPageUrl

If those are new params, go ahead and get a PR up to add those to your bidder reference.

This is what needs to be updated
https://docs.prebid.org/dev-docs/bidders/showheroes-bs.html

And the PR should go here https://github.com/prebid/prebid.github.io/pulls

**Comment by vadim-mazzherin** [comment]
@ChrisHuie @Rothalack Thanks very much!

**Comment by vadim-mazzherin** [comment]
@Rothalack, I have updated the documentation. 
stage and contentPageUrl parameters aren't public

**Review by Rothalack — APPROVED** [review]
This should be good to go, working in testing.

**Pull request merged**
