### PR TITLE
Prebid core: accept and propagate AD_RENDER_FAILED / AD_RENDER_SUCCEEDED events from cross-origin ads

### PR DESCRIPTION
**Pull request by dgirardi**
## Type of change

- [x] Bugfix
- [x] Does this change affect user-facing APIs or examples documented on http://prebid.org?

## Description of change
﻿This adds a new type of cross-origin message ('Prebid Event') to allow PUC and other cross-origin renderings to correctly report rendering result, and generates the appropriate events.

Addresses https://github.com/prebid/Prebid.js/issues/7702

Related PUC changes: https://github.com/prebid/prebid-universal-creative/pull/152
Documentation changes https://github.com/prebid/prebid.github.io/pull/3508

### CODE REVIEW

**Comment by dgirardi** [comment]
To the reviewers (@jsnellbaker, @robertrmartinez) I am unable to get the example in `integrationExamples/x-domain/creative.html` to work, with or without of my changes. Since PUC is working for me and I have spent too many hours on it already I'm marking this ready for review - but beware that may or may not be broken.

**Comment by jsnellbaker** [comment]
@patmmccann I think you mentioned during a previous meeting that you used the `x-domain/creative.html` example for your sites.  If so, are there some test pages you can provide that we could use for this PR?  Thanks.

**Comment by dgirardi** [comment]
Figured out the x-domain example, and changes in this PR appear to work as intended: https://s3.us-east-1.amazonaws.com/files.prebid.org/test/dgirardi/x-domain/2/custom_safeframe_render_update.html

I believe there is some issue with `postMessage` failing silently when crossing betwen http and https (in local testing), which for some reason does not happen with PUC.

**Review by jsnellbaker — APPROVED** [review]
I believe this looks good.   Thanks for putting it together.

**Review by robertrmartinez — APPROVED** [review]

**Comment by patmmccann** [comment]
Lgtm

**Review by osazos — COMMENTED** [review]
Thanks for your work, please take a look at my comments and let me know. By the way this seems good.

**Comment by dgirardi** [comment]
@osazos all good points, PR updated.

**Pull request merged**
