### PR TITLE
Rise Bid Adapter: Added support for banner & gpid

### PR DESCRIPTION
**Pull request by OronW**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support for banner & gpid

- test parameters for validating bids
```
{
                        bidder: 'rise',
                        params: {
                            org: '6006bd365f7d48000117ecc9',
                            testMode: true,
                        }
                    }
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by noamtzu** [comment]
Hi guys, can we assign this? Thanks a lot

**Comment by noamtzu** [comment]
Hi guys, we need your help to push it forward 🙏🏻  please assist

**Comment by musikele** [comment]
Hi @noamtzu , is there a test ad I can use to show a banner?

**Comment by noamtzu** [comment]
@musikele yes there is. any problem on your side? for me it's working just fine

**Comment by musikele** [comment]
@noamtzu , I mean, the readme.md I see only contains a video ad unit, there's no reference in the docs about the riseBidAdapter supporting also banner. 
I did my review and it's working fine, even though I never received a valid bid. The `test: true` parameter seems to have no effect. 

Let me know if you want to update the .md file otherwise I'll approve it as is.

**Comment by noamtzu** [comment]
@musikele My apologies for the mistake.
here is the update docs:  
https://github.com/prebid/prebid.github.io/pull/3609

regarding the test param his name is testMode and not test.
for example:
```
{
          bidder: 'rise',
          params: {
              org: '6006bd365f7d48000117ecc9',
              testMode: true,
          }
}
```

**Review by musikele — APPROVED** [review]
LGTM

**Comment by noamtzu** [comment]
@musikele Thanks a lot

**Pull request merged**
