### PR TITLE
Read floor data in analytic + support for Criteo Id

### PR DESCRIPTION
**Pull request by bjorn-lw**
## Type of change
- [ ] Feature

## Description of change
Support in analytics for reading floor data, both from Prebid's floors module and from Livewrapped's wrapper.

Note that adapter support for Prebid's floor module will follow at a later stage.

Added support for Criteo's id module

### CODE REVIEW

**Comment by musikele** [comment]
Dear @bjorn-lw, this PR contains two logical and separate things (analytics adapter and bidder adapter), so please can you split it in two separate MRs ? Thank you.

**Comment by bjorn-lw** [comment]
> Dear @bjorn-lw, this PR contains two logical and separate things (analytics adapter and bidder adapter), so please can you split it in two separate MRs ? Thank you.

@musikele I'd rather not. They belong together and we need to have both them both merged at once.

**Comment by musikele** [comment]
In general, there is a rule that prohibits to put two "different" things in the same PR. You may have seen it when you try to open a new Issue; or in the file PR_REVIEW.md . 
Anyway, I understand your problem and for this time I'll try to review the PR as is. 

Can you update the file `livewrapperBidAdapter.md` with test parameters that return a test ad? 
At the moment I see from livewrapper Bid adapter this 400 response: 

```
 {"errorMessage":"Guru Meditation. Error at log: 11/30/2020 4:55:48 PM"}
```

**Comment by bjorn-lw** [comment]
I appreciate you're being thorough. 

I could remove the Criteo support if you wish, but would be great if you let it pass this time. Since you sometimes have weeks before MRs are getting attention I was hoping I could let this one slip in as well since it's really small, but I won't next time.

I have updated the example.

**Comment by musikele** [comment]
I see the file `livewrappedAnalyticsAdapter.md` is missing. It should contain some basic info about how to install and use it. See examples from other adapters. A good description of various options is appreciated; also, if there are any test parameters that can be used, don't forget to add them.

**Comment by bjorn-lw** [comment]
@musikele Look, as I said, I really appreciate your thoroughness, but this is not a new adapter or analytics adapter submission. It's some changes to existing adapters that have existed in Prebid.js for quite a long time now.

The analytics adapter can only be used in agreement with Livewrapped AB. There are no test id's that can you can use unless you have an account with us.

However, there are unit tests for the adapter.

Thank you.

**Comment by musikele** [comment]
@bjorn-lw , 
this is an open source library and I, as a reviewer, have to go through a list of rules that all contributors and reviewers  follow. 
I only ask to add a simple .md file that explains what this module is, how to enable, and a general description of the parameters used. 
I can say that the code looks good, but I still have to test on my end. We recently had cases of modules that broke other modules, or prevented the auction to happen under special circumstances. We do not want to repeat that... 
So please, add this file, and tomorrow morning I'll do a final test to the analytics module and hopefully merge it.

**Comment by bjorn-lw** [comment]
@musikele OK, it's added now. Thank you for your input.

**Review by musikele — APPROVED** [review]
LGTM

**Pull request merged**
