### PR TITLE
Seedtag Bid Adapter: add support for a new type of placement

### PR DESCRIPTION
**Pull request by lauramorillo**
## Type of change
- Feature

## Description of change
We have implemented support for a new type of placement (inArticle) and we needed to start measuring events on bid won to measure any possible discrepancy rendering on that new placement.

- contact email of the adapter’s maintainer: laura@seedtag.com

### CODE REVIEW

**Comment by ChrisHuie** [comment]
@lauramorillo it looks like our CircleCI tests didn't automatically run on this pr. By chance are you following your fork on CircleCI instead of the main Prebid source repo?

**Comment by lauramorillo** [comment]
> @lauramorillo it looks like our CircleCI tests didn't automatically run on this pr. By chance are you following your fork on CircleCI instead of the main Prebid source repo?

I don't know what's the issue with CircleCI, any suggestion to fix it?

**Comment by lauramorillo** [comment]
> @lauramorillo it looks like our CircleCI tests didn't automatically run on this pr. By chance are you following your fork on CircleCI instead of the main Prebid source repo?

Fixed! Some commits where missing from master :)

**Comment by ChrisHuie** [comment]
Awesome @lauramorillo :) Thanks

**Comment by Rothalack** [comment]
Hey @lauramorillo , everything is looking good and working. The only thing left I can think of would be to add the new inArticle type to the list here: https://docs.prebid.org/dev-docs/bidders.html#seedtag

I would update the Media Types section and the description for Placement.

That would be in this file. https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/seedtag.md

**Comment by lauramorillo** [comment]
@Rothalack done! I have created the PR https://github.com/prebid/prebid.github.io/pull/2740 for that! We have not changed anything about the Media Types that we support, only a new placement that will continue working with the same supported types, so I only updated that part. Thank you!

**Comment by Rothalack** [comment]
Awesome, good to go!

**Pull request merged**
