### PR TITLE
Upgrade Inskin adapter to Prebid 3

### PR DESCRIPTION
**Pull request by cciocov**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Upgrade Inskin adapter code for Prebid 3, by removing the use of deprecated functions. No other changes were introduced.

### CODE REVIEW

**Comment by bretg** [comment]
@cciocov - you need to port over your unit tests as well please.

**Comment by GLStephen** [comment]
@cciocov I can test this and approve/merge once you add your unit tests

**Comment by cciocov** [comment]
@GLStephen Just added the unit tests, thanks!

**Comment by GLStephen** [comment]
LGTM merged

**Pull request merged**
