### PR TITLE
quantcastBidAdapter update for 3.0

### LINKED ISSUE #4308: quantcast adapter - Update all end points to https
## Type of issue

Feature Request
## Description

While doing an internal review for point 2 of the adapter’s section of http://prebid.org/blog/pbjs-3, I observed something unusual in your adapter. I saw more endpoints (test url) than the usual bid endpoint and usersync endpoint. Can you clarify on that all these endpoints are needed and whether they can be updated to https protocol or may be you can make the updates yourself?
## Following change need to be addressed:
- All the endpoints or any other thrid party urls used by the adapter needs to be updated to secure (https).
## Platform details

Prebid 3.0
## Other information

http://prebid.org/blog/pbjs-3

### PR DESCRIPTION
**Pull request by dpapworth-qc**
Updates to quantcastBidAdapter for pbjs 3.0. Fixes #4308. 

## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Set endpoints to secure. Use mediaTypes.banner.sizes when sizes field not present.

### CODE REVIEW

**Comment by dpapworth-qc** [comment]
I've merged master to address the issue with tests not being run. Should be good to review now.

**Comment by dpapworth-qc** [comment]
@GLStephen have you had a chance to review this?

**Comment by dpapworth-qc** [comment]
@mike-chowla would it make sense to re-assign the reviewer if @GLStephen isn't available?

**Comment by mike-chowla** [comment]
Apologies for delay.  I was out on vacation.

**Pull request merged**
