### PR TITLE
TargetVideo Bid Adapter: add new adapter

### PR DESCRIPTION
**Pull request by grajzer**
TargetVideo bid adapter

## Type of change
- [ ] Bugfix
- [x] Feature
- [x] New bidder adapte
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
- test parameters for validating bids
```
{
  bidder: 'targetVideo',
  params: {
    placementId: 13232385,
    video: {
      skippable: true,
      playback_method: 'auto_play_sound_off'
    }
  }
}
```

### CODE REVIEW

**Comment by ChrisHuie** [comment]
Docs -> https://github.com/prebid/prebid.github.io/pull/3228

**Comment by ChrisHuie** [comment]
@grajzer can you please add unit testing for this pr

**Comment by umakajan** [comment]
@grajzer it looks like this is a duplicate of `appnexusBidAdapter`. Any reason we are not adding this as an alias here: https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L68?

**Comment by grajzer** [comment]
Hi @umakajan you're right, it's basically a copy. 

Do you want me to update this pull request? Or I should create a new pull request and this should be declined?

**Comment by umakajan** [comment]
I'd opt to create a new PR to keep the commits clean, but either one is fine here.

**Comment by grajzer** [comment]
Hi @umakajan I had issues creating a new separate pull request, and ended up modifying this one. Thank you!

**Review by umakajan — APPROVED** [review]

**Pull request merged**
