### PR TITLE
[Gumgum] Add in-video product line

### PR DESCRIPTION
**Pull request by estavillo**
## Type of change

- [x] Feature

## Description of change

Added support for invideo (non-linear ads) into gumgum's adapter. 

- test parameters for validating bids
```
{
    bidder: 'gumgum',
    params: {
	inVideo: 'ggumtest'
    }
 }

```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/
https://github.com/prebid/prebid.github.io/pull/1926

### CODE REVIEW

**Comment by estavillo** [comment]
Friendly bump.

**Comment by bretg** [comment]
Please add a unit test for this new functionality.

**Comment by wqi1972** [comment]
Please add test parameter for `inVideo` into `gumgumBidAdapter.md`
If possible, add the other 2 missing parameters: `ICV` and `video` as well.

**Comment by wqi1972** [comment]
@estavillo looks there was some problem with code merging for this PR. 
I suggest you close this PR, fork a new branch from prebid:master and do it from scratch.

**Pull request closed without merging**
