### PR TITLE
GumGum: sets mediaType of bidRequest depending on product id

### PR DESCRIPTION
**Pull request by susyt**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Sets mediaType to VIDEO when the product type is found to be video (product 7) or in-video (product 6). Default mediaType is set to BANNER

## Other information

@derberbaby

### CODE REVIEW

**Comment by Rothalack** [comment]
Took 6 tries to get Circleci to pass, but it made it!

Do you think you'd want to make a documentation update for this?

**Comment by susyt** [comment]
thanks @Rothalack! and sure thing! as in make a note that in-video products are considered mediatype video and all else is defaulted to banner?

**Comment by Rothalack** [comment]
The two places I was thinking of were:
https://github.com/prebid/Prebid.js/blob/master/modules/gumgumBidAdapter.md
and
https://docs.prebid.org/dev-docs/bidders.html#gumgum

If I'm understanding correctly, it would be applicable to update those in relation to this change, but I could be wrong!

**Comment by susyt** [comment]
ok updated! the corresponding prebid.github PR is: https://github.com/prebid/prebid.github.io/pull/2551

**Pull request merged**
