### PR TITLE
Prebid Core: targeting keys issue when enableSendAllBids and alwaysIncludeDeals is true

### PR DESCRIPTION
**Pull request by pm-priyanka-deshmane**
## Type of change
- [x] Bugfix

## Description of change
When both the **enableSendAllBids** and **alwaysIncludeDeals** flags are set to **true**, targeting keys for bids without deals have not been passed to the ad server since version 9.16.0.
We suspect that this issue may have been caused by the changes introduced in [PR #12273](https://github.com/prebid/Prebid.js/pull/12273).
Specifically, before checking the value of the alwaysIncludeDeals flag and dealId, we are not checking the value of the enableSendAllBids flag.

## Other information
When below config is set, if there is a bid without deal, targeting keys for that bid were being skipped in adserver call.
```
        enableSendAllBids: true,
        targetingControls: {
          alwaysIncludeDeals: true
        }
```

### CODE REVIEW

**Comment by pm-priyanka-deshmane** [comment]
@dgirardi @patmmccann @jlquaccia Can you review this?

**Review by dgirardi — APPROVED** [review]
Thank you for spotting and fixing this!

**Review by jlquaccia — APPROVED** [review]
LGTM!

**Comment by pm-priyanka-deshmane** [comment]
@jlquaccia Can you merge this PR ?

**Pull request merged**
