### PR TITLE
Update appnexusBidAdapter.js, added adastaMedia as alias

### PR DESCRIPTION
**Pull request by Adasta2019**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by Adasta2019** [comment]
Hello, I noticed that no one has been assigned to review this PR. 
Can you please let me know whether this is the right path to have our adapter listed as an alias of Appnexus one on prebid.org?

**Comment by jsnellbaker** [comment]
@Adasta2019 This is the right location; I just grabbed this PR (as I have the other related PR https://github.com/prebid/Prebid.js/pull/4255 where the similar alias was being removed from another bidder).

I'll take a look into these changes soon and follow-up.

**Comment by Adasta2019** [comment]
@jsnellbaker - Thanks for the prompt reply! Looking forward to getting your feedback on both PR and do not hesitate to let me know if I can do something to speed things up.

**Comment by bretg** [comment]
related to docs pr https://github.com/prebid/prebid.github.io/pull/1501

**Pull request merged**
