### PR TITLE
added CCPA support, gvlid to adform and adformOpenRTB adapters

### PR DESCRIPTION
**Pull request by braizhas**
## Type of change
- [x] Feature
- [x] Refactoring (no functional changes, no api changes)

## Description of change
- added gvlid
- added CCPA support
- send `gdprApplies:false` flag to adserver

- Scope.FL.Scripts@adform.com
- [x] official adapter submission

- https://github.com/prebid/prebid.github.io/pull/1968

### CODE REVIEW

**Comment by braizhas** [comment]
Could somebody review/merge changes?

**Comment by braizhas** [comment]
@prebid/core should I create new PR?

**Comment by jsnellbaker** [comment]
Hi @braizhas 

Sorry about the delay here, I'll take a look over this PR today and follow-up accordingly.

**Comment by braizhas** [comment]
@jsnellbaker thanks!

**Pull request merged**
