### PR TITLE
init GothamAds adapter

### PR DESCRIPTION
**Pull request by supportGothamad**
## Type of change

- [ x] New bidder adapter  

## Description of change

- test parameters for validating bids
```
    {
                bidder: 'gothamads',
                params: {
                        placementId: 'hash',
                    accountId: 'accountId'
                }
            }
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- [ x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by smenzer** [comment]
please remove the `package-lock.json` file from the PR

**Comment by smenzer** [comment]
please also get your tests passing before we review this.

**Comment by supportGothamad** [comment]
Hello @smenzer ! Thank you for your replies! I have fixed your notice. Could you please check my PR.

**Comment by smenzer** [comment]
@supportGothamad the package-lock.json file is still in this PR as a removed file...you need to not commit the file at all. If you're not familiar with git enough to back out the file, I would suggest closing this PR and opening a new one without committing it in the first place.

**Comment by smenzer** [comment]
thanks @supportGothamad ... looks like now your PR includes every change from master branch. Can you rebase on the latest version of master and then force push, should be ok then.

**Pull request closed without merging**
