### PR TITLE
AdHash Bid Adapter: changes to support preroll videos

### PR DESCRIPTION
**Pull request by wyand-sp**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change
Added support to AdHash bid adapter for video prerolls.

## Other information
PR to documentation change: https://github.com/prebid/prebid.github.io/pull/4527

### CODE REVIEW

**Comment by patmmccann** [comment]
@mkendall07 mind taking a look? This is a pretty unique integration and curious for your thoughts.

**Comment by wyand-sp** [comment]
Hey @mkendall07 this was a boolean flag if we want to load the library that helps us render the ad on the page or not. However this functionality is no longer used so I just removed it. I just wanted to stick our changes to the video-related things only. Cheers!

**Comment by wyand-sp** [comment]
Can we have the review finished, please? Or at least a time estimate when will this be done? This functionality is critical for us right now. Thank you!

**Comment by ChrisHuie** [comment]
@wyand-sp can review asap. Can you please pull in recent commits on master because this looks to be failing from a flaky test we reworked?

**Comment by wyand-sp** [comment]
Sure, done.

**Comment by wyand-sp** [comment]
@ChrisHuie all checks have passed with the latest pull from master.

**Comment by wyand-sp** [comment]
@ChrisHuie any update on this review?

**Review by spotxslagle — APPROVED** [review]
LGTM

**Review by mkendall07 — APPROVED** [review]

**Pull request merged**
