### PR TITLE
restrict outstream w/o renderer to PBS

### PR DESCRIPTION
**Pull request by sumit116**
## Type of change

- [x] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
[{
      'code': 'div-gpt-ad-1460505748561-0',
      'sizes': [640, 480],
      'mediaTypes': {
        'video': {
          playerSize: [[ 640, 480 ]],
          context: 'outstream',
          mimes: ['video/mp4']
        },
        banner: { sizes: [[300, 250]] }
      },
      'transactionId': '4ef956ad-fd83-406d-bd35-e4bb786ab86c',
      'bids': [
        {
          'bid_id': '123',
          'bidder': 'appnexus',
          'params': { 'placementId': '12349520' }
        }
      ]
    },
    {
      code: 'video1',
      mediaTypes: {
        video: {
          playerSize: [640, 480],
          context: 'outstream',
          mimes: ['video/mp4']
        }
      },
      bids: [
          {
              bidder: 'appnexus',
              params: {
                  placementId: 13232385,
                  video: {
                      skippable: true,
                      playback_method: ['auto_play_sound_off']
                  }
              }
          }
      ],
      renderer: {
        url: 'http://cdn.adnxs.com/renderer/video/ANOutstreamVideo.js',
        render: function (bid) {
            ANOutstreamVideo.renderAd({
                targetId: bid.adUnitCode,
                adResponse: bid.adResponse,
            });
        }
      }
    }
  ];
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

### CODE REVIEW

**Comment by sumit116** [comment]
@jsnellbaker ,
The below `adResponse` object is required to pass in the renderer.render() to display an outstream video add through Prebid Server.
```
bid.adResponse = {
	"ad": {
		"video": {
			"content": bid.vastXml
		}
	}
}
```

So, now the `renderer` object would look like:
```
renderer: {
                 url: 'http://cdn.adnxs.com/renderer/video/ANOutstreamVideo.js',
                 render: function (bid) {
                    adResponse = {
                        ad: {
                            "video": {
                                "content": bid.vastXml
                            }
                        }
                    }
                    ANOutstreamVideo.renderAd({
                        targetId: bid.adUnitCode, // target div id to render video
                        adResponse: adResponse,
                    });
                  }
              }
```

Can you please review this PR now?

**Comment by sumit116** [comment]
> @sumit116 I think these updates look good.
> 
> Can you put together a docs PR for the updated sample adUnit render code (for when serving from PBS)? The additions would be helpful to note down.

Thanks @jsnellbaker . Docs PR added: https://github.com/prebid/prebid.github.io/pull/1385.

**Comment by spormeon** [comment]
how do you get this "renderer" thing to work with multi boxes?  the docs are non existant and the examples dont show how to do it?

**Comment by sumit116** [comment]
> boxes

@jsnellbaker , do you have any idea about this?

**Comment by jsnellbaker** [comment]
@spormeon Can you please clarify a little further on what you mean?

**Comment by spormeon** [comment]
how do you get a renderer to work with "multi boxes" it just doesnt seem to work?

**Comment by jsnellbaker** [comment]
@spormeon Do you have a page setup where you're trying to get this to work that I can see?  I don't understand the term 'multi boxes' in this context.  Do you mean just having multiple outstream video placements serving together?

**Comment by spormeon** [comment]
prebid "multi-format" my test pages are behind login, so unless i can Pm you its hard to give you it

**Pull request merged**
