### PR TITLE
init new pull request with GothamAds prebid adapter

### PR DESCRIPTION
**Pull request by supportGothamad**
## Type of change

- [ x] New bidder adapter   

## Description of change

- test parameters for validating bids
```
    {
                bidder: 'gothamads',
                params: {
                        placementId: 'hash',
                    accountId: 'accountId'
                }
            }
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ x] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/pull/2599

### CODE REVIEW

**Comment by Rothalack** [comment]
There's an issue with Circleci builds that is being worked out now. Hopefully working soon.

In the meantime, I noticed your indentation in gothamadsBidAdapter.md is inconsistent. I would clean that up. I'm testing now.

**Comment by Rothalack** [comment]
I just noticed in your docs repo PR shows the biddercode as gothamAds and then in your adapter and test code it's using gothamads. I assume that means you should update the dosc PR to show gothamads as the biddercode.

**Comment by supportGothamad** [comment]
Hello @Rothalack  ! Thank you ! I have fixed my docs PR

**Comment by smenzer** [comment]
@supportGothamad if you pull in the latest master branch it should clear up the circleci errors

**Comment by Rothalack** [comment]
Could you provide a placementId and accountId that I could test with?

I'm also getting a CORS policy error. I think it might be related to the "Adapters may not create or trigger any network requests or pixels" rule found [here](https://docs.prebid.org/dev-docs/bidder-adaptor.html#bidder-adaptor-Required-Adapter-Conventions). I'm getting this policy error when attempting to run an auction to test and getting the "no bid request" response from that endpoint.

Access to XMLHttpRequest at 'https://us-e-node1.gothamads.com/bid?pass=asffw1&integration=prebidjs' from origin 'http://localhost:9999' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute utils.js:263

I'm not certain about these, just looking for why I can't get a test to run.

**Comment by supportGothamad** [comment]
Hello, @Rothalack ! Could you please test with the next credentials 

            bids: [{
                bidder: 'gothamads',
                params: {
                    placementId: 'hash',
                    accountId: 'BjoPDyjjw7r5wWRCHMyx'
                }
            }]

**Comment by Rothalack** [comment]
@supportGothamad Please pull in master. It has some tweaks that should fix the circleci build.

**Comment by supportGothamad** [comment]
Hello @Rothalack .. I have merged master branch, but I still have probles with circle ci

**Comment by Rothalack** [comment]
I've tested locally with the fix in the PR that fixes this circleci problem. I'm confident in your changes, merging!

**Pull request merged**
